### ISSUE TITLE
Mercedes AMG GT-S 

### ISSUE THREAD

**Issue by FkknAlpha** [fkk-cz/noire_vehicles#100]
I know you buffed it a little, but is there any way to make the performance and sound the same as the regular GT ? The regular GT sounds way more beefy and tops over 220 + , and the GT-S struggles to get to 170

**Comment by DankGrandma** [comment]
depends on if we wanna buff the GT-S or nerf the GT. 
fInitialDragCoeff value; fInitialDriveForce; fInitialDriveForce; fClutchChangeRateScaleUpShift; fClutchChangeRateScaleDownShift; fInitialDriveMaxFlatVel are all lower than on the GT version

audioNameHash SCHLAGEN is what the GT uses, swap from the feltzer2 audiohash to fixaroo that one

**Comment by fkk-cz** [comment]
> 
> 
> depends on if we wanna buff the GT-S or nerf the GT.
> fInitialDragCoeff value; fInitialDriveForce; fInitialDriveForce; fClutchChangeRateScaleUpShift; fClutchChangeRateScaleDownShift; fInitialDriveMaxFlatVel are all lower than on the GT version
> 
> audioNameHash SCHLAGEN is what the GT uses, swap from the feltzer2 audiohash to fixaroo that one

decided to nerf the GT and have both vehicles use the same handling
