### ISSUE TITLE
2014 Lamborghini hurricane LB, 2022 Porsche Panamera turbo s.

### ISSUE THREAD

**Issue by Cruzamp** [fkk-cz/noire_vehicles#1000]
They display NULL in the garage and in my house as well.

**Comment by fkk-cz** [comment]
Both vehicles fixed, forgot to set `gameName` to the corresponding model name. https://github.com/fkk-cz/noire_vehicles/commit/ef4dbefcc455cd40fd16cc555aee6d836d14c49c
