### ISSUE TITLE
Gooseneck flipping/glitching

### ISSUE THREAD

**Issue by glefave0209** [fkk-cz/noire_vehicles#1003]
Can we have the ability to flip Goosenecks.?  Something reasonable that would require maybe 4 people to do it

Although the recent improvements have helped a ton in the mines, the goosenecks are still very touchy and the ability to flip them would be a huge relief for the mining community and likely a relief for DOT/PD/assist from the requests

It would also be great for the immersion to see how well it would work in the mines.  I'm confident the majority of us would help out the cause when needed

**Comment by fkk-cz** [comment]
Moved this to the vehicle repo - one obvious but overlooked solution to help mitigate the trailer flipping issue is to adjust the current trailer handling metas. Made a few adjustments in https://github.com/fkk-cz/noire_vehicles/commit/eaba611d1b9d1f224ea96de8342b84c032de4c3d which will help with these commonly observed issues:
- Trailer getting destroyed or completely burned
- Small trailer is extremely easy to flip over - was using the `BOATTRAILER` handling which has an extremely soft suspension and can sway a lot, making it more likely to do so
- Lowered center of gravity offset for the gooseneck trailer to hopefully stabilize the vehicle more

Testing will need to be done to see whether these changes result in any significant improvements. Not sure whether the `CTrailerHandlingData` adjustments are even correct, I only compared to existing trailer handling metas from the mpgunrunning DLC.

**Comment by glefave0209** [comment]
> > when trailers glitch it's a user error; however, there's a lot of residual effects from this because it's very tight in the mines/sell mines. One guy glitches his trailer and then takes out 2-3 bystanders.. Or somebody trying to reflip their trailer by ramming it takes out somebody else
> 
> Which one is it, a bug or user error? The only known issue I've seen is where the trailer is attached incorrectly (not aligned properly) to the vehicle but cannot be detached unless another vehicle is used to detach it. Refer to [fkk-cz/noire-public#359](https://github.com/fkk-cz/noire-public/issues/359).
> 
> People driving their vehicles poorly or too fast is not a valid use case for flipping trailers. There is no elegant solution for such, the best case scenario will involve expanding the insurance system or giving DOT the sole ability to move vehicles. Civilians who drive poorly should have to suffer the consequences instead of misusing `/assist` and asking staff to come and delete their flipped vehicles.

Apologies, I guess I'm doing a poor job explaining the problem.  User error causes the glitch, so as you said, somebody forgetting to detach a trailer, but afterwards, that persons trailer will take out innocent bystanders, tip their trailers, explode them etc.  I know there are a lot of clowns that are reckless, but there is an amazing community of professional miners that all respect the rules and play a team game.  We take on a lot of residual effects from other players bad decisions.  That's all I was trying to say in terms of getting us a way to fix (essentially) somebody else's problem

The adjustments should help greatly though.  Thank you so much for that!.  I think those 3 adjustments will make a huge difference for us.  I (we) will keep you updated on the changes and how they effect our day-to-day in the mines

**Comment by fkk-cz** [comment]
Adjusted the trailer handling again in https://github.com/fkk-cz/noire_vehicles/commit/8b6826bebbb509cb1bafd8a994e96bbacd70bc8d. No idea how the game calculates the towing vehicle's top speed and acceleration, my guess is the vehicle and trailer's mass is involved. For example, the `19ramdonk` seems to have a much harder time pulling a `trailercar` compared to the `nissantitan17`. Lowered the mass of the trailer to real life values which could fix this issue.

**Comment by fkk-cz** [comment]
Closing this and merging with https://github.com/fkk-cz/noire_vehicles/issues/1005.
