### ISSUE TITLE
Trailer issues with latest change and trunk change

### ISSUE THREAD

**Issue by mattny0608** [fkk-cz/noire_vehicles#1005]
Trailers are having speed issues and handling issues with the latest change, on top of that I hope the not being able to use a trunk unless you have the keys can be readdressed. I wanted to submit a business plan for use in the mines and request a couple of things be added there just was still working on the document. I have already been running business out of the mines with minimal bugs and issues after obtaining my business license. This change to the trunks completely destroys my business as well as makes it difficult for people who play together with their friends and store stuff in each other’s vehicles. Either that or can we give out copies of our keys so people can still access (this is not a preferred fix but at least solves both my issues listed above) I would like to still submit my business plan and possibly request small changes in the mines. I will finish typing it up when I get home from work tonight and submit that not sure if that will help with the decision about these changes or not.

**Comment by SimonGhostRiley1** [comment]
Same issues for me as well.

**Comment by iGotDank** [comment]
> 

I personally love the idea of having the trunks only accessible by people with keys. It’ll ward out all the trolls who come up there. A major problem I see right away with having multiple sets of keys is person A rents out car/rig to person B. Person A gives a set of keys and then maliciously goes and takes back the car/rig because they still have the keys for it, I could totally see that happening thus not actually fixing the problem; just removing and creating another one

**Comment by glefave0209** [comment]
The tweak caused owners of vehicles to be restricted to accessing their own trunks in safezones

You can be the owner of the car, with keys in hand and not be allowed in your own trunk in the mines

**Comment by xFooliee** [comment]
I mean its real life, maybe we could do something about the trailer stealing but as far as trunk and stuff goes, if you dont like it then thats on you tbh. Seems like everyone wants to milk the RP cuz they are victims but thats apart of life

**Comment by mattny0608** [comment]
> I mean its real life, maybe we could do something about the trailer stealing but as far as trunk and stuff goes, if you dont like it then thats on you tbh. Seems like everyone wants to milk the RP cuz they are victims but thats apart of life

I am not sure what you're referencing? Are you countering one of my points or? Just trying to be transparent and will happily debate

**Comment by xFooliee** [comment]
Im responding to dudes comment about the trunk being only accessible to whoever has keys. I aint coming at nobody im js. Idk if this is like a directional respond thing or what im new to this i just typed in the box below

**Comment by fkk-cz** [comment]
The issue of not being able to open trunks in safezones even with keys has been fixed.

> This change to the trunks completely destroys my business as well as makes it difficult for people who play together with their friends and store stuff in each other’s vehicles. Either that or can we give out copies of our keys so people can still access (this is not a preferred fix but at least solves both my issues listed above)

What would be the purpose of having multiple people mining into the same vehicle? That is an inefficent use of storage and does not increase your yield, regardless of how many people are involved.

This change was implemented because we're simply tired of receiving half a dozen assists **daily** for the same thing. Hopefully once the handling is tweaked and dialed in correctly trailer flipping will be very rare and not much of an issue.

**Comment by xFooliee** [comment]
> The issue of not being able to open trunks in safezones even with keys has been fixed.
> 
> > This change to the trunks completely destroys my business as well as makes it difficult for people who play together with their friends and store stuff in each other’s vehicles. Either that or can we give out copies of our keys so people can still access (this is not a preferred fix but at least solves both my issues listed above)
> 
> What would be the purpose of having multiple people mining into the same vehicle? That is an inefficent use of storage and does not increase your yield, regardless of how many people are involved.
> 
> This change was implemented because we're simply tired of receiving half a dozen assists **daily** for the same thing. Hopefully once the handling is tweaked and dialed in correctly trailer flipping will be very rare and not much of an issue.

Ive seen multiple people mine into the same car or work together in mining to make the process quicker, that or some people will have 1 who mines and the other drops off and then switch each run.

**Comment by mattny0608** [comment]
> The issue of not being able to open trunks in safezones even with keys has been fixed.
> 
> 
> 
> > This change to the trunks completely destroys my business as well as makes it difficult for people who play together with their friends and store stuff in each other’s vehicles. Either that or can we give out copies of our keys so people can still access (this is not a preferred fix but at least solves both my issues listed above)
> 
> 
> 
> What would be the purpose of having multiple people mining into the same vehicle? That is an inefficent use of storage and does not increase your yield, regardless of how many people are involved.
> 
> 
> 
> This change was implemented because we're simply tired of receiving half a dozen assists **daily** for the same thing. Hopefully once the handling is tweaked and dialed in correctly trailer flipping will be very rare and not much of an issue.
> 
> 
> 
> 

As the guy above me said, lots of people work together in the mines to fill one rig and make the fill take a lot less time, then they can stay there filling the next as the first person goes to sell. I've made a lot of money in the course of a week between my team and me a lot more than we would have made if we were doing it alone

**Comment by xFooliee** [comment]
Respectfully I think what would REALLY help calm a lot of these issues down would be fixing where people shouldn’t have to unhitch their trailer…you fix that and you will have a lot less crimes of stealing someone’s rig. Literally at that point no one can hotwire/lockpick in a safe zone, all you have to do is lock your door and you’re fine. Otherwise when you unhitch i have seen people ram vehicles out of the way or simply just back in and take off, and it’s not like its something that we can control, we literally have to unhitch otherwise our trucks will glitch. I say you fix that, and u will fix the problem.

**Comment by Kraezia** [comment]
In my humble opinion, i think this tweak was implemented just to please the crowd who are too lazy or absent minded to actually lock there vehicles.  This server is supposed to be "Heavy RP", yet you are taking out a realistic function, such as being able to open the trunk to any car assuming its unlocked.  I understand why this tweak was implemented, but i sincerely hope it gets reworked.

**Comment by xFooliee** [comment]
> In my humble opinion, i think this tweak was implemented just to please the crowd who are too lazy or absent minded to actually lock there vehicles. This server is supposed to be "Heavy RP", yet you are taking out a realistic function, such as being able to open the trunk to any car assuming its unlocked. I understand why this tweak was implemented, but i sincerely hope it gets reworked.

EXACTLY, its like someone complaining that when they crash, their car dies. Its RP thats the whole point but def a few tweaks could be made

**Comment by fkk-cz** [comment]
> Respectfully I think what would REALLY help calm a lot of these issues down would be fixing where people shouldn’t have to unhitch their trailer…you fix that and you will have a lot less crimes of stealing someone’s rig.

What? I'm talking about people stealing out of **trunks**, not stealing the entire trailer itself.

> Literally at that point no one can hotwire/lockpick in a safe zone, all you have to do is lock your door and you’re fine.

Again, that doesn't solve the problem. I've seen multiple assists/reports in just the last few days showing people walking up to other people's vehicles and attempting to steal items in a safezone, in between the vehicle owner locking and unlocking the trunk. This [race condition](https://en.wikipedia.org/wiki/Race_condition) is obviously undesirable and bad design, and only hurts the honest player who is trying to get in and out selling their mined items.
