### ISSUE TITLE
2014 Lamborghini hurricane LB please fix handling?????? 

### ISSUE THREAD

**Issue by Cruzamp** [fkk-cz/noire_vehicles#1006]
At low speed it sits there and spins. And when you try to turn while on the throttle it has under steer, it just keeps going strait.  And it's just way to slippery. Plus the brakes are non existent. You have to like press them 5 minutes before you wanna turn.

**Comment by Cruzamp** [comment]
Maybe make it the same handling as the senna?? maybe a little better because its a wider car than the senna??

**Comment by PreacherDeimos** [comment]
I wanted this car so badly but I was so disappointed with how it handled. Literally like it's on ice.

**Comment by Cruzamp** [comment]
I know bro. You can't even turn now it's literally impossible to drive.  Around a turn it just goes strait. And in power it just spins out all the time. It need hella fixing.

**Comment by fkk-cz** [comment]
Fixed in https://github.com/fkk-cz/noire_vehicles/commit/68b05d204d6a5a3c908e465ab283b1a38a7a14c2.
