### ISSUE TITLE
2020 Ferrari Monza SP2 Texture Issues

### ISSUE THREAD

**Issue by ItsGabble** [fkk-cz/noire_vehicles#1007]
2020 Ferrari Monza SP2 has big texture issues rn. The Ferrari emblems are missing, the headlights change color, the tail/brake light is sometimes transparent and changes colors when driving, wheel and wheel well textures are scuffed when driving and wheels shutter when parked. 
![image](https://user-images.githubusercontent.com/102539785/165791950-4a4cf4f2-168e-4b33-bf29-28b92efdc573.png)
![image](https://user-images.githubusercontent.com/102539785/165792025-f87b7af0-9d18-41b6-967e-99b15a6493d7.png)
![image](https://user-images.githubusercontent.com/102539785/165792066-0bd6105f-e0e6-4b13-b1a0-52553d67163b.png)
![image](https://user-images.githubusercontent.com/102539785/165792143-6463573d-c772-4d6b-9d8f-68ade6ef876f.png)
![image](https://user-images.githubusercontent.com/102539785/165792245-73ed86c8-39c7-4036-8e2a-aacaa207726a.png)

**Comment by ItsGabble** [comment]
Following up on this- would a new car have to be imported for this to be fixed? Trying to get an idea of what to expect

**Comment by fkk-cz** [comment]
Looks like this texture dictionary got fucked up when converting. Oddly enough, I don't have the .ytd in my backup folder.

Redownloaded the vehicle and replaced the textures, it should be fixed on next reset.
![image](https://user-images.githubusercontent.com/74131024/168450241-b057752b-a46e-485a-826a-26057f8334f1.png)
