### ISSUE TITLE
Chevrolet Corvette C8 MANSAUG

### ISSUE THREAD

**Issue by EncrustMust** [fkk-cz/noire_vehicles#1009]
Needs acceleration and top speed increase (non supporter c8 is way faster which doesn’t make sense)
Brake power needs increased
Needs the non supporter c8 audio put on it

**Comment by cxerq** [comment]
> Needs acceleration and top speed increase (non supporter c8 is way faster which doesn’t make sense) Brake power needs increased Needs the non supporter c8 audio put on it

What is the current top speed of it?

**Comment by fkk-cz** [comment]
https://github.com/fkk-cz/noire_vehicles/commit/997f8cb800414de076aab6ff4214a41f8efa1eeb
