### ISSUE TITLE
2003 Porsche Carrera GT

### ISSUE THREAD

**Issue by CallsignDeadshot** [fkk-cz/noire_vehicles#1010]
The braking on the vehicle seens to be absolutely non existant, the vehicle would slide and drop 10mph every second and a half. Now if you were going 100mph, it would take more than 10 seconds to stop which is pretty much undrivable.

**Comment by fkk-cz** [comment]
https://github.com/fkk-cz/noire_vehicles/commit/a27f4df2216e008f5485381355c176253ffef5c8
