### ISSUE TITLE
Ram 3500 Flatbed door & passenger issue

### ISSUE THREAD

**Issue by Chitowndevil21** [fkk-cz/noire_vehicles#1012]
I don't know if anyone else has noticed this but the doors on this vehicle no longer work & only the driver can get in, this is a 4 door. Just wondering if this could be looked into & corrected. This worked fine when the vehicle was first purchased.

**Comment by No-Yes1** [comment]
I'm unsure why this is the case, I looked at the layouts and it was the correct layout type. I've tweaked it and will see if it changes. https://github.com/fkk-cz/noire_vehicles/commit/f4d7c300fb20fa5d21ec545a9ad352b429192fd5. Please wait until this is merged.
