### ISSUE TITLE
Sound & Dirtmapping

### ISSUE THREAD

**Issue by PreacherDeimos** [fkk-cz/noire_vehicles#1014]
A few days ago I purchased the 2021 BMW M4 Competition car after knowing what it sounds like in real life and getting really excited to own it, I was quite let down with how quiet it is. So I simply request that you please just turn the volume up on the vehicle to make it not sound so quiet as it's a Competition Track car.

My second part to this inquiry is the dirtmapping, I've been told by Ty McNugget and Lenny Nelson that you can request to have it tweaked or removed? Please change it at least, as it stands the vehicle is literally covered in mud within 30 seconds as if you just took it to a Rally course, thank you so much for your hard work and continuous development. 

If you're interested down below I will display a video of it's sound in the game vs. real life.

Audio of how quiet it is in game: https://www.youtube.com/watch?v=YP_mrCBePcY

Short clip of real life sound level :  https://www.youtube.com/watch?v=cGuacgfEc48&t=4s

**Comment by iGotDank** [comment]
Did you not test it before buying it? Just curious

**Comment by tythetanman** [comment]
https://www.gta5-mods.com/vehicles/bmw-g82-m4-competition-sound

That sounds should be able to work with that exact model is the closest thing I can find that goes with the competition M4’s.

**Comment by PreacherDeimos** [comment]
> Did you not test it before buying it? Just curious

I did test it, I was just too excited with how fast it got to pay attention to the sound and dirtmapping, thanks for your question.

**Comment by PreacherDeimos** [comment]
> 

Thank you Ty.

**Comment by tythetanman** [comment]
Will get one and re submit.

**Comment by PreacherDeimos** [comment]
> 

https://www.gta5-mods.com/vehicles/m5-sound-mod

**Comment by No-Yes1** [comment]
we already have this in -game, so more then happy to swap the audio hash for it

**Comment by No-Yes1** [comment]
https://github.com/fkk-cz/noire_vehicles/commit/c791e51d131ad1f7afaa14e0aea0c5f00e23d79f - Leaving open for the dirt mapping issue as I need to take a look into it

**Comment by tythetanman** [comment]
Interesting part is the Lamborghini Huracan EVO actually has the same dirt mapping issue you just drive it for a few feet and it feels like you went through the rough mud of the swamps.

**Comment by No-Yes1** [comment]
> Interesting part is the Lamborghini Huracan EVO actually has the same dirt mapping issue you just drive it for a few feet and it feels like you went through the rough mud of the swamps.

Just tested the hevo, there was no mud when testing on road, maybe on dirt but that's to be assumed?

**Comment by No-Yes1** [comment]
> A few days ago I purchased the 2021 BMW M4 Competition car after knowing what it sounds like in real life and getting really excited to own it, I was quite let down with how quiet it is. So I simply request that you please just turn the volume up on the vehicle to make it not sound so quiet as it's a Competition Track car.
> 
> My second part to this inquiry is the dirtmapping, I've been told by Ty McNugget and Lenny Nelson that you can request to have it tweaked or removed? Please change it at least, as it stands the vehicle is literally covered in mud within 30 seconds as if you just took it to a Rally course, thank you so much for your hard work and continuous development.
> 
> If you're interested down below I will display a video of it's sound in the game vs. real life.
> 
> Audio of how quiet it is in game: https://www.youtube.com/watch?v=YP_mrCBePcY
> 
> Short clip of real life sound level : https://www.youtube.com/watch?v=cGuacgfEc48&t=4s

https://github.com/fkk-cz/noire_vehicles/commit/b5ca960de1c4003e9f0e2b1a58441181b722829a. Tweaked the dirtLevel values which hopefully should remove the dirt on the vehicle. If this does not work then it'll have to be a native change. the sound change has already been implemented/changed. Please wait for this change to come into effect.
