### ISSUE TITLE
Hayabusa

### ISSUE THREAD

**Issue by Drtidepod420** [fkk-cz/noire_vehicles#1017]
can we get are civ bikes as in the hayabusa to match the speed as the highway BMW cause irl hayabusas are one of the fastest bikes in the world

**Comment by fkk-cz** [comment]
![image](https://user-images.githubusercontent.com/74131024/166853886-4b1591bf-e471-4251-a624-7a2f9728d5d8.png)

What's the current top speed?

**Comment by cxerq** [comment]
> ![image](https://user-images.githubusercontent.com/74131024/166853886-4b1591bf-e471-4251-a624-7a2f9728d5d8.png)
> 
> What's the current top speed?

I own this bike and can confirm you can get to at least 190 if you go onto a wheelie!
