### ISSUE TITLE
Tweak Ferrari 458 Prio?

### ISSUE THREAD

**Issue by xZedys** [fkk-cz/noire_vehicles#1019]
The Ferrari 458 prio goes about 180 top speed, could there possibly be a slight buff? I don't know of a Ferrari topping out at 180. If not all good, thank you FKK appreciate everything you do for the city.

**Comment by xZedys** [comment]
The Ferrari 458 can hit 202 top speed. I think all 458's including prio should be looked at

**Comment by cxerq** [comment]
> The Ferrari 458 can hit 202 top speed. I think all 458's including prio should be looked at

I submitted the change for the 458 prio change, if it get approved it should hit 202, for the others the 458 Italia is fine idk the other one to look at!

**Comment by fkk-cz** [comment]
Merged https://github.com/fkk-cz/noire_vehicles/pull/1021. Will take effect on next reset (as always).

@xZedys can confirm whether this helped.

**Comment by xZedys** [comment]
> Merged #1021. Will take effect on next reset (as always).
> 
> @xZedys can confirm whether this helped.

I took it on the highway only reached a top speed of 182 mph

**Comment by No-Yes1** [comment]
> > Merged #1021. Will take effect on next reset (as always).
> > @xZedys can confirm whether this helped.
> 
> I took it on the highway only reached a top speed of 182 mph

I'll take a look later.

**Comment by fkk-cz** [comment]
Turns out I forgot to pull changes last night. Should be good tomorrow.

**Comment by No-Yes1** [comment]
@xZedys Can you confirm whether this is now fine?

**Comment by xZedys** [comment]
> @xZedys Can you confirm whether this is now fine?

I just tested it, and there is no difference tbh still the same speed

**Comment by No-Yes1** [comment]
Which 458 is it, the itala/prior/specialate

**Comment by cxerq** [comment]
> Which 458 is it, the itala/prior/specialate

I was the one who made the change i and fucked up! I changed the Special not the Prior as i thought the Special was the prior :( My bad chief

**Comment by No-Yes1** [comment]
All good. I'll amend it in a second.

**Comment by No-Yes1** [comment]
Tweaked the right model name this time. https://github.com/fkk-cz/noire_vehicles/commit/d6d2242b1d2efcc03a81782da45480bba64979a3. Reverted the other 458 then was changed in error. https://github.com/fkk-cz/noire_vehicles/commit/d80487816c28506d941bf51c7287303dddee4107

**Comment by xZedys** [comment]
> Which 458 is it, the itala/prior/specialate

Yeah it was the prior

**Comment by xZedys** [comment]
> Tweaked the right model name this time. [d6d2242](https://github.com/fkk-cz/noire_vehicles/commit/d6d2242b1d2efcc03a81782da45480bba64979a3). Reverted the other 458 then was changed in error. [d804878](https://github.com/fkk-cz/noire_vehicles/commit/d80487816c28506d941bf51c7287303dddee4107)

Just took a test drive on it, only hitting 184 mph i'd say it still needs tweaked some more

**Comment by No-Yes1** [comment]
184mph is fine. Please refer to this comment:

[fkk-cz](https://github.com/fkk-cz)
[2 days ago](https://github.com/fkk-cz/noire-public/discussions/801#discussioncomment-2704172)
Maintainer
Going to put this out there - what's the difference between 190 mph and 200 mph besides 10 mph? Rhetorical question obviously.

As stated above, no one without a death wish would ever attempt to drive these speeds on a public road. One pothole or bad stretch of road would blow out your tire or suspension, not to mention make you lose control and wreck your $300k supercar. Unfortunately GTA (or any game to my knowledge) doesn't simulate bad road conditions very well, if at all. Additionally, vehicles that can reach such speeds should be completely ineffective off road and take a lot of damage -- I can think of quite a few scenarios where I've seen people launch a Ferrari up a mountain and keep driving.

We will not be making these trivial changes to vehicles' top speeds unless they're significantly broken _(>10% speed diff.)._ The same applies to people asking for vehicles to go 220-230 mph+. No vehicle in the city should be easily reaching those speeds.

For anyone who thinks a vehicle that can 'only' go 180 mph is slow, I'd suggest you try driving that speed on a U.S. highway sometime -- then come back and tell me it's too slow.
