### ISSUE TITLE
porsche taycan

### ISSUE THREAD

**Issue by veprezy** [fkk-cz/noire_vehicles#102]
the top speed is slow only 134 i think it should do like 150 seeing as in irl it does 167

**Comment by DankGrandma** [comment]
since the fInitialDragCoeff value is 1, the fix should be to change fInitialDriveMaxFlatVel value to 200.
the 200 is not MPH. to find the MPH based off fInitialDriveMaxFlatVel value times it by .82, that should give you a top speed (in this case) of 164

**Comment by fkk-cz** [comment]
it's a 199k car, 167 would be unbalanced
