### ISSUE TITLE
2016 NSX

### ISSUE THREAD

**Issue by TheRealKovuu** [fkk-cz/noire_vehicles#1023]
I’ve noticed topics of car speeds and realized the 2016 NSX should be topping out at about 190-191 mph but a fully maxed out NSX barely clears 160. Is there anything we could do to slightly buff the speed?
![F56D2585-C843-490C-BC06-50C53BC7E504](https://user-images.githubusercontent.com/103857121/166877219-74ece077-f96d-4605-8252-cadab83f4e7c.png)

**Comment by cxerq** [comment]
Upped the top speed once accepted should go about 190!
