### ISSUE TITLE
Ferrari 488 Pista

### ISSUE THREAD

**Issue by landerssonn** [fkk-cz/noire_vehicles#1026]
The Ferrari 488 Pista fully maxed out with top speed 170-180 is too slow. i want a slight buff because the picture below shows that it should be 211mph.
![Ferrari 488 Pista](https://user-images.githubusercontent.com/104997947/166948237-b995b26b-31a3-422b-854a-78c2ce6622ac.png)

**Comment by cxerq** [comment]
> i want a slight buff

Oh My you could have said is there a chance the top speed gets looked at not I WANT IT BUFFED

**Comment by landerssonn** [comment]
is there a chance the top speed gets looked at

**Comment by No-Yes1** [comment]
Tweaked slightly: https://github.com/fkk-cz/noire_vehicles/commit/7320932013a7e776884507e651beae1fc8325bc4.
