### ISSUE TITLE
Mclaren Senna Top Speed

### ISSUE THREAD

**Issue by TdotG** [fkk-cz/noire_vehicles#1029]
Car is 715k which is painfully expensive. Barely hits 200. Would like for the Top speed to be raised to much more than 200.

**Comment by Scubaaaaa** [comment]
McLaren says the Senna is capable of going from zero to 60 mph in 2.7 seconds. Top speed is 208 mph.

**Comment by apricates** [comment]
yup the senna is pretty slow now and the dodge demon goes faster than it

**Comment by TdotG** [comment]
My point exactly. Demon is half the price of the senna and is faster. Basically a waste of 715k plus the upgrades only for it be slower than a car that is half the price and could even bought much cheaper used.

**Comment by Scubaaaaa** [comment]
What I said above is what Mclaren said about the car IRL. That's not in city

**Comment by QuintenM911** [comment]
the Senna hits 208 in perfect conditions and the demon hits 211 so your point doesn't make sense the vehicle performs as it should

**Comment by TdotG** [comment]
If we’re talking about IRL top speeds a demon isn’t going to hit 211 unless it’s on slicks/semi-slicks, a prep surface, a flat runaway. There’s multiple variables.

**Comment by fkk-cz** [comment]
> If we’re talking about IRL top speeds a demon isn’t going to hit 211 unless it’s on slicks/semi-slicks, a prep surface, a flat runaway. There’s multiple variables.

Then it should get adjusted. 200 MPH is sufficient for any supercar in here.
