### ISSUE TITLE
Rimac buff--no noticeable change

### ISSUE THREAD

**Issue by MinoritySanta** [fkk-cz/noire_vehicles#1039]
Was told to open new request.  Still tops out at 182.  Per video... Lots of room on the airstrip and won't push past 181-182 mph

https://youtu.be/9oxMse28_MQ

**Comment by No-Yes1** [comment]
Tweaked it again https://github.com/fkk-cz/noire_vehicles/commit/70f191894762372e9c4933d306c409bd630d5086. Please wait until this is merged.

**Comment by glefave0209** [comment]
I'm not sure if this was forgotten about.  Top speed still 182

**Comment by MinoritySanta** [comment]
Still 182 mph after recent merge.  Can we try another handling tweak or possibly just bump top speed. Thanks!

**Comment by MinoritySanta** [comment]
Hello. Just wanted to follow up on this as was last commented 8 days ago. Maybe fell through the cracks

**Comment by No-Yes1** [comment]
Attempted _another_ fix for the rimac. https://github.com/fkk-cz/noire_vehicles/commit/25201d2ef51b9025f1c2eb46ea1f42e29e9a5625. Please wait until this is merged.

**Comment by MinoritySanta** [comment]
Doesn't appear the tweaks are working for top speed. Still maxes at 183. I know it shows 199 mph but can we just ramp it to 230mph so it's fixed?  If it only goes 210 after that, that's fine, it just doesnt appear the handling tweaks are working as intended so maybe the quicker fixed is just to adjust top speed?

**Comment by RichieRockefeller** [comment]
> Doesn't appear the tweaks are working for top speed. Still maxes at 183. I know it shows 199 mph but can we just ramp it to 230mph so it's fixed?  If it only goes 210 after that, that's fine, it just doesnt appear the handling tweaks are working as intended so maybe the quicker fix is just to adjust top speed?

I agree Santa, I purchased a Rimac and the car is great but a top speed bump and a handling tweak would make it more reasonable for a $2 mil car.

**Comment by No-Yes1** [comment]
Trying one last fix, if not then marking as wontfix.

**Comment by No-Yes1** [comment]
![Desktop Screenshot 2022 06 11 - 21 59 03 23](https://user-images.githubusercontent.com/79383480/173204688-e6692bb9-732c-4e56-89c2-462529965bbd.png)

Done - 200mph on the dot, due to the unnecessary speed/acceleration that somehow can't be touched, the armour will be touched too, to ensure people don't just buy the vehicle to run away from cops 24/7.

**Comment by No-Yes1** [comment]
Fixed in https://github.com/fkk-cz/noire_vehicles/commit/c0cb7a7b2cabfb0e6aaaf650104be5d28250b656. Please wait for this to merge live.

**Comment by MinoritySanta** [comment]
Santa would never run from the police! 😂

Thank you, Sir. Appreciate your hard word on this one
