### ISSUE TITLE
Dodge Challenger Hellcat tweek

### ISSUE THREAD

**Issue by Howie98** [fkk-cz/noire_vehicles#104]
Dodge Challenger Hellcat too slow, realistic speed is 203mph but in game its about 145mph, please fix this.  
![Screenshot (4)](https://user-images.githubusercontent.com/81951998/113546546-31fc3500-95ba-11eb-8e32-406d374e109f.png)

**Comment by Howie98** [comment]
Its a supporter vehicle too so it should be faster

**Comment by DankGrandma** [comment]
raising fInitialDriveForce value a few tenths and lowering fInitialDragCoeff value to about 3 might help

**Comment by ImDead48** [comment]
He likes to have some cars irl to have accurate speeds. Yes it hits 203 without the speed limiter. But with the speed limiter it only hits 160 around there irl.
