### ISSUE TITLE
2014 Lamborghini hurricane LB Handling.

### ISSUE THREAD

**Issue by Cruzamp** [fkk-cz/noire_vehicles#1040]
It's almost there!! The takeoff is way better now. But on higher speeds it's slippery. Like when you try turning while on the power you ether spin out or you slide and keep going strait. There is like no traction while you are turning and going like 70+.   I can add a clip later.

**Comment by No-Yes1** [comment]
Tweaked in https://github.com/fkk-cz/noire_vehicles/commit/c531e4e2266eedc1deaa3aa5c6bf81e1432bbbb2. Please wait until this is merged.
