### ISSUE TITLE
Mclaren Senna

### ISSUE THREAD

**Issue by apricates** [fkk-cz/noire_vehicles#1041]
So yall are just keeping the Senna at a slow speed? I dont understand how a demon and a charger that is 90k go the same speed as a 715k Mclaren Senna....not understanding why yall closed the last last ticket. If yall talkng about perfect "conditions" then nerf the chargers to go only 180 mph max instead of 201 mph. The aventador s goes 215mph in city and IRL top speed is 217 while the Senna IRL speed is 208 but in city barely pushes 190 going on the highway WITH bumps.

**Comment by No-Yes1** [comment]
let's drop the attitude. 

[fkk-cz](https://github.com/fkk-cz) commented [11 hours ago](https://github.com/fkk-cz/noire_vehicles/issues/1029#issuecomment-1119341183)
If we’re talking about IRL top speeds a demon isn’t going to hit 211 unless it’s on slicks/semi-slicks, a prep surface, a flat runaway. There’s multiple variables.

Then it should get adjusted. 200 MPH is sufficient for any supercar in here.

What Chargers go 201mph?

**Comment by TdotG** [comment]
Just a suggestion, buff the top speed of the senna if possible. I don’t think 4-Door/2-Door vehicles should be anywhere near the top speed of super cars. Most of the super cars are above 300k which isn’t cheap by any means. If you’re paying a premium(500k and above) for a vehicle it should be noticeably faster then the cars below that price. The acceleration on the super cars are on point, but it’s the top speeds should be adjusted accordingly.

**Comment by No-Yes1** [comment]
That still doesn't answer my question, what charger(s) go 201mph, since that needs to be adjusted/tweaked.

**Comment by glefave0209** [comment]
Just to chime in on the Dodge "haters".  This is what Dodge does.  Hellcat and Demon were historical vehicle launches in terms of Horsepower/MSRP

Hellcats and Demons can keep up with supercars on a straight line.  A Demon is 800+ horsepower.  A hellcat is 707 horsepower.  The reason they are "cheaper" is because everything else about the car sucks.  Handling, cornering, center of gravity, weight etc etc

Hellcat Charger IRL top speed is 203 MPH.  Demon Challenger top speed is 211 MPH. 

Stop the hate! lol

**Comment by TdotG** [comment]
> Just to chime in on the Dodge "haters". This is what Dodge does. Hellcat and Demon were historical vehicle launches in terms of Horsepower/MSRP
> 
> Hellcats and Demons can keep up with supercars on a straight line. A Demon is 800+ horsepower. A hellcat is 707 horsepower. The reason they are "cheaper" is because everything else about the car sucks. Handling, cornering, center of gravity, weight etc etc
> 
> Hellcat Charger IRL top speed is 203 MPH. Demon Challenger top speed is 211 MPH.
> 
> Stop the hate! lol

I don’t ever remember saying anything bad about the Hellcat/Demon I’m very well aware the power they make. All I suggested was to buff the top speed slightly of Senna.

**Comment by No-Yes1** [comment]
Tweaked the Senna slightly so it goes 200mph https://github.com/fkk-cz/noire_vehicles/commit/9e5cdcbe2797614c437011a2e63906ed7bd9dd26. No vehicles so really be exceeding 200mph unless over 1M. Gives players more reason on wanting to grind a nice handling vehicle etc etc. Please wait until this is merged.
