### ISSUE TITLE
2018 Aston Martin DBS

### ISSUE THREAD

**Issue by ChirpyMedusa** [fkk-cz/noire_vehicles#1042]
Ever since DSC was dropped, this car has lost about 60-80mph in its top speed. On a completely flat surface, and I did test this on the test track, the car barely reaches 155mph. For its price at over $345k and its previous speed, I believe this car should get a buff. Thanks.

**Comment by No-Yes1** [comment]
DSC wasn't even meant for speed boost reasons.

**Comment by ChirpyMedusa** [comment]
I totally understand that but at the same time the IRL speed of this vehicle is 211mph and it's not hitting anywhere near that currently.

**Comment by No-Yes1** [comment]
https://github.com/fkk-cz/noire_vehicles/blob/725d27ce9a2a221f45dac4b7500dfab934fa739f/DATA/superleggera_data/handling.meta#L18

This would give it an est. top speed of 184.992mph. 

For the price if it , it's fine. We're not going to keep buffing top speeds of vehicle slightly just to ""match irl speeds"" - when in fact, those irl speeds are either based on paper, or in perfect road/weather conditions. We will only tweak speeds if the vehicle is not right at all/handling fixes.
