### ISSUE TITLE
Bugatti Veyron

### ISSUE THREAD

**Issue by ChirpyMedusa** [fkk-cz/noire_vehicles#1045]
Would it be possible to turn down the sound on this vehicle slightly? It is so loud that is impossible to hear anything else going on around you. There are definitely some loud cars but this one is a little excessive, in my opinion. I would love to buy it if it were turned down a bit. Thanks.

**Comment by Mynameisnotlenny** [comment]
Another possible option would be to turn down the sound of the engine for passengers in the car as realistically Bugatti happens to make loud cars however they also have excellent sound isolation to prevent the engine from being too loud for the passengers inside.

**Comment by fkk-cz** [comment]
Unfortunately there is no easy way to adjust volume of an audio hash. Swapping the sounds would also likely cause complaints from people who *do* like the loud exhaust.

**Comment by PreacherDeimos** [comment]
Turn down your SFX sound in your Audio Settings!
