### ISSUE TITLE
2016 NSX Top speed test

### ISSUE THREAD

**Issue by TheRealKovuu** [fkk-cz/noire_vehicles#1046]
I recently requested for the recent speed change to the nsx and it was implemented but when testing it tops at 130 now. Just letting you know if there's anything that can help with it. Thank you for applying the input.

**Comment by No-Yes1** [comment]
![image](https://user-images.githubusercontent.com/79383480/167255948-382ed372-bdfe-4558-88af-54b44b1f1b77.png)


> I recently requested for the recent speed change to the nsx and it was implemented but when testing it tops at 130 now. Just letting you know if there's anything that can help with it. Thank you for applying the input.

Is it this vehicle?

**Comment by TheRealKovuu** [comment]
No that’s not the one it’s the 2016 Honda NSX under supporter.

**Comment by cxerq** [comment]
> No that’s not the one it’s the 2016 Honda NSX under supporter.

So you are saying the car is slower now? that doesnt make much sense

**Comment by No-Yes1** [comment]
It would appear that the commit change was not the correct vehicle again. I've amended this and reverted the previous change: https://github.com/fkk-cz/noire_vehicles/commit/9a03720f542f09b95c8d8a71b9f4ac926129f138. Will leave this open for when it merges to see if it's still an issue @TheRealKovuu

**Comment by No-Yes1** [comment]
Closing this due to no response, so i'm guessing the issue has been fixed.
