### ISSUE TITLE
1994 Nissan 240SX SE

### ISSUE THREAD

**Issue by PreacherDeimos** [fkk-cz/noire_vehicles#1049]
Hello! As seen below the dirt-mapping on my Nissan is just completely fucked, it looks very weird, not normal at all, it also has some weird 3rd light poking through the center of the hood as shown in this video below. One other small request, please change the sound of my Nissan to this one here: https://www.gta5-mods.com/vehicles/nissan-240z-l24-i6-sound-mod-sp-add-on-fivem

https://www.youtube.com/watch?v=cm98QNMaSPI

![167372516-492089c1-55d3-4946-9879-ed30bc246b40](https://user-images.githubusercontent.com/103844484/167372653-1b36a2ff-4d15-4689-87ff-4f1a86c15fd5.png)

Thank you so much for all your guys hard work! Been killin it!

**Comment by Artificial-IQ** [comment]
This is an issue caused by the vehicle model creator and cannot be changed. Have a nice day.
