### ISSUE TITLE
BMW i8 LB, SUPER

### ISSUE THREAD

**Issue by TheBottomFragger** [fkk-cz/noire_vehicles#1050]
Hey! 
I love how the i8 LB looks and how it drives, BUT it spins out a lot when you start driving. Is there any way to change this? Or a “fix” for it?
It’s only on take off it spins out, other than that it’s great!

**Comment by PreacherDeimos** [comment]
This can easily be fixed I'm sure, it does drive well and I wish you good luck on your fix.

**Comment by No-Yes1** [comment]
Fixed in https://github.com/fkk-cz/noire_vehicles/commit/27796632bcf3bec91e945979a65c6ff2625fc493. Please wait until this is merged.
