### ISSUE TITLE
Lamborghini Huracan EVO Massive speed decrease. 

### ISSUE THREAD

**Issue by tythetanman** [fkk-cz/noire_vehicles#1052]
Since DSC removal the Lamborghini Huracan EVO has dropped from a top speed of over 245 to under 115 around the range of the senna and other cars that are under $750,000. 

When the Lamborghini Huracan EVO is a 1.1 million dollar vehicle. 

I was just checking to see if it’s possible that It can get a speed bump up that is somewhere closer to the speed it was getting when DSC was on it. 

Thanks again even for the consideration on the speed bump up.

**Comment by No-Yes1** [comment]
>to under 115

What? https://github.com/fkk-cz/noire_vehicles/blob/b5ca960de1c4003e9f0e2b1a58441181b722829a/DATA/hevo_data/handling.meta#L17 vehicle has an average top speed of 184.5mph. Top speed irl is Top speedkm/h >325 (mph > 202). We're not buffing top speeds to how it was while DSC was a thing. As the speed isn't less then 10% then what the proposed irl top speed, we're not tweaking it.
