### ISSUE TITLE
Non Supporter Lamborghini Aventador Top speed

### ISSUE THREAD

**Issue by PsychoticCore** [fkk-cz/noire_vehicles#1053]
For a car that is 1.5 Million dollars I think it should be quicker in speed and quicker at stopping and better at turning. Better car overall. Not many people have the car but if you compare it to the Murcielago which is 950,000$ brand new its just about the same if not worst. Murci brakes great and turns great too but for the Aventador that is almost 600k more expensive id expect it to be quicker than a cheaper car that is much much older too

_dont mind all the Title edits lol couldnt make my mind up_

**Comment by No-Yes1** [comment]
Fixed in https://github.com/fkk-cz/noire_vehicles/commit/73f713f5507d04869390ffb9b53cb194f6bada99. Please wait until this is merged.
