### ISSUE TITLE
Ferrari 488 Pista

### ISSUE THREAD

**Issue by landerssonn** [fkk-cz/noire_vehicles#1055]
I made a issue earlier about the top speed being to slow compared to the real top speed. i think u did change it but i didnt notice any change. do you mind checking it again, thank you

**Comment by No-Yes1** [comment]
Please see the below comment, we're not going to keep fine tuning vehicles to it's """real"" top speeds, as that's on paper and perfect condictions:

[fkk-cz](https://github.com/fkk-cz)
[7 days ago](https://github.com/fkk-cz/noire-public/discussions/801#discussioncomment-2704172)
Maintainer
Going to put this out there - what's the difference between 190 mph and 200 mph besides 10 mph? Rhetorical question obviously.

As stated above, no one without a death wish would ever attempt to drive these speeds on a public road. One pothole or bad stretch of road would blow out your tire or suspension, not to mention make you lose control and wreck your $300k supercar. Unfortunately GTA (or any game to my knowledge) doesn't simulate bad road conditions very well, if at all. Additionally, vehicles that can reach such speeds should be completely ineffective off road and take a lot of damage -- I can think of quite a few scenarios where I've seen people launch a Ferrari up a mountain and keep driving.

We will not be making these trivial changes to vehicles' top speeds unless they're significantly broken (>10% speed diff.). The same applies to people asking for vehicles to go 220-230 mph+. No vehicle in the city should be easily reaching those speeds.

For anyone who thinks a vehicle that can 'only' go 180 mph is slow, I'd suggest you try driving that speed on a U.S. highway sometime -- then come back and tell me it's too slow.
