### ISSUE TITLE
New Yacht Issues 

### ISSUE THREAD

**Issue by Cobby1-89** [fkk-cz/noire_vehicles#1056]
I just purchased the 2.25 Mill yacht and there are a couple of issues with it.  #1 It needs fuel, but there is no place to physically add it, if fuel usage could be removed that would be perfect. #2 If you are the driver, once you are in the seat you cannot leave the driver's seat, if you attempt to get back into the seat to drive, it will make you jump out the side of the boat and you are stuck wherever you are at. It just needs some attention to the ability to get back into the driver's seat successfully, and operate without fuel, because no one is going to be able to carry that much fuel on their person to constantly re fuel out in the ocean. If you leave the driver's seat for a party or an event, it would be nice to get back in the seat and drive back to a dock, also once the boat is out of the garage you cannot put it back due to the driver's seat issue, so once you take it out....it stays out.

**Comment by mattny0608** [comment]
Just would like to touch on this... the 4.7 mil yacht is also rather buggy. It keeps slamming you against the side because of the rocking and it was throwing people off last night (LOL) just needs a little "anchored" love as in when it's anchor is down just needs to be more stationary I think. I can make a completely separate ticket if need be and submit clips later. Just figured with this title it fits

**Comment by No-Yes1** [comment]
> Just would like to touch on this... the 4.7 mil yacht is also rather buggy. It keeps slamming you against the side because of the rocking and it was throwing people off last night (LOL) just needs a little "anchored" love as in when it's anchor is down just needs to be more stationary I think. I can make a completely separate ticket if need be and submit clips later. Just figured with this title it fits

This need to be in a separate issue as it's an different model.

**Comment by fkk-cz** [comment]
Fixed. https://github.com/fkk-cz/noire/commit/5e675b8a4705ecbf105759af421b696490fb8e98
