### ISSUE TITLE
New 4.7 mil yacht

### ISSUE THREAD

**Issue by mattny0608** [fkk-cz/noire_vehicles#1057]
The4.7 mil yacht is rather buggy. It keeps slamming you against the side because of the rocking and it was throwing people off last night (LOL) just needs a little "anchored" love as in when it's anchor is down just needs to be more stationary I think. It is buggy as well while it's moving that people slide around, not as bad though. Also was hoping that a yacht of this size would have a storage or something somewhere? Like a cargo or something..? I can submit clips this evening when home if needed.

**Comment by fkk-cz** [comment]
The player movement issues inside the yacht is most likely caused by desync issues, which could be exacerbated if the player controlling the vehicle has a large ping/FPS differential compared to the non-seated ped.

This most likely cannot be solved, one thing that could help would be to reduce the intensity of the waves if a player is near either yacht model.

**Comment by mattny0608** [comment]
Is there any chance the waves could be tuned down then to solve this issue at least for the most part > The player movement issues inside the yacht is most likely caused by desync issues, which could be exacerbated if the player controlling the vehicle has a large ping/FPS differential compared to the non-seated ped.
> 
> 
> 
> This most likely cannot be solved, one thing that could help would be to reduce the intensity of the waves if a player is near either yacht model.

**Comment by Blumpkin-JC** [comment]
Tuning down the waves would not make sense as the ocean has large waves and would not be realistic

**Comment by gxdsent** [comment]
> Tuning down the waves would not make sense as the ocean has large waves and would not be realistic

that’s not what he means in a literal sense regarding the whole games ocean🤦🏽‍♂️ in game the intensity of the waves just surrounding the yacht would have to be turned down so players can actually function on it

**Comment by No-Yes1** [comment]
This yacht is being recalled.
