### ISSUE TITLE
Mclaren 650s coupe.

### ISSUE THREAD

**Issue by Cruzamp** [fkk-cz/noire_vehicles#1058]
I have had this car when dsc was in and it was good. But when it was taken out it's way slow now. The top speed it suppose to be 207 so somewhere around 195-197 would be ok. Also its suppose to take off 0-60 in 3.0 seconds. And do 0-125 in 8 seconds. It's takes it's time  for it to even get to 140.

**Comment by Cruzamp** [comment]
Also could you add this sound to it. It's the closest I could find for the 650s mclaren v8 sound. Its a lot deeper than the 720s 

https://www.gta5-mods.com/vehicles/mclaren-720s-m840t-v8-sound-mod-sp-add-on-fivem

**Comment by No-Yes1** [comment]
> I have had this car when dsc was in and it was good. But when it was taken out it's way slow now. The top speed it suppose to be 207 so somewhere around 195-197 would be ok. Also its suppose to take off 0-60 in 3.0 seconds. And do 0-125 in 8 seconds. It's takes it's time for it to even get to 140.

Fixed in https://github.com/fkk-cz/noire_vehicles/commit/b23484f389907a8fabd04cebe0d87cb61b7f5b49.

**Comment by No-Yes1** [comment]
> Also could you add this sound to it. It's the closest I could find for the 650s mclaren v8 sound. Its a lot deeper than the 720s

https://www.gta5-mods.com/vehicles/mclaren-720s-m840t-v8-sound-mod-sp-add-on-fivem

Fixed https://github.com/fkk-cz/noire_vehicles/commit/29097d6dcf0a8f904f47d40e6d7e29d6ae58d23b. Please wait until this is merged.
