### ISSUE TITLE
BMW M5 Competition Tweak

### ISSUE THREAD

**Issue by RichieRockefeller** [fkk-cz/noire_vehicles#1059]
The non-supporter BMW M5 F90 is currently faster than the supporter 2022 BMW M5 Competition. I did test drives for both and a little race with a buddy on a straight away then tested the top speed on both and the competition was slower overall in every aspect. I love the sound but I feel as though it could get tweaked for the speed especially since the irl top speed is 190mph and it is quite a bit faster than the F90.

**Comment by No-Yes1** [comment]
People were using the 2022 M5 as a meta for getaways, which is why the vehicle got nerfed and won't be re-buffed. Can blame other people for not wanting to RP and just have an end goal to get away as fast and unrealistic as possible.
