### ISSUE TITLE
[ 2018 Harley Davidson FLHXS ]

### ISSUE THREAD

**Issue by PreacherDeimos** [fkk-cz/noire_vehicles#1060]
I have really been looking forward to buying more Bikes, specifically Harleys, but I have ran into a visual problem, the Wind Deflector, the part that you can see through should NOT be transparent, yet you can see straight through it, the gauges are also fucked with the mapping, are these errors something that's fixable? 

Vehicle: 2018 Harley Davidson FLHXS (Supporter)

Picture of transparent Wind Deflector: 

https://cdn.discordapp.com/attachments/889302842672824351/974606346257334322/unknown.png

Picture of miss-mapped gauges:

https://cdn.discordapp.com/attachments/889302842672824351/974825121535631460/unknown.png

**Comment by STKstyx** [comment]
I did read the issue and the issue I posted is for a completely different bike lol

**Comment by fkk-cz** [comment]
Fixed on next restart.
