### ISSUE TITLE
Non supporter Porsche gt3rs

### ISSUE THREAD

**Issue by Cruzamp** [fkk-cz/noire_vehicles#1061]
Could we do some fixing on this car. The top speed is 167mph at the moment but it's suppose to be way better it hits 194 mph irl. Also it's a small zippy car. The takeoff is good and getting to the 160 is ight!!

**Comment by PreacherDeimos** [comment]
Car specs for the GT3 RS for whoever decides to modify the Porsche, if they do. 

![image](https://user-images.githubusercontent.com/103844484/168411873-078d39a4-c434-4bd2-a5b1-59e5cd180116.png)

**Comment by Cruzamp** [comment]
Also adding a custom sound would be awesome!! here is a F6 GT3RS sound. Hoping it works!!! 

https://www.gta5-mods.com/vehicles/tuned-porsche-911-gt3rs-f6-sound-mod-add-on-sp-fivem

**Comment by No-Yes1** [comment]
> Also adding a custom sound would be awesome!! here is a F6 GT3RS sound. Hoping it works!!!
> 
> https://www.gta5-mods.com/vehicles/tuned-porsche-911-gt3rs-f6-sound-mod-add-on-sp-fivem

This already has a custom audio hash ``      <audioNameHash>gt3flat6</audioNameHash>``

**Comment by No-Yes1** [comment]
> Could we do some fixing on this car. The top speed is 167mph at the moment but it's suppose to be way better it hits 194 mph irl. Also it's a small zippy car. The takeoff is good and getting to the 160 is ight!!

https://github.com/fkk-cz/noire_vehicles/commit/0846e3952381de3a32067798aba89801a1fcdefa. Tweaked so it goes 180, that's fine for the vehicle/speed/handling.
