### ISSUE TITLE
Lamborghini LP 700-4

### ISSUE THREAD

**Issue by TheGodfatha** [fkk-cz/noire_vehicles#1062]
The car is a 1.2 million dollar car and it’s drives the same speed as my old Mclaren spyder. Car caps at 183 and won’t move from that unless I go off a cliff. This is the benchmark for most cars that aren’t even a quarter of the price range. I was just wondering if you could push it to at least 190 flat to set a clear difference.

**Comment by No-Yes1** [comment]
Fixed in https://github.com/fkk-cz/noire_vehicles/commit/f661c599cadf0434cb8731bdfeae70c9050cb195. Please wait until this is merged.
