### ISSUE TITLE
1964 Impala

### ISSUE THREAD

**Issue by xFooliee** [fkk-cz/noire_vehicles#1063]
I think that the 1964 Impala should be counted as a lowrider, it's known for having hydrolics and it should also have the option to be topless/convertible. Feel like it would be more realistic

**Comment by No-Yes1** [comment]
> I think that the 1964 Impala should be counted as a lowrider, it's known for having hydrolics and it should also have the option to be topless/convertible. Feel like it would be more realistic

That's a model issue sadly, does the impala have hydrolics? I can add it if needs be?

**Comment by TheGodfatha** [comment]
Yes please add it

**Comment by No-Yes1** [comment]
https://github.com/fkk-cz/noire_vehicles/commit/556fb3bd88cfa26fd6580d44f3a27e745c9745dc - added hydraulics to the 64 impala. Please wait until this is merged.
