### ISSUE TITLE
2015 Subaru WRX STI

### ISSUE THREAD

**Issue by Ell34** [fkk-cz/noire_vehicles#1064]
This car has a few issues. It has no upgrades or cosmetic upgrades. mod on the website shows it does, window tints dont work, neon headlights dont work and its also very tippy

**Comment by No-Yes1** [comment]
Swapped modkit id for the no upgrades: https://github.com/fkk-cz/noire_vehicles/commit/94dbbbc1c8c42f2ccb802ffce5f94270a8b7318c

Fixed handling https://github.com/fkk-cz/noire_vehicles/commit/71f9af0528245f1eb26f26cc25252b34a2cc7c36.

Please wait until this is merged.
