### ISSUE TITLE
Sound change on Non Supporter Aventador?

### ISSUE THREAD

**Issue by PsychoticCore** [fkk-cz/noire_vehicles#1065]
So I was thinking since the Aventador is a V12 which should sound high pitch and mean which it doesn't right now we maybe can see on getting a sound change?

I was thinking maybe of this sound here that is supposed to be for an SVJ, yes not the same Lamborghini as I'm talking about but both cars mentioned here have the same Firing Order which is what dictates the sound mostly apart from how the headers are made and such bla bla bla but I was thinking maybe this? If you devs or others in the community would maybe rate this or say your feelings on this it'd be great cause I personally much prefer this sound over the current one in the city currently and wouldn't mind it being swapped out. I feel like this sound would be much more fitting than the tame and quiet sounding sound we currently have. Then again I'm not the only one who has this car so idk if everyone has the same opinion on it or not. 👍 

https://www.gta5-mods.com/vehicles/gintani-f1-lamborghini-aventador-svj-v12-sound-mod-sp-add-on-fivem

**Comment by No-Yes1** [comment]
Which aventador?

**Comment by PsychoticCore** [comment]
> Which aventador? 

Sound change for the Non Supporter Aventador is what I'm asking, sorry if me naming more than 1 lambo confused you

**Comment by PsychoticCore** [comment]
> Which aventador? 

This one here if it helps at all 
https://github.com/fkk-cz/noire_vehicles/commit/73f713f5507d04869390ffb9b53cb194f6bada99

**Comment by No-Yes1** [comment]
There's already a custom sound on that aventador, so no.
