### ISSUE TITLE
Lamborghini Aventador S (non supporter lambo) textures weird/buggy

### ISSUE THREAD

**Issue by PsychoticCore** [fkk-cz/noire_vehicles#1066]
All the little green bits are buggy and are like half there if that makes sense, mainly the ones at the back there looks really really odd. I dont think its supposed to look like that but i may be wrong.
idk if its possible to completely remove the green or let us change the color of it but that'd be great if we could
![image](https://user-images.githubusercontent.com/69283872/168460091-01d0acd3-5137-43d3-9a85-cccbb75f093a.png)
![image](https://user-images.githubusercontent.com/69283872/168460099-94acd695-9731-45dd-91b4-8aef0ca596d2.png)
![image](https://user-images.githubusercontent.com/69283872/168460109-eed51c78-ebeb-4987-bd0c-cbf6a291dcab.png)

**Comment by fkk-cz** [comment]
I was unable to find the original model and textures for this vehicle. Don't have texture backups either, as this vehicle was (poorly) resized a long time ago.
