### ISSUE TITLE
2010 Chevy Silverado

### ISSUE THREAD

**Issue by EncrustMust** [fkk-cz/noire_vehicles#1070]
Needs handing and suspension fixed, flips way to easily
Acceleration and top speed needs increased 80 is top speed
Can’t tow trailers currently

**Comment by No-Yes1** [comment]
> Needs handing and suspension fixed, flips way to easily
Acceleration and top speed needs increased 80 is top speed

Fixed in https://github.com/fkk-cz/noire_vehicles/commit/6262dc62a46a22260e16ca2132244b870b51b2e2

> Can’t tow trailers currently

Fixed in https://github.com/fkk-cz/noire_vehicles/commit/255c2852de22cd43374d06202d60a447064d5e43. Please wait until these are merged.
