### ISSUE TITLE
GTR sound 

### ISSUE THREAD

**Issue by somedudenamedrush** [fkk-cz/noire_vehicles#1071]
found a good custom sound for the GTR would be nice to have it put it https://www.gta5-mods.com/vehicles/nissan-gt-r-vr38dett-v6-engine-sound-oiv-add-on-fivem-sound

**Comment by No-Yes1** [comment]
Done in https://github.com/fkk-cz/noire_vehicles/commit/141713609f8b2e00c31eac16b64685b2ee514df0. Please wait until this is merged.
