### ISSUE TITLE
2020 Dodge Charger Hellcat (The $268000 one)

### ISSUE THREAD

**Issue by banderson0827** [fkk-cz/noire_vehicles#1074]
Hello, I have been studying the 3 main supporter Chargers (2016 Dodge Charger Hellcat, 2020 Dodge Charger Hellcat $95000, and 2020 Dodge Charger Hellcat) for some time now. I got the 2020 Dodge Charger Hellcat $95000 at first due to the price but I decided to upgrade today to the 2020 Dodge Charger Hellcat $268000 although it seemed slower due to the better handling, and I was hoping the top speed would be higher. The issue is the $268000 2020 Dodge Charger Hellcat is slower than the $95000 Dodge Challenger Hellcat. I would like to request that the top speed of the $268000 2020 Dodge Charger Hellcat be increased to at least 220 as the $95000 2020 Dodge Challenger Hellcat hits 190. I would like to request also that the acceleration of the $268000 2020 Dodge Charger Hellcat be increased to at least match the $95000 version if not better. The car should perform much better if it is 3X the price, not worse. Thank you for your attention to this issue! :)

**Comment by banderson0827** [comment]
Also I forgot to mention there is a bright orange light coming from the rear trunk right in the middle of the brake lights. If that could be fixed as well would be much appreciated!

**Comment by No-Yes1** [comment]
Yeah, no. That is not going 220 mph. Fixed the Speed/Acceleration to match the 95K Hellcat.
