### ISSUE TITLE
Porsche GT2 RS

### ISSUE THREAD

**Issue by Cruzamp** [fkk-cz/noire_vehicles#1075]
This car is suppose to be faster than the GT3 RS with the top speed being 211 mph. Irl the gt2 rs has more horse power. The 0-60 is 2.6 seconds and the 0-120 is 7.0 seconds. Plus it's more money at pdm than the gt3 rs. Currently the car barely hits 130 at pdm when you test drive it. After upgrades that's going to probably top out at 160 maybe. After all the upgrades it should top out at 202 or so. It is a 400k car.

**Comment by No-Yes1** [comment]
Fixed in https://github.com/fkk-cz/noire_vehicles/commit/379fdd64c1d217f31a0fab6fb59447b49d6c7d71. Please wait until this is merged.
