### ISSUE TITLE
2003 Ram SRT10 speed buff

### ISSUE THREAD

**Issue by glefave0209** [fkk-cz/noire_vehicles#1077]
This vehicle has a Viper engine in it, and the top speed is 120mph.  I requested to have this vehicle in the city, and the IRL MSRP was $70,000 in 2003.  It was put in the city at $35,000 PDM, so I'm not expecting this to have actual Viper speed for that price.  I understand you guys try to make it reasonable for the price.

That being said, I do feel like this thing should be able to go faster than the minivans that are in the city.. lol.  The Toyota Truck goes 160 mph, and I don't think it's unreasonable for a truck with a viper engine to at least push 150

**Comment by No-Yes1** [comment]
Fixed in https://github.com/fkk-cz/noire_vehicles/commit/338e7d904d22c32c2d2b460a41e31d2886f9523e. Please wait until this is merged.
