### ISSUE TITLE
Lamborghini centenario lp 770-4

### ISSUE THREAD

**Issue by Cruzamp** [fkk-cz/noire_vehicles#1078]
So this car is 1.9 million. And it's sooo slow. It should hit 217 mph irl it hits the 217 mph. And the takeoff is also super slow. It should zoooooooom. There is the stats for it. 

770 hp v12 
0-62 in 2.8
Top speed is 217 
And huge brakes to stop it in an instant!!! 

Plus at pdm it's 1.9 mill. That's a lot of money when you can just get the sc18 which Is way faster.

**Comment by No-Yes1** [comment]
Tweaked in https://github.com/fkk-cz/noire_vehicles/commit/d37082c616d83393d848092da9db715e94ad20e8. Please wait until this is merged.
