### ISSUE TITLE
Custom Wheel Pack

### ISSUE THREAD

**Issue by Metalwrist** [fkk-cz/noire_vehicles#1082]
Could this wheel pack be added to Los Santos Customs? https://www.gta5-mods.com/vehicles/real-wheels-pack

**Comment by No-Yes1** [comment]
Do these even work for FiveM?

**Comment by No-Yes1** [comment]
I found another pack that might work, I need to do some testing on this to ensure this works. Give me a bit of time.

**Comment by Metalwrist** [comment]
awesome thank you

**Comment by PreacherDeimos** [comment]
Here's some more Add-On rims, pretty dope.

https://www.gta5-mods.com/vehicles/various-wheels-pack-add-on

**Comment by No-Yes1** [comment]
Pinning this issue just so I don't forget.



> Here's some more Add-On rims, pretty dope.
> 
> https://www.gta5-mods.com/vehicles/various-wheels-pack-add-on

I'll take a look at this, and see if I can add them in into one whole resource.

**Comment by No-Yes1** [comment]
> Here's some more Add-On rims, pretty dope.
> 
> https://www.gta5-mods.com/vehicles/various-wheels-pack-add-on

These work fine, optimised/removed some of them in the pack as they weren't optimised/big texture assets. 




> Could this wheel pack be added to Los Santos Customs? https://www.gta5-mods.com/vehicles/real-wheels-pack

Going to test these out shortly, and see if they can work as one resource.

**Comment by TheGodfatha** [comment]
Based on the examples you’ve seen from everyone in the thread is it possible for you to find some that might work. I ask this because Gta rims are not it. They look horrible on most cars and on top of that most stock tires are just ugly.

**Comment by No-Yes1** [comment]
> Based on the examples you’ve seen from everyone in the thread is it possible for you to find some that might work. I ask this because Gta rims are not it. They look horrible on most cars and on top of that most stock tires are just ugly.

Did you even read what I said previously? The one preacher provided works fine, the original ones do not. I'm in the making of finding more. If you find more then send here and i'll check them out.

**Comment by TheGodfatha** [comment]
My bad completely glossed over his specific one.

**Comment by AntonioAres** [comment]
On the topic of rims, I found a dope  Forgiato wheel pack that I think would be dope to have in the city.    https://www.gta5-mods.com/vehicles/forgiato-wheels-pack-1-add-on

**Comment by PeanutTheCop** [comment]
is there any chance we could get these also?

https://www.gta5-mods.com/paintjobs/hoosier-tires-drag-slicks-with-replaced-tread-and-dirt-texture-vehshare
