### ISSUE TITLE
2007 Toyota hilux arctic

### ISSUE THREAD

**Issue by Cruzamp** [fkk-cz/noire_vehicles#1083]
Love this truck. Speed if perfect. But handling is terrible. Can you fix it a little. Stopping and cornering is very bad would love to have it fixed. Also could you make it tow the small trailer. It's got a orange tow hitch. Could ya at least make it tow the small one.

**Comment by Cruzamp** [comment]
Also it's broken when you hop in the back seats. It takes a second to get it. And when you get out of the back seats it puts you in the truck and it's sometimes hard to get out of the trunk.

**Comment by No-Yes1** [comment]
Just realized that this vehicle is a RHD, so changing the layout might cause issues when driving...

**Comment by No-Yes1** [comment]
@Cruzamp - Are you able to supply a clip of this:
> Also it's broken when you hop in the back seats. It takes a second to get it. And when you get out of the back seats it puts you in the truck and it's sometimes hard to get out of the trunk.

**Comment by Cruzamp** [comment]
there is a lot in the clip of everything it does.  
https://medal.tv/games/gta-v/clips/m0vg90mfMH0Cc/d1337TMu0axb?invite=cr-MSxQbDcsNDQ2NjM5MTks

**Comment by Kaiyashi9** [comment]
Did you add the option for the trailer I actually just bought it and I couldn't tow

**Comment by Cruzamp** [comment]
> Did you add the option for the trailer I actually just bought it and I couldn't tow

They said it might work...

**Comment by No-Yes1** [comment]
> Did you add the option for the trailer I actually just bought it and I couldn't tow

It's dependant on the vehicle creator and if it can actually tow. Seems as though this doesn't. Reverted the change https://github.com/fkk-cz/noire_vehicles/commit/44899c874d129be97150fcf1f365454b5a95b597

**Comment by No-Yes1** [comment]
I've attempted to fix/debug the issue on localhosts, and can't actually fix the vehicle layouts issue. This may have to be another car that needs to be removed/recalled.
