### ISSUE TITLE
not really a issue id just like the values changed for the s15 rb

### ISSUE THREAD

**Issue by Kaiyashi9** [fkk-cz/noire_vehicles#1085]
values for supporter s15 rb thats around 40k 
HANDLING DATA - 

    <fMass value="1500.000000"/>
    <fInitialDragCoeff value="15.5"/>
    <fPercentSubmerged value="85.000000"/>
    <vecCentreOfMassOffset x="0.000000" y="0.000000" z="0.000000"/>
    <vecInertiaMultiplier x="1.000000" y="1.000000" z="1.000000"/>
    <fDriveBiasFront value="0.000000"/>
    <nInitialDriveGears value="6"/>
    <fInitialDriveForce value="1.900000"/>
    <fDriveInertia value="1.000000"/>
    <fClutchChangeRateScaleUpShift value="5.000000"/>
    <fClutchChangeRateScaleDownShift value="5.000000"/>
    <fInitialDriveMaxFlatVel value="200.000000"/>
    <fBrakeForce value="4.850000"/>
    <fBrakeBiasFront value="0.670000"/>
    <fHandBrakeForce value="3.500000"/>
    <fSteeringLock value="57.000000"/>
    <fTractionCurveMax value="1.000000"/>
    <fTractionCurveMin value="1.450000"/>
    <fTractionCurveLateral value="35.000000"/>
    <fTractionSpringDeltaMax value="0.150000"/>
    <fLowSpeedTractionLossMult value="0.500000"/>
    <fCamberStiffnesss value="0.000000"/>
    <fTractionBiasFront value="0.450000"/>
    <fTractionLossMult value="1.000000"/>
    <fSuspensionForce value="2.800000" />
    <fSuspensionCompDamp value="1.400000" />
    <fSuspensionReboundDamp value="2.200000" />
    <fSuspensionUpperLimit value="0.060000" />
    <fSuspensionLowerLimit value="-0.050000" />
    <fSuspensionRaise value="-0.000000"/>
    <fSuspensionBiasFront value="0.500000"/>

**Comment by No-Yes1** [comment]
> <fInitialDriveForce value="1.900000"/>

This would make it a drift vehicle then i'm guessing? We tried a drift handling meta file a while back, and it turned into people driving unrealistically/abusing the mechanics of it.
