### ISSUE TITLE
2010 lfa buff

### ISSUE THREAD

**Issue by Kaiyashi9** [fkk-cz/noire_vehicles#1086]
Can we get a buff on the lfa nothing crazy it goes 120-130 currently I'd like anything between 150-170

**Comment by KCurt420** [comment]
no it needs to be like 180-190 this car is amazing irl and fast asf too, i think the acceleration and the top speed need to be buffed on this car other then that its amazing

**Comment by gxdsent** [comment]
agreed ^ this thing is sick irl lol in city it’s been neglected for so long for some reason 😂 for reference it beats the 10’ GTR in a quarter mile, not by a lot but it still does 👍🏽

**Comment by KCurt420** [comment]
also im not sure if you can fix the dirt map of the car but it gets really dirty really fast

**Comment by No-Yes1** [comment]
Not sure why this wasn't brought up earlier, this was a mess to clean up...



> no it needs to be like 180-190 this car is amazing irl and fast asf too, i think the acceleration and the top speed need to be buffed on this car other then that its amazing

New speed should be around 180. https://github.com/fkk-cz/noire_vehicles/commit/0a9a886534bd71ceb14563e4b21deb0877434596





> also im not sure if you can fix the dirt map of the car but it gets really dirty really fast

https://github.com/fkk-cz/noire_vehicles/commit/6d2348fd3a226c8c200ea7802493ca55756704a2.

Please wait until this is merged.
