### ISSUE TITLE
Bugatti Divo/Koenigsegg Jesko

### ISSUE THREAD

**Issue by xFuziii** [fkk-cz/noire_vehicles#1087]
hello,
recently i was checking out what my next possible car would be and it came down to these 2cars
Bugatti Divo 1.7mil
Koenigsegg Jesko 2mil
My question is if it would be possible to check out these cars stats?
Because their stats are really not it.
Jesko hits like 140mph
And Bugatti divo hits like 150ish mph
And both their asceleration is also not it.
While these cars are actually hypercars and perform insane IRL.
 Koenigsegg  Jesko IRL hits like 300mph but offcours i am not gonna ask for that top speed anything around 225mph would be nice for this car and a asceleration boost would also be nice.
Bugatti Divo IRL hits like 236Mph so it would also be nice if this car gets checked out and gets a performance boost.

Thank u for reading this and have a good day

**Comment by No-Yes1** [comment]
Apologies in the delay of response.

Fixed Divo -- https://github.com/fkk-cz/noire_vehicles/commit/a9c5bd0ffbf645193a4722bbf703c24a3ae2cb82.
Fixed Jesko -- https://github.com/fkk-cz/noire_vehicles/commit/ab157ee235e36c551ce5b768f0fb837f3b5bbb40.

Please wait for this to be merged.
