### ISSUE TITLE
Koenigsegg Agera RS Speed/Acceleration Tweak

### ISSUE THREAD

**Issue by RichieRockefeller** [fkk-cz/noire_vehicles#1088]
The $500k Koenigsegg Agera RS does not have the best acceleration and top speed compared to its IRL performance. "The Koenigsegg Agera RS recorded a top speed of 277.8mph and beat Bugatti Veyron Supersport, which could only manage the speed of 267mph (427.2 kmph)." "Koenigsegg Agera RS. 0-60 mph 2.6" "The Koenigsegg Agera RS is the newly crowned fastest production car in the world, after having surpassed the speed attained by previous record-holder, the Bugatti Veyron."

**Comment by PsychoticCore** [comment]
To be fair the car is 4.1 Million IRL unlike it's 500k price in city 😂

**Comment by RichieRockefeller** [comment]
> To be fair the car is 2.5-4.1 Million IRL unlike it's 500k price in city 😂

So then we should raise the praise.

**Comment by No-Yes1** [comment]
> > To be fair the car is 2.5-4.1 Million IRL unlike it's 500k price in city 😂
> 
> So then we should raise the price.

Raising the price would mean that people who already own the vehicle, would get their money back, if not more when they wish to sell it. Something we avoid. We are also not going to remove the vehicles from everyone's garage and then force players to rebuy it at a higher value, as it's not fair on the people who already own the vehicle.

As for stats you provided, they are not "real life" stats, either on paper or on perfect weather/road conditions. you wouldn't speed 190/200mph on the freeway, unless your wanting to kill yourself, kill members of the public or get arrested. vehicle won't be tweaked.
