### ISSUE TITLE
SeaShark Yacht

### ISSUE THREAD

**Issue by Metalwrist** [fkk-cz/noire_vehicles#1089]
I opened this issue the other day I just wanted to explain something, The Sea shark is a normal jet ski and the Sea shark yacht its not a big Yacht its just called Sea Shark Yacht is the same thing so you might as well take it out of city because it cost 40k more and is no different than the regular Sea shark. maybe offer a different jet ski in its place.
maybe this Yamaha instead?
https://www.gta5-mods.com/vehicles/2011-yamaha-fx-ho-waverunner-jetski-add-on

**Comment by fkk-cz** [comment]
`SEASHARK` is a vanilla make/model name with no relation to the add-on yacht. We will not remove a vehicle that a lot of people own solely for sharing or being similar to another vehicle's name.
