### ISSUE TITLE
Lamborghini Urus

### ISSUE THREAD

**Issue by noyeahsure** [fkk-cz/noire_vehicles#1094]
is it possible to get the speed buffed a small amount, I think it hits like. 135-140?, im not asking for IRL speeds. and the handling tweaked a bit? i spin far too much while turning in this thing.

**Comment by No-Yes1** [comment]
Fixed in https://github.com/fkk-cz/noire_vehicles/commit/ef334e21d0b3e39124215249279598558e495c5b. Please wait until this is merged.
