### ISSUE TITLE
Lfa buff part 2

### ISSUE THREAD

**Issue by Kaiyashi9** [fkk-cz/noire_vehicles#1099]
Doesn't seem like there was a speed increase the dirt mapping is definitely decreased which I appreciate thank you I'm not particularly concerned with the speed increase but a few of my friends definitely want it I see in the handling.meta that it was changed but we don't notice a difference

**Comment by No-Yes1** [comment]
Whoops! I forgot to set the values after I fixed the layout of the file. https://github.com/fkk-cz/noire_vehicles/commit/642d66346b2d2d6b1ced5adb0f57336890f0fb4a. Please wait until this is merged.
