### ISSUE TITLE
2020 Dodge Charger Hellcat $268k

### ISSUE THREAD

**Issue by RichieRockefeller** [fkk-cz/noire_vehicles#1100]
The more expensive $268k Dodge Charger Hellcat still seems to be slower than the cheaper $95k Daytona. I do not believe that, overall, it has to be buffed to disbelief or anywhere in an unrealistic spot but to just be a bit better. I sold my cheaper charger to buy this one and apart from the wheel spin and slightly better handling I was a bit disappointed for the amount I paid. I, in no way, feel as though I am entitled to get better for the money I spend but I just wanted to put this request in to see what you guys think. Thanks!

**Comment by No-Yes1** [comment]
Fixed in https://github.com/fkk-cz/noire_vehicles/commit/16afe9c4a0b26a2af37f1cd2facd311844b60121. Please wait until this is merged.
