### ISSUE TITLE
1970 Plymouth Convertible 

### ISSUE THREAD

**Issue by YouTri3** [fkk-cz/noire_vehicles#1102]
It's almost undrivable. It spins out and has 0 traction. It sounds great. Looks Great. Handles and Turn and overall drives horribly. It reminds me of DSC but it's off and you barely can control it.

**Comment by No-Yes1** [comment]
Fixed in https://github.com/fkk-cz/noire_vehicles/commit/5df676b7d21ece5c2dd16b3abf7f6c538c98c06c. Please wait until this is merged.
