### ISSUE TITLE
Dodge Charger 2016

### ISSUE THREAD

**Issue by cxerq** [fkk-cz/noire_vehicles#1104]
So the clip kinda speaks for itself, But whenever you try to turn a corner the car just flips over, can this be fixed! 
https://medal.tv/games/gta-v/clips/mnd6wuwqI0adi/d1337vB84GBV?invite=cr-MSxXZkcsMTg3OTQ2MDQs

**Comment by No-Yes1** [comment]
Fixed in https://github.com/fkk-cz/noire_vehicles/commit/2d9935c891720562e079c4216cf32111028f6447. please wait until this is merged.
