### ISSUE TITLE
2020 Nissan Sentra

### ISSUE THREAD

**Issue by EncrustMust** [fkk-cz/noire_vehicles#1105]
Tint doesnt work on this
Also the suspension is messed up, when you accelerate it does basically a endo and when you brake it lifts the front end. The suspension is very wobbly whenever you turn it acts like it has fox rally suspension and rolls the whole body. And whenever you turn the direction your turning body rolls instead the opposite like its supposed to.

**Comment by No-Yes1** [comment]
Fixed in https://github.com/fkk-cz/noire_vehicles/commit/bec413b730b5fb86a9a82d12bdac41dbf9b9857b. Please wait until this is merged.
