### ISSUE TITLE
Dodge Ram 2010 commercial double hitch issue

### ISSUE THREAD

**Issue by DarkHourEnt** [fkk-cz/noire_vehicles#1106]
The truck has a double hitch but the small trailer hitch does not hook on to any small trailers . The Gooseneck hitch does work, however it is very slow barely going over 50mph when hooked . I purchased the truck priced over 130k specifically for the double hitch. 

![B7429D86-99B2-4741-842D-6457343AA328](https://user-images.githubusercontent.com/106414427/170803955-1fa69581-4ebc-4f51-8b00-04a84ae23f71.jpeg)

**Comment by No-Yes1** [comment]
I've taken a look at this, and the ``trailercar`` - small trailer isn't in the vehicles.meta file to be supported. I've increased the speed a little bit so it should go a little faster when a gooseneck is hooked. https://github.com/fkk-cz/noire_vehicles/commit/614ada4caddff489420df0d2b5016a485f59931b Please wait until this is merged.
