### ISSUE TITLE
Porsche Panamera S Traction

### ISSUE THREAD

**Issue by TdotG** [fkk-cz/noire_vehicles#1111]
Is there anyway you could minimize the wheel spin on the car? It's  AWD yet it feels like its RWD. The tires spin from a dead stop, the handling is very solid, it just needs to spin less off a stop.

**Comment by No-Yes1** [comment]
Fixed in https://github.com/fkk-cz/noire_vehicles/commit/a8830083b85585df8bb7157f7ab20f888a672acb. Please wait until this is merged live.
