### ISSUE TITLE
Mazda RX7 Veilside

### ISSUE THREAD

**Issue by IseeNomore** [fkk-cz/noire_vehicles#1112]
I think it needs some tweaking on the handeling because it just doesnt wanna turn without hitting the handbrakes, By the looks of this car and knowing where it comes from it should be able to turn better then it does

**Comment by No-Yes1** [comment]
Fixed in https://github.com/fkk-cz/noire_vehicles/commit/c62aa02dcc6178d18fb291be54840b97790e1dc6. Please wait until this is merged.
