### ISSUE TITLE
Aston Martin Valkyrie

### ISSUE THREAD

**Issue by mattny0608** [fkk-cz/noire_vehicles#1113]
"For the price, the vehicle is fine and won't be fixed"??? How is this an acceptable response to a ticket regarding a vehicle not working properly. Sometimes the car undamaged only goes 189 (straight out of a garage) and it goes faster up hill than down hill??? This needs to be looked at why am I investing in such expensive things and then they get overlooked "eh screw it" is pretty much the response?? The car is 3 million dollars and shouldn't have the issues it's having.

**Comment by somedudenamedrush** [comment]
Tweaked top speed and acceleration, should be the fastest car in the game. https://github.com/fkk-cz/noire_vehicles/commit/d2830b78096cabbac1be74689c4549e1deb0900b. Please wait until this is merged. 

sorry about the last person who replied
