### ISSUE TITLE
Porsche Carrera GT “both versions” 

### ISSUE THREAD

**Issue by TheGodfatha** [fkk-cz/noire_vehicles#1114]
For the GT (100k) it’s far to slow fully upgraded the handling is pretty bad and the speed is lackluster compared to its irl speeds. I’m mainly asking about tweaking  the speed of the car . I’m pretty sure if you guys increase speed  it messes with handling, but that’s already bad as I said .if you could tweak the speed it would be appreciated. For both versions because they are basically around the same speed.

**Comment by boscarrr** [comment]
I agree especially the 400k one it currently has no upgrades I’m not sure if that is intentional but the car only goes about 165mph and I personally think it should go faster.

**Comment by No-Yes1** [comment]
I need both vehicle names. @TheGodfatha @boscarrr

**Comment by TheGodfatha** [comment]
2003 Porsche Carrera GT there’s a 100k version and a 400k version.

**Comment by No-Yes1** [comment]
400K porsche does not have any upgradable parts/can not be tweaked.

Fixed the Performance/Top speed issues: https://github.com/fkk-cz/noire_vehicles/commit/966c43f4766d2ac05792f8e2a26e5d4e83875036 / https://github.com/fkk-cz/noire_vehicles/commit/1870f6a3e145464185ccc219580f208fdbe11ad2.

Fixed the 100K porsche not having upgrades. https://github.com/fkk-cz/noire_vehicles/commit/a5977b8175fa4d07bf4e5fffdca4ddc0c1025069. Please wait until these are merged.
