### ISSUE TITLE
Lexus SC 300 No Engine or Transmission Upgrades

### ISSUE THREAD

**Issue by Chitowndevil21** [fkk-cz/noire_vehicles#1116]
Just wondering if this vehicle can get these upgrades added, it has all the other performance upgrades?  This is the Lexus SC 300 that costs around 30K, not to be confused with the Lexus SC300 that is over 40K.

**Comment by No-Yes1** [comment]
Fixed in https://github.com/fkk-cz/noire_vehicles/commit/406b9309d3701278034262a9d781c790977e8f7f. Please wait until this is merged.
