### ISSUE TITLE
1970 Buick GSX

### ISSUE THREAD

**Issue by PreacherDeimos** [fkk-cz/noire_vehicles#1118]
This car slides way too much, turn at any speed and it just wants to spin out and the tires also just spin like crazy. It's not exactly fast either so I'm asking for a change to the handling please and a speed of 140. In my opinion, just give it the handling and speed of the 1969 Camaro SS, this car handles like a dream.

**Comment by No-Yes1** [comment]
Fixed in https://github.com/fkk-cz/noire_vehicles/commit/8d84a4c97493d055a8f7296e07209075b4deaeb8. Please wait until this is merged.
