### ISSUE TITLE
2008 Lamborghini gallardo

### ISSUE THREAD

**Issue by Cruzamp** [fkk-cz/noire_vehicles#1119]
Right now it does 165, maybe make the acceleration better I think it could do the top speed but it needs a long runway. It does 196 mph irl at least make it get to like 180 and it's a v10 it should get there pretty quick.

**Comment by No-Yes1** [comment]
Speed is fine for the price, tweaked acceleration slightly https://github.com/fkk-cz/noire_vehicles/commit/42be7ede1a2267667c685a263b26e54ede821ef4. Please wait until this is merged live.
