### ISSUE TITLE
Aventador S 

### ISSUE THREAD

**Issue by TdotG** [fkk-cz/noire_vehicles#1120]
Is there anyway you can buff the top speed by 10 mph at most, I saw the handling was buffed ab 3 weeks ago, but for 1.5m, its a bit tame. Can you please give it a little bit of a speed buff? Much appreciated.

**Comment by No-Yes1** [comment]
> Is there anyway you can buff the top speed by 10 mph at most, I saw the handling was buffed ab 3 weeks ago, but for 1.5m, its a bit tame. Can you please give it a little bit of a speed buff? Much appreciated.

Upping the speed by that small amount is useless, and won't be fixed.



> Also idk if its only for me but the audio for the car gets a bit weird if the car is slightly damaged, would appreciate it if you can allow me to send a new file if its ok

As said in an previous issue, we will no longer be accepting new vehicle audio sounds as the resource it one of the biggest assets and takes a while to download.

**Comment by No-Yes1** [comment]
Last thing, vehicle goes 212.38mph maxed out anyways, so yeah defo wont be fixed.
