### ISSUE TITLE
Koenigsegg Jesko 

### ISSUE THREAD

**Issue by xFuziii** [fkk-cz/noire_vehicles#1123]
So 2 weeks ago i made a Git Hub about the Koenigsegg Jesko(2mil) to give it a HUGE buff.
This car is one of the fastest cars and has a top speed of 300mph IRL while in the city it hit's bare 170mph.
Like i said in the previous post i don't expect a top speed like this but it would make sense that the car is one of fastest ones in the city.
The asceleration is decent but could be better.
Could i also put in another engine sound for it?
And the car also get dirty way to fast if this could maybe get fixed aswell?

Thank for your time and understanding.

**Comment by MinoritySanta** [comment]
When I first got into the city, my goal was to save for this car.  I'm glad I test drove it first

Would love to see this buffed also

**Comment by No-Yes1** [comment]
You already have an open issue regarding this https://github.com/fkk-cz/noire_vehicles/issues/1087. Don't duplicate/make multiple issues.
