### ISSUE TITLE
Supporter Vehicle 2001 Chevy Suburban 

### ISSUE THREAD

**Issue by 01Elly** [fkk-cz/noire_vehicles#1124]
Hello there, 
I have a issue with supporter vehicle 2001 Chevy Suburban. 
                                                                            This vehicle has a towing hitch in the back as shown in the video, However, when trying to attach a trailer it doesn't attach to the truck Chevy Suburban can tow a trailer in the back IRL the vehicle in game already has the towing hitch on the truck and It will be obligated if this can be added in game as well. Moreover, The Chevy Suburban is not that great, this truck only has 750 trunk space. Adding a small trailer to it will not give any kind of advantage to the player using that truck. 
                                                            That said I think adding a small trailer to this truck as it already has a hitch will be phenomenal. I Hope The Dev's Will Consider This And I Will Be Thankful To Them. 
Thank you. 
Video - https://www.youtube.com/watch?v=-RxJ3bmkv70

**Comment by No-Yes1** [comment]
Added support for the small trailer in https://github.com/fkk-cz/noire_vehicles/commit/26e22038d4b84649bd57a3af0af8f7d15dc1bd67. Please wait until this merged.

**Comment by 01Elly** [comment]
Hello there once again 
Thank you for taking in this issue and helping out with this. I really appreciate this. 
However, with all due respect,
After testing I found that its either the trailer is not working properly or the things are not added properly or the server didn't restarted yet. Please guide me if im wrong. 
https://youtu.be/HGoGQAhDOH8

**Comment by gxdsent** [comment]
> 

most likely the changes aren’t merged yet. they don’t go in over restart one by one, changes are usually pushed through all at once so it’s one big group instead of each car one by one all the time
