### ISSUE TITLE
New 2017 Ram 3500---hitches not active

### ISSUE THREAD

**Issue by MinoritySanta** [fkk-cz/noire_vehicles#1126]
Just bought the vehicle and the hitches don't appear to be active.  There should be a working small trailer and gooseneck.  There was a note in the GTAV mods with directions if this helps

https://www.gta5-mods.com/vehicles/2017-dodge-ram-3500

**Comment by xFooliee** [comment]
Yes could we please get the bed hitch fixed so i can use my gooseneck

**Comment by SimonRileyLA** [comment]
Very great looking trucks. When the hitches get fixed it will be awesome!

**Comment by No-Yes1** [comment]
Added support for both the small trailer/gooseneck trailer. https://github.com/fkk-cz/noire_vehicles/commit/112fa9043a915f01a7a50dd6d7a96777bd35aff8. Please wait until this is merged.

**Comment by MinoritySanta** [comment]
So the hitches work now, but something is still off..  The gooseneck trailer connects to the small trailer hitch and you get no power from it. 15 mph max

I don't know if it needs more torque/towing power or maybe the small trailer hitch just needs to be deactivated.  ??

**Comment by No-Yes1** [comment]
That's a model issue and can't be fixed, small trailer works fine, removing support for gooseneck.
