### ISSUE TITLE
1984 cutlass donk tweak

### ISSUE THREAD

**Issue by Corruptpitbull** [fkk-cz/noire_vehicles#1127]
the donks bounce when your driving and even when there isn't a bump

**Comment by No-Yes1** [comment]
Not at all helpful. What donks _specifically_

**Comment by Corruptpitbull** [comment]
The 1984 cutlass donk

**Comment by No-Yes1** [comment]
Fixed in https://github.com/fkk-cz/noire_vehicles/commit/7bfa644920891ff890cb74c21012c4db4ada3b57. Please wait until this is merged live.
