### ISSUE TITLE
2019 Mitsubishi Lancer EVO

### ISSUE THREAD

**Issue by FukBerk** [fkk-cz/noire_vehicles#1129]
Would it be possible to get the speed buffed a little bit? The car cost around 150k at PDM and it only goes roughly 145mph. I think for the money it should go a little faster as its predecessor (Evo 9) goes about the same speed and cost 40k. I understand that it is a lot bigger (its model in the city is actually super big too) and weights more but these cars are still able to hit 180+ when modified irl. Understandable it shouldn't be that fast in the city since its only a 4 cylinder but maybe 160-170 top speed would be appropriate.

**Comment by No-Yes1** [comment]
Fixed in https://github.com/fkk-cz/noire_vehicles/commit/72103c6da1ecf5001fbf6fa0f960284e3077c3dd. Please wait until this is merged.
