### ISSUE TITLE
buff 2020 supra

### ISSUE THREAD

**Issue by Envy12345** [fkk-cz/noire_vehicles#113]
its a whole lot slower than the bronco for 20k more there is no reason that the heavy bronco should be faster than the supra only hitting 125

**Comment by fkk-cz** [comment]
https://github.com/fkk-cz/noire_vehicles/commit/7fd4684c427453906f25ff97141f7c0520e9de3f#diff-5299aed2474e2e1fc8258dcd7dc2b15493e8abe317be20b6e02ce19bbc322726
