### ISSUE TITLE
Attach support for small vehicles on the bed of trucks. Dodge Ram 3500 trailer support as well.

### ISSUE THREAD

**Issue by xFooliee** [fkk-cz/noire_vehicles#1130]
Wanted to add an idea for trucks. Maybe a way that we could have bike/atv ramps for trucks so that way they can haul small things such as bikes and atv's and sportsbikes which is done in reality. Be able to put the tailgate down for more room and have a ramp to ride them up and attach to the back of the truck.

Also wanted to add about giving trailer support for the gooseneck on the new Dodge Ram 3500.

**Comment by No-Yes1** [comment]
> Wanted to add an idea for trucks. Maybe a way that we could have bike/atv ramps for trucks so that way they can haul small things such as bikes and atv's and sportsbikes which is done in reality. Be able to put the tailgate down for more room and have a ramp to ride them up and attach to the back of the truck.

_what_ - this is model issues and can't acc be implented.

> Also wanted to add about giving trailer support for the gooseneck on the new Dodge Ram 3500.
which new 3500. You need to specific vehicle names.

**Comment by xFooliee** [comment]
> > Wanted to add an idea for trucks. Maybe a way that we could have bike/atv ramps for trucks so that way they can haul small things such as bikes and atv's and sportsbikes which is done in reality. Be able to put the tailgate down for more room and have a ramp to ride them up and attach to the back of the truck.
> 
> _what_ - this is model issues and can't acc be implented.
> 
> > Also wanted to add about giving trailer support for the gooseneck on the new Dodge Ram 3500.
> > which new 3500. You need to specific vehicle names.

2017 3500 Dodge Ram

**Comment by No-Yes1** [comment]
Already an active issue #1126 - please see open issues prior to opening one.
