### ISSUE TITLE
Lambo SC18 has to licence plate

### ISSUE THREAD

**Issue by Ethioking** [fkk-cz/noire_vehicles#1131]
I was told by an officer that i could receive a ticket for not haveing a licence plate but there is no option to get one, page up has no options and i cant pick one at the Los Santos customs

**Comment by No-Yes1** [comment]
this is a model issue and can not be fixed/added - lspd/sahp should not give tickets for the sc18 as it is unable to get plates. should be removed/recalled at that point.
