### ISSUE TITLE
1998 Subaru Impreza 22B-STI

### ISSUE THREAD

**Issue by FukBerk** [fkk-cz/noire_vehicles#1132]
Is there anyway to improve the handling at slower speeds on the 22B-STI? It feels like an SUV when trying to make maneuvers at slower speeds (20-30mph). It cost 65k at PDM which is 15k more than its 4 door successor (Subaru Impreza WRX STI) and it should handle better at slower speeds since it weights less since it's only a 2 door. I don't think the speed needs to be changed at all because it cost more, is about equal top speed to the 4 door version (145mph-ish), and doesn't shoot flames or smoke which usually indicates a "healthier" EJ.

**Comment by No-Yes1** [comment]
Fixed in https://github.com/fkk-cz/noire_vehicles/commit/97c8b8b98626242085b7dbe036733b3372b48736. Please wait until this is merged.
