### ISSUE TITLE
2022 BMW M5 Competition (supporter)

### ISSUE THREAD

**Issue by FertileSphere** [fkk-cz/noire_vehicles#1135]
Is it possible to install a new muffler (tone down the sound file) on the BMW/s, things is stupid loud even with the game volume down. I have trouble thinking let alone hearing anything else.

**Comment by No-Yes1** [comment]
We're not adding anymore new custom sounds in, if there's already one in-game that sounds realistic, then sure.

**Comment by FertileSphere** [comment]
> We're not adding anymore new custom sounds in, if there's already one in-game that sounds realistic, then sure.

I just want it abit quiter, not asking for new sounds.

**Comment by No-Yes1** [comment]
Can't do that as it's the audio itself so we are unable to turn down the sound.

**Comment by FertileSphere** [comment]
> Can't do that as it's the audio itself so we are unable to turn down the sound.

okay! I'll see if there is a quiter sound already in city. Thanks for replying
