### ISSUE TITLE
Supra A90

### ISSUE THREAD

**Issue by somedudenamedrush** [fkk-cz/noire_vehicles#1137]
the car currently has no sound/modkit and is slower than the 70k supra
if it handled the same as the 70k supra but had a little bit more speed/accel it would be nice

**Comment by No-Yes1** [comment]
> the car currently has no sound

Tweaked sound to the ``tsgr20`` https://github.com/fkk-cz/noire_vehicles/commit/5aaaef98045f0f6155d9513c1ae70be9752e98c8

Swapped modkit id: https://github.com/fkk-cz/noire_vehicles/commit/b5d5e10dce864fa549684650df2971fe4081be33

>  slower than the 70k supra
 
Tweaked handling https://github.com/fkk-cz/noire_vehicles/commit/9b5b30998668d75579e15dd2e4bec975637ebd3b. Please wait until this is merged.
