### ISSUE TITLE
Supra A90 interior issue 

### ISSUE THREAD

**Issue by somedudenamedrush** [fkk-cz/noire_vehicles#1138]
so we have this car in the city but it was updated so u can change the ugly cyan interior wondering if we could get the latest version put in

https://www.gta5-mods.com/vehicles/2020-toyota-supra-a90-addon-template-wheels-tuning#comments_tab

**Comment by No-Yes1** [comment]
@fkk-cz Can you take a look at this/swap out the stream files.

**Comment by somedudenamedrush** [comment]
Any Update to this ?

**Comment by HvrdNo** [comment]
Any Update to this as I have the car as well

**Comment by fkk-cz** [comment]
Replaced the stream files. No idea if this will work, given the fact there appears to be 179 new #fts.
