### ISSUE TITLE
Camaro ZL1

### ISSUE THREAD

**Issue by vSxpreme** [fkk-cz/noire_vehicles#1140]
I feel like the ZL1 Should be faster especially for the price and irl it’s supercharged and in game it barely can beat a mustang

**Comment by No-Yes1** [comment]
Be helpful if you could provide the year as there is multiple zl1's....

**Comment by vSxpreme** [comment]
the 2018

**Comment by No-Yes1** [comment]
Fixed in https://github.com/fkk-cz/noire_vehicles/commit/f154cbb135eaa3810773434b3d309db409d28d4b. Please wait until this is merged
