### ISSUE TITLE
Ferrari 458 prior top speed and acceleration 

### ISSUE THREAD

**Issue by Theonewton** [fkk-cz/noire_vehicles#1141]
Personally  I think the car is quite slow and for the price of 239k I think it could be better ,top speed of a 458 is 202 but top speed in city is around 190 and the acceleration is very slow when you get passed 100 the acceleration is terrible am not sure if it’s a simple fix but would be great

**Comment by No-Yes1** [comment]
> top speed of a 458 is 202 but top speed in city is around 190

_what_ - this makes no sense. Why would we fine tune a car to only go >10mph more. For the price of the vehicle, the handling is fine.
