### ISSUE TITLE
Lfa buff part 3

### ISSUE THREAD

**Issue by Kaiyashi9** [fkk-cz/noire_vehicles#1142]
Sorry to make another issue on the lfa but there isn't a notice able change I put the same handling.meta into a test server I had and it got up to 227 I'm not sure if we are running a different script on here interfering with it but I would just increase the drive force and see what happens

**Comment by No-Yes1** [comment]
>  I had and it got up to 227 

That doesn't make sense and is non-realistic as the vehicle top speed is 202mph. Furthermore, for the price of the vehicle. We will won't be tweaking this vehicle anymore.

**Comment by No-Yes1** [comment]
Ok - I see what happened... I tweaked the wrong lfa... appears to be two. A broken one/one that is not in PDM/one that is in PDM.
