### ISSUE TITLE
135,000$ more than the roadster and only beats the top speed by 3mph

### ISSUE THREAD

**Issue by Vanilla12345** [fkk-cz/noire_vehicles#1143]
https://medal.tv/games/gta-v/clips/oBPle0WOVV9L1/d1337eZ86Hqa?invite=cr-MSw3Yk4sNjg5NzMwMzQs
please make the 2017 NIO EP9 go faster, the NIO EP9 goes 194 irl so i think it should at least hit 180mph in the city.
"Performance. The EP9 can accelerate from 0 to 100 km/h (62 mph) in 2.7 seconds, 200 km/h (124 mph) in 7.1 seconds, and 300 km/h (186 mph) in 15.9 seconds, as demonstrated by Richard Hammond in The Grand Tour. The car can achieve a top speed of 313 km/h (194 mph)."

**Comment by viigyD** [comment]
iirc, this vehicle was nerfed a while ago because a ton of people bought and abused it. In general, electric vehicles are hard to make true to life without making them extremely OP. It's prob the same reason why the Model S and Taycan drive like boats in the city, and why the roadster is very squirrely and made of glass.

**Comment by Vanilla12345** [comment]
> iirc, this vehicle was nerfed a while ago because a ton of people bought and abused it. In general, electric vehicles are hard to make true to life without making them extremely OP. It's prob the same reason why the Model S and Taycan drive like boats in the city, and why the roadster is very squirrely and made of glass.

yeah but now you can barely see 1 on the road and it already drives like crap just make it hit 180mph or something higher, bc i bought and if they say they wont do anything to it i really just want a full refund bc im not even going to 300k if i refund and i really like the look of the car but its so slow and drives like crap and its mad of glass and is squirrely like it kinda sucks now

**Comment by No-Yes1** [comment]
Slightly increased top speed/decreased drag. Don't be like a certain person and abuse it for everyone and the vehicle wouldn't be nerfed. https://github.com/fkk-cz/noire_vehicles/commit/ae822cfbaf155c961c60eb386d9d3f91045776df. Please wait until this is merged.
