### ISSUE TITLE
1998 Subaru 22b sti needs to be fixed or changed in car dealership

### ISSUE THREAD

**Issue by Wrxghost1** [fkk-cz/noire_vehicles#1144]
The Supporter Vehicle version of the 98' 22b subaru sti is $66k and is advertised to be heavier 3000+ pounds and slower with 350 torque. The TUNER VEHICLE version of 98' 22b Subaru sti (Sultan RS Classic) is $248k and is advertised to be a lighter 2500 pounds and faster with 450 torque. However AFTER every max upgrade done to both cars remain the same speed and literally the same accessory modifications. 
There is absolutely no difference between the two vehicle other than the $180k price difference and the wrongly advertised speed. 
The Tuner vehicle cannot be traded in back to the car dealership even for it 70% MSRP or whatever. I felt as I've been wronged by the city and want this fixed ASAP. Either take down the TUNER VEHICLE tab in the dealership. or Make those vehicles eligible to trade in back to the dealer ship for the 70%.
ADMINS Explained the difference one being in Vanilla GTAO and one being a supporter vehicle. it shouldn't matter, i understand that the vehicles speed isnt the cities fault. but the fact that 2 of the exact same cars are listed for 2 completely different prices does not seem reasonable and can be confusing. especially if the one that is more expensive says its faster.

**Comment by Stagonium** [comment]
They aren't the same car though, the GTAO car is based off of that Subaru but it is not advertised as such. You had the opportunity to test drive both cars, see their performance, and you chose the one that was more expensive and apparently slower. That was your choice and no one else's. No one can help you recover any money from the car except someone at UCL who is interested. Wish you the best in the endeavor up north.

**Comment by Yush6969** [comment]
Free my darg

**Comment by Wrxghost1** [comment]
okay then disable the Tuner vehicle tab. that shits a fucking scam to anyone in the city

**Comment by gxdsent** [comment]
> okay then disable the Tuner vehicle tab. that shits a fucking scam to anyone in the city

i’d say opposite, very few people have those cars and the customizations are endless. paying for the uniqueness is the point of the tuners, not for function
