### ISSUE TITLE
2019 Chevrolet Corvette Zr1

### ISSUE THREAD

**Issue by TheGodfatha** [fkk-cz/noire_vehicles#1145]
Not really an issue more so a question. I wanted to know if it’s possible to get a widebody kit for the corvette. It’s basically the same car as the Demon swap and that has a widebody so I would really want one for this car it would complete it for me honestly. Not for it to come widebody in the dealership but make it an option in Los santos customs under body parts category.

**Comment by No-Yes1** [comment]
Sadly not as it's a model issue and can't be implanted.
