### ISSUE TITLE
1990 Ferrari F40 Broken Textures

### ISSUE THREAD

**Issue by mfried456** [fkk-cz/noire_vehicles#1147]
For some reason, when the 1990 Ferrari F40 collects dirt, it turns the car's color to a neon green/mint in some spots. I believe it is "dirt" as washing the car removes the color for a short period of time. Also, I was hoping the breaking could receive a slight buff. Thanks

**Comment by No-Yes1** [comment]
Fixed breaking issues https://github.com/fkk-cz/noire_vehicles/commit/6077072662195e6bb9b4503632efb08a46cc8590. Please wait for this to merge. Leaving open for broken textures.

**Comment by fkk-cz** [comment]
Should be fixed on next restart.
