### ISSUE TITLE
pls make the 1998 Supra go faster

### ISSUE THREAD

**Issue by Vanilla12345** [fkk-cz/noire_vehicles#1148]
Irl the supra goes 177MPH and in game it only goes 160MPH pls make it go faster

**Comment by gxdsent** [comment]
> Irl the supra goes 177MPH and in game it only goes 160MPH pls make it go faster

to be fair, with the speed limiter (for NA versions at least) a stock one probably averages around 145-150. that speed is pretty accurate. 155-160 would be normal for an mk iv. (upgrades obviously bump it up a bit)

**Comment by Vanilla12345** [comment]
Your right I did not think about it's that way> > Irl the supra goes 177MPH and in game it only goes 160MPH pls make it go faster
> 
> 
> 
> to be fair, with the speed limiter (for NA versions at least) a stock one probably averages around 145-150. that speed is pretty accurate. 155-160 would be normal for an mk iv. (upgrades obviously bump it up a bit)
