### ISSUE TITLE
koenigsegg jesko

### ISSUE THREAD

**Issue by DefineFusion** [fkk-cz/noire_vehicles#1149]
I know that this vehicle was recently buffed however I think that is still a little slow compared to other vehicles of lower price and for it’s price point in general. IRL the Jesko reaches 330mph, which is not what I’m asking for at all. I’ve been driving the Jesko now for a full day and the speed from 0-200mph is great however it struggles to get even past 213mph on flat ground and in certain areas of the map it seems to pick up but the top speed is never consistent and I have a hard time getting it past 215mph. I did multiple straight races against the Aventador S which is $1,500,000 and have lost to its acceleration and top speed. I think that another minor buff to this $2,000,000 car would be needed and make it more worth its price point in the city. If it were able to maintain 230-240mph flat ground I feel like it would fit is pricing better. As for take the Rimac is the same price and now goes 200mph, but the advantages of that is no gas, and faster acceleration. So currently for the same price it seems that the Rimacs pros outweighs the Jeskos. One more thing to add is that it gets very dirty very quickly. Thank you.

**Comment by Scubaaaaa** [comment]
With the current price of the Jesko at $2,000,000 I will say that the car is literally perfect for the price. It easily maintains 230 while gunning it up the freeway. I can say that it easily compares to the $2,500,000 Ferrari FXXK as far as speed. With the fact of it getting dirty that would be the dirt map of the vehicle, which I don't believe they can change.

**Comment by No-Yes1** [comment]
See above -- buffed values slightly https://github.com/fkk-cz/noire_vehicles/commit/81064855616a334df924c26962c0776a2a5d7973. Should be faster then the aventadors. Please wait until this is merged.
