### ISSUE TITLE
koenigsegg agera rs max speed enhance

### ISSUE THREAD

**Issue by Poggers3361** [fkk-cz/noire_vehicles#1150]
I believe that the koenigsegg agera rs current top speed of 200 is a bit too low for a supporter car for 500k. because regular cars for  300-400k are faster than it. so i think that the top speed should at least be around the 210-215 ish area since the real life top speed is 277.

**Comment by tythetanman** [comment]
That would put its top speed around the exact Top 
 of the $1.1 million Lamborghini Huracan EVO

**Comment by PsychoticCore** [comment]
They don't go off IRL top speed and for 500k that's a pretty banging speed... My $1.5 Million Aventador doesn't go much much faster than 220 on flat ground

**Comment by Poggers3361** [comment]
maybe 215 is a bit ambitious but at least 205.

**Comment by No-Yes1** [comment]
For the price of vehicle, the car is fine and wont be tweaked.
