### ISSUE TITLE
Rimac C Two 2 mil

### ISSUE THREAD

**Issue by RichieRockefeller** [fkk-cz/noire_vehicles#1151]
The new buff on the Rimac C Two honestly made me extremely happy because I felt as though I was getting an amazing deal for an electric car of my dreams in this city that goes 200 mph. I did notice that the armor got nerfed and that is 100% reasonable that, as you said, people don't buy this vehicle solely to avoid interactions with Law Enforcement and just to get away instantly. My only thing here is if the vehicle is practically a one-shot if it hits something to fully break down; is the acceleration really needed to be dropped so hard? I will show you two examples of each. This is me racing the roadster in test drive (both are equivalent to fully upgraded since they are electric). [https://medal.tv/games/gta-v/clips/oZ1hiJU42ebu9/d1337UIv2koh?invite=cr-MSxMa3EsMzgwNzE5MzMs](url) To compare these two vehicles, the roadster tops out at 157 mph and the rimac at 199 mph. At this point, both vehicles have similar armor and the top speed difference is around 42 mph. The roadster is listed as 200k and the rimac is listed as 2 mil. I understand that it is difficult to make everyone happy and you guys worked hard to keep it balanced but would there be any possibility if the acceleration can be buffed to a fair spot? These are some clips of the current armor and where it's at. [https://medal.tv/games/gta-v/clips/oZfwt-kz4Kk7r/d1337cRMEmJe?invite=cr-MSxIaUIsMzgwNzE5MzMs](url) [https://medal.tv/games/gta-v/clips/oZp3xnv2JIT4k/d1337gOfUKCU?invite=cr-MSxiM0wsMzgwNzE5MzMs](url) This last clip shows a mock robbery of me going fast and hitting a wall... here it is, [https://medal.tv/games/gta-v/clips/oZvOKwaYSmxtF/d1337Nctch1B?invite=cr-MSxxQmQsMzgwNzE5MzMs](url) the update, the armor was pretty crazy (maybe too good) and the acceleration was unmatched. Now, the acceleration got hit to the point where (being an electric car) gets beat by cars like the 2019 Mclaren Senna which is 715k, and the 2020 Koenigsegg Jesko which is 2 mil (off the launch and top speed).

**Comment by MinoritySanta** [comment]
The acceleration revert hasn't been merged yet.  It will be fixed
