### ISSUE TITLE
2017 Koenigsegg Agera RS sound improvement/replace

### ISSUE THREAD

**Issue by eliaxes** [fkk-cz/noire_vehicles#1152]
i think the supporter car 2017 Koenigsegg agera RS needs a better sound since now i think it has an original gta car sound. However the sound doesn't fit the car if u compare it to a real life Agera RS

**Comment by RichieRockefeller** [comment]
Skip to 0:35: [](https://www.youtube.com/watch?v=T3U7Z-9pKns)
[](https://www.gta5-mods.com/vehicles/koenigsegg-agerars-sound)

**Comment by RichieRockefeller** [comment]
Skip to 0:35: https://www.youtube.com/watch?v=T3U7Z-9pKns
https://www.gta5-mods.com/vehicles/koenigsegg-agerars-sound

**Comment by No-Yes1** [comment]
We're not adding anymore custom audio sounds as it's a huge resource. If you find a sound that is somewhat realistic that is already in game then I can change it to that.

**Comment by RichieRockefeller** [comment]
> We're not adding anymore custom audio sounds as it's a huge resource. If you find a sound that is somewhat realistic that is already in game then I can change it to that.

The Koenigsegg Jesko has a 5.0 L V8 just like the Agera RS so maybe this would be the best fit?

**Comment by No-Yes1** [comment]
> > We're not adding anymore custom audio sounds as it's a huge resource. If you find a sound that is somewhat realistic that is already in game then I can change it to that.
> 
> The Koenigsegg Jesko has a 5.0 L V8 just like the Agera RS so maybe this would be the best fit?

That is also an vanilla audio hash. Do you want it changed https://github.com/fkk-cz/noire_vehicles/blob/effd00fa5e48f0c6657ddc7bc3d32450e79c29a2/DATA/jesko-data/vehicles.meta#L18

**Comment by RichieRockefeller** [comment]
> > > We're not adding anymore custom audio sounds as it's a huge resource. If you find a sound that is somewhat realistic that is already in game then I can change it to that.
> > 
> > 
> > The Koenigsegg Jesko has a 5.0 L V8 just like the Agera RS so maybe this would be the best fit?
> 
> That is also an vanilla audio hash. Do you want it changed
> 
> https://github.com/fkk-cz/noire_vehicles/blob/effd00fa5e48f0c6657ddc7bc3d32450e79c29a2/DATA/jesko-data/vehicles.meta#L18

Let me go to PDM to compare all of the V8 engine cars and determine which may be the best fit.

**Comment by RichieRockefeller** [comment]
There were a bunch of V8 engine cars which were very different but I believe the 2019 Mclaren Senna is a good option or the 2019 Aston Martin Vantage which was very good too. The 2022 Porsche Panamera S already shares the same sound as the Lambo Urus so maybe we should keep those out of this.

**Comment by Poggers3361** [comment]
> > > We're not adding anymore custom audio sounds as it's a huge resource. If you find a sound that is somewhat realistic that is already in game then I can change it to that.
> > 
> > 
> > The Koenigsegg Jesko has a 5.0 L V8 just like the Agera RS so maybe this would be the best fit?
> 
> That is also an vanilla audio hash. Do you want it changed
> 
> https://github.com/fkk-cz/noire_vehicles/blob/effd00fa5e48f0c6657ddc7bc3d32450e79c29a2/DATA/jesko-data/vehicles.meta#L18

if he finds a good sound for the jesko can you add that to the agera rs too?

**Comment by RichieRockefeller** [comment]
I would say, in my opinion, for the Agera RS I would go with the 2018 Aston Martin DBS sound and for the Jesko I would go with either the 2019 Aston Martin Vantage, 2020 Audi Rs7, or the 1990 Ferarri F40. All of these cars have a V8 engine. I want to see others' opinions about these sounds and we can go from there. It is difficult to please everyone but the cars I listed seem to be in between loud and quiet.

**Comment by Poggers3361** [comment]
> I would say, in my opinion, for the Agera RS I would go with the 2018 Aston Martin DBS sound and for the Jesko I would go with either the 2019 Aston Martin Vantage, 2020 Audi Rs7, or the 1990 Ferarri F40. All of these cars have a V8 engine. I want to see others' opinions about these sounds and we can go from there. It is difficult to please everyone but the cars I listed seem to be in between loud and quiet.

i think that these sounds are perfect for these cars and would fit well

**Comment by No-Yes1** [comment]
Updated audio hash to the following:

Agerars = 2018 Aston Martin DBS
Jesko = 2020 Audi RS7.

Please wait for this to merge live.
