### ISSUE TITLE
Lamborghini Urus Texture

### ISSUE THREAD

**Issue by Ell34** [fkk-cz/noire_vehicles#1154]
Since the texture update on the vehicles, I’ve noticed the default tires on the urus are slightly Chrome looking, and the Lamborghini badge on the hood is gone, it’s just a solid colour, and on the back where it would say Lamborghini is also gone. Yes it’s a small issue but don’t come at me

**Comment by No-Yes1** [comment]
deal w/ it... joking

**Comment by Ell34** [comment]
> deal w/ it... joking

Dude that’s the fastest response I’ve ever got LMAO
