### ISSUE TITLE
E63 Sound change

### ISSUE THREAD

**Issue by TdotG** [fkk-cz/noire_vehicles#1155]
Anyway you could change it to the same sound file as the AMG GT Black Series. The E63 is a 5.5L V8 the sound file it has right now sounds like a vanilla sound. Would appreciate if it gets changed, thanks.

**Comment by TdotG** [comment]
Also if there is anway to increase the top speed, the car IRL hits 186 in city 155-165

**Comment by somedudenamedrush** [comment]
> Also if there is anway to increase the top speed, the car IRL hits 186 in city 155-165

the sound will prolly be updated but im gunna be honest i own the car making it hit 186 for the price of 120k is overkill 
its probably the best 4 door in the city to begin with

**Comment by TdotG** [comment]
i mean the panamera i used to have would hit 190+, the E63 has to go downhill to hit max speed on flat its much slower

**Comment by PsychoticCore** [comment]
> i mean the panamera i used to have would hit 190+, the E63 has to go downhill to hit max speed on flat its much slower
I have a panamera and I can confirm that thing doesnt reach 190 flat... maybe on the downhill entering LS but no shot it goes that quick on flat ground

**Comment by TdotG** [comment]
Shii mine does Lmfao

**Comment by TdotG** [comment]
Just takes a while

**Comment by No-Yes1** [comment]
> Also if there is anway to increase the top speed, the car IRL hits 186 in city 155-165

I'm not increasing the top speed by that small amount. As stated above, the vehicle for 120K is fine.

**Comment by No-Yes1** [comment]
I'll take a look at the audio hash later.

**Comment by No-Yes1** [comment]
Fixed in https://github.com/fkk-cz/noire_vehicles/commit/12735470127f8c9d73b8aa8710708f2c1d627a38. Please wait for this to merge live.
