### ISSUE TITLE
2017 Dodge RAM 3500 trailer turn glitch

### ISSUE THREAD

**Issue by xFooliee** [fkk-cz/noire_vehicles#1156]
When driving with a small trailer, the truck barely wants to turn, basically blocks the truck from turning in which makes it hard to navigate. Does it going forward and backwards, in this video I'm including, it shows in reverse to give you a better view of whats going on.
https://medal.tv/games/gta-v/clips/oXqKG8rc82T7F/d13374WoRdBG?invite=cr-MSxsRlQsNjQ5MzgwNjYs

**Comment by No-Yes1** [comment]
Fixed in https://github.com/fkk-cz/noire_vehicles/commit/da7e9d2e807cb08c28492d4cad863b8145ae49a7. Please wait for this to merge live.
