### ISSUE TITLE
Lambo Centenario 

### ISSUE THREAD

**Issue by MinoritySanta** [fkk-cz/noire_vehicles#1159]
Top speed is probably fine, just requesting acceleration tweak. 

$2 million PDM price and it takes a long time for it to even hit 160-180.

**Comment by No-Yes1** [comment]
Fixed in https://github.com/fkk-cz/noire_vehicles/commit/7c2866a2262e7cb880d775cca82e8f938b7d2699. Please wait for this to merge live.
