### ISSUE TITLE
Mercedes AMG GT 63 S - Armor bump

### ISSUE THREAD

**Issue by YeagerGTA** [fkk-cz/noire_vehicles#1160]
I think the performance of this vehicle is pretty solid right now, the only thing I am noticing is that it really sensitive to bumps in the backend. Case in point, someone hit me from behind while I was moving at about 20-25mph faster than I was going and totally disabled the vehicle. This has happened a few times. It handles front bumps fairly well, though even that could be adjusted slightly. Not looking to get it overpowered but feel as a luxury performance car, it should be a bit more solid and be able take a bit more damage.

**Comment by No-Yes1** [comment]
https://github.com/fkk-cz/noire_vehicles/blob/1984790c553d9b9e0eaddfe2b12e242cf5b415b6/DATA/gt63samg_data/handling.meta#L41-L44

The values of the vehicle are fine are standard. This will not be fixed.
