### ISSUE TITLE
Honda Civic Type R FK8 Sound Improvement

### ISSUE THREAD

**Issue by Jaadoohz** [fkk-cz/noire_vehicles#1161]
I was wondering if it was possible to improve the sound for the FK8 Type R. There’s a few sound files i’ve found online in regards to this vehicle. 

https://www.gta5-mods.com/vehicles/honda-k20a-k20c-2-0-i4-engine-sound-oiv-add-on-fivem-sound

**Comment by No-Yes1** [comment]
We're not adding in any new custom sounds, if you find one that's already in-game that sounds similar, put it in here and i'll replace it with that.

**Comment by No-Yes1** [comment]
Closing as no response from issue creator.
