### ISSUE TITLE
2020 Dodge Charger Hellcat $268k No Noticeable Change

### ISSUE THREAD

**Issue by RichieRockefeller** [fkk-cz/noire_vehicles#1163]
The 2020 Dodge Charger Hellcat that is $268k got fixed about 3 weeks ago and it seems like it is the same to be honest. I raced the cheaper $95k 2020 Dodge Charger Hellcat Daytona and it was faster by a good amount for the price difference. In "DATA" the car that got tweaked was the "sjdodge", could this be the wrong file? I also noticed that the Daytona has better armor, is this intentional? These are two clips of the races that I did. **_https://medal.tv/games/gta-v/clips/pikZZjh1fjn9C/d1337NOHYPxk?invite=cr-MSxvRXksMzgwNzE5MzMs_** and **_https://medal.tv/games/gta-v/clips/pilRiu8IANc_N/d1337fCl7mjh?invite=cr-MSwxeW4sMzgwNzE5MzMs_**

**Comment by No-Yes1** [comment]
sjdodge is the 2020 Dodge Charger hellcat.

**Comment by No-Yes1** [comment]
Model: sjdodge Name: 2020 Dodge Charger SRT Hellcat

**Comment by No-Yes1** [comment]
Nerfed the daytona, not sure why it's meant to go that fast when it's 95K, i'm not increasing the top speed of the other one to 200mph. https://github.com/fkk-cz/noire_vehicles/commit/445a08c5c9abe7d35ac81df039ebbca13a384cbf. Please wait for this to be merged.
