### ISSUE TITLE
Mclaren 720 S N Largo slower than 720 S Spider

### ISSUE THREAD

**Issue by guwop** [fkk-cz/noire_vehicles#1165]
Hello I would like to bring to attention the Mclaren 720 S N Largo (weight 3,128 lb) being slower than the 720S Spider(weight 3,236 lb) 

The McLaren 720 S Spider is a convertible which makes it heavier and slower by default, with this ticket I hope to accomplish getting the 720 S N-Largo either at the same speed of the 720 S Spider or slightly faster, I've tested both of these cars ingame with a drag race and the 720 S N-Largo was blown out of the water by the convertible version.

Thank you for reading.

**Comment by No-Yes1** [comment]
Fixed in https://github.com/fkk-cz/noire_vehicles/commit/1984790c553d9b9e0eaddfe2b12e242cf5b415b6. Please wait for this to be merged live.
