### ISSUE TITLE
Koenigsegg Jesko: Sound Change

### ISSUE THREAD

**Issue by DefineFusion** [fkk-cz/noire_vehicles#1169]
So recently the Jesko sound was changed to the Audi Rs7 sound and I can speak for all the Jesko owners on this one and we don’t like that sound and it just doesn’t fit the car. I know that y’all aren’t taking sounds that aren’t in the city already, but I think as well as a few other Jesko owners that the Aston Martin Valhalla sound would fit best with this car. Both the Valhalla and Jesko are twin-turbo V8s and we feel that the Valhalla would be the best. As it’s not too loud or too quite and quite different then most sounding V8s in the city. So if we could get the Valhalla sound on the Jesko that would be great. Thank you.

**Comment by PsychoticCore** [comment]
Agreed

**Comment by No-Yes1** [comment]
Can't you all agree on one sound... this will be the last time the audio would be touched.

**Comment by No-Yes1** [comment]
Fixed in https://github.com/fkk-cz/noire_vehicles/commit/51ba1c06c57a931d050561856ded373ddf850a72. Please wait for this to merge.
