### ISSUE TITLE
Supporter Corvette C8 Mansaug

### ISSUE THREAD

**Issue by AntonioAres** [fkk-cz/noire_vehicles#1170]
So when trying to upgrade the car in the tuning shop, it won't allow any transmission upgrades. Idk if this Is a common glitch/bug in the sever

**Comment by No-Yes1** [comment]
Fixed in https://github.com/fkk-cz/noire_vehicles/commit/16bed5e1df15ce9b84492dd75804a063b6f52070. Please wait for this to be merged.
