### ISSUE TITLE
2016 Charger SRT Hellcat texture issues

### ISSUE THREAD

**Issue by JazzGgg** [fkk-cz/noire_vehicles#1173]
Its missing a hellcat badge on the right side, the 2 front door panels don't match the car, and the engine bay is a 6.4-liter hemi not the hellcat engine which is the 6.2-liter supercharged engine

**Comment by CasperBoiRL** [comment]
honestly, can you just put the scat logos on the side? It would be a lot easier, and there’s no scat in the game

**Comment by fkk-cz** [comment]
Should be fixed on next restart.

**Comment by fkk-cz** [comment]
Recalling this vehicle -- model seems to be broken, reverting texture compression didn't seem to help.
