### ISSUE TITLE
Koenigsegg Gemera

### ISSUE THREAD

**Issue by gammergrill** [fkk-cz/noire_vehicles#1175]
can yall plzz buf the top speed and the acceleration make the top speed 200 or around there and the acceleration way faster its so slow and the acceleration is not it

**Comment by TdotG** [comment]
I agree, the car is the most expensive 4 door in the city, 500k isnt cheap and for its price its very underwhelming.

**Comment by No-Yes1** [comment]
It's not going 200mph for 500K, can tell you that much.
