### ISSUE TITLE
Toyota Hilux Artics Trailer pulling.

### ISSUE THREAD

**Issue by CasperBoiRL** [fkk-cz/noire_vehicles#1177]
It already has a trailer hitch, all it needs is the ability to pull a small trailer.

**Comment by gxdsent** [comment]
> It already has a trailer hitch, all it needs is the ability to pull a small trailer.

i think there’s a model issue where it can’t connect to trailers. they tried recently to make it work but it’s not possible due to the whoever made the model didn’t take trailers into account

**Comment by CasperBoiRL** [comment]
is there anyway to take a trailer hitch from another model and put it on there to make it work? or is that out of the picture?

**Comment by gxdsent** [comment]
> is there anyway to take a trailer hitch from another model and put it on there to make it work? or is that out of the picture?

unfortunately you’d have to message the creator and have him fix it since we technically can’t go in and change his work from the files we have

**Comment by CasperBoiRL** [comment]
can you send me the link of where you got the model from so i can contact the person?

**Comment by gxdsent** [comment]
pretty sure this was the model that was submitted, but it looks like the last time it was updated was in 2017 so who knows if he’ll respond lol https://www.gta5-mods.com/vehicles/top-gear-toyota-hilux-2007-arctic-trucks-at38

**Comment by CasperBoiRL** [comment]
I messaged him on facebook lmao, hopefully he answers.

**Comment by No-Yes1** [comment]
We do not support trailer adding to vehicles/modify vehicle stream files, so the vehicle will not have a tow hook.
