### ISSUE TITLE
My Veyron was recalled but they're is still a Veyron at the car dealership

### ISSUE THREAD

**Issue by tantatertot** [fkk-cz/noire_vehicles#1179]
I had to sell my Veyron, as it was recalled, and I am confused on how the vehicle can be recalled when the vehicle is still in the game.

**Comment by somedudenamedrush** [comment]
a new model was put in to replace it

**Comment by tantatertot** [comment]
But since I was required to sell the old model because it was recalled shouldn't I get the new model as it is the same vehicle?

**Comment by somedudenamedrush** [comment]
everyone who had the old model had to do the same thing sell and rebuy the new one

**Comment by tantatertot** [comment]
I bought it while I had supporter and I haven't bought supporter since I bought the vehicle so I'm unable to rebuy it though

**Comment by No-Yes1** [comment]
See above. Vehicle was recalled to replace another model.

**Comment by tantatertot** [comment]
how does that make sense at all though how can you make me sell the vehicle for something completely out of my control and just put the car back in the game where I am unable to get it again.
