### ISSUE TITLE
E63 AMG sound issue

### ISSUE THREAD

**Issue by somedudenamedrush** [fkk-cz/noire_vehicles#1180]
whatever sound it has now it causes alot of ppl crashing and probably should be patched asap

**Comment by No-Yes1** [comment]
Are you sure it's the sound?

**Comment by No-Yes1** [comment]
Fixed in https://github.com/fkk-cz/noire_vehicles/commit/0bb565fcc0dd9c8b4a874c442e4a7c72febc98c1. Please wait for this to merge.

**Comment by TdotG** [comment]
I don't think it's the sound, the AMG GT BS has the same sound and it doesn't seem to crash people out of the server. I have had friends crash out but I dont think it's the sound.
