### ISSUE TITLE
2019 ZR1 Top speed adjustment

### ISSUE THREAD

**Issue by whitefeatherr** [fkk-cz/noire_vehicles#1181]
The 2019 ZR1's top speed is around 214 MPH. It only goes 160. Acceleration could be a little quicker. It's a Supercharged 6.2L V8 Vette. 0-60 in 2.9 seconds. It handles amazingly, but the top speed is really lacking this car. Especially since its $178,000. I hope I am not asking for much. Please consider changing it! 

Thank you :)

**Comment by No-Yes1** [comment]
for 178K the speed/handling is fine and will not be tweaked/
