### ISSUE TITLE
Dodge Viper ST Adjustment

### ISSUE THREAD

**Issue by ameripie** [fkk-cz/noire_vehicles#1182]
The Viper top speed is about 181 and costs $465,995 at PDM. There are many cars a lot less that go at similar or faster speeds like the $335k Demon, $231k Stingray, and $160k ZL1. I feel like its top speed should be buffed to match the price range it's in.

**Comment by No-Yes1** [comment]
Fixed in https://github.com/fkk-cz/noire_vehicles/commit/1dfe53e42b5a433d0127d4dd4941f7d12d7bc56a. Please wait for this to merge.
