### ISSUE TITLE
2019 ZR1 Corvette Top Speed.

### ISSUE THREAD

**Issue by whitefeatherr** [fkk-cz/noire_vehicles#1185]
The 2019 ZR1 Corvette's top speed needs to be 200-220mph. It only goes 160mph. Since it's $178,000 it would've been a fast car. A $40,000 base charger goes 180....Anyway to just up the top speed?

**Comment by ix1ali** [comment]
a camaro zl1 is around the same price
https://medal.tv/games/gta-v/clips/q36EzSXygEl0j/d1337Xqq3cnL?invite=cr-MSx3VGEsNzE5NzM5MTgs
also top 180 mph

**Comment by Scubaaaaa** [comment]
You've already opened one, and been denied. Please don't repeatedly open tickets about the same thing after being denied.

**Comment by No-Yes1** [comment]
> A $40,000 base charger goes 180

Wrong. https://github.com/fkk-cz/noire_vehicles/blob/0bb565fcc0dd9c8b4a874c442e4a7c72febc98c1/DATA/2017charger/handling.meta#L19

Only goes 120mph. As stated above, issue was already made and denied.
