### ISSUE TITLE
Brabham bt62r 

### ISSUE THREAD

**Issue by Proudcat1** [fkk-cz/noire_vehicles#1186]
I was wondering if a couple aspects on the car could be changed such as the sound the car has a horrible GTA vanilla sounding audio file. maybe it could be replaced with the old mclaren audio file or something more sports car sounding. I’m not sure exactly what the top speed is outside of the test drive but inside the test drive it’s a little slow compared to the price and how the car actually preforms. I was also looking at the acceleration being really ass and it drags like a drag car taking it some time to start moving it’s one of my favorite cars irl and was saving to buy one and was wondering if some changes could be made before I bought it for the price of 735,000.

**Comment by TdotG** [comment]
Its a Ford V8 with ab 700 HP, 0-60 in 3 seconds give or take. Top speed is 190.

**Comment by Proudcat1** [comment]
Yea which in game 0-60 is like 10 secs for some reason it has a really bad drag. Top speed in game doesn’t compare to that from what I’ve tested could be wrong.

**Comment by Proudcat1** [comment]
And that sounds great I don’t need a car to push 260 I just want it to perform nice and actually like a super car more than a drag car. The audio file is my biggest concern as it sounds like a gta vanilla muscle car

**Comment by No-Yes1** [comment]
What sound in particular though?

**Comment by No-Yes1** [comment]
Fixed the handling/performance https://github.com/fkk-cz/noire_vehicles/commit/2fcdd8c65e18a77762c2f11e13a0afd232b8afb1. Waiting for further information on audio @Proudcat1

**Comment by Proudcat1** [comment]
I think I referenced it in the original post I was thinking maybe the maclaren p1 sound as idk it just sounds fitting for a high horse power sports car high pitched and loud

**Comment by No-Yes1** [comment]
Updated audio hash: https://github.com/fkk-cz/noire_vehicles/commit/1c53cee11bf7478c5dd9ae79ecf930f8d5b40f2f. Please wait for this to merge.
