### ISSUE TITLE
Enhance the 2019 ZR1 Corvette.

### ISSUE THREAD

**Issue by whitefeatherr** [fkk-cz/noire_vehicles#1187]
I don't know if it's a bug or not, but this is the third issue about the performance of the car, and it keeps disappearing. Is it going somewhere else? Removed?

Anyway to adjust the top speed?

**Comment by Scubaaaaa** [comment]
My guy, no matter how many times you make another issue it's still going to get denied.............

**Comment by No-Yes1** [comment]
https://github.com/fkk-cz/noire_vehicles/issues/1185 https://github.com/fkk-cz/noire_vehicles/issues/1181. The vehicle won't be nerfed. Stop making issues.

**Comment by TdotG** [comment]
He’s gotta be trolling at this point. I’d honestly nerf it at this point just to be funny Lmao..
