### ISSUE TITLE
Chevy Tahoe

### ISSUE THREAD

**Issue by CasperBoiRL** [fkk-cz/noire_vehicles#1188]
There’s a trailer hitch on there, but it doesn’t have the ability to pull a trailer.

**Comment by CasperBoiRL** [comment]
So, is it possible to add?

**Comment by No-Yes1** [comment]
Added in https://github.com/fkk-cz/noire_vehicles/commit/933ee53681217ff25cf0cb6e04edf931476892c2. Please wait for this to merge.

**Comment by CasperBoiRL** [comment]
just to be clear, i mean the non-supporter one.

**Comment by CasperBoiRL** [comment]
also, does this take place at server restart?

**Comment by No-Yes1** [comment]
i told you, you have to wait for it to merge. Could take a few days.

**Comment by CasperBoiRL** [comment]
i know, i just didn’t know what merge means

**Comment by CasperBoiRL** [comment]
it says new commit. does that mean added? because it doesnt work.

**Comment by No-Yes1** [comment]
Appears it doesn't want to tow. Even tried with pre-existing models (boattrailer) and it didn't connect. Nothing we can do.

**Comment by No-Yes1** [comment]
Reverted change: https://github.com/fkk-cz/noire_vehicles/commit/c0e7aaf416acfa4b73034c9ad60e35c7baa8fb0f

**Comment by CasperBoiRL** [comment]
i already bought the car bruh, can i get a full refund?

**Comment by No-Yes1** [comment]
We don't tend to issue full refunds for this issue. However, I am looking to buy a Tahoe. If you're in the city, make an assist within the next 10 minutes and i'll buy it full price.

**Comment by CasperBoiRL** [comment]
okay. will do rm
