### ISSUE TITLE
1990 Ferrari F40 Braking

### ISSUE THREAD

**Issue by mfried456** [fkk-cz/noire_vehicles#1189]
The braking on the 1990 Ferrari F40 was slightly tweaked but still results in the car spinning out. Any chance this can be tweaked a bit further? Thanks in advance

**Comment by No-Yes1** [comment]
Fixed in https://github.com/fkk-cz/noire_vehicles/commit/2f187583b2a3db17efe0b94bc057d7413caa7a4a. Please note that obviously it won't be "perfect" handling/braking due to the age of the vehicle. Please wait for this to merge.
