### ISSUE TITLE
Maserati Levante Novitek (again)

### ISSUE THREAD

**Issue by LactatingWalrus** [fkk-cz/noire_vehicles#119]
After the last change on this car, it flips very easily when going around corners at a normal speed. Not sure what changed to cause it but I can't even make it out of the city anymore because it flips on to it's roof most of the time.

**Comment by LactatingWalrus** [comment]
I should mention the handling that it previously had was perfect for that car. It was pretty stable.

**Comment by fkk-cz** [comment]
reverted back to old handling

https://github.com/fkk-cz/noire_vehicles/commit/be640ca1ed5bd8e6a8604b251ed11d39688e988b#diff-623d13b221c21d4726dfae0e0739dfa8a7b14d0edd718acff02cc382866e589c
