### ISSUE TITLE
2016 Porsche Carrera S 

### ISSUE THREAD

**Issue by Cpieper11** [fkk-cz/noire_vehicles#1191]
2016 Porsche Carrera S needs to be faster on top speed I believe 350k car and can't beat a 53k challenger on top speed although it's awd acceleration is great top speed terrible for a 350k car

**Comment by Freewillie321** [comment]
A guy posted something about a zr1 needing top seed adjustments since it can easily go 200mph. They turned it down and threatened to nerf it...

**Comment by No-Yes1** [comment]
Fixed in https://github.com/fkk-cz/noire_vehicles/commit/70a57363579a2d8a3769ebf2f6e778537ca3e51a, Please wait for this to merge
