### ISSUE TITLE
Tesla Roadster Top Speed

### ISSUE THREAD

**Issue by CasperBoiRL** [fkk-cz/noire_vehicles#1195]
I understand that the Roadster doing the realistic top speed of 250  is very unbalanced, but, I still think the top speed should be higher than 157. Im not asking for 250, Im asking for about 180-190, as the current top speed is very un-realistic.

**Comment by Proudcat1** [comment]
It already has the fastest acceleration why make it also one of the fastest cars especially for how low of a price it is

**Comment by CasperBoiRL** [comment]
Becaue as someone mentioned in the ticket about the ZR1, price doesnt determine how fast a car is. It is based of realism.

**Comment by Stagonium** [comment]
It is not based just off of the real life equivalent. The roadster is 200,000 in city, and the top speed matched with the acceleration that it has is at a balanced spot and will not be adjusted.

**Comment by CasperBoiRL** [comment]
I understand, but it is not balanced how it is. There are multiple cars around 75000 that have higher top speeds than 157. Its not balanced, and should be around 180.

**Comment by Stagonium** [comment]
I personally own the rimac, it is 2 million dollars. It goes 198 and IRL goes 258. for 200k the roadster is where it should be. It WILL NOT be adjusted.

**Comment by CasperBoiRL** [comment]
In the ZR1 ticket, the main point the admins had was that it is not the price that determines the speed, it is the real life car that  does. That does not mean that the Tesla should do the full 250, but it does mean it should do around 170, then it would be balanced

**Comment by okxeon** [comment]
The only way to balance it out then would be to nerf the acceleration of the roadster if a top speed like that was given. IRL that car might be well worth the money, but for that price in here and what you want done will ultimately just lead to people abusing it.

**Comment by noyeahsure** [comment]
I have the tesla roadster, and for the price it is. it is perfectly balanced compared to other cars.
the acceleration is one of, if not THE fastest of the cars in the city. and it handles well. the speed will not be buffed. as said before.
