### ISSUE TITLE
Maserati Levante Novitek

### ISSUE THREAD

**Issue by degzy1** [fkk-cz/noire_vehicles#120]
i  cant even make a turn in this car with out it flipping the way it handled be for hand was fine just needed an top speed an acceleration an braking tweak

**Comment by fkk-cz** [comment]
reverted back to old handling

https://github.com/fkk-cz/noire_vehicles/commit/be640ca1ed5bd8e6a8604b251ed11d39688e988b#diff-623d13b221c21d4726dfae0e0739dfa8a7b14d0edd718acff02cc382866e589c
