### ISSUE TITLE
 2012 lamborghini aventador j speedster top speed buff

### ISSUE THREAD

**Issue by EMN19** [fkk-cz/noire_vehicles#1200]
i think that for the 1M$ price that 210 is a bit low and that it should be in the 215-220 range. and since it does not have a roof maybe the speed can compensate for it.

**Comment by lemi97** [comment]
https://bit.ly/3yfmNxU

**Comment by TdotG** [comment]
I’m surprised this got buffed slightly. I was expecting a “this vehicle is good for the price and it will not be buffed”.

**Comment by noyeahsure** [comment]
did we just buff a car because it had no roof?? wouldnt that make it slower...

**Comment by TdotG** [comment]
I mean if it’s a convertible it should be slightly slower. But it’s a roadster

**Comment by No-Yes1** [comment]
> did we just buff a car because it had no roof?? wouldnt that make it slower...

lol

**Comment by No-Yes1** [comment]
Change Reverted. Vehicle won't be tweaked for the price/handling already.

**Comment by TdotG** [comment]
LMAO
