### ISSUE TITLE
Aston Martin Valkyrie

### ISSUE THREAD

**Issue by tythetanman** [fkk-cz/noire_vehicles#1204]
Looking to see what can be tweaked, because it is considerably slower than the Jesko. Out of city top speed is 250mph and it is priced at $3 million. 1 million more than the Jesko. 

Top speed is under 210

Turning needs tweaking as well.
Handling overall tweaks.

**Comment by tythetanman** [comment]
Braking is amazing how it is.

**Comment by Scubaaaaa** [comment]
Are you positive the car only goes 210? I've driven one plenty of times and it went much faster

**Comment by Scubaaaaa** [comment]
https://streamable.com/g3tvk0

The Valkryie does not need a speed buff at all. If anything the handling at high speeds needs to be buffed slightly.

**Comment by tythetanman** [comment]
I’ll take that. Did Just see the video. Have only had others try it too. Thx of handling can be buffed.

**Comment by No-Yes1** [comment]
Fixed in https://github.com/fkk-cz/noire_vehicles/commit/6c12932baf1ec51bf59c7ae51cb96fd3e9daed97. Please wait for this to merge live.
