### ISSUE TITLE
(Posting here for American Vampire) Please FIX the - 2013 Ford Mustang Shelby GT500 ( NEED FOR SPEED )

### ISSUE THREAD

**Issue by tythetanman** [fkk-cz/noire_vehicles#1205]
Just posting in the right place for American vampire
![EBC8B06B-46EA-451B-8EBE-7A872FF8A23C](https://user-images.githubusercontent.com/94341559/177469726-53e12228-c1de-484d-95ef-da451769aec4.jpeg)

-AmericanVampire

Ok so if you are unaware this mustang was the vehicle in the movie "Need for Speed" This is an exact clone of the vehicle well.... everything except it's entire reason for being in the movie - (it's SPEED) This mustang is a 900hp mustang that goes 239 MPH - Sadly in the city this 900hp muscle car does barely 130 MPH 👎 what gives? Can we please at least push this vehicle up to 201mph just to say it goes over 200mph. It's very disappointing to buy this and it go slower than the majority of cars out on the street and its a Shelby GT500 at that, they are 160's and up but this is a 900HP Shelby GT500 vehicle so PLEASE, lets give something back to ford. the non-900HP standard 5.0 in the city does better than this which anyone who knows anything knows this is not accurate.

**Comment by No-Yes1** [comment]
For the price of the vehicle, the handling/performance is fine and will not be tweaked
