### ISSUE TITLE
Ferrari Enzo

### ISSUE THREAD

**Issue by Mynameisnotlenny** [fkk-cz/noire_vehicles#1206]
Wanted to see if this vehicle could be tweaked. Car in real life is known for its braking power so wanted to see if braking could be tweaked slightly. Car also tops out around 160-170 this car in real life hits around 218-220 MPH so wanted to see if top speed could be risen slightly. The car also has no upgrades besides turbos which from what I believe is a model issue so if any tweaks were to be made that would also have to be taken into account. The handling may need to be buffed slightly but not much.  Not sure if any other tweaks need to be made feel free to add on if you believe anything else needs to be changed or not touched at all.

**Comment by Mynameisnotlenny** [comment]
Looks like the turbo upgrade doesn’t save either actually

**Comment by No-Yes1** [comment]
Won't be fixed the handling as it's fine for the price. Fixed the no upgrades which will obvs make the vehicle somewhat faster. Fixed in https://github.com/fkk-cz/noire_vehicles/commit/3adfd3b3638b604102593f75f623cab789ac02f9. Please wait for this to merge live.
