### ISSUE TITLE
2020 Mercedes-Benz AMG GT Black armour buff

### ISSUE THREAD

**Issue by Senni4** [fkk-cz/noire_vehicles#1209]
The armour on the 2020 Mercedes-Benz AMG GT Black is weak, earlier today I got rammed while being chased and the car immediately started smoking after a little bump from the back, I was wondering if you could buff the armour to make the vehicle stronger, as of right now it’s very weak.

**Comment by No-Yes1** [comment]
Fixed in https://github.com/fkk-cz/noire_vehicles/commit/332cb500cdfbfe02bcd0888dab96e9bebdc8f32c. Please wait for this to merge live.
