### ISSUE TITLE
BRZ and BMW M4 Widebody 

### ISSUE THREAD

**Issue by Retr0Flux** [fkk-cz/noire_vehicles#121]
Add more power to brz to make it able to speed up faster.
For the bmw m4 widebody increase it so 4 people can get in it and increase speed and acceleration since IRL it's way better.

**Comment by ZacLuxton** [comment]
> Add more power to brz to make it able to speed up faster.

Done https://github.com/fkk-cz/noire_vehicles/commit/3416b2718881681935c448be1ab550c0ea98f954

> or the bmw m4 widebody increase it so 4 people can get in it

Its a 2 door car, it'll just tp you inside the car without any animation, so we wont be doing that

**Comment by ZacLuxton** [comment]
BRZ is fixed

**Comment by ZacLuxton** [comment]
merging BMW with #437
