### ISSUE TITLE
2012 suporter lamborghini aventador lp700-4 top speed buff

### ISSUE THREAD

**Issue by EMN19** [fkk-cz/noire_vehicles#1210]
the current top speed is 190 which for a 1,25m dollar car is pretty bad. I think that the 220 ish range would fit the price much better. And the acceleration is just a bit weak for the price

**Comment by KyleScot** [comment]
I also bought this vehicle prior to me getting my Aventador S. After driving the Aventador LP with upgrades, the car would not pass 200mph, it would sit anywhere between 186-190mph. I understand that price point does not always have to determine the Top Speed of a vehicle in the city, but I feel that the Top Speed of the Aventador LP, in my opinion would be reasonable within the 215mph range. My Porsche GT3RS which is just under $400k at PDM, has a Top Speed of 190mph in the city. When we take into consideration that the Lambo is $1.25m, it would be reasonable to say that it should definitely have a buff that increases its Top Speed to be 200+mph.

**Comment by No-Yes1** [comment]
Fixed in https://github.com/fkk-cz/noire_vehicles/commit/ff830c2e32b13af537d35fb6acff8b72cd1c283c. Please wait for this to merge live.

**Comment by EMN19** [comment]
> Fixed in [ff830c2](https://github.com/fkk-cz/noire_vehicles/commit/ff830c2e32b13af537d35fb6acff8b72cd1c283c). Please wait for this to merge live.

i waited for the merge just to find it only doing 195 as i said for 125 mil i think that if it isnt atleast 215 or above its just not fair

**Comment by No-Yes1** [comment]
It's not going 215mph or whatever your proposed. People will just start buying it to abuse. Happened way too often. Car buffed to 200mph. With the handling/acceleration/traction even at top speeds the car is just fine and will not be tweaked further. https://github.com/fkk-cz/noire_vehicles/commit/f6fae07ac336320f1f2aa6b5e9a82c0435f13fb1. Please wait for this to merge live.

**Comment by No-Yes1** [comment]
are you really saying that 200+ is _not fast_

**Comment by No-Yes1** [comment]
I already said the vehicle will go 200mph give or take. That's final.
