### ISSUE TITLE
Lamborghini SC18 last gear

### ISSUE THREAD

**Issue by CasperBoiRL** [fkk-cz/noire_vehicles#1214]
It does good, but when it switches into last gear, it has pretty much no difference compared to the previous gear. All i’m asking is for the last gear to be lengthen a bit

**Comment by okxeon** [comment]
Improved the top end slightly here https://github.com/fkk-cz/noire_vehicles/commit/c2a60fbf69480b5ed913d419377bd5e0dbf2a47e. Will now average 190 - 195.
