### ISSUE TITLE
2019 porsche gt2 rs buff acceleration and top speed. 

### ISSUE THREAD

**Issue by Cruzamp** [fkk-cz/noire_vehicles#1217]
this car is faster than the gt3 rs in all ways irl it has more horse power than the gt3.  here are the specs and the top speed of the gt2 rs its is 211 it barely hits 185 and the get up/ acceleration should be better than the gt3 rs  it has more torque but its not.  

 ![Screenshot 2022-07-07 202305](https://user-images.githubusercontent.com/95521024/177905028-74d74546-329f-4174-bc82-51ac279f8bef.png)
  here are the specs for the gt3 rs the specs in game are perfect to the ones irl. 

![Screenshot 2022-07-07 202327](https://user-images.githubusercontent.com/95521024/177905224-dded66d0-1fbd-452a-b98e-eae5ae790e9e.png)

**Comment by Cruzamp** [comment]
here is the top speed for the gt2 rs if ya need that because it said the gt3 goes 193 top speed. 

![Screenshot 2022-07-07 202223](https://user-images.githubusercontent.com/95521024/177905511-50e24ba5-f054-4551-be2c-17db1be08ef0.png)

**Comment by Scubaaaaa** [comment]
Slightly improved the average speed of the vehicle
https://github.com/fkk-cz/noire_vehicles/commit/7e5c5a986044435217dc76f7aacf38ba6ef9d86c
