### ISSUE TITLE
2015 Subaru WRX STI

### ISSUE THREAD

**Issue by Ell34** [fkk-cz/noire_vehicles#1218]
The handling on this car was tweaked about a month ago, few days after it was added. However, the handling on it is still a boaty feel. It would be nice to see it get tightened a bit. Everything else about the car is fine.

**Comment by okxeon** [comment]
This should make it drive a bit smoother without as much of the boat feel to it. https://github.com/fkk-cz/noire_vehicles/commit/4f90696d69a7bac23882036234d8cd2081f7e3ef
