### ISSUE TITLE
CamaroZ28 missing vehicles.meta file

### ISSUE THREAD

**Issue by DankGrandma** [fkk-cz/noire_vehicles#122]
i was looking to see if this was in game but i dont see it

**Comment by ImDead48** [comment]
The reasoning it's in the files but not in game is because it's a 1:1

**Comment by fkk-cz** [comment]
> 
> 
> i was looking to see if this was in game but i dont see it

https://github.com/fkk-cz/noire_vehicles/blob/6df7812acf5a3920a2eb2475df7bc11a5d59b007/DATA/streetz28/vehicles.meta
