### ISSUE TITLE
Agera RS

### ISSUE THREAD

**Issue by CasperBoiRL** [fkk-cz/noire_vehicles#1221]
The Agera RS is RWD, but in the game it is AWD

**Comment by CasperBoiRL** [comment]
If the grip could also be adjusted too, it would be great. It corners a bit bulky, and will need more grip added to compensate for losing the 2 front tires putting power down

**Comment by okxeon** [comment]
Changed to fully RWD here https://github.com/fkk-cz/noire_vehicles/commit/c7160450804a7c4bbbb80e87f4087bc13e449c2e. Not sure how much of a noticeable difference this will make but here you go. Also the grip seems fine for the 500k price tag of the car.

**Comment by CasperBoiRL** [comment]
It says commutes, but it def still spins all 4s on launch

**Comment by okxeon** [comment]
It's not yet been merged. Wait for that to happen and the update will take effect.
