### ISSUE TITLE
2020 Rolls Royce Cullinan + Black Badge

### ISSUE THREAD

**Issue by Ell34** [fkk-cz/noire_vehicles#1223]
Both models in the city are FWD and spin out like a mf, but in the big city are AWD. If this could be changed that'd be great :)

**Comment by No-Yes1** [comment]
Fixed in https://github.com/fkk-cz/noire_vehicles/commit/90333c476e25522e9128f7ce09f05730659e8ef9. Not sure why this is was left for so long so thanks for bringing it up. Please wait for this to merge live.
