### ISSUE TITLE
Yamaha MT10 2016

### ISSUE THREAD

**Issue by Baker187** [fkk-cz/noire_vehicles#1224]
The Yamaha MT10 2016 is the competition to the KTM 1290 SD Big city and needs a buff to match. currently it will only do like 105

**Comment by okxeon** [comment]
Created a new handling file here https://github.com/fkk-cz/noire_vehicles/commit/98e0bd17551e87c5a2f84cc0983890124f2d38f5 so it would not use the default vanilla BATI one. This handling is almost identical to the KTM super duke. Bike will now do 160 opposed to the default 105 before.
