### ISSUE TITLE
Dodge Ram 2019

### ISSUE THREAD

**Issue by CasperBoiRL** [fkk-cz/noire_vehicles#1227]
Can i get the sound from the challenger RT put in this truck? Same engine.

**Comment by okxeon** [comment]
Is this the truck with the spinner rims that are massive and looks 'interesting' to put it nicely?

**Comment by CasperBoiRL** [comment]
Nah, it’s the jacked up off road one with the spare tire in the back

**Comment by CasperBoiRL** [comment]
It’s like 31k in PDM

**Comment by No-Yes1** [comment]
Fixed in https://github.com/fkk-cz/noire_vehicles/commit/b3cf4336af6c63be07ae2a81c353623f4fae0fcd. Please wait for this to merge live.
