### ISSUE TITLE
22' bmw m5 comp enhancement?

### ISSUE THREAD

**Issue by limpic** [fkk-cz/noire_vehicles#1232]
curently the 22' m5 comp does like 155 MAX for 175k while cars like the trackhawk does like 160 for 85k. so a better top speed would put it in the right price to speed ratio

**Comment by Scubaaaaa** [comment]
People were using the 2022 M5 as a meta for getaways, which is why the vehicle got nerfed and won't be re-buffed. Can blame other people for not wanting to RP and just have an end goal to get away as fast and unrealistic as possible.
