### ISSUE TITLE
2019 Mclaren 600LT

### ISSUE THREAD

**Issue by BaelyTV** [fkk-cz/noire_vehicles#1233]
Per Scubas request

This car has significantly less top speed and way too tight angle on the front making the handling way worse than the cheaper mclaren the 2020 GT

Could we possibly get the dirt mapping adjusted as well, gets dirty very fast.

ScubaK

**Comment by okxeon** [comment]
How much is the car?

**Comment by BaelyTV** [comment]
250-270k scuba already looked into it just asked me to make a git so it doesnt look like hes just randomly buffing

**Comment by Scubaaaaa** [comment]
I upped the top speed a bit, handling seemed fine for price.
https://github.com/fkk-cz/noire_vehicles/pull/1219/commits/3aa59090286772fca009f7858896a238a1b2853d
