### ISSUE TITLE
Brabham bt62

### ISSUE THREAD

**Issue by Proudcat1** [fkk-cz/noire_vehicles#1234]
Made an original post about this the handling was buffed so was the top speed to around 180 which I'm fine with. Was wondering if anything can be touched with the acceleration as it is dogshit and either A spins out completely or takes 5 seconds to even get the thing to move.

**Comment by okxeon** [comment]
Gave the car some power to the front wheels to prevent them from spinning for like 5 seconds before actually going. This significantly improved the launch where the car no longer feels sluggish. In addition improved the top end to 190+ as its 735k and that feels more appropriate. Slightly improved the handling as well to grip the road better at higher speeds. Changes can be found here: https://github.com/fkk-cz/noire_vehicles/commit/53f4c37f266ccb5c4bb77234971e06c16474ece8
