### ISSUE TITLE
2019 ZR1 Gearing update and comsetic issue. (I added data values)

### ISSUE THREAD

**Issue by dukerzzz** [fkk-cz/noire_vehicles#1236]
I know you guys are annoyed with that one guy posting the TOP SPEED three times, but this post is more factual and has more details.

**Performance/handling.meta:**
0-60 is 2.9 - 3.0 seconds. The car shouldn't be burning out like it is now. It should just go and not lose its rear end every time.
fLowSpeedTractionLossMult value="1.200000". If we change it to .6-.8 that would be closer to ideal for the car. If you watch this video the car doesn't burn out at all. It just goes. (Go to the 0:35 second mark to see the take-off):
https://www.motor1.com/news/438806/corvette-zr-1-top-speed-run-jbpg/

Also I noticed this: InitialDriveGears value="6". The car has 7 gears total if it's a manual. Looking at the interior the car is a manual,(stickshift and 3 pedals), so there is 7 gears total, but the file says 6. This means that the top speed would need to be adjusted to 180 at a minimum. I know the top speed thing is annoying you guys, but the gearing is wrong. If you check this article out it states that it is in fact a 7-speed manual transmission: https://media.gm.com/media/us/en/chevrolet/vehicles/corvettezr1/2019.tab1.html

So doing the math with the fInitialDriveMaxFlatVel value="205.000000". 205 x .82 (.82 to get the MPH) is 168.1mph. The only time I reached that was going into the city.  If we change the valve to 220-225 instead of 205, that would be ideal for this car since there are 7 gears. That would put the car around 180-184mph in the game.

**Cosmetics:**
One thing with the car is the spoiler on the back falling off after tiny little hits. I know it's a tedious thing and I don't know if you guys can do anything about it, but if I hit even the slightest thing with the rear of the car going even 5mph, the spoiler falls off. I can repair the car and it comes back. It's just a little thing that I noticed. It's no biggie if it's going to be a hassle to fix. Just wanted to bring it up.

Handling is great, braking is great, the style is amazing and the sound is amazing. Overall great car, just needs some final adjustments to make it fully true. 

I got these values from the 2019zr1_data. I notice there was another corvettezr1_data, but the MaxFlatVel was 220 and there were a lot more vehicle body mods to that file too. the 2019 ZR1 has no modifiable body. Other than wheels.
Link to the files that I got the data from: https://github.com/fkk-cz/noire_vehicles/tree/master/DATA/2019zr1_data

Thank you for reading this! Hopefully, a couple of changes will happen!

**Comment by okxeon** [comment]
How much is the car in game?

**Comment by dukerzzz** [comment]
$180,000

**Comment by okxeon** [comment]
Tweaked a bit here: https://github.com/fkk-cz/noire_vehicles/commit/eb9951733c527eaef41567b6f93fed3f1b0271c5. Car will now hit 175-180 & also improved the launch so the tires don't spin as much. For a 180k price tag this is probably the best it should do. Wait for the changes to merge for it to take effect.

**Comment by okxeon** [comment]
Was not aware this car was not really supposed to get any speed improvements. I'll lower the top speed but the launch can prob stay the same.

**Comment by TdotG** [comment]
So close, but yet so far LMFAO

**Comment by dukerzzz** [comment]
> Was not aware this car was not really supposed to get any speed improvements. I'll lower the top speed but the launch can prob stay the same. 

Aw man! I was close to getting it changed. Is it the price? Like why couldn't it be 175-180? :)
