### ISSUE TITLE
Mercedes Benz-AMG One Model Change / Values upgrades

### ISSUE THREAD

**Issue by Chunky30** [fkk-cz/noire_vehicles#1238]
The Mercedes Benz-AMG One is a car that despite its model, to put it in lgith words looks like its made out of Play-Doh and has some issues with it for being a 2.7m Car. Found this good and FiveM ready model that exceeds the allowed/suggested polly count of i believe between 200-250k?. Due to its exclusivity and it being a 2.7m Car i was wondering if the model could be change to the one suggested below which exceeds said boundaries. Also the car is based of F1 technology and i was wondering if its traction/top speed-acceleration could be slightly tweak, not to the point its the most OP car in the city. 

https://forum.cfx.re/t/mercedes-amg-one/4834849

If not I understand why and would be happy to work allong the team responsable for this kind of stuff to find a model within the boudaries for this car that has so much pottential :)

**Comment by No-Yes1** [comment]
Polygons: 374.524

Vehicle need to be <200K polygon's.

As for the handling, i'll take a look later.

**Comment by No-Yes1** [comment]
https://streamable.com/09xquo - handling is already too OP. Can't hit corners like it's a piece of cake at 200mph. Accel/Top Speed/Traction is fine. The clip attached is the vehicle stock.

**Comment by No-Yes1** [comment]
As for the model, make a request vehicle ticket as they are now open.
