### ISSUE TITLE
BMW M8 

### ISSUE THREAD

**Issue by SAMOXID** [fkk-cz/noire_vehicles#124]
The M8 feels to slow, mostly at the beginning. The car costs 198,000 and is extremely hard to get it going fast. It struggles to reach 150 and when it does, it takes ages to get there. I’d appreciate an acceleration buff and up the speed a little. 

Thanks for reading and hope you can help

**Comment by Ahy-jason-todd** [comment]
buff the supporter one too while your at it when you changed the supporter one it turns out u nerfed the top speed of it
