### ISSUE TITLE
Dingy 4s only seats two

### ISSUE THREAD

**Issue by teresgrunt4555** [fkk-cz/noire_vehicles#1243]
Is there any way to get the dingy 4s to be 4 seater. It’s cost more than the two seater and would really like to be able to use all the seats for the price upgrade. I looked to see if this was an issue before and it looks like it was brought up in march and still doesn’t work

**Comment by No-Yes1** [comment]
Refer to previous issue: https://github.com/fkk-cz/noire_vehicles/issues/918
