### ISSUE TITLE
Jeep Trailcat sound and buff

### ISSUE THREAD

**Issue by CasperBoiRL** [fkk-cz/noire_vehicles#1246]
First off, can we get the sound from the hellcats and trackhawks into this car? Its the same engine, and there's really no reason not to. Second, can it get a little bit of a buff? Obviously, its not gonna be as fast as a hellcat with all the massive tires and stuff, but it still needs to be faster than it is.

**Comment by No-Yes1** [comment]
For the price of the vehicle (74K) the handling will not be tweaked. Tweaked the audio hash: https://github.com/fkk-cz/noire_vehicles/commit/2b1935333db54bd99585320b920aa17315ab1174. Please wait for this to merge live.
