### ISSUE TITLE
falling off of the Honda xr250 even from like 3 feet jumps

### ISSUE THREAD

**Issue by tantatertot** [fkk-cz/noire_vehicles#1250]
I recently got the Honda xr250 and went to the dirt bike track near sandy shores and found that I cant even make most of the jumps there without falling off and losing a ton of my health I think it would be nice if you were able to take some larger jumps without bailing on the bike to create a more fun experience. I believe it is like this with all other bikes as well.

**Comment by okxeon** [comment]
Can you provide a video of this?

**Comment by CasperBoiRL** [comment]
https://medal.tv/games/gta-v/clips/sGHp28C4Ppy-C

**Comment by CasperBoiRL** [comment]
if the four wheeler “fall off” physics from the banshee would be added, it would be amazing, and so much more realistic

**Comment by tantatertot** [comment]
fax

**Comment by tantatertot** [comment]
Its actually horrible you fall of from a 2 feet jump an then it takes away 75% of your health from one fall its horrible

**Comment by fkk-cz** [comment]
This isn't a vehicle-specific issue, rather, is caused by a client script that knocks a ped off a bike under certain deceleration conditions. I'll probably adjust it so the tires get blown out instead.

**Comment by CasperBoiRL** [comment]
what? can you just make it where it doesn't do anything until its a certain height where its realistic to fall off?
