### ISSUE TITLE
Koenigsegg Gemera

### ISSUE THREAD

**Issue by Stagonium** [fkk-cz/noire_vehicles#1254]
I feel like at the 500k price point as a supercar, the vehicle is a bit lackluster as far as handling, braking and acceleration are concerned. I think the acceleration should be slightly buffed further than it was in [this tweak](https://github.com/fkk-cz/noire_vehicles/commit/776c6e93dfde3c9a490f8e1650dabb86d2135381). And the braking and overall handling just needs to be tightened a little more to really feel like its in that Supercar class of vehicle.

**Comment by tantatertot** [comment]
fax

**Comment by No-Yes1** [comment]
Fixed in https://github.com/fkk-cz/noire_vehicles/commit/f78f69750bab09fa90467411a49222d910df724b. Please wait for this to merge live _(It also might have something to do with the fact it's AWD, so if this doesn't work then i'll test it elsewhere)_
