### ISSUE TITLE
Lamborghini Sesto Elemento

### ISSUE THREAD

**Issue by BubbaDaniels** [fkk-cz/noire_vehicles#1258]
The Lamborghini Sesto Elemento is a 450k hypercar that struggled to get too 145mph on the test track idk but to me personally I feel like if your gonna charge 450k for a car it should go at least 175mph

**Comment by okxeon** [comment]
Test track and on the street will have two very different outcomes. It can be looked at but just know that it might not be as shit as you are implying.

**Comment by PsychoticCore** [comment]
> Test track and on the street will have two very different outcomes. It can be looked at but just know that it might not be as shit as you are implying.

Bumps on the road make cars so much quicker ong
