### ISSUE TITLE
Mercedes AMG GTS 

### ISSUE THREAD

**Issue by CBENNETT32** [fkk-cz/noire_vehicles#126]
The Mercedes amg gts and feels slow at the start and doesnt go much faster than the Mercedes cls 53 any chance we can get a little more torque and top speed please

**Comment by fkk-cz** [comment]
https://github.com/fkk-cz/noire_vehicles/commit/6df7812acf5a3920a2eb2475df7bc11a5d59b007#diff-2a5d3d9e81fd3daaec5d97fe074bcf6bec76a06abe27247bff22a8a33e76ef1b
