### ISSUE TITLE
Mercedes AMG GT Black edition

### ISSUE THREAD

**Issue by FertileSphere** [fkk-cz/noire_vehicles#1260]
Considering the type/brand of car, very lackluster in the way of spirited driving. I can barely outdrive a fully loaded sedan. Wouldnt mind it being looked as far as traction goes as its technically a street legal track car. not wanting any speed drag changes as its in a good space in those areas IMO.

**Comment by No-Yes1** [comment]
Fixed Traction issue: https://github.com/fkk-cz/noire_vehicles/commit/01ce2c2e2ead4c5949c5ffbb13b6f8127b7546e6. Please wait for this to merge live.
