### ISSUE TITLE
2019 Mclaren Senna Armor issue

### ISSUE THREAD

**Issue by hadizoerr** [fkk-cz/noire_vehicles#1261]
Once you set armor 3 on the 2019 Mclaren Senna you cant revert it which makes it slower (it deducts your money when u try to get rid of it but no change happens)

I also think it should get a slight speed bump aswell, up to 210 perhaps?

**Comment by hadizoerr** [comment]
everyone says armor slows it down, and the car goes 198-200 mph, if its being realistic the senna goes 208 top speed

**Comment by hadizoerr** [comment]
car cost 715,000$

**Comment by CasperBoiRL** [comment]
i’ve never heard anyone say armor slows it down. the car is also in the millions irl

**Comment by hadizoerr** [comment]
are you sure? doesnt armor add weight? i know weight differentiates with motorcycles, isnt it the same with car?

**Comment by CasperBoiRL** [comment]
if you buy an actual “armored” car from gtav, then it is slower than the normal one, but adding armor at ls customs does nothing

**Comment by okxeon** [comment]
If the car currently goes slightly under 200 mph its close enough to the top speed. Does not need an 8-10 mph buff.
