### ISSUE TITLE
Mercedes Benz 600sel customization bugged 

### ISSUE THREAD

**Issue by WyattRamsey33** [fkk-cz/noire_vehicles#1263]
Not sure what went wrong but while customizing my car all my textures broke and the car was half invisible and eventually fell through the ground.

https://medal.tv/games/gta-v/clips/taHyc5xBwItDc/d1337WljzK4Z?invite=cr-MSxlbE0sNzEwMTg0MDMs

**Comment by okxeon** [comment]
Yea this is very broken and will probably have to get removed / replaced.

**Comment by WyattRamsey33** [comment]
https://medal.tv/games/gta-v/clips/taHyc5xBwItDc/d1337EyH2dKT?invite=cr-MSxVSE0sNzEwMTg0MDMs

**Comment by WyattRamsey33** [comment]
https://medal.tv/games/gta-v/clips/taHyc5xBwItDc/d1337EyH2dKT?invite=cr-MSxVSE0sNzEwMTg0MDMs
ill try the clip one more time

**Comment by fkk-cz** [comment]
Recall has been issued.
