### ISSUE TITLE
Small Trailer Turning Radius.

### ISSUE THREAD

**Issue by jayruss62** [fkk-cz/noire_vehicles#1265]
When using the small bumper pull trailer you can barley turn a corner. Could we possibly see a fix to this?

**Comment by No-Yes1** [comment]
Is this for certain vehicles/all vehicles?

**Comment by jayruss62** [comment]
All vehicles

**Comment by No-Yes1** [comment]
Just tested this with multiple vehicles and it's working fine/no issues.

**Comment by jayruss62** [comment]
The past 3 trucks I’ve had don’t turn worth a shit with the small trailer they do when moving but at slow speeds and tight corners they hardly turn I can submit a clip
