### ISSUE TITLE
2010 Ram Flatbed price reduction

### ISSUE THREAD

**Issue by CasperBoiRL** [fkk-cz/noire_vehicles#1267]
I really love this truck because it’s different, but the price is outrageous. Could we please be able to lower it to like 30k, since it’s a work truck anyway?

**Comment by jayruss62** [comment]
I agree this truck is very over priced

**Comment by No-Yes1** [comment]
Prices can not be tweaked once in place as players already own the vehicle and if they wish to sell the vehicle,  they receive the % of how much the vehicle is in PDM, and not how much they brought the vehicle for.

**Comment by CasperBoiRL** [comment]
Well then can you recall it and change the price?

**Comment by tantatertot** [comment]
fax
