### ISSUE TITLE
Tesla Roadster Nerf

### ISSUE THREAD

**Issue by noyeahsure** [fkk-cz/noire_vehicles#1268]
I'm not sure why this was nerfed. acceleration as well, which a main point of teslas is fast acceleration, i felt like the car was perfectly fine beforehand, esp with the armor being kind of eh on it

**Comment by D4LPebble** [comment]
i agree, the nerf on the roadster is insanely unneeded, its crazy light, so if you hit a sidewalk itll start flipping or any bump really. the armor is insanely weak, one of the worst armor'd cars in the city. the only thing that WAS good about the car was its acceleration. real roadsters hit 0-60 in 1.1 seconds of course this is "track speeds" professionally. however it takes well over that to get to 60 and i dont even want to talk about the difference to even get to 160 now. the acceleration tweak ruins the glass cannon car, PLEASE revert it

**Comment by AngelMff** [comment]
Agreed the roadster was only good for acceleration. armor was way too weak one light pole at a good fast speed and your done for or one shot to the back of the tire and the car was dead the car takes a good driver especially when in cop chases with it it’s not a easy car to drive when it comes to that at high speeds especially with the speed only topping out at 157

**Comment by Rakeem21** [comment]
very very unnecessary nerf. if anything you should maybe nerf the top speed to 155 or something but the acceleration was perfectly needed. the car handles not that well and it breaks by anything touching it. if there is a single bump in the road you can go flying and then wreck the car just like that. it really needs the acceleration back.

**Comment by No-Yes1** [comment]
Buffed acceleration and nerfed top speed to 155: https://github.com/fkk-cz/noire_vehicles/commit/313cdca9a962cdbf4091c6cd82d30912c520ab2e. Please wait for this to merge live.

**Comment by jamesclark19** [comment]
the launch needs to go back to normal the models is faster at launch your paying $200000 for it just for it to be that slow and a really slow launch now wtf. plz put in back to normal no need.

**Comment by somedudenamedrush** [comment]
sir when the update gets pushed it will be reverted just wait a little

**Comment by No-Yes1** [comment]
Can you not see simple responses: > Please wait for this to merge live. _sigh_
