### ISSUE TITLE
2009 zr1 corvette 

### ISSUE THREAD

**Issue by NoSmoke96** [fkk-cz/noire_vehicles#127]
Hi was looking to see if I could get a top speed & exhaust sound buff/tweak for the 2009 zr1 corvette especially for a $105k price range. The top speed atm is around 155mph which is quite slow for a zr1 I was gonna see if it was possible to get it up to like the 175-180mph range or just a tad quicker as well as a deeper exhaust tone or Growl for a more realistic feel.

**Comment by fkk-cz** [comment]
155mph for a 105k car is balanced
