### ISSUE TITLE
My Vehicle is wanted by the police for no reason

### ISSUE THREAD

**Issue by tantatertot** [fkk-cz/noire_vehicles#1271]
Why is it that when I drive past a cop to fast and they don't care to stop me my vehicle is wanted by the police and not able to be put into a garage? I was driving fast in my car and a cop pulled out of the SAHP station and turned on his lights and continued to drive pass me towards the city since, I'm assuming, he got a call, yet my car is still wanted by the police and I'm prevented from putting it in a garage even though the cop was not even trying to pull me over. Is there any way we can fix this?

**Comment by Mynameisnotlenny** [comment]
You were clocked on the vehicles radar and it automatically flagged your plate for speeding.

**Comment by No-Yes1** [comment]
This is for vehicle specific issues. Wait the timer out.
