### ISSUE TITLE
gcart requires exemption from gas

### ISSUE THREAD

**Issue by WyattRamsey33** [fkk-cz/noire_vehicles#1272]
New golf cart has 8 seats but only has 2 working seats. Is this able to be fixed?

https://medal.tv/games/gta-v/clips/tARgm8g_UeNly/d1337zIaoPDx?invite=cr-MSxlWXUsNzEwMTg0MDMs

**Comment by No-Yes1** [comment]
It's a layout fix. However, R* doesn't have any 8 seater layouts (apart from the limo), however the layout seats are very much different and will probably cause game crashes. I'll take a look at this and see if it can have 4 seats at least.

**Comment by WyattRamsey33** [comment]
Also its electric but takes gas

**Comment by No-Yes1** [comment]
I've attempted to fix the layout - however sadly none work as it either crashes my game or still only does 2 seats.

**Comment by No-Yes1** [comment]
> Also its electric but takes gas

@fkk-cz - can you exempt this for taking gas.

**Comment by Competent1** [comment]
Thank you for submitting this issue. Good news, the issue here has been resolved! Enjoy the vehicle!
