### ISSUE TITLE
Aventador S Handling

### ISSUE THREAD

**Issue by TdotG** [fkk-cz/noire_vehicles#1274]
I dont know if the handling update has went live yet but, the car sometimes feels like a drift car. It loses traction alot more than it has before.

**Comment by TheBottomFragger** [comment]
> I dont know if the handling update has went live yet but, the car sometimes feels like a drift car. It loses traction alot more than it has before.

I have the same issue, haven’t been in the city much, but I flew in yesterday and used the car, and it just didn’t feel the same

**Comment by TdotG** [comment]
> > I dont know if the handling update has went live yet but, the car sometimes feels like a drift car. It loses traction alot more than it has before.
> 
> I have the same issue, haven’t been in the city much, but I flew in yesterday and used the car, and it just didn’t feel the same

Ok good I thought I was trippin.

**Comment by CasperBoiRL** [comment]
yeah i havce the aventador j, and its rwd now... not awd

**Comment by TdotG** [comment]
Yea the Aventadors are AWD not RWD. It almost feels like a Italian hellcat at times.

**Comment by CasperBoiRL** [comment]
it used to be awd, something changed

**Comment by TdotG** [comment]
From what I know. I requested the Aventador S handling to be adjusted so it feels less like a boat. Not sure why the J Speedster is messed up too.

**Comment by CasperBoiRL** [comment]
well idk why the aventador j was changed, but it needs to be reverted, nobody requested anythign

**Comment by No-Yes1** [comment]
aventador j has the same handling id as the avantador s, that's why they were both changed.

**Comment by CasperBoiRL** [comment]
well can the change on the J be reverted? It was unneeded, and nobody asked for it. can you not just copy the unchanged handling file and copy it to make the aventador j has its own handiling file, so it doesn’t get changed.

**Comment by No-Yes1** [comment]
Well can you please hang fire whilst i take a look further

**Comment by No-Yes1** [comment]
Fixed in https://github.com/fkk-cz/noire_vehicles/commit/706199f84e82290feedf6fc36817349bd3ecbefc. Please wait for this to merge live.
