### ISSUE TITLE
GT2RS sound addon

### ISSUE THREAD

**Issue by CasperBoiRL** [fkk-cz/noire_vehicles#1279]
I've recentley seen a Mercedes SLR new custom sound get added, so i wanted to ask for this for the 2019 GT2RS. I went looking for a good engine sound already in the game, but there are no Porsche with engine sounds. https://www.gta5-mods.com/vehicles/porsche-911-gt3-rs-engine-sound-oiv-add-on-fivem

**Comment by TdotG** [comment]
I tried adding this exact sound in previously, unfortunately I don’t think they’re allowing/adding anymore new sounds due to the size of the files.

**Comment by CasperBoiRL** [comment]
see https://github.com/fkk-cz/noire_vehicles/commit/904ab0fd0c05f81365079e9a0ababc7e79ae3f75 they added a sound there, surely they can add this

**Comment by TdotG** [comment]
That sound is already been there. It’s the black series sound file. It was also the same one for the E63 AMG, before it got reverted to the default sound due to people crashing out of the server.

**Comment by CasperBoiRL** [comment]
ohhh i see now. well maybe theyll make this one exception, due to there being no sounds in any of the porsches.

**Comment by CasperBoiRL** [comment]
and its not a big file, only 8mb

**Comment by TdotG** [comment]
Ya that would be nice, it’s very on par with the IRL flat six.

**Comment by Cruzamp** [comment]
There is a sound for the gt3 rs it's a custom sound it sounds like a flat 6 na and when you put the turbo on it it sound incredibly. The Mercedes is a v8 bi turbo I don't think they sound similar at all.  It's a F6 vs a V8 it's missing 2 cylinders.

**Comment by CasperBoiRL** [comment]
well duh

**Comment by No-Yes1** [comment]
Updated audio hash for ``mercedesm155`` -- https://github.com/fkk-cz/noire_vehicles/commit/8a0b0ccf330c6dbb48828d56f6130770a41c9362. Please wait for this to merge live.

**Comment by CasperBoiRL** [comment]
No no, this is not what i wanted, i wanted the custom sound in the link i sent

**Comment by CasperBoiRL** [comment]
It’s a very small file

**Comment by No-Yes1** [comment]
We're not adding anymore custom sounds.

**Comment by No-Yes1** [comment]
What you want and get is 2 different things.
