### ISSUE TITLE
Audi r8 Buff

### ISSUE THREAD

**Issue by Ahy-jason-todd** [fkk-cz/noire_vehicles#128]
Since the car cant upgrade its super fragile needs and slight hp boost as well as acceleration again I know it was buffed recently but the car is 400k and its really not that much better in terms of acceleration or speed against I m8 keep the current top speed of the Audi r8 and buff acceleration again please. Also for whatever reason the turbo on the audi keeps not staying on

**Comment by fkk-cz** [comment]
https://github.com/fkk-cz/noire_vehicles/blob/be640ca1ed5bd8e6a8604b251ed11d39688e988b/DATA/r820/handling.meta#L7
https://github.com/fkk-cz/noire_vehicles/blob/be640ca1ed5bd8e6a8604b251ed11d39688e988b/DATA/r820/handling.meta#L14-L18

this car already has virtually no drag and generous accel/speed values.
