### ISSUE TITLE
1984 Ford F-150 Tipping Issue

### ISSUE THREAD

**Issue by Bountyrogger** [fkk-cz/noire_vehicles#1282]
So the 1984 just got flown in today and the only issue I honestly see is it very easily tips. Pretty much anything over 20-30 mph and you try and turn and it wants to flip immediately. Looking to see if there is anyway to adjust it so it actually stays on all 4 wheels

**Comment by okxeon** [comment]
Can look into it. Test the 1986 silverado in pdm and see if you would want that handling put onto it.

**Comment by Bountyrogger** [comment]
If you meant the K30 then yeah handling is good to use on the 84 F-150. Maybe with slightly better turning?

**Comment by okxeon** [comment]
I was assuming this was a completely different truck. Forget what I said above. Replaced it with the 2010 dodge ram 3500 here https://github.com/fkk-cz/noire_vehicles/commit/75b7edd4a32a2336dca442a6741050081c0730e5
