### ISSUE TITLE
Jeep Trailcat speed butf

### ISSUE THREAD

**Issue by CasperBoiRL** [fkk-cz/noire_vehicles#1283]
It has 707 hp, and struggles to get over 120MPH. The F250 Damn near outruns the trailcat, and it’s a base model

**Comment by No-Yes1** [comment]
See a previous issue that you have created - https://github.com/fkk-cz/noire_vehicles/issues/1246. Vehicle will not be tweaked.

**Comment by CasperBoiRL** [comment]
You say it’s the price, yet the F250, which is 30K cheaper, and is overall less powerful, is nearly faster than it.

**Comment by No-Yes1** [comment]
Nerfed the F-250 https://github.com/fkk-cz/noire_vehicles/commit/05247bc14632a4556c9d489b6fc64be25f028923. Thanks for bringing it up :)

**Comment by CasperBoiRL** [comment]
there’s no need for that

**Comment by HvrdNo** [comment]
you can make an issue without snitching lmao

**Comment by CasperBoiRL** [comment]
it’s not snitching, i’m comparing to a car. neither one of the cars are fast

**Comment by HvrdNo** [comment]
completely could have went another way about it other than ratting out the veh thats faster than it

**Comment by CasperBoiRL** [comment]
it’s not faster than it. i’m not ratting it out, i’m just saying the jeep should be gaster

**Comment by fkk-cz** [comment]
> you can make an issue without snitching lmao

Do you think we are somehow completely oblivious/unaware of what vehicles are broken?
