### ISSUE TITLE
Ducati Monster 900

### ISSUE THREAD

**Issue by TheBottomFragger** [fkk-cz/noire_vehicles#1284]
I bought this yesterday, and I guess I was happy with the motorcycle itself, or how it was driving, BUT I had to sell it back because it kept breaking down. It literally can’t handle a little hit, especially not with two people on the bike. It broke down twice after my friend got on the bike, and it also can’t handle getting kicked ONCE. 
I don’t know if this makes sense, if it doesn’t, im pretty sure I clipped it happening, so I can post that later if needed.

**Comment by No-Yes1** [comment]
I'll take a look later.

**Comment by No-Yes1** [comment]
Fixed in https://github.com/fkk-cz/noire_vehicles/commit/748529995897a21ac9bea2e090f71fbd8e462065. Please wait for this to merge live.
