### ISSUE TITLE
Vehicle Customization

### ISSUE THREAD

**Issue by xFooliee** [fkk-cz/noire_vehicles#1285]
I've noticed a lot of vehicles have widebody's and although they look cool, the wheel fitment is horrible on a lot of them. Could there be an addition such as like how wide we want the wheels, offset, camber, etc. 
Basically just more things and options that we could do to vehicles we own.

**Comment by okxeon** [comment]
If the wheel fitment is horrible with the body mods its most likely an optimization issue with the model. Is there a specific vehicle you could name that has this issue?

**Comment by CasperBoiRL** [comment]
im pretty sure the non-supporter GTR has this, same with the R/T

**Comment by okxeon** [comment]
![Screenshot 2022-07-30 015433](https://user-images.githubusercontent.com/98451518/181877055-6ffff349-5b71-46fe-b3a0-885cc26defd3.png)
I see what you mean how the wheels don't move out. Unfortunately I don't believe there is a clean way to implement what you are suggesting.

**Comment by No-Yes1** [comment]
We've discussed this in an different issue - the ability to get a Stancer/modify vehicles is simply not an ability. Refer to this issue for further information: https://github.com/fkk-cz/noire-public/issues/761
