### ISSUE TITLE
Ford Fiesta WRC chnged to offroad class

### ISSUE THREAD

**Issue by CasperBoiRL** [fkk-cz/noire_vehicles#1287]
It is a jacked up rally car, so i think it should be off road class.

**Comment by fkk-cz** [comment]
Misread this earlier -- I thought you were saying this vehicle was incorrectly set to `VC_OFF_ROAD`.

**Comment by CasperBoiRL** [comment]
what? so it cant be switched to offroad? its literally WRC car

**Comment by okxeon** [comment]
> It is a jacked up rally car, so i think it should be off road class.

What is even wrong with the car? Is the traction / handling bad off road? Or do you literally just want it to have the label of being an off road car?

**Comment by CasperBoiRL** [comment]
Trunk Space. I’m on the mission to have the sickest mining rig. I have a Charger OffRoad, Jeep Trailcat, and a hilux. And, it’s off road class, so it should rightfully be 1000 trunk space

**Comment by okxeon** [comment]
Its a rally car not a flatbed truck or a SUV. Makes no sense for it to have 1k truck space.

**Comment by CasperBoiRL** [comment]
So then why not make the trackhawk 1k storage? Bevause when i asked, you said it was based off of class, not the car

**Comment by No-Yes1** [comment]
"should rightfully be 1000 truck space" - no, no it shouldn't. You want it to stick mining vehicles on.

**Comment by No-Yes1** [comment]
> So then why not make the trackhawk 1k storage? Bevause when i asked, you said it was based off of class, not the car

So now you're ratting out even _more_ cars, nice.
