### ISSUE TITLE
Bugatti bolide is broken

### ISSUE THREAD

**Issue by tythetanman** [fkk-cz/noire_vehicles#1288]
Way to cracked/fast for the price (I think The kids now a days say cracked) 

way to fast for under $1 million.  At over 230mph top speed.

**Comment by Decratic** [comment]
The car used to cost $575,000 and is the price I purchased it for . I'm not too sure why they price dropped it by so much when it's such a good car.

**Comment by mfried456** [comment]
Going to have to strongly disagree here. Top speed is no where near 230 and is closer to 212-215 on flat and straight streets. I feel it is very fair for how much it costs.

**Comment by tythetanman** [comment]
Senna is 715k. Top speed around 212-215

**Comment by Decratic** [comment]
They just need to put the original price back tbh

**Comment by mfried456** [comment]
> Senna is 715k. Top speed around 212-215

Good reason for why the senna should be buffed; not for why the bolide should be nerfed

**Comment by HvrdNo** [comment]
mfried456 is correct 575k was the price for the car before the most recent drop it used to be more than that at one point 
it doesnt go 230 and how is it fair to the people who bought it at the higher prices it gets gutted 
not sure why we are here saying this car needs to be nerfed just ask for a buff of the car u want tweaked and move on

**Comment by HvrdNo** [comment]
lets not forget when the car was slower than a supra but yall werent here for that

**Comment by CasperBoiRL** [comment]
> > Senna is 715k. Top speed around 212-215
> 
> Good reason for why the senna should be buffed; not for why the bolide should be nerfed

bro it barley goes that fast in real life. when people ask for buff based on price, they say that cars are based on irl performance and not price. but when someone like me asks a slow car to be buffed bc its way faster irl, they say that it is based on price.

**Comment by Decratic** [comment]
The Bolide can hit 300+ IRL.

**Comment by CasperBoiRL** [comment]
Yeah, but it also costs millions irl.

**Comment by Decratic** [comment]
Definitely needs to go back to the original price at least.

**Comment by Scubaaaaa** [comment]
I will agree that the car was a too good for the price. Slightly nerfed the top speed and acceleration. https://github.com/fkk-cz/noire_vehicles/commit/2bfc6889748b6310d353f620dd37c53faccf78c2

**Comment by tythetanman** [comment]
I take full responsibility for being that bitch that got this nurfed 😂

**Comment by Decratic** [comment]
RIP Bolide 😢🤣

**Comment by mfried456** [comment]
Ridiculous…this is why we can’t have nice things @tythetanman

**Comment by TdotG** [comment]
Seems like Ty is public enemy #1 rn lol

**Comment by PsychoticCore** [comment]
> I take full responsibility for being that bitch that got this nurfed 😂

I'll take half you can take the other half

**Comment by mfried456** [comment]
> I will agree that the car was a too good for the price. Slightly nerfed the top speed and acceleration. [2bfc688](https://github.com/fkk-cz/noire_vehicles/commit/2bfc6889748b6310d353f620dd37c53faccf78c2)

@Scubaaaaa the car was nerfed too much - doesn't even hit 200 now, sometimes barely even cracks 190. Can you please find a middle ground?

**Comment by tythetanman** [comment]
He did that on purpose

**Comment by okxeon** [comment]
It should be doing 190 flat - 200+ on a downhill. If its not doing that can take a look later in game.

**Comment by Jakebeastt** [comment]
that's how the bugatti veyron goes its like 180-190 than it goes to 200 on a straight than sometimes it speeds up. so im not really seeing a problem at all. i've had that bugatti bolide before i think it does very well on how it works.

**Comment by okxeon** [comment]
People can make the argument "oh but it goes 300+ irl and only 190-200 in here". Yea you're right but it also comes with a price tag of 4.7 million where as in here its only $460,000. For a tenth of the price you are getting a sleek bugatti that will do 190 - 200. This is very fair, especially when comparing speed to the many other cars in its price point. I am really not seeing a problem here as the car still goes fast. This was a slight nerf.

**Comment by CasperBoiRL** [comment]
Yeah, we’ll the cars that i requested to be buffed were pretty much the exact same price has irl, so there’s no reason why it’s slower

**Comment by BreezyEZ** [comment]
Maybe you stop complaining. The car is fine the way it is and was justified reasonable by multiple people. Learn some common sense. Thank you. :)

**Comment by Competent1** [comment]
Casper, you complain and whine the most about vehicles. I wish your messages were like Casper the ghost, invisible.
