### ISSUE TITLE
2017 Lamborghini Huracan Spyder

### ISSUE THREAD

**Issue by mfried456** [fkk-cz/noire_vehicles#1290]
The top speed needs a minor buff - not sure if it is related to the drag or weight of the car that is slowing it down

**Comment by No-Yes1** [comment]
The car is absolutely fine for the price tag. The Bolide just got nerfed and is possibly a little slower then this now (even though it's got way less weight then the Huracan). Car will not be tweaked. https://streamable.com/fgznlp
