### ISSUE TITLE
2010 BMW M5 F10

### ISSUE THREAD

**Issue by Decratic** [fkk-cz/noire_vehicles#1292]
My car used to be fully modified and had a livery on it. Now when I go to Los Santos Customs there aren't any modifications for this model anymore. Not sure what happened.

**Comment by okxeon** [comment]
Looks like its modkit ID got duplicated to another car for some reason. Fixed here https://github.com/fkk-cz/noire_vehicles/commit/03fabef7355bf4e6d1940e9d27026927fb9bd27b for next merge.
