### ISSUE TITLE
Dodge RAM 1500 - won't spawn at PDM?

### ISSUE THREAD

**Issue by livxy** [fkk-cz/noire_vehicles#1294]
Quite simply put, the Dodge RAM 1500 won't spawn at PDM so I can't buy it new or test drive it. I restarted my game multiple times.

**Comment by No-Yes1** [comment]
The Dodge RAM 1500 was removed from PDM a long time ago, it needs to be removed from the pdm DB

**Comment by livxy** [comment]
thank you!! :)
