### ISSUE TITLE
2003 Infiniti G35

### ISSUE THREAD

**Issue by HellcatOwner420** [fkk-cz/noire_vehicles#1298]
Brought this car into the city a couple months ago and I realized it only allows you to upgrade the turbo and no other performance mods. This is a pretty sporty base model car In the real world so I was wondering if you guys could fix that.

**Comment by No-Yes1** [comment]
Fixed in https://github.com/fkk-cz/noire_vehicles/commit/87eaeaf1744ddbf70466e9ccfe0c0d4787b283c6. Please wait for this to merge live.
