### ISSUE TITLE
SL600 sound

### ISSUE THREAD

**Issue by tantatertot** [fkk-cz/noire_vehicles#1299]
It would be pretty sick for the 600SL to have the same sound as the Pagani Huayra Roadster as the Huayra actully uses the same v12 engine from the 600SL

**Comment by No-Yes1** [comment]
Fixed in https://github.com/fkk-cz/noire_vehicles/commit/6a519856c75f5b98f4c103eb81e3f86306daee33. Please wait for this to merge live.
