### ISSUE TITLE
Ford Raptor 6.2L V8 Underpowered Compared to V6 3.0L

### ISSUE THREAD

**Issue by RealDarkwater** [fkk-cz/noire_vehicles#130]
Makes no sense a fully tuned 32,000$ 3 Litre V6 Colorado feels faster/quicker than a fully tuned $90,000 Raptor with 6.2 Litre V8 (3.2 litres more of displacement and 2 more cylinders than the Colorado.

I was saving up after a week of legal jobs for it to be an immensely disappointing purchase please tweak this truck, and thank you for all for tweaking/bugfixing/maintaining everything in the server!

-M

**Comment by RealDarkwater** [comment]
For reference the Colorado ZR2 3L produces 300HP, the Baha SVT Raptor R (pictured in game) is rated at 500HP.

**Comment by fkk-cz** [comment]
https://github.com/fkk-cz/noire_vehicles/commit/017ce2c15b03f6d4abf73451083b9e89487afba5#diff-1111367e721cb19369761b9cae5e696f891363df7039eedfbdbc8152c2b92301
