### ISSUE TITLE
350z customization

### ISSUE THREAD

**Issue by tantatertot** [fkk-cz/noire_vehicles#1301]
The 2003 Nissan 350z has no customization at all no engine upgrade no body parts no nothing

**Comment by No-Yes1** [comment]
Fixed in https://github.com/fkk-cz/noire_vehicles/commit/5aad0adc5dcc9c61953aa0c9109288401bdeab53. Please wait for this to merge live.

**Comment by tantatertot** [comment]
does it have any body mods?

**Comment by No-Yes1** [comment]
you're going to have to wait for that to merge live into the server to get an answer for that.

**Comment by tantatertot** [comment]
when will this merge?

**Comment by okxeon** [comment]
Keep an eye on the https://discord.com/channels/777682935687413790/872873208875974736 channel
