### ISSUE TITLE
Carrera Gt sound

### ISSUE THREAD

**Issue by tantatertot** [fkk-cz/noire_vehicles#1302]
I think it would be cool for the carrera gt to get the lfa sound as they sound similar in real life and are known for being 2 of the best sounding v10s ever

**Comment by No-Yes1** [comment]
Tweaked both Carrera GT's to the LFA sound: https://github.com/fkk-cz/noire_vehicles/commit/ff2c6b72ee1dead81b6228b2f49bce105203a81d. Please wait for this to merge live.
