### ISSUE TITLE
SF90 has bugged textures 

### ISSUE THREAD

**Issue by IIBurntLuisII** [fkk-cz/noire_vehicles#1303]

**Comment by Mynameisnotlenny** [comment]
Can you elaborate? Maybe provide photos/videos of what specific textures are bugged on the vehicle.

**Comment by IIBurntLuisII** [comment]
im mining rn but the texture looks chrome on some parts and other blue

**Comment by IIBurntLuisII** [comment]
https://steamcommunity.com/sharedfiles/filedetails/?id=2843730380
here is a pic of wa i mean

**Comment by fkk-cz** [comment]
Textures were completely broken on this. Downloaded the original vehicle files and recompressed them to ~23 MiB.

**Comment by okxeon** [comment]
![image](https://user-images.githubusercontent.com/98451518/188590041-b8428cab-1c99-47af-b7ad-8d66b1481d2d.png)
![image](https://user-images.githubusercontent.com/98451518/188590080-dffcf0e7-c368-4594-9210-96d5a372f537.png)
Vehicle textures seem to be fixed after recompressing.
