### ISSUE TITLE
Is it possible to get the dirt reduced idk if thats something that would or could get changed 

### ISSUE THREAD

**Issue by IIBurntLuisII** [fkk-cz/noire_vehicles#1305]
https://gyazo.com/fca96f5608bcc34939a3ff406a93e07f

**Comment by noyeahsure** [comment]
dirtmaps cannot be changed sadly. its been brought up but its nothing the team can fix.

**Comment by IIBurntLuisII** [comment]
oh ok

**Comment by PsychoticCore** [comment]
I wish the Jesko could stay that clean lol

**Comment by IIBurntLuisII** [comment]
same with the svj it gets dirty in 4 mins

**Comment by Stagonium** [comment]
As stated above, dirtmaps cannot be changed unfortunately.

**Comment by IIBurntLuisII** [comment]
nah i know im just sayin

**Comment by Cobby1-89** [comment]
yea, carwash
