### ISSUE TITLE
Ford F-350 Super Duty Small Trailer pulling 

### ISSUE THREAD

**Issue by PeanutTheCop** [fkk-cz/noire_vehicles#1307]
Whenever you try to connect a small trailer, the trailer just connects to the gooseneck hitch. This makes it outrageously hard to control and the brakes serve no function.

**Comment by No-Yes1** [comment]
This seems like a weird model issue where it hooks it up to the other trailer point - I'll just unsupport the ``trailercar``

**Comment by No-Yes1** [comment]
Fixed in https://github.com/fkk-cz/noire_vehicles/commit/b0d47005e66b1e24ad9d6614ef156b9479594ba6. Please wait for this to merge live.
