### ISSUE TITLE
1999 Skyline GTR livery issue 

### ISSUE THREAD

**Issue by thr33o5king** [fkk-cz/noire_vehicles#1309]
I purchased my ‘99 GTR and it came with a Livery. When attempting to remove the Livery it would not save and reverts back to the Livery. Note: switching to another livery will keep the livery it is switched to. However switching to “default” to remove any livery reverts it back to the first Livery selection.

**Comment by thr33o5king** [comment]
Issue resolved on its own. Workaround that was performed:

While in the customizing menu, left city and joined back hours later. 

Vehicle was still at the mod shop but out of the customize menu. Was able to drive away with no livery. 

May still need some looking into. Not sure if visiting the mod shop again will bring back the livery.

**Comment by thr33o5king** [comment]
Just pulled my GTR from the garage and the livery is back on

**Comment by No-Yes1** [comment]
Fixed in https://github.com/fkk-cz/noire_vehicles/commit/f7fc9a53b3d069d91dfc56b844c9e0955e202f66. Please wait for this to merge live.
