### ISSUE TITLE
Enhancement to 1992 Honda NSX (supporter)

### ISSUE THREAD

**Issue by thr33o5king** [fkk-cz/noire_vehicles#1310]
Is there a way to give the NSX engine a bit louder of an engine sound and better turbo spool? Currently the engine sound and turbo spool sound similar to a regular GTA online vehicle. Any enhancement would be appreciated. 

Thanks!

**Comment by No-Yes1** [comment]
Have you got a vehicle sound in mind?

**Comment by thr33o5king** [comment]
I don't necessarily have a particular sound in mind. But maybe closer to the GTR R35 that is in the game to give it more of an exotic Rec/purr and louder turbo blow-off Or the 1998 Supra. I see the NSX isn't exactly very fast (top speed about 147-150 depending on the dips of the road) so maybe closer to the sound of the GTR R35

**Comment by thr33o5king** [comment]
[](https://youtu.be/HjYpJ7nZVD0)

**Comment by thr33o5king** [comment]
[Honda NSX turbo](https://youtu.be/v0cyimWbbFw)

**Comment by No-Yes1** [comment]
Updated audio hash to the same one as the GTR R35: https://github.com/fkk-cz/noire_vehicles/commit/6b5b40b1107ef75d56243d27e6033f4a020f9e56. Please wait for this to merge live.
