### ISSUE TITLE
BMW M4 Competition - Gets too dirty too fast

### ISSUE THREAD

**Issue by IIcey77** [fkk-cz/noire_vehicles#1311]
The BMW M4 gets dirt very fast, myself along with a few friends have this car and noticed that driving like 2 or 3 miles on paved roads gets dirt all over the car. A trip from PDM to UCL will have it looking like I took it mudding. Would it be possible to tone that down a bunch of notches?

**Comment by No-Yes1** [comment]
That's a model issue and can't be fixed.
