### ISSUE TITLE
Buff Infiniti G35 Sounds And Speed

### ISSUE THREAD

**Issue by thr33o5king** [fkk-cz/noire_vehicles#1312]
I was wondering if it was possible to buff the speed of the 2003 Infiniti G35. Currently it has slow acceleration and does not have ability to upgrade Engine levels. Top speed about 125. Should be closer to the 370z Nismo. Sound should be similar to that of the Q50 that is in the game. 

Thanks in advance!

**Comment by Baker187** [comment]
03 g35 0-60 is 6.2 sec    370z is 4.8 secs
g35 0-100 16 secs          370z 11.7sec 
260-280HP                          350HP
                                            
So no where close to 370z

**Comment by No-Yes1** [comment]
> Currently it has slow acceleration 

That's a lie - the vehicle has good acceleration for the price of the vehicle.

> does not have ability to upgrade Engine levels.

That's a weird model/creator issue and can't be fixed (we've tried in the past)

> Top speed about 125. Should be closer to the 370z Nismo.

Refer to mine and Baker's comments above. The vehicle's top speed will not be tweaked further.

> 5. Should be closer to the 370z Nismo. Sound should be similar to that of the Q50 that is in the game.

Replaced audio hash https://github.com/fkk-cz/noire_vehicles/commit/9db63966f0a838ca69ac4a8da559b068bc047b6c.

I tweaked the traction values slightly too as upon testing it does seem to handle rough af round corners and slide out - https://github.com/fkk-cz/noire_vehicles/commit/f842dfaf6c30b285b6e2bb95a28a2c2166907c9d. Please wait for both of these to merge live.
