### ISSUE TITLE
Change off sound

### ISSUE THREAD

**Issue by IseeNomore** [fkk-cz/noire_vehicles#1313]
I think the 720s Spider and N-Largo are just way to loud, I was thinking maybe change the sounds to the Jesko sounds wich still sounds great.

**Comment by No-Yes1** [comment]
Tweaked both of them to the jesko audio hash: https://github.com/fkk-cz/noire_vehicles/commit/5b8e60d9027692a2fca05f8a3edc793df661e274. Please wait for this to merge live.
