### ISSUE TITLE
Enhancement to 1992 Porsche 911 GT2

### ISSUE THREAD

**Issue by Robbinrubbindeeznutz** [fkk-cz/noire_vehicles#1314]
Enhancement to 1992 Porsche 911 GT2. The GT3 is way faster than the GT2 yet in real life GT2 has 523 hp and the GT3 has 500 hp. In game gt3 tops out at 190-200 while the GT2 barely cracks 160. GT2 should also be one of the loudest cars in the game, the RWB built GT2 are crazy loud

**Comment by Robbinrubbindeeznutz** [comment]
https://youtu.be/RvJ_WhjUl5s

**Comment by okxeon** [comment]
Swapped its engine sound here https://github.com/fkk-cz/noire_vehicles/commit/a4604fb5f2a6bb16545e104a2202f3cbc5a16d05 to the one on the 2017 Mclaren 720s since you wanted loud. As for its speed I was hitting 170+ mph and for a $275k price tag that is good enough.
