### ISSUE TITLE
Mclaren 765 lt Upgrade issues

### ISSUE THREAD

**Issue by Planegorgon** [fkk-cz/noire_vehicles#1316]
The car doesn't have the ability to upgrade Engine or Transmissison! When is this going to be fixed?

**Comment by Planegorgon** [comment]
This is my second supporter car and both have just disspointed me, anyway I cant get my money back or a refund on that car I paid about 382k and I really don't want the car if I can't even upgrade the engine or transmission on it. Car goes like 160 my Zl1 camaro goes faster then that.

**Comment by okxeon** [comment]
Its previous modkit ID should have been fine, but in case there was some odd issue swapped it out here https://github.com/fkk-cz/noire_vehicles/commit/b242cd1cf61a64ea95b083f8794619fd7bcf72aa. If this does not solve the issue its an issue with the vehicles model and can not be fixed. Wait for this tweak to merge.
