### ISSUE TITLE
Lamborghini Sesto Elemento Buff

### ISSUE THREAD

**Issue by PeanutTheCop** [fkk-cz/noire_vehicles#1317]
This car is very fast in real life, due to it being full carbon. But in the game, it is mediocre. Irl it has a top speed of around 221, and 0-60 in 2.5 seconds. It is way slower in the city, and deserves a buff.

**Comment by Scubaaaaa** [comment]
For the $450,000 price the car is perfectly fine where it is. It goes over 175mph in test drive. The car doesn't need a buff.

**Comment by PeanutTheCop** [comment]
What? I was only hitting 150s.
