### ISSUE TITLE
2019 Porsche 911 GT2 RS Handling

### ISSUE THREAD

**Issue by mfried456** [fkk-cz/noire_vehicles#1318]
The 2019 Porsche 911 GT2 RS is a track car with great handling and insane power big city but doesn't match in city. Can the handling be tweaked? More specifically, the car has a lot of oversteering

**Comment by okxeon** [comment]
As far as the speed goes that will not be tweaked due to its price tag. If the car has handling issues like the oversteering that you mentioned that can be tweaked accordingly. Will take a look later tonight.

**Comment by okxeon** [comment]
I am not having oversteer issues with this vehicle. At low speeds it turns well and feels good. At high speeds its alright for a RWD porsche. Also its handling was just tweaked yesterday to improve its handling. In my opinion the car is nice for the price and does not need to be tweaked.
