### ISSUE TITLE
2020 Dodge Charger SRT Hellcat (sjdodge) Textures

### ISSUE THREAD

**Issue by Planegorgon** [fkk-cz/noire_vehicles#1320]
Is the broken texture on the Charger Hellcat which is worth about 268k going yo be fixed if so how long? Or is the car going to get taken out?

**Comment by fkk-cz** [comment]
Which vehicle are you referring to? Provide the plate or exact model name.

**Comment by Planegorgon** [comment]
It's the 2020 Dodge Charger SRT Hellcat under supporter worth $268,555.

**Comment by fkk-cz** [comment]
Restored the original texture dictionary, should fix the visual issues.

**Comment by Planegorgon** [comment]
Alright I'll test drive and let you know! Thanks.

**Comment by Planegorgon** [comment]
Test drove it still was having same issue.

**Comment by fkk-cz** [comment]
Looks like it's a model issue then. This cannot be fixed without contacting the original vehicle creator. Issuing a recall for this.

**Comment by Planegorgon** [comment]
So I should sell it back and get some money back before it's gone huh?
