### ISSUE TITLE
2019 porsche gt2rs speed

### ISSUE THREAD

**Issue by Rakeem21** [fkk-cz/noire_vehicles#1321]
this car should be going a higher top speed or faster acceleration. IRL this car goes 211 mph top speed but i can barely go 195 on the highway. the ferrari 458 prior has a higher top speed and better acceleration even though it is half the price of it. the porsche should get a buff.

**Comment by dinmamma100** [comment]
this car should atleast top out 210mph

**Comment by No-Yes1** [comment]
That's just simply not true:

gt2rs:

https://github.com/fkk-cz/noire_vehicles/blob/0e83d75ace575ff2295d08e28cc414c37e5a2bc5/DATA/gt2rs_data/handling.meta#L13 - Acceleration

https://github.com/fkk-cz/noire_vehicles/blob/0e83d75ace575ff2295d08e28cc414c37e5a2bc5/DATA/gt2rs_data/handling.meta#L17 - Top speed = 192mph

458 prior:

https://github.com/fkk-cz/noire_vehicles/blob/0e83d75ace575ff2295d08e28cc414c37e5a2bc5/DATA/pd458wb_data/handling.meta#L13 - Acceleration

https://github.com/fkk-cz/noire_vehicles/blob/0e83d75ace575ff2295d08e28cc414c37e5a2bc5/DATA/pd458wb_data/handling.meta#L17 - Top speed = 189mph.

The car will NOT be receiving another buff. For the price of the vehicle the car is fine.
