### ISSUE TITLE
2019 PORSCHE GT2RS traction at start of acceleration

### ISSUE THREAD

**Issue by Rakeem21** [fkk-cz/noire_vehicles#1322]
the traction right when you start accelerating is ass, it spins out a bit right when you start to accelerate causing it to make lower 0-60 speeds rather than how it should be. it makes cars that have worse acceleration, beat the porsche in races even when they shouldn't be able to.

**Comment by No-Yes1** [comment]
Fixed in https://github.com/fkk-cz/noire_vehicles/commit/0fbbbd89b33e1e31c986df695045f158ecb3ff13. Please wait for this to merge live.
