### ISSUE TITLE
Porsche 911 turbo s needs a speed buff 

### ISSUE THREAD

**Issue by T45DARK** [fkk-cz/noire_vehicles#1326]
the 911 turbo s needs a speed buff of at least 20 mph and it needs better acceleration in the higher gears it gets up to 120 fast but after than it takes about a minute and a half to get to 170-180 for a 350 thousand dollar car i believe you should get what your paying for

**Comment by Rakeem21** [comment]
you want the turbo s to go 200+?

**Comment by No-Yes1** [comment]
Which year are you referring too? 2021 or 2016?

**Comment by T45DARK** [comment]
the 2016

**Comment by No-Yes1** [comment]
For the price of the vehicle, and the acceleration/handling on it already, the vehicle will not be tweaked.
