### ISSUE TITLE
s1000rr

### ISSUE THREAD

**Issue by dinmamma100** [fkk-cz/noire_vehicles#1327]
the s1000rr needs a speed buff it tops out at 155 without wheelie and hard to get over 175 with wheelie the bike dosent have any mods except the turbo

**Comment by Scubaaaaa** [comment]
People were using the BMW s1000rr as a meta for getaways, which is why the vehicle got nerfed and won't be re-buffed. Can blame other people for not wanting to RP and just have an end goal to get away as fast and unrealistic as possible.
