### ISSUE TITLE
2003 Carrera GT 470k edition 

### ISSUE THREAD

**Issue by DarkHourEnt** [fkk-cz/noire_vehicles#1328]
The vehicle is beautiful and sounds amazing but the top speed on it is 170 going down hill I like the car but would be in love with it if it can go slightly faster!

**Comment by okxeon** [comment]
Tweaked here https://github.com/fkk-cz/noire_vehicles/commit/26f4cbd6c5de3af34458a3edf56bdf9b6bba81e7. Averages 180+ on flat. Also I agree the car does look super clean.

**Comment by DarkHourEnt** [comment]
Thank you !!
