### ISSUE TITLE
Bugatti Bolide

### ISSUE THREAD

**Issue by RomanianSniper** [fkk-cz/noire_vehicles#133]
Just saved up for awhile to buy this car and it is slow, top speed is around 130 which is still slower than my Urus (after nerf). If this could be improved I would appreciate it, Thank you!

**Comment by fkk-cz** [comment]
https://github.com/fkk-cz/noire_vehicles/commit/017ce2c15b03f6d4abf73451083b9e89487afba5#diff-880a742f81b65cccc889d2bb95f1b7f7ca27375ad92c28bd537c837dcfaa3adf

**Comment by RomanianSniper** [comment]
Just went for a test drive and I am liking the new changes, thanks again!
