### ISSUE TITLE
Subaru WRX STI sound

### ISSUE THREAD

**Issue by Cozy5** [fkk-cz/noire_vehicles#1330]
Hi this post is regarding the STI sound. Is there any way it can be changed from the stock gta sound to either of these ones? https://www.gta5-mods.com/vehicles/subaru-impreza-wrx-sti-ej20-f4-sound-mod-sp-add-on-fivem  or  https://www.gta5-mods.com/vehicles/subaru-sti-ej257-f4-engine-sound-oiv-add-on-fivem-sound  It would amazing if possible. Thank you!

**Comment by No-Yes1** [comment]
We're not adding in any new custom sounds -- if you have an idea of one that's already in game that sounds somewhat realistic, then post it here
