### ISSUE TITLE
2020 Mercedes-Benz AMG GT Black handling at high speeds

### ISSUE THREAD

**Issue by mfried456** [fkk-cz/noire_vehicles#1334]
When the 2020 Mercedes-Benz AMG GT Black gets up to high speeds, the handling is bad and will quickly spin out at a slight turn.

**Comment by okxeon** [comment]
Yeah after testing the vehicle I see what you mean, but for the price the cars handling cant be perfect. Especially since it averages 185-190 as a top speed which is already higher than most cars in its price range.

**Comment by mfried456** [comment]
Yea I definitely agree with the top speed but was just wondering if there was a way to tweak the handling at high speeds so that there was a little bit of tolerance to turns and it wouldn’t spin out. If not, all good thanks for checking

**Comment by okxeon** [comment]
I mean yes it is possible to do, but I feel as if for the price of the car it performs well enough.
