### ISSUE TITLE
2019 porsche gt2rs supporter car (traction issue)

### ISSUE THREAD

**Issue by Rakeem21** [fkk-cz/noire_vehicles#1335]
respectfully, im pretty sure you guys increased the traction loss at low speeds instead of decreasing it. it feels like a muscle car's launch. please fix

**Comment by No-Yes1** [comment]
taking a look at this later.

**Comment by Rakeem21** [comment]
> taking a look at this later.

alright thank you!

**Comment by No-Yes1** [comment]
Fixed issue, tried and tested and it's defo a lot better. Last time this vehicle will receive any further traction issues: https://github.com/fkk-cz/noire_vehicles/pull/1339/commits/72d546330e1ce9b949edd03e58a6aad85e2642e6. Please wait for this to merge.
