### ISSUE TITLE
Rx7 VeilSlide

### ISSUE THREAD

**Issue by cxerq** [fkk-cz/noire_vehicles#1336]
It feels like the steering locks when trying to turn at a someone what high speed 90mph+

Any chance that could get fixed!

**Comment by okxeon** [comment]
Its handling at higher speeds is going to be worse but it is certainly manageable. The car was designed to be a low-medium speed drift car. After I drove it down the freeway a few times I see what you mean, but its intended purpose is to drift - not to drive in a straight line at high speeds.
