### ISSUE TITLE
F350 King Ranch 6x6 suspension

### ISSUE THREAD

**Issue by DankGrandma** [fkk-cz/noire_vehicles#134]
i want to see about tweaking the suspension on this truck. When climbing even small rocks under 15mph she hops of them pretty strongly. 
can we try raising the fMass value to like 2800 and raising the fSuspensionReboundDamp value to 1.8

**Comment by DankGrandma** [comment]
I might have it backwards and the values need to be lowered. higher is supposed to be stiffer..

**Comment by fkk-cz** [comment]
> 
> 
> I might have it backwards and the values need to be lowered. higher is supposed to be stiffer..

https://github.com/fkk-cz/noire_vehicles/commit/6df7812acf5a3920a2eb2475df7bc11a5d59b007#diff-011166622d7cea893b593dd67941a355c248bb94e84751d6496b6b765ef15cf8
