### ISSUE TITLE
Koenisegg Regera Buff

### ISSUE THREAD

**Issue by PeanutTheCop** [fkk-cz/noire_vehicles#1342]
It took me 21 seconds to get down the test track in this car, with a top speed of 155. In real life, it takes the car 22 seconds to reach 249 MPH. It obviously shouldn’t go that fast, that is game breaking, but it should be able to go at least 180-185 at the end.

**Comment by PeanutTheCop** [comment]
And the Jesko Audio hash would be nice too

**Comment by okxeon** [comment]
The vehicle already averages 190 on a flat and 200+ on bumps and downhill. Granted for its price tag it can be increased slightly and was done here https://github.com/fkk-cz/noire_vehicles/pull/1344/commits/dedbd4fc58af9dcc67a64f1292218f27e265f498, but the vehicle handles very well so cant make it too fast. As for swapping the audio hash that was done here https://github.com/fkk-cz/noire_vehicles/commit/fa0f00833a9b511a00020325890a74d16d6e0667.

**Comment by PeanutTheCop** [comment]
It also only has 1 gear irl. This is small, but would make a difference
