### ISSUE TITLE
2017 Dodge Charger

### ISSUE THREAD

**Issue by Mynameisnotlenny** [fkk-cz/noire_vehicles#1345]
The 2017 non supporter Dodge Charger has no upgrades available besides turbo, just wanted to see if this was able to be fixed.

**Comment by No-Yes1** [comment]
Refer to these historical issues: https://github.com/fkk-cz/noire_vehicles/issues/254 / https://github.com/fkk-cz/noire_vehicles/issues/803. Vehicle does not have any customizations and can not be added.
