### ISSUE TITLE
2019 aventador svj issues

### ISSUE THREAD

**Issue by Rakeem21** [fkk-cz/noire_vehicles#1348]
this car deserves upgrades, its literally a stock car. the windows cant be tinted and car horn cant be changed or anything and the engine/vehicle in general doesnt have upgrades

**Comment by No-Yes1** [comment]
Fixed in https://github.com/fkk-cz/noire_vehicles/commit/f3b1cbe852672f96e957d83d65a0218796399bb2. Please wait for this to merge live.
