### ISSUE TITLE
ferrari 488 pista top speed

### ISSUE THREAD

**Issue by XRSRUNSYOU** [fkk-cz/noire_vehicles#1349]
The car is $375,000 but cant go over 167 mph, I feel that this speed is not fit for the car. It would be great if you guys could take a look at the vehicle top speed and tweak it a little bit. Thank you!

**Comment by No-Yes1** [comment]
https://github.com/fkk-cz/noire_vehicles/blob/36f4056b5e10ae0b389f2cd7d27257d8e0caeda4/DATA/pista_data/handling.meta#L17 - This would give the vehicle a total top speed of 199.99mph

https://github.com/fkk-cz/noire_vehicles/commit/f69e5c8f8b371ce7fb0d78a4c674f7fe9ee83106 - Decrease the drag significantly so this should improve. Anything over the value 5.0 means the vehicle's top speed decreases <= 20mph. Please wait for this to merge live.
