### ISSUE TITLE
Regera Further Acceleration Buff

### ISSUE THREAD

**Issue by PeanutTheCop** [fkk-cz/noire_vehicles#1351]
It was recently buffed, but not by a big margin. It still only goes 155 at the end of the test track, which is horrible for the real life comparison of the car (and the price) it was mentioned that due to the handling, it can’t be made too fast. I would be down to sacrifice MOST of the handling in order to enable to fat to do a realistic speed of about 175-180 at the end of the track.

**Comment by PeanutTheCop** [comment]
The car is made to be a super fast braking and acceleration car, not really made for cornering.

**Comment by No-Yes1** [comment]
Fixed in https://github.com/fkk-cz/noire_vehicles/commit/a4d8e3129d38cfeea34f396a2f0aa2dbe8a9f58c. Please wait for this to merge live.

**Comment by PeanutTheCop** [comment]
I appreciate you hearing me out and doing it, thank you a lot.
