### ISSUE TITLE
Jeep Gladiator Small Trailer

### ISSUE THREAD

**Issue by Rauzii** [fkk-cz/noire_vehicles#1353]
Will you add availability to haul small trailer with the jeep gladiator, already has a hitch. thanks!

**Comment by No-Yes1** [comment]
This was brought up in the past -- https://github.com/fkk-cz/noire_vehicles/issues/908.

Looks like this was added, if it's unable to tow then it seems like it's not capable sadly :/ 

https://github.com/fkk-cz/noire_vehicles/blob/986fa723d969fe2c9baf7fad0464b370e34abf36/DATA/gladiator_data/vehicles.meta#L101-L109
