### ISSUE TITLE
supporter 2017 camaro zl1 needs a huge speed buff

### ISSUE THREAD

**Issue by T45DARK** [fkk-cz/noire_vehicles#1355]
car hits 165, basically the non supporter zl1 but 40 thousand more, in real life the supporter zl1 has 1000hp and can hit 217 mph

**Comment by okxeon** [comment]
Car is only slightly above 200k so obviously cant make it go 217, but can make it do about 180. Tweaked here https://github.com/fkk-cz/noire_vehicles/commit/9c4a4098c2096c6622631e2d7c3707ae41cce25a.
