### ISSUE TITLE
Regera Acceleration remains unchanged after previous fix

### ISSUE THREAD

**Issue by PeanutTheCop** [fkk-cz/noire_vehicles#1358]
So i put a ticket and we agreed to remove most of the good handling to make the car have better acceleration, as it should. But after the previous fix (https://github.com/fkk-cz/noire_vehicles/commit/a4d8e3129d38cfeea34f396a2f0aa2dbe8a9f58c) nothing changed, it still does the same exact speed in the test track(150-155) I’m pretty sure it has been merged, because in PDM that the drag coefficient is 3.0, which is what the drag coefficient of the fixed car is, not 3.2 (prior to fix) In conclusion, nothing has changed.

**Comment by No-Yes1** [comment]
Checked this out. Fully upgraded the vehicle & car goes 190 with amazing handling: https://streamable.com/4abot3

**Comment by PeanutTheCop** [comment]
Yes, that’s what i’m saying, it seems like absolutely nothing has changed. We “agreed” on removing the good handling and making it a straight line car. (like real life) It would be “realistic” for the car to be going 230 at the end of test track, but that’s game breaking. I was hoping for around 175-180 at the end of test track with a top speed of around 215. Mins you the car cost the exact same IRL, but with a top speed of 260+ and it takes it 22 seconds to go from 0-250 mph.

**Comment by PeanutTheCop** [comment]
I agree that if the car went as fast as i’m asking with that handling, it would be OP. That’s why i was saying remove all of the hood handling, and make it faster straight line speed.

**Comment by No-Yes1** [comment]
I'll have a play around later.

**Comment by PeanutTheCop** [comment]
ight, say less

**Comment by PeanutTheCop** [comment]
results?

**Comment by okxeon** [comment]
Improved the top speed and acceleration here https://github.com/fkk-cz/noire_vehicles/pull/1361/commits/855188d68acb99c4cea613ac9f0b88993ecf4d10. Also you keep mentioning the test track. The major difference between the test track and owning the car is the performance upgrades that will become available with actually owning the car. When you test drive a vehicle you are doing so in its stock form. This is why speed are not the same. So yeah before you were only hitting 155 as you said, but obviously the car goes much faster than that on the freeway. Either way the speed and acceleration was touched up on.

**Comment by PeanutTheCop** [comment]
Yeah, i just used that to gauge the acceleration, as it was a universal measurement. I appreciate it
