### ISSUE TITLE
2020 SRT Hellcat Charger 

### ISSUE THREAD

**Issue by Straightvibes** [fkk-cz/noire_vehicles#136]
The charger seems a lot slower now. Please revert it back to how it was 🙏🏾🙏🏾

**Comment by fkk-cz** [comment]
It hasn't been changed for months?

https://github.com/fkk-cz/noire_vehicles/commits/196320e8c0b00b50de7b0aaf4830dea3e886b927/DATA/srtday20_data/handling.meta
