### ISSUE TITLE
2021 Ducati V4S sound change

### ISSUE THREAD

**Issue by eliaxes** [fkk-cz/noire_vehicles#1360]
the ducati v4s has a sound which doesn't really fit a irl ducati, i think its a original gta sound. It would be nice if it had a better sound like the Ktm Super duke R 1290.

**Comment by eliaxes** [comment]
its the 2021 ducati

**Comment by okxeon** [comment]
Tweaked here https://github.com/fkk-cz/noire_vehicles/pull/1361/commits/d665c7fc952a7334cb69874ce5cb319c61c68ca9. Will now have the audio of the KTM SuperDuke.
