### ISSUE TITLE
McLaren 720 S N-Largo speed issues

### ISSUE THREAD

**Issue by guwop** [fkk-cz/noire_vehicles#1362]
As of today the McLaren 720 S N-Largo struggles to reach over 165 MPH on the highway and it's an almost $400k vehicle that goes 214 MPH in real life.

**Comment by okxeon** [comment]
Tweaked here https://github.com/fkk-cz/noire_vehicles/commit/ae71d04abb86a0d3e6ad4e526a50f1a33142692e. Top speed will now be around 180 mph on flat ground.
