### ISSUE TITLE
1993 Mercedes Benz 600sel Sound revert 

### ISSUE THREAD

**Issue by somedudenamedrush** [fkk-cz/noire_vehicles#1363]
friend of mine owns the car hates driving it cause of the new sound and would like the sound reverted from the current to the original one if possible

**Comment by okxeon** [comment]
Not sure what one was on it before. Do you have a replacement sound in mind you want added to this car?

**Comment by somedudenamedrush** [comment]
13 Bentley Continental GT sound which believe its the SCHAFTER4 sound

**Comment by okxeon** [comment]
Done here https://github.com/fkk-cz/noire_vehicles/commit/6b1f08ba576aa8e1c543238e52276ef120c758bb. Wait for this to merge.

**Comment by somedudenamedrush** [comment]
https://github.com/fkk-cz/noire_vehicles/commit/5bfbeba808120f8f3d7a919c71aa709f3c35371e

that might be the 4 door 600 sl sound u changed was looking thru the data and saw where the change happen [600sl_data ](https://github.com/fkk-cz/noire_vehicles/pull/1300) it currently has a zonda sound

**Comment by okxeon** [comment]
Gotcha, little confusing to have a 600sel & a 600sl. Reverted here https://github.com/fkk-cz/noire_vehicles/pull/1368/commits/21778ad4a87f6f741b47a020294ba9045638be29. Thanks for pointing that out.

**Comment by PeanutTheCop** [comment]
did you put the zonda sound back on the 600sl?

**Comment by okxeon** [comment]
Wait for it to merge.
