### ISSUE TITLE
 2019 Lamborghini Aventador SVJ Upgrade Issues and Horn Issue

### ISSUE THREAD

**Issue by Blurrr5** [fkk-cz/noire_vehicles#1365]
On the 2019 Lamborghini Aventador SVJ under upgrades the only performance upgrade you can change is the turbo, you cannot upgrade engine, suspension, armor, etc.  Also you cannot use any custom horns from LS customs and when u change it it says you purchased the mod but u still have the default horn.

**Comment by okxeon** [comment]
Thanks for pointing out. Vehicle has been fixed here https://github.com/fkk-cz/noire_vehicles/commit/b1e456ab307390c231b10b9c6d285ad3375e36c0. Wait for this to merge to be fixed in game.
