### ISSUE TITLE
2020 Corvette C8 Stingray Customization

### ISSUE THREAD

**Issue by Cozy5** [fkk-cz/noire_vehicles#1367]
Hi, I just bought the C8 Corvette for about 230,000 because I was too impatient lol and it seems like the only thing that is upgradable is the engine upgrades and no cosmetic upgrades, is there any way there could be some more customizable options like Body Parts such as bumpers, skirts, spoilers and such? I just feel like when you are paying 230,000 for a car, it just seems like you should have the ability to upgrade it and make it yours.

**Comment by okxeon** [comment]
We cant add body modifications like that as that's up to the mod creator. I get for 230k you want some additional customization options, but unfortunately none were created for it.
