### ISSUE TITLE
2020 Corvette C8 Stingray Customization 

### ISSUE THREAD

**Issue by Cozy5** [fkk-cz/noire_vehicles#1369]
Hi I just opened an issue like not too long ago and I'm sorry to bug but is there any way this version of it can be added: https://www.gta5-mods.com/vehicles/2020-corvette-c8-stingray-add-on-oiv-tuning-template  If not I get it and I know I already said this but I just feel like I got robbed from all of my hard earned money and it won't sell since it is really expensive.

**Comment by okxeon** [comment]
You did not get robbed... You still own the car, you just can't put any body mods on it. It still goes like 180 for a cheap price and looks clean. Unfortunately we can't replace the model with that one you provided. The C8 is really not that bad of a car - yea it might be disappointing with no insane body mods, but still a perfectly usable vehicle.
