### ISSUE TITLE
Regera Transmission gears

### ISSUE THREAD

**Issue by PeanutTheCop** [fkk-cz/noire_vehicles#1371]
I’m sorry to put in another ticket about this car. I feel it has already been tweaked to perfect performance wise with the last commits, and i thank y’all greatly for putting the car where it should be. That being said, the in game car has 6 gears, as opposed to 1 irl.

**Comment by PeanutTheCop** [comment]
Nevermind, it has came to my attention that it might affect performance, and it’s fine how it is. If it can be implemented without suffering various performance debuffs, than go for it. But if it makes the car slower, it’s fine how it is.

**Comment by Competent1** [comment]
The Regera technically is a hybrid IRL, utilizing batteries and electric motors. This is the reasoning on why IRL it only has one gear, as Konenigsegg has invented their own direct drive system. The vehicle enters electric vehicle mode as well during this. In the city however, the vehicle is NOT a hybrid and does not have an electric mode.  If batteries and electric motors were not used on the vehicle, then it'd be what it currently is in the city right now. This vehicle also had issues when attempting to change it to 1 gear. Hopefully this vehicle is to your liking after the plethora amount of github requests you've made on the vehicle.

**Comment by PeanutTheCop** [comment]
yeah i know, it’s perfect rn. i appreciate it
