### ISSUE TITLE
2020 hellcat 98k 

### ISSUE THREAD

**Issue by dinmamma100** [fkk-cz/noire_vehicles#1372]
this car needs a speed buff becasuse it only tops out at 185

**Comment by BreezyEZ** [comment]
No.

**Comment by Competent1** [comment]
"_only 185_"... does NOT _need_ a speed buff as you are requesting.

**Comment by Competent1** [comment]
This vehicle was abused in the past and due to this, the speed and armor of this said vehicle was lowered.

**Comment by Scubaaaaa** [comment]
Going to agree with what was stated above. People used the vehicle as meta to get away/win in the past. The vehicle doesn't need a buff.
