### ISSUE TITLE
389k lambo sc18 needs a speed buff

### ISSUE THREAD

**Issue by T45DARK** [fkk-cz/noire_vehicles#1377]
389k lambo sc18 needs a speed buff hits 190 should be a bit faster maybe around 205-210

**Comment by PsychoticCore** [comment]
Im not a car Dev or nun but 389k for 190mph car is a pretty good deal

**Comment by BaseTrooper** [comment]
I just bought this car as well. Definitely deserves a buff

**Comment by okxeon** [comment]
The car will not be buffed as it is perfectly fine the way it is now for the price.
