### ISSUE TITLE
1990 454ss issue

### ISSUE THREAD

**Issue by Bigheadsteve214** [fkk-cz/noire_vehicles#1381]
1990 454ss is considered a emergency vehicle 
 
Can you lower the truck where the fenders are by the tires thanks!

**Comment by No-Yes1** [comment]
Fixed in https://github.com/fkk-cz/noire_vehicles/commit/6117210151b3fd1a2eb711fa786a291ddba7f8dd. Please wait for this to merge live.

**Comment by Bigheadsteve214** [comment]
What do you mean to merge live?

**Comment by Competent1** [comment]
> What do you mean to merge live?

Basically means when the changes here are implemented into the server. Don't have to do anything on your part, just be patient. Shouldn't take long at all.

**Comment by Bigheadsteve214** [comment]
Is it gonna be today because it still not working?

**Comment by okxeon** [comment]
wait till the update merges. It will say it in the noire-vehicle channel.

**Comment by Bigheadsteve214** [comment]
The 454ss starts now but can you fix the steering on its hard to turn and you can still see through the firewall inside the truck and the 3rd break light won’t turn off and the break lights won’t come on and no upgraded can be applied it needs to be buffed a little it has a 7.4 in it thanks!

**Comment by Bigheadsteve214** [comment]
Is this getting worked on?

**Comment by Scubaaaaa** [comment]
Suspension issue should be fixed here. https://github.com/fkk-cz/noire_vehicles/pull/1410/commits/768b923f2c1735698279e929e254ab0414fea275
Can't make the truck any lower then it currently is as it would cause the same issue as before.
