### ISSUE TITLE
Pontiac G8 sound add and buff

### ISSUE THREAD

**Issue by Tunawuvsu** [fkk-cz/noire_vehicles#1382]
this car is way slower than it should be, and i think it deserves a buff. also, is there any chance it could get the sound from the c6 zr1 added?  it fits the car very well

**Comment by PeanutTheCop** [comment]
i would love this. i was super disappointed when i asked for the car to be added over a year ago, and it was very underwhelming.

**Comment by No-Yes1** [comment]
> this car is way slower than it should be, and i think it deserves a buff.

Re-wrote the handling.meta file & upgraded top speed, balanced the vehicle out by nerfing acceleration etc as the car is <70K.  https://github.com/fkk-cz/noire_vehicles/commit/aa60c42937643f106865c31822d5f3c7b891a69f.

>is there any chance it could get the sound from the c6 zr1 added? it fits the car very well

Added in https://github.com/fkk-cz/noire_vehicles/commit/75c7362fc4038ff3ea5b2c63ce8a165d1d113df0. Please wait for this to merge live.
