### ISSUE TITLE
Ferrari 488 Pista Texture Bug

### ISSUE THREAD

**Issue by Jamicusoperk** [fkk-cz/noire_vehicles#1383]
The car goes completley matte when you go under shade, and depending on the angle the shine bugs out but none of this occurs if you are in the passenger seat of the car or, you aren't in the car at all. CONTEXT: https://www.youtube.com/watch?v=hwHIZfLHK0Y

**Comment by fkk-cz** [comment]
Recompressed textures & spawned your exact vehicle and tried in the same location -- seems to be fine now.
