### ISSUE TITLE
‘18 Chevrolet Camaro ZL1 Sport performance 

### ISSUE THREAD

**Issue by RangerThrawn** [fkk-cz/noire_vehicles#1384]
The overall performance of this vehicle is a bit disappointing - it’s a $160k vehicle, but it soft tops at a rate/speed similar to a Nissan 370z   ..    it will soft too at 120, then slowwwwwlllyyyyy climb to 150     - it’s unusual for such an expensive vehicle.   Since purchasing it , I have tried to sell it to someone , and people won’t even pay 80k for it because everyone knows about it’s unrealistic/poor performance .   Can you help to raise both the soft top speed and true top speed ?    Thanks so much

**Comment by kdottyyy** [comment]
I 100% agree with this, the hellcat which is like 60k goes 160 while this struggle to even touch 150. For 160k, it def needs a top speed buff.

**Comment by okxeon** [comment]
Modified the vehicle slightly here https://github.com/fkk-cz/noire_vehicles/commit/6d57f3f5d181f3d01465655d73992b3a61243ff8. The car should now get up to speed a bit faster and will also go around 160 mph now. Keep in mind this car is directly competing with the 2017 Hennessey Camaro Exorcist ZL1 as it is designed to be the 'more powerful' version of this car so not a whole lot can be done.
