### ISSUE TITLE
Enhancement to Ferrari 458 Prior

### ISSUE THREAD

**Issue by thr33o5king** [fkk-cz/noire_vehicles#1386]
Can we adjust the sound of the Ferrari 458 Prior to that of the 2019 Ferrari 488 Pista ? This would give the Prior A more typical Ferrari exotic engine sound. 

Thank you in advance !

**Comment by okxeon** [comment]
Swapped its audio here https://github.com/fkk-cz/noire_vehicles/pull/1387/commits/eefb8ee2cec3c82bf0bd52057de2d54244d91191. Wait for it to merge for the change to be implemented.

**Comment by thr33o5king** [comment]
Anyway to reopen this? I purchased the prior thinking it would keep the same sound as the Pista. Now I see it was changed back to original sound. 

This doesn't sound like a Ferrari. Doesn't even have a sound when it's idle

**Comment by okxeon** [comment]
I reverted back to default as it seems not everyone was on the same page on wanting the pista audio swapped to it. Refer to https://github.com/fkk-cz/noire_vehicles/issues/1394. If you can find another one that people seem toa gree to then sure it can be changed.
