### ISSUE TITLE
I've heard from many people that armor reduces speed

### ISSUE THREAD

**Issue by Rakeem21** [fkk-cz/noire_vehicles#1388]
I would like to know if it's true or just plain rumors. 
I have also heard that if you put armor on your car and then take it off, the speed would still be slower than brand new.

If this is true, please fix it so that you can just fully take the armor off. and if its rumors please let me know also.

**Comment by No-Yes1** [comment]
This is a rumour. Due to r* limitations, there is no way of decreasing top speed if you have armour on the vehicle.
