### ISSUE TITLE
2011 Ferrari 599 GTO (599)

### ISSUE THREAD

**Issue by fkk-cz** [fkk-cz/noire_vehicles#1392]
Audio hash & handling needs adjusting.

**Comment by okxeon** [comment]
Handling: https://github.com/fkk-cz/noire_vehicles/commit/cfa30f2b37a231bc3ed25d8b17a0f3a123dcc8b1
Audio: https://github.com/fkk-cz/noire_vehicles/commit/44f38e053696e82157e4c14759bb8dcc730e78b7
