### ISSUE TITLE
2008 Lamborghini Gallardo (gallardo2005)

### ISSUE THREAD

**Issue by fkk-cz** [fkk-cz/noire_vehicles#1393]

**Comment by okxeon** [comment]
Handling edit: https://github.com/fkk-cz/noire_vehicles/commit/c257f4ae4a2d148243dedf0039b5aea18ccc9e14
Not sure what audio hash to give it, will look in game later today.

**Comment by okxeon** [comment]
Audio done here: https://github.com/fkk-cz/noire_vehicles/pull/1410/commits/dadf55b425e2db7a2121b5797d59208b64fa3c65
