### ISSUE TITLE
pagani zonda tricolore sound

### ISSUE THREAD

**Issue by Gmoney7** [fkk-cz/noire_vehicles#1397]
It has a stock gta sound and the sound that closest resembles its real life sound is the murcielago sv sound. and i think it also needs a speed tweak, its kind of slow for 1.6mil it tops about 160-150 in  test drive.

**Comment by okxeon** [comment]
Tweaked its handling here: https://github.com/fkk-cz/noire_vehicles/commit/0e24b9a55ae6728d2c47f0d6c7d443e426763927 & swapped audio hash here: https://github.com/fkk-cz/noire_vehicles/commit/d0afc4a00dc9031ac02988ec4db17228169b3cbe
