### ISSUE TITLE
92 Honda NSX

### ISSUE THREAD

**Issue by LethalTrade** [fkk-cz/noire_vehicles#1399]
I just recently purchased this car and was wondering if a couple things about it could be tweaked or looked into. The turning on the car is horrible (it turns really wide) and when you hit the brakes it just slides. Also if the initial wheel spin can be lower just a bit so you aren't sliding for so long and initial acceleration is slow(this might be because of the wheel spin not sure). Lastly if the sound can be changed to the same sound as the Acura NSX LB.

**Comment by okxeon** [comment]
Gave it the Silvia S14 handling here: https://github.com/fkk-cz/noire_vehicles/commit/aca5b246787e632ec64de2f4dba572361f16e277
Audio was tweaked here: https://github.com/fkk-cz/noire_vehicles/commit/4b8f6ea43fd6f0f707b2958b68a2b82eda28c06c
