### ISSUE TITLE
Mercedes AMG S

### ISSUE THREAD

**Issue by TGK7** [fkk-cz/noire_vehicles#140]
for 181k i think the car should have a 180 top speed and maybe a bit faster acceleration but the cars bugged every time i take it out the garage it changes the cars color to blue it also gets dirty for no reason i washed it then 2 minutes later its dirty again just by having it parked

**Comment by fkk-cz** [comment]
> but the cars bugged every time i take it out the garage it changes the cars color to blue

switch to a non pearlescent paint

> it also gets dirty for no reason i washed it then 2 minutes later its dirty again just by having it parked

this can't be fixed, some cars have dirt textures that are more visible
