### ISSUE TITLE
PikaMobile handling

### ISSUE THREAD

**Issue by woody67890** [fkk-cz/noire_vehicles#1401]
Is there any way that the Pikamobile's handling can be improved so it doesn't roll even with the slightest turn? Also doesn't seem to be very durable, slightest crash and it's disabled. 

The Reliant Robin is the same handling, which I keep for the memes, but I really want the Pikamobile to be a daily car because it's great! Pretty please

**Comment by okxeon** [comment]
Don't know why the default handling was so terrible, tweaked here: https://github.com/fkk-cz/noire_vehicles/pull/1411/commits/58535e99f970627a5a098dde7155d8503a117b0e
