### ISSUE TITLE
Mercedes-Benz Sprinter 211 CDI issues 

### ISSUE THREAD

**Issue by yellingmatt** [fkk-cz/noire_vehicles#1402]
Tested this vehicle couple issues 1. you cant change colors 2.) should go a little fast like 130 thats a comparable speed to big city 3. vehicle has zero sound noise (engine, tires, horn)

**Comment by okxeon** [comment]
Improved the top speed here: https://github.com/fkk-cz/noire_vehicles/commit/62b5fbe8a512b7ab8cb003ccde0a3091f1847c19 & audio was done here: https://github.com/fkk-cz/noire_vehicles/commit/6a25c78fee067e809fdc28c15db68ced49ae6a09. It _should_ now have the audio hash of the ``burrito``.
