### ISSUE TITLE
2018 BMW M5 F90

### ISSUE THREAD

**Issue by PierreWhoopy** [fkk-cz/noire_vehicles#1403]
This car is a Twin turbo V8 and can only go 160 max on a straight, while it can easily reach 190mph but is limited to that to its real life counterpart. And also acceleration is really really sluggish unless you two step it every time. And especially for 212k.

**Comment by okxeon** [comment]
The acceleration I did agree needed an improvement and was increased. The top speed however was also improved, but not nearly as much as you were probably hoping. Yea it might do X speed irl, but the car is also only 212k. If it was going 190 for that speed it would be broken and abused without a doubt. Tweakes were done here: https://github.com/fkk-cz/noire_vehicles/pull/1410/commits/b8f6836407e82b37a79e7efb5ab8cb2acbaaeebb.
