### ISSUE TITLE
1992 honda nsx headlights are inverted

### ISSUE THREAD

**Issue by rawranevilpanda** [fkk-cz/noire_vehicles#1405]
recently I've noticed the headlights go down instead of up, it was working correctly before so I guess some changes that had been done recently to it might have to be reverted

**Comment by okxeon** [comment]
Fixed this issue here: https://github.com/fkk-cz/noire_vehicles/pull/1410/commits/cca088612c7746d741be55a2a86017fb6a024ed5. The problem was it was missing a fPopUpLightRotation value.
