### ISSUE TITLE
BMW M3 E46 GTR

### ISSUE THREAD

**Issue by rawranevilpanda** [fkk-cz/noire_vehicles#1406]
This car has a custom exhaust and it sounds like it has a cat, car should probably be louder or have the engine sound changed, also I feel like It should be slightly faster

**Comment by okxeon** [comment]
Tweaked its audio here: https://github.com/fkk-cz/noire_vehicles/pull/1410/commits/8e372b4b6ce38d09a7dee87bd185c0bc9f600e05. The speed / handling is already excellent for a car that only costs 40k.
