### ISSUE TITLE
Support Vehicle Tweak

### ISSUE THREAD

**Issue by MichaelCoppJr** [fkk-cz/noire_vehicles#141]
Affected: 2017 GMC Sierra 1500.

The vehicle is currently set as " ,Super " and has little no acceleration or top speed.

**Comment by fkk-cz** [comment]
https://github.com/fkk-cz/noire_vehicles/commit/017ce2c15b03f6d4abf73451083b9e89487afba5#diff-762914f9c4ad4b30a695ac2a0fdafcb8ccbe67e09d90cd727a189b2a4f77587a
https://github.com/fkk-cz/noire_vehicles/commit/017ce2c15b03f6d4abf73451083b9e89487afba5#diff-0f38b7c546da153d6c2be511dddc45df7b68e0a7d287e7ec007579242acb1c39
