### ISSUE TITLE
2019 mclaren exhaust 

### ISSUE THREAD

**Issue by Bigheadsteve214** [fkk-cz/noire_vehicles#1414]
Can the 2019 mclaren 600lt be a little lauder almost sounds almost  like a Tesla fully modified.

**Comment by okxeon** [comment]
What of the other cars in game do you want the 600LT to sound like?

**Comment by Bigheadsteve214** [comment]
Either the svj or another lambo

**Comment by okxeon** [comment]
The svj uses a over used lambo sound. A close alternative is the 675LT as its a louder mclaren based sound. Edited here: https://github.com/fkk-cz/noire_vehicles/commit/7c5b53e16aea1966a8e4dbc52acc55481100f31c
