### ISSUE TITLE
2016 Cadillac CTS-V

### ISSUE THREAD

**Issue by SkylordM** [fkk-cz/noire_vehicles#1415]
Can the 2016 Cadillac CTS-V get the sound pack from the Pontiac G8 GXP, and maybe have the handling looked at?
Thank you!

**Comment by SkylordM** [comment]
As for the handling of the vehicle. I know that it is a bigger car, but even with the best brakes upgrade, it's still difficult to stop and corner with it. Then, for the stability on take-off and cornering to not spin out. Just where you can help, I guess,

**Comment by okxeon** [comment]
Edited the handling here: https://github.com/fkk-cz/noire_vehicles/commit/4c9d53fd48ed9a5f3a2c40a24935a17b53f9af51
and the audio here: https://github.com/fkk-cz/noire_vehicles/commit/d84d1af9c6ec9eebcdb6f1c10c977054b75c7fde

-this cadillac actually looks clean, wait for this to merge to apply in game
