### ISSUE TITLE
57 Eldorado Acceleration!

### ISSUE THREAD

**Issue by rustigibbons** [fkk-cz/noire_vehicles#1418]
I know this was just added and I hate to ask, but since the vehicle is 58k would it be possible to increase the acceleration portion of the vehicle? Fully tuned up it takes a minute to get to top speed of like 85? If its ok would it be possible to have it similar in power to the 62 Continental Sedan? If not its ok, still love the ride just wanted a little more speed for traveling purposes! Thanks !

**Comment by okxeon** [comment]
Tweaked here: https://github.com/fkk-cz/noire_vehicles/commit/f7ec7a2a4cd2182e4bb331930636554721b96a49. All I did was up the acceleration and that's all it really needed.

**Comment by rustigibbons** [comment]
ur the best ty !
