### ISSUE TITLE
Mazda Rx-7 Spirit in supporter tab

### ISSUE THREAD

**Issue by Shika586** [fkk-cz/noire_vehicles#142]
Yea i just spent 125k on this Mazda rx7 and the top speed on this is 110-115 mph. i have a 69 charger that i got for 55k and it goes 140-145mph. I would love for the mazda to get an increase in top speed and maybe a little acceleration increase also. i think the ideal top speed would and should be 145-150mph. Thank you

**Comment by fkk-cz** [comment]
https://github.com/fkk-cz/noire_vehicles/commit/017ce2c15b03f6d4abf73451083b9e89487afba5#diff-d42319c79302eb94f51a26e8d8d28fa9ff92c0f880a1f82b8446fc72cb4ad3eb
