### ISSUE TITLE
Lamborghini sc20 buff + audio change

### ISSUE THREAD

**Issue by apricates** [fkk-cz/noire_vehicles#1421]
As the title says I would like a speed and handling buff because it feels like a stock car from (Regular GTA) and the audio change to one of the other lambo audio hashes. Please and thank you in advance.

**Comment by okxeon** [comment]
Handling tweaked here https://github.com/fkk-cz/noire_vehicles/commit/9c549fb73265a972dcfb3a501f44511321871e47. Will now average a much faster top speed and handles a little nicer. Audio was tweaked here https://github.com/fkk-cz/noire_vehicles/commit/0c3cbaf9ff3217cf36d06dcd8f38abb59c78ff88 and changed to the SC18 audio.
