### ISSUE TITLE
Non Supporter Subaru 

### ISSUE THREAD

**Issue by cxerq** [fkk-cz/noire_vehicles#1422]
Would it be possible for this car to be tweaked so it could be useful in getaways, top speed is fine could even get lowered if the handling and breaking got a slight upgrade, the car should be able to drift a bit more, ideally without less traction while taking off

**Comment by okxeon** [comment]
Improved the handling here: https://github.com/fkk-cz/noire_vehicles/commit/a1270f9cbaafb277a6ea746f73d18afadaf4e777. Improved the turning radius / traction values so it should handle better. Also improved the acceleration as it seemed a little sluggish. As for drifting its hard to have a car good for drifting and to have good traction. It's kinda a one or the other.

**Comment by cxerq** [comment]
Okay thanks for the changes! I appreciate it!
