### ISSUE TITLE
The 2020 charger srt hellcat gold supporter car should be better

### ISSUE THREAD

**Issue by Danny123372** [fkk-cz/noire_vehicles#1424]
The car in real life doesn’t have bad grip at the start like that I just think it’s kinda dumb that it does that like that all I want to change for the car because let’s say I’m in a chase and try to drive off that shit does a whole burnout for 5 seconds before i start’s driving like it’s soo bad please fix that.

**Comment by okxeon** [comment]
I agree it has a little too much wheel spin on it. Tweaked here: https://github.com/fkk-cz/noire_vehicles/commit/07aa526597a755ffcf1b7c3b6eb000cdc0c312a5
