### ISSUE TITLE
2022 Kawasaki Ninja H2

### ISSUE THREAD

**Issue by Vibez2Tone** [fkk-cz/noire_vehicles#1425]
You buy this buy for $250,000 which is not cheap and it only tops out at 235? That is unfair for the people who put almost a full day of playing time just to buy that bike and it only goes to 235. That is unfair and unrealistic. The complaining from the cops should not effect that bikes speed because in real life bikes like that exist and cops cant do a thing about it but try. Can we please get this bike buffed again to at least 265?

**Comment by cxerq** [comment]
You actually gotta be joking right? Literally there is cars over 700k that barely get 200mph, and you are complaining over a Bike that goes 235mph for 250k Get the fuck outta here

**Comment by No-Yes1** [comment]
see above. the vehicle won't be tweaked.
