### ISSUE TITLE
the top speed of the bugatti chiron pur sport 

### ISSUE THREAD

**Issue by IIBurntLuisII** [fkk-cz/noire_vehicles#1427]
so the car cost 4.5m if i was to buy it what is the fastest u will make it go there would probably only be 1 in the city

**Comment by PeanutTheCop** [comment]
are you even close to that amount of money?

**Comment by IIBurntLuisII** [comment]
> are you even close to that amount of money?

nah lol it would take like 2 months of straight grinding

**Comment by okxeon** [comment]
The car has already been buffed to match the price previously. As of right now it has excellent handling and a decent top speed. Also, there is already one is the city already.
