### ISSUE TITLE
McLaren 720S N-Largo Top Speed

### ISSUE THREAD

**Issue by Cozy5** [fkk-cz/noire_vehicles#1428]
Hi, I recently bought the McLaren 720S N-Largo for around 380K and the top speed just doesn't make sense considering how it is in real life and the price. The top speed of the car is around 210 MPH or so, but in game it seems like I can only push it to go around 180-185 is there any way it can get a speed boost since it kind of doesn't make sense for it to go around 180-185 since it cost 370K and IRL it goes around 215 top speed. So I'm just asking if it can get a speed boost just for it to go a little faster.

**Comment by PeanutTheCop** [comment]
this is very good top speed for the price. there are many cars way over this price that go just as fast. they cant make things "realistic" because people will abuse the shit out of them

**Comment by Cozy5** [comment]
> this is very good top speed for the price. there are many cars way over this price that go just as fast. they cant make things "realistic" because people will abuse the shit out of them

ive seen cars for a lower price go faster than the one im talking about and im not asking for the car to go 215-220 because that is way too fast for this I mean like 200-210 because 180 is not as close as I thought when I test drove it.

**Comment by okxeon** [comment]
For 380k the car is ay okay. IRL is not always a good compassion for these cars as yes IRL it might do whatever speed, but the economy is also quite different. IRL people dont make 1k for picking up trash as a sanitation worker in 30 seconds, money is much easier to come across in here. When compared to many of the other high end super cars 380k for a car is not exactly even super expensive. I get that you would like for it to go faster, but for the price point it should not go faster.
