### ISSUE TITLE
2015 GMC Yukon Denali trunk space 

### ISSUE THREAD

**Issue by DarkHourEnt** [fkk-cz/noire_vehicles#1431]
Bought the truck, hefty price tag of 140k - kinda slow but not a issue .  Can you improve the trunk space from 750 to 1,000 At least ?

**Comment by No-Yes1** [comment]
Fixed in https://github.com/fkk-cz/noire_vehicles/commit/60f83a70b2392ae1aedc756047020941dfaa1634. Please wait for this to merge live.

**Comment by DarkHourEnt** [comment]
This has not been implemented in the city yet . How often are Merges ?

**Comment by No-Yes1** [comment]
I'll take a look later for you, it should have been done by now…

**Comment by No-Yes1** [comment]
![image](https://user-images.githubusercontent.com/79383480/194762652-fb49d458-7139-4960-b750-82bb404a103d.png)

on second thoughts, this is an SUV, so the vehicle trunk space is fine & won't be fixed.
