### ISSUE TITLE
Taco truck storage

### ISSUE THREAD

**Issue by Fallinglol** [fkk-cz/noire_vehicles#1433]
Is there a way to alter the storage capacity on the taco truck? currently it holds 750, but i was wondering if it could get buffed to 1000+.

**Comment by No-Yes1** [comment]
I need to have a play around with this. Leave this with me and I'll take a look.

**Comment by No-Yes1** [comment]
Did some research, and you can't actually change a vehicles.meta file for a vanilla GTAV vehicle (which is very strange..), the other work around it would be if you replace the vehicle & re-did the taco truck. This vehicle won't be tweaked/buffed to 1k storage.
