### ISSUE TITLE
BMW M3 E46 GTR

### ISSUE THREAD

**Issue by rawranevilpanda** [fkk-cz/noire_vehicles#1434]
![20220912180233_1](https://user-images.githubusercontent.com/81263370/189786928-9c045dce-1ea3-4eda-8ae8-519f75c375c4.jpg)
![20220912181749_1](https://user-images.githubusercontent.com/81263370/189786946-0b65c573-224a-47b6-9f7b-9f0ec3aa999d.jpg)
This bmw doesnt sound like it has a custom exhaust, the car should be way louder I made a post before about it but theres a lot of bmw's so I could see how there would be confusion about it, also I think it should be faster than what it is.

**Comment by okxeon** [comment]
What car would you like it to sound like instead?

**Comment by rawranevilpanda** [comment]
[https://www.youtube.com/watch?v=7SDWPBZj12I&t=29s](url) in the game the car had a supercharged v8 that had a high rev limit, not quite as big as the m5 so not as deep sounding, not sure if anything could match that currently in city. Ill take anything that's close even if it sounds like it has a turbo

**Comment by rawranevilpanda** [comment]
[https://www.gta5-mods.com/vehicles/bmw-e46-m3-s54-inline-6-engine-sound-oiv-add-on-fivem](url) I'll use this as an example for something that could work, If a supercharger whine could be added on top of that would be near perfect.

**Comment by okxeon** [comment]
Can you find another vehicle at pdm that you would like ti to sound like?

**Comment by rawranevilpanda** [comment]
![20220913110911_1](https://user-images.githubusercontent.com/81263370/189979521-b76dfa54-b596-4c22-b46a-449971c263b1.jpg)
Personally I think the closest thing right now would be the BMW M3 E92 GTS its not perfect but close enough imo, 
![20220913110010_1](https://user-images.githubusercontent.com/81263370/189979728-e78bcd9d-960e-4c3a-99bd-3daed1ef566a.jpg)
if for some reason you don't think that would be a good fit also the updated engine for the 2003 m3 would be a good replacement as well

**Comment by okxeon** [comment]
Swapped its audio hash here for you: https://github.com/fkk-cz/noire_vehicles/commit/6306d63935b84fbbe9770ec07d277c79c64ad4c5.
