### ISSUE TITLE
1994 Toyota Supra 

### ISSUE THREAD

**Issue by rawranevilpanda** [fkk-cz/noire_vehicles#1435]
![20220912184101_1](https://user-images.githubusercontent.com/81263370/189788772-46eb4408-42b2-4c53-aaa3-6671743ec8c9.jpg)
![20220912183023_1](https://user-images.githubusercontent.com/81263370/189788793-c5645c2b-1e42-40d7-b1b1-05ad4fa211df.jpg)
![20220912183904_1](https://user-images.githubusercontent.com/81263370/189788804-5e922ba7-511d-4604-bb0c-6ce6c992808b.jpg)
Right now the Car sounds like a 4 banger subaru impreza, I actually like the way the other Supra engines in the city sound so I wouldn't mind if it was changed to sound more like those, also for 350k I think the car should be way faster than what it is now

**Comment by okxeon** [comment]
Tweaked the audio here: https://github.com/fkk-cz/noire_vehicles/commit/0c2d8000f1f536cb16490b3f7fd67218ea0f737e
And the top speed here: https://github.com/fkk-cz/noire_vehicles/commit/84811cc5503dfbca05bc2bd99fa8de8479df9e7f
