### ISSUE TITLE
Mclaren 675LT handling

### ISSUE THREAD

**Issue by Cruzamp** [fkk-cz/noire_vehicles#1439]
It currently dives like a boat, whenever you turn it sways back and forth. When you are driving in a straight line and do left and right quick turns is take the whole car sway like crazy. And the brakes are terrible as well.  If you can drive it and test the swaying. It feels like it has no sway bars in the car.

**Comment by okxeon** [comment]
Idk how the mod creator of the vehicle thought this was a good handling for the car. Swapped it to the Mclaren 720s handling here: https://github.com/fkk-cz/noire_vehicles/commit/e99d71a37bfd4e12efa94b592fefb8d3a99705f8
