### ISSUE TITLE
BMW M4 Competition Armor and Dirt Collection

### ISSUE THREAD

**Issue by mfried456** [fkk-cz/noire_vehicles#1440]
The car breaks down way too easily and needs an armor buff. Also for some reason, it gets dirty super quickly even when just driving on paved roads.

**Comment by okxeon** [comment]
Tweaked the damage mults here: https://github.com/fkk-cz/noire_vehicles/commit/dcccb482119c6b78ea22f8772c6436e10726cfb8. As for the dirt there is no fix for that, its just the way the car is.
