### ISSUE TITLE
Audi R8 speed and braking

### ISSUE THREAD

**Issue by UnfoundShadow** [fkk-cz/noire_vehicles#1445]
The Audi R8 needs to be faster like look at the specs on this car from 2020 which is the date that the car is in the server it needs to be faster and have better breaking the breaks on this car can't stop it to save its life and the top speeds sucks which makes no sense since its 300k and has AWD V10 it should be a whole lot faster than 185 flat like that's ridiculous.  
Revised 5.2-liter V-10
Base model with 570 horsepower
V10 Performance with 620 horsepower
0 to 62 as quick as 3.1 seconds
Top speed of up to 205 mph
Standard all-wheel-drive system

**Comment by cxerq** [comment]
First its 395k, second you are the first person in months to complain about the R8 top speed or braking! I have personally owned an R8 for so long I dont remember when I didnt have one, the Car doesnt need any tweaking at all! Can say for sure if you think the breaks suck you just suck no offence! :)

**Comment by UnfoundShadow** [comment]
i mean it takes awhile to break but like even that its 395k i bought mine for 300k and nobody complains about it because nobody can afford it to drive it and even then when they do they sell it bc for the price it should be going atleast 200. And the brakes could be worse but should be better. I will admit when u hit something the car is a tank, and the acceleration is perfect.

**Comment by cxerq** [comment]
> i mean it takes awhile to brake but like even that its 395k i bought mine for 300k and nobody complains about it because nobody can afford it to drive it and even then when they do they sell it bc for the price it should be going atleast 200. And the brakes could be worse but should be better. I will admit when u hit something the car is a tank, and the acceleration is perfect.

Thats soo incorrect, People dont drive it cause they want more expensive cars, you tell me another car around 300-400k thats better than the R8 ill wait!

**Comment by UnfoundShadow** [comment]
Listen I just want a little bit for speed that's all at least 190 flat like an easy 190 flat when I tell people the top speed of this vehicle there surprised and always say it should be faster

**Comment by UnfoundShadow** [comment]
like a demon is 200k and goes 200 and its a dodge

**Comment by okxeon** [comment]
A demon also can only drive at that speed in a straight line, not really a fair comparison considering the R8 has decent handling. As for the top speed the good handling / accel makes up for the fractionally lower top end when compared to other cars in its price range and class.
