### ISSUE TITLE
Ferrari 458 Prior

### ISSUE THREAD

**Issue by Danny123372** [fkk-cz/noire_vehicles#1447]
Can we get a small speed buff to this car I’m just wondering like maybe ten miles faster or even 5 if that’s ok I think it deserves that if that’s ok and can you make it to where you can remove the livery please even if no speed buff but can you at least make it to where we can remove the livery please thank you and bye.

**Comment by okxeon** [comment]
The top speed was recently adjusted and is perfectly fine. As for the livery you can put on another one / remove it at the mod shop.
