### ISSUE TITLE
MMcLaren 720S N-Largo Acceleration

### ISSUE THREAD

**Issue by Cozy5** [fkk-cz/noire_vehicles#1448]
Hi, I recently bought the McLaren 720S N-Largo for around 380K and the acceleration just doesn't really go with the actual car. I know it isn't a drag car or anything but it takes a little too long to get to a about 110 or so, I was beat by a 458 Prior and a Lexus LFA. It seems like it just can't keep up with the other cars even though it is really expensive and I know it is easier to get money in real life but then again it makes sense for the car to go faster than either of those cars. If it could just have a little faster acceleration it would be nice.

**Comment by No-Yes1** [comment]
I've just got this going 160 in under a minute stock btw. The vehicle is fine and will not be tweaked / adjusted.
