### ISSUE TITLE
Harley Davidson Road King Cosmetic Issues

### ISSUE THREAD

**Issue by rustigibbons** [fkk-cz/noire_vehicles#1450]
When taken to the shop, most if not all of the customizing options that are listed do not work. The exhaust for example dont show other than default. The seats dont show other than default. Also the Saddlebag doesnt show. Was wondering if this could be fixed? Rusti would def be happy !

**Comment by okxeon** [comment]
After looking into it this looks like a mod creator issue and something we cant fix. Looks like there were mods intended for this but never got created.
