### ISSUE TITLE
Harley Davidson FLHXS, in garage as null

### ISSUE THREAD

**Issue by rustigibbons** [fkk-cz/noire_vehicles#1453]
just noticed this thread had a double comment on it, my bad. Any news of a possible fix on this issue ?

**Comment by rustigibbons** [comment]
Noticed on this bike that is is as null in the garage and the keys are null. Biggest issue to me and a few other owners though is the dash is see through and sometime changes colors. Hoping this could all be addressed!

**Comment by Competent1** [comment]
Thank you for submitting this issue. Upon further review of this vehicle, I do have some bad news. This vehicle has model issues and has a recall pending on it. Sorry for any inconvenience that this may cause.
