### ISSUE TITLE
[Exact name of vehicle, as displayed in game]: Dodge Hellphant

### ISSUE THREAD

**Issue by cxerq** [fkk-cz/noire_vehicles#1456]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

It cant do wheelies

### Expected Behavior

It should do Wheelies

### Anything else?

Please make it do Wheelies, It looks like it would! Pleassse

**Comment by fkk-cz** [comment]
This isn't a vehicle issue.
