### ISSUE TITLE
Mercedes Sprinter van 

### ISSUE THREAD

**Issue by DarkHourEnt** [fkk-cz/noire_vehicles#1457]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

Cannot respray the van a different color .

### Expected Behavior

Allow the van to be painted a different color . 

### Steps To Reproduce

Go to the respray location 

### Anything else?

No

**Comment by Scubaaaaa** [comment]
This issue was brought up in the past, unfortunately this issue cannot be fixed because the mod creator never actually gave the vehicle a mod kit.
