### ISSUE TITLE
Porsche 718 boxster s

### ISSUE THREAD

**Issue by Danny123372** [fkk-cz/noire_vehicles#1458]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

Can you make it too where the car closes the roof and can you please make it a little faster it is a porsche and It's only going 160 and plus i got a hellcat for the same price thats faster i mean nothing huge i just want it to reach like 175 or 180 it would be cool if you did that but its ok if you buff it a little less i just want a buff with the speed please.

### Expected Behavior

I thought this car would go a lot faster to be honest and for the roof to close but i new what the traction was going to be like and stuff like that.

### Steps To Reproduce

1. i just think a speed buff is what it needs so please.

### Anything else?

i just think it needs to be a little faster you know

**Comment by No-Yes1** [comment]
> Can you make it too where the car closes the roof

That's a model issue & can't be fixed.

> please make it a little faster

The car as you said goes 160mph, the price is around 95K, which is more than enough for that vehicle. Vehicle will NOT be tweaked.
