### ISSUE TITLE
Porsche Taycan 

### ISSUE THREAD

**Issue by PoppaHapps** [fkk-cz/noire_vehicles#1459]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

Handling is horrible on this vehicle 

### Expected Behavior

hoping that the handling can be fixed

### Anything else?

nothing else is wrong witht the car just needs a little bit better  handling

**Comment by No-Yes1** [comment]
Fixed the handling https://github.com/fkk-cz/noire_vehicles/commit/172c46338b1a47e0f1414f1136aebcab38276054. Please wait for this to merge live.
