### ISSUE TITLE
Mclaren p1 gtr [Exact name of vehicle, as displayed in game]: 

### ISSUE THREAD

**Issue by Ahy-jason-todd** [fkk-cz/noire_vehicles#1462]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

Is it possible to make the car 1 whole color or remove the livery it comes with cuz stock its has grey in the doors and roof of the car cant paint match it 

### Expected Behavior

Is it possible to make the car 1 whole color or remove the livery it comes with cuz stock its has grey in the doors and roof of the car cant paint match it 

### Steps To Reproduce

Is it possible to make the car 1 whole color or remove the livery it comes with cuz stock its has grey in the doors and roof of the car cant paint match it 

### Anything else?

Is it possible to make the car 1 whole color or remove the livery it comes with cuz stock its has grey in the doors and roof of the car cant paint match it

**Comment by Ahy-jason-todd** [comment]
also cant change any colors blue red green etc

**Comment by No-Yes1** [comment]
This is a model issue & can't be fixed.
