### ISSUE TITLE
rolls royce wraith 

### ISSUE THREAD

**Issue by PoppaHapps** [fkk-cz/noire_vehicles#1463]
### Is there an existing issue for this?

- [x] I have searched the existing issues

### Current Behavior

Handling is kinda of bad, you have to slow the car right down to make turns in this car

### Expected Behavior

The handling to be improved a little bit if this is possible 

### Anything else?

nothing else

**Comment by No-Yes1** [comment]
Fixed the handling / terrible corner turns https://github.com/fkk-cz/noire_vehicles/commit/06e6fc0a3da0f43f4b069464d7a254b0cfca9696. Please wait for this to merge live.
