### ISSUE TITLE
2012 Cadillac Escalade ESV

### ISSUE THREAD

**Issue by damnonion** [fkk-cz/noire_vehicles#1464]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

The only upgrade on the car is the turbo, the car needs upgrades and better handling, it’s one of my favorite vehicles in the city it just handles shit and gets broke down damn near instantly 

### Expected Behavior

Id hope you guys could add upgrade’s and fix the handling 

### Anything else?

i’ve used this car in multiple city’s and it’s had upgrades and better handling

**Comment by No-Yes1** [comment]
This is fixed in https://github.com/fkk-cz/noire_vehicles/commit/31dcc7b3b3d92297f96bd7d50bc1d02dd8eb2574. Please wait for this to merge live.
