### ISSUE TITLE
2017 Koenigsegg Agera RS

### ISSUE THREAD

**Issue by Trixwithoutmilk** [fkk-cz/noire_vehicles#1465]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

Currently this vehicle is too slow and cheap for its potential. This car is around $7,000,000 in real life and it doesn't live up to its full potential in this server.

### Expected Behavior

I would love to see this car get a price change and a speed buff so it can live up to its name, great hyper car my personal favorite. 

### Anything else?

Nope just really hope this car gets buffed. :)

**Comment by No-Yes1** [comment]
The price of the vehicle is 500K here, and can reach a top speed of 200mph. The car is perfectly fine for the price and will not be tweaked.
