### ISSUE TITLE
2016 Porsche 911 Turbo S 

### ISSUE THREAD

**Issue by Nicocpln** [fkk-cz/noire_vehicles#1468]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

Why is the Porsche so slow for 355k, it isn’t normal that a bmw m5 f90 is way quicker then the Porsche the Porsche needs a speed update it should at least go 185/190 mph for that price 

### Expected Behavior

Need a speed buff ain’t normal this car is slow for 355k

### Steps To Reproduce

.

### Anything else?

.

**Comment by Nicocpln** [comment]
And also the car gets dirty so quick, we cant see the brake lights

**Comment by Nicocpln** [comment]
![porsche dirty](https://user-images.githubusercontent.com/114328794/192132493-f536bb9c-c050-43d8-adbf-eb757aae07a1.png)

![Porsche break lights](https://user-images.githubusercontent.com/114328794/192132516-cc92ed02-c476-4837-b0c1-395bef0aadb5.png)

**Comment by Nicocpln** [comment]
Also the handling when accelerating isnt that good

**Comment by Nicocpln** [comment]
and IRL the sound of the car is more aggressive if by any chance u can make that change too

**Comment by No-Yes1** [comment]
> And also the car gets dirty so quick, we cant see the brake lights

This is a model issue as it's dependant on the dirtmapping and can't be fixed sadly. We have tried previously however it either just doesn't work or makes the car looks awful

**Comment by No-Yes1** [comment]
> Also the handling when accelerating isnt that good

Fixed the above in https://github.com/fkk-cz/noire_vehicles/commit/0e3b011f9616f7452e4337e6403d23b9ebe6fa26. The car should now go around 180 give or take.

**Comment by No-Yes1** [comment]
> and IRL the sound of the car is more aggressive if by any chance u can make that change too

Find a supported vehicle sound that is already in-game and sounds realistic.

**Comment by Nicocpln** [comment]
Thanks a lot for the changes above, I tried to find some sound packs but it’s for the Porsche gt3, can you still put it for the turbo s?

**Comment by Nicocpln** [comment]
https://www.gta5-mods.com/vehicles/porsche-911-gt3-rs-engine-sound-oiv-add-on-fivem

**Comment by Nicocpln** [comment]
There is this one but I feel like it’s similar too the one you have now 
https://youtu.be/jrmJds9l_Ds

**Comment by No-Yes1** [comment]
it needs to be a sound that is currently in the city as I said above.

**Comment by Nicocpln** [comment]
Where can I find the sounds that are in the city tho

**Comment by No-Yes1** [comment]
Test drive cars in the city is the only way unfortunately.

**Comment by Nicocpln** [comment]
Aight imma let you know can I choose sounds from supporter cars as well?

**Comment by No-Yes1** [comment]
Yes.

**Comment by Nicocpln** [comment]
Yo can you do the lamborghini urus?

**Comment by Nicocpln** [comment]
and btw are you sure the speed is buffed? mine is still stuck at 165-171

**Comment by Nicocpln** [comment]
Any updates ?

**Comment by No-Yes1** [comment]
Apologies in the delay. Updated the audio hash to the urus audio hash: https://github.com/fkk-cz/noire_vehicles/commit/32f56c66bf031c025bcb37182cc8e37d8d784e3f. The speed and previous adjustments should now be live. Please wait until the audio hash is pushed and live.

**Comment by Nicocpln** [comment]
Aight thanks a lot man <3

**Comment by Nicocpln** [comment]
Is the Urus audio hash live?
