### ISSUE TITLE
Lamborghini Huracan Evo

### ISSUE THREAD

**Issue by Scooterbug7** [fkk-cz/noire_vehicles#147]
The exhaust on the Huracan is way too loud compared to all the other cars, and it just gets really annoying after a while of driving it. I still like the Huracan having a louder exhaust but if it could just be a little quieter it would be a lot better to drive and own the vehicle

**Comment by Scooterbug7** [comment]
The vehicle also gets dirty way too fast when I'm just driving on the road

**Comment by fkk-cz** [comment]
> 
> 
> The vehicle also gets dirty way too fast when I'm just driving on the road

this can't be fixed, some cars have dirt textures that are more visible
