### ISSUE TITLE
[Exact name of vehicle, as displayed in game]: 1970 Corvette z71

### ISSUE THREAD

**Issue by rustigibbons** [fkk-cz/noire_vehicles#1470]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

Sound is odd for the vehicle, but more so the handling and breaking is quite bad.

### Expected Behavior

a different sound package mabye more comparable to and older vehicle, and a slight improvement to handling and breaking so its not as slidey.

### Anything else?

Nothing else just a couple basic tweaks that I think are fair.

**Comment by okxeon** [comment]
Tweaked the handling here: https://github.com/fkk-cz/noire_vehicles/commit/21783df02d0dc67c23afa334b895b251add33c82 & the audio here: https://github.com/fkk-cz/noire_vehicles/commit/9af04a8714e3b5488ac41eeb6fc8872aede017f1
