### ISSUE TITLE
[Exact name of vehicle, as displayed in game]: 1965 ford mustang rtr

### ISSUE THREAD

**Issue by rustigibbons** [fkk-cz/noire_vehicles#1471]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

No paint job options

### Expected Behavior

Hope i can change paint job and liveries.

### Anything else?

Nope

**Comment by Scubaaaaa** [comment]
Unfortunately this is a model issue, and there's nothing we can do about this issue. The mod creator made the vehicle this way when he created the car.
