### ISSUE TITLE
[Exact name of vehicle, as displayed in game]: 2021 BMW M4 Competition

### ISSUE THREAD

**Issue by kinkybearcat** [fkk-cz/noire_vehicles#1473]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

Acceleration from 2nd and 3rd gear is sluggish when trying to pick up speed above 110. Then after around 130mph car seems to really understeer as it picks up speed drastically. Picking up speed seems to take a little until a certain speed then it really picks up which seems a little weird. Lastly the car seems to get dirty pretty quickly, but I understand this is a texture issue.

### Expected Behavior

The car should accelerate pretty quickly on the lower gears. 1st gear all the way to 3rd should accelerate pretty quickly getting up to 110-130 and not feel so sluggish. The acceleration should be a bit more balanced rather than a sudden build up of speed in the higher gears as this causes the major understeer at high speeds, almost like an electric car. 

### Anything else?

Nope

**Comment by Competent1** [comment]
I own one of these and it is *perfectly* fine for it's current price. It does not need a buff to it's acceleration **at all**. Try to think logically next time before making a request like this.

**Comment by okxeon** [comment]
The car seems perfectly fine the way it is currently. It used to be better but it was abused.
