### ISSUE TITLE
2017 Lamborghini Huracan Spyder supporter car 

### ISSUE THREAD

**Issue by chico214** [fkk-cz/noire_vehicles#1477]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

The Lambo doesn't sound like an exotic sports car.
Plus the window wiper is glitched on the front window 

### Expected Behavior

can you make the car sound more like a sports car like similar to the Lamborghini Murcielago 
fix the windshield wiper 

### Anything else?

nothing else

**Comment by okxeon** [comment]
The wipers cant be tweaked as thats a model issue, but swapped the audio hash here: https://github.com/fkk-cz/noire_vehicles/commit/925e256f0a13b28de1661969066e67944ae9bcd0
