### ISSUE TITLE
[Exact name of vehicle, as displayed in game]: 2017 Dodge RAM 1500 TRX

### ISSUE THREAD

**Issue by kinkybearcat** [fkk-cz/noire_vehicles#1478]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

The top speed is quite low considering it has a 707 hp supercharged V8. Max speed is around 120mph with full upgrades. The recalled TRX went much faster at 160mph top speed and the Titan can reach 145mph. 

### Expected Behavior

The 1500 TRX should go at least 150mph maybe 160mph max to match the recalled TRX. I would expect it to be faster than the Titan as well.

### Anything else?

Nothing else

**Comment by okxeon** [comment]
Tweaked here: https://github.com/fkk-cz/noire_vehicles/commit/f57d73f701971eff223851f89121040fcf37e9d3
