### ISSUE TITLE
Bentley Mulliner Bacalar

### ISSUE THREAD

**Issue by DarkHourEnt** [fkk-cz/noire_vehicles#1483]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

Vehicle is slow , irl this twin turbo v12 Bentley reaches 200 mph . In the city it barely reaches 140 . 
Also the audio does not sound very powerful like a twin turbo.

### Expected Behavior

The price tag is the same compared to IRL (1.9m) Increase the speed to match irl .update audio to sound more powerful . 

### Anything else?

Car is 1 of 12 irl

**Comment by IIBurntLuisII** [comment]
W

**Comment by No-Yes1** [comment]
Fixed in https://github.com/fkk-cz/noire_vehicles/commit/1fd175febc135ac0fdc65cb50a550d87f9ec3a31. Please wait for this to merge live.
