### ISSUE TITLE
Ferrari Stradale Improvements. 

### ISSUE THREAD

**Issue by tythetanman** [fkk-cz/noire_vehicles#1485]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

Just minor things looking to have upgraded on the vehicle if possible:

A possible swap for another Ferrari sound to go on it because the sound that’s on it sounds like a normal GTA vehicle compared to a one. $4 million Ferrari.

also, the handling how it fish tails for a car at 1.4 million compared to cars in the $700,000 range and compared to the Lamborghini’s at 1 million plus that’s I believe within the same range of 1.1-1.5 million does not spin like that. Has better control.

### Expected Behavior

Car handling
I think could be buffed for the price and breaks. Breaks like a Tesla truck. 

Sound sounds like a vanilla gta car. If they could just have a Ferrari sound that is custom that’s already in the city one of the better ones preferably not one of the ones under 700,000.

### Steps To Reproduce

Just start the engine and try to drive straight or even a turn within the first 30 seconds or better yet in the first 15 seconds of driving you hear the engine and the issue. 

### Anything else?

Thank you.

**Comment by tythetanman** [comment]
Also the name of the car shows up as NULL everywhere.

**Comment by tythetanman** [comment]
It’s a retextured local car… with the sound and handling , fish tailing it does as well.

**Comment by Scubaaaaa** [comment]
Changed the audio has here https://github.com/fkk-cz/noire_vehicles/pull/1487/commits/9bfa06c554cc15ba9c6dc29982c798f7c0a69617
Will take a look at the handling in a bit

**Comment by tythetanman** [comment]
Seeing what you think on if the handling and breaking can get adjustments/upgrades.

**Comment by Scubaaaaa** [comment]
Changed the handling here https://github.com/fkk-cz/noire_vehicles/pull/1493/commits/2d57e5f529012b345718df2e5d054ba51084d2cd
Wait for next merge to go live

**Comment by tythetanman** [comment]
Thx Scuba and big boss

**Comment by tythetanman** [comment]
Breaking 
Turning 
Acceleration Need buffs after testing it more. Not 100% sure if you all agree.

**Comment by okxeon** [comment]
The handling on the car, specifically the acceleration, turning, & breaking is alright. If anything the suspension is a little off, but handling wise I believe the car is fine.

**Comment by tythetanman** [comment]
Fair. Thx.
