### ISSUE TITLE
2013 Audi RS7

### ISSUE THREAD

**Issue by mfried456** [fkk-cz/noire_vehicles#1488]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

Poor handling and breaking.

### Expected Behavior

The Audi RS7 is a track car and should have great handling and breaking. Any chance this could be improved?

### Anything else?

Thank you for your time.

**Comment by No-Yes1** [comment]
Fixed in https://github.com/fkk-cz/noire_vehicles/commit/a9296c665e363ea22e5becc7bea4f38b8ed46a83. Please wait for this to merge live.

**Comment by mfried456** [comment]
Any chance this could be tweaked a bit further? Seems like there wasn't a noticeable change in braking or traction.
