### ISSUE TITLE
Mercedes Benz E-55 AMG has no sound

### ISSUE THREAD

**Issue by Few-2** [fkk-cz/noire_vehicles#149]
Okay so I bought the e55 today and it doesn't have any vehicle noises with it, you cant hear the engine or tires or even the door shutting. Its such a sick car and looks dope so I really hope it can be fixed. Thank you so much.

**Comment by fkk-cz** [comment]
https://github.com/fkk-cz/noire_vehicles/commit/b28cbcefb0c7e4a05fb69b601dee30922bd3c48f#diff-d3a2256ac146ece6c3bd88af256feeb49a503a5751369cb4e1fa90d7b9dcf6f6

**Comment by Few-2** [comment]
Hey sorry I don't know what that means. Does that mean its not fixable, sorry to reopen this and bother you
