### ISSUE TITLE
Pontiac g8 gxp 

### ISSUE THREAD

**Issue by Bigheadsteve214** [fkk-cz/noire_vehicles#1491]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

Can you guys make this car a little faster it tops out 170 in real life it only does 123 fully modded 

### Expected Behavior

Should do 170

### Anything else?

It has a corvette engine

**Comment by No-Yes1** [comment]
For the price of the vehicle ($68K), the vehicle is fine and will not be tweaked.
