### ISSUE TITLE
2019 Ferrari 488 Pista Sound

### ISSUE THREAD

**Issue by RangerThrawn** [fkk-cz/noire_vehicles#1492]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

The engine sound is so loud that I find myself pulling over and stopping the engine just to conduct phone calls -   Any chance to lower the sound 15% ?     

### Expected Behavior

Just a more manageable sound experience would be great 

### Steps To Reproduce

1. Drive the car   

2. Attempt to speak on your cellphone during drive 

### Anything else?

Thanks for your time - you all are doing great work

**Comment by BreezyEZ** [comment]
While I can agree the audio of the car can be loud at sometimes, it’s one of my favorite features about the car and I’m sure others will say the same. To me it’s one of the most unique sounding cars in the city. Hopefully they are able to lower the audio hash and not change to the Prior’s sound.

**Comment by okxeon** [comment]
Refer to what was stated above, the sound will not be replaced.
