### ISSUE TITLE
2020 rolls-Royce culminan 

### ISSUE THREAD

**Issue by Bigheadsteve214** [fkk-cz/noire_vehicles#1496]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

It does not let you mod the truck it’s 350k it should give you options to mod it.

### Expected Behavior

For 350k it should let you mod it I can only paint it and put a turbo 

### Anything else?

Nothing else

**Comment by Bountyrogger** [comment]
The problem with this is its most likely a mod issue.

**Comment by Bigheadsteve214** [comment]
So is this gonna get resolved or should I sell it?

**Comment by okxeon** [comment]
If you are referring to the 2020 Rolls-Royce Cullinan then this has been fixed here: https://github.com/fkk-cz/noire_vehicles/commit/912135aa0c9c08a3a776d6991eb861e59106540b
