### ISSUE TITLE
Honda Civic Type-R [hatchback one]

### ISSUE THREAD

**Issue by recruit2212** [fkk-cz/noire_vehicles#1499]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

Vehicle hasn't got any body modifications to add like front and rear bumpers so on so fourth.
![image_2022-10-15_140143415](https://user-images.githubusercontent.com/87608707/195987796-32a8f249-fd00-4181-9484-2eada1740f62.png)
![image_2022-10-15_140200381](https://user-images.githubusercontent.com/87608707/195987809-fdf7a745-bbb8-4b0c-9384-0c59a641a066.png)

vehicle handles fine it just has no body modifications 

### Expected Behavior

To allow body kits/trims to be put on vehicle to enhance the visual look of it.

### Anything else?

N/A

**Comment by No-Yes1** [comment]
This isn't a vehicle issue. Most add-on vehicle don't come with any body modifications to it as it's all done by the model creator.
