### ISSUE TITLE
2013 Audi RS7

### ISSUE THREAD

**Issue by mfried456** [fkk-cz/noire_vehicles#1500]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

Even after the car was tweaked, there was no actual improvement in the car's traction or braking - still has poor traction and braking.

### Expected Behavior

Better traction and braking - it is meant to be a track car.

### Anything else?

Thank you for your help.

**Comment by Scubaaaaa** [comment]
Corrected a carcols error involving one of the upgrades. Once that is merged I'll take a look at the car.

**Comment by mfried456** [comment]
Welp...the car certainly feels like it got a big nerf from that change. Acceleration seems worse and braking/traction is just as bad as before. Just pointing it out

**Comment by styxh** [comment]
After driving the car it drives perfectly fine! Car doesn't need buffed at all!

**Comment by okxeon** [comment]
> After driving the car it drives perfectly fine! Car doesn't need buffed at all!

I agree, drives fairly decent in my opinion for only $149k
