### ISSUE TITLE
2017 LAMBORGHINI HURACAN SPYDER

### ISSUE THREAD

**Issue by T45DARK** [fkk-cz/noire_vehicles#1502]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

the vehicle is 418 grand and only hits 180 on a flat road i believe this car deserves a buff considering it is the same speed as the normal Huracan for 255k. id like to suggest to have this car go about the same speed as the 2019 Ferrari 488 pista which is about 40 grand cheaper than the huracan 

### Expected Behavior

i expect a solid speed of over 200-210 especially since it is a supporter and the price is a good amount msrp

### Steps To Reproduce

.

### Anything else?

.

**Comment by okxeon** [comment]
For 418k it should not be going 200+ mph... If the 488 pista goes that speed it needs to be looked at.
