### ISSUE TITLE
[Exact name of vehicle, as displayed in game]:  2020 BMW M8 COupe

### ISSUE THREAD

**Issue by No-Yes1** [fkk-cz/noire_vehicles#1503]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

Texture issues on the back of the vehicle: 

### Expected Behavior

N/A

### Steps To Reproduce

Check the back of the vehicle.

### Anything else?

![image](https://user-images.githubusercontent.com/79383480/196034464-819c102c-3e62-42bb-a702-616bfb560577.png)

**Comment by Ell34** [comment]
![Screenshot 2022-10-18 023201](https://user-images.githubusercontent.com/92474477/196353321-3eea660b-bbe8-40ad-b4e5-69d9a79a9847.png)

Adding on to this - this is what it looks like when its dirty.

**Comment by Scubaaaaa** [comment]
This vehicle is recalled
