### ISSUE TITLE
Lamborghini murcielago

### ISSUE THREAD

**Issue by Gmoney7** [fkk-cz/noire_vehicles#1504]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

Its very slow for its price, and before you come at me, yes i know its a non-supporter and all that, but it really has nothing that stands out apart from the sound, acceleration is meh, top speed is comparable to the 2008 gallardo which is almost 700k cheaper, handling is also nothing extra-ordinary. like for almost a mil you'd except just a lil higher top speed.

### Expected Behavior

I'd just be happy with a acceleration update, or increased top speed to like 200, because it barely hits 195 and stays at 192-193 most of the time

### Steps To Reproduce

1. start the car.
2. drive til you hit the top speed.

### Anything else?

I do understand if this isn't possible but its just something thats been on my mind for some time. (there was a previous issue stated in may about the top speed. idk how fast the adventador s goes, because i understand that you cant make the murcie faster than the adventador s because of the price difference.

**Comment by No-Yes1** [comment]
Adjusted Top Speed / Acceleration slightly in https://github.com/fkk-cz/noire_vehicles/commit/44428ffc8bc150faf44dda8a1ad17e57f5a68dfa. Please wait for this to merge live.
