### ISSUE TITLE
Lamborghini Aventador S

### ISSUE THREAD

**Issue by IIBurntLuisII** [fkk-cz/noire_vehicles#1505]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

is it possible to get it the same engine sound as the Murcielago SV

### Expected Behavior

.

### Steps To Reproduce

drive the car

### Anything else?

nothing else

**Comment by Scubaaaaa** [comment]
The problem with changing audio on popular cars like this is that once it's done people don't agree. Going to ask in here before I make the change if anyone has an issue with this?

**Comment by IIBurntLuisII** [comment]
best way to do it i hope they enjoy it its a nice engine sound

**Comment by No-Yes1** [comment]
No response from above. Changed audio hash here: https://github.com/fkk-cz/noire_vehicles/commit/75515574c88a9c5bef6d080b8ee1090cef38a5ee. Please wait for this to merge live.

**Comment by TheBottomFragger** [comment]
Noooo!! It sounds so disgusting 😭 I didn’t even see this until now 😭
Had this car for so long now, don’t know why this was changed when nobody requested it until now.

**Comment by IIBurntLuisII** [comment]
i really love the merci sound the old engine sound was mid

**Comment by IIBurntLuisII** [comment]
> Noooo!! It sounds so disgusting 😭 I didn’t even see this until now 😭 Had this car for so long now, don’t know why this was changed when nobody requested it until now.

it was originally posted 8 days ago no one spoke up i think it should stay

**Comment by PsychoticCore** [comment]
Aventador Audio > Murcielago Audio

**Comment by TheBottomFragger** [comment]
> > Noooo!! It sounds so disgusting 😭 I didn’t even see this until now 😭 Had this car for so long now, don’t know why this was changed when nobody requested it until now.
> 
> it was originally posted 8 days ago no one spoke up i think it should stay

I honestly have the chat for this muted, and got told by my friends yesterday, that’s how I found out. I hate the sound of it tbh lol

**Comment by IIBurntLuisII** [comment]
> > > Noooo!! It sounds so disgusting 😭 I didn’t even see this until now 😭 Had this car for so long now, don’t know why this was changed when nobody requested it until now.
> > 
> > 
> > it was originally posted 8 days ago no one spoke up i think it should stay
> 
> I honestly have the chat for this muted, and got told by my friends yesterday, that’s how I found out. I hate the sound of it tbh lol

ofc its all personal preference from all the people i asked its good

**Comment by Scubaaaaa** [comment]
Reverting this change back here as multiple people don't like it - https://github.com/fkk-cz/noire_vehicles/pull/1519/commits/67b3ef34df0a4947459fe30ec341b3ca4fda81e1
I'm going to agree with them aswell, that is not the sound for this vehicle
