### ISSUE TITLE
Mitsubishi Evo 9

### ISSUE THREAD

**Issue by cxerq** [fkk-cz/noire_vehicles#1506]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

The acceleration and handling are a little bad right now

### Expected Behavior

Could the acceleration and handling get a slight buff so the car could be used as a getway car! Currently the car is a little slidey and slow to get to top speed! 

### Anything else?

Thanks for taking the time to read!

**Comment by No-Yes1** [comment]
Just tested this -- this isn't that bad for the price point; the handling is pretty much on point. Won't be tweaked.
