### ISSUE TITLE
[Exact name of vehicle, as displayed in game]: Bugatti Divo

### ISSUE THREAD

**Issue by Winterssssssss** [fkk-cz/noire_vehicles#1509]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

The Bugatti Divo does not sound like the real Bugatti Divo in real life and i know this server prides itself on realism.

### Expected Behavior

Just sound like a default car 

### Anything else?

N/A

**Comment by No-Yes1** [comment]
> The Bugatti Divo does not sound like the real Bugatti Divo in real life and i know this server prides itself on realism.

Have you got an audio that sounds somewhat realistic that is already in-game?

**Comment by Winterssssssss** [comment]
It should sound like the Bugatti Veyron or the Bugatti super sport and they are already in-game

**Comment by jeanndabeann** [comment]
idk who u are but if it sounds super loud now, i actually hate you :)))
