### ISSUE TITLE
Mclaren P1 GTR Buff acceleration and top speed

### ISSUE THREAD

**Issue by JaegerPop** [fkk-cz/noire_vehicles#151]
McLaren P1 GTR Acceleration is not good takes forever to get to top for this type of car that is 550K and the top speed is only 150Mph which is really bad when a 40K car can hit the top speed faster and higher speed . Would love to have a big buff to acceleration and top speed

**Comment by ZacLuxton** [comment]
Already fixed a long time ago #345
