### ISSUE TITLE
2012 lotus exige s sports 

### ISSUE THREAD

**Issue by styxh** [fkk-cz/noire_vehicles#1510]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

Speed maxes at 130 

### Expected Behavior

Wondering if it can get upped too atleast 150 too somewhat make it average seeing that it is a super car 

### Anything else?

Thank you

**Comment by No-Yes1** [comment]
Fixed in https://github.com/fkk-cz/noire_vehicles/commit/64dc9f6ed13461b425b5335968de2bc5f0752d56. Please wait for this to merge live.
