### ISSUE TITLE
Mitsubishi Eclipse GSX (No year)

### ISSUE THREAD

**Issue by Ell34** [fkk-cz/noire_vehicles#1512]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

The vehicle has many cosmetic upgrades but when you hover over them, they dont work. screenshot showing the exact issue

### Expected Behavior

Upgrades should be showing/working

### Steps To Reproduce

take car to ls customs 

### Anything else?

![Screenshot 2022-10-23 030239](https://user-images.githubusercontent.com/92474477/197378915-e10a97ba-8262-4714-ae64-da413818e493.png)

**Comment by Scubaaaaa** [comment]
This is a model issue and nothing we can fix unfortunately. When making the vehicle the mod creator never gave it the extra's.
