### ISSUE TITLE
2017 Italdesign Zerouno 

### ISSUE THREAD

**Issue by MrThrawn** [fkk-cz/noire_vehicles#1515]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

This 850k cars flat top speed  is  160-165mph   -     in big city this is a 3.2 second 5.2 v10  Italian supercar 

### Expected Behavior

Please consider a higher top speed - perhaps 200-210mph?    , thank you

### Steps To Reproduce

Drive the 2017 italdesign Zerouno 

### Anything else?

I bought this car after testing it and falling in love with the control, and assumed I would get a reasonable boost once it had upgrades , sadly the top speed only went up 5mph… really heart breaking

**Comment by okxeon** [comment]
Significantly improved the cars handling & performance here: https://github.com/fkk-cz/noire_vehicles/commit/4c9a58a7c67d1162217d3b83cacfb4a482bd9035 as well as swapped the audio hash to something more fitting here: https://github.com/fkk-cz/noire_vehicles/commit/1d927f5bb05d6b8554708e7bde124c26edb6067e
