### ISSUE TITLE
McLaren P1 livery 

### ISSUE THREAD

**Issue by tythetanman** [fkk-cz/noire_vehicles#1516]
### Is there an existing issue for this?

- [x] I have searched the existing issues

### Current Behavior

The livery on the side of it that just says McLaren P1 is absolute ass. Even if it’s just different colors for the car instead of it being that one that would be great.  

Only thing I wondered a little bit about was the breaking. Not sure if that even needs tweaking other than that it’s a great car.

### Expected Behavior

Disgusting livery

### Steps To Reproduce

Just look at the bitch

### Anything else?

Thank you for looking at it and the potential changes

**Comment by Artificial-IQ** [comment]
We are currently not changing the livery on this vehicle. Have a nice day.
