### ISSUE TITLE
2017 Lamborghini Huracan Spyder

### ISSUE THREAD

**Issue by Fallinglol** [fkk-cz/noire_vehicles#1520]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior
The cars launch at the start needs to be buffed a bit IMO 
The car is really weak and can barely withstand any damage taken.

### Expected Behavior
Buff the cars launch
Buff the armor a tad bit to make it withstand damage.

### Steps To Reproduce

Test the launch on the vehicle after revving the engine.
test the damage that the vehicle can withstand by hitting something with the car.

### Anything else?

nope

**Comment by okxeon** [comment]
Tweaked the damage mults & the low speed traction loss here: https://github.com/fkk-cz/noire_vehicles/commit/4f5e3ba9207c389555b6aa9378f01f60d58bd91e
