### ISSUE TITLE
We need a good engine sound for the aventador s

### ISSUE THREAD

**Issue by IIBurntLuisII** [fkk-cz/noire_vehicles#1521]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

rn its ight i really liked the murci sound but ig people didnt what is another good engine sound

### Expected Behavior

not loud or good 

### Steps To Reproduce

drive it

### Anything else?

.

**Comment by Gmoney7** [comment]
I agree the sound right now Isnt really good, and did you mean the adventador s? Because the Murci shouldnt change sound.

**Comment by IIBurntLuisII** [comment]
nah the murci is perfect but i want something as good for the aventador s

**Comment by okxeon** [comment]
I have no issue with the current sound the vehicle has. Sounds what a lambo should sound like imo.
