### ISSUE TITLE
Bugatti Divo

### ISSUE THREAD

**Issue by Ell34** [fkk-cz/noire_vehicles#1523]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

I am simply asking for a slight accel buff and armour buff. 

### Expected Behavior

Idk 

### Steps To Reproduce

Drive the car up LS fwy
Get gapped :( 

### Anything else?

No

**Comment by okxeon** [comment]
The performance to the price is fine. The vehicle does not need to be tweaked.
