### ISSUE TITLE
Lamborghini Sesto Elemento

### ISSUE THREAD

**Issue by TylerGrimm2019** [fkk-cz/noire_vehicles#1524]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

When respraying the car the secondary color does not change the red details on the car.

### Expected Behavior

Please make it so the secondary color changes the what is right now permanent red details on the Lambo.

### Steps To Reproduce

1. Go to the mechanic/ car customization garage.
2.  Respray Paint
3. Secondary Color
4. Nothing changes on the car

### Anything else?

Please make the secondary color change the permanent red details on the car. It would make the car more customizable.

**Comment by Scubaaaaa** [comment]
This is a model issue and nothing that we can fix on our end. When the mos creater was making the car he didn't add the option to change the color.
