### ISSUE TITLE
Lambo aventador svj

### ISSUE THREAD

**Issue by medd54** [fkk-cz/noire_vehicles#1525]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

The Svj is a beautiful and amazing car. My only issue with it that its turning and turning radius does not match the price of the car. 
when driving its very heavy and turns really slow. On bends it tends to crash because of the slow turning. The brakes and speed  are amazing but does not match the turning and 90-180 degree handbrakes. 

### Expected Behavior

I expect this car to do everything it does besides the weak turning and drifting that it has. I would recommend trying it out its a wonderful car. So i expect it to turn as smooth and  fast as the car is. For almost 1.5 million this car should have amazing turning and drifting . At the end of the day its an Aventador SVJ. One of the coolest cars. So some decent turning and drifting would be much appreciated. The car definitely qualifies as one of the best cars. The only thing is the turning.

### Steps To Reproduce

No comment I’ll leave that to ur expertise 

### Anything else?

I very much appreciate all you ur guys contributions and admire all your hard work in the city. 
i hope my issue can be resolved as i worked extremely hard for this amazing car. I really want to enjoy the car in the city and not regret purchasing it because of a turning issue that it very much qualifies for in my perspective . For 1.5 mil this car should be the top in every category. 
i suggest trying it out and see what you guys can do.

Really appreciate the support. And hope you consider my comments.
Thanks!

**Comment by MrThrawn** [comment]
Totally agree with this , the turning in the early acceleration is especially punishing

**Comment by BreezyEZ** [comment]
After testing the car for 10-15 minutes I found it to perform perfectly fine. I see no reason for it to change.
