### ISSUE TITLE
2020 audi rS7 sportback  audio hash and handling fix

### ISSUE THREAD

**Issue by NikeXpert** [fkk-cz/noire_vehicles#1528]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

audio hash: https://www.gta5-mods.com/vehicles/audi-rs7-2020-sound
can you please take the handling from the 2011 audi rs5 and put it on the rs7 plz. 
also can it please get a trunk.

### Expected Behavior

2020 Audi rs7 handles like its one ice 24/7

### Steps To Reproduce

audio hash: https://www.gta5-mods.com/vehicles/audi-rs7-2020-sound
can you please take the handling from the 2011 audi rs5 and put it on the rs7 plz. 
also can it please get a trunk.

### Anything else?

audio hash: https://www.gta5-mods.com/vehicles/audi-rs7-2020-sound
can you please take the handling from the 2011 audi rs5 and put it on the rs7 plz. 
also can it please get a trunk.

**Comment by Scubaaaaa** [comment]
No new audio hash's will be put in the city. If you find a sound from another vehicle that's already in city feel free to request it to be changed as long as the sound is realistic for the car.

**Comment by Scubaaaaa** [comment]
Also like stated in a past github made on this vehicle, the vehicles handling will stay how it. The car handled fine for being priced at 149k.

**Comment by okxeon** [comment]
After test driving the car I found it handles fairly decent and does not need to be buffed and or replaced.
