### ISSUE TITLE
[Exact name of vehicle, as displayed in game]: Porsche gt3

### ISSUE THREAD

**Issue by rooftop11** [fkk-cz/noire_vehicles#1529]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

can you guys change the porsche gt3rs top speed? its a 380k car and it barely does 185. i feel like it should at least do 195-200. it goes 195 IRL. https://www.motorious.com/articles/news/watch-a-porsche-911-gt3-rs-approach-its-official-top-speed/        not only that but this car is 225k IRL. i feel it should at least be compensated with more speed for paying 160k more. https://www.porsche.com/usa/models/911/911-gt3-rs/911-gt3-rs/

### Expected Behavior

change top speed to 195-210

### Anything else?

 https://www.motorious.com/articles/news/watch-a-porsche-911-gt3-rs-approach-its-official-top-speed/   
https://www.porsche.com/usa/models/911/911-gt3-rs/911-gt3-rs/

**Comment by Scubaaaaa** [comment]
"On the runway, the hopped-up Porsche 991 hit 187 mph during the 2.3-mile sprint. Porsche claims the top speed for the car is a blistering 194 mph."
This is from the actual article you posted above.  a 2.3 mile sprint and the car didn't even break 190.

After testing the vehicle the speed is perfectly fine for the price, ontop of the that the car handles pretty well. Realistically the car would only hit those speeds on a track with perfect conditions, not driving down busy city roads with traffic and plenty of potholes. The vehicle will not be buffed.
