### ISSUE TITLE
RX-7 needs another buff

### ISSUE THREAD

**Issue by AlexBishop1112** [fkk-cz/noire_vehicles#153]
the car only hits 123 make it go like 165

**Comment by fkk-cz** [comment]
https://github.com/fkk-cz/noire_vehicles/commit/81e3b4b322252fef0fba9b964fd6f40cd589d45a#diff-d42319c79302eb94f51a26e8d8d28fa9ff92c0f880a1f82b8446fc72cb4ad3eb
