### ISSUE TITLE
Aston Martin Valkyrie… 😒

### ISSUE THREAD

**Issue by tythetanman** [fkk-cz/noire_vehicles#1530]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

Slower than the Fxx

turns like shit 

Acceleration slower than a few cars that’s not the $4 million Bugatti’s

breaks ok

### Expected Behavior

Fxx is better and over 500k less

### Anything else?

It’s slow

**Comment by tythetanman** [comment]
Just backed myself up a little bit before I’m told it goes too fast, it turns good and the handling is good… aqua even had to say it poorly performed compared to his Ferrari, and I was driving his Ferrari versus my Aston. Martin and I beat the living shit out of my Aston Martin. Which is more than a half 1 million cheaper the Ferrari.

**Comment by okxeon** [comment]
I just test drove the car and hit speeds of 270 mph. On top of that the vehicle has insane acceleration compared to other hyper cars in its price range. Yeah you are also right, the vehicle turns like shit - but for a car that does 270 and hits it quick as shit I am not wanting to further buff this. IMO if anything it needs a significant speed reduction, and so does the fxxk.

**Comment by tythetanman** [comment]
I could agree, but whenever it flips that much some type of handling upgrade is something that could be added, if possible, because it flips like a flounder. Not so much the speed speed is good but cars like the Ferrari should not be bidding it with a more than half 1 million difference but thank you for the consideration and looking at it.

**Comment by tythetanman** [comment]
It’s more of the flipping issue and handling for a car that’s 3 million the speed yes flat is good but it’s a car that has a reputation and has the record for the fastest car on the Nuremberg Ring. It’s more of the handling of why it’s flipping and flopping so much whenever it’s hitting these high speeds and turning should be closer to how fast the top Bugatti is, but not exactly the same.  Definitely think you if it gets increased or not. I definitely even love how it is now it’s a great track car.
