### ISSUE TITLE
Mitsubishi Lancer Evolution X

### ISSUE THREAD

**Issue by MerkTitty** [fkk-cz/noire_vehicles#1531]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

The car doesnt have any upgrades only a turbo. and the trunk is not working at the moment

### Expected Behavior

the car too be a bit faster and handle a little better at cornering and braking. and the trunk too work 

### Steps To Reproduce

add the ability too upgrade and the ability too use the trunk on the car

### Anything else?

nope

**Comment by okxeon** [comment]
Fixed the error where you could not upgrade the car here: https://github.com/fkk-cz/noire_vehicles/commit/facff5869ed99ab8adf3cfdad4af1e90765adbea
