### ISSUE TITLE
 1995 Ford Mustang Muscle 

### ISSUE THREAD

**Issue by recruit2212** [fkk-cz/noire_vehicles#1533]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

Just too slow for the price  166k for like 142 mph flat is harsh compared to the cheaper 2015 mustang which is able to reach higher speeds. a simple speed upgrade would be needed.

### Expected Behavior

Since vehicle is modified from pdm in the first place it should be topping out around 180mph when fully upgraded 

### Steps To Reproduce

1.Make top end speed higher.
2.slight acceleration buff but only slight.

### Anything else?

n/a

**Comment by ImDead48** [comment]
Your wanting a 1995 mustang to go 180 and wanting a 2015 mustang to just stay at 130-150? That don't make much since. You have to stay realistic

**Comment by recruit2212** [comment]
Ok fair enough but maybe 165/170mph maxed out would make it a bit more worth it since its much more money than the 2015 mustang and its kind of bland only having sub 50k challengers/mustangs  being faster than most 80/90grand sports cars. Not saying the 1995 mustang needs to be insane speeds just a slight speed buff would make it more worth the purchase. as its a bit disappointing when finding out its topping out at 142or so mph flat out fully upgraded

**Comment by okxeon** [comment]
For the price the vehicles top speed does not need to be adjusted.
