### ISSUE TITLE
2020 Mclaren GT

### ISSUE THREAD

**Issue by T45DARK** [fkk-cz/noire_vehicles#1534]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

this car is underwhelming in the performance end compared to other cars in the 200k price range, i feel like this car could do better
at a very unsteady 160 mph this car is the laughing stock of the mclarens in the city

### Expected Behavior

a nice speed buff up to at least 190 mph

### Steps To Reproduce

..

### Anything else?

i had a similar car ( supporter Camaro zl1) buffed for the same reason and it was the exact same speed and price of this car.

**Comment by IIBurntLuisII** [comment]
i agree with this the car is uber mid it def needs a buff

**Comment by styxh** [comment]
I mean you're paying for the name not paying for the speed or performance tbh. Not every expensive car goes fast.

**Comment by IIBurntLuisII** [comment]
but 213k for 160mph pretty shit

**Comment by IIBurntLuisII** [comment]
or 180 instead of 190 it jsut needs more bc the senna i could get 195 ok and that car is almost a mil the GT def needs a lil help

**Comment by styxh** [comment]
Yea but you're comparing an almost million dollar car with a less then 300k car it's not even the same

**Comment by IIBurntLuisII** [comment]
i understand that but u also gotta look at it, it could be better

**Comment by IIBurntLuisII** [comment]
im not saying make it the fastest car for 200k but it can be better

**Comment by BreezyEZ** [comment]
For the price of the vehicle the speed is perfectly fine. I was able to hold and maintain 170-180MPH on a flat. On top of that that handling is pretty decent for a car that is only 200k.
