### ISSUE TITLE
2022 Grand Cherokee Trackhawk

### ISSUE THREAD

**Issue by MrSosa01** [fkk-cz/noire_vehicles#1535]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

It’s has un-drivable handling and horrible brakes it slips off too much

### Expected Behavior

Trackhawks in irl have 4 piston brembos brakes and it handles really good for a suv

### Anything else?

Bad handle

**Comment by Ell34** [comment]
I do agree, the handling is absolutely horrible. But it was changed around a year ago because people were abusing it because it used to drive really nice. Hopefully they will consider just buffing the handling slightly.

**Comment by MrSosa01** [comment]
![image](https://user-images.githubusercontent.com/104510936/201276979-7130a181-88cb-4f2b-9e27-0af8160a0a01.jpg)
Cause by garbage handling

**Comment by okxeon** [comment]
Modified the vehicles handling here: https://github.com/fkk-cz/noire_vehicles/commit/2964a7dce3279ef5e60d35aeaf0ca702e7615c2c. Wait for this to merge to take effect in game.
