### ISSUE TITLE
2020 Ferrari SF90 Stradale

### ISSUE THREAD

**Issue by Chitowndevil21** [fkk-cz/noire_vehicles#1536]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

This car has no performance upgrades except for turbo. Was wondering if performance upgrades can be added. Side note no wheel options, don't know if anything can be done about this either but just throwing it in.

### Expected Behavior

Just looking for some more customization on this vehicle. 

### Steps To Reproduce

Just take it to mod shop.  No performance options appear  as well as no wheel options. Can't even change the license plate. 

### Anything else?

No

**Comment by Scubaaaaa** [comment]
Swapped the mod kit here - https://github.com/fkk-cz/noire_vehicles/pull/1537/commits/cbe16574d623af2eee9516a35900c742e048661d
Wait until the changes are merged over
