### ISSUE TITLE
2013 Volkswagen Beetle

### ISSUE THREAD

**Issue by SirLisps** [fkk-cz/noire_vehicles#1538]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

Car flips every time when turning

### Expected Behavior

To not flip at the slightest turn

### Anything else?

At any speed the car will start tipping when turning, and can very easily do a small wheelie.

**Comment by Scubaaaaa** [comment]
Handling swapped here - https://github.com/fkk-cz/noire_vehicles/pull/1543/commits/3c6b93db733777a1871beb0570539275a2156694
Wait for the merge to go live
