### ISSUE TITLE
2008 Alfa Romeo 8C Sports 

### ISSUE THREAD

**Issue by recruit2212** [fkk-cz/noire_vehicles#1539]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

sounds like a default gta car 
would be nice for a v8 sound as they are a really nice sounding v8's
https://www.gta5-mods.com/vehicles/bmw-m3-gtr-p60b40-v8-sound-mod-sp-fivem-add-on
or 
https://www.gta5-mods.com/vehicles/ford-f-150-5-0-coyote-v8-engine-sound-oiv-add-on-fivem-sound 
these two are the closest I've can find to the irl sound id preferer the bottom link but ill take what i can get. 

### Expected Behavior

make it sound as good as it looks 

### Steps To Reproduce

n/a

### Anything else?

n/a

**Comment by Competent1** [comment]
Thank you for making this issue and being patient regarding the 2008 Alfa Romeo 8C. You have probably already noticed but the audio hash for this vehicle was changed back on 4/3/23. Here is the commit for it https://github.com/fkk-cz/noire_vehicles/commit/94409fd1f32015cba14e538d6fbbff2bdc90040d. I test drove the car and it sounds great. Again, thanks for being patient and enjoy the vehicle!
