### ISSUE TITLE
DODGE RAM TRX

### ISSUE THREAD

**Issue by PeanutTheCop** [fkk-cz/noire_vehicles#1540]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

It said it was recalled after getting back on from a couple moths ago. When i spawn it in, nothing happens and I have to get it from insurance only for it to do nothing.

### Expected Behavior

Spawn the car so I can take it to PDM to sell

### Steps To Reproduce

Spawn TRX

### Anything else?

no

**Comment by okxeon** [comment]
The vehicles stream files have already been removed so it can not be added back to pdm. Its unfortunate, but the recalls were a time sensitive.
