### ISSUE TITLE
McLaren 765LT

### ISSUE THREAD

**Issue by PsychoticCore** [fkk-cz/noire_vehicles#1541]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

Engine & Transmission unable to be upgraded at LSC

### Expected Behavior

Be able to upgrade the Engine & Transmission when upgrading the car. 
If not possible, buffing the car for slight better acceleration and top speed? car is nearly 400k and caps out at about 170-175 mph give or take.

### Steps To Reproduce

1. Bring the car to LSC
2. Try to upgrade the Engine and Transmission

### Anything else?

No

**Comment by Scubaaaaa** [comment]
Xeon attempted to swap this modkit to it's own # a while ago and it still didn't correct the issue. This is a model issue and not anything we can fix

**Comment by PsychoticCore** [comment]
> Xeon attempted to swap this modkit to it's own # a while ago and it still didn't correct the issue. This is a model issue and not anything we can fix

Any chance this car could be buffed for slight better acceleration and or top speed since that isn't fixable? As Engine and Transmission would bring both of those up. Not asking for it to go like 230 mph, just a slight buff. 
Currently caps out at 175 ish and takes a while to get there
