### ISSUE TITLE
2013 Ford Explorer (New AMR Vehicle) 

### ISSUE THREAD

**Issue by Bountyrogger** [fkk-cz/noire_vehicles#1542]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

The Handling and such is ok I guess but was wondering if we could transfer the Handling/Braking/speed from the old 2016 AMR explorer to this new 2013 Explorer by chance?

### Expected Behavior

Just looking to see if we can transfer the Handling/braking/speed from the old 2016 AMR Explorer  to the new 2013 one is all.

### Anything else?

Thank you for the help as always.

**Comment by okxeon** [comment]
Tweaked the vehicle here: https://github.com/fkk-cz/noire_vehicles/commit/361fd213c50bf3fc84a7c6aef33dcaf1a664f756. I personally never liked the handling of the old amr fleet, so I just improved this ones values to make it perform nicer. Should fix all performance issues.
