### ISSUE TITLE
McLaren 765LT

### ISSUE THREAD

**Issue by PsychoticCore** [fkk-cz/noire_vehicles#1544]
### Is there an existing issue for this?

- [x] I have searched the existing issues

### Current Behavior

Currently the vehicle cannot have its Engine and Transmission upgraded as mentioned in the last 765LT GitHub thingy, which I understand cannot be fixed.
So it is slower than it **could** be if it were to be upgraded.

### Expected Behavior

A **slight** Acceleration and or Top Speed buff to make it even out as if it was able to be upgraded if that makes sense. 

Maybe even it out a tad more and make it more even to other McLaren's that are even cheaper and are the lower Horsepower models.
I'm not asking for it to go 230mph but just a slight buff from its cap that is basically 170-175mph currently and how long it takes to get it up to that speed.

### Steps To Reproduce

1. Take the car out on the streets
2. test the Acceleration & Top speed

### Anything else?

No

**Comment by BreezyEZ** [comment]
Fixed. Vehicle should go around 175-180MPH now as well as buffed the launch.
https://github.com/fkk-cz/noire_vehicles/commit/10c9b8df8f3a564081681712bd27ea02400698a4
