### ISSUE TITLE
2020 Chevrolet Blazer (No Mods)

### ISSUE THREAD

**Issue by Chitowndevil21** [fkk-cz/noire_vehicles#1545]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

This vehicle has no performance upgrades, can't change the wheels or even add tint.  Was wondering if this can be fixed on this vehicle.

### Expected Behavior

Just needs mods

### Steps To Reproduce

Take to a mod shop & feel disappointed in your purchase.

### Anything else?

![20221119094211_1](https://user-images.githubusercontent.com/93257343/202859713-31c9723a-0211-4a7d-b0ff-88d5c4085457.jpg)
![20221119094217_1](https://user-images.githubusercontent.com/93257343/202859716-4d2c4da8-c1ee-4274-8ca4-a8409d5fae12.jpg)
![20221119094221_1](https://user-images.githubusercontent.com/93257343/202859721-8e3c765d-afcd-4490-a8e1-588d0594d3e8.jpg)
![20221119094226_1](https://user-images.githubusercontent.com/93257343/202859729-1f46d146-51a7-4b73-befe-adf22ab6f924.jpg)
![20221119094230_1](https://user-images.githubusercontent.com/93257343/202859731-d936d1fe-e6b3-4fdc-bf63-b2d750131e1e.jpg)

![20221119094309_1](https://user-images.githubusercontent.com/93257343/202859734-8d2feaf0-e306-4ad5-9e52-760a9af13573.jpg)

**Comment by Scubaaaaa** [comment]
The vehicle itself has no actual carcols or carvariations meta files. So there's no working mod kit for the vehicle itself. This is something that the mod creator did that we cannot change.
