### ISSUE TITLE
2016 Honda NSX

### ISSUE THREAD

**Issue by FukBerk** [fkk-cz/noire_vehicles#1546]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

An update added a livery to the car that you cant take off, before you could make the car one solid color but with this new livery, you cant change the color of it at all (besides secondary - interior), could we please have the livery taken off the car

### Expected Behavior

Be able to take the livery off of the car and make the car's color customizable again

### Steps To Reproduce

Pull car out of garage
Take of Mod shop
Try to remove livery/change color of car

### Anything else?

Nope, thank you.

**Comment by Competent1** [comment]
I am able to change all of the colors (Primary included) on the 2016 Honda NSX. Appears this issue was resolved.
