### ISSUE TITLE
2016 Porsche 911 Turbo S

### ISSUE THREAD

**Issue by Casizu** [fkk-cz/noire_vehicles#1548]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

The problem with this car isn't the car itself, but it's durability to gunshots. Multiple times has my car been shot at and in 4-6 gunshots the car breaks down instantaneously without smoking. 

### Expected Behavior

Be able to keep driving after getting shot at multiple times like any other car would.

### Steps To Reproduce

1. Drive past someone shooting the car at average speeds 
2. See if the car breaks down or starts smoking

### Anything else?

Nothing else. I just notice the car breaks down ALOT faster to gunshots than any other car

**Comment by BreezyEZ** [comment]
After checking out the values in game, it is on par with other vehicles. This doesn't need to be changed.
