### ISSUE TITLE
2002 cobra 

### ISSUE THREAD

**Issue by TGK7** [fkk-cz/noire_vehicles#155]
The cars acceleration and speed are perfect even tho its a drag car i think the handling could be buffed a tiny bit also for some reason the cars hollow like the only thing solid is the frame i can walk inside the car 
![Desktop Screenshot 2021 04 15 - 22 47 38 74](https://user-images.githubusercontent.com/82477538/114964395-a8abf480-9e3c-11eb-963b-cb0a264fde22.png)

**Comment by DankGrandma** [comment]
fkk heard how fast this goes. don't nerf speed plz. it doesn't turn. fine as a drag car.

**Comment by ZacLuxton** [comment]
Just tested this out, for a drag car the handling is perfect fine, its not meant to be perfect around every corner, Also the issue with the frame is probably an issue with the ydd files, something that we can't fix.
