### ISSUE TITLE
Yamaha Banshee

### ISSUE THREAD

**Issue by xxWazzabi** [fkk-cz/noire_vehicles#1550]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

Doesnt spawn in. just seems to fall straight through the map and then shortly prompts me with a vehicle error code. i've spent over 6k just recovering it and it just seems to fall through the map every time i try to retrieve it.

### Expected Behavior

to just simply spawn in or be removed completely with a refund for my purchse

### Steps To Reproduce

1. Purchase to see if it happens to yourself aswell

### Anything else?

just want either for it to be fixed or my money back i spent on it

**Comment by okxeon** [comment]
I am not having any issues with the vehicle spawning in, might be a client sided issue. As for the handling I replaced it with the vanilla `blazer` 4 wheeler.
