### ISSUE TITLE
2021 Bugatti Super Sport 300

### ISSUE THREAD

**Issue by LPLips7** [fkk-cz/noire_vehicles#1551]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behaviour

Car cost 3.5 million and has a slow acceleration and slow top speed. Goes the slower than the Aston Martin Valkyrie which is 3 Million dollars. Caps out at 185 Non Upgraded, and upgraded would go only 215 flat... Slower acceleration than multiple other supercars that are half the Price. Yet the handling is amazing on it so at least that's good..

### Expected Behaviour

I would like if this Bugatti went a little bit fast and had a better acceleration, As I would like to purchase it. 
Unfortunately I don't have any solution to this, but I Believe you can change the speed within the files. It Should be going the same speed as the Valkyrie. The Aston Martin Valkyrie goes 245 flat upgraded, 215 flat no upgrades, and It's 500k Cheaper than this Bugatti. This Bugatti Super Sport 300 goes the same speed as a 450k Lamborghini Sesto Elemento...

### Steps To Reproduce

https://forums.gta5-mods.com/topic/4042/how-do-i-change-the-top-speed

This is the only forum I found Somewhat showing what to do

### Anything else?

https://forums.gta5-mods.com/topic/4042/how-do-i-change-the-top-speed

**Comment by okxeon** [comment]
Tweaked the handling all around here: https://github.com/fkk-cz/noire_vehicles/commit/c4596c378ef06e650e4ead4ee812fe310a0a7781. The valkyrie will be significantly nerfed as we will no longer be tweaking cars to go 270mph.
