### ISSUE TITLE
2020 Ferrari F8 Tributo

### ISSUE THREAD

**Issue by LUISTHEBARBERTTV** [fkk-cz/noire_vehicles#1553]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

The sound is horrendous, complete stock ped car sound. 
Its just not even worth the 1.250 million for it to sound the way it is.

### Expected Behavior

I would like to change the sound from the F8 Tributo to a sound like the other Ferraris maybe like the supporter one.

Any sound literally, if you'd like me to request something specific i can

### Anything else?

Thats all, just if anything replace the stock sound for the sound of the supporter Ferrari F8

**Comment by Scubaaaaa** [comment]
Swapped the audio hash here - https://github.com/fkk-cz/noire_vehicles/pull/1571/commits/65550ea43eca9bae0f486df96456c36659f70db5
Wait for the merge to go live

**Comment by damnonion** [comment]
This car sounded fine i've had it for months and loved the sounds, it's now so loud yo where i can't hear my self think or people talk in my car, the sound is nice but it's way to loud, can y'all please lower the sounds
