### ISSUE TITLE
[Exact name of vehicle, as displayed in game]: 2020 Audi Rs7

### ISSUE THREAD

**Issue by GhostJose** [fkk-cz/noire_vehicles#1555]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

only goes 170 and accelerates painfully slow for being such a fast and expensive car in real life. also has no storage even though it has a trunk and isnt a supercar. also has awful handling. also arent able to use first person as you can only see the roof. either recall this and refund all the people who have it as everyone ive talked to also complained about these problems!

### Expected Behavior

Higher speed 
Higher acceleration
some trunk space even 250 storage
better handling
also cant go in first person

### Anything else?

no

**Comment by Scubaaaaa** [comment]
Like stated in a past github made on this vehicle, the vehicles handling will stay how it. The car handled fine for being priced at 149k.
