### ISSUE TITLE
Boxville Vans, (GoPostal Job Vehicle): Acceleration Boost, Top Speed Increase

### ISSUE THREAD

**Issue by Bountyrogger** [fkk-cz/noire_vehicles#1556]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

They honestly are probably the slowest thing I have driven in the city, and I understand that its meant to be full of packages but still... Its so slow i see people using small trailers to transport them for being so slow.

### Expected Behavior

Be a bit faster/have better acceleration 

### Steps To Reproduce

N/A

### Anything else?

NGL its kinda dumb because I'm watching some people using the small trailer to transport them which shouldn't impact this job like that.

**Comment by fkk-cz** [comment]
https://github.com/fkk-cz/noire_vehicles/commit/76303d79bbc5a92aee961be960a9a0659ba6c643 switches the vehicle class to Service, which should help with the fuel economy issues.

**Comment by fkk-cz** [comment]
The `boxville2` van is intended to only go 50-60 MPH, to avoid issues seen with `trash` trucks that would drive around the city at 80 MPH and plow into everything. The upgraded work vehicle will handle much better.

**Comment by okxeon** [comment]
Created a modified handling of the boxville here: https://github.com/fkk-cz/noire_vehicles/commit/6b2c699fca259780e15e6c7c4892956bfd891916. Nearly doubled the acceleration and to compensate reduced the top speed of the vehicle. After driving it around the city/county for like 20 mins it felt more fair.
