### ISSUE TITLE
[Exact name of vehicle, as displayed in game]: 

### ISSUE THREAD

**Issue by yon1129** [fkk-cz/noire_vehicles#1557]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

2019 porsche gt2rs is 400k gets beat by 76k supra can barley do 185 

### Expected Behavior

a little quicker and better top speed

### Steps To Reproduce

1 in airport toyota supra beats 2019 porsche gt2rs

### Anything else?

was racing supra beats me when my car is 4x the amount of his compared to other cars in price range way slower then others

**Comment by Scubaaaaa** [comment]
For the price of the vehicle the speed and handling are both fine. I tweaked the supra to make it more fair for the price compared to the gt2rs - https://github.com/fkk-cz/noire_vehicles/pull/1571/commits/dbce96f8b8985a246145a005965f0f42e5cbb735
