### ISSUE TITLE
2020 Audi R8 speed/handing and sound replacement 

### ISSUE THREAD

**Issue by somedudenamedrush** [fkk-cz/noire_vehicles#1559]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

Currently when the car hits its last gear it tops out around 163 unless goin downhill cars for a 400k car (cars cheaper goes faster than this) id be happy with 185 -190. Handling when at slower speed it slides a bit like it wants to fishtail if that could be fixed that would be nice

also for the sound replacement it sounds nothing like a v10 this would match the car perfectly https://www.gta5-mods.com/vehicles/flat-plane-italian-v10-addon-sound

### Expected Behavior

better speed and handing 

new sound

### Anything else?

would love to see the car updated

**Comment by styxh** [comment]
that sound is so vanilla tho isn't there something better?

**Comment by BreezyEZ** [comment]
This car is perfectly fine for it's price. Was able to maintain 175-185 MPH going up the freeway, as well drove it around Sandy and it didn't fishtail on my once? It has really solid handling!

**Comment by somedudenamedrush** [comment]
> 

honestly anything is better than the vanilla sound lmao 

thoughts on this https://www.gta5-mods.com/vehicles/twin-turbo-audi-lamborghini-5-2l-v10-sound-mod-sp-add-on-fivem

**Comment by styxh** [comment]
now this one sounds nice the other sound you sent was still so vanilla
> 
> 
> 
> honestly anything is better than the vanilla sound lmao 
> 
> 
> 
> thoughts on this https://www.gta5-mods.com/vehicles/twin-turbo-audi-lamborghini-5-2l-v10-sound-mod-sp-add-on-fivem

**Comment by somedudenamedrush** [comment]
bet if its fine with you and can be done by staff im good to agree on this one

**Comment by Artificial-IQ** [comment]
At this time no new audio is being added. Have a nice day.
