### ISSUE TITLE
Bentley supersport gt// Acceleration and Top speed buff

### ISSUE THREAD

**Issue by Fitzald** [fkk-cz/noire_vehicles#156]
The top speed is only 170 which scales in comparison to its real life model hitting top speeds of 209mph

The acceleration is very poor struggling to even reach its already fairly poor top speed unless on the highway. 
A buff to these would make much more worth it as the price is a hefty 485k

**Comment by ZacLuxton** [comment]
IRL, you wouldnt speed the vehicle up in the city streets, you would wait until you're on an open road i.e an highway, we can make the vehicle go a little faster, so it goes around 190mph.

**Comment by ZacLuxton** [comment]
https://github.com/fkk-cz/noire_vehicles/commit/748459f4a84a97c037a0adb98ea54152d1e11566

This will probably fix the issue, will see tomorrow
