### ISSUE TITLE
Honda Civic SIR EG6

### ISSUE THREAD

**Issue by PsychoticCore** [fkk-cz/noire_vehicles#1560]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

Vehicle has no Performance upgrades, only one it has is the Turbo

### Expected Behavior

To be able to upgrade its performance upgrades

### Steps To Reproduce

1. Get the car
2. Bring it into LSC
3. click on "upgrades"
4. cycle through the upgrades in there and see there's nothing able to be upgraded

### Anything else?

No

**Comment by okxeon** [comment]
fixed here: https://github.com/fkk-cz/noire_vehicles/commit/df01478df8b3fd543fdacfeb3f063a6d87dca56f. Once merger the vehicle should be able to upgrade.
