### ISSUE TITLE
[Exact name of vehicle, as displayed in game]: 2010 Lexus LFA

### ISSUE THREAD

**Issue by aukurust** [fkk-cz/noire_vehicles#1564]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

Currently the Lexus LFA goes around 180 MPH and is worth $375,000 the pricing is realistic the sound is realistic but the speed lacks a little bit. The speed isn't bad its just like 20 MPH below what it goes in real life and having the speed tweaked a little bit quicker would be nice.

### Expected Behavior

Hopefully the car can get a little boost in speed doesn't have to be huge but it would be nice to see as its basically a racecar and gets beat by cars cheaper then it like the supra for example. It would be a good addition also since the LFA goes 202 in real life so the tune wouldn't even be that big.

### Steps To Reproduce

Just give it a little tune up

### Anything else?

,

**Comment by Scubaaaaa** [comment]
After testing the vehicle is fine for it's price. When talking about a vehicle's top speed IRL you have to remember, that top speed is typically calculated on a track with perfect conditions. You're not going to be driving a car going 200mph on a busy city road full of pot holes. This car will not be buffed
