### ISSUE TITLE
Lamborghini Gallardo Superleggera 

### ISSUE THREAD

**Issue by SirLisps** [fkk-cz/noire_vehicles#1565]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

Speed/acceleration seems pretty slow for the price and type of car

### Expected Behavior

A higher top speed or better acceleration 

### Anything else?

There’s a lot of cars that are way less in price that go a lot faster. (in acceleration and top speed)

**Comment by LPLips7** [comment]
The car goes slow due to the nerf it had. It used to go as fast as some 350k cars. It still goes decent speeds.. Otherwise I'd sell it super cheap at like 90k

**Comment by styxh** [comment]
you cant compare a lambo too any other name brand cars their all different. you're paying for the name and the logo doesn't mean it needs too go fast because  it cost such and such price🤷🏼‍♂️

**Comment by okxeon** [comment]
> you cant compare a lambo too any other name brand cars their all different. you're paying for the name and the logo doesn't mean it needs too go fast because it cost such and such price🤷🏼‍♂️

refer to this. The vehicle can hold 180 mph and its handling to performance is perfectly fine.
