### ISSUE TITLE
2019 Dodge Ram

### ISSUE THREAD

**Issue by ImDead48** [fkk-cz/noire_vehicles#1567]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

Want to say i love the truck, and love the handing, but i wanted to say for a 2019 Dodge Ram with a diesel engine. This thing is crazy slow. i went to the airport to test everything since its all flat so no bumps could up my speed or slow it down.
**Top Speed**  The truck was able to go a max speed of 96mph with everything maxed on it. 
**Top Speed with a trailer**  keep in mind there was nothing on the trailer and I was able to hit 66mph

### Expected Behavior

Not asking for the truck to have a crazy top speed like other trucks in the city that are able to go 150mph+ with only being 15k more. Just asking if the truck was able to go 115mph without the trailer.

### Anything else?

No.

**Comment by okxeon** [comment]
increased the top speed here: https://github.com/fkk-cz/noire_vehicles/commit/89ff6c8abf6003438db7f43afa9577e7fffec5b8. Wait for this tweak to merge.
