### ISSUE TITLE
[Exact name of vehicle, as displayed in game]: 

### ISSUE THREAD

**Issue by crazyday93** [fkk-cz/noire_vehicles#1568]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

why is the bmw m5 comp slower than that standard non supporter bmw m5 

### Expected Behavior

at least do the same speed 

### Steps To Reproduce

take it for a drive 

### Anything else?

could the speed be increased to match the standard m5 please

**Comment by Scubaaaaa** [comment]
People were using the 2022 M5 as a meta for getaways, which is why the vehicle got nerfed and won't be re-buffed. Can blame other people for not wanting to RP and just have an end goal to get away as fast and unrealistic as possible.
