### ISSUE TITLE
[Exact name of vehicle, as displayed in game]: 

### ISSUE THREAD

**Issue by SirLisps** [fkk-cz/noire_vehicles#1569]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

I saw someone respond to my gethub about the to Lamborghini Gallardo superleggera and I think they were thinking about the wrong one, the one I’m talking about is a support car that cost $445,000 it just got added

### Expected Behavior

I just want to make sure your thinking of that right car 

### Anything else?

N/A

**Comment by okxeon** [comment]
You can reply to people from the initial post, refer to what was said in there.
