### ISSUE TITLE
Rari F8 Tributo

### ISSUE THREAD

**Issue by damnonion** [fkk-cz/noire_vehicles#1573]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

Cars so loud you can’t even hear yourself think or the person talk in tha passenger. 
Nice sound just too loud 

### Expected Behavior

Can y’all please lower the audio so a spot where y’all can actually hear 

### Steps To Reproduce

lower the audio on the current sounds you put on it 

### Anything else?

i’ve had this car a long time and have never had any issues with it, i’ve bought this car 2x once from the oG owner and another from the auction after police taking it from me. after buying the c at twice and spending over 2 million on it i’d hate for this sounds to ruin the car iva had for so long and neve had a problem with it

**Comment by okxeon** [comment]
The sound is nice, but I agree it is very loud. Replaced with the 458 prior sound.
