### ISSUE TITLE
2002 Acura RSX Type S Handling

### ISSUE THREAD

**Issue by Ell34** [fkk-cz/noire_vehicles#1574]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

It literally does not turn, needs a major handling buff

### Expected Behavior

To actually turn 

### Steps To Reproduce

Test drive car
Try to turn

### Anything else?

N/a

**Comment by FukBerk** [comment]
Mine turns on just fine

**Comment by Competent1** [comment]
I spent some time with this vehicle and it has undergone a lot of testing. The issues you have stated have been fixed, enjoy the vehicle!
