### ISSUE TITLE
[1995 Ford Mustang]

### ISSUE THREAD

**Issue by Unwashedarc** [fkk-cz/noire_vehicles#1575]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

The car seems a very slow compared to other cars in its price range (around $160k) 

### Expected Behavior

I think that it should have a 15-20mph top speed buff to be at least on par with other cars with a similar price point such as the Audi RS5, Nissan GTR, Camaro ZL1. These are all cars that are in the same price range and can hit 160 and the mustang can only hit 140.

### Steps To Reproduce

Drive the car on the highway

### Anything else?

No

**Comment by okxeon** [comment]
Did not realize anyone else actually owned one of these given I've never seen a single other person use it in game. Tweaked the vehicle here: https://github.com/fkk-cz/noire_vehicles/commit/c89098355e07103f82a4647cb318f5c3d755c754
