### ISSUE TITLE
Mclaren 765Lt

### ISSUE THREAD

**Issue by T45DARK** [fkk-cz/noire_vehicles#1576]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

car has no engine or transmission upgrades you cant even click the options this causes the car to be ridiculously slow compared to its competitors. considering the car is 380 grand it should be able to keep up with the cheaper and slower versions of the car (2017 Mclaren 720s, Mclaren 720s spider) ect 

### Expected Behavior

i hope the engine upgrades can be sorted out along side the transmission of the car allowing the car to hit its desired speed

### Steps To Reproduce

.

### Anything else?

.

**Comment by PsychoticCore** [comment]
This issues been brought up a few times now and they're unable to fix it, it did get buffed just the other day so it's a little quicker than it used to be at least

**Comment by T45DARK** [comment]
well if it cant be fixed i feel that it should be buffed a bit more considering it only hits 170 and takes a while to get up there

**Comment by T45DARK** [comment]
especially considering the speeds of these other cars that are cheaper its just not fair at all if your paying almost 400 and it goes slower than a simple 4 door or suv

**Comment by okxeon** [comment]
A "simple 4 door" should also not be hitting a speeds of 170 mph - if that's the case then a majority of these overused cars need to be looked at.

**Comment by styxh** [comment]
i 100% agree need too get these vehicles at realistic speeds especially these "simple 4 doors"     


> A "simple 4 door" should also not be hitting a speeds of 170 mph - if that's the case then a majority of these overused cars need to be looked at.

**Comment by T45DARK** [comment]
If we are talking realistic speeds than this mclaren should definitely be hitting over 170

**Comment by okxeon** [comment]
There is a difference between realistic irl, and realistic for a gta 5 sever that spans about 8 miles from top to bottom. 170 mph is perfectly fine for a mclaren, especially one thats only $380k.
