### ISSUE TITLE
2002 Ferrari Enzo

### ISSUE THREAD

**Issue by Chitowndevil21** [fkk-cz/noire_vehicles#1578]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

No upgrades

### Expected Behavior

Performance upgrades
Wheel customizations
Window tint
Etc.

### Steps To Reproduce

Take to mode shop. 

### Anything else?

No

**Comment by Idk-maybe** [comment]
Swapped the vehicle modkit here - https://github.com/fkk-cz/noire_vehicles/pull/1603/commits/fa786e9fd27caaee400d0d14d3f0b82ed59f30c8
Wait for it to be merged live and the issue should be fixed
