### ISSUE TITLE
Lamborghini Centenario LP 770-4

### ISSUE THREAD

**Issue by talanzollers** [fkk-cz/noire_vehicles#1579]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

I just paid 1.9m for the Lamborghini Centenario and it wont let me upgrade ANYTHING. please help me fix this bug, i spent 2 weeks playing this game to get this car and nothing upgrades.

### Expected Behavior

i would like for you guys to fix the bug so that i can upgrade my car i worked hard for.

### Steps To Reproduce

help me fix this please

### Anything else?

nope!

**Comment by okxeon** [comment]
Its possible this issue was fixed in one of the many vehicle modkit fixes in the past few weeks we did. As of currently this vehicle has upgrades in all categories 
![image](https://user-images.githubusercontent.com/98451518/211713848-db088de1-97a2-4771-b13d-0eace6865ba4.png)
