### ISSUE TITLE
VW GTI Mk5

### ISSUE THREAD

**Issue by Rengleif** [fkk-cz/noire_vehicles#158]
Being a Mk7 GTI owner IRL, I have to say the car looks nice as far as the Mk5 goes, but it just doesn't seem to pull the power off the line that it's real life counterpart does, and the turning/handling on it is a bit too floaty. The turn radius should be way tighter, as it is a hot hatch and it drives like a tank on turns right now. The base price should probably be a few grand higher as well.

**Comment by fkk-cz** [comment]
https://github.com/fkk-cz/noire_vehicles/commit/b28cbcefb0c7e4a05fb69b601dee30922bd3c48f#diff-8ef3005574896b61ed8fe5e105e3fc98e1a34b69e13babd49bb6a5c427154fea

increased turning radius, don't want to mess with the accel/speed as the values are extremely unconventional and (somehow) work

this vehicle was also an issue in the past, where people could go 200mph
