### ISSUE TITLE
Tesla Gas Station Truck

### ISSUE THREAD

**Issue by LactatingWalrus** [fkk-cz/noire_vehicles#1580]
### Is there an existing issue for this?

- [x] I have searched the existing issues

### Current Behavior

Can't drive faster than maybe 2mph with the gas trailer attached. If you hold gas/brake/handbrake and then let go of both the brake and the handbrake will it begin moving. It can reverse just fine but the issue is there's only so much room at these gas stations and leaving the trailers blocks the spawn point until the server restarts.

### Expected Behavior

I'd expect the Tesla truck to be able to pull a gas trailer so it can be moved out of the way. I used to be able to even do a whole gas run with the trailer attached.

### Steps To Reproduce

1. Spawn a Tesla semi truck
2. Attach a gas trailer
3. Try to accelerate

### Anything else?

I have a clip if needed.

**Comment by cxerq** [comment]
Maybe it could be made that the trailer just poofs after a run is completed

**Comment by JuniorR1234** [comment]
Any update on this?

**Comment by okxeon** [comment]
The vehicle should be replaced with the ``phantom3`` and completely get rid of the buggy tesla semi. The tesla semi is a cool concept, but the vehicle is way too low in quality and has too many issues.
