### ISSUE TITLE
[1970 dodge challenger]: 

### ISSUE THREAD

**Issue by diamonddave588** [fkk-cz/noire_vehicles#1581]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

The sound for the car is really bland i wish for it to sound better 

### Expected Behavior

Better sounds 

### Steps To Reproduce

1. Get in car
2. Turn on car
3. Drive forward 
4. Enjoy 

### Anything else?

Here is the link for what I want it to sound like 
https://www.gta5-mods.com/vehicles/dodge-challenger-1970-hemi-idle-sound

**Comment by okxeon** [comment]
replaced the audio with the 1969 dodge charger sound: https://github.com/fkk-cz/noire_vehicles/commit/e9d518a6f8c71b7646e68d880c8d88b236fdb4c4
