### ISSUE TITLE
[Exact name of vehicle, as displayed in game]: 2017 Ford GT

### ISSUE THREAD

**Issue by Mackowo** [fkk-cz/noire_vehicles#1582]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

The car just seems to be very under powered for its price. The acceleration is one of the lowest for its price range and the top speed on a flat line doesn't compensate for the acceleration. There are many cars that are way cheaper that perform better in every aspect. 

### Expected Behavior

I would expect the car to at least perform somewhat better. The price doesn't justify this vehicle. 

### Steps To Reproduce

1. Get in car 
2. Test acceleration 
3. Test top speed

### Anything else?

I just believe if a car is this high in price it should perform a little bit better than cars half the price. I'm not expecting the car to be something amazing, just slightly better to justify the price.

Thanks for looking into it ❤️

**Comment by styxh** [comment]
Gotta remember with hyper and supercars such as this one you're paying for looks and the name. its not always about speed the car gets close too 200 and it gets up there quick. It also handles fairly well. in all honesty the car may be a little "too good" for the price!

**Comment by Mackowo** [comment]
I think this should be conveyed to the player tho, how expensive cars are mostly for looks. When you grind for awhile to get a car just to learn its only for looks and not performance is a bit disheartening. 

Not to be rude lol just My dumb opinion, thanks for the quick response tho ❤️

**Comment by styxh** [comment]
i mean in reality tho you can test drive it and see exactly how the car performs and you can also go too LS customs upgrade it and see exactly how it performs fully upgraded.

**Comment by Idk-maybe** [comment]
After testing, the car is fine for the price. I don't see a reason for it to get buffed seeing as it's speed is fine, with decent handling
