### ISSUE TITLE
[Exact name of vehicle, as displayed in game]: Suzuki GSX-R1000

### ISSUE THREAD

**Issue by LUCCI23** [fkk-cz/noire_vehicles#1584]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

after going to LS CUSTOMS adding turbo, different color pattern, headlights and neons upon placing in the garage the vehicle reverts to stock other then the color pallet but the color pallet is not of which is selected

no option to remove license plate

more upgrades in order to reach a higher top speed due to the bike going 175+ irl
and has a faster acceleration
### Expected Behavior

any and all upgrades should remain after placing in a garage
color pallet should be of what was requested in the shop
more performance upgrades

### Anything else?

hope some of the issues could be resolved i cannot offer any insight on how to correct said problems

**Comment by okxeon** [comment]
Fixed the bikes modkit - this will fix its upgrades from being removed from the vehicle when stored/pulled from a garage. This also will give the bike an option to have proper upgrades in the shop.
