### ISSUE TITLE
[1970 Dodge Challenger rt ]: 

### ISSUE THREAD

**Issue by diamonddave588** [fkk-cz/noire_vehicles#1586]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

It's a bit under powered when it comes to the top speed compared to other cars at this price point I understand it's a classic but the top speed irl for that car is around 160 to 170

### Expected Behavior

I just wish for the top speed to be increased everything else is perfect about the car 

### Steps To Reproduce

1. Top speed increased to 165
2. I don't know any configuration for this 
3. Better top speed 
4. Go fast and enjoy the classics 

### Anything else?

Please do this my sound pack mod wasn't answered I just want this car to be a little better considering this is my dream car irl

**Comment by Competent1** [comment]
I just tested this vehicle out. Looking at the price and the results of my test session, it does not need a top speed increase to 165 mph. When talking about a vehicle's top speed IRL you have to remember, that top speed is typically calculated on a track with perfect conditions and on top of that, top speeds of vehicles irl will not match the top speed of the same vehicle in city. There is a discussion open in the discord titled Vehicle Handling Rework which talks about all vehicles having their top speed decreased for quality of life and balancing purposes.

**Comment by okxeon** [comment]
Another thing is your can't compare cars speed in game to an irl model. Yes the car can technically do x speed, but the gta map is only so big and it does not make sense for cars to be whipping it around going 170+ everywhere.
