### ISSUE TITLE
TOYOTA SUPRA

### ISSUE THREAD

**Issue by mrpleefs** [fkk-cz/noire_vehicles#1587]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

hey, are you able to re consider the nerf on the 350k supporter toyota supra? i understand the top speed issues when people are going well over 200 but this car should be alot faster. in real life a 2jz mkiv supra can easily hit 1000 hp with a tune and bolt on mods. the car was nerfed too much imo now its unrealistically slow and it cost 350k ....it also didnt hit 200 on level ground before anyway.. i think rolling back some of the acceleration and handling nerf but lowering the top speed slightly from what it was would be a better way to go about it because i love that car as a fast alternative to the normal italian cars but its just way too slow now

### Expected Behavior

I think the nerf on the 350k supporter supra was way too much id like to see it revisited and the nerf rolled back especially acceleration 

### Anything else?

happy to discuss further what I think the cars performance should be at. not sure what else to add

**Comment by styxh** [comment]
my man the supra still performs extremely well its just not as fast anymore. it was lowered too be more realistic for gta and the size of the map. the city is too fast paced because everyone is so used too driving 200+ constantly. the supra is perfect for the price!

**Comment by mrpleefs** [comment]
I Understand the top speed needs to be dialed down on alot of cars, but the acceleration now is only 1 second faster 0-100mph than my 89 miata lol that doesn’t make sense the miata is a 1.8L 4 cylinder and the supra is a 2JZ twin turbo inline 6.

I will do some more Testing but to me it seems way over nerfed.

**Comment by styxh** [comment]
> I Understand the top speed needs to be dialed down on alot of cars, but the acceleration now is only 1 second faster 0-100mph than my 89 miata lol that doesn’t make sense the miata is a 1.8L 4 cylinder and the supra is a 2JZ twin turbo inline 6.
> 
> I will do some more Testing but to me it seems way over nerfed. 
> 
> 
> Sent from my iPhone
> 
> > On Dec 24, 2022, at 6:30 PM, Styx ***@***.***> wrote:
> > 
> > ﻿
> > my man the supra still performs extremely well its just not as fast anymore. it was lowered too be more realistic for gta and the size of the map. the city is too fast paced because everyone is so used too driving 200+ constantly. the supra is perfect for the price!
> > 
> > —
> > Reply to this email directly, view it on GitHub, or unsubscribe.
> > You are receiving this because you authored the thread.
> 

the miata hasn't been nerfed yet. every vehicle in the city is getting QOL adjustments. theres no reason too compare this car too that car and blah blah blah when they are all getting changed. its fine!

**Comment by mrpleefs** [comment]
Alright well at least make the blow off valve turbo sound come back on the supra now it never goes off in between gears because the dude is shifting at like 2000 rpms.

**Comment by okxeon** [comment]
In comparison to every other vehicle that was nerfed with the QOL adjustments this car is perfectly fine. A top speed of 215mph on a 350k car really made no sense. Refer to previous comments as why the car will remain the same.
