### ISSUE TITLE
2018 Harley Davidson FLHXS

### ISSUE THREAD

**Issue by Ell34** [fkk-cz/noire_vehicles#1590]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

The bike turns really bad, needs a slight handling buff

### Expected Behavior

TO be able to turn 

### Steps To Reproduce

drive it

### Anything else?

no

**Comment by Competent1** [comment]
Thank you for submitting this issue. After the mechanics at the shop looked at this vehicle, we do have some bad news. This vehicle has model issues and has a recall pending on it. Sorry for any inconvenience that this will cause.
