### ISSUE TITLE
2016 Porsche 911 Turbo S, Sport

### ISSUE THREAD

**Issue by helloqueygs** [fkk-cz/noire_vehicles#1592]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

The driver side door teleports you in when you click f, and sometimes it wont work so it makes you go to the passenger side and you have to shuff to get to the drivers side. Not only that its literally a 1 seater the passenger side breaks and will not let anyone after the slightest damage. (I've tested it)

### Expected Behavior

opening doors, functioning doors, and seats.

### Steps To Reproduce

1. buy the car at pdm
2. open the driver door
3. (try getting in the passenger side)

### Anything else?

https://medal.tv/games/gta-v/clips/OgFH8WPJLdHGS/d1337DNX1qvQ?invite=cr-MSxOMGwsNDQ0MTg2MzYs

For 355k$ id like it working

**Comment by styxh** [comment]
pretty sure thats a model issue

**Comment by DarkFan5** [comment]
Nope think its a snow issue, didnt have any issues ever before this snow in the last couple days. Snow should be gone soon

**Comment by helloqueygs** [comment]
aigh

**Comment by helloqueygs** [comment]
still hasnt fixed

**Comment by Idk-maybe** [comment]
The only change made recently was the change to test the new drive-by layout, I reverted here https://github.com/fkk-cz/noire_vehicles/pull/1591/commits/36dbaabe43677abd13eeb4db140e233d53821419

Wait for the tweak to merge
