### ISSUE TITLE
[Exact name of vehicle, as displayed in game]: McLaren 765LT Super

### ISSUE THREAD

**Issue by Sxuce777** [fkk-cz/noire_vehicles#1593]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

hey admins, i just purchased the McLaren 765LT and it lets me upgrade everything but the Engine and Transmission. Why is that? pls help.

### Expected Behavior

for it to be fixed

### Steps To Reproduce

hey admins, i just purchased the McLaren 765LT and it lets me upgrade everything but the Engine and Transmission. Why is that? pls help.

### Anything else?

hey admins, i just purchased the McLaren 765LT and it lets me upgrade everything but the Engine and Transmission. Why is that? pls help.

**Comment by BreezyEZ** [comment]
This cannot be fixed as you saw in supporter-chat . It is a model issue. Sorry!
