### ISSUE TITLE
1990 Chevrolet Camaro IROC-Z

### ISSUE THREAD

**Issue by LPLips7** [fkk-cz/noire_vehicles#1595]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

Nice Car, Great Handling and everything... But, There are No Upgrades, besides Turbo

### Expected Behavior

Should have Upgrades for Suspension, Transmission, Engine, Armour, and brakes aswell

### Steps To Reproduce

Just add the upgrades and that's really all guys . Thanks

### Anything else?

Nope

**Comment by okxeon** [comment]
Fixed the broken modkit on the car, so should be fixed for next merge. I agree the car looks great, I hope more people end up driving these kind of vehicles.
