### ISSUE TITLE
Mercedes-Benz s600 w220

### ISSUE THREAD

**Issue by damnonion** [fkk-cz/noire_vehicles#1597]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

no upgrades no window tints 

### Expected Behavior

add upgrade’s 

### Anything else?

no thanks

**Comment by Idk-maybe** [comment]
Attempted a modkit fix here - https://github.com/fkk-cz/noire_vehicles/pull/1603/commits/78da87896291cc69633aa6c34be56c80feaf767a
Wait for the merge to go live
