### ISSUE TITLE
2017 Ford gt

### ISSUE THREAD

**Issue by T45DARK** [fkk-cz/noire_vehicles#1602]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

the ford gt is a 680 thousand dollar super car, i feel that this car should be buffed due to the fact that it is THE slowest car in its price range (600k-700k) for a supercar i believe that 170 mph is a bit slow, especially considering the price.

### Expected Behavior

i believe that this car should be slightly buffed in the top speed area and have the drag reduced so this car can compete in its price range and keep its value in the re-sale market

### Steps To Reproduce

1.reduce drag
2. give it a higher top speed

### Anything else?

.

**Comment by Competent1** [comment]
I tested this vehicle for many hours and with how good the handling is, the speed is fine for the current price that the car is at.

**Comment by T45DARK** [comment]
i very much disagree with this statement, i believe that the car could have decreased handling and higher top speeds just as the rest of the super cars

**Comment by Idk-maybe** [comment]
After testing the car, it hits speeds of about 175 on a flat. Mixed with it's handling for it's price the vehicles speed wont be touched
