### ISSUE TITLE
[Exact name of vehicle, as displayed in game]: Lamborghini Aventador S

### ISSUE THREAD

**Issue by Cozy5** [fkk-cz/noire_vehicles#1607]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

The top speed just makes no sense at all, I am going 174 when I see Murcielagos going 180 and Huracan Evo Spyders going 200+, hell I have been smoked by a 150k Corvette that is supporter, my car cost 1.5M and I am getting smoked by cars that are not even close in price. How does that make sense? I'm not trying to be rude but I bought this car because the supporter McLaren I have goes 160 when it costs 380K and I figured since this costs a lot of money it will go faster guaranteed, yet here I am with another car that is just getting absolutely dusted by supporter cars that are not even close in price or other non-supporter cars that are still way cheaper. I just don't understand how that works.

### Expected Behavior

I would like to see the car boosted in MPH for sure, the acceleration is also pretty slow so that would be nice. Maybe about 215 MPH? A little lower like 210? That makes sense considering how it goes about 174 right now. 

### Steps To Reproduce

I don't really know.

### Anything else?

No

**Comment by LPLips7** [comment]
I've noticed Cars Getting nerfed a little over the top too. I dont think you'll be able to get it to go 210 man.

**Comment by Cozy5** [comment]
> I've noticed Cars Getting nerfed a little over the top too. I dont think you'll be able to get it to go 210 man.

Yeah I know but a man can wish, I think 200 would be good though

**Comment by LPLips7** [comment]
Its not going to though, thats the thing. 2 Million dollar cars are hitting the 180 - 185 part now. Me Personally, Im not really bothered by it, As I now think acceleration is what matters. I'd prefer have a car that goes 1 - 100 in 3 seconds but caps out at 160 then have a car that goes 1- 100 in 6 seconds and goes 200

**Comment by okxeon** [comment]
Tweaked here: https://github.com/fkk-cz/noire_vehicles/commit/8877e21ac521807d45442cc6f7d6415ed6401f11 to make the vehicle go about 180+ now and higher acceleration. As for your wishes of a 210+ top speed - thats really just not going to happen. This has been said in multiple other discussions, chats, and githubs, but gone are the days where the norm for a car is 200+ mph. As for the evo spyder that will be tweaked as well.
