### ISSUE TITLE
2020 Ferrari F8 Spider

### ISSUE THREAD

**Issue by LPLips7** [fkk-cz/noire_vehicles#1608]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

The cars wonderful, Goes about 165 flat which isn't too bad after the nerf, Has decent handling for the Price. I have noticed (Maybe It's Just me) That the acceleration is a bit Slow

### Expected Behavior

It would be nice too see if this car could possibly get a slight acceleration buff... I've noticed the car goes 1 - 100 in an average of about 6- 7 seconds... Unless its double clutched of course but that boosts every other car as well. The 200- 350k Ferrari's accelerate as fast or Faster. 

### Steps To Reproduce

Just a slight acceleration buff would be nice and it only goes 165 flat so a slight speed buff aswell would be nice If that's all good. Maybe test it ingame and let me know what ya'll think...

### Anything else?

If I see any other cars that handle or feel weird after the new nerf, I'll test it out and be sure to create a ticket.. Otherwise- Thank you

**Comment by okxeon** [comment]
After driving the car around for a while it seems like this is a fair balance. The car has decently high drive inertia, and after hitting that 100mph mark it hits its top speed in 10-15 secs after that. I do not think this vehicle needs a buff or adjustment as it seems perfectly fair and balanced.
