### ISSUE TITLE
1984 Ford F-150

### ISSUE THREAD

**Issue by PsychoticCore** [fkk-cz/noire_vehicles#1609]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

When turning at above like 30 mph the vehicle will start flipping uncontrollably 

### Expected Behavior

For the vehicle to not flip when turning

### Steps To Reproduce

1. Drive
2. Attempt to turn

### Anything else?

No

**Comment by BreezyEZ** [comment]
Fixed here: https://github.com/fkk-cz/noire_vehicles/pull/1610/commits/6f3054473e200e585e8df5dd6c69c2191d036f59

Wait for this to merge.
