### ISSUE TITLE
dodge challenger hellcat in supporter vehicles

### ISSUE THREAD

**Issue by trayvonblack** [fkk-cz/noire_vehicles#161]
great car the only thing is it sounds so bad for being a hellcat it would be alot better if it has a custom sound to it i thought about this one would be nice for it.        https://www.gta5-mods.com/vehicles/v8-supercharger-mod

**Comment by Straightvibes** [comment]
This would be dope on the 2020 SRT Hellcat Charger too

**Comment by fkk-cz** [comment]
> 
> 
> great car the only thing is it sounds so bad for being a hellcat it would be alot better if it has a custom sound to it i thought about this one would be nice for it. https://www.gta5-mods.com/vehicles/v8-supercharger-mod

unfortunately this is for SP, it seems to replace a vanilla car:

3) replace that line with this new line " **mamba** " (you can use this line to replace any cars sound)
