### ISSUE TITLE
2018 Dodge Charger Police Surplus

### ISSUE THREAD

**Issue by LPLips7** [fkk-cz/noire_vehicles#1621]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

Hi- Its me again-Car's feckin Awesome, performs well and goes a nice speed, But i have noticed multiple bugs with it. To start off with, The car's horn seems not to work for me half the time..? I've also noticed if you take off the Bull bar with PG UP Options, you can't put it back on until you've registered a repair kit. And whenever i take it out of a garage, The keys dont seem to work on it until you step out of the vehicle...

### Expected Behavior

Just wondering if this is a possible fix, or if this is actually the Modkit of the vehicle itself.

### Steps To Reproduce

... Just fix that stuff listed above if possible

### Anything else?

Nope, Thanks

**Comment by okxeon** [comment]
As of right now the vehicle has leo flags which I believe causes the buggy / delayed horn -- removed that here https://github.com/Competent1/noire_vehicles/commit/80a0839a5941a1c2aab0b4fb4e3330878a61ae70. As for the extras not staying on the vehicle select the extras you like, and then take the vehicle to the customs shop and apply some vehicle mod like tires and exit. this _should_ save the extras to the car for the future.
