### ISSUE TITLE
1997 Mitsubishi GTO coupes

### ISSUE THREAD

**Issue by recruit2212** [fkk-cz/noire_vehicles#1624]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

Currently no performance upgrades or body kits. 
the vehicle had the ability to change the wheels but now it only allows for paint and turbo which is a shame since these cars are known for their modding capability.

### Expected Behavior

ability to change body parts and engine upgrades .

### Steps To Reproduce

1.go to customs
2.Try to put upgrades on.  

### Anything else?

n/a

**Comment by okxeon** [comment]
Corrected the vehicles modkit which should allow for engine & body mods.
