### ISSUE TITLE
[Exact name of vehicle, as displayed in game]: 1964 Chevrolet Impala SS

### ISSUE THREAD

**Issue by Patton1776** [fkk-cz/noire_vehicles#1625]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

Simply put, the Impala is a $43K car that is undrivable.  It lacks any upgrades (except Turbo) and corners so poorly that it's virtually undrivable. 

It looks gorgeous, but it corners like melted cheese and the lack of upgrade options makes it impossible to address with suspension.  It also cannot have it's wheels changed, painted, or any of the other cosmetic upgrades almost all cars have (window tint, horn, etc.)

### Expected Behavior

- Ability to take corners without spinning ass-out (even at low speed)
- Paint-able wheels
- Changeable wheels
- Vehicle upgrade options (engine, suspension, etc)

### Steps To Reproduce

- Drive the car around a corner at even low speeds, spins out.  Virtually undriveable above 50 mph.
- Visit upgrade shop, no upgrades are available (even cosmetics, apart from car paint)

### Anything else?

Love the server!  Considering a paid donation when I can spare the change.

**Comment by okxeon** [comment]
Gave the vehicle the handling of the chino, which is a similar vanilla style of vehicle. This should significantly improve on the handling. In addition also corrected the modkit for the vehicle which should allow body mods / engine mods now.
