### ISSUE TITLE
SPEED UNIT OVER POWERED 

### ISSUE THREAD

**Issue by damnonion** [fkk-cz/noire_vehicles#1628]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

Ferrari Tribuito F8 vs Mustang speed unit
1.3 million car used to go 210-225 avg
i understand y’all had to balance the speed to the ratio of that map but a mustang should not be keeping up 1.3 million dollar farari going down the interstate. The bikes weren’t keeping up why is the mustang stil so op 

### Expected Behavior

If y’all gonna balance the cars out it doesn’t make sense for a ford mustang to go as fast as a Rari
My cars goes an avg of 175 either my car should go 200 or the mustang should go 150, y’all said y’all nerfed the cop cars but it seems like that mustang needs to be looked over it should be be competing with a super car like that 

### Steps To Reproduce

Lower Speed unit mustang or raise Farrari F8 Tributo speed

it’s a shame people spend so long trying to be able to buy a car someone doesn’t have just for one of the most basic cars in america (ford mustang)  to be able to keep it with the car without a problem, regardless of the work put into a mustang it should never be able to keep up with a farrari f8 

### Anything else?

we could set something up so y’all could see how unrealistic it is for a mustang to keep up w a rari i wish i could have got the clip

**Comment by damnonion** [comment]
any reason why a ford mustang goung as fast as 1.3 million dollar Ferrari

**Comment by xFooliee** [comment]
> any reason why a ford mustang goung as fast as 1.3 million dollar Ferrari

My bad brother, I’ll take the twin turbskies off tonight

**Comment by xFooliee** [comment]
I mean in all fairness it takes the high speed unit a little time to climb up anything past 170. If we are talking about unrealistic then we can def talk about someone doing chases in a 1.7 mil car as well lol. Plus everybody likes to abuse everything then complains when it doesn’t go there way

**Comment by Unwashedarc** [comment]
It is realistic for a mustang to go the same speesld as a Ferrari no matter what. It's also not unrealistic for people in fast cars to run from police.

**Comment by damnonion** [comment]
if you pull me over in a car that i can go faster than you in im gonna outrun you it's simple, y'all just can't keep up with it so your nerf everything into the ground if facts were brought up about both cars the it would be easy to see a Ferrari should be able to easily out run a mustang. The mustang gets up to 170 just as fast. Yall livin in a fantasy, no reason a mustang should keep up with ferarri with no problem on the e way

**Comment by styxh** [comment]
in all fairness if you can't out run that terrible handling mustang in your 2mill Ferrari you probably shouldn't be running in the first place lol.

**Comment by damnonion** [comment]
crazy thing is i outran y'all then made the github when i made it away from y'all.

**Comment by Idk-maybe** [comment]
This was given QOL adjustments here - https://github.com/fkk-cz/noire_vehicles/commit/63e9a047547b712085fa95c880a759a8c368c247
The vehicle should be fair compared to others now
