### ISSUE TITLE
Bugatti Chiron Exhaust Sound

### ISSUE THREAD

**Issue by Ell34** [fkk-cz/noire_vehicles#1632]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

Sounds like a default car

### Expected Behavior

Is it possible to give the Bugatti chiron the same sound as the divo?

### Steps To Reproduce

n/a

### Anything else?

no

**Comment by Competent1** [comment]
This issue has been resolved by the mechanics that work hard in the simulator/shop. Wait for the new engine sound to be merged.
