### ISSUE TITLE
2017 Porsche 911 GT-RSR -

### ISSUE THREAD

**Issue by spliff808** [fkk-cz/noire_vehicles#1635]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

The vehicle currently performs aright, but now how you would expect a top of the line Porsche to handle. I find the top speed reasonable however the car is significantly lighter than most cars at 2855 pounds so I feel it lacks just a tad in acceleration . The main issue I have is the handling, Porsches are know for being amazing handling cars for the track and this car doesn't perform like one, especially for being the best of the best Porsche, the RSR is line of GT cars that are produced for motorsport endurance races. they are top of the line. It shouldn't get to much better handling wised than these cars.

Car also is shown as NULL in garage.

### Expected Behavior

For the car to really stick to the ground so thousands of dollar suspension feels likes it working. I would expect the tires to be a bit more sticky as again this is really a race car. Acceleration and speed could maybe use some love but I feel the handling is where its struggling most.

### Anything else?

I hope you guys see where im coming from with this Line of Porsches (RSR) and how they compare and compete against other cars.

**Comment by spliff808** [comment]
Vehicle could use a more aggressive audio track too. Especially cause the Porsches rev very high.

**Comment by Idk-maybe** [comment]
After testing the vehicle it's performance is perfectly fine for the price point. I don't see a reason this vehicle should be buffed
