### ISSUE TITLE
2011 Subaru Impreza STI

### ISSUE THREAD

**Issue by Jokke8567** [fkk-cz/noire_vehicles#1636]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

Dosnt smoke when broke down so its hard to see when it will break down

### Expected Behavior

Making it so it will smoke when broken down

### Anything else?

nope

**Comment by okxeon** [comment]
I don't quite know why the vehicle does not smoke when it should be, but there is an audible sound of engine smoke which can help you know if it will break down. As far as I am aware there is no fix for this.
