### ISSUE TITLE
[BUG]: livery on the Audi RS5 Libertywalk is glitched 

### ISSUE THREAD

**Issue by Nateofficial** [fkk-cz/noire_vehicles#1638]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

Before I bought the RS5 Libertywalk I saw that the livery was glitched out and flashing between the other liveries depending on what angle you're viewing the car at. After buying it I noticed you can't take the glitched livery off and you can't really change the livery because it still flashes no matter what livery you choose or if you fully remove the livery. 

### Expected Behavior

After buying the RS5 Libertywalk I was planning on going to Los Santos Customs, going to the "livery" option, switching through the liveries, taking the glitched livery off, painting the car white. 

### Steps To Reproduce

.

### Anything else?

.

**Comment by Idk-maybe** [comment]
This is a model issue and nothing can be done by us to fix it, the vehicle just needs to be removed
