### ISSUE TITLE
[Exact name of vehicle, as displayed in game]: 

### ISSUE THREAD

**Issue by noyeahsure** [fkk-cz/noire_vehicles#1639]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

any time I get into a small wreck in the new 2022 Camaro SS the bumper basically inverts itself, not sure if this is something we can fix or not?

### Expected Behavior

nothing really expected, just asking a question

### Steps To Reproduce

1. wreck car
2. observe

### Anything else?

![image](https://user-images.githubusercontent.com/93731208/216271795-ea2b1e22-5953-4722-bc19-a81aa8020e7d.png)

**Comment by Idk-maybe** [comment]
This vehicle needs to be recalled, it's a model issue
