### ISSUE TITLE
2021 Porsche 911 Turbo S

### ISSUE THREAD

**Issue by Ell34** [fkk-cz/noire_vehicles#1643]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

The car feels like its on top of a ball, center of gravity/weight feels off

### Expected Behavior

Not to drive like a boat

### Steps To Reproduce

Test drive

### Anything else?

no

**Comment by Idk-maybe** [comment]
I gave this vehicle a major handling rework, shouldn't act weird like it did before. - https://github.com/fkk-cz/noire_vehicles/pull/1664/commits/edfba8201665d84dcd6faafa562fb018f49a4cb4

Wait the it to merge live
