### ISSUE TITLE
[Lamborghini Huracan LB]: 

### ISSUE THREAD

**Issue by Unwashedarc** [fkk-cz/noire_vehicles#1646]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

The top speed is fine and I think its very balanced but the acceleration is super slow and it is way too drifty and spins out way too much. It also cannot seem to go over curbs without hitting them, sometimes even making the car smoke.

### Expected Behavior

Make it less drifty so that I can take corners without spinning out. 

Buff the acceleration to make it actually feel like a Lambo.

If possible, make it so that it doesn't hit curbs when trying to drive over them. 

### Steps To Reproduce

1. Drive this car
2. Test the acceleration on a straight road
3. Take corners and sharp turns
4. try to drive over curbs at a slight angle

### Anything else?

No

**Comment by okxeon** [comment]
Tweaked the traction and raised the suspension on the vehicle to make it feel cleaner to drive. These https://github.com/fkk-cz/noire_vehicles/commit/cdd803f35cc7807766666d760458921f459b6f1a improvements should feel like a big difference. As for the acceleration it seems about on par to other related vehicles.
