### ISSUE TITLE
Small Trailer BUG

### ISSUE THREAD

**Issue by HeywoodJabloughmi** [fkk-cz/noire_vehicles#1647]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

Locking the trailer is only prevents you from lowering the ramps and being able to sit on it. anybody can still hook up to a locked trailer. 

### Expected Behavior

a locked trailer should not be able to be hooked up to and stolen. 

### Steps To Reproduce

Park a trailer, lock it, and then someone else hooks up to it while its locked.

### Anything else?

I was hunting when my trailer got stolen and i couldn't do anything about it, when i retrieved the trailer it was still locked. then i tested it with someone else to see if you can still hook up to trailers while being locked and you can.

**Comment by okxeon** [comment]
Since the trailers are all add on mods I do not believe there is an easy fix for this. One solution is to leave the truck towing the trailer parked right at the hitch so it is nearly impossible for potential thieves.
