### ISSUE TITLE
Mercedes Benz Metris

### ISSUE THREAD

**Issue by esteban23xD** [fkk-cz/noire_vehicles#165]
Switch the category from muscle to offroad for the trunk Idc about fuel efficiency just really want the space

**Comment by fkk-cz** [comment]
https://github.com/fkk-cz/noire_vehicles/commit/b28cbcefb0c7e4a05fb69b601dee30922bd3c48f#diff-08e157b9be8b881c74a66dc183bfe3c1012ee79552d8b7671ca54e3523244b5c

VC_VAN is more appropriate
