### ISSUE TITLE
Police Vehicles still being able to catch up to a 2 mil + Car

### ISSUE THREAD

**Issue by LPLips7** [fkk-cz/noire_vehicles#1651]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

Ok, So I've just bought a 2.4 Million Dollar Bugatti & Into a hot pursuit in the city, highway and through Sandy Shores. My Question is, Why are Police Bikes still catching up to the car when most American police bikes go 130 MPH, and why are The SUV's still catching up when they Don't go very fast IRL. 

I'm obviously a bit salty as this makes no sense what so ever, And I know for a fact it annoys Mod's when we complain about Police Vehicles going unrealistic speeds, but its true... And yes i've seen the recent Police Vehicle nerfs, but i'm just still mind Boggled... & It's not me Going "Slow" In it when i was going 160 - 180 and SUV's Were still catching up when they were meant to be nerfed....

### Expected Behavior

Im pretty Happy with the Bugatti's speed, But i just don't even understand how this works anymore. The QOL Adjustments were meant to cover all vehicles, & Yes I Understand Not every vehicle can be adjusted at Once... So I say either reduce the Police Vehicles speeds, or buff the 2.4 Mil Chiron. 2.4 mil just for a cop to catch up in a SUV Or Motorbike.... The SUV's were catching me Quick AF Through the streets which makes 0 sense, and still almost caught me on the highway, Then, a cop bike TAILS Me right behind the whole time I'm flying into Sandy Shores....

If I'm really putting 2.4 Mil into a single car and it gets caught up to by a SUV Or a bike im a bit annoyed..

Similar to the Same case With the Ferrari FXXK Github Post that was made

### Steps To Reproduce

Either slightly buff the vehicle considering it should average 190 - 195 not 185 on the highway without Air, Or nerf these cop Cars. 

Not trying to start an argument or nothin, but the whole thing doesnt make sense to me...

Police vehicles Going Over what they go IRL, & 2 MIllion Dollar Hypercars going way under what they go IRL...Bugatti Chiron should be going Slightly Faster flat, aka a possible slight buff on acceleration

### Anything else?

Also the 597k Bugatti Veyron Goes basically same speed as the 2.4 mil Chiron still, so the Veyron needs a nerf... Or the chiron needs a buff

**Comment by Ell34** [comment]
As the only other owner of this car, I don’t claim this

**Comment by Ell34** [comment]
The car is fine bro

**Comment by Ell34** [comment]
Just don’t get into a police chase

**Comment by LPLips7** [comment]
Ell I don't think I've ever seen you go anywhere besides Weekend Shopping, Burgershot and Court house... From what It looks like in the Handling adjustments Traction is Being adjusted

**Comment by Ell34** [comment]
Bud I don’t know why you’re getting salty. The car is fine, yes the QOL adjustments suck but there’s nothing you can do about it

**Comment by LPLips7** [comment]
just a weeee bit salty... I'd be happy with a slight handling and an ever so slight speed boost whether top speed or acceleration.. Other than that the cars great!

**Comment by okxeon** [comment]
> when i was going 160 - 180 and SUV's Were still catching up
This just straight up is false. No police SUV will even hit 160, much less catch up to you already traveling at this speed. Another thing, why are you evading in a Bugatti?? You are complaining about realism here with police vehicle speeds, yet you are evading in a million dollar car over what -- speeding?? Also from what you are saying here is because you own a million dollar vehicle you should be untouchable by the police? This whole argument makes literally no sense at all.

**Comment by LPLips7** [comment]
I didn't Pull over because I'm a felon with a class 2 firearm, Also I apologize if it seems like I went on a bit of a ramble here..
