### ISSUE TITLE
Bugatti Chiron.. Last Post Hopefully

### ISSUE THREAD

**Issue by LPLips7** [fkk-cz/noire_vehicles#1653]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

After the new QOL Adjustments, the acceleration and turning is fine now, But i don't understand why the top speed of it flat was lowered... Now I'm only averaging 178- 182 Flat

### Expected Behavior

I'm just happy if it goes 185 - 188 flat Average or something... There's now 500k Supercars catching up to it

### Steps To Reproduce

Fix Top speed when driving on a Flat Surface

### Anything else?

Nope...

**Comment by Ell34** [comment]
When the QOL for the car was posted, it was only mentioned in the public channels that the handling was touched, nothing about top speed.. I don't know why nobody would mention that the top speed was also adjusted.

**Comment by Idk-maybe** [comment]
*There's now 500k Supercars catching up to it* - Then it seems as cars need more of a QOL Adjustment then they were given. The car for the value is fair seeing as cars that cost more, go slower compared to this. For example, the Super Sport 300, goes roughly 173-175 on a flat. This vehicle will not be buffed.
