### ISSUE TITLE
Bugatti Chiron Audio Swap

### ISSUE THREAD

**Issue by LPLips7** [fkk-cz/noire_vehicles#1654]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

I know the audio has already been swapped on this Vehicle, but it still sounds a bit plain...

### Expected Behavior

Wanted the car to have a unique sound..

### Steps To Reproduce

https://www.gta5-mods.com/vehicles/mercedes-amg-m177-m178-amg-gt-engine-sound-pack-oiv-add-on-fivem

The Sound Pack comes with 2 Mods- The sound I wanted to be added was the AMG 4.0T V8 (M177) Engine Sound

### Anything else?

No thank you, Hopefully it works.

**Comment by styxh** [comment]
Man the Amt of complaints you've put in on this car you might as well just buy a new car at this point.

**Comment by LPLips7** [comment]
Im fine with the car now I just want an Audio Swap..
