### ISSUE TITLE
Pontiac FireBird (Supporter Car)

### ISSUE THREAD

**Issue by PiggySquad** [fkk-cz/noire_vehicles#166]
The car was 90k yet only tops out at 113mph the cars half the price go 180mph. I'm just asking for it to be raised at least a little bit <3 Oh also the texture of the stripes on the car glitches out and doesn't work

**Comment by fkk-cz** [comment]
https://github.com/fkk-cz/noire_vehicles/commit/81e3b4b322252fef0fba9b964fd6f40cd589d45a#diff-2c4f2ec9b1b755f47a7546794d85ee7412f41ae0ef7c36e3837d44962dacd128

also fixed the GTX2 name
