### ISSUE TITLE
Nissan Skyline GT-R

### ISSUE THREAD

**Issue by RileyRamirezz** [fkk-cz/noire_vehicles#1661]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

i noticed the max speed has been decreased with approximantly 20 mph which in my opinion i find strange and also it has more traction when i take off or when i use the handbrake which i find very unfortunate

### Expected Behavior

i would like the Skyline to get its prior performance back or at least the amazing handbrake performance that im able to drift around. it was such an amazing and well ballanced car and fun to drive. i really hope you would consider my request 

### Anything else?

unfortunatly i have no videos to compare the before and after. i hope you will take my word for it that this car is not what its used to be

**Comment by Competent1** [comment]
This has been adjusted here: https://github.com/fkk-cz/noire_vehicles/commit/2e7394d44eea6a322015a3045b4baa8ce5b8eb0d Wait for it to be merged.

**Comment by RileyRamirezz** [comment]
how long does the mergeing usually takes?

**Comment by Competent1** [comment]
Not too long. This has not been merged yet. Please continue to be patient, thanks!
