### ISSUE TITLE
[Exact name of vehicle, as displayed in game]:  Nissan titan

### ISSUE THREAD

**Issue by Gmoney7** [fkk-cz/noire_vehicles#1662]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

Its very very vulnerable, its as easy to break as the h2 was back when it got nerfed, its so weird, its like a 5 ton truck with bumper bars and stuff and it cant even take one hit without smoking

### Expected Behavior

I expect it to be as resilient as before, maybe not as fast but at least make it not break down after touching air molecules

### Steps To Reproduce

1.drive it
2.crash it 

### Anything else?

no

**Comment by Competent1** [comment]
Thank you for submitting this issue regarding the Nissan Titan. After driving/testing this vehicle and crashing into many things at various speeds (top speed included), I have concluded that this vehicle does **NOT** break down after touching air molecules like you have stated. It can, in fact, take *more* than one hit without smoking. I would suggest learning how the vehicle drives and try to not crash into things. No action needs to be taken regarding this issue.
