### ISSUE TITLE
Hummer H2

### ISSUE THREAD

**Issue by LPLips7** [fkk-cz/noire_vehicles#1663]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

Was looking to buy the Hummer H2
I've gone to the LS Cutoms in test drive and noticed you can't change the Wheels, Wheel Colour, Window Tint, And can only add Turbo as a performance upgrade

### Expected Behavior

See if the Kit for the vehicle can be fixed...

### Steps To Reproduce

Fix all the upgrades

### Anything else?

Nope- Thanks.

**Comment by okxeon** [comment]
This vehicle has no included ``carcols.meta`` and or ``carvariations.meta`` files. This will result in no body mods being available and there is no fix for this.
