### ISSUE TITLE
bugatti veyron

### ISSUE THREAD

**Issue by AkumaCx** [fkk-cz/noire_vehicles#1669]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

The bugatti veyron has a bug where when you go to repair the vehicle when opening the hood in the front (which is supposed to be the trunk cuz the engine is in the back) there is a second hood under the first one 

### Expected Behavior

Would be great to have more attention to detail with getting rid of that second random hood glitch in the front. As well as making cars that have the engine in the back and trunks in the front be actually usable trunk spaces as it makes sense to be able to have access to a trunk when there is one in the front of your vehicle rather than it saying the vehicle has no working trunk. Also if possible have your player repair the vehicle from the back side since that’s where the engine is located (If that’s too difficult then it’s not that big of a deal) 

### Anything else?

No

**Comment by Artificial-IQ** [comment]
This is something the model creator should have done. Sorry for the inconvenience. Have a nice day.
