### ISSUE TITLE
2022 M5 Competition CS

### ISSUE THREAD

**Issue by b1ds4** [fkk-cz/noire_vehicles#1674]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

The car goes 150 MPH flat, and yes I am well aware that you have nerfed all the vehicles but a 7 thousand pound track hawk shouldn't accelerate and have a higher top speed than my m5.

### Expected Behavior

I would expect the M5 CS to be a way faster car than a track hawk. '

### Steps To Reproduce

Nerf the trackhawk and a lot of SUVs to where they should be.

Buff M5 CS to 155-160 Flat.

### Anything else?

.

**Comment by FARQ3X** [comment]
+1000 SUVs are overpowered while supercars and supercar fast sedans are slow.

**Comment by fkk-cz** [comment]
Increasing the speed from 150 to 160 only represents a 6% increase. This is not worth considering as adjusting vehicle top speeds can be difficult and not as precise as you might think. We generally only consider adjusting speeds when there is a clear error and the vehicle is significantly underperforming its intended values.
