### ISSUE TITLE
Hummer H6

### ISSUE THREAD

**Issue by LPLips7** [fkk-cz/noire_vehicles#1675]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

Its not so much an issue... But is there a reason the Hummer H6 is 457k?... Just wondering as it isn't drive by compatible, doesn't go very fast, and only holds 4 people... Does it being 11k Pounds in weight have to do with it?

### Expected Behavior

Just a question was curious thats all.

### Steps To Reproduce

..

### Anything else?

nope. Just a question

**Comment by fkk-cz** [comment]
It's a rather large vehicle that could potentially be abused if the vehicle is easily affordable.
