### ISSUE TITLE
2018 Dodge Charger Police Surplus

### ISSUE THREAD

**Issue by IIcey77** [fkk-cz/noire_vehicles#1677]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

This vehicle when originally added in was amazing. It would get up to around 150-155 in a decent amount of time, and if on a longggg straight eventually 175ish. Although now 155 seems to be right around its max. This normally wouldn't be an issue but the vehicle does cost $200k, which is a lil unrealistic to begin with. For a non-hellcat Charger for that price its a bit steep, but its old performance made up for it, not so much anymore. 

### Expected Behavior

Speed Buff

### Anything else?

N/A

**Comment by fkk-cz** [comment]
This vehicle is supposed to have the standard 375hp V8 engine (or maybe even the V6). 155 is more than fair, the vehicle is priced at 200k to prevent everyone from driving around in one. As a result, no changes will be made to this vehicle at this time.
