### ISSUE TITLE
Honda nsx 2017

### ISSUE THREAD

**Issue by AlexBishop1112** [fkk-cz/noire_vehicles#168]
only goes 120 please make it go alot faster

**Comment by fkk-cz** [comment]
https://github.com/fkk-cz/noire_vehicles/commit/81e3b4b322252fef0fba9b964fd6f40cd589d45a#diff-3ef702ca0ec15dee59cfd6cd6d0b4d3a6cb1f6154c052a81d0dde952f83a0d35
