### ISSUE TITLE
McLaren 765LT 

### ISSUE THREAD

**Issue by FARQ3X** [fkk-cz/noire_vehicles#1680]
### Is there an existing issue for this?
The car is fine, Was hoping to request an audio change if possible, 720s, 675LT etc all have a nice custom sound while this got that Zentorno noise. Also the Senna, which is a track car, aka should handle corners much better, is faster in a straight line. The 765LT is by far McLarens fastest straight line vehicle, beating even a P1 ever so slightly.... Wouldn't mind if it got a tiny boost considering the Senna which is far slower than a P1, is MUCH faster than it. The Senna costs more IRL too yet its slower in straight line because it is much more capable in corners. The Top speed is fine, car goes 165-170 flat at most tho.

### Expected Behavior

Eh I would love it to sound like the 720s and be just a tad bit faster considering it is the fastest McLaren in pure straight line speed.

### Steps To Reproduce

Engine Rev and GTA sounds come out, Race a Maserati Gran Turismo GT/Senna and get embarassed in a car that should be faster.

### Anything else?

Nope

**Comment by Competent1** [comment]
The engine audio has been swapped here https://github.com/fkk-cz/noire_vehicles/commit/ea62700e45597f555ee44c37e810f755beb37891 Wait for it to be merged.

**Comment by FARQ3X** [comment]
Thanks a million!
