### ISSUE TITLE
2020 Koenigsegg Jesko

### ISSUE THREAD

**Issue by LPLips7** [fkk-cz/noire_vehicles#1681]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

Nothing is wrong with the car, just simply requesting an Audio Hash swap...

### Expected Behavior

I would like to see if the audio for the jesko can be swapped to the audio on the 2020 Bugatti Chiron Pur Sport. Was looking for more of a BRR then a VRR sound and found it on the pur sport..

### Steps To Reproduce

Swap the Audio hash on jesko to the audio hash on Bugatti Chiron Pur sport.... 

### Anything else?

Nope, and thank you!

**Comment by Competent1** [comment]
It has been discussed that certain expensive vehicles have their own exclusive audio that won't be applied to other vehicles. The Pur Sport is an example of this. This request is not planned for now.
