### ISSUE TITLE
2022 BMW M5 Competition 

### ISSUE THREAD

**Issue by FertileSphere** [fkk-cz/noire_vehicles#1682]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

Current Audio hash is way to loud compared to other vehicles, I have audio set to lower the engine fx but even then its still too loud. I Would like to request a Audio hash swap. The 2021 Alfa Romeo Gulia GTam has a less invasive sound but keeps to the style of engine in the car. 

### Expected Behavior

Audio hash swap.

### Steps To Reproduce

Nil

### Anything else?

nil

**Comment by FARQ3X** [comment]
BMWs 4.4 V8 in the F90 is notorious for being loud, especially when tuned.

**Comment by FertileSphere** [comment]
> BMWs 4.4 V8 in the F90 is notorious for being loud, especially when tuned.

I get that but I don't want my eardrums blown out while trying to hear my passenger.

**Comment by FARQ3X** [comment]
>True, Ive found all custom engine sounds to be loud so have my SFX down low when people speak, you could fix it in settings that background noise goes much lower when someone speaks! The Car sounds glorious, be a shame to lose that noise!

**Comment by Competent1** [comment]
After review of the request you have submitted regarding the audio of the 2022 BMW M5 Competition, this request will not be pursued further and the engine audio changing is not planned at this moment in time. Sorry for any inconveniences that this may cause and thank you for your understanding.
