### ISSUE TITLE
1964 Chevrolet Impala SS[

### ISSUE THREAD

**Issue by FARQ3X** [fkk-cz/noire_vehicles#1684]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

Eh car is very prone to flipping but its fine outside of that. I was hoping to ask can you guys add Hydraulics somehow? The 64 Impala is probably the most iconic lowrider, would be sick to see that shit jump :D

### Expected Behavior

No issues tbh except it liking to flip over.

### Steps To Reproduce

Zoom thru vinewood hills at 30mph watch it flip.

### Anything else?

Nope would be sick to see a 64 Impala on hydraulics tho

**Comment by Competent1** [comment]
I tested this vehicle in Vinewood Hills and did many, many barrel rolls so I can see what you were talking about here. I made a slight adjustment here https://github.com/fkk-cz/noire_vehicles/commit/b37e9fbc9d01290a5e15deb6891b29a2c8d570c0 and after this adjustment, I wasn't able to flip it over once. I got close a couple of times when full sending at speeds of over 65+ mph, so it still is possible (intended by the way). The initial issue here is definitely not as bad and should be manageable now. Sorry for the long wait and thanks for submitting this GitHub issue. If you think this vehicle and/or other vehicles have issues that need to be tested upon, be sure to submit another request.
