### ISSUE TITLE
Ford Crown Victoria (Taxi variant) 

### ISSUE THREAD

**Issue by radoncombe** [fkk-cz/noire_vehicles#1685]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

Current sound (vanilla gamefiles) doesn't really feel right with the Crown Vic.. 

Doesn't sound like that V8 engine like it would have.

### Expected Behavior

Looking for a more unique sound for both the stock version and Taxi version. 

### Steps To Reproduce

https://www.gta5-mods.com/vehicles/ford-crown-victoria-4-6-modular-v8-engine-sound-oiv-add-on-fivem-sound

Sounds from this mod replacing current Taxi/stock Crown Victoria engine sfx.

### Anything else?

Nothing else to request.. Thanks for checking this out.

**Comment by fkk-cz** [comment]
https://github.com/fkk-cz/noire_vehicles/commit/42e8d0138ce31433162e45db02b0c23ece98f285 replaces the audio hash for the civilian version with the one found in most police vehicles. Also fixed a long standing handling issue where engine braking was disabled which led to a weird feeling when driving around.
