### ISSUE TITLE
McLaren 765LT and others!

### ISSUE THREAD

**Issue by FARQ3X** [fkk-cz/noire_vehicles#1692]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

The McLaren 765LT is extremely underpowered on launch, top speed is ok, nothing special but could use a small buff there too.
Aston Martin DB11 needs a heavy nerf. it is a car that does 0-60MPH in 4 seconds irl and yet it smokes the 765LT.
Aston Martin Vanquish Zagato needs a heavy nerf, it is a luxury coupe yet performs like a Bugatti. McLaren MP4-12C would outperform both Astons irl.
Ferrari 458 Prior needs a nerf, it is a car that does 0-60 in 3.2 Seconds irl and yet it smokes the 765LT too.
McLaren 720s is balanced but its launch is the same as a 765LT irl. Yet here it is MUCH MUCH faster. It is a car that is MUCH slower than 765LT in 1/4 mile.
McLaren 600LT is balanced but needs a nerf in acceleration, it has no right to keep up with a 720s/765LT.
McLaren Senna needs a nerf, it should be slower than a 720s yet smokes every car on this list.
Agera RS could use a buff on acceleration, and a slight one on top speed, it gets smoked by DB11 which is a low performance luxury coupe comparatively.
Bugatti Chiron SS 300 is slower than Pur Sport lmao how? the Pur Sport will not be close in straight line, its advantage is track Aero.
Corvette C7 Z06 is slower than base model.
Venom GT could use a buff on on acceleration, it gets smoked by DB11 which is a low performance luxury coupe comparatively. 
Porsche Carrera GT (there is 2 for some reason) needs a nerf it outperforms the Agera and Venom. 
Porsche Panamera Turbo S (Idk why its called S. completely diff cars.) needs a buff, it should perform on F90 level.
All 3 F90 BMWs could use a buff on top speed by approx 10 MPH IMO.
BMW M3 GTR needs a big nerf. It is a track car, not a top speed monster.
BMW 850CSi hits ridiculous flat ground speeds for an old luxury coupe.
Ford Everest needs a nerf, it is faster than a Trackhawk currently.
Mercedes G Wagon 2022 needs a nerf, it is faster than a Trackhawk currently.
R32 Skyline needs a nerf, it outperforms a lot of cars stock it has no business being close to.
Nissan Titan needs a weight nerf lmao, currently used as battering ram against heavier*IRL* vehicles.

### Expected Behavior

I'll update as it goes along. I am not being prejudiced here, I am basing performance on what it should be not price,

https://fastestlaps.com/create-comparison *Good tool for comparison*

### Steps To Reproduce

Drive these cars, compare performance and u will see lack of balance.

### Anything else?

https://www.youtube.com/watch?v=AIT4gMy-DIw
https://www.youtube.com/watch?v=9e0Pnqs7yTU

http://www.dragtimes.com/half-mile-times.php

**Comment by LPLips7** [comment]
If someone pays 4.76 million for a car its gonna uphold to its price...

**Comment by FARQ3X** [comment]
> If someone pays 4.76 million for a car its gonna uphold to its price...

Not going back to this. Price has nothing to do with performance. The 300SS isnt going to turn like the Pur Sport, just be better in straight line.

**Comment by LPLips7** [comment]
So besides the fact that its not irl and its a game... 
I recently bought the Audi RS6 and its probably ONE of the BEST purchases I have made for a 4 door. I'm NGL that thing is still yet to be nerfed, I've hit 150 going flat, I think 130 flat would be fair for it. The F90 M5 is an awesome car just the wheel spin at the start is annoying... I think the handling on both vehicles is pretty fair..

**Comment by FARQ3X** [comment]
> So besides the fact that its not irl and its a game... I recently bought the Audi RS6 and its probably ONE of the BEST purchases I have made for a 4 door. I'm NGL that thing is still yet to be nerfed, I've hit 150 going flat, I think 130 flat would be fair for it. The F90 M5 is an awesome car just the wheel spin at the start is annoying... I think the handling on both vehicles is pretty fair..

Agreed handling is more than fair, RS6 has realistic handling, as does the F90 M5 however nerfing the RS6 that far down is counterproductive tbh, then it falls in line with SUVs which it should slightly outperform on the top end. And it means having to nerf down 70-80% of Sedans it should perform in line with, the F90 M5 is simply underpowered and needs a small buff to put it closer to Charger Daytona(Best handling file along with RS6 imo, both should be templates as they demonstrate 2 most popular platforms AKA VW/Audis Engine in front of front wheels causing understeer and BMW/Merc/Dodges "Gap of Luxury" causing oversteer with engine weight being on front wheels.) as most other sedans fall into the 145-155 Category.  As said in Discord by myself. *RS6 has great handling in the fact it understeers like it does IRL, but its faster in straight line than M5.* The being faster in straight line is simply wrong, outside of that I do agree the car is spot on.

**Comment by FARQ3X** [comment]
Lambo Urus needs a nerf and handling swap preferably to RS6 just a little slower. Currently its a RWD Vehicle somehow, and its way too fast for a MLB Evo platform *Bentley Bentayga, Audi Q7/8, Cayenne, Touareg* It needs a nerf. Its wheels are BEHIND the engine, hence causing understeer but very solid handling. Exactly same idea as RS6 just taller and bigger. Same engine too.

**Comment by FARQ3X** [comment]
So what ur saying is a Lambo Urus should be outperforming an M5/Trackhawk when it is an MLB Evo platform vehicle? Not only this its somehow RWD. The vehicle needs a nerf. I own the vehicle,just like I own multiple vehicles on the list and I can happily admit it is overpowered. 155-160MPH on a flat... in a car that is slower than a trackhawk? Certainly slower than RS6, and definitely should handle like the RS6, being that its a VW platform, as explained above. Please stay out of here if you are just looking for an argument. So far your arguments haven't been based on how a car is built or car knowledge but how much u like a car.

**Comment by okxeon** [comment]
https://github.com/fkk-cz/noire_vehicles/commit/fa1ae831eebe5ea7c633b445438e6067224fafde. Buffed the acceleration of the 765lt but significantly nerfed the top end. For $382,500 that car should not have been hitting 190-200 mph regularly...

**Comment by okxeon** [comment]
For the mp412c the top end has been improved to be about equal to the 720s https://github.com/fkk-cz/noire_vehicles/commit/bc799466044afa76190a71db9bab2c868d497f0f.

**Comment by okxeon** [comment]
Reduced the 600lt acceleration slightly https://github.com/fkk-cz/noire_vehicles/commit/eb2be84dd965ad0f420c6c2ca3ed15c7c3eb55ed.

**Comment by okxeon** [comment]
The Agera RS got an acceleration buff as well as a top speed buff https://github.com/fkk-cz/noire_vehicles/commit/66ba55c4c0b6ae383b637bb2a9b23b27adca87ab.

**Comment by FARQ3X** [comment]
Good work! I have a few more written out somewhere, will send in full list in a bit, Shame these are getting applied after I have left.

**Comment by Competent1** [comment]
The Senna will not be getting adjusted at this time, it will not be going slower than the 720s. Same goes to the Bugatti Pur Sport vs Chiron SS 300.

**Comment by FARQ3X** [comment]
I gave a performance comparison, I understand price plays a factor for the city as to not make cars too common or "Meta"

**Comment by okxeon** [comment]
The c7z06 got an acceleration / slight top end buff, also changed swapped its audio hash to the same one used by the c7.

**Comment by Competent1** [comment]
The BMW M3 GTR was also adjusted a couple of weeks ago and the 850csi was adjusted last week.

**Comment by Competent1** [comment]
The Everest was also adjusted 2 weeks ago.

**Comment by FARQ3X** [comment]
> The BMW M3 GTR was also adjusted a couple of weeks ago and the 850csi was adjusted last week.

yes I have watched the feed closely, vehicles were a big point of interest for me.

**Comment by Competent1** [comment]
The adjustments here have been complete. Wait for these adjustments to be merged. The others we haven't mentioned won't be adjusted. Have a good one and thanks for bringing these to our attention.
