### ISSUE TITLE
bugatti veyron vitesse super

### ISSUE THREAD

**Issue by PoppaHapps** [fkk-cz/noire_vehicles#1694]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

Slides a bit to much with no upgraded suspension and if you do upgrade the suspension it slide a lot more. sometimes when drift the car spins right out and does a 360.

### Expected Behavior

to not slide around as much as it does now and no more doing 360 when trying to drift 

### Anything else?

nothing else wrong with the car

**Comment by FARQ3X** [comment]
It is a 1000HP+ AWD top speed machine, if you are going to try drift an AWD vehicle you should know that a handbrake with no throttle is the only way to do so. If you put power to front wheels, the cars front will pull, hence making drifting impossible.

**Comment by Competent1** [comment]
This has been adjusted here https://github.com/fkk-cz/noire_vehicles/commit/bbc80daf330bf8bedf582db535039665a462e52f . If there are further issues after this, do make another GitHub on it and more testing can be done.
