### ISSUE TITLE
2012 Cadillac Escalade 

### ISSUE THREAD

**Issue by damnonion** [fkk-cz/noire_vehicles#1695]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

super bad handling for a a top tier suv 

### Expected Behavior

make it easier to turn the escalade it handles like a trash master 

### Steps To Reproduce

1. improve handling 

### Anything else?

pls help

**Comment by FARQ3X** [comment]
While I love the Escalade with all my heart, it is a big heavy body on frame vehicle and its handling reflects it.

**Comment by fkk-cz** [comment]
https://github.com/fkk-cz/noire_vehicles/commit/433d09421ffb2ff62a690126ff740ef9991e9672 fixes this issue. Traction values were _extremely_ low, which most likely led to the vehicle understeering on any turn over a reasonable amount of speed.
