### ISSUE TITLE
2020 Mercedes-Benz AMG GT Black Series Buff Top speed and acceleration and no sound from the car and cant take off camo of the paint of the car

### ISSUE THREAD

**Issue by JaegerPop** [fkk-cz/noire_vehicles#170]
No sound from exhaust and honking, extremely poor acceleration and top speed is way too low for this type of car

**Comment by ZacLuxton** [comment]
I've just checked this, the exhaust of this vehicle sounds fine, so does the handling of it. To fix the camo, go to LS Customs, then go to stickers, and use up and down arrows, and that should take the sticker off
