### ISSUE TITLE
2020 Audi RS6 Avant

### ISSUE THREAD

**Issue by Jerryes000** [fkk-cz/noire_vehicles#1700]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

the doors arent working propperly always, like i cant get in and almost all the time when someone is on the driver seat others cant get in and sometimes the car wont let me sit to the driver seat but passenger seat.

### Expected Behavior

it should work like all the other cars 

### Anything else?

https://medal.tv/games/gta-v/clips/12adzhgFXVNJwh/d13375IYqsbz?invite=cr-MSxla2UsMTU1ODI2ODY3LA  

https://medal.tv/games/gta-v/clips/12aeEUpIraXPW1/d1337DC0BeKz?invite=cr-MSx0SFIsMTU1ODI2ODY3LA

**Comment by Idk-maybe** [comment]
This issue should be resolved with the last merge listed above
