### ISSUE TITLE
Aston Martin Valkyrie

### ISSUE THREAD

**Issue by iiiTmaa** [fkk-cz/noire_vehicles#1703]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

Soo im gonna get the valkyrie as my car but when i test drive it it only goes 133mph  top speed everything else is good about the car. For a car for 3mil its really bad and slow and irl it goes 220mph. Thats pretty fast compared to 133mph

### Expected Behavior

i would like the car too get a speed buff since 133mph is slow for a 3 mil car.  Idk how much but it should atleast hit around 200 mph

### Anything else?

https://www.caranddriver.com/aston-martin/valkyrie

**Comment by fkk-cz** [comment]
https://github.com/fkk-cz/noire_vehicles/commit/35538ca89ec5072fd0d0547a4bc66670e5eabda5 fixes the extremely low top speed of this vehicle. `fInitialDriveMaxFlatVel` was previously set to 165.0, which implies a top speed of 135.3 MPH -- fairly close to the number you provided.
