### ISSUE TITLE
More Drive - By Compatible Vehicles

### ISSUE THREAD

**Issue by LPLips7** [fkk-cz/noire_vehicles#1704]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

I thought it would be a good idea to create a list of Vehicles I believe you should be able to do drive - by's in... 

### Expected Behavior

Here are some of the vehicles-
Hummer H6
Mercedes-Benz G63 AMG 6x6
Mercedes-Benz AMG W140 S600
BMW E60 M5
2021 Ford Bronko Wildtrak
2021 BMW X7
2014 Chevrolet Tahoe (Non - Supporter)
Volvo XC90 (Non - Supporter)
2003 Ford F-350 Super Duty
2016 Chevrolet Suburban
2107 Rolls Royce Wraith (Maybe)
2019 Aston Martin DBX

### Steps To Reproduce

Up to the staff team, but hopefully add these Vehicles to the Drive - By Compatible list

### Anything else?

Most of the Vehicles are larger 4 seaters / 4 doors, with large windows, and space, Therefore I think they would make good Drive by Vehicles.  Especially all 6x6 in game i think should be Drive - By compatible considering there size...

**Comment by fkk-cz** [comment]
Added drive-by compatibility for a few of these vehicles. https://github.com/fkk-cz/noire_vehicles/commit/59f4f29b116692f13505c21ccca93887dded4808

Some of the ones you listed above don't make sense as drive-by vehicles or are oversized and need to be recalled.

**Comment by LPLips7** [comment]
Big man you're the goat much appreciated!!!
