### ISSUE TITLE
2013 Aston Martin Vantage 

### ISSUE THREAD

**Issue by Casidrew** [fkk-cz/noire_vehicles#1707]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

It’s current speed caps at 155 and the price should be increased.

### Expected Behavior

Any possible way if increasing speed to 170mph and price increase of 80k would be great. It has a v12 engine 

### Steps To Reproduce

Increase speed 

### Anything else?

N/a

**Comment by Competent1** [comment]
Thank you for submitting a GitHub issue on the Vantage. After testing, this vehicle does not need further tweaking. It will also not be getting a price increase.
