### ISSUE TITLE
1999 Nissan Skyline GTR Audio swap

### ISSUE THREAD

**Issue by Ell34** [fkk-cz/noire_vehicles#1708]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

Is it possible to put the no year nissan skyline gtr (70k one) sound on this car?

### Expected Behavior

sound nicee

### Steps To Reproduce

n/a

### Anything else?

no

**Comment by Idk-maybe** [comment]
Swapped the audio here - https://github.com/fkk-cz/noire_vehicles/pull/1709/commits/c852689d0bd2f954d7a5520518932a8b6f8d8799
Wait for the change to be merged live
