### ISSUE TITLE
Mustang GT Color

### ISSUE THREAD

**Issue by c0sm0th3gr34t** [fkk-cz/noire_vehicles#171]
I've noticed the Mustang GT whenever I put it in the garage and take it out, it doesn't save the pearlescent paint i have on it.  I always remembers the black primary paint, but never the pearlescent part. It normally comes out red pearlescent but i've seen it come out orange and blue pearlescent before too.  So whenever this happens i just have to go back to the los santos customs and change it back to the color i want it to be, Lime.  Is this a known thing with all cars or is it just me?
EDIT: It also sounds pretty quiet so maybe the sound being turned up a little bit would be nice

**Comment by fkk-cz** [comment]
pearlescent paint has always caused issues, I would recommend sticking with primary/secondary paint only

>  EDIT: It also sounds pretty quiet so maybe the sound being turned up a little bit would be nice
https://github.com/fkk-cz/noire_vehicles/blob/6df7812acf5a3920a2eb2475df7bc11a5d59b007/DATA/mgt/vehicles.meta#L18
it uses the tornado audioHash, do you have a better suggestion?

**Comment by DankGrandma** [comment]
how does the forgt50020 sound? that uses musv8

**Comment by ZacLuxton** [comment]
https://github.com/fkk-cz/noire_vehicles/pull/418/commits/6b2d519be396bbdb80c8bbba119db0c685bc6527

Should be a little bit louder and aggressive
