### ISSUE TITLE
Jaguar E-Type 

### ISSUE THREAD

**Issue by ghost** [fkk-cz/noire_vehicles#1711]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

From specific angles of the camera, the bootlid window and the c-pillar windows will render and double-sided and non-transparent.

### Expected Behavior

Full transparency for all windows, including those mentioned above

### Steps To Reproduce

Angle your camera towards the right rear side of the car and move it around, the windows will become transparent to opaque, then flicker back when you've changed your camera angle

### Anything else?

I sold my E-type 1 month ago, if I still had it I would show you what I meant through images and so on..

**Comment by Artificial-IQ** [comment]
This is an issue caused by the model creator of the vehicle and cannot be changed. Have a nice day.
