### ISSUE TITLE
[2014 Dodge Charger SRT]

### ISSUE THREAD

**Issue by Unwashedarc** [fkk-cz/noire_vehicles#1712]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

The car is good overall, the speed/acceleration is good and the handling is also good. But it cannot do drive bys. the 2020 hellcat and the 2018 police charger are both drive by compatible but this one is not.

### Expected Behavior

Make the vehicle drive by compatible.

### Steps To Reproduce

1. Get into the charger as a passenger
2. try to do a drive by

### Anything else?

No

**Comment by Artificial-IQ** [comment]
Fixed here https://github.com/fkk-cz/noire_vehicles/commit/6bbeb642ed249ccc86866a84c554157f7ffbc8d6 Please wait for this to go live.
