### ISSUE TITLE
Nissan Skyline 2000 GT-R

### ISSUE THREAD

**Issue by ghost** [fkk-cz/noire_vehicles#1715]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

**Handling:**

- Sloshes from one side to another. Lowering the suspension does make this effect slightly less worse, but stiffens the suspension and makes it even harder to corner

- Braking is poorly. At high speeds, or maybe 80-90, tap the brakes and you will slide forwards (quite a distance). ??Probably tuned for drifting or to simulate no ABS?? Still presents an issue...

**Customization**

- The stock part, such as the front bumper, rear bumper, exhaust, will not be replaced. It only clips with the new part. 

**Front Bumpers. They will clip through the front stock bumper.**
**Oil coolers, they will clip through the front grille and stock bumper.** 
**Exhaust. It will clip through the stock  exhaust (except for the side exhaust option, of course.)**
 
 Of course, this car also has custom arches, and the wheels don't line up with those parts, but that's a whole different issue with no solution (from what I've heard)
 
 So far those areas seem to be the issues for this car.

### Expected Behavior

The handling should be re-tuned to where it is slightly more drive-able in its current state. Brakes, slightly stronger

The stock parts should disappear once you've chosen to replace it with a new custom one at LSC.

### Steps To Reproduce

Drive the car around after you buy it or even test drive it.

As for customization: Try to install a new part. You may notice the stock one will not disappear, only to stay there.

### Anything else?

Further media will be provided upon request

**Comment by Artificial-IQ** [comment]
Thank you for submitting this GitHub issue on the Nissan Skyline 2000 GT-R. At this time, this vehicle is fine in its current state and will not be tweaked. Have a nice day.
