### ISSUE TITLE
Lamborghini Centenario LP 770-4

### ISSUE THREAD

**Issue by Marco1738** [fkk-cz/noire_vehicles#1716]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

I cannot no matter what i try change the interior color of the car, i have tried liveries, secondary color, addons, you name it. but i also see that there isnt even an option to change interior color.

### Expected Behavior

please add an interior color option in the respray section so other people like myself wont have an issue with it anymore. or tell me if there already is a section for it (because i cant find it)

### Steps To Reproduce

1. Add interior color option to respray section

### Anything else?

no

**Comment by Idk-maybe** [comment]
Unfortunately this is a model issue and nothing that we can fix. This would've been something the mod creator did when making the vehicle
