### ISSUE TITLE
Nissan Skyline GT-R

### ISSUE THREAD

**Issue by RileyRamirezz** [fkk-cz/noire_vehicles#1720]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

So all of a sudden this skyline has stickers all over it not how i bought it or how i want it and im not able to remove it from the vehicle

### Expected Behavior

i would like the stickers to be removed completly if there wont be an option to have or not have it on the vehicle

### Anything else?

-

**Comment by Ell34** [comment]
cmon it's for the homie paul

**Comment by Competent1** [comment]
There are no plans at this moment in time to remove the livery that is on this vehicle.
