### ISSUE TITLE
2018 pagani Huayra roadster

### ISSUE THREAD

**Issue by Casidrew** [fkk-cz/noire_vehicles#1721]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

This car is maxes at 185 and with horrible handling. The price is not worth for the performance 

### Expected Behavior

Increase speed to 200+ with better handling 

### Steps To Reproduce

N/a

### Anything else?

N/a

**Comment by LPLips7** [comment]
Did you buy it or just test drive it?

**Comment by Casidrew** [comment]
Test drove it with upgrades

**Comment by LPLips7** [comment]
SO you're telling me you managed to upgrade it fully then take it on the highway? In 60 Seconds???

**Comment by Idk-maybe** [comment]
I can personally say that this car does not need buffed, this is one of the vehicles that was not yet hit with QOL Adjustments. This car will not be tweeked

**Comment by LPLips7** [comment]
Will it be hit with QOL Adjustments though...? I feel like the car's performance matches the price....    ?
