### ISSUE TITLE
2017 Ford GT

### ISSUE THREAD

**Issue by LKEEZY** [fkk-cz/noire_vehicles#1723]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

I would like to have the audio file switched since the current sound, sounds like a subaru.Subaru

### Expected Behavior

Have the audio hopefully sound more acurrate.accurate

### Anything else?
https://www.gta5-mods.com/vehicles/ford-gt-ecoboost-3-5-v6-engine-sound-oiv-add-on-fivem-sound

**Comment by fkk-cz** [comment]
Added in https://github.com/fkk-cz/noire_vehicles/commit/ed38b4bd670555273cd6e5d679fce020685eaa7b.
