### ISSUE TITLE
2005 Mercedes-Benz SLR McLaren super 

### ISSUE THREAD

**Issue by recruit2212** [fkk-cz/noire_vehicles#1724]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

The car is general is nice but the sound isn't the greatest so it would be nice to add the same sound from the 2005 Mercedes SL55 v8 to this Mercedes SLR of the same era 

### Expected Behavior

Sound like the v8 that comes on these irl 

### Steps To Reproduce

N/A

### Anything else?

N/A

**Comment by No-Yes1** [comment]
Audio hash has been updated to reflect the same as the 2005 Mercedes SL55 - https://github.com/fkk-cz/noire_vehicles/commit/9d388f01cc3bcc95a22f3b3a18fb4670f0929dae
