### ISSUE TITLE
2012 Mercedes-Benz C63 AMG sports 

### ISSUE THREAD

**Issue by recruit2212** [fkk-cz/noire_vehicles#1725]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

Overall the car is good but the sound lets it down abit.
Ive found a exact engine file sound which should work 
https://www.gta5-mods.com/vehicles/mercedes-amg-63-m177-v8-engine-sound-oiv-add-on-fivem

### Expected Behavior

Sound like its irl counterpart 

### Steps To Reproduce

n/a

### Anything else?

n/a

**Comment by Artificial-IQ** [comment]
The audio hash for this vehicle will stay as is at the moment. Have a nice day.
