### ISSUE TITLE
RIME GalaxyRoamer RV

### ISSUE THREAD

**Issue by Plasre** [fkk-cz/noire_vehicles#1726]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

The car is fuel powered at the moment and it needs fuel, also only 2 of the 5 seats work.

### Expected Behavior

The rv has solar panels on the top of it and no exhaust pipes, so therefore its an eletrical vehicle so it shouldnt need gas, and instead run of of electricity, also only 2 of the 5 seats in the bus are actualy usable.  

### Steps To Reproduce

1. Buy an RV.
2. See that it has solar panels and no exhaust pipes and also spot that it needs fuel.
3. For the seats get a bus and try to get more than 2 people to enter it and sit down.

### Anything else?

.

**Comment by radoncombe** [comment]
The solar panels are just there to provide energy for the living accommodations

The terrorbyte in vanilla has solar panels.. Doesn't make it an electric truck, right?

**Comment by Idk-maybe** [comment]
Refer to what's stated above, the solar panels are there to provide energy for the accommodations for living. An RV of that size wouldn't be fully electric like you're requesting. This vehicle will remain gas and not be made electric
