### ISSUE TITLE
AMG

### ISSUE THREAD

**Issue by Brandon2191** [fkk-cz/noire_vehicles#173]
Audio completely bugged. No sound whatsoever coming from engine or vehicle period, unable to even use the radio

**Comment by fkk-cz** [comment]
> 
> 
> Audio completely bugged. No sound whatsoever coming from engine or vehicle period, unable to even use the radio

which one?

**Comment by Brandon2191** [comment]
lol yall on top of it over there fsho fsho..

________________________________

**Comment by Brandon2191** [comment]
very confused as to why Im perm banned btw lmao. I didnt know I wasnt allowed to go in another city ahaha.

________________________________

**Comment by ZacLuxton** [comment]
This isn't exactly the place for it, just closing it since you never responded originally, don't even know who you are
