### ISSUE TITLE
Ford GT40

### ISSUE THREAD

**Issue by sailboat76** [fkk-cz/noire_vehicles#1732]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

The car costs almost 800k at pdm and has no customizations. It also has no upgrades. Because of this the car is quite slow, only topping out around 160 on the highway. It looks good and has a nice sound but is somewhat underwhelming for what the car is. 

I'm not sure if it's just how the file for the car is in the game but it would be really nice if it would look at perform like the top of the line sports car it is. 

### Expected Behavior

Looking for either a top end increase in speed (15-20mph) or a possibility to customize the car and or upgrade it in Benny's. 

### Steps To Reproduce

1. Test the car in the test city
2. Modify the top end speed/ add customizations
3. Save the day

### Anything else?

no

**Comment by fkk-cz** [comment]
Modkit didn't match up correctly, that's probably why there were no upgrades. https://github.com/fkk-cz/noire_vehicles/commit/12148aabdbcce10170e9bea437d86a37b51544b0

**Comment by Competent1** [comment]
Issue has been resolved.
