### ISSUE TITLE
[Exact name of vehicle, as displayed in game]: 

### ISSUE THREAD

**Issue by clicky79** [fkk-cz/noire_vehicles#1734]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

Honda s2000 rear fenders hit box wider than model causing the rear end to hit things that you shouldn't.  

### Expected Behavior

the s2000 rear trackwidth and front are the same with the same size tire so you should be able to pass thru anything the front end passes.

### Steps To Reproduce

drive the Honda s2000 and squeezy through something 

### Anything else?

..

**Comment by Artificial-IQ** [comment]
This issue is caused by the model creator and cannot be fixed. Have a nice day.
