### ISSUE TITLE
[2019 lamborghini Aventador SVJ]: 

### ISSUE THREAD

**Issue by Sevenr7** [fkk-cz/noire_vehicles#1738]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

hi guys im here to talk about the lambo Svj 2019 
So the top speed is ok also the dmg it takes to get wrecked is fine too but the only thing it needs a lil touch on the handling since its a weak car i think it should have a lil better handling for a 1.5 mill car 

### Expected Behavior

expecting the handling gets better a bit just to avoid the small dmgs taking when turning

### Steps To Reproduce

not sure what to put here

### Anything else?

also not sure what to put here

**Comment by fkk-cz** [comment]
[Handling values](https://github.com/fkk-cz/noire_vehicles/blob/master/DATA/svj63_data/handling.meta) look fine. No adjustments will be made to this vehicle.
