### ISSUE TITLE
Ford GT 2017

### ISSUE THREAD

**Issue by baranhorc** [fkk-cz/noire_vehicles#1740]
### Is there an existing issue for this?

- [x] I have searched the existing issues

### Current Behavior

In my ford gt, i am doing like 175 mph on flat but all of a sudden, it starts to slow down on the last gear. 

### Expected Behavior

it should protect its speed that its supposed to go or go faster a little bit

### Steps To Reproduce

1. idk remove the last gear?
2. Or maybe make the last gear longer
3. Also i think this car should go a bit faster like 180-185
### Anything else?

thats it

**Comment by fkk-cz** [comment]
I was unable to recreate this when driving the vehicle fully upgraded. 175 mph is fair given the price point.
