### ISSUE TITLE
2023 Lamborghini Revuelto

### ISSUE THREAD

**Issue by Ell34** [fkk-cz/noire_vehicles#1741]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

Its an electric car but sounds like the aventador. The acceleration from 0-100 is insanely slow. I swear a crown vic accelerates faster and the handling is off. Once you're over 130 you're not turning 

### Expected Behavior

Be a decent car

### Steps To Reproduce

Test drive car

### Anything else?

no

**Comment by Competent1** [comment]
I believe this vehicle was just added not too long ago. Changes to the files have not been made yet. This will be worked on as soon as are we able to, thanks for being patient.

**Comment by fkk-cz** [comment]
https://www.youtube.com/watch?v=YPRn7dCfMac

This vehicle isn't supposed to be completely silent. What is the point of driving a supercar if you can't even hear the scream of a V12 engine?

**Comment by Ell34** [comment]
> https://www.youtube.com/watch?v=YPRn7dCfMac
> 
> This vehicle isn't supposed to be completely silent. What is the point of driving a supercar if you can't even hear the scream of a V12 engine?

Hey man I'm not familiar with lambos

**Comment by radoncombe** [comment]
> Hey man I'm not familiar with lambos

the Revuelto shares engines with the previous/current gen Aventadors, Centenario, Sian  

the electric motors only provide power... Not supposed to sound like a Prius

**Comment by Casidrew** [comment]
Whatever was done to the handling and speed made the car soo much worse, any chance of correcting this? Handling got worse and speed dropped heavy

**Comment by Casidrew** [comment]
> I believe this vehicle was just added not too long ago. Changes to the files have not been made yet. This will be worked on as soon as are we able to, thanks for being patient.

Hey it just got change so horribly. No handling and speed is so bad for 2.5 mil

**Comment by Casidrew** [comment]
I own the car and god it's a waste from what it was before

**Comment by Ell34** [comment]
I don’t know why you expected the car to stay at being able to do 230, especially since the quality of life adjustments happen

**Comment by Casidrew** [comment]
Have you used a svj or jesko? They hit that speed at 1.5 and 2 mil price point. But not to mention when you drive the car is on ice. 0 grip

**Comment by h4423** [comment]
Nah.

**Comment by phxsec** [comment]
fixed in https://github.com/fkk-cz/noire_vehicles/commit/6b3793e2bded0a9e549944a8d93d1f5ed92027f3

**Comment by Casidrew** [comment]
> fixed in https://github.com/fkk-cz/noire_vehicles/commit/6b3793e2bded0a9e549944a8d93d1f5ed92027f3

Sweet I'll try it out on restart

**Comment by Casidrew** [comment]
> fixed in https://github.com/fkk-cz/noire_vehicles/commit/6b3793e2bded0a9e549944a8d93d1f5ed92027f3

Tries the car out and no change has happened just horrible handling and speed

**Comment by phxsec** [comment]
fixed it https://github.com/fkk-cz/noire_vehicles/pull/1747/commits/61f6d8ffd084da61533e8b3e087561f7edbdce89

**Comment by Casidrew** [comment]
> retweaked/fixed it https://github.com/fkk-cz/noire_vehicles/pull/1747/commits/61f6d8ffd084da61533e8b3e087561f7edbdce89

Tested car again and max speed is still 164 mph and little handling

**Comment by phxsec** [comment]
handling was fixed, not going to change the top speed. the driveability of the car is fine now. the car already accelerates fast enough to it's top speed. again, stated many times in the past is that cars $ amount don't dictate the top speed.

**Comment by Casidrew** [comment]
> handling was fixed, not going to change the top speed. the driveability of the car is fine now. the car already accelerates fast enough to it's top speed. again, stated many times in the past is that cars $ amount don't dictate the top speed. the top speed was tested on a flat surface, not on a highway. so therefore you essentially could go faster if hitting downhills.

I don't feel any difference on launch the handling was changed and regarding top speed I would think not because of the amount of money spent on the car related to speed. Just based on the actual top speed of the car, for example this car top speed is 217mph while the lambo svj is 215 mph. But in city it's completely different. Svj goes 200+ while revuelto stuck at 163.

**Comment by phxsec** [comment]
> I don't feel any difference on launch the handling was changed and regarding top speed I would think not because of the amount of money spent on the car related to speed. Just based on the actual top speed of the car, for example this car top speed is 217mph while the lambo svj is 215 mph. But in city it's completely different. Svj goes 200+ while revuelto stuck at 163.

the handling on launched was changed to prevent from spinning tires to much causing drivability issues (so that's fixed, so not sure what issues you're having with handling still). it's a 1 gear car due to it being hybrid/electric so it already has no limitations on acceleration (besides what drag % it has set), and no the car will not go 215. (will look into the SVJ and tweak if needed). i'll consider possibly changing top speed from 164 to 175/180 but that's pushing it considering the car accelerates from 0-140 in like 3 seconds. also previously stated before and in the past is that IRL speeds of a car are all based off of (perfect driving conditions, track orientated upgrades, skilled/trained drivers, and weather/road surfaces).

**Comment by Casidrew** [comment]
> It has already been established that cars in city won't match their IRL speeds, some cars in city do 300 mph IRL. I don't see why you keep comparing vehicles speeds in city to IRL.

Did a comparison to show cars in city and doesn't explain the difference in speed.

**Comment by Casidrew** [comment]
> > I don't feel any difference on launch the handling was changed and regarding top speed I would think not because of the amount of money spent on the car related to speed. Just based on the actual top speed of the car, for example this car top speed is 217mph while the lambo svj is 215 mph. But in city it's completely different. Svj goes 200+ while revuelto stuck at 163.
> 
> the handling on launched was changed to prevent from spinning tires to much causing drivability issues (so that's fixed, so not sure what issues you're having with handling still). it's a 1 gear car due to it being hybrid/electric so it already has no limitations on acceleration (besides what drag % it has set), and no the car will not go 215. (will look into the SVJ and tweak if needed). i'll consider possibly changing top speed from 164 to 175/180 but that's pushing it considering the car accelerates from 0-140 in like 3 seconds. also previously stated before and in the past is that IRL speeds of a car are all based off of (perfect driving conditions, track orientated upgrades, skilled/trained drivers, and weather/road surfaces).


I understand the reason for these balance changes and the reason behind it. Just because a car accelerates faster than other shouldn't drop a cars top speed from 230 to 163 god dam. I would say having its top speed changed to 200 and leaving its handling as is a good spot for it. Goes fast but doesn't turn well just like most cars should be. Regarding all the wheel spin at the start I'm still having it, do you want me to summit a video or something? Just doesn't seems fixed. Again I appreciate the honest feed back just trying to have this car feel worth having. Thank you

**Comment by Competent1** [comment]
Seems the latest tweak isn't implemented yet. I just tested this vehicle after the most recent tweak adjustments and it is much better. I believe whatever handling issue you were experiencing before will no longer be an issue once it is implemented.

**Comment by Casidrew** [comment]
> Seems the latest tweak isn't implemented yet. I just tested this vehicle with the most recent tweak adjustments and it is much better. I believe whatever handling issue you were experiencing before will no longer be an issue once it is implemented. 

I love the handling change and it helps a lot. I've been testing more and this car does not keep up with many cars in its class. If you can please increase the speed to 200 range so that it can keep up.

**Comment by Competent1** [comment]
This vehicle will not be going to the 200 mph range like you have requested. Refer to the messages above from @phxsec regarding the top speed of the vehicle.

**Comment by Casidrew** [comment]
> This vehicle will not be going to the 200 mph range like you have requested. Refer to the messages above from @phxsec regarding the top speed of the vehicle.

Okay well I thought I'll try higher than what @phxsec said.  Any chance we can do the 180 mph so that it can keep up? Because it's can't atm, well only for 7 secs till other cars catch it.

**Comment by phxsec** [comment]
> Okay well I thought I'll try higher than what @phxsec said. Any chance we can do the 180 mph so that it can keep up? Because it's can't atm, well only for 7 secs till other cars catch it.

"Keep up"?? the car literally accelerates fast enough, around 0-120/130 in like 3/4 seconds. it out performs a LOT of its class right off the line given that its 1. Electric (so the torque is insane) and 2. Drag/Weight (the car is fairly light).
The car will stay at its current handling specs.
