### ISSUE TITLE
2019 Aston Martin Vantage

### ISSUE THREAD

**Issue by ghost** [fkk-cz/noire_vehicles#1742]
### Is there an existing issue for this?

- [X] #1757

### Current Behavior

- Currently shares V12 audio with Jaguar XJ220 / Aston Martin Vanquish. 

- Quite loud

- Has V8 irl

### Expected Behavior

Sound close to IRL (V8 engine)

### Steps To Reproduce

Test drive the car

### Anything else?

N/A

**Comment by No-Yes1** [comment]
Do you have a current sound in mind that's already in-game?

**Comment by Artificial-IQ** [comment]
We will not be changing the audio at this time. Have a nice day.
