### ISSUE TITLE
r34 gtr

### ISSUE THREAD

**Issue by dinmamma100** [fkk-cz/noire_vehicles#1743]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

i really wanna buy
 the r34 gtr but when i test drive it even with upgrades it only tops at about 120 which i think is fine for the price but i also dont understand why its only 70k 

### Expected Behavior

i think it should cost more (maybe like 250-350k) and top out at like 150-160. that would make the car way more appealing and irl it goes 156mph STOCK.  

### Steps To Reproduce

increase price or add a similar model with higher price
increase top speed or add another similar model with higher speed

### Anything else?

i think its pretty weird to add a car for way cheaper than it is in real life and also make it slower than it is in real life, its like adding a buggati chiron for 500k and make it go 170 when you could just make it a fair price and a fair speed

**Comment by dinmamma100** [comment]
its called nissan skyline GT-R ingame not r34 sorry

**Comment by phxsec** [comment]
A lot of the vehicles are not identical to IRL speeds, therefore we can make the vehicles slightly cheaper/slower for the players who want the vehicle (for looks, ofc) but do not want to spend a hefty amount of coin for it. Would definitely consider your alternative of adding in a different model/form (Skyline GT-R) but 25-30 MPH faster (fully upgraded) and a bigger price change.

**Comment by Competent1** [comment]
Refer to what was said above. This vehicle will not be getting a price adjustment just so it can have faster speeds. Like you've said, the vehicle at the moment is fair for the price.
