### ISSUE TITLE
Lamborghini Centenario LP 770-4

### ISSUE THREAD

**Issue by IIcey77** [fkk-cz/noire_vehicles#1746]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

I believe while trying to fix the Reveulto the sound for the Centenario may have been swapped accidentally. 

Not only does it now sound like an RC Car but it also has no idle sound as if it were hybrid.

### Expected Behavior

Restore the old sound of the Centenario.

### Anything else?

N/A

**Comment by phxsec** [comment]
The sound of the (Lamborghini Centenario LP 770-4) sounds just like the (Lamborghini Aventador S)

i don't see the issue here.

**Comment by IIcey77** [comment]
maybe mine was bugged last night? not sure, all good now sorry!

**Comment by Competent1** [comment]
I was going to say, the audio for this video has not been tweaked/adjusted. Glad you are still enjoying your vehicle and that everything is all good.
