### ISSUE TITLE
458 Prior designe sound.

### ISSUE THREAD

**Issue by BlizzWizz** [fkk-cz/noire_vehicles#175]
https://www.gta5-mods.com/vehicles/complete-car-sound-pack 

Here is a pack with a lot of car sound. The 458 is one of them but if posible make it louder when you add it. :)

**Comment by fkk-cz** [comment]
> 
> 
> https://www.gta5-mods.com/vehicles/complete-car-sound-pack
> 
> Here is a pack with a lot of car sound. The 458 is one of them but if posible make it louder when you add it. :)

Unfortunately these are for SP, I need the .awcs and nametables for FiveM
