### ISSUE TITLE
2023 RAM 1500 TRX 

### ISSUE THREAD

**Issue by IIcey77** [fkk-cz/noire_vehicles#1750]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

The sound of this vehicle in city compared to real life isn’t very accurate, i found one that’s as close you can get. The other issue i don’t care much for but could definitely be changed is making it a little faster, considering it has a hellcat engine, and it’s current price, i think 125-126 top speed could be bumped up to around what the current non supporter Demon is, which i believe is around 150-160. 

### Expected Behavior

Sound changed to the one linked below, and speed buff if possible, maybe 145-150 flat.

### Anything else?

https://www.gta5-mods.com/vehicles/dodge-challenger-hellcat-redeye-v8-sound-mod-sp-add-on-fivem

**Comment by Competent1** [comment]
Thank you for submitting this issue on the 2023 Ram 1500 TRX. The audio hash for this vehicle has been adjusted here https://github.com/fkk-cz/noire_vehicles/commit/8c6604f320d4caaa66048a5bcc33526832d6ecbb. After testing, this vehicle will not be getting a speed buff as requested. Please wait for the sound adjustment/tweak to be merged.
