### ISSUE TITLE
[Exact name of vehicle, as displayed in game]: Bugatti Chiron

### ISSUE THREAD

**Issue by Rakeem21** [fkk-cz/noire_vehicles#1751]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

I feel this car is not worthy of 2.4 million based on its performance. It is a bit too slow or handles not well enough. I had the SVJ before this which is 1.4mil and it is faster, yet that couldn't handle just as well but for a whole million extra, the bugatti chiron should be better than it is currently.

### Expected Behavior

For the handling, at very low speeds it is pretty good but then at some point the turning doesn't feel like it helps alot, which is the same with all the cars at high speeds but for this it's more significant because since it is slower than other cars, I think it should have something else be better like for instance braking power or turning power or something. 

### Anything else?

none,thanks

**Comment by LPLips7** [comment]
Yea I've gone down this road before... Not a Road i'd go down again...

**Comment by Artificial-IQ** [comment]
I have tested this vehicle and it seems fine. I got it up to 180mph and the braking power and handling are where they should be in the vehicle's current state.
