### ISSUE TITLE
[Exact name of vehicle, as displayed in game]: Shelby GT500 Eleanor

### ISSUE THREAD

**Issue by SomeSweetName** [fkk-cz/noire_vehicles#1752]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

Car is great, but has zero upgrades, you cant change wheels, window tint or anything. also only has turbo for upgrade.

### Expected Behavior

would love to see engine and trans upgrades, and even armor. and would love to be able to customize the car.

### Anything else?

i would love to see this car get a rework so that i can finally enjoy it.

**Comment by No-Yes1** [comment]
Unfortunately, the vehicle creator has not added the ability for upgrades/customization's. Therefore, we would not able to add the ability for this vehicle to have upgrades.
