### ISSUE TITLE
[Exact name of vehicle, as displayed in game]: chrysler 300

### ISSUE THREAD

**Issue by Baker920** [fkk-cz/noire_vehicles#1756]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

The sound of this vehicle in city compared to real life isn’t very accurate, i found one that’s as close you can get.  and its a SRT so it makes sense that it sounds like an SRT not a normal car. 

### Expected Behavior

the sound to be changed to the link i put below

### Anything else?

https://www.gta5-mods.com/vehicles/chrysler-300c-srt-8-v8-sound-mod-sp-add-on-fivem#comments_tab

**Comment by Artificial-IQ** [comment]
The audio hash for this vehicle will currently not be changed. Have a nice day.
