### ISSUE TITLE
Zastava Yugo Skala 55 2-

### ISSUE THREAD

**Issue by Plasre** [fkk-cz/noire_vehicles#1784]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

The vehicle is very overpriced for what it was meant to be, currently in game it costs 107,302K dollars.

### Expected Behavior

In real life on the release of the vehicle in the uk it cost around 2400 pounds in the 1980s which with inflation today would cost around 10,279.05 pounds which equates to 12 995,55 dollars today, so i would like for the price of the vehicle be lower to at least under 30k, the car was meant to be an affordable family car, and because of the low price the manufacturers had to cut down on certain details of the vehicle making it less reliable and slower than the other cars made around its time. All of the information stated here can be found on Wikipedia linked below.

### Steps To Reproduce

1. Go to the dealership
2. Look at the price of the vehicle.

### Anything else?

https://en.wikipedia.org/wiki/Zastava_Skala

**Comment by Artificial-IQ** [comment]
Thank you for submitting this issue for the Zastava Yugo Skala 55 2. In response to your statements above, irl you don't make thousands of dollars for picking up trash for 50 seconds ... it's easier to make money here than irl, so, therefore, vehicles/items are more expensive to offset that difference. This vehicle's price will not be changed as it is fair for its current state. Have a nice day.
