### ISSUE TITLE
[issue]: <buff durability on crownvic>

### ISSUE THREAD

**Issue by Tayytayyy** [fkk-cz/noire_vehicles#1786]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

the durability on the crown vic is just too low for taxi drivers. we are driving for hours and a lot of times can't control the damage done to our cars, due to other people's bad driving.

### Expected Behavior

i'd like the crownvic to go back to what it's durability was before the change

### Steps To Reproduce

idk, just thought i'd try asking

### Anything else?

us taxi drivers rely on our cars as a part of our jobs, and it's just become a little harder to get our passengers to their destinations over the last two days; between using half our earnings on repairs, and having our cars simply dying at just the thought of getting sideswiped.

**Comment by fkk-cz** [comment]
https://github.com/fkk-cz/noire_vehicles/commit/a7446eaf20a5bc00135e60311b92a991be720cfe fixes this.

**Comment by Tayytayyy** [comment]
> Other people’s bad driving… Elvira was stopped going over 120 yesterday 😂

Shhhhh
