### ISSUE TITLE
2023 Ram 1500 TRX

### ISSUE THREAD

**Issue by Blurrr5** [fkk-cz/noire_vehicles#1787]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

The truck costs 347k and the fastest the truck goes on flat is 122mph. This truck needs to have a speed increase with how much it costs

### Expected Behavior

for the truck to get a speed buff

### Steps To Reproduce

1. make the truck faster

### Anything else?

no

**Comment by phxsec** [comment]
Price does NOT dictate speed/performance of vehicles. This has been talked/discussed about in the past, the vehicles 0-60 is 2.97secs and 0-100 in 8.02secs. Already plenty quick.

**Comment by Blurrr5** [comment]
yea its quick but it has a very low top speed i think if it was buffed about 130mph it would be more balanced

**Comment by phxsec** [comment]
you will not notice a 8-MPH speed increase.

**Comment by phxsec** [comment]
Also to add, this is taken from google (The top speed has also been throttled down to 118 mph (to help the truck cope with the power). The sprint to 0 to 60 mph blew by in 3.7 seconds, and the Ram revealed itself to be a surprisingly agile truck.) So the 0-60 from IRL is .73 seconds slower AND the top speed IRL is 118.

**Comment by Blurrr5** [comment]
what about the truck being unable to tow a trailer? is this something that could be tweaked?

**Comment by phxsec** [comment]
> what about the truck being unable to tow a trailer? is this something that could be tweaked?

probably not, due to it not having a tow-hitch.

**Comment by Artificial-IQ** [comment]
Thank you for submitting this issue for the 2023 Ram 1500 TRX. Price does not directly correlate with a vehicle's performance in all cases. Considering that this is a pickup truck with good performance in its current state, this vehicle will not be receiving a change. Have a nice day.
