### ISSUE TITLE
2018 Jaguar SV XE, Sports

### ISSUE THREAD

**Issue by Etched6477** [fkk-cz/noire_vehicles#1791]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

Vehicle is a 4 door but you can only have 2 people sit inside of it currently.

### Expected Behavior

Increase the vehicle capacity to fit 4 people.

### Steps To Reproduce

Spawn Vehicle & try to fit more then 2 people inside of it.

### Anything else?

Nothing else to add.

**Comment by No-Yes1** [comment]
This car is only a 2 seater due to the fact there is a rollbar in the back and no actual seats.

![image](https://github.com/fkk-cz/noire_vehicles/assets/79383480/03510f31-fd9c-4a17-a818-e3b71081acfd)

The vehicle will not be tweaked to allow it to be a four seater.
