### ISSUE TITLE
Porsche GT2 RS Topspeed

### ISSUE THREAD

**Issue by SuicideLeopard** [fkk-cz/noire_vehicles#180]
The acceleration and handling on the car are quite good. But the topspeed is only 155mph. The car costs nearly 400k i feel like it should get an upgrade. I think 200-205 would be appropriate.

**Comment by fkk-cz** [comment]
https://github.com/fkk-cz/noire_vehicles/commit/c0ebe7b2dd7bc038d0493f4e20b7de52b1fa69cf#diff-197be8255d27288ca779e675755d50d3fc64d6b6aea3d0cd0421dd8d57c597a7
