### ISSUE TITLE
Rimac 

### ISSUE THREAD

**Issue by cxerq** [fkk-cz/noire_vehicles#1800]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

When you slightly go off road you lose full control of the car, I understand that the car isnt made for off road, But if you just accidently swerve and go off you cant control it or break, Also it seems to get destroyed reallly fast now. 

### Expected Behavior

Be able to control more when you go off road, and maybe make it not destroy as quick (Mostly the off road those)

### Steps To Reproduce

Just try drive the rimac slightly off road and you will see

### Anything else?

I am not sure when this change seemed to happen, cause i checked the change logs and cant seem to see any changes

**Comment by Competent1** [comment]
The changes weren't made specifically to this vehicle. The off-road/damage factors were applied to all vehicles as a whole. No changes will be made at this time to this vehicle.
