### ISSUE TITLE
Ferrari Fxxk

### ISSUE THREAD

**Issue by Gohennn** [fkk-cz/noire_vehicles#1801]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

Was looking at changing the audio on the Fxxk, reason for wanting the change is that is pretty loud, and feel like it could be changed to something better.

### Expected Behavior

Was wanting the audio of the Fxxk to be changed to the same as the 2015 Ferrari LaFerrari which is already in-game if that is possible. Much more quiet and the sounds overall are just better.  

### Steps To Reproduce

N/A

### Anything else?

N/A

**Comment by No-Yes1** [comment]
Audio hash been been updated to reflect the 2015 LaFerrari - https://github.com/fkk-cz/noire_vehicles/commit/b210449e3f07e29189c27601e09dab7a83880950
