### ISSUE TITLE
[Exact name of vehicle, as displayed in game]: Mclaren P1

### ISSUE THREAD

**Issue by bigarabb** [fkk-cz/noire_vehicles#1803]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

I just bought the car for 750k and this thing is slow asl, idk how the senna which is a little cheaper can go faster than this thing, on top of that theres another mclaren called the f1 which is 949k and goes over 130 mph.

### Expected Behavior

increase the speed on the F1 and P1

### Steps To Reproduce

speed
speed
speed

### Anything else?

no

**Comment by Artificial-IQ** [comment]
Thank you for submitting this issue on the Mclaren P1 GTR and Mclaren F1. Both of these vehicles' top speed and acceleration have been adjusted. Refer to [18b5039](https://github.com/fkk-cz/noire_vehicles/commit/18b503961e1d8e260d0cff514c209449d452f5d2) and https://github.com/fkk-cz/noire_vehicles/commit/b64e40806a98fc6370cde0ed8e187f566ff5dcf4 Have a nice day!
