### ISSUE TITLE
Lamborghini Centenario LP 770-4

### ISSUE THREAD

**Issue by NickStuck** [fkk-cz/noire_vehicles#1806]
### Is there an existing issue for this?

- [ ] I have searched the existing issues

### Current Behavior

I have been collecting cars in the city now for over a year and had recently just purchased the Lamborghini Centenario LP 770-4 for 1.9 million. The car sounds/handles good, but its top speed is slow when compared to other vehicles not even close to its price range. For example, the McClaren Senna (715k) handles amazing and has a top speed of 180mph but is almost 1/3 the price of the Lambo. The top speed of the Lamborghini Centenario is 185mph which is only a 5-mile difference over a very big price gap.

### Expected Behavior

I expect the Lamborghini Centenario to be somewhere around the ballpark of its price competitors such as the Koenigsegg Jesko (2mil) which has a top speed of 210-215mph.

### Anything else?

There are various cars under 500k that easily reach speeds of 170-180mph and it's unfair to pay almost 2million dollars for a car that goes the same speed.

**Comment by Artificial-IQ** [comment]
Thank you for submitting this issue for the Lamborghini Centenario LP 770-4. After testing the jesko and lp770, these are my findings below. (added the fxxk just for an additional comparison)
Flat top speed: (does not take bumps into account / all vehicles are tested on the same, flat road)
Jesko - 186mph
LP770 - 183mph 
FXXK - 189mph 

Price does not directly correlate with speed in all cases. Nevertheless, after thorough testing and side-by-side stat comparison, this vehicle is where it should be in its current state. Have a nice day!
