### ISSUE TITLE
[Exact name of vehicle, as displayed in gamel]: lamborghini urus

### ISSUE THREAD

**Issue by Ermal182** [fkk-cz/noire_vehicles#1809]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

Lamborghini urus one of the fastest suvs in the world and its very slow in the city. When i mean slow its slower than a g wagon or a bmw

### Expected Behavior

I think it should be a bit faster like it can go 150 without upgrade 

### Anything else?

No

**Comment by Artificial-IQ** [comment]
Thank you for submitting this issue for the 2018 Lamborghini Urus. After testing with upgrades, this vehicle is where it should be in its current state. It is faster than the two vehicles you mentioned above (BMW x7 / AMG G63). This vehicle will not be changed. Have a nice day.
