### ISSUE TITLE
Chevrolet Corvette c7 z06 Top speed/Acceleration 

### ISSUE THREAD

**Issue by Jinxss06** [fkk-cz/noire_vehicles#181]
The top speed on the car is 120mph I thought after engine upgrades it’s be faster but it’s not even faster than my friends Honda S2000 (17k) and it gets beat off the line by pretty much any car by the time I’m up to 60mph the person I’m racing is in 70mph it’s also a Supporter car it’s 105,000$ too so the fact that a 17,000$ car is faster than it really upsets me

**Comment by fkk-cz** [comment]
https://github.com/fkk-cz/noire_vehicles/commit/c0ebe7b2dd7bc038d0493f4e20b7de52b1fa69cf#diff-e0648c8ef481988544c3aaf5f150471ded34492b87edb3b877fd564281e2e2dd
