### ISSUE TITLE
Rimac C2 needs fuel to move even though its electric

### ISSUE THREAD

**Issue by Trapp1** [fkk-cz/noire_vehicles#1815]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

Whenever I pull the Rimac out of the garage I need to fuel it up to move even though its electric

### Expected Behavior

For it to go back to being electric and not needing fuel 

### Steps To Reproduce

.

### Anything else?

.

**Comment by No-Yes1** [comment]
Merging this issue with an existing one - https://github.com/fkk-cz/noire_vehicles/issues/1814
