### ISSUE TITLE
2024 Hummer EV

### ISSUE THREAD

**Issue by Poochthebozz** [fkk-cz/noire_vehicles#1817]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

The Hummer is requiring to be refueled for some reason. I was also wondering if we could make this vehicle drive by compatible.  

### Expected Behavior

The hummer expected not to be refueled. 

### Steps To Reproduce

1. Drive the car till the fuel runs out.
2. Stand outside of it and look at it wondering how you're electric car ran out of gas.
3. Run to get a gas can and refuel it because it needs gas lol Or call DOT to tow your car lol

### Anything else?

If this vehicle could be made drive by compatible that would be cool.

**Comment by Poochthebozz** [comment]
![Screenshot 2023-07-25 164447](https://github.com/fkk-cz/noire_vehicles/assets/115928615/54864a92-81cf-4e85-abc9-8189e95aa785)
I was also looking into the EV and was wondering if these addons could be added?

**Comment by notJudgeTy** [comment]
If it’s possible, if it can go a little bit faster.  Not even that much maybe 10mph faster along with it being able to be electric power as it should be.

**Comment by notJudgeTy** [comment]
This to electric possible?? Checking in on it and possibly a little faster.

**Comment by MrThrawn** [comment]
Please fix this, I saved up to buy this and now am so saddened to see it needs gas, the electric aspect is why I thought it was worth 410k.  :(

**Comment by MrThrawn** [comment]
This ticket is 3 months old - R.I.P.

**Comment by Artificial-IQ** [comment]
duplicate issue of https://github.com/fkk-cz/noire_vehicles/issues/1814
