### ISSUE TITLE
BMW M8

### ISSUE THREAD

**Issue by boy711** [fkk-cz/noire_vehicles#182]
I really love this car, can you add more wheels. add more customize for this car and please make the car sound abit aggressive and more pop and flames please.

**Comment by fkk-cz** [comment]
https://github.com/fkk-cz/noire_vehicles/commit/358ab33382806dd89e17aabd25903c2c4109ca3e#diff-0eca9f756769dfff49961b25af9a0414f1e122e0ff983511c02b18a7de228a16

let's see if this fixes it, not sure what modKit IDs are valid or not

**Comment by fkk-cz** [comment]
https://github.com/fkk-cz/noire_vehicles/commit/358ab33382806dd89e17aabd25903c2c4109ca3e#diff-0eca9f756769dfff49961b25af9a0414f1e122e0ff983511c02b18a7de228a16

fixed, looks like there's no cosmetic upgrades on this one
