### ISSUE TITLE
[Exact name of vehicle, as displayed in game]: 2008 Chevrolet Suburban

### ISSUE THREAD

**Issue by MrGibbster** [fkk-cz/noire_vehicles#1820]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

I paid $333,739 for this 2008 Chevrolet Suburban that shows in its gta 5 mods link " https://www.gta5-mods.com/vehicles/chevrolet-suburban-08-add-on-tuning " that it can tow trailers and also states it does but it does not. I can add a trailer hitch to it for $333 in the mod shop but when trying to connect to the small trailer, It zooms out when backing up to it and does not connect. I would appreciate it if I could use this 300 thousand-dollar SUV for what it's intended to do. Thank you!

### Expected Behavior

I expected when adding this 2008 Chevrolet Suburban in and paying $333,739 that I would be able to tow the small trailer with it as that's the reason why I requested it into the city. I wanted to haul cars with it.

### Steps To Reproduce

N/A

### Anything else?

I would really like it if I could use this to tow the small trailer in the city. Thank you all I appreciate your help!

**Comment by Artificial-IQ** [comment]
Fixed here https://github.com/fkk-cz/noire_vehicles/commit/20930ed11a0ba987d0bc7c76cb51c0e507750a7c Please wait for this to go live.
