### ISSUE TITLE
2022 Ford F450 Platinum

### ISSUE THREAD

**Issue by MrGibbster** [fkk-cz/noire_vehicles#1822]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

This 2022 Ford F450 Platinum that I paid $432,844 for doesn't include a tow hitch to tow "small trailer" and does not attach to this trailer or any trailer.

### Expected Behavior

I expected to be able to tow with this 2022 Ford F450 Platinum and hitch up to the "small trailer" to it. 

### Anything else?

I would be greatly apprecatied if I could use this Ford F450 Platinum as intended. Thank you very much.

**Comment by No-Yes1** [comment]
Added combability for the small trailer -- https://github.com/fkk-cz/noire_vehicles/commit/97362412387a1e6a4cbf492102acbad88452a919. Please wait for this to merge live.

**Comment by MrGibbster** [comment]
Thank you! You are the goat.

**Comment by MrGibbster** [comment]
when will this be live?
