### ISSUE TITLE
2020 audi rs7

### ISSUE THREAD

**Issue by Ermal182** [fkk-cz/noire_vehicles#1825]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

I think that car is not as fast as it should be, in irl its the fastest sedan.

### Expected Behavior

I think it should be a bit faster, my mercedes that is cheaper goes faster than the audi

### Anything else?

No.

**Comment by Artificial-IQ** [comment]
Thank you for submitting this issue for the 2020 Audi RS7. After testing and comparing this vehicle to other vehicles in its class, I have determined that it is perfectly fine. It is where it needs to be in its current state and will not be tweaked. Have a nice day.
