### ISSUE TITLE
devels sixteen

### ISSUE THREAD

**Issue by highfkyo** [fkk-cz/noire_vehicles#1828]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

the screen gets darker at night when your in the vehicle and its running with the lights on once you turn it off or turn the lights off the surronding area brightens back up

### Expected Behavior

for the surronding areas to not darken up makes it hard to drive at night cant see wel

### Steps To Reproduce

1.have devel sixteen
2.be in devel sixteen
3.have car and lights on
4.witness darkness

### Anything else?

nothing else to add just seeing if its possible to get it fixed iam assuming its the lights on the car that does it

**Comment by okxeon** [comment]
This is more than likely how the mod creator used lighting assets for the car. As far as I am aware there is no easy way to reduce the intensity of these lights, which is unfortunate as it does exactly as you said and washes out and darkens all other colors.

**Comment by highfkyo** [comment]
yeah i was just hoping there was something that could be done cause i know lights for cop cars and shit have been changed so was hoping that could be changed it makes the car undriveable at times at night you can see shit around

**Comment by Artificial-IQ** [comment]
Unfortunately after looking into this issue, this is how the model designer created the vehicle model and cannot be changed. Have a nice day.
