### ISSUE TITLE
Audi RS5 Liberty Walk

### ISSUE THREAD

**Issue by Omers5** [fkk-cz/noire_vehicles#183]
The car is pretty slow - Fully modded, car maxes out at 150. In real life, this car's top speed is 170+ stock. Also, really overpriced.. About 170k in-game compared to MSRP of about $80k.
I think the price is fine (cheaper than the non-supporter RS5) but should at least translate to a good top speed. Not sure what the non-supporter RS5's top speed is.
Just for reference - Macan (which is also a supporter car) costs 1/4th of the price, has more storage, and tops out about 40mph faster...

Also, it has a cargo carrier on the roof as an option, maybe a bump to the 400 storage capacity too?

**Comment by fkk-cz** [comment]
https://github.com/fkk-cz/noire_vehicles/commit/358ab33382806dd89e17aabd25903c2c4109ca3e#diff-2d6191658f30e45f594b0be7809bac8c73a568aadd533f891ae3219212d72079
https://github.com/fkk-cz/noire_vehicles/commit/358ab33382806dd89e17aabd25903c2c4109ca3e#diff-1a1a88ac962e00df63ae088771532c8fe1db3ea624106ff49a4e088a4ec473d1
