### ISSUE TITLE
Maserati Levante

### ISSUE THREAD

**Issue by shoozifroo** [fkk-cz/noire_vehicles#1830]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

- Trunk in real life, no trunk in the city. 
- the back doors can't open. when someone gets in the back they just step through the door/ glitch through it

### Expected Behavior

Trunk added 

Functioning backdoors

### Steps To Reproduce

1. Get in Maserati Levante 
2. Check that trunk doesn't work 
3. try to toggle back doors to see that you can't 

### Anything else?

N/a

**Comment by No-Yes1** [comment]
This is a model issue and can not be fixed.
