### ISSUE TITLE
Hummer Ev

### ISSUE THREAD

**Issue by Poochthebozz** [fkk-cz/noire_vehicles#1831]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

The vehicle requires to be fueled. 

### Expected Behavior

Not to be refueled 

### Steps To Reproduce

Drive the HummerEv till the fuel indicator goes to 0%
 

### Anything else?

No

**Comment by Poochthebozz** [comment]
Could we also make this vehicle drive by compatible?

**Comment by No-Yes1** [comment]
You already have an existing issue on this - merging with https://github.com/fkk-cz/noire_vehicles/issues/1817
