### ISSUE TITLE
Corvette ZR1 Demon Swap

### ISSUE THREAD

**Issue by Godlyah** [fkk-cz/noire_vehicles#1833]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

goes around 130-140mph

### Expected Behavior

to go at least 160-170 since its demon swap and the hellcat demon goes around that speed and its on a corvette body so it go faster

### Steps To Reproduce

just drive it around

### Anything else?

just drive around in the car

**Comment by Artificial-IQ** [comment]
Thank you for submitting an issue for the Corvette ZR1 Demon Swap. Please wait for the tweaks to merge here https://github.com/fkk-cz/noire_vehicles/commit/221fb4228281eb267c4615b7dad30954ac4177bc
