### ISSUE TITLE
2018 Ford Raptor

### ISSUE THREAD

**Issue by Blurrr5** [fkk-cz/noire_vehicles#1834]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

The 2018 Ford Raptor should be able to be drive by compatible

### Expected Behavior

To be able to drive by out of it

### Steps To Reproduce

1. Make it able to be drive by compatible
2. Do drive bys out of it 

### Anything else?

no

**Comment by fkk-cz** [comment]
This vehicle will not be drive-by compatible for layout reasons.
