### ISSUE TITLE
RX-7 needs another buff

### ISSUE THREAD

**Issue by Ahy-jason-todd** [fkk-cz/noire_vehicles#184]
Just make the rx7 like the nissian supporter gtr or the nsx  rx-7 cost more but really under performing if possible lighten the grip of the car as well doesn't turn at all the car needs a buff as a whole or make it the same as nsx or gtr

**Comment by fkk-cz** [comment]
https://github.com/fkk-cz/noire_vehicles/commit/358ab33382806dd89e17aabd25903c2c4109ca3e#diff-d42319c79302eb94f51a26e8d8d28fa9ff92c0f880a1f82b8446fc72cb4ad3eb
