### ISSUE TITLE
2009 Audi rs6 avant

### ISSUE THREAD

**Issue by dinmamma100** [fkk-cz/noire_vehicles#1840]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

the car costs 189,000 dollars and its so slow. the cars speed is equivalent to a 30-40k car. i honestly think if you test drive it you will agree. it also dosent have upgrades.

### Expected Behavior

i think the acceleration should be better and top speed should be better

### Steps To Reproduce

1. test drive car.
2. drive it around
3. test drive 40k car
4. see which feels faster

### Anything else?

no

**Comment by Competent1** [comment]
This vehicle was added 24 hours ago. Please be patient and wait for adjustments to be made to it once we are able to work on it.

**Comment by Artificial-IQ** [comment]
Fixed here https://github.com/fkk-cz/noire_vehicles/commit/cf8ca8506ce7e1d7b4a70db739e071cfaeb28b22 and https://github.com/fkk-cz/noire_vehicles/commit/eeb90a4dd6b13d01bbc1a241c2d1a7f2e83c19cc Please wait for this to go live.
