### ISSUE TITLE
Golf Cart

### ISSUE THREAD

**Issue by Etched6477** [fkk-cz/noire_vehicles#1841]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

Vehicle is currently able to only seat 2 people.

### Expected Behavior

Vehicle visibly can seat 6-8 people but I would expect to at least be able to seat 4 people in the golf cart.

### Steps To Reproduce

spawn car
try to sit more then 2 people in in it.

### Anything else?

Nothing else

**Comment by No-Yes1** [comment]
Refer to this issue - https://github.com/fkk-cz/noire_vehicles/issues/1272. We are unable to change the vehicle layout of the vehicle.
