### ISSUE TITLE
[Exact name of vehicle, as displayed in game]:  2012 Lamborghini Aventador LP700-4-

### ISSUE THREAD

**Issue by robertyyyyyy** [fkk-cz/noire_vehicles#1842]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

Im looking to purchase this vehicle though the handling needs to be tweaked, as this vehicle does cost $1.2 million I would expect the handling and breaking to be one of the better handling vehicles in the game. The turning radius is not the greatest. When you test drive the car and you take a corner decently hard where you should expect this type of vehicle to make that turn it just slides and crashes. The handling and breaking should be tweaked and upgraded to where it should be able to take corners considering it is an aventador and the price. It should be one of the better handling cars in the game. 

### Expected Behavior

I expected for this car to be one of the better handling and breaking cars in the game considering this is an aventador and has a price of $1.25 million. 

### Steps To Reproduce

Test out the cars before being added into the game. 

### Anything else?

Nothing else.

**Comment by Artificial-IQ** [comment]
https://github.com/fkk-cz/noire_vehicles/commit/d55aa2386471e20dadf5141a361776751595f6d1 fixes the brake force and includes some minor handling tweaks.
