### ISSUE TITLE
2022 Ford F450 Platinum

### ISSUE THREAD

**Issue by Bajwa93** [fkk-cz/noire_vehicles#1845]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

Truck cost 432,844 and top speed is 105

### Expected Behavior

Could top speed be increased a little bit roughly 130-140MPH?

### Steps To Reproduce

1. Buy vehicle
2. upgrade all specs on vehicle
3. drive vehicle

### Anything else?

Could it be drive-by compatible

**Comment by Artificial-IQ** [comment]
Thank you for submitting an issue for the 2022 Ford F450 Platinum. The F450 is a heavy truck that should not be having a high top speed. It is where it should be in its current state and will not be tweaked. Have a nice day.
