### ISSUE TITLE
[Exact name of vehicle, as di in game]: lamborghini huracan evo spider non supporter

### ISSUE THREAD

**Issue by Ermal182** [fkk-cz/noire_vehicles#1849]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

The car costs 1.1 m and it only goes 155-160
 My car that costs 200k goes faster than this

### Expected Behavior

This car should hit 180-190 with upgrades minimum if we look at the price

### Anything else?

No

**Comment by Artificial-IQ** [comment]
https://github.com/fkk-cz/noire_vehicles/commit/84715f06558eb1781ecd0f89b409a32a31444316 buffs the top speed. Please wait for this to go live.
