### ISSUE TITLE
Porsche Panamera is way too slow for the price and compared to IRL 

### ISSUE THREAD

**Issue by cxerq** [fkk-cz/noire_vehicles#185]
So I bought the Porsche Panamera and was expecting it to go atleast 180 ish and people have said it goes 190 but even with turbo it goes 135 MAX, havent seen it go any higher I think this needs to be fixed asap, and the car feels extremely heavy when turning like you need to slow down ALOT otherwise you will crash. But mostly the speed needs to be fixed!

**Comment by fkk-cz** [comment]
https://github.com/fkk-cz/noire_vehicles/commit/358ab33382806dd89e17aabd25903c2c4109ca3e#diff-142c107ea305582da931aeef5f00068253cf67e8dc31546c50594deb3d52fef0
