### ISSUE TITLE
Mitsubishi FTO GP sports 

### ISSUE THREAD

**Issue by recruit2212** [fkk-cz/noire_vehicles#1853]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

no engine upgrades or transmission upgrades available even though all the other performance upgrades can be put on this. 

### Expected Behavior

allow for transmission upgrades and engine upgrades since you can put all the other performance on it other than those two 

### Steps To Reproduce

n/a

### Anything else?

no sir

**Comment by Artificial-IQ** [comment]
Fixed here https://github.com/fkk-cz/noire_vehicles/commit/9fb5beaa8850173452d4f2c8b62cb3101cd9c28e and https://github.com/fkk-cz/noire_vehicles/commit/ba83f88ce5a99c5938dd44cd8e7827c309843005 Please wait for this to go live.
