### ISSUE TITLE
[Exact name of vehicle, as displayed in game]: 1958 Porsche 718 RSK

### ISSUE THREAD

**Issue by cottonhands** [fkk-cz/noire_vehicles#1855]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

![image](https://github.com/fkk-cz/noire_vehicles/assets/143256292/a321df67-64c1-4b40-b74c-acc91f01116d)

- Price is too high 

- Wrong vehicle name 

### Expected Behavior

- Rename to `1974 Porsche 911 Targa`

- Price less than $200,000 @ PDM

 

### Steps To Reproduce

- Drive to PDM 

- Scroll down in the supporter car section until you find `1958 Porsche 718 RSK`

- Success

- Panic

### Anything else?

Nothing else is wrong

**Comment by LPLips7** [comment]
💀

**Comment by fkk-cz** [comment]
Fixed on next reset.
