### ISSUE TITLE
Bugatti Pur Sport 

### ISSUE THREAD

**Issue by natenectar** [fkk-cz/noire_vehicles#1856]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

Just bringing this to you guys with low expectations because im pretty sure adding/changing anything to the car would require removing/adding a whole new script, anyways.. you can only change the primary color on the car, the secondary color stays the same, is there anyway we can make it so we can pick the secondary color? or if i found a script, would it be possible to bring in a few liveries for it? like i said, its not a huge issue, but from speaking to other owners of the car, we would all love if we had a few more options for it being such an expensive car, so just curious if there is any options here 

### Expected Behavior

i dont have any issues with the car what so ever, it would just be nice to have a few more options to customize with, and to see if anything was possible, from what all can actually be done to a car, and what can be added with no much issue on your part 

### Anything else?

nothing else, just kinda speaking up for the community of the owners of the Pur Sport, to see if anything could possibly be done

**Comment by Artificial-IQ** [comment]
Thank you for submitting this GitHub issue for the Bugatti Chiron Pur Sport. The vehicle model that is currently in-game will stay and we do not plan on replacing the model. Have a nice day.
