### ISSUE TITLE
Maserati MC 12 

### ISSUE THREAD

**Issue by natenectar** [fkk-cz/noire_vehicles#1858]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

I previously requested a "slight buff" for the car, was able to have a slight top end speed adjustment, it now matches perfectly with how the car would perform irl, i have no issues anymore with the top end of the car, or the audio, I am now requesting for a "slight" acceleration, and handling buff, just slowly requesting performance issues for the car, with it being 1.5m i am just trying to get it where it needs to be, As i stated previously im fairly certain i am a 1 of 1 owner, and understand this car isnt very popular because of the price, you can buy a cheaper car that is faster, but I initially purchased the car for visual appeal, car shows, and its more exciting in my opinion to own a car that nobody else has. Now the car goes 180-190 flat, downhill 205-215, the handling is mid level, it just needs to have the acceleration/handling tuned just a tad, and this will never leave my garage 

### Expected Behavior

as i stated above, this is my second request for the car, and have no issues other than it does deserve to have an acceleration and handling adjustment. In a straight line, this car just takes a bit to long to get to top end speed, for 1.5m and it being a "track car" i would think it should be performing best with handling, and acceleration, other than having a really high top end speed, with poor handling 

### Anything else?

thank you for taking the time to read this, and i appreciate what you guys do, have a great day

**Comment by Artificial-IQ** [comment]
Fixed this here https://github.com/fkk-cz/noire_vehicles/commit/b225d670d68938919d174018433c5cd31ca6c42e Please wait for the tweaks to go live. Have a nice day.
