### ISSUE TITLE
1990 Chevrolet Silverado 454ss

### ISSUE THREAD

**Issue by Undertive** [fkk-cz/noire_vehicles#1860]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

It doesn’t have upgrades like window tint, I can’t change rims , I can’t put armor suspension , brakes , I can’t change lights 

### Expected Behavior

I need that to be fixed cause I bought the pass for this vehicle and I can’t even fix it how I want 

### Anything else?

I have none but I game you guys can check it has no upgrades

**Comment by Artificial-IQ** [comment]
The vehicle model creator did not include carvariation and carcol metas for this vehicle causing the upgrades to be broken. Have a nice day.
