### ISSUE TITLE
2024 mustang dark horse

### ISSUE THREAD

**Issue by RDZeROo** [fkk-cz/noire_vehicles#1862]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

i feel the speed and handling of the dark horse is very bad 

### Expected Behavior

i would like the dark horse to at least go 140-150 with it being 300k and a little bit better handling 

### Steps To Reproduce

boost speed and handling 

### Anything else?

no

**Comment by Artificial-IQ** [comment]
Fixed here https://github.com/fkk-cz/noire_vehicles/commit/2b70dd6619648e99b01f197df1c440182283f18f Please wait for this to go live.
