### ISSUE TITLE
Non Supporter 350k Supra upgrade

### ISSUE THREAD

**Issue by notJudgeTy** [fkk-cz/noire_vehicles#1863]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

Little slow… not by a ton and for the type of car it is the handling And drifting could be better for it being a 350k speed/drift car 

### Expected Behavior

Little faster, better handling, better durability and just upgrades to make it 3x better than the 90k Supra. 

### Steps To Reproduce

Drive it and take fast turns. Slows down really slow into drifts and slow acceleration for what it is. 

### Anything else?

Thx for the help.

**Comment by Artificial-IQ** [comment]
Fixed here https://github.com/fkk-cz/noire_vehicles/commit/38a77a36e8b4e6ed76f655cf3edb5e3b9f2b07ee Please wait for this to go live.
