### ISSUE TITLE
[Exact name of vehicle, as displayed in game]: 2014 Lamborghini Huracan LB

### ISSUE THREAD

**Issue by gooperbooper** [fkk-cz/noire_vehicles#1865]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

The vehicle has a trunk compartment under the front hood of the car and the engine is in the back of the vehicle. When opening the trunk I still have to go to the back of the vehicle where the ENGINE is at and not the front of the vehicle where the TRUNK is at.

### Expected Behavior

Trunk should be in the front of the vehicle rather than the back of it where the engine is.

### Steps To Reproduce

1. Go to the back of the vehicle
2. Open the trunk

### Anything else?

Nope

**Comment by Artificial-IQ** [comment]
We unfortunately cannot fix this. The trunk placement is solely down by the model creator of the vehicle.
