### ISSUE TITLE
Subaru 22B STI

### ISSUE THREAD

**Issue by Shmenley** [fkk-cz/noire_vehicles#1867]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

Drives like a boat; difficult to turn and not agile as its younger brothers 

### Expected Behavior

Should drive similar to the Impreza, but faster and more agile since its the upgraded version of the 1998 Impreza. The speed is fine on it, though it could use a boost in my opinion, but the handling is not good at all since it has trouble taking turns in the city. Overall, for a legendary rally car, it should be able to corner very well. 

### Anything else?

https://www.youtube.com/watch?v=bS41Ymal0L0&ab_channel=CarHunters

I mean this car should have amazing handling nonetheless

**Comment by Artificial-IQ** [comment]
Fixed here https://github.com/fkk-cz/noire_vehicles/commit/95a17bd2bd445829a4d0adbc17ecf9988234deec Please wait for this to go live.
