### ISSUE TITLE
[Exact name of vehicle, as displayed in game]: 1993 Nissan Skyline GT-R, Price: $114,367

### ISSUE THREAD

**Issue by cottonhands** [fkk-cz/noire_vehicles#1868]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

Extremely horrid steering - causes snap oversteer at times, and instability under braking. 

The possible cause of this issue: 
**Current value of `fSteeringLock` for this vehicle is too high.** 

### Expected Behavior

Expected the vehicle not to: 

**- corner so sharply** 
**- nearly spin when minimal power is applied upon turns**
**- and feel twitchy every time you even get near to full lock**

I recommend a possible fix:

**Edit value of current `fSteeringLock`**
**to `<fSteeringLock value="22.000000" />`**
 
**This change will hopefully improve the handling of the vehicle, in a way - simulate the steering of the real car, and reduce the effects of the loose steering.** 
 

### Steps To Reproduce

Test drive the vehicle at PDM. 

### Anything else?

Nothing else, just this fix.

**Comment by Artificial-IQ** [comment]
Fixed here https://github.com/fkk-cz/noire_vehicles/commit/668ead42234fd3c1ec3d1b955ad04e1484d9008b Please wait for this to live.
