### ISSUE TITLE
Silvia 2002 not customizable

### ISSUE THREAD

**Issue by itsEaf1** [fkk-cz/noire_vehicles#187]
Hi, I just bought a Silvia 2002 at the dealership and went straight to customize it.. Only problem is that nothing seems to be working as of cosmetics and upgrades.. 

I think it needs a quick fix ! 

Thank you!

**Comment by fkk-cz** [comment]
https://github.com/fkk-cz/noire_vehicles/commit/2bf3d89fd9be3a59b5ae989a692e47f7118ceaa1#diff-c29dfc7190e2702dfa0602bfa60c2319c950d137986f6c3ae79d96d8ef84f7b5
