### ISSUE TITLE
2022 BMW M5 Competition

### ISSUE THREAD

**Issue by PatrickBUD** [fkk-cz/noire_vehicles#1871]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

I have been an owner of this car for quite some while and i feel like the vehicle underperforms in its current state. When comparing my 2022 BMW m5 Competition to the 2018 BMW f9 m5 there was no noticeable difference in the vehicles performances. I would appreciate if you can consider a decrease in time needed for the time the car needed to gain traction at low speeds as well as a slight buff to the vehicles acceleration. I feel as though this car being 4 years newer as well as being apart of the competition series should have a noticeable bump in performance from the 2018 BMW M5. Thank you!

### Expected Behavior

I feel as though the vehicle should perform slightly better than its 2018 counterpart. Thank you for the time and effort dedicated to this subject.

### Steps To Reproduce

N/A

### Anything else?

N/A

**Comment by Artificial-IQ** [comment]
Fixed here https://github.com/fkk-cz/noire_vehicles/commit/f8468d31ac4de29d414f396a5e597826c4017756 Please wait for this to go live.
