### ISSUE TITLE
1979 lincoln town car

### ISSUE THREAD

**Issue by OrangeBugatti** [fkk-cz/noire_vehicles#1874]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

 currently only a two seater but its a limo

### Expected Behavior

4-6 seats as its a limo type car

### Anything else?

n/a

**Comment by Artificial-IQ** [comment]
Thank you for submitting a GitHub issue for the 1979 Lincoln Town car. Unfortunately, the model designer made this vehicle a 2-seater and this cannot be modified. Have a nice day.
