### ISSUE TITLE
2018 Jeep Grand Cherokee Trackhawk

### ISSUE THREAD

**Issue by Ell34** [fkk-cz/noire_vehicles#1876]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

Vehicle already has terrible handling, add a passenger and you aren't turning any corners. 

### Expected Behavior

Make a turn properly

### Steps To Reproduce

1. Drive the car
2. Take a turn
3. Add a passenger 
4. Crash into a wall

### Anything else?

n/a

**Comment by Artificial-IQ** [comment]
Fixed here https://github.com/fkk-cz/noire_vehicles/commit/38fd057dc8b4e1f1ea55775aa321fa61b35d6b9b Please wait for this to go live.
