### ISSUE TITLE
Buggati Pur sport is ruined 

### ISSUE THREAD

**Issue by natenectar** [fkk-cz/noire_vehicles#1879]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

Why would the pursport get hit this hard? its terrible now, i know 3 people who is talking about selling it, all the owners are respectful and nobody abuses the car for all i know, for it to get hit this hard, top end speed lost 50-60mph, it burns out when you take off, the acceleration is horrible now, it doesn't grip like anything it did before.. for the people who grinded 2-3 months to save up for a 5 million dollar car, it should be performing better than anything in the city, now its on par with cars that cost 3 million dollars less than it, its so sad whats been done to it, to the point when we have to sell it now because its so terrible, we will take a 1.3 million dollar loss, please for the love of god, just put it back to its original specs

### Expected Behavior

i expect a Buggati pur sport to have a higher top end than 215 miles an hour, better handling, and acceleration.. ill say it again, its a 5 million dollar car, whats been done to it, is unfair to the people who grinded literal months to get this

### Anything else?

I have been been a diamond supporter, with an occasion plat supporter for almost a year now, i will always supported you guys and this city, but what you guys had done to this car, is literally heart breaking, since i have owned it, i have been nothing but respectful, and to my friends who own the car, we have all been respectful and appreciated what it is, this is a slap in the face for all the time, and grinding we have put in to buy this car, for it to be on par with cars now 3 million dollars cheaper than it, when none of us have done anything, for it to be hit this hard makes me want to give the car up, and take my loss, its a sad day for everyone who owns this car.. please for the love of god, realize how bad you have made it, and just change it back to its original specs like it deserves

**Comment by Artificial-IQ** [comment]
Thank you for submitting this GitHub issue for the Bugatti Chiron Pur Sport. To address some of your concerns, this vehicle never went through quality of life adjustments. When it was initially put in there weren't any balancing measures done. Unfortunately in this past couple of weeks there have been multiple people who have abused this vehicle. It was so good that it simply outperformed the $10.4 million 2015 Ferrari LaFerrari which should have never been the case. This vehicle is still better than the $3.5 million Bugatti Super Sport 300. Thorough testing was done on this vehicle to ensure it is fair for the community. You also gotta think about the fact that price doesn't always equal pure performance. Expensive vehicles are also bought for looks. 

The Pur Sport was so incredibly overpowered compared to any vehicle. This car could turn flawlessly at 220mph which could easily get abused. There were people stealing it and getting into chases they knew they would have an advantage in. To give you some context, this car had a fTractionCurveMin value of 5.0. No car ever has had this kind of grip with the combination of eye-opening speed.

To address the top speed concern, it was not touched at all. You can still hit 230mph with this car no problem. The acceleration is still at the top of its class and not comparable to $3 million cars as you mentioned. This vehicle has been looked at for a while and we determined this was the best move at this time. The Pur Sport will stay as is and will not be tweaked. It is the way it should have been from the beginning. Have a nice day.
