### ISSUE TITLE
Add more non supporter bikes please

### ISSUE THREAD

**Issue by RDZeROo** [fkk-cz/noire_vehicles#1885]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

Add more non supporter bikes please we need more motorcycles 

### Expected Behavior

add more  non supporter moto bikes

### Steps To Reproduce

please add more

### Anything else?

no

**Comment by Artificial-IQ** [comment]
The way to go about this would be for a gold supporter or higher to request the bikes through the vehicle requests channel in discord.
