### ISSUE TITLE
[Exact name of vehicle, as displayed in game]: lamborghini urus 2018

### ISSUE THREAD

**Issue by Ermal182** [fkk-cz/noire_vehicles#1887]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

The car is so bad in the sand and its and suv with 600 hp

### Expected Behavior

It should be a drive by and better in sand

### Steps To Reproduce

.

### Anything else?

No

**Comment by Artificial-IQ** [comment]
Thank you for submitting a GitHub issue for the 2018 Lamborghini Urus. The `<fTractionLossMult value="1.0" />` is perfectly fair as there are vehicles that have a value of `<fTractionLossMult value="3.0" />`. This is a luxury SUV and should not drive flawlessly through sand, dirt, and mud.

As for the driveby compatibility, `<layout>LAYOUT_DELTA_SUV</layout>` is the correct layout for it to be able to driveby.

The 2018 Urus is where it should be in its current state and will not be tweaked. Have a nice day.
