### ISSUE TITLE
[Hennessey Venom F5]: 

### ISSUE THREAD

**Issue by Blevins09** [fkk-cz/noire_vehicles#1888]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

I'm writing in hopes of having a car reworked/buffed. The Hennessey Venom F5 is a beautiful car that I've owned for a couple of months now, and I absolutely love it. However, I've noticed that the car lacks in performance when compared to other cars at a similar/lower price point. The top speed, traction, and handling pale in comparison to the $389k Lamborghini SC18, which I believe to be a well balanced car for its price.

### Expected Behavior

 I would truly appreciate it if you would look into the car and consider improving its performance, even if it's just a slight improvement. Thank you in advance for your consideration. 

### Anything else?

Nothing else to add

**Comment by Artificial-IQ** [comment]
Fixed here https://github.com/fkk-cz/noire_vehicles/commit/de091ca2f496aef787ae8d3ad71c000af2cd10e2 The top speed is fair for this car. Handling and brake force were adjusted slightly. Please wait for this to go live.
