### ISSUE TITLE
BMW M5 F90

### ISSUE THREAD

**Issue by Chicken171** [fkk-cz/noire_vehicles#189]
No upgrades on the car. Even window tint doesnt work. There is no different type of tires and changing the rim color doesn't work. There should be upgrades to atleast have armor or something because it is really weak, touch something and its broken. Also the cosmetics dont work as i said earlier, like the window tint etc.

**Comment by fkk-cz** [comment]
https://github.com/fkk-cz/noire_vehicles/commit/2f0c6034627398a078be116eb3c80d061c79b811#diff-a7ed7590275ec332959d0e6f5574a2bfd94b58ddc2dea50c11565e9388bf4ffb
