### ISSUE TITLE
[Exact name of vehicle, as displayed in game]: 2015 Ferrari 458 Speciale 

### ISSUE THREAD

**Issue by xpxyj** [fkk-cz/noire_vehicles#1890]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

This car got a huge nerf, Its just illogical to have a charger that costs 70k$ to keep up with a 1mil$ car. I find that stupid and sorry for my attitude just pissed.

### Expected Behavior

A balance for the car would be great.

### Anything else?

No

**Comment by Artificial-IQ** [comment]
Thank you for submitting a GitHub issue for the 2015 Ferrari 458 Speciale. To address your concerns, this vehicle never went through quality-of-life adjustments when all of the cars were tweaked. This change was needed and the car is much faster than the charger you brought up. The Ferrari 458 Speciale is where it should be in its current state and will not be tweaked.
