### ISSUE TITLE
1999 Dodge Viper Supporter Car Not Customizable 

### ISSUE THREAD

**Issue by santi1588** [fkk-cz/noire_vehicles#190]
My dodge viper lost all of its upgrades and cosmetics like the spoiler and the double lines. It  just happened today when i logged in. All my upgrades were gone so it is back to the stock version.

**Comment by fkk-cz** [comment]
https://github.com/fkk-cz/noire_vehicles/commit/2f0c6034627398a078be116eb3c80d061c79b811#diff-47bb5344a4f8eb735da1efb48d29d1712ba31c502bf466c7adc859c4ab529b42
