### ISSUE TITLE
[Exact name of vehicle, as displayed in game]: 2017 koenigsegg Agera RS

### ISSUE THREAD

**Issue by Ermal182** [fkk-cz/noire_vehicles#1900]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

Its to slow for its price and in irl its one of the fastest cars ever

### Expected Behavior

To make this car faster

### Anything else?

No

**Comment by Artificial-IQ** [comment]
Thank you for submitting a GitHub issue for the 2017 Koenigsegg Agera RS. The speed is perfectly fine in its current state and will not be tweaked.
