### ISSUE TITLE
BMW m5 competition

### ISSUE THREAD

**Issue by Etched6477** [fkk-cz/noire_vehicles#1902]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

The noise this car produces is terrible, it sounds like a 1992 honda civic with the exhaust cut off. Ideally I would hope the sound to be changed and/or lowered. I love this car but it gives me a headache everytime I drive it.

### Expected Behavior

Lower the noise the car makes/swap the engine audio

### Steps To Reproduce

Spawn the vehicle
Drive it
Go deaf
Turn off car

### Anything else?

Nothing else to add

**Comment by Artificial-IQ** [comment]
You would need to recommend an audio hash that's already in game. I feel as though the sound that the m5 competition currently has fits it pretty well.

**Comment by Artificial-IQ** [comment]
Closing this due to failure to respond. Have a nice day.
