### ISSUE TITLE
[Exact name of vehicle, as displayed in game]: mercedes gt63s 

### ISSUE THREAD

**Issue by Ermal182** [fkk-cz/noire_vehicles#1909]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

Its too slow for its price

### Expected Behavior

To be faster

### Anything else?

No

**Comment by Artificial-IQ** [comment]
Thank you for submitting a GitHub issue for the Mercedes GT63S. After testing, this vehicle is perfectly fine in its current state and will not be tweaked. Have a nice day.
