### ISSUE TITLE
2014 INFINITI Q50

### ISSUE THREAD

**Issue by Blazifyy** [fkk-cz/noire_vehicles#1910]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

The q50 not being a slider

### Expected Behavior

I know you guys said to make a list of suggestions for what cars to be sliders and i feel like the q50 would be a good slider vehicle fits the criteria for slider type vehicles in my opinion 

### Anything else?

Hopefully it becomes a slider

**Comment by Artificial-IQ** [comment]
Fixed here https://github.com/fkk-cz/noire_vehicles/commit/020342a63d6e65d67bc92ab2e3b060c938aa3769 Please wait for this to go live.
