### ISSUE TITLE
Porsche panamera Issue

### ISSUE THREAD

**Issue by cxerq** [fkk-cz/noire_vehicles#192]
The top speed of the Porsche Panamera is only 134MPH, And i seen the changed you added today for it, But doesnt look like they worked! The handling and stuff hasnt been improved either!

**Comment by fkk-cz** [comment]
You need to go into LS customs and remove all of your upgrades. For turbo, make sure you select **Turbo** first, then hit up arrow to switch back to **Default**, hit enter. That will remove the turbo on your car
