### ISSUE TITLE
My 1994 Supra (350k$) got smoked by a KIA Fortek

### ISSUE THREAD

**Issue by medonaldduck** [fkk-cz/noire_vehicles#1925]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

I raced a KIA Fortek with my 1994 Toyota Supra thats 350k$ at pdm and got smoked

### Expected Behavior

Theres a clip of it :

https://medal.tv/games/gta-v/clips/1BTSOfNoGS-GKK/d1337kudZEWu?invite=cr-MSx0aTIsMjAyNTY2MzMxLA

### Anything else?

https://medal.tv/games/gta-v/clips/1BTSOfNoGS-GKK/d1337kudZEWu?invite=cr-MSx0aTIsMjAyNTY2MzMxLA

**Comment by RollingDragon** [comment]
Maybe sell the supra and buy a new car

**Comment by medonaldduck** [comment]
> Maybe sell the supra and buy a new car

I mean im trynna keep it but its crazy how a 10k car is faster than a 350k car you know?

**Comment by Artificial-IQ** [comment]
This vehicle is where it should be in its current state and will not be tweaked.
