### ISSUE TITLE
[Exact name of vehicle, as displayed in game]: Ram TRX 

### ISSUE THREAD

**Issue by Bandoflock** [fkk-cz/noire_vehicles#1926]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

Paid a lot for it and it does only 120 and it is no longer a slider 

### Expected Behavior

Should do Atleast 150 and should most definitely be a slider 

### Steps To Reproduce

Make it a slider and a little buff to it 

### Anything else?

Plz n ty

**Comment by ImDead48** [comment]
Honestly it don’t need a speed buff yes 120-125 is a little slow. Yes the truck is 350K+ but the acceleration is the key of the vehicle. And I do agree on it should be “drive by compatible”. If anything on a “speed buff” could we have it go faster then 75mph off road? Nothing crazy like 100 more like 90mph or 85mph

**Comment by spliff808** [comment]
I agree, I think the truck is in a good state in term of speed/ handling/ acceleration, but I do agree with the off road speed, I purchased the truck in the hopes of being a decent prerunner but the speed hit when off-roading is very heavy which isn’t the most realistic, especially when LEO vehicle don’t take a speed hit on dirt

**Comment by Artificial-IQ** [comment]
This vehicle is where it should be in its current state and will not be tweaked.
