### ISSUE TITLE
Nissan gtr acceleration is to slow , I get beat by almost every car i race. It also seems to break so fast 

### ISSUE THREAD

**Issue by Ethioking** [fkk-cz/noire_vehicles#193]
Nissan GTR acceleration is to slow, I get beat by almost every car i race, i got smoked by a Maserati that's 1/3 of the price, it also seems to break so fast, after hitting 1 sign ill start to smoke short after

**Comment by fkk-cz** [comment]
The Maserati in question was nerfed a few weeks ago.
