### ISSUE TITLE
[Tesla Model X] : using fuel not electric

### ISSUE THREAD

**Issue by Lymeish** [fkk-cz/noire_vehicles#1930]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

as title says - Model X is consuming gasoline instead of being electric

### Expected Behavior

not use gasoline

### Steps To Reproduce

drive the car

### Anything else?

let me wear shorts

**Comment by Artificial-IQ** [comment]
duplicate issue of https://github.com/fkk-cz/noire_vehicles/issues/1814
