### ISSUE TITLE
2020 Dodge Charger SRT Hellcat 

### ISSUE THREAD

**Issue by Jinxss06** [fkk-cz/noire_vehicles#194]
You cannot put neons under glow on and the back strip stays stays white there’s no cosmetic upgrades and the pearlescent keep going back to the original car color no matter how many times I change it

**Comment by fkk-cz** [comment]
> 
> 
> You cannot put neons under glow on and the back strip stays stays white there’s no cosmetic upgrades and the pearlescent keep going back to the original car color no matter how many times I change it

The white strip cannot be changed
