### ISSUE TITLE
2016 Ford Explorer - SAHP

### ISSUE THREAD

**Issue by Lymeish** [fkk-cz/noire_vehicles#1940]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

Top light bar only works for front facing lights.

### Expected Behavior

Both front and back sides of the lightbar should light up.

### Steps To Reproduce

get in car
turn on lights

### Anything else?

thank you

**Comment by okxeon** [comment]
Im not sure what you mean by "Top light bar only works for front facing lights.". The vehicle has rear facing lights as extras that need to be applied, and they have fully working environmental lighting. 
![Screenshot 2024-01-20 140428](https://github.com/fkk-cz/noire_vehicles/assets/98451518/aeab1bb0-5796-4466-ad0a-407a59ca08e2)
![Screenshot 2024-01-20 140458](https://github.com/fkk-cz/noire_vehicles/assets/98451518/0d033751-478d-443e-aa21-b78616a8e0b9)
![Screenshot 2024-01-20 140549](https://github.com/fkk-cz/noire_vehicles/assets/98451518/fbb9a4ba-2066-4194-9307-e58cf4e9f367)
