### ISSUE TITLE
Tesla Model X gas problem 

### ISSUE THREAD

**Issue by BobDown23** [fkk-cz/noire_vehicles#1941]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

Purchased a Tesla Model X from the PDM and the vehicle ran out of gas and stopped running, Teslas shouldn’t require Gas 

### Expected Behavior

The vehicle is Electric it shouldn’t require gas

### Steps To Reproduce

1. Buy the Tesla model X
2. Drive the Tesla model x
3. run out of gas 

### Anything else?

Nope

**Comment by No-Yes1** [comment]
There is already an open issue on this - refer to this instead https://github.com/fkk-cz/noire_vehicles/issues/1930
