### ISSUE TITLE
Lamborghini gallardo superleggera

### ISSUE THREAD

**Issue by dinmamma100** [fkk-cz/noire_vehicles#1946]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

Right now the car sound is vanilla meaning it not realistic at all for a 5.0 v10 it sounds like a normal gta car

### Expected Behavior

it should sound more realistic
Example: https://www.gta5-mods.com/vehicles/lamborghini-gallardo-5-0l-v10-sound-mod-sp-add-on-fivem

### Steps To Reproduce

drive the car around and listen
add the new sound so it sounds more realistic

### Anything else?

thanks for looking at thisw

**Comment by okxeon** [comment]
Swapped the audio on the vehicle to a louder and more fitting sound. Changes will be in for next restart.

**Comment by dinmamma100** [comment]
idk how long its supposed to take sop thats why im asking becasue there has been several restarts and its still the same sound
