### ISSUE TITLE
Lamborghini Murcielago 2008 Lp 640-4 Roadster Super

### ISSUE THREAD

**Issue by ViktorRus114** [fkk-cz/noire_vehicles#1948]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

The Lamborghini Murcielago 2008 Lp 640-4 Roadster Super is a iconic car known throughout the car industry considering the price of around 1.05 million it appears that the car doesn't have a functional dashboard to change the roof on and off which is absurd also another issue is that the interior looks like its melting and the speedometer is barely visible I'm hoping to see a change in this
![image_2024-01-28_111158452](https://github.com/fkk-cz/noire_vehicles/assets/157957546/7acac98d-7d9c-4715-a94f-c6a78363cd37)

### Expected Behavior

I would expect the car to have a better interior seeing as the looks on the outside is immaculate also the speedometer also to have a functional dashboard to switch the roof on and off and to apply a spoiler.

### Steps To Reproduce

1. make the dashboard using page up be useable and to be able to change the roof on and off add a spoiler and remove the back plate
2. make the interior look aesthetically pleasing
3. make the speedometer visible and to make it look better to match the car and make it more realistic

### Anything else?

![image_2024-01-28_111328932](https://github.com/fkk-cz/noire_vehicles/assets/157957546/dada9d06-57b8-4c7c-8ea8-8f20e997483d)
![image_2024-01-28_111357748](https://github.com/fkk-cz/noire_vehicles/assets/157957546/d3b48bd9-e8cb-437a-ba16-a9a2cb1d4abf)

**Comment by Artificial-IQ** [comment]
This is something you would need a vehicle model designer to do. Unfortunately, we do not work on the models themselves.
