### ISSUE TITLE
lamborghini hurcan evo sypder, super

### ISSUE THREAD

**Issue by jasrajps** [fkk-cz/noire_vehicles#1949]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

slow accelleration considering the pricing of the car. the cars acceleration is very bad conidering it is one of the top of the lines Lamborghinis and the Gallardo and mucilago can easily beat it during acceleration.

### Expected Behavior

i think personally that the car should have a faster acceleration time just enough to beat the gallardo and murcilago considering in real like it is more expensive and realistically should have a faster acceleration due to the parts in the cars.

### Steps To Reproduce

1: compare both cars (inlucing gallardo0
2: see the speeds and accelerations.
3: make a change the the accelerations only.

### Anything else?

https://github.com/fkk-cz/noire_vehicles/assets/151686647/2634c221-f516-439c-a72a-62faddf13d61

https://github.com/fkk-cz/noire_vehicles/assets/151686647/2118142c-5446-40eb-af15-42b47254c761

https://github.com/fkk-cz/noire_vehicles/assets/151686647/5a3e0fd6-7188-4786-adf0-4de20171e872

**Comment by Artificial-IQ** [comment]
This vehicle is where it should be in its current state and will not be changed.
