### ISSUE TITLE
Request: <Lamborghini Svj>

### ISSUE THREAD

**Issue by robertyyyyyy** [fkk-cz/noire_vehicles#1952]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

The Lamborghini Svj is one hell of a car and coming with a heavy price of about $1.4 million the handling is pretty awful considering its price and the car its self, being a Lamborghini which is the top of the top within the hyper car industry. The speed is fine but the handling and breaking is god awful and I was hoping to see a change in that. 

### Expected Behavior

I expected the car to have one of the best handling, breaking, and speed.

### Steps To Reproduce

Just to take a look at it and hopefully make some changes to it. 

### Anything else?

No nothing else.

**Comment by Artificial-IQ** [comment]
This vehicle is where it should be in its current state and will not be tweaked.
