### ISSUE TITLE
[Exact name of vehicle, as displayed in game]: Bugatti veyron

### ISSUE THREAD

**Issue by sneakyyyyyy** [fkk-cz/noire_vehicles#1953]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

I payed just under 600k and now there are cars that are 400k that go faster and handle better this car does not perform how it should 

### Expected Behavior

It need the speed to go up 

### Steps To Reproduce

It just needs the speed up a bit for a Bugatti it’s slow 

### Anything else?

No thanks

**Comment by Artificial-IQ** [comment]
The vehicle is where it should be in its current state and will not be tweaked.
