### ISSUE TITLE
2020 c8 Corvette 8th gear redlines forever but keeps accelerating

### ISSUE THREAD

**Issue by c0sm0th3gr34t** [fkk-cz/noire_vehicles#196]
i'm not sure if it's a bug with the top speed or something, but i've noticed that the C8 gets to 130 very quick and hits 8th gear fast, but once it hits 8th gear it seems to redline, but keeps accelerating.  It sounds like it's redlining at 130, but the top speed has gone as high as 200.  The acceleration on it and top speed is fine, it just doesn't feel natural when the car is redlining at 130 in 8th gear and it the speed just keeps going up anyway.

**Comment by fkk-cz** [comment]
https://github.com/fkk-cz/noire_vehicles/commit/2bf3d89fd9be3a59b5ae989a692e47f7118ceaa1#diff-e9832e085e8c7f87189f2080a7b9dac865febbca3551d41cf60ef2ccd8979223
