### ISSUE TITLE
2018 Dodge Challenger SRT Demon

### ISSUE THREAD

**Issue by Ctolding69** [fkk-cz/noire_vehicles#1960]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

The top speed of this vehicle is way too low. It cant even hit 170 on flat roads. Its take off is slow because of the tires spinning and that's expected but the top speed should be higher.

### Expected Behavior

I expect the top end speed to go up some.

### Steps To Reproduce

1. Drive it and see how slow it is top speed wise
2.  Compare to the other vehicles in class and price range
3. Give it the top end speed it deserves

### Anything else?

When it first was released it was way too fast, it went like 230. But it is way over nerfed

**Comment by Artificial-IQ** [comment]
The current state of the 2018 Dodge Challenger SRT Demon is where it should be and the vehicle will not be tweaked.
