### ISSUE TITLE
Lamborghini Centenario LP 770-4

### ISSUE THREAD

**Issue by Ahy-jason-todd** [fkk-cz/noire_vehicles#1964]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

Recently purchased this car for 2.2 million and was expecting something better slightly better. I know there was a ticket made about this before over 6+ months ago but between the price change, i believe it should perform just a bit better. When googled the top speed it said 217. Now i know you guys nerfed all the cars for a reason so I don't expect 217 top speed but maybe just something along the lines of 195-205 on a flat? or something that performs a similar to the FXXK ferrari. This i premium hyper car and a costly shouldnt have the same performance as any 800k-1.2m car. Thank you a 

### Expected Behavior

I expect the Lamborghini Centenario to be somewhere around 195-205 top on a flat 

### Steps To Reproduce

no response 

### Anything else?

Again just a premium car not everyone can afford it and those who can should be able to enjoy the performance it offers

**Comment by Artificial-IQ** [comment]
This vehicle is where it should be in its current state and will not be tweaked.
