### ISSUE TITLE
Subaru WRX STI Upgrades

### ISSUE THREAD

**Issue by wilkyJW** [fkk-cz/noire_vehicles#197]
I recently bought a Subaru WRX STI and I'm unable to upgrade it. When I go to the place to upgrade it the only options I get is "Default" for things such as engine, Armor, brakes, suspension, and transmission etc.

https://user-images.githubusercontent.com/83140886/115972830-c6edb080-a51e-11eb-90dc-13d1f311b3ed.mp4

**Comment by fkk-cz** [comment]
https://github.com/fkk-cz/noire_vehicles/commit/2bf3d89fd9be3a59b5ae989a692e47f7118ceaa1#diff-0004041b4dc06dab3a00b8482ec28a663fed6d41dddee7b31699e41d0fb7e8cf
