### ISSUE TITLE
Pfister Comet S2

### ISSUE THREAD

**Issue by sailboat76** [fkk-cz/noire_vehicles#1975]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

The car is nice but has no top end speed, reaches 120 pretty slowly when fully upgraded. For 180k, and being a knockoff 911, I was expecting a little more. 

### Expected Behavior

Increase the top end by like 15-20 and the acceleration a little to go with it. It doesn't need a ton, just something to make buying the car make sense. 

### Steps To Reproduce

Test speed in city and highway, tweak top end speed, and reinstate car with changes

### Anything else?

no

**Comment by Artificial-IQ** [comment]
This is a vanilla car and is fine in its current state. It will not be tweaked at this time.
