### ISSUE TITLE
2016 Alfa Romeo Giulia Empty Custom Shop/Buff

### ISSUE THREAD

**Issue by SavageStonerDude** [fkk-cz/noire_vehicles#198]
2016 Alfa Romeo Giulia
 The car drives great and sounds good but it doesn't seem to anything available in LS customs... i cant even change the rims or add/remove any body parts.. i can only paint the car and change tire smoke colors/ window tint.. the back passenger seats still don't seem to work either.. 
 i would love for some more customization options and if possible a small top speed buff after all, it is a super-car if possible to have it go 190-200 would be perfect! (i cant get it over 180 MPH).. thank you

**Comment by fkk-cz** [comment]
https://github.com/fkk-cz/noire_vehicles/commit/2bf3d89fd9be3a59b5ae989a692e47f7118ceaa1#diff-1ca445a838493d73795a092a742efb54f1add7e638175b455dd626898500b89b

**Comment by SavageStonerDude** [comment]
so the price of this car is now 74,500 at pdm but i thought it was 175,400??

**Comment by SavageStonerDude** [comment]
thank you for the fixes
