### ISSUE TITLE
BMW M8 Speed Issue

### ISSUE THREAD

**Issue by GunnaWunnaa** [fkk-cz/noire_vehicles#200]
The BMW M8 is a beautiful car and I don't want to come off as entitled because I really appreciate all the work you guys do for the server, However the car is ultimately just too slow. The acceleration and handling are pretty good but the top speed of 150 just feels as if it is not enough for a 200k car. There are many cars that cost a lot less than this BMW and beat it in races easily. If you guys think you could increase the speed it would be really appreciated. Thank you for taking your time to read this request and I hope you have a great day.

**Comment by ZacLuxton** [comment]
This is already fixed in a previous issue, should go > 165ish now maxed out
