### ISSUE TITLE
Rocket Bunny V3 BRZ

### ISSUE THREAD

**Issue by Skylar96** [fkk-cz/noire_vehicles#204]
when i go into the los santos customs it dosent give me the option to do any engine upgrades, it just says default and when i buy the turbo it disappears sometimes

**Comment by bkkells** [comment]
yea same needs upgrades and tints

**Comment by ZacLuxton** [comment]
Vehicle speed should be better now

https://github.com/fkk-cz/noire_vehicles/commit/3416b2718881681935c448be1ab550c0ea98f954

**Comment by ZacLuxton** [comment]
Speed is fixed, should go a lot faster and the accel too, leaving open as it will need a new modkit

**Comment by ZacLuxton** [comment]
https://github.com/fkk-cz/noire_vehicles/commit/02c2c3801ee6f3a3c9a3888acec08c72efee5c1d
