### ISSUE TITLE
2016 Dodge Challenger

### ISSUE THREAD

**Issue by Luntrix420** [fkk-cz/noire_vehicles#206]
Doesn't let you upgrade anything everything says default.

**Comment by fkk-cz** [comment]
https://github.com/fkk-cz/noire_vehicles/commit/2bf3d89fd9be3a59b5ae989a692e47f7118ceaa1#diff-0587765d805a72f5beb39a2e9cc7d350f4a70afc8a7fe76f2822fd7994865844

trying this modkit ID, see if it's fixed
