### ISSUE TITLE
tesla roadster buff please 

### ISSUE THREAD

**Issue by stinsy12** [fkk-cz/noire_vehicles#208]
Hey can we a buff on tesla roadster car has no problem reaching like 115 however for a 200k car and a supporter vehicle I think it shouldn't be capped speed around 130-145 and that's being a little generous. Speed should cap around 200-215 considering its a 250mph car IRL.

**Comment by wilkyJW** [comment]
I agree with this.

**Comment by fkk-cz** [comment]
https://github.com/fkk-cz/noire_vehicles/commit/910c62788860674d8adee52697cbf6d5ea67ede1#diff-66b8bbdab284f7f1604dbc52076f758be40827ce8ebebcdb08534b1d8dd49b9c
