### ISSUE TITLE
Garage Pearlescent

### ISSUE THREAD

**Issue by EveEnchooli** [fkk-cz/noire_vehicles#211]
There's an ongoing issue with vehicle pearlescent paint. 
When a car is pulled out of the garage it comes out a different pearlescent than what was paid for...
(ex. Model X always default to like orange pearlescent) 
I know it also happens for the S2000, GTR, Supra, and a list of other cars.

**Comment by fkk-cz** [comment]
This has been fixed, check updates in Discord
