### ISSUE TITLE
BMW M4 liberty walk 

### ISSUE THREAD

**Issue by MadBasel** [fkk-cz/noire_vehicles#213]
Can't do any upgrades other than turbo and in general the acceleration is slow and the car tops out at 120 which is **unrealistic.**

**Comment by fkk-cz** [comment]
https://github.com/fkk-cz/noire_vehicles/commit/910c62788860674d8adee52697cbf6d5ea67ede1#diff-1881bb02c820cbc2cd0692a504efce32edf424dd23bdd5a1ae181742463678b3
