### ISSUE TITLE
Tesla Roadster

### ISSUE THREAD

**Issue by Skylar96** [fkk-cz/noire_vehicles#214]
i really like the car i just feel like the top speed is to slow. it tops out at 145. and im pretty sure thats the slowest of all the teslas.

**Comment by fkk-cz** [comment]
https://github.com/fkk-cz/noire_vehicles/commit/910c62788860674d8adee52697cbf6d5ea67ede1#diff-66b8bbdab284f7f1604dbc52076f758be40827ce8ebebcdb08534b1d8dd49b9c

**Comment by imcoty** [comment]
change was made and the issue was closed but the tesla still has the same issue as this ticket
