### ISSUE TITLE
Audi R8 no upgrades 

### ISSUE THREAD

**Issue by TheMitch1** [fkk-cz/noire_vehicles#216]
Please could the Audi R8 get upgrades as it does not have upgrades and I think the car is pretty slow for what it is!

**Comment by fkk-cz** [comment]
this issue was fixed in https://github.com/fkk-cz/noire_vehicles/commit/910c62788860674d8adee52697cbf6d5ea67ede1#diff-f394e6c3dc0d6156982d304061c358f97ad0465cb290bf3ec0534b0d75a94b20
