### ISSUE TITLE
mclaren 720s Supporter 

### ISSUE THREAD

**Issue by Ahy-jason-todd** [fkk-cz/noire_vehicles#221]
Has no upgrades the car stock is way too slow if possible put upgrades car should be just as good as the porsche 911 Pdm 330k one if not a bit better

**Comment by fkk-cz** [comment]
https://github.com/fkk-cz/noire_vehicles/commit/c68f953610e314aa01541352614c138b547df004#diff-673b9d4e5d0bbe2db65bad03a19ef51829026df8bbfcbd1835572b5f020919c8

reduced the drag and slightly increased the top speed

**Comment by Ahy-jason-todd** [comment]
is it not possible to add upgrades ik recently you added upgrades to a lot of cars
