### ISSUE TITLE
GTR wide wheels with wide body

### ISSUE THREAD

**Issue by stanzyz** [fkk-cz/noire_vehicles#222]
I would like to see wide wheels with the GTR because there is no point of having the widebody kit if you cant have wide wheels to fill them in it just looks silly so I would like to see wide wheels with the GTR in the future Thanks.

**Comment by ZacLuxton** [comment]
Unfortunately wheels would be there own independent mod, and are not apart of the vehicle.meta files, there is no "wide wheels" with standard GTA wheels, so there is no way to put it in
