### ISSUE TITLE
2008 Alfa Romeo 8C

### ISSUE THREAD

**Issue by GordoGambino** [fkk-cz/noire_vehicles#223]
The car is $300K and doesnt go over 150 meanwhile, there are 50-60K cars that are way faster. If you can pls bump the speed up, I would really appreciate it.

**Comment by fkk-cz** [comment]
https://github.com/fkk-cz/noire_vehicles/commit/c68f953610e314aa01541352614c138b547df004#diff-43ed21d28133bf33c07bf1a22f6439d3aef47a8fb54a42fea1295dd51ad166c3

should be better now
