### ISSUE TITLE
2017 Nissan Titan

### ISSUE THREAD

**Issue by Stagonium** [fkk-cz/noire_vehicles#225]
Name on insurance and when locking and unlocking is NULL and also only holds 750 even though its a big truck.

**Comment by Stagonium** [comment]
it also goes insanely unrealistically fast

**Comment by apricates** [comment]
Nah keep the speed. It takes a good a minute to start hitting those numbers but if it becomes a problem just ban it from being able to run from cops. The car is so fun cruising around with friend outside the cities.

**Comment by Stagonium** [comment]
Yea I just wanted them to know so that the cops dont allow them for robberies or whatever ya feel?

**Comment by fkk-cz** [comment]
https://github.com/fkk-cz/noire_vehicles/commit/c68f953610e314aa01541352614c138b547df004#diff-2c4f2ec9b1b755f47a7546794d85ee7412f41ae0ef7c36e3837d44962dacd128

Knocked down the top speed, thanks. Also changed the vehicle class to `VC_OFF_ROAD` which fixes the trunk space issue.

> 
> 
> Nah keep the speed. It takes a good a minute to start hitting those numbers but if it becomes a problem just ban it from being able to run from cops. The car is so fun cruising around with friend outside the cities.

We already have server rules in place to restrict high end cars from being used in robberies, but people seem to complain about not being able to use their supercars to rob small gas stations.. Ideally all cars should be tuned to their realistic specs to avoid this issue.
