### ISSUE TITLE
porsche gt3rs

### ISSUE THREAD

**Issue by teejizzle** [fkk-cz/noire_vehicles#226]
add a sound it sounds like the normal gta cars. and yall nerfed it to where it barely hits 200 its a 850,000 SPORTS car. made for mostly racing instead of looks or anything like that the porsche 911 is faster than it top speed wise and its less than half the price.

**Comment by fkk-cz** [comment]
> Porsche says its 2019 911 GT3 RS can hit a top speed of 194 mph. That's pretty fast, considering all of the drag-inducing aero. The car was meant for corners, not straight-line numbers, after all.Mar 26, 2020

The GT3's acceleration is already pretty ridiculous, not sure why you are complaining about 200MPH+.. Knocked back the drive force a bit to reflect more realistic acceleration, even in GTA standards
https://github.com/fkk-cz/noire_vehicles/commit/c68f953610e314aa01541352614c138b547df004

In terms of balance, drag has been increased on the 911 turbo s. https://github.com/fkk-cz/noire_vehicles/commit/c68f953610e314aa01541352614c138b547df004

In reality, the 911 turbo s is actually _faster_ than the GT3.

**Comment by fkk-cz** [comment]
What audioHash do you suggest for the GT3?

**Comment by teejizzle** [comment]
just anything grumbly if that makes sense. a good purr

**Comment by teejizzle** [comment]
and in reality a 850,000 car should be faster than a way cheaper one. its fine now i just hope that the money amount on race cars should reflect on speed the gt2 hits 239.

**Comment by teejizzle** [comment]
so i have been told it hits 239 but the amount of cash should reflect on speed especially since they are all race cars

**Comment by teejizzle** [comment]
219* not 239 even the gt3 hitting 220 is good just a slight buff. if not keep it how it is

**Comment by teejizzle** [comment]
https://gtaforums.com/topic/967314-i-will-like-to-know-how-to-install-vechicle-sound/   .. but even a sound like this is niceee

**Comment by ZacLuxton** [comment]
Updated audio hash: https://github.com/fkk-cz/noire_vehicles/pull/419/commits/b2467a9d0d935b2ea95825c2c7b29d0515010c3a

Should sound a little bit better now
