### ISSUE TITLE
2017 Koenigsegg Agera RS

### ISSUE THREAD

**Issue by james77610** [fkk-cz/noire_vehicles#227]
Can you please tweak the Koeniggsegg agera RS to have better acceleration/top speed. I paid 500k for it and the lamborghini performante is quicker than it and is significantly cheaper. In reality the agera rs is much faster than a lot of cars that seem to be a little overkill when it comes to their performance settings. Please take the time and consideration to meet my request as I'd be extremely grateful. Thank you!

**Comment by fkk-cz** [comment]
https://github.com/fkk-cz/noire_vehicles/commit/c68f953610e314aa01541352614c138b547df004#diff-4f13532c561643a1e01219b5e61443023104b25b91bef33caaff12087c1da62c

should be better now
