### ISSUE TITLE
PDM Backroom Vehicle Replace

### ISSUE THREAD

**Issue by MichaelCoppJr** [fkk-cz/noire_vehicles#23]
The current Ford F-150 Raptor in the backroom is dog... I'm asking to have it replaced with a better model, I will link two if you'd like to choose one. 

https://www.gta5-mods.com/vehicles/ford-raptor-2017-addon-template?__cf_chl_jschl_tk__=1e8a7a3f50e05390706efafaff4558c952bd579c-1612303484-0-AZ5Ctuthu0v_j7Suoc81RFPTo9cWetBEW_OWjYO47uW9rihQAaE8Z-UCzAlAnp1vsj-7xP1eYT9_MRGliq9kgyorgTaNFiw_s6wL-shiE-sHvuw6OxY3-S2lrIq9AngJ7D3Eo9Q_wGOq_qO2YeVNbl1phI2dCCIYBiSJWNQ5WIZBqKK6_vIjZGqmnGVtRfDe0e5MET2tY2NKU7MqBOjGwjQJhqgBtjvSFdJ6SODgIX40zm9aog0orFQtAy0POJ8_3-NeoVsmePN77iy4ulfvgpmZKG1JSr9tMMEQvIULMmrxWrv5-lMinTIs6HEzpL1SKapmaWQKk9eRuycsuzL8BSATBYNOQ0AJ48rySSzk2hCw

https://www.gta5-mods.com/vehicles/2018-ford-f-150-raptor-crew-cab-oiv-add-on-tuning-fivem

**Comment by T45DARK** [comment]
I agree it would be great to have a better model raptor
