### ISSUE TITLE
Ambulance Heli

### ISSUE THREAD

**Issue by Retr0Flux** [fkk-cz/noire_vehicles#230]
Hey Bobby, one time at the hospital you were talking to us about adding a heli for us to use to get to Blaine and Paleto. I found a good one that has good interior if you ever plan to add that. https://www.gta5-mods.com/vehicles/air-ambulance-medevac-helo-ec-135

**Comment by fkk-cz** [comment]
This is a replacement vehicle:

> can replace supervolito or polmav
