### ISSUE TITLE
McLaren 720s

### ISSUE THREAD

**Issue by calebaustin8** [fkk-cz/noire_vehicles#231]
There is no upgrades for it, slow top speed and not great acceleration

**Comment by fkk-cz** [comment]
Managed to get it up to 180 stock, how is that slow

**Comment by calebaustin8** [comment]
probably the wrong one. theres 2 720s. i only got the one to like 130 if i remember

**Comment by fkk-cz** [comment]
> 
> 
> probably the wrong one. theres 2 720s. i only got the one to like 130 if i remember

you're right, it was the 720nlargo that, for some reason, did not have parity with the regular 720s

fixed https://github.com/fkk-cz/noire_vehicles/commit/9f716a3ff6a9d3ba34d545b8670f63047c74510d#diff-6fcf28355d928c79fe01d360cba486c6db48507ca4b06144c2dd7fa978eaaa83
