### ISSUE TITLE
Ford Raptor Turbo & Upgrades Disappearing/Other

### ISSUE THREAD

**Issue by RealDarkwater** [fkk-cz/noire_vehicles#233]
Upgrades didn't apply at first then on relog they disappeared again, Raptor can barely go over 105 unless going downhill as well.
90,000$ is quite steep for a just okay Acceleration and a max speed almost shared with that of a Colorado 1/3rd the price.

**Comment by fkk-cz** [comment]
which raptor? there's 2

**Comment by RealDarkwater** [comment]
The non-supporter one that's $90,000

**Comment by fkk-cz** [comment]
https://github.com/fkk-cz/noire_vehicles/commit/d1aeaa5619debf7df0c7c95513a56e3518b14eae#diff-1111367e721cb19369761b9cae5e696f891363df7039eedfbdbc8152c2b92301

improved the top speed, the modkit ID looks fine
