### ISSUE TITLE
livery/sticker

### ISSUE THREAD

**Issue by bkkells** [fkk-cz/noire_vehicles#234]
1992 honda NSX

**Comment by DankGrandma** [comment]
> 1992 honda NSX

you have to be more specific..

**Comment by bkkells** [comment]
I bought the car with stripes/design I just wanna remove them and put primary and secondary colors

**Comment by fkk-cz** [comment]
> 
> 
> I bought the car with stripes/design I just wanna remove them and put primary and secondary colors

Go to LS customs, under the stickers category, use up/down arrows to remove the stripes.
