### ISSUE TITLE
Lamborghini Urus

### ISSUE THREAD

**Issue by KCurt420** [fkk-cz/noire_vehicles#235]
None of the upgrades work the, you can apply them but none of them work the car is the exact same and the neon doesn't work either you cant have an underglow

**Comment by fkk-cz** [comment]
https://github.com/fkk-cz/noire_vehicles/commit/3a1ba05218dd9092f93833c0d199be7f68fecfdb#diff-1718a7d8d1f0218994fe55610e03c1bddf30792dfd3c20d15abf0fe027d2aaf7

trying a new modkit ID

**Comment by fkk-cz** [comment]
perf. upgrades work now, no cosmetics on this one
