### ISSUE TITLE
Ford Bronco

### ISSUE THREAD

**Issue by Luntrix420** [fkk-cz/noire_vehicles#238]
When upgrading the bronco their is bare minimum cosmetics you can do to it. If we could make it where we can get custom bumpers/light bars and custom rims like some of the trucks do that would be sick.

**Comment by DankGrandma** [comment]
> When upgrading the bronco their is bare minimum cosmetics you can do to it. If we could make it where we can get custom bumpers/light bars and custom rims like some of the trucks do that would be sick.

this would have to be done by the mod maker

**Comment by fkk-cz** [comment]
should be fixed with a new modkit ID https://github.com/fkk-cz/noire_vehicles/commit/4da193359aa2a77a6b91c6df9a960236b2529e60#diff-fed9f3d0163c6a0de0e82955757e2757bb73fad2f5fe230093a71a8518048eae
