### ISSUE TITLE
Ferrair 458 Prior

### ISSUE THREAD

**Issue by Luntrix420** [fkk-cz/noire_vehicles#243]
Respray wont let you change the primary color of red to anything. It lets you change the secondary and pearl just not the primary.

**Comment by fkk-cz** [comment]
should be fixed with a new modkit ID https://github.com/fkk-cz/noire_vehicles/commit/4da193359aa2a77a6b91c6df9a960236b2529e60#diff-e059796eafdb5c615c8c07fe9c8e3a9a0996a47b1d1f44b4e5c9824956e618a9

**Comment by fkk-cz** [comment]
you can change the liveries under **stickers**
