### ISSUE TITLE
Problems with BMW M8

### ISSUE THREAD

**Issue by ouchacactuss** [fkk-cz/noire_vehicles#247]
Most of the cosmetics say "Default" so not a lot to do with the car and the car feels relatively slow for how much it is. Adding turbo just takes your money and doesn't add it, same with the armor.

**Comment by fkk-cz** [comment]
there are no cosmetic upgrades for this model

https://github.com/fkk-cz/noire_vehicles/blob/9f716a3ff6a9d3ba34d545b8670f63047c74510d/DATA/bmwm8/carcols.meta#L9
