### ISSUE TITLE
Mustang Mach E

### ISSUE THREAD

**Issue by DankGrandma** [fkk-cz/noire_vehicles#249]
it wont take armor past level 2 and (this may be because its electric idk) it wont take the turbo upgrade

https://youtu.be/fuEIkt7p_Ig

**Comment by fkk-cz** [comment]
the turbo issue was fixed https://github.com/fkk-cz/noire/commit/f59bb9dd779a68e088c97e457d882200b8ed8252

Armor is currently restricted to level 2, as some vehicles (almost) have invincibility with level 5 armor
