### ISSUE TITLE
PDM Additions

### ISSUE THREAD

**Issue by MichaelCoppJr** [fkk-cz/noire_vehicles#25]
Add some classic trucks? 

1970 Ford F100, Trucks

https://www.gta5-mods.com/vehicles/ford-f100-1970-add-on-animated-template-replace

1997 GMC Sierra, Trucks

1997 GMC Sierra 1500 Custom [Add-On | Extras | Unlocked] - GTA5-Mods.com

1978 Ford F-150 XLT Ranger, Trucks

https://no.gta5-mods.com/vehicles/1978-ford-f150-xlt-add-on

**Comment by T45DARK** [comment]
Fr and classic cars to
