### ISSUE TITLE
2020 McLaren GT No Turbo/PermaDirty windows

### ISSUE THREAD

**Issue by RealDarkwater** [fkk-cz/noire_vehicles#250]
Turbo upgrade for the McLaren at Los Santos Customs charges me but doesn't install a turbo, and the windshield/windows are splotchy/dirty for some reason.

Love you <3

**Comment by fkk-cz** [comment]
This car might have model/livery issues, the textured pattern is not normal and should be removable in stickers but I can't change it. Do you want it removed?

**Comment by RealDarkwater** [comment]
Sure, it'll make for a cleaner look.
Turbo is fixed, and the perma dirty look was me being an idiot, I washed the car and it's good.
