### ISSUE TITLE
Eleanor 1967 Shelby GT500's acceleration and top speed are all wrong

### ISSUE THREAD

**Issue by nickytheprophet** [fkk-cz/noire_vehicles#252]
its supposed to max at 172MPH and be just as fast as the 2020 Eleanor Shelby GT500, if not faster, the model in your game costs $189k, which means its the 770 Horsepower version, I hope this issue can be resolved and fixed

**Comment by nickytheprophet** [comment]
The Hellcat has790HP, the 1967 gt500 has 20 less, you can only upgrade the turbo and it has no cosmetics, it's 189k in the supporter cars and I feel like it was a waste of money for a well known to be a monster of a vehicle

**Comment by fkk-cz** [comment]
fixed https://github.com/fkk-cz/noire_vehicles/commit/9f716a3ff6a9d3ba34d545b8670f63047c74510d#diff-70a7fc9508f676fd12bd0b12016d487620013de84b3ad63ba8531e6a530c33a2
