### ISSUE TITLE
2017 Dodge Charger

### ISSUE THREAD

**Issue by Jmay419** [fkk-cz/noire_vehicles#254]
i have an issue with the Charger not only cant i upgrade then engine or breaks i cant even change the rims from default, im not asking for any crazy rims just something other than what comes on it please!

**Comment by fkk-cz** [comment]
> 
> 
> i have an issue with the Charger not only cant i upgrade then engine or breaks i cant even change the rims from default, im not asking for any crazy rims just something other than what comes on it please!

https://github.com/fkk-cz/noire_vehicles/tree/master/DATA/2017charger

No carcols/carvariations file was provided with this model. Some vehicles do not have cosmetic upgrades
