### ISSUE TITLE
Bugatti Divo 

### ISSUE THREAD

**Issue by Juicex420** [fkk-cz/noire_vehicles#261]
Armor dose not Apply pass level 2 And the turbo Dose not Stay applied to the car.

**Comment by fkk-cz** [comment]
this vehicle shouldn't have any upgrades at all

https://github.com/fkk-cz/noire_vehicles/blob/6df7812acf5a3920a2eb2475df7bc11a5d59b007/DATA/divo_DATA/carvariations.meta#L21
