### ISSUE TITLE
Fix Bike

### ISSUE THREAD

**Issue by Retr0Flux** [fkk-cz/noire_vehicles#263]
"So due to the fact I cant figure out how to use Vehicle Tweaks Ill just leave this here that the Ninja H2r is slower then the BMW 1000 RR and the Yamaha R1 but in fact has a top speed of 249 mbh and is the fastest production Bike in the world but in game has a top speed of like 140 or so" (STRIZXY ON DISCORD).

**Comment by fkk-cz** [comment]
https://github.com/fkk-cz/noire_vehicles/commit/3a1ba05218dd9092f93833c0d199be7f68fecfdb#diff-559f83b17f588fa2cc0861e65e77c5699714827ab9dc14508bd59296bcf30328

should be better now
