### ISSUE TITLE
Lamborghini SC18

### ISSUE THREAD

**Issue by xFuziii** [fkk-cz/noire_vehicles#265]
hello,
i just bought a Lamborghini SC18 it is a good looking car so was i like i'll buy it i went to Los Santos Customs and it said i couldnt do any upgrades on it... is there a way to fix this? if not to get my money back atleast bcs it's worth 389000 and that's a lot of money for a car i can't upgrade.

Patty Junior

**Comment by fkk-cz** [comment]
trying a new modkit ID https://github.com/fkk-cz/noire_vehicles/commit/2027a74a1b0fb9e254e5732ae320a55f3fdd7733#diff-515a745a3aa6307b2a8625ab8fafb6344dee1ea2fc37ed221a52f6d1c26e866c

**Comment by xFuziii** [comment]
so i went to check it out and it looks like i still cant upgrade it

**Comment by fkk-cz** [comment]
> 
> 
> so i went to check it out and it looks like i still cant upgrade it

this car has no cosmetics, but there are performance upgrades available now
