### ISSUE TITLE
Buggati Veyron

### ISSUE THREAD

**Issue by KCurt420** [fkk-cz/noire_vehicles#266]
It has no engine, brake, transmission, armor or turbo upgrades and it cost almost 300,000 and you cant even change the wheels on it? anyway this can be fixed?

**Comment by KCurt420** [comment]
also the window tint doesnt even work for it

**Comment by fkk-cz** [comment]
https://github.com/fkk-cz/noire_vehicles/commit/db2bd9b5ab30f2df3a1a95990b9b93341e4f6d8d#diff-ee0a11f138c297148e70aa00d373ffcbc71e9d3d4d711b4c9956f1c8664133f4

fixed a while back, forgot to commit this
