### ISSUE TITLE
Lamborghini perfomente 

### ISSUE THREAD

**Issue by Maxzoldyck** [fkk-cz/noire_vehicles#268]
turbo disappearing and cant put anything above armor level 2

**Comment by bubblehead53** [comment]
also its constantly dirty and super dirty really fast

**Comment by fkk-cz** [comment]
the turbo issue _should_ be fixed: https://github.com/fkk-cz/noire/commit/e756cd366cfce931bcb0e5306e808590ab092632#diff-79fea71d0afc03e7099a4bb82a0f704259032b89a5f60de4a5c1e45173630970

as for the dirt level, that is a texture for the vehicle
