### ISSUE TITLE
2018 BMW M5 Just keeps spinning out

### ISSUE THREAD

**Issue by cxerq** [fkk-cz/noire_vehicles#269]
The car just spins out all the time, Literally i hold W and the car will do a donut the traction is really bad

**Comment by fkk-cz** [comment]
https://github.com/fkk-cz/noire_vehicles/commit/6328aa214cfabad0ce966648a3918f32564b2fff#diff-078dc1e8588695396f979955483c1e6eadf5094852026a04cb62e90421f67687

should fix the traction and braking issues
