### ISSUE TITLE
Toyota supra wrong speed !

### ISSUE THREAD

**Issue by akxbigboi** [fkk-cz/noire_vehicles#270]
The speed of this car is listed at 270mph at PDM, but the car actually only goes 170mph DOWNHILL. The jeep trackhawk that's around $80k is faster than this car... this car cost $350k
![Desktop Screenshot 2021 05 12 - 02 54 00 75](https://user-images.githubusercontent.com/83898077/117955864-b76bb700-b2d5-11eb-9fa8-32dc5af96205.png)

**Comment by akxbigboi** [comment]
i have video proof of the car barely breaking 180 downhill.

**Comment by fkk-cz** [comment]
Fixed the speed display issue, should display ~170MPH now
