### ISSUE TITLE
2016 alfa romeo super spins out

### ISSUE THREAD

**Issue by Lemonreginold** [fkk-cz/noire_vehicles#271]
in first gear or on acceleration it seems the traction becomes nothing and you spin out.
also a lack of custimization but i know thats not up to you

**Comment by fkk-cz** [comment]
should be better now https://github.com/fkk-cz/noire_vehicles/commit/db2bd9b5ab30f2df3a1a95990b9b93341e4f6d8d#diff-b10985a15e8beeb6e4f2d96f6baf935ec69031def4a041ad0332937bae61b04e
