### ISSUE TITLE
2020 Audi rs7

### ISSUE THREAD

**Issue by AlexBishop1112** [fkk-cz/noire_vehicles#274]
needs better acc and should hit like 180

**Comment by fkk-cz** [comment]
https://github.com/fkk-cz/noire_vehicles/commit/db2bd9b5ab30f2df3a1a95990b9b93341e4f6d8d#diff-d5f95d71c2993ade9ac9e861fcda5e8434e78a94b97e133149ef58a9102105f2

should be better now
