### ISSUE TITLE
Lamborghini SC18

### ISSUE THREAD

**Issue by xFuziii** [fkk-cz/noire_vehicles#275]
hello,
is it maybe possible to give this car a little ascelleration boost and top speed?

Patty Junior

**Comment by xFuziii** [comment]
like it takes off really slow i also have to huracan and that car is pretty good balanced so i wanted a upgrade to this car so if it's a little bit better then the huracan i would be happy

**Comment by xFuziii** [comment]
and is it possible to have another engine sound? if not it's cool just wondering what u can ask for and what is possible

**Comment by fkk-cz** [comment]
https://github.com/fkk-cz/noire_vehicles/commit/db2bd9b5ab30f2df3a1a95990b9b93341e4f6d8d#diff-b3a84a2771b311b186aec72d5127657f5197c74868203f2ac2c665e94fab275f

should be better now

> 
> 
> and is it possible to have another engine sound? if not it's cool just wondering what u can ask for and what is possible

what audioHash do you want?

**Comment by xFuziii** [comment]
where do i find the audiohash on the GTA5 mods browser page or? and ty for buffing the car btw the only thing that is still slow in my opinion is the 0-60 but overall it's pretty decent ty for this

**Comment by fkk-cz** [comment]
> 
> 
> where do i find the audiohash on the GTA5 mods browser page or? and ty for buffing the car btw the only thing that is still slow in my opinion is the 0-60 but overall it's pretty decent ty for this

Yes, find the model name of any vanilla (or add-on DLC) GTA vehicle, here's a list: https://wiki.gtanet.work/index.php?title=Vehicle_Models

**Comment by ZacLuxton** [comment]
Should now have a better sound:

https://github.com/fkk-cz/noire_vehicles/blob/974f2e1404349b5a37918ca5de37b47861da2721/DATA/sc18_data/vehicles.meta#L18
