### ISSUE TITLE
Lamborghini Countach is too slow for its price

### ISSUE THREAD

**Issue by nickytheprophet** [fkk-cz/noire_vehicles#276]
It's 425k and only goes about 180

**Comment by fkk-cz** [comment]
> 
> 
> It's 425k and only goes about 180

Lamborghini claimed 300km/h (186 mph) top speed for the first Countach LP400. However, like engine power, the top speed was deliberately overrated to overwhelm Ferrari Daytona. Its actual performance was around 170 mph, with 0-60 mph taking 5.6 seconds, very close to but still slower than the front-engined Daytona. Nevertheless, the wild looks of Lamborghini successfully deceived most people, leading them to believe it was the fastest car in the world.

https://www.autozine.org/Archive/Lamborghini/classic/Countach.html
