### ISSUE TITLE
2017 Hennessey Velociraptor 6x6 not worth the price

### ISSUE THREAD

**Issue by ITwasntTP** [fkk-cz/noire_vehicles#277]
for 325k the truck is not worth the price, it barley reaches 100. in irl the smaller version hits a top speed of 165 mph and the basic raptor in la noire hits 150 and has a high acceleration when the velociraptor has a faster 0-60 in irl so it should have a similar top speed to since it has a engine with 200 plus for horse power. the basic 2018 raptor can fit 6 people when the 6x6 can only fit 4 which is a huge downgrade and disappointment. the window tint and turbo upgrades also don't work. the 6x6 has a v6 super twin turbo engine that produces well over 600hp and i feel like the truck only has some basic sounding gta engine

**Comment by ITwasntTP** [comment]
also the nissan titan fits 8 people and its only like 50k, so really the velociraptor should fit 8 people for a 325k truck

**Comment by fkk-cz** [comment]
> 
> 
> for 325k the truck is not worth the price, it barley reaches 100. in irl the smaller version hits a top speed of 165 mph and the basic raptor in la noire hits 150 and has a high acceleration when the velociraptor has a faster 0-60 in irl so it should have a similar top speed to since it has a engine with 200 plus for horse power. the basic 2018 raptor can fit 6 people when the 6x6 can only fit 4 which is a huge downgrade and disappointment. the window tint and turbo upgrades also don't work. the 6x6 has a v6 super twin turbo engine that produces well over 600hp and i feel like the truck only has some basic sounding gta engine

https://github.com/fkk-cz/noire_vehicles/commit/d1aeaa5619debf7df0c7c95513a56e3518b14eae#diff-8615cc8d92354f337b51a8d16b7180534de2da9ad1c92e2ff5f45cc505c8d5f6

should be better, increased target top speed to ~150MPH and improved acceleration
