### ISSUE TITLE
Jaguar E Type too slow for price

### ISSUE THREAD

**Issue by WantedYeti** [fkk-cz/noire_vehicles#278]
jaguar e type should be at least 160 mph or higher for price range of 200k+

**Comment by fkk-cz** [comment]
https://github.com/fkk-cz/noire_vehicles/commit/db2bd9b5ab30f2df3a1a95990b9b93341e4f6d8d#diff-f13339fbaba761917345670e7839f4f60145ca69b93e1c9170e7ffc98c500875

should be better now
