### ISSUE TITLE
Missprint

### ISSUE THREAD

**Issue by MarkusGohome** [fkk-cz/noire_vehicles#279]
I bought a BMW E60 M5 and it told me the speed it could go and it cant go that fast. And tbo i just want my money back.

**Comment by fkk-cz** [comment]
https://github.com/fkk-cz/noire_vehicles/commit/db2bd9b5ab30f2df3a1a95990b9b93341e4f6d8d#diff-52d4f8ef32a3e9f46448a8c127b949700d7eb0c5f57772d4981d2444939201af

fixed the display issue and aligned the car's top speed with more realistic values
