### ISSUE TITLE
SSC TuaTara

### ISSUE THREAD

**Issue by herkkkk** [fkk-cz/noire_vehicles#280]
I'm making this complaint because the speed on the car isn't realistic to the car IRL, the tuatara is the fastest production car in the world hitting 334 and it maxes out at 200 so I just wanted the vehicle speed to get improved.

**Comment by fkk-cz** [comment]
> 
> 
> I'm making this complaint because the speed on the car isn't realistic to the car IRL, the tuatara is the fastest production car in the world hitting 334 and it maxes out at 200 so I just wanted the vehicle speed to get improved.

No vehicle in GTA should go 334MPH, GTA's vehicle physics are already generous enough.. At 200MPH your vehicle is faster than 99% of all vehicles in the game
