### ISSUE TITLE
Dodge Demon

### ISSUE THREAD

**Issue by ITwasntTP** [fkk-cz/noire_vehicles#281]
it needs a much needed acceleration boost, this car holds the record for fastest 0-60 at 2.1 seconds and the turbo doesnt work

**Comment by ITwasntTP** [comment]
there is a huge issues with upgrades at LS customs. you can pretty much only have 1 upgrade at a time. all the performance upgrades stay when you buy them except for the turbo, with cosmetic there is a problem with the horn, window tint, and the roll cage. im the only one in the city that has a roll cage on the inside and i cant get rid of it. with the turbo, horn, and window tint the game makes pick only one so if you try to add another mod it cancels the previous ones you bought. i probably lost over 20k trying to get this to work resetting my parts a already bought

**Comment by ITwasntTP** [comment]
and the charger hellcat has a faster acceleration and top speed by 20mph. hellcats only 95k and i spent 335k on the demon

**Comment by ITwasntTP** [comment]
also the neon headlights dont work if you want a turbo or a horn

**Comment by fkk-cz** [comment]
> 
> 
> there is a huge issues with upgrades at LS customs. you can pretty much only have 1 upgrade at a time. all the performance upgrades stay when you buy them except for the turbo, with cosmetic there is a problem with the horn, window tint, and the roll cage. im the only one in the city that has a roll cage on the inside and i cant get rid of it. with the turbo, horn, and window tint the game makes pick only one so if you try to add another mod it cancels the previous ones you bought. i probably lost over 20k trying to get this to work resetting my parts a already bought

> 
> 
> also the neon headlights dont work if you want a turbo or a horn

This issue has been fixed https://github.com/fkk-cz/noire/commit/e756cd366cfce931bcb0e5306e808590ab092632#diff-79fea71d0afc03e7099a4bb82a0f704259032b89a5f60de4a5c1e45173630970

**Comment by ZacLuxton** [comment]
> and the charger hellcat has a faster acceleration and top speed by 20mph. hellcats only 95k and i spent 335k on the demon

Daytona goes 210, Hellcat 180, Demon 200

**Comment by ZacLuxton** [comment]
https://github.com/fkk-cz/noire_vehicles/commit/e1f5b987943f01dfbcd7398bd452e588f3463ffa

Fixed some issues on the Demon, so that it shouldnt break down so easily
