### ISSUE TITLE
Ferrari 488 pista

### ISSUE THREAD

**Issue by butternut97** [fkk-cz/noire_vehicles#283]
its a bit slow compared to cars in the same price range and the acceleration could be a bit better

**Comment by fkk-cz** [comment]
https://github.com/fkk-cz/noire_vehicles/commit/d1aeaa5619debf7df0c7c95513a56e3518b14eae#diff-73cf4fa934765d1b1e94a15cb89830e9fe2be2e25fe0a5cc47f16bed26c5be7d

acceleration should be better now
