### ISSUE TITLE
Mini Cooper R56

### ISSUE THREAD

**Issue by daisyxox** [fkk-cz/noire_vehicles#284]
The car breaks down just from driving because it's very low to the ground, after exiting LS Customs it glitched and wouldn't even drive forward. It's so bad I can't even use it at all really.

**Comment by fkk-cz** [comment]
https://github.com/fkk-cz/noire_vehicles/commit/db2bd9b5ab30f2df3a1a95990b9b93341e4f6d8d#diff-ed16d685248b329677162328dfc9cffcd208a89271cc928a8f9bec67addfc00d

raised the suspension a bit, should be better now
