### ISSUE TITLE
Agera RS

### ISSUE THREAD

**Issue by Ac3v4** [fkk-cz/noire_vehicles#285]
the agera is quiet slow for a 500k hyper car, the brakes are almost non existent and has troubles with the textures. but the main point is the speed, my Bugatti Veyron which is like half the price is so much faster than it so please adjust it. :)

**Comment by fkk-cz** [comment]
https://github.com/fkk-cz/noire_vehicles/commit/db2bd9b5ab30f2df3a1a95990b9b93341e4f6d8d#diff-4f13532c561643a1e01219b5e61443023104b25b91bef33caaff12087c1da62c

improved the brakes and set the target speed around 200MPH
