### ISSUE TITLE
2020 Tesla Roadster slower than Model X

### ISSUE THREAD

**Issue by imcoty** [fkk-cz/noire_vehicles#287]
the Roadster can't get over 145 while the Model X has no problem. i know the handling is a tad better than the Model X but was wondering if the roadster being lessened in speed was intentional.

**Comment by fkk-cz** [comment]
It's a 200k electric car that can go 0-145 in < 5 seconds, seems fair to me?

**Comment by imcoty** [comment]
cool i was just making sure the top speed of 145 was intentional
