### ISSUE TITLE
Dodge Challenger R/T

### ISSUE THREAD

**Issue by BGS-Volkov** [fkk-cz/noire_vehicles#288]
Cosmetics not working/saving:
-Window Tint

Upgrades not working/saving:
Armor level 4+
Turbo

**Comment by fkk-cz** [comment]
fixed in https://github.com/fkk-cz/noire/commit/e756cd366cfce931bcb0e5306e808590ab092632#diff-79fea71d0afc03e7099a4bb82a0f704259032b89a5f60de4a5c1e45173630970
