### ISSUE TITLE
BMW M5 F90 2018

### ISSUE THREAD

**Issue by ToxicPanicTV** [fkk-cz/noire_vehicles#289]
Can't install Turbo and Armor Level 5.

Sometimes I can install Turbo but it disappears again after I put it in the garage or use an Repair Kit on it.

And I lost my VW GOLF GTI. It disappeared a few weeks ago and the Admins did not help me. Got nothing for losing my car.

**Comment by fkk-cz** [comment]
> 
> 
> Can't install Turbo and Armor Level 5.
> 
> Sometimes I can install Turbo but it disappears again after I put it in the garage or use an Repair Kit on it.
> 
> And I lost my VW GOLF GTI. It disappeared a few weeks ago and the Admins did not help me. Got nothing for losing my car.

the turbo/armor issues with LS customs have been fixed https://github.com/fkk-cz/noire/commit/e756cd366cfce931bcb0e5306e808590ab092632#diff-79fea71d0afc03e7099a4bb82a0f704259032b89a5f60de4a5c1e45173630970

as for the GTI, make a ticket in discord about that
