### ISSUE TITLE
2013 Audi RS7 

### ISSUE THREAD

**Issue by Mynameischug** [fkk-cz/noire_vehicles#290]
There are no upgrades at all available for the vehicle, cosmetics are there, just not any upgrades to the engine, armor, etc...

**Comment by fkk-cz** [comment]
https://github.com/fkk-cz/noire_vehicles/commit/d1aeaa5619debf7df0c7c95513a56e3518b14eae#diff-962ec93b40a561e20fbc6ed4b0b0e0cb53a138e025ad30c4dd2b0fd79384f6c7

should be fixed, was a duplicate modkit ID
