### ISSUE TITLE
2020 amg gt black series buff

### ISSUE THREAD

**Issue by SpunkySx** [fkk-cz/noire_vehicles#291]
the car acceleration ok and the top speed tops out at 165. but the car is a Mercedes supercar that can go over 200+ mph. Can u buff the acceleration a little and the top speed a higher number especially for a supporter car that's 346k.

**Comment by SpunkySx** [comment]
and maybe a little more of a beefer audio from the engine

**Comment by SpunkySx** [comment]
https://www.youtube.com/watch?v=vwcFYD5GzfA&t=150s a video of a guy testing the speed of the car that's not by Mercedes themselves

**Comment by ZacLuxton** [comment]
#349
