### ISSUE TITLE
BMW M2 non-supporter

### ISSUE THREAD

**Issue by LilPipo** [fkk-cz/noire_vehicles#292]
Maybe upgrade the acceleration and the top speed on the car because its way to slow for the price, IRL the car is super fast so i would like to see improvements on that car. 

kind regards, Lil Pipo

**Comment by fkk-cz** [comment]
> IRL the car is super fast

Top speed is limited to 250 km/h (155 mph) but can be extended to 270 km/h (168 mph) with the optional M Driver's package. The M2 was used as a safety car in the 2016 MotoGP season.

hardly 'super fast', top speed in game is limited to 155 mph, just like real life equivalent
