### ISSUE TITLE
Mercedes EQC400

### ISSUE THREAD

**Issue by mrmonkeyman2007** [fkk-cz/noire_vehicles#293]
Mercedes EQC400 is super gliched you can only sit 2 players in it even do ita 4 door. 
its an "electric car" with a engine sound. 
you dont sit probarly in the seeds
And it only has 250 trunk space but normaly SUVs have 750

**Comment by fkk-cz** [comment]
> 
> 
> Mercedes EQC400 is super gliched you can only sit 2 players in it even do ita 4 door.
> its an "electric car" with a engine sound.
> you dont sit probarly in the seeds
> And it only has 250 trunk space but normaly SUVs have 750

Replaced the incorrect audioHash and vehicleClass, not sure about the second part.

https://github.com/fkk-cz/noire_vehicles/commit/6328aa214cfabad0ce966648a3918f32564b2fff#diff-b61d2027fc25c5ec5dabfe49b4cc55019ad587933a88662ec77524404cebf3a0
