### ISSUE TITLE
focus RS color customization

### ISSUE THREAD

**Issue by zestyspade** [fkk-cz/noire_vehicles#294]
the color on the ford focus RS is only different shades and textures of black no matter what color you choose, it has no pigment. this has been a problem since i started playing but i just got the car and it annoys me that my car can only be black.

**Comment by fkk-cz** [comment]
Looks like a duplicate/invalid modkit ID. Should be fixed now

https://github.com/fkk-cz/noire_vehicles/commit/6328aa214cfabad0ce966648a3918f32564b2fff#diff-73ff3937b748984c59d3bb3c38e034252d46cd65ffdb2520cb864786b25799e2
