### ISSUE TITLE
tesla roadster is slow

### ISSUE THREAD

**Issue by sotobeat** [fkk-cz/noire_vehicles#295]
the tesla roadster goes faster then the model x in real life but goes 145 top speed in game i was wondering is the tesla could ne brought up in speed

**Comment by imcoty** [comment]
last time car was updated the immediate drag was changed but it still hard caps at 145. 

ok with it not being the fastest car but the model X being 20 MPH faster is just weird.

**Comment by fkk-cz** [comment]
see https://github.com/fkk-cz/noire_vehicles/issues/353
