### ISSUE TITLE
Ferrari F430 

### ISSUE THREAD

**Issue by Bobiiz** [fkk-cz/noire_vehicles#296]
For 770k this car is kinda slow... 192mph? Cmon guys, alfa Romeo giulia goes 189. Imo 205-210mph would be great. For this price of course.

**Comment by fkk-cz** [comment]
What's the difference between 192MPH and 205MPH? (besides 13MPH, of course...) The Giulia should not go 189MPH, given its cheap price.

**Comment by fkk-cz** [comment]
See https://github.com/fkk-cz/noire_vehicles/issues/306#issuecomment-846497372
