### ISSUE TITLE
Mercedes-Benz A45 AMG armor buff

### ISSUE THREAD

**Issue by TheTerminator1999** [fkk-cz/noire_vehicles#300]
The armor of this car is very weak even with upgrades, you hit one car and you’re smoking.

**Comment by fkk-cz** [comment]
https://github.com/fkk-cz/noire_vehicles/commit/0700e2da9ae0e9551f800657dc01286fc590f47e#diff-d6e744f509110a803b75232905ff63b3d2f6f005bd922ce00cc7a3dc49fccb7e

fixed
