### ISSUE TITLE
NIO nerfed too hard!

### ISSUE THREAD

**Issue by ryan16626** [fkk-cz/noire_vehicles#301]
Hello,

The NIO has been nerfed way to hard. Everyone I have talked to who owns one in addition to myself feels the same way. Any way you can compromise and add some acceleration and top speed back? 

Thanks for your time and attention :)

**Comment by fkk-cz** [comment]
See my response in https://github.com/fkk-cz/noire_vehicles/issues/307#issuecomment-846495626
