### ISSUE TITLE
Dodge Challenger Hellcat for Supporter 

### ISSUE THREAD

**Issue by apricates** [fkk-cz/noire_vehicles#303]
It goes like 160-170 and irl it goes 203. The acceleration is pretty slow and since it costs more than hellcat charger it should be at least on par.

**Comment by cambocac** [comment]
I agree about the acceleration needing to be increased. However I believe the hellcat was tuned down recently to reduce the top speed, as people were abusing it to commit robberies and running from police - could be mistaken

**Comment by apricates** [comment]
> I agree about the acceleration needing to be increased. However I believe the hellcat was tuned down recently to reduce the top speed, as people were abusing it to commit robberies and running from police - could be mistaken

The charger hellcat can reach 210 easily on the highway but the dodge challenger costs more but it goes significantly slower

**Comment by fkk-cz** [comment]
Brought the hellcatlb in line with the srtday20.

https://github.com/fkk-cz/noire_vehicles/commit/0700e2da9ae0e9551f800657dc01286fc590f47e#diff-3e5583407add1335261df8a4e835a900b33aede3c513b9e9aa2c9905bcb47d5f

Also swapped the audioHash so the vehicles sound the same.
