### ISSUE TITLE
2009 bugatti veyron in supporter vehicles 

### ISSUE THREAD

**Issue by trayvonblack** [fkk-cz/noire_vehicles#305]
its a slow car for being a bugatti would love to see it get faster in acceleration and top speed

**Comment by fkk-cz** [comment]
https://github.com/fkk-cz/noire_vehicles/blob/d1aeaa5619debf7df0c7c95513a56e3518b14eae/DATA/bug09_data/handling.meta#L7-L17

On paper this vehicle has a target speed of 205MPH with next to nothing for drag. For a car that's woefully under priced at 256k, don't be greedy.
