### ISSUE TITLE
FERRARI F430 - Slow and zero upgrades.

### ISSUE THREAD

**Issue by rolflogan42** [fkk-cz/noire_vehicles#306]
I cant upgarde my ferrari 430s, and the car is slow af to be a  430S. If i crash my car in the slightest it needs a repair kit. Please add upgrades to it and make the car faster. Remember this car is 775k at the pdm.

**Comment by fkk-cz** [comment]
https://github.com/fkk-cz/noire_vehicles/commit/0700e2da9ae0e9551f800657dc01286fc590f47e#diff-0798621e2279b734216c3aaa1b7f845850b7b034a4f655d58a90910e7d48d54bR27

Trying a new modkit ID, should have upgrades now



> If i crash my car in the slightest it needs a repair kit.

https://github.com/fkk-cz/noire_vehicles/blob/0700e2da9ae0e9551f800657dc01286fc590f47e/DATA/f430s/handling.meta#L41-L44

You sure? Damage values are standard.
