### ISSUE TITLE
Drag Coefficant on NIO 12.43? 

### ISSUE THREAD

**Issue by Kingaustin161** [fkk-cz/noire_vehicles#307]
I understand this was to nerf the speed on the NIO but this is a $335,000 in-game ($1,250,000 IRL) electric car, It should be the best electric car in here for that price. it was really good and the acceleration felt like that of an electric car but now I feel like I'm driving my grandma's Buick. nerfed way too hard.

**Comment by fkk-cz** [comment]
> 
> 
> I understand this was to nerf the speed on the NIO but this is a $335,000 in-game ($1,250,000 IRL) electric car, It should be the best electric car in here for that price. it was really good and the acceleration felt like that of an electric car but now I feel like I'm driving my grandma's Buick. nerfed way too hard.

The NIO appears to have some very strange handling values, see:
https://github.com/fkk-cz/noire_vehicles/blob/d1aeaa5619debf7df0c7c95513a56e3518b14eae/DATA/ep9_data/handling.meta#L7-L17

Electric vehicles are very hard to get right as there's obviously only one drive gear, which leads to using an insanely high `fInitialDriveForce` for the car to even be usable. Any other vehicle with a `fInitialDragCoeff` value of 12 would surely not even come close to hitting the target top speed, which incidentally, is also inaccurate (fInitialDriveMaxFlatVel = 200 => 200 * 0.82 = 164 MPH).

> but now I feel like I'm driving my grandma's Buick. nerfed way too hard.

No need for the over dramatization, I just tested the vehicle and it is the only electric car that can reliably do 200 MPH+, especially given curb boosting. For a vehicle that is 335k in game, I think that is more than reasonable and fair given the price and performance relative to other (electric and non-electric) vehicles in the price range.
