### ISSUE TITLE
2016 BMW M2 F22

### ISSUE THREAD

**Issue by laxreese33** [fkk-cz/noire_vehicles#308]
has no engine, armour, and brake upgrades.

**Comment by ZacLuxton** [comment]
![image](https://user-images.githubusercontent.com/79383480/124830282-8e803f00-df71-11eb-93b8-4654efe3d5dc.png)

![image](https://user-images.githubusercontent.com/79383480/124830303-963fe380-df71-11eb-87bc-ff953ff20003.png)

![image](https://user-images.githubusercontent.com/79383480/124830314-9a6c0100-df71-11eb-9f9c-3e42a4b50c4d.png)


All seem fine to me
