### ISSUE TITLE
Dodge Viper ST

### ISSUE THREAD

**Issue by StevieStyles** [fkk-cz/noire_vehicles#310]
so the 465K dodge viper st is a bit slow for the price and a bit unrealistic. The car is way faster irl. I think an acceleration buff would be a good fix....being the top speed is good just takes a year to get there. plz help! tired of getting smoked by cars half the price of the viper.

**Comment by fkk-cz** [comment]
https://github.com/fkk-cz/noire_vehicles/blob/834d1a2250015c4fc8704458ee8a7d335317b12f/DATA/viper/handling.meta#L12-L16

these vehicle stats are already generous enough, any further improvements would create an imbalance.
