### ISSUE TITLE
2018 Lambo Urus

### ISSUE THREAD

**Issue by StevieStyles** [fkk-cz/noire_vehicles#311]
So the trunk space in the urus is .5....the truck has a very nice trunk irl so i was curious if the trunk space could be buffed to .75

**Comment by fkk-cz** [comment]
> 
> 
> So the trunk space in the urus is .5....the truck has a very nice trunk irl so i was curious if the trunk space could be buffed to .75

https://github.com/fkk-cz/noire_vehicles/commit/128fd0891fce7b20d1a336e95afef10fcfb1f3e1#diff-6b10844c2d9f1b6a6bb1e018e10e5b6b540d6fdfa7d3cc9fa6da5e705cd5e236
