### ISSUE TITLE
2021 BMW M4 Competition BUG

### ISSUE THREAD

**Issue by dellfu123** [fkk-cz/noire_vehicles#312]
Please take a look at the textures on the car i can not change the color of the car and the car looks like its smudged with dirt all over it 
![unknown](https://user-images.githubusercontent.com/84749411/119414494-a8b1d680-bcbd-11eb-868a-57bd3ab27c06.png)

**Comment by ZacLuxton** [comment]
This was fixed when vehicles were re-textured
