### ISSUE TITLE
koenigsegg gemera is like paper

### ISSUE THREAD

**Issue by SpunkySx** [fkk-cz/noire_vehicles#314]
the performance doesn't need to be touched but the car armor idk if it is working properly if i get one sign or smallest crash and my car is broken and needs to be repaired.

**Comment by fkk-cz** [comment]
https://github.com/fkk-cz/noire_vehicles/blob/128fd0891fce7b20d1a336e95afef10fcfb1f3e1/DATA/gemera_data/handling.meta#L41-L44

damage values are standard.
