### ISSUE TITLE
Ferrari F12 Berlinetta

### ISSUE THREAD

**Issue by Beno7777** [fkk-cz/noire_vehicles#315]
The acceleration is kinda slow for its price and I can´t change its color, when I try to change the color its only changing in a grey shade. Also it should sound a bit louder.

**Comment by fkk-cz** [comment]
https://github.com/fkk-cz/noire_vehicles/commit/128fd0891fce7b20d1a336e95afef10fcfb1f3e1#diff-44212b57f9bf8d2d3b1fa935bb2dd796e3fe329340f4dfe744ebbdb28dc0e0ef

increased fInitialDriveForce, in terms of the color go to LS customs and change the stickers on the car (up/down arrows).
