### ISSUE TITLE
Tesla Model X

### ISSUE THREAD

**Issue by EveEnchooli** [fkk-cz/noire_vehicles#316]
Can we potentially make the model x a 5 or 6 seater considering that the car is supposed to seat 7 (even if it doesn't look comfy.) I think it makes sense for it to be able to seat more people, especially when the Roadster seats 4 and people's heads stick out.

**Comment by ZacLuxton** [comment]
There is no 6 seater vehicles that is fit for this, so unfortunately this is something we can not fix
