### ISSUE TITLE
lamborghini murcielago

### ISSUE THREAD

**Issue by butternut97** [fkk-cz/noire_vehicles#317]
the brakes are pretty bad and the car seems heavy i would assume that has something to with drag and the car could go a bit faster the fastest i got it to was 170 i think like 190 would be fair i know this a older car but i thought i would at least try

**Comment by fkk-cz** [comment]
https://github.com/fkk-cz/noire_vehicles/commit/128fd0891fce7b20d1a336e95afef10fcfb1f3e1#diff-c728971ed361f4d42abe5b7dcf7243e144bd4a0a707321344c9f4e0144cf4bf2

increased fBrakeForce
