### ISSUE TITLE
2019 Aston Martin Vantage

### ISSUE THREAD

**Issue by Leetsauce** [fkk-cz/noire_vehicles#319]
Every time I repair the car the hood stays open a little bit, it will not fully close.  Any way to fix that?

**Comment by Leetsauce** [comment]
![image](https://user-images.githubusercontent.com/84821570/119594257-71205880-bda9-11eb-9b9a-abad03a906c6.png)

**Comment by TeeJizzlee** [comment]
t /hood

**Comment by fkk-cz** [comment]
See above reply.
