### ISSUE TITLE
2017 bentley bentayga

### ISSUE THREAD

**Issue by Rojingrey** [fkk-cz/noire_vehicles#320]
speed could be better goes about 160-165mph with upgrades,and irl goes 187mph stock.Speed could definitely be increased counting the fact that it cost 425k, yet there's a Volvo xc90 in game that goes over 210mph for 90k, and irl it goes 130mhp.(don't know if this matters but i got the non sporty looking version,still the same specs i gave).

**Comment by fkk-cz** [comment]
https://github.com/fkk-cz/noire_vehicles/commit/128fd0891fce7b20d1a336e95afef10fcfb1f3e1#diff-5912d9822b8cf3c0f8535541bc03531d61fb76c0d3d7a71d675479aa977728da

Just realized there's 2 Bentaygas with the same price but different handling.

Also nerfed the XC90: https://github.com/fkk-cz/noire_vehicles/commit/128fd0891fce7b20d1a336e95afef10fcfb1f3e1#diff-6f950aed84a3a3a7e06d5f5b64d408dbf33851b89fbab6de42c63e2c95d6ad51
