### ISSUE TITLE
BMW M8

### ISSUE THREAD

**Issue by boy711** [fkk-cz/noire_vehicles#321]
the car has no upgrade for engine suspension etc,

**Comment by fkk-cz** [comment]
https://github.com/fkk-cz/noire_vehicles/commit/128fd0891fce7b20d1a336e95afef10fcfb1f3e1#diff-0554270384ab73ba9711181cc5a01698ea983c9d6d6f74fca360b92701e5c10c

had a duplicate modkit ID

**Comment by fkk-cz** [comment]
fixed
