### ISSUE TITLE
porsche 2019 gtr2 rs

### ISSUE THREAD

**Issue by SpunkySx** [fkk-cz/noire_vehicles#322]
the acceleration on the car is not good especially for a Porsche which is known for that the car burns out at the start making it the slowest of all the Porsche when it should be the quickest

**Comment by fkk-cz** [comment]
https://github.com/fkk-cz/noire_vehicles/commit/128fd0891fce7b20d1a336e95afef10fcfb1f3e1#diff-197be8255d27288ca779e675755d50d3fc64d6b6aea3d0cd0421dd8d57c597a7

reduced fLowSpeedTractionLossMult
