### ISSUE TITLE
1968 Pontiac Firebird

### ISSUE THREAD

**Issue by butternut97** [fkk-cz/noire_vehicles#323]
car has no traction and the brakes are very bad

**Comment by fkk-cz** [comment]
https://github.com/fkk-cz/noire_vehicles/commit/128fd0891fce7b20d1a336e95afef10fcfb1f3e1#diff-2621d907efa82c11de27b120bd03e3de65c45307f27e86647237e266d4c69a42

improved traction and braking

**Comment by butternut97** [comment]
the car is still broken same issues
