### ISSUE TITLE
Dodge Viper ST

### ISSUE THREAD

**Issue by TeeJizzlee** [fkk-cz/noire_vehicles#325]
top speed is good but can we get a buff on acceleration considering it is almost a 500k car.

**Comment by fkk-cz** [comment]
> 
> 
> top speed is good but can we get a buff on acceleration considering it is almost a 500k car.

https://github.com/fkk-cz/noire_vehicles/blob/128fd0891fce7b20d1a336e95afef10fcfb1f3e1/DATA/viper/handling.meta#L12-L16

the acceleration-related values are already very generous as-is
