### ISSUE TITLE
Lamborghini Gallardo Upgrades/Customization/Speed

### ISSUE THREAD

**Issue by SlothDolphin** [fkk-cz/noire_vehicles#328]
Paid more money for this over the GTR and the car actually goes slower then the GTR. Only upgrade is Turbo with no other upgrades. Would love to see some customization to the car also! Acceleration is slow. Please just look into it atleast!! Thank you! <3

**Comment by fkk-cz** [comment]
Fixed the 'no upgrades' issue https://github.com/fkk-cz/noire_vehicles/commit/128fd0891fce7b20d1a336e95afef10fcfb1f3e1#diff-f8242e2ae371c8c9b2596b2a0c06aad61832e5d5fef239b3792149e72e8407cd

In terms of the speed, it's the cheapest Lamborghini in PDM and shouldn't be very fast
