### ISSUE TITLE
Hennessey Venom GT

### ISSUE THREAD

**Issue by ITwasntTP** [fkk-cz/noire_vehicles#329]
The tail lights have an issue, theres 5 red dots in line on each side covering the actual two taillights on each side.
The car needs a higher top speed and a little bit more acceleration.
The Hennessey Venom GT is the worlds 3rd fastest production car at 270mph

**Comment by ITwasntTP** [comment]
And the headlights are a bit funky because they shine through the front grill like underglow

**Comment by ITwasntTP** [comment]
the car barely goes 180

**Comment by ITwasntTP** [comment]
I dont expect the car to go 270 but the fact the the dodge hellcat challenger and charger, demon, lambo perfermonte, mclaren p1 and 720, and the audi r8 and probably many other cars all go 200-240mph and the Vemon GT only goes 180 if that.

**Comment by ITwasntTP** [comment]
If you could get the car to sound more like the bugatti veyron that be great since its a 6.6 V8 and not a ferrari

**Comment by ZacLuxton** [comment]
> And the headlights are a bit funky because they shine through the front grill like underglow

This is a model issue, something that we can not fix,

> If you could get the car to sound more like the bugatti veyron that be great since its a 6.6 V8 and not a ferrari

The Veyron has a monster truck audio hash: 
https://github.com/fkkcz/noire_vehicles/blob/ada0b784e598793b08b82f8fb878071ffc86b1df/DATA/bug09_data/vehicles.meta#L18, I have changed this so that it sounds like a bit more realistic.

Will take a look at the handling so that it goes around 190

**Comment by luiisgg** [comment]
Please give this car some love it turns like a TrashMaster and you need the length of the map to ever reach 6th gear :(

**Comment by ITwasntTP** [comment]
They wont love this car they just love the hellcats and other cars, the damn charger goes 210 when in real life its only a 392 V8 that doesnt even go over 150, they only wanna make it 190 when in real life it goes 270. Its really a slap in the face to the players that grinded to get the more expensive car for it not to be what it really is, and then favor the cheaper cars to be unrealistic in real life aspects and be better then the expensive cars that we worked hard for

**Comment by ZacLuxton** [comment]
https://github.com/fkk-cz/noire_vehicles/commit/7af4e342c1f2499547a1852221f0a88343d7b68d

**Comment by ZacLuxton** [comment]
Should do around 190 maxed out
