### ISSUE TITLE
Dodge demon roll cage probleme

### ISSUE THREAD

**Issue by GamaPrime** [fkk-cz/noire_vehicles#332]
I'm having the same problem as my friend with a Dodge Demon. It automatically added a ugly ass roll cage and it cant be replaced. Idk if it is a duplicate problem or a mod problem. 

Gama_prime

**Comment by fkk-cz** [comment]
> 
> 
> I'm having the same problem as my friend with a Dodge Demon. It automatically added a ugly ass roll cage and it cant be replaced. Idk if it is a duplicate problem or a mod problem.
> 
> Gama_prime

PAGE UP -> turn extra 2 off
