### ISSUE TITLE
Mass PDM list

### ISSUE THREAD

**Issue by ZacLuxton** [fkk-cz/noire_vehicles#335]
Ferrari FXXK -> 125mph, irl speed 217mph.

Alfa Romeo Giulia -> Classed as super, needs to be changed to sports.

Audi Q8 -> Top speed 110, irl speed 155, needs to have a bit better initial acceleration 

Bentley Continental  GT - Top Speed 115, IRL speed 195.

Bentley Bentayga (2017) - Top Speed 130, IRL speed 187. Possible decrease in price tag would be justified?

Volvo XC90 - Top Speed 180, IRL speed 136.

BMW M5 -> Instantly climbs up and then holds down gear for a few seconds.

Audi R8 -> Top Speed 200+ Maxed out, especially for the price, rather needs to be nerfed, or price needs to go up.

Rimac C Two -> It’s an electric vehicle, needs to have 0 fuel

Volkswagen Golf 7.5R -> Needs to be changed to Compact / Sport type, currently classed as ‘super’

VW Passat -> Decrease in speed asap, goes almost 200mph

Lexus LFA -> this thing is a drift car right now…

**Comment by ZacLuxton** [comment]
Brabham BT62-R top speeds out 140ish, irl speed 200mph

**Comment by fkk-cz** [comment]
https://github.com/fkk-cz/noire_vehicles/commit/834d1a2250015c4fc8704458ee8a7d335317b12f

Fixed almost all of these issues, with the exception of the Bentley/BMW.
