### ISSUE TITLE
GO Kart

### ISSUE THREAD

**Issue by EveEnchooli** [fkk-cz/noire_vehicles#336]
can't change paint color, and its not in stickers either :(

**Comment by EveEnchooli** [comment]
also no neons :(

**Comment by ZacLuxton** [comment]
The issue is, is that it's a go cart, Its not meant to have neons, if you look at the go kart's data files, it does not have the carcols.meta file which is the reason why you probably cant upgrade it, change colour to it etc;

https://github.com/fkk-cz/noire_vehicles/tree/master/DATA/gokart2_data
