### ISSUE TITLE
Mazda Miata

### ISSUE THREAD

**Issue by jqde** [fkk-cz/noire_vehicles#338]
There is little to no customization including wheels and body mods which I believe as a Miata there should be a lot of body customization. Also the only performance mod for the car is a turbo which I haven't found to make a difference

**Comment by fkk-cz** [comment]
https://github.com/fkk-cz/noire_vehicles/commit/834d1a2250015c4fc8704458ee8a7d335317b12f#diff-c828e74358f4a27a480e734bd9ab3b708677ce1c0d1b17c9ad020aeca096edd5

trying a new modkit ID

**Comment by fkk-cz** [comment]
fixed
