### ISSUE TITLE
Huracan Evo Spyder

### ISSUE THREAD

**Issue by ItzHunterrrrr** [fkk-cz/noire_vehicles#341]
Car could have a small buff to acceleration and a decent buff to speed considering its 1.1m and only goes 200... i have 4 other cars that go faster and are less than half the price

**Comment by fkk-cz** [comment]
> 
> 
> Car could have a small buff to acceleration and a decent buff to speed considering its 1.1m and _only_ goes 200... i have 4 other cars that go faster and are less than half the price

_only_ goes 200? do you realize that's faster than 99% of vehicles in GTA space?
