### ISSUE TITLE
lamborghini gallardo Upgrades/No Horn Change

### ISSUE THREAD

**Issue by SlothDolphin** [fkk-cz/noire_vehicles#342]
I know you guys said Upgrades were added but I dont see upgrades along with now I cannot change my horn. I would love to see  more customization in all cars tbh. I only pay 10$ a month though so I have no say lol.

**Comment by fkk-cz** [comment]
https://github.com/fkk-cz/noire_vehicles/commit/834d1a2250015c4fc8704458ee8a7d335317b12f#diff-f8242e2ae371c8c9b2596b2a0c06aad61832e5d5fef239b3792149e72e8407cd

trying a new modkit ID

**Comment by Jaynissan** [comment]
issue wasnt fixed
