### ISSUE TITLE
Mclaren P1 GTR

### ISSUE THREAD

**Issue by xFuziii** [fkk-cz/noire_vehicles#345]
hello,

As u can see i bought the mclaren P1 GTR for 1250000.
The handling and the braking are insane but the only thing i miss is speed and asceleration so if u can boost this i would really appreciate that bcs in RL it goes 225 MPH and 0-60 in 2.4sec.

ty and have a nice day

**Comment by fkk-cz** [comment]
https://github.com/fkk-cz/noire_vehicles/commit/834d1a2250015c4fc8704458ee8a7d335317b12f

should be better now

**Comment by xFuziii** [comment]
don't feel any changes...still goes 180mph maybe the asceleration is a little better but that's it. we did a race the other day and i lost all of them and those cars were around 300K while mine was 1m250k so yeah think i'm gonna make a ticket for it then if that's cool so i dont lose my money
