### ISSUE TITLE
2019 McLaren Senna Buff/Modification

### ISSUE THREAD

**Issue by YungNino** [fkk-cz/noire_vehicles#347]
I want to request some modifications/buffs for the McLaren Senna. 2019 I believe.  It's really quiet. I really like the sound of the McLaren P1 GTR, or a similar sound, something loud would be great.

Also, I feel the acceleration is a bit slow and perhaps the top speed could be a little higher. I say this because my $525,000 2017 Lambo Terzo Millenio has way faster acceleration and top speed at a cheaper price point. 

The turning as well could be better.

Thank you

NEW

@Yung Nino
I want to request some modifications/buffs for the McLaren Senna. 2019 I believe. For $715,000 I feel it's pretty quiet. I really like the sound of the McLaren P1 GTR, or a similar sound, something louder would be great.  Also, I feel the acceleration is a bit slow and perhaps the top speed could be a little higher. I say this because my $525,000 2017 Lambo Terzo Millenio has way faster acceleration and top speed at a cheaper price point.   The turning as well could be better.  Thank you(edited)

**Comment by YungNino** [comment]
Should I expect a response or how do I know if my request has been accepted or rejected?

**Comment by ZacLuxton** [comment]
The reason why it was so quiet was because the audio hash was the limo;

			<audioNameHash>STRETCH</audioNameHash>

This has now been changed to a louder hash, #414 

The vehicles irl top speed goes 220 in perfect / track conditions. Upon testing the vehicle out, I have managed to get the vehicle up to 200mph fully maxed out down a straight line of road
