### ISSUE TITLE
BMW i8

### ISSUE THREAD

**Issue by KCurt420** [fkk-cz/noire_vehicles#348]
Love the car but the acceleration is way too slow for this car its ways faster then that, same with the top speed it says top speed is 176 but i can barely hit 170

**Comment by KCurt420** [comment]
it hits 200 in real life and i htought it was an eletric car i could be wrong?!

**Comment by KCurt420** [comment]
mainly just want the acceleration for this car to be fixed

**Comment by KCurt420** [comment]
I just raced a 4 door suv and it smoked the i8 this thing needs buffed please lol

**Comment by fkk-cz** [comment]
> How fast can a BMW i8 go?
> 250 km/h
> Its top speed is electronically limited to 250 km/h (155 mph) and is expected to go from 0 to 100 km/h (0 to 60 mph) in 4.6 seconds.

source: google
