### ISSUE TITLE
AMG GT Black Series

### ISSUE THREAD

**Issue by Coopshoots** [fkk-cz/noire_vehicles#349]
So I had the AMG GT S and I recently upgraded to the AMG GT Black Series. It is almost double the price and it goes about the same speed. I think that the Black Series should be able to go over 200 because there are a lot of cars that are cheaper that are a lot faster. Thank you.

**Comment by ZacLuxton** [comment]
https://github.com/fkk-cz/noire_vehicles/commit/5c4fa5862343d27b04f8818dca86ad5196e37d39 - Should do around 200 maxed out
