### ISSUE TITLE
Chevrolet C-10 Custom

### ISSUE THREAD

**Issue by Scooterbug7** [fkk-cz/noire_vehicles#350]
The truck doesn't have breaks and it doesn't turn, also the tires have almost no grip

**Comment by fkk-cz** [comment]
this has been an issue for months, no idea how a vehicle with
https://github.com/fkk-cz/noire_vehicles/blob/8ac774937cea817e130527a10cb80b0acaae846f/DATA/c10custom_data/handling.meta#L18-L19

can have no brakes
