### ISSUE TITLE
1973 Porsche 9/11 no upgrades.

### ISSUE THREAD

**Issue by EricTheButcher** [fkk-cz/noire_vehicles#351]
The 1973 Porsche 9/11 supporter car doesnt have any upgrades at all. Can you please atleast add Armor to it because it breaks down so fast.

**Comment by fkk-cz** [comment]
> 
> 
> The 1973 Porsche 9/11 supporter car doesnt have any upgrades at all. Can you please atleast add Armor to it because it breaks down so fast.

https://github.com/fkk-cz/noire_vehicles/commit/834d1a2250015c4fc8704458ee8a7d335317b12f#diff-248a42a3fcff300a9647582f408f0d721d65d0b26be847a99427fc9ea4fe380d

trying a new modkit ID

**Comment by fkk-cz** [comment]
fixed
