### ISSUE TITLE
Toyota Supra

### ISSUE THREAD

**Issue by Ac3v4** [fkk-cz/noire_vehicles#354]
Toyota supra is like 350,000 and is very slow, it only goes like 160 and irl they can be upgraded heavily. if i can either get my money back or if it can be a big buff it would be much appreciated seeing as there's hardly any in the city, thanks :)

**Comment by Ac3v4** [comment]
i also wouldnt mind if the turning/handling is not too good but the speed should be much better

**Comment by fkk-cz** [comment]
Just tested the vehicle, was able to reach a top speed of about 170-180 MPH, which, for the price range, is totally appropriate.

**Comment by fkk-cz** [comment]
https://github.com/fkk-cz/noire_vehicles/commit/2bc91cd8b525a9adef5a97a17404af52ae7fc907#diff-7815995d70000afcabd1d679a53c057b9f6dfeac928dbbaaaa4fe1794ed2cc12

that being said, a little higher top speed never hurts
