### ISSUE TITLE
2004 Hummer H1 

### ISSUE THREAD

**Issue by JohnLocker23** [fkk-cz/noire_vehicles#356]
No customization options are available for example no window tint, no wheel customization, whenever you buy a horn it doesn't set it as the new horn. There should be a tire and ladder combo on top of the roof of the Hummer there is no option to add that the only way to get that is buy buying it at PDM same goes with the light bar option on top as well. There are no wheel options that are given nor color. Vehicle upgrades the only upgrade available was a turbo.

**Comment by fkk-cz** [comment]
https://github.com/fkk-cz/noire_vehicles/tree/master/DATA/hummer_data

looks like there's no carcols.meta for this vehicle, which explains the lack of upgrades. You can use the vehicle extra menu (PGUP) to toggle the tire/ladder combo.
