### ISSUE TITLE
2017 Koenigsegg Agera RS

### ISSUE THREAD

**Issue by james77610** [fkk-cz/noire_vehicles#358]
Was just wondering if you could increase the brakeforce on the 2017 koenigsegg agera rs as it takes a very long time to slow down at times. Also, acceleration feels a little slow compared to vehicles half the price.

**Comment by fkk-cz** [comment]
https://github.com/fkk-cz/noire_vehicles/commit/2bc91cd8b525a9adef5a97a17404af52ae7fc907#diff-4f13532c561643a1e01219b5e61443023104b25b91bef33caaff12087c1da62c

Fixed the brakes and boosted the drive force
