### ISSUE TITLE
Tesla Roadster (again)

### ISSUE THREAD

**Issue by Jayson1800** [fkk-cz/noire_vehicles#359]
I know my issue got closed, the handling and brakes got improved, excepted the top speed. In-game, the model of the roadster is the second generation that has the roof on top. There are some videos helping it showing that the top speed is fast. the roadster beats a Bugatti and a Ferrari. 

Tesla vs LaFerarri - https://www.youtube.com/watch?v=f2H1l9EzGQ8
Tesla vs Bugatti Chiron - https://www.youtube.com/watch?v=53WrZqIc4aw&t=89s

La Ferrari top speed is 350 km/h (261 mph)
Bugatti Chiron top speed is 261 mph

If you have the second generation model car in-game, it should have the top speed as well.

**Comment by Jayson1800** [comment]
If you can't do that, I want a full refund on my tesla roadster, because I know I could get something better at the dealership. But I don't want to.

**Comment by Jayson1800** [comment]
A reasonable top speed for the price I payed for the car should be at least 185-190

**Comment by ZacLuxton** [comment]
For the price, 150 is fair, if you want a refund, sell it back to PDM
