### ISSUE TITLE
Rx-7 Veilside 

### ISSUE THREAD

**Issue by Fasxic** [fkk-cz/noire_vehicles#360]
The handling and brakes for the veilside are kinda messed up and pretty hard to use maybe you can fix that up

**Comment by TheK0opa** [comment]
Is it worth buying i was considering

**Comment by fkk-cz** [comment]
https://github.com/fkk-cz/noire_vehicles/commit/ada0b784e598793b08b82f8fb878071ffc86b1df#diff-3027988e3c7b9855e0d767fed27078e33754e34de77783ef99268a71105f51be

raised traction, braking should be improved
