### ISSUE TITLE
F350 6x6 Bugged Seating

### ISSUE THREAD

**Issue by starbvck** [fkk-cz/noire_vehicles#362]
For some reason, only sometimes you can have a single passenger in the truck and other times no one can even get into the truck with you. I figured with the enormous size of that thing it would be at least like the titan truck where you can fit 8 people in it. Hopefully this can be fixed asap considering the gang work we've started doing. 

(Also the name pops up as NULL in garage/other places)

-Gee Baby (TKG)

**Comment by ZacLuxton** [comment]
Should now be fixed, pending restart

https://github.com/fkk-cz/noire_vehicles/commit/236c0f17565f3bcb75d5709785dd470930bf38f8

**Comment by ZacLuxton** [comment]
that layout didn't work, trying another one:

https://github.com/fkk-cz/noire_vehicles/commit/75c94e9da02812f43c2bc20aecdfc037ae245046

**Comment by fkk-cz** [comment]
now a 4 seater
