### ISSUE TITLE
GMC Denali

### ISSUE THREAD

**Issue by UnHolyG** [fkk-cz/noire_vehicles#363]
It won't allow you to upgrade the car at all with any upgrades like brakes, engine, armor, and everything else. The only thing you can change is the color and even then the color is a bit glitchy

**Comment by ZacLuxton** [comment]
![image](https://user-images.githubusercontent.com/79383480/124831072-aa381500-df72-11eb-8cce-c746d4d94266.png)

![image](https://user-images.githubusercontent.com/79383480/124831086-ad330580-df72-11eb-9071-1c05f2e7dd06.png)

![image](https://user-images.githubusercontent.com/79383480/124831097-b02df600-df72-11eb-898c-327f75d8827f.png)

![image](https://user-images.githubusercontent.com/79383480/124831115-b4f2aa00-df72-11eb-8ed2-d5dd84b3d8a3.png)

![image](https://user-images.githubusercontent.com/79383480/124831141-bc19b800-df72-11eb-8953-7aa98bc31185.png)

![image](https://user-images.githubusercontent.com/79383480/124831177-c8057a00-df72-11eb-8e66-9268cd314ad5.png)

The car seems fine, all upgrades seem to be good
