### ISSUE TITLE
1979 camaro z28

### ISSUE THREAD

**Issue by unseencthulhu** [fkk-cz/noire_vehicles#364]
Has no upgrades or wheels or cosmetics

**Comment by fkk-cz** [comment]
https://github.com/fkk-cz/noire_vehicles/commit/b0073687b1f83093978af03d3e21e621d7edcd80#diff-3eb1fe52ec717fb5a4986e47fa73fac082c21f63c57cf5595f0aedb07dbc3d14

trying a new modkit ID

**Comment by fkk-cz** [comment]
> 
> 
> [b007368#diff-3eb1fe52ec717fb5a4986e47fa73fac082c21f63c57cf5595f0aedb07dbc3d14](https://github.com/fkk-cz/noire_vehicles/commit/b0073687b1f83093978af03d3e21e621d7edcd80#diff-3eb1fe52ec717fb5a4986e47fa73fac082c21f63c57cf5595f0aedb07dbc3d14)
> 
> trying a new modkit ID

fixed cosmetics and performance upgrades
