### ISSUE TITLE
2017 McLaren 720s

### ISSUE THREAD

**Issue by butternut97** [fkk-cz/noire_vehicles#366]
car has no performance upgrades other then turbo and it doesn't stay on the car, also has no rim options and window tint doesn't work.

**Comment by butternut97** [comment]
also i found a sound pack for the car
https://www.gta5-mods.com/vehicles/custom-vehicle-engine-sounds-pack-add-on-sounds

**Comment by fkk-cz** [comment]
https://github.com/fkk-cz/noire_vehicles/commit/b0073687b1f83093978af03d3e21e621d7edcd80#diff-5c9b1a6dee472fc6c5e51e6c38543f5e638611b712201369140b29b05de5c5dd

trying a new modkit ID

**Comment by fkk-cz** [comment]
> 
> 
> [b007368#diff-5c9b1a6dee472fc6c5e51e6c38543f5e638611b712201369140b29b05de5c5dd](https://github.com/fkk-cz/noire_vehicles/commit/b0073687b1f83093978af03d3e21e621d7edcd80#diff-5c9b1a6dee472fc6c5e51e6c38543f5e638611b712201369140b29b05de5c5dd)
> 
> trying a new modkit ID

Fixed cosmetic and performance upgrades
