### ISSUE TITLE
Mercedes-Benz E55 

### ISSUE THREAD

**Issue by KingWZRD123** [fkk-cz/noire_vehicles#367]
has no engine or trans upgrades top speed says 220 but with drag and no upgrades it goes 140ish i feel like a bit of a tweak is needed but it could also be the no upgrades

**Comment by fkk-cz** [comment]
https://github.com/fkk-cz/noire_vehicles/commit/b0073687b1f83093978af03d3e21e621d7edcd80#diff-963fdcae895af09ed8020dc3e5414803ec30f01e653989b30d725a8f7e9747d2

trying a new modkit ID
