### ISSUE TITLE
2010 KTM EXC 530 nearly unrideable 

### ISSUE THREAD

**Issue by DankGrandma** [fkk-cz/noire_vehicles#368]
I couldnt find the file for this one to see what the handling.meta is. not sure what its named but its nearly unrideable. wheelies way to hard on takeoff and its extremely slippery.

**Comment by DankGrandma** [comment]
it seems to be all dirt bikes, local Sanchez's too. all broken

**Comment by fkk-cz** [comment]
> 
> 
> it seems to be all dirt bikes, local Sanchez's too. all broken

the SANCHEZ should be fixed, an erroneous handling.meta caused it
