### ISSUE TITLE
Mustang Mach E

### ISSUE THREAD

**Issue by Stagonium** [fkk-cz/noire_vehicles#369]
I just feel like with it being an SUV it should have more than 400 storage in the trunk. at least 500 but probably 750

**Comment by fkk-cz** [comment]
https://github.com/fkk-cz/noire_vehicles/commit/8ac774937cea817e130527a10cb80b0acaae846f#diff-784126851afefe2faee64a53714059e957fd8f9556474b5a97ab9e86ae2c7b0a

fixed
