### ISSUE TITLE
Mercedes-Benz EQC400

### ISSUE THREAD

**Issue by Mynameischug** [fkk-cz/noire_vehicles#370]
Issues where its a 4-door but only the front 2 doors open, can only carry 2 people

**Comment by ZacLuxton** [comment]
I may have fixed the issue, I'll see after restart:

https://github.com/fkk-cz/noire_vehicles/pull/422/commits/b43fc754980061ea3ad5e46c73bf328e61a8e707

**Comment by ZacLuxton** [comment]
Fixed
