### ISSUE TITLE
1992 Honda NSX

### ISSUE THREAD

**Issue by SpunkySx** [fkk-cz/noire_vehicles#373]
The car is practically undrivable its spins out constantly not even from bad driving just spin out/burns out constantly. while also not being able to make a turn due to it turning so wide. there's also no customization or upgrades at all leaving u down the street when u try to break missing ur turn by 20 feet. i just want the car to be drivable since i love the look of the car

**Comment by SpunkySx** [comment]
You also cant even change the wheels on the car if u don't like the factory tires

**Comment by fkk-cz** [comment]
https://github.com/fkk-cz/noire_vehicles/issues/372
