### ISSUE TITLE
BMW M5 2018, Quite slow

### ISSUE THREAD

**Issue by cxerq** [fkk-cz/noire_vehicles#374]
The IRL Top speed of BMW m5 is 155 But you can get an Upgrade to make it go 189mph, And i think if you add turbo onto it, it should do 189mph as you can buy that upgrade IRl, and the Price of it is 212K for a okay car in its current state!

**Comment by ZacLuxton** [comment]
I just tested this out, I put turbo on it, and it goes 180, the vehicle itself is fine and does not need anything fixed

**Comment by cxerq** [comment]
> I just tested this out, I put turbo on it, and it goes 180, the vehicle itself is fine and does not need anything fixed

well when i owned this i had tubro and never once was i able to get it to 180, idk if thats just me or my car was bugged or something but that was the case for me!
