### ISSUE TITLE
2014 BMW M4 Libertywalk wont take transmission upgrades (video attached)

### ISSUE THREAD

**Issue by DankGrandma** [fkk-cz/noire_vehicles#375]
i tried looking for the file to see the carcols but i cant find it. these added car names are a mess lmao dont know how you keep it all sorted B

**Comment by fkk-cz** [comment]
you sure it's only the transmission upgrades?

https://github.com/fkk-cz/noire_vehicles/blob/8ac774937cea817e130527a10cb80b0acaae846f/DATA/m4lb_data/carcols.meta#L260-L279

carcols.meta shows gearbox upgrades

**Comment by DankGrandma** [comment]
yeah but it wont even let me click into transmissions menu. 

https://youtu.be/4gS9aWucp0E

**Comment by ZacLuxton** [comment]
Merging with #437
