### ISSUE TITLE
Mach E

### ISSUE THREAD

**Issue by Pookk** [fkk-cz/noire_vehicles#376]
I know that there is a ticket already. But Mach E should really have more trunk space... Tesla has 750, CTSV Wagon has 500, Mach E has 400...bless up

**Comment by fkk-cz** [comment]
https://github.com/fkk-cz/noire_vehicles/commit/8ac774937cea817e130527a10cb80b0acaae846f#diff-784126851afefe2faee64a53714059e957fd8f9556474b5a97ab9e86ae2c7b0a

fixed
