### ISSUE TITLE
yzf r1 yamaha breaking fast and slow

### ISSUE THREAD

**Issue by alphacuremom2** [fkk-cz/noire_vehicles#377]
It said the bike could do 207 and with everything on it stock rims and no armor i can only hit around 165. The bike also blows up even if i dont hit anything from pillbox garage to mining.

**Comment by fkk-cz** [comment]
> 
> 
> It said the bike could do 207 and with everything on it stock rims and no armor i can only hit around 165. The bike also blows up even if i dont hit anything from pillbox garage to mining.

Just tested it, goes 180 flat when fully upgraded -- which is pretty close to realistic values.
