### ISSUE TITLE
BMW M3 GTR E46 NFS MW

### ISSUE THREAD

**Issue by herkkkk** [fkk-cz/noire_vehicles#379]
This car only goes around 150mph when it's supposed to go around 180 mph, there are similar cars around the same price range that go much faster than 150mph.

**Comment by fkk-cz** [comment]
https://github.com/fkk-cz/noire_vehicles/commit/ada0b784e598793b08b82f8fb878071ffc86b1df#diff-efa561c554092ad8b8c436e8fbd58502d7fdbf5b6e4c642fb492ac761526af5b

increased the top speed
