### ISSUE TITLE
GMC Denali

### ISSUE THREAD

**Issue by Qewi00** [fkk-cz/noire_vehicles#382]
GMC Denali is too light, every turn makes it overturn and damages the car at relatively low speed. It spins out of control when driven. Making it hard to upkeep. 

Making the GMC Denali heavier, but keeping the speed to actually drive consistently

**Comment by fkk-cz** [comment]
https://github.com/fkk-cz/noire_vehicles/commit/8ac774937cea817e130527a10cb80b0acaae846f#diff-2c4f2ec9b1b755f47a7546794d85ee7412f41ae0ef7c36e3837d44962dacd128

should be better now
