### ISSUE TITLE
2020 Yamaha R1 glitched

### ISSUE THREAD

**Issue by alphacuremom2** [fkk-cz/noire_vehicles#385]
i have a 2020 r1 and since the gas glitch was patched it is always out of gas. I filled it to 100 last night drove it to my house and put it away when i went to immediately take it back out i had 6 fuel. this has happened every time I put it away. Thanks for taking the time to check it out. -Alpha

**Comment by fkk-cz** [comment]
not sure about this fuel issue, I did however go through and tweak all the bikes to be more in line with their realistic handling (mainly top speed) values.

https://github.com/fkk-cz/noire_vehicles/commit/2da289f3b704e6be082076a12a7fe7157a3fa41f
