### ISSUE TITLE
1995 Skyline R33

### ISSUE THREAD

**Issue by gxdsent** [fkk-cz/noire_vehicles#386]
Top speed doesn't go higher than low 120's. Price for the car is 140K, maybe compensate price with a little higher of a top speed maybe? Definitely goes higher than that IRL. Hopefully we can get a little change on that one :) 

-Gee

**Comment by fkk-cz** [comment]
https://github.com/fkk-cz/noire_vehicles/commit/8ac774937cea817e130527a10cb80b0acaae846f#diff-d3ca61af45cfae7ab1c5433f25b13554b126f390b66468fe860aaf9d43402a57

should do around ~140 now
