### ISSUE TITLE
PDM List v2

### ISSUE THREAD

**Issue by ZacLuxton** [fkk-cz/noire_vehicles#387]
2021 BMW X7 - Vehicle class needs to be changed from ‘sports’’ to ‘SUV’

Tesla Cybertruck + Jaguar I-Type -> Runs on gas when its an electric vehicle

Jaguar I-Type -> Drifts around a fair bit, better drag, and a better top speed? Possible texture required as well

**Comment by fkk-cz** [comment]
fixed in https://github.com/fkk-cz/noire_vehicles/commit/8ac774937cea817e130527a10cb80b0acaae846f

> Possible texture required as well
Need to check this in game
