### ISSUE TITLE
Brabus G Wagon 

### ISSUE THREAD

**Issue by Ac3v4** [fkk-cz/noire_vehicles#388]
this new g wagon that i added is a boat compared to the normal one. it needs an all around buff because the brakes, the handling and the speed are trash compared to the normal one. its also $350,000 more than the normal g wagon so it should at least go around 200 with the same handling and brakes. thanks :0

**Comment by ZacLuxton** [comment]
Hi there, the vehicles top speed irl is 149 according to Brabus's website, I got it going 165 fully maxed out which is more then enough. The issue with The Brabus version in comparison to the original G-Wagon is the fact that its meant to be more heavier. The brakes are fine, I tested going from 165 to 0.

https://www.brabus.com/en/cars-for-sale/C4S082-1.html
