### ISSUE TITLE
SSC Tuatara

### ISSUE THREAD

**Issue by GpaMoney** [fkk-cz/noire_vehicles#389]
Car is 450,000 and cant even hit 200mph. Its advertised in the dealership as having a top speed of 360mph. Car needs a massive buff to top speed and acceleration.

**Comment by fkk-cz** [comment]
https://github.com/fkk-cz/noire_vehicles/commit/13ade74ed350a161828c7a67c6526828b293ab8a#diff-78e82e0d4f30754a23d93f3e47ab3b942d85fe01071c4428533ef36b86c9ea49

fixed and refunded
