### ISSUE TITLE
Tesla cybertruck refund

### ISSUE THREAD

**Issue by TheK0opa** [fkk-cz/noire_vehicles#390]
As we all know the cybertruck isn’t perfect but the worst part is the interior looks like a straight mess and my driver door keeps not working as my character has to go around the truck into the passenger side to enter and it still doesn't sit 4 ppl let alone the six from the bed truck. Very disappointing car to say the least i mean even the speed is not what it mentions or even close to it.

**Comment by DankGrandma** [comment]
https://www.gta5-mods.com/paintjobs/cybertruck-retexture-for-dragon20-fredwalkthrough-s-mod

**Comment by TheK0opa** [comment]
I recommended this pack but nothing was done so i sold it i lost 50k which sucks but i guess

**Comment by ZacLuxton** [comment]
![image](https://user-images.githubusercontent.com/79383480/124368509-954d4000-dc59-11eb-9e2e-5c03609c5068.png)

You knew what the vehicle looked like before purchasing it

> i mean even the speed is not what it mentions or even close to it.

This is speed without drag, the vehicle is probably a mess, getting out and in the vehicle is something we can not fix as it probably has something to do with the ydd
