### ISSUE TITLE
2008 chrysler 300c srt8

### ISSUE THREAD

**Issue by tre2drip** [fkk-cz/noire_vehicles#391]
Hey
My car Just got put in the game but I just went to the upgrade shop and there were nothing to upgrade.
Can yall add the upgrades for the 2008 chrysler 300c srt8 and a see through hood please and thank you..

**Comment by fkk-cz** [comment]
https://github.com/fkk-cz/noire_vehicles/commit/b0073687b1f83093978af03d3e21e621d7edcd80#diff-bc10297735565baac0e216fd0549119381618e4e015d354c2151939cd2b9f833

trying a new modkit ID

**Comment by fkk-cz** [comment]
> 
> 
> [b007368#diff-bc10297735565baac0e216fd0549119381618e4e015d354c2151939cd2b9f833](https://github.com/fkk-cz/noire_vehicles/commit/b0073687b1f83093978af03d3e21e621d7edcd80#diff-bc10297735565baac0e216fd0549119381618e4e015d354c2151939cd2b9f833)
> 
> trying a new modkit ID

Fixed cosmetic and performance upgrades
