### ISSUE TITLE
Honda CBR Motorcycle 

### ISSUE THREAD

**Issue by CyaDev** [fkk-cz/noire_vehicles#392]
Doesnt have any cosmetic upgrades, cant change spray paint or anything, going to sticker tab also didnt work. Also the bikes just randomly start smoking and get overheated for no reason

**Comment by fkk-cz** [comment]
https://github.com/fkk-cz/noire_vehicles/commit/b0073687b1f83093978af03d3e21e621d7edcd80#diff-3e72eb0b60073f25d997413eaf05df26df7faf0f3baf82d65009f9dedc8fc707

trying a new modkit ID

**Comment by fkk-cz** [comment]
Looks like there are no sticker (livery) changes for this vehicle. Fixed performance upgrades.
