### ISSUE TITLE
1965 Hoonigan Ford

### ISSUE THREAD

**Issue by Scopzze** [fkk-cz/noire_vehicles#394]
I bought the 1965 hoonigan ford i asked to be added well the car looks amazing but some things are off, in IRL the car is a 1400hp twin turbo so the car should be pretty quick and have very fast take off also the car sounds nothing like a muscle car more like a sports car the handling is pretty decent the only thing i would like changed is the top speed of the car to at least like 180mph, the launch on it to be one of the fastest in the game since it is a very quick car in irl and change the sound on it to like the 2020 GT500 sound package or like the hellcat charger

**Comment by Scopzze** [comment]
it just needs a buff cuz there are cars around the price of it that have very faster takeoff and speed and sound better

**Comment by DankGrandma** [comment]
it didn't let me take any upgrades but turbo too

**Comment by ZacLuxton** [comment]
https://github.com/fkk-cz/noire_vehicles/commit/13cd5545adad1a1881e93795ec752552570595e1 - Updated Audio Hash to be the 2020 GT500

**Comment by ZacLuxton** [comment]
https://github.com/fkk-cz/noire_vehicles/commit/1c6e557fcc81c58e9c53786ff3608ba0d2985fbf - Fixed Handling, pending no upgrades

**Comment by DankGrandma** [comment]
when the audio hash was changed I believe it removed the flames that would shoot out the exhaust

**Comment by ZacLuxton** [comment]
The only thing I can think of is reverting to change back to the old sound then

**Comment by ZacLuxton** [comment]
https://github.com/fkk-cz/noire_vehicles/commit/74f31dbceb619997741f60ffb6ce8c76da5e3ce8 - reverted audio hash, as well as attempting to make it a 2 seater
