### ISSUE TITLE
Ferrari f40

### ISSUE THREAD

**Issue by Ac3v4** [fkk-cz/noire_vehicles#395]
the f40s brakes are so bad, when u brake u cant turn and it brakes so slow it feels like ur just floating across the road making u have to brake like 5 seconds before ur meant to. please test it and see for yourself and try to fix it if possible. thanks

**Comment by fkk-cz** [comment]
https://github.com/fkk-cz/noire_vehicles/commit/ada0b784e598793b08b82f8fb878071ffc86b1df#diff-3bd132f9c6503d450bc64c4117286dec0558f05ac9e4a0f08bff9ca2ed7378db

should be improved now
