### ISSUE TITLE
Bugatti Divo

### ISSUE THREAD

**Issue by herkkkk** [fkk-cz/noire_vehicles#396]
The Bugatti Divo is amazing One of the best-looking cars in the city in my opinion and I'm very happy with my purchase except for one thing, it turns like a boat. The Divo was never built to be as fast as the other Bugatti's so that's why I'm happy with the speed. But the Divo was built for corners and to take turns very well. For $680,000 I would hope it had better handling. Thank you.

https://www.bugatti.com/divo/ - Resource in case you need one.

**Comment by herkkkk** [comment]
You also can't change the wheel color or LED color inside the car.

**Comment by fkk-cz** [comment]
> 
> 
> The Bugatti Divo is amazing One of the best-looking cars in the city in my opinion and I'm very happy with my purchase except for one thing, it turns like a boat. The Divo was never built to be as fast as the other Bugatti's so that's why I'm happy with the speed. But the Divo was built for corners and to take turns very well. For $680,000 I would hope it had better handling. Thank you.
> 
> https://www.bugatti.com/divo/ - Resource in case you need one.

https://github.com/fkk-cz/noire_vehicles/commit/1b98a99dd024eb5ef8a0e0d546ca0cee5d647169#diff-24c3d024151f493801dc5df8972048d300bae335630e6eed019c26fe7127075b

fixed the turning issues
