### ISSUE TITLE
Porsche Taycan 

### ISSUE THREAD

**Issue by jqde** [fkk-cz/noire_vehicles#397]
the porsche taycan irl does roughly a top speed of 162 mph but in the game it tops out at 134 mph can this please be fixed it is more expensive than the model x but a fair bit slower

heres an article which shows the top speed
https://driving.ca/auto-news/news/the-porsche-taycan-is-the-worlds-fastest-car-indoors-that-is

**Comment by fkk-cz** [comment]
the top speed is fair given the price to performance compared to similarly priced vehicles.
