### ISSUE TITLE
Alfa Romeo Giulia

### ISSUE THREAD

**Issue by Veloxica** [fkk-cz/noire_vehicles#400]
Car has 4 doors but only has 2 door accessibility :(

**Comment by Stagonium** [comment]
open the driver door and look in the back. It has no seats back there.

**Comment by fkk-cz** [comment]
that car has a rear seat delete

**Comment by Veloxica** [comment]
when I look at the rear seats outside and inside they arent deleted, they are still fully there. I assume a delete would be replaced with a roll cage or some other performance addition?
