### ISSUE TITLE
Porche Macan

### ISSUE THREAD

**Issue by styles11** [fkk-cz/noire_vehicles#401]
The car is fine driving wise but the paint is messed up. there are white vertical lines on the front bumber and the back left door has like a mirrior like reflection and the rear glitches out.
![2021 06 25-09 52](https://user-images.githubusercontent.com/85504600/123435072-2574f080-d59b-11eb-898b-fa5e05d51017.png)
![2021 06 25-09 49_01](https://user-images.githubusercontent.com/85504600/123435086-29a10e00-d59b-11eb-84f4-9b71a824b1ee.png)

**Comment by ZacLuxton** [comment]
vehicle is to be removed from the game
