### ISSUE TITLE
Aston Martin Valhalla 

### ISSUE THREAD

**Issue by Jayson1800** [fkk-cz/noire_vehicles#402]
Hi, this car is very slow the acceleration and doesn't go the top speed that it has to go to.
The acceleration supposes to be faster, it's reportedly supposed to go 60mph in 3 seconds and the top speed suppose to be 220 Due to being a project car in real life. This car is supposed to be a 2022 car in the making. It barely gets to 140. Hope we can get that fix. I paid 780k for this car. There are some cars that are cheaper that could outspeed this car, for example like the Lamborghini Huracan Performante.

And can we get the turning of the vehicle a slight fix? It's a little bit too stiff when turning. 

Source: https://www.forbes.com/wheels/news/the-nearly-2-million-aston-martin-valhalla-is-a-gift-from-the-gods/

**Comment by Jayson1800** [comment]
And can we get the turning of the vehicle a slight fix, its a little bit to siff.

**Comment by Jayson1800** [comment]
The Turbo doesn't save after buying it, please fix that too. Thank you.

**Comment by fkk-cz** [comment]
https://github.com/fkk-cz/noire_vehicles/commit/1b98a99dd024eb5ef8a0e0d546ca0cee5d647169#diff-ac198e947986967e81c56619108cfabec327f98d13e4c01892e317493b816397

fixed the major issues
