### ISSUE TITLE
2005 bmw m3 e46

### ISSUE THREAD

**Issue by butternut97** [fkk-cz/noire_vehicles#403]
car tops out around 130 i feel like 150 to 160 would be fair. car has no performance mods also the window tint and wheels do not have options.

**Comment by fkk-cz** [comment]
https://github.com/fkk-cz/noire_vehicles/commit/ada0b784e598793b08b82f8fb878071ffc86b1df

trying a new modkit ID

**Comment by ZacLuxton** [comment]
Resolved, can now upgrade this vehicle
