### ISSUE TITLE
Grand Cherokee Trackhawk

### ISSUE THREAD

**Issue by Yungjuicebox** [fkk-cz/noire_vehicles#405]
recently i bought a jeep track hawk and I was expecting the speed to be a lot better, while it does hit some high speeds like 170 it takes an incredibly long time to get there. im making this issue to request a higher speed/acceleration on the track hawk to better reflect it in real life. with upgrades in my opinion it should go at least 180.

**Comment by ZacLuxton** [comment]
This thing goes 180 irl, I've managed to get it going 200+ driving straight down, for the price you're getting a perfect vehicle
