### ISSUE TITLE
1999 Ford F-150 Lightning

### ISSUE THREAD

**Issue by gxdsent** [fkk-cz/noire_vehicles#408]
I know it literally got imported today and being the first one to probably own it since I got it put in, just some quick remarks about it that could hopefully get changed when possible:

-First is the trunk space for the truck is only at 400 which is on the very low side

-Second is being one of fords iconic trucks at the time, from fast and furious, etc. They come with around 360-380 hp for this model irl and in game it wont go over 100mph on a flat straight, no hill boosts, etc. Drag speeds hit around 140 in person. I understand you wouldn't want it to be too crazy in game but I definitely think it could use some help in that department because it is very underwhelming there. Even if the price rose to compensate with some speed increase that would be great because I know it's a pretty popular truck.

Besides that the truck is awesome. Thanks for getting the import in so swiftly! 
-Gee <3

**Comment by fkk-cz** [comment]
https://github.com/fkk-cz/noire_vehicles/commit/13ade74ed350a161828c7a67c6526828b293ab8a#diff-21e466b6d87a1afacf73f7929d77da3fa9645169fad956d8cf9914ae8ee5810a

https://github.com/fkk-cz/noire_vehicles/commit/13ade74ed350a161828c7a67c6526828b293ab8a#diff-1b25e7548f96d8c5e1f38f57e5cc56127e0b39fc023f46da10a3736ccb403fa5

trunk space fixed, top speed raised

**Comment by gxdsent** [comment]
> [13ade74#diff-21e466b6d87a1afacf73f7929d77da3fa9645169fad956d8cf9914ae8ee5810a](https://github.com/fkk-cz/noire_vehicles/commit/13ade74ed350a161828c7a67c6526828b293ab8a#diff-21e466b6d87a1afacf73f7929d77da3fa9645169fad956d8cf9914ae8ee5810a)
> 
> [13ade74#diff-1b25e7548f96d8c5e1f38f57e5cc56127e0b39fc023f46da10a3736ccb403fa5](https://github.com/fkk-cz/noire_vehicles/commit/13ade74ed350a161828c7a67c6526828b293ab8a#diff-1b25e7548f96d8c5e1f38f57e5cc56127e0b39fc023f46da10a3736ccb403fa5)
> 
> trunk space fixed, top speed raised

@fkk-cz 
will this be intergrated next update? just getting in now and trunk space is still at 400
