### ISSUE TITLE
Audi RS7 Invisible

### ISSUE THREAD

**Issue by Yush6969** [fkk-cz/noire_vehicles#409]
Yo bruv, the Audi RS7 is an immaculate vehicle and definitely worth the price. The issue with the vehicle is that you can not see the car from a distance. It goes invisible when you are too far, then shows only when you get closer.

**Comment by fkk-cz** [comment]
https://github.com/fkk-cz/noire_vehicles/commit/13ade74ed350a161828c7a67c6526828b293ab8a#diff-a3435fd421432ef5341c2bb7671dca3e240852d9c6b2cd5e85dffbf7ab097142

https://github.com/fkk-cz/noire_vehicles/commit/13ade74ed350a161828c7a67c6526828b293ab8a#diff-d8c6641ddc40e44ad2a851e04a27495a07077693dc34a873d5f3c47742bf0daf

fixed for both rs7s
