### ISSUE TITLE
mclaren 720s n-largo

### ISSUE THREAD

**Issue by franco4200** [fkk-cz/noire_vehicles#410]
please make the acceleration better, the car really only starts going when its at 80mp/h for its price I definitely think it should have a better acceleration if not better acceleration and better top speed cuz it goes 180-190 mp/h on flat.

and be able to dobble clutch would be nice:D

**Comment by fkk-cz** [comment]
test drove the vehicle, I don't think a performance tweak is needed given the vehicle's price.
