### ISSUE TITLE
Ford mustang GT40

### ISSUE THREAD

**Issue by Scooterbug7** [fkk-cz/noire_vehicles#411]
First of all the name should be changed to GT40 Mk1 rather than mustang GT40, also you cant change the window tint on the vehicle (it's just stuck blacked out). The top speed also could be a little better. Also, it would be cool if there were some more liveries on the car but idk if that would be possible

**Comment by ZacLuxton** [comment]
> First of all the name should be changed to GT40 Mk1 rather than mustang GT40
Should be good now

> , also you cant change the window tint on the vehicle (it's just stuck blacked out).
This isn't something that we can fix, You can change to limo to have it less tinted.

> The top speed also could be a little better.

The vehicles top speed is already 180mph maxed out, which is more then enough for how fast it increases.

> Also, it would be cool if there were some more liveries on the car but idk if that would be possible

Find ones that would fit the vehicle
