### ISSUE TITLE
Monte Carlo Upgrades

### ISSUE THREAD

**Issue by MrGoony** [fkk-cz/noire_vehicles#412]
Not necessarily looking for cosmetics as there isn't much that you should do to a beauty like a box chevy. Would love to have some engine upgrades though. The price of the car is great, I just feel like it could use a little extra power, I know other people agree too. I don't know if it's possible but would love to have just a bit more to it. The car would be perfect if it didn't lose so much power in the corners and the acceleration was a bit better. The lack of modern day customization with cosmetics could be weighed out by the modern day engine upgrades that you're able to do to the car now.

**Comment by fkk-cz** [comment]
https://github.com/fkk-cz/noire_vehicles/commit/13ade74ed350a161828c7a67c6526828b293ab8a#diff-15d25130b27518442974ae9e89d662333d6f267e6cf3e03ea5fa01edd4ab5c84

trying a new modkit ID

**Comment by fkk-cz** [comment]
fixed
