### ISSUE TITLE
Mclaren P1

### ISSUE THREAD

**Issue by xFuziii** [fkk-cz/noire_vehicles#413]
Hello,

So i bought the Mclaren P1 took to los santos i can only put on turbo no other upgrades.
Then i went on the highway to test it out and it only hits like 160Mph.
Is there a chance to have upgrades on it and like a acceleration boost and a top speed boost?

Thank u 
Patty Junior

**Comment by fkk-cz** [comment]
https://github.com/fkk-cz/noire_vehicles/commit/13ade74ed350a161828c7a67c6526828b293ab8a

trying a new modkit ID

**Comment by ZacLuxton** [comment]
Modkit is working, tested it, goes 200 now
