### ISSUE TITLE
Lamborghini sc18

### ISSUE THREAD

**Issue by kelliott33** [fkk-cz/noire_vehicles#415]
I believe this vehicle is to slow in game, you're paying almost 400k for a car that goes 150mph when in irl it goes 210 and 0-60 in less then 3 seconds

**Comment by ZacLuxton** [comment]
https://github.com/fkk-cz/noire_vehicles/commit/bf1c8bdd6ee28935131634bed32e14cd067e4823

https://github.com/fkk-cz/noire_vehicles/commit/260a41a6467ca4d85ff84188f5f4827be9ca7bbe

**Comment by ZacLuxton** [comment]
Merging with an already existing issue #470
