### ISSUE TITLE
Full Refund For Aston Martin Valhalla

### ISSUE THREAD

**Issue by Jayson1800** [fkk-cz/noire_vehicles#424]
Hello, I rebought the Aston Martin Valhalla because my ticket was closed and was responded: "fixed the major issues".... What issues fixed, the car felt the same, the only difference felt was the acceleration was a little bit faster, but that's all. The top speed is not there, it caps at 160-168mph on the highway full speed. The steering still feels like a boat. Overall not impressed with the "major issues" that were fixed. I want a full refund for the car.

I paid 780k for the car, I sold back the car the first time I bought it for 350k or something, and I had to grind the money back to buy it again. I don't want to sell the car again and get half my money back again.

**Comment by ZacLuxton** [comment]
If you want a full refund of the vehicle, then make a ticket on discord, we do not deal with refunds, if you want us to deal with the handling, then we can, but if you only want a refund, then make a ticket

**Comment by ZacLuxton** [comment]
I've just drove this, its got good accel, and goes up to 200mph flat out
