### ISSUE TITLE
Porsche Taycan top speed

### ISSUE THREAD

**Issue by jqde** [fkk-cz/noire_vehicles#426]
the car in the city hits top speed of 134 and irl hits roughly 160, heres a link to the Porsche site which shows the stats of the car, id be happy for acceleration to be a little bit worse to make up for the top speed if needed

https://www.porsche.com/australia/models/taycan/taycan-models/taycan-turbo-s/

**Comment by ZacLuxton** [comment]
Vehicle speed / accell is good for the price, doesn't need an increase in speed
