### ISSUE TITLE
ZSW540 mercedes-Benz A45 AMG is a 4 door with only 2 working seats

### ISSUE THREAD

**Issue by rivxl** [fkk-cz/noire_vehicles#433]
car has 4 doors but is only a 2 seater
![Screenshot_4](https://user-images.githubusercontent.com/86927440/124402606-5bcf1000-dcff-11eb-92ec-1cc62954f8cf.png)

**Comment by ZacLuxton** [comment]
Should be fixed

https://github.com/fkk-cz/noire_vehicles/commit/1097cbb8b52ec14a80f0e3570da71dadc019bc1d

**Comment by ZacLuxton** [comment]
Fixed
