### ISSUE TITLE
Tesla Cybertruck Top Speed False Advertisement

### ISSUE THREAD

**Issue by VHboys** [fkk-cz/noire_vehicles#434]
I'm not complaining or anything, I just wanted y'all to know that I recently bought the Cybertruck and was a little shocked and disappointed in the actual top speed after getting the truck. PDM said the top speed was 207.46MPH but I maxed out at 115 even after modifications. The drag is only 8.0 so I doubt it really makes that big of a difference.

Thanks!

**Comment by ZacLuxton** [comment]
Might have been an issue with the gears, its meant to have 1 gear, but instead it had 6.

https://github.com/fkk-cz/noire_vehicles/commit/6e45aefebca0ce4322d1f85aac6e616f1786858e

**Comment by ZacLuxton** [comment]
https://github.com/fkk-cz/noire_vehicles/commit/a7366eda67491e7b1574befb07665cb2aa5b415d - Should do 142 now maxed out
