### ISSUE TITLE
Lights Tinted on Kia Optima

### ISSUE THREAD

**Issue by Sanz-J** [fkk-cz/noire_vehicles#436]
Because of Tinted lights The Lights are not Much visible (The Textures inside The light). The Optima came with Tinted lights when i bought it brand new from PDM

**Comment by ZacLuxton** [comment]
![image](https://user-images.githubusercontent.com/79383480/124504197-e32f8880-ddbe-11eb-9e1a-079f48ff1136.png)

Just tested this out, with and without tinted windows to see what that will do, I believe it's an issue on your end as it's working fine for me, no tints

![image](https://user-images.githubusercontent.com/79383480/124504239-f6425880-ddbe-11eb-8d6b-8eb2b76887c7.png)

**Comment by Sanz-J** [comment]
That's not the Optima , that's the Kia Forte, check with the Kia Optima ( It's a 4DR Sedan)

**Comment by ZacLuxton** [comment]
my bad, I'll test this one out in a few hours

**Comment by Sanz-J** [comment]
Alright, Cool

**Comment by ZacLuxton** [comment]
headlights off:

![image](https://user-images.githubusercontent.com/79383480/124651105-6e2d8300-de92-11eb-9f46-93f5beb96088.png)

headlight on:

![image](https://user-images.githubusercontent.com/79383480/124651123-75549100-de92-11eb-8e99-6d36c31e53f5.png)

It seems fine to me, maybe check ur graphic settings, or if you have a graphics mod, check that out
