### ISSUE TITLE
BMW M4 Liberty Walk

### ISSUE THREAD

**Issue by MadDogMav** [fkk-cz/noire_vehicles#437]
Can't open transmission upgrades tab which I assume means no upgrades and the windshield doesn't tint when tinted.

**Comment by ZacLuxton** [comment]
> windshield doesn't tint when tinted.

That's not a glitch, some cars don't, some do, the window tint in itself is perfectly fine

>  transmission upgrades tab which I assume means no upgrades

https://github.com/fkk-cz/noire_vehicles/blob/c495cc226652d9dc3e4ac476890ed06e3495ee4d/DATA/m4lb_data/carcols.meta#L261-L286

Seems like they do have gearbox / trans upgrades, will take a look at spacing etc

**Comment by DankGrandma** [comment]
I posted a video, plz check that out

**Comment by DankGrandma** [comment]
hope it gets a buff too. slower than m5's

**Comment by DankGrandma** [comment]
https://youtu.be/4gS9aWucp0E
