### ISSUE TITLE
2020 RS7 Speed

### ISSUE THREAD

**Issue by ValentinoFiveM** [fkk-cz/noire_vehicles#438]
RS7 looks like it maxes at 155 maybe 160.  I'd recommend 180, maybe 170. The RS5 max is 170

**Comment by ZacLuxton** [comment]
![image](https://user-images.githubusercontent.com/79383480/124510586-0f9dd180-ddcc-11eb-94f6-96f696287044.png)

IRL speed for the vehicle, no need for it to be tweaked

**Comment by ZacLuxton** [comment]
https://github.com/fkk-cz/noire_vehicles/commit/fbb17c5854f015e8a00e16e79a7e144dac24d662 minor tweak to the vehicle type
