### ISSUE TITLE
1997 Lambo SV 

### ISSUE THREAD

**Issue by KingWZRD123** [fkk-cz/noire_vehicles#441]
its made of aluminum foil i stg and it does not turn at all please buff

**Comment by fkk-cz** [comment]
https://github.com/fkk-cz/noire_vehicles/commit/40d2cd9ca8518cdb9932a9455999a16595c93b8f#diff-1bd83a9eca4498625f9b9772b75205e29a99ce5c04e7e1ca99d57e6c4e7e72b1

fixed the steering issue
