### ISSUE TITLE
2015  Ferrari 458 speciale 

### ISSUE THREAD

**Issue by butternut97** [fkk-cz/noire_vehicles#442]
the car should have a functioning convertible. the mod for his car shows it working and if you hit h it makes the sound like it is moving.

**Comment by ZacLuxton** [comment]
I think this is a issue with the model ydd files, as it seems like its an convertible

**Comment by ZacLuxton** [comment]
![image](https://user-images.githubusercontent.com/79383480/124635050-ea1dd000-de7e-11eb-9d45-1544e87f138c.png)

Maybe its just you, it works for me? It _could_ be an upgrade from LS Customs that is on, let me see

**Comment by ZacLuxton** [comment]
https://streamable.com/gho8io

It seems like an issue your end, check your keybinds possibly
