### ISSUE TITLE
Lambo Hurracan Evo Spyder problems

### ISSUE THREAD

**Issue by Cortez312** [fkk-cz/noire_vehicles#444]
Car is too slow and caps out at 215 downhill which is really slow for its price point of 1.15m. The huracan performante is 280k and has a top speed of 230mph which is 15 miles faster with an almost 900k price difference. The car spins out easily and has turning problems until it reaches 2nd-3rd gear. The car's underglow doesn't work properly if its on the floor and will only show up if its slightly elevated on any side of the vehicle. I want to request for a full refund since this car isn't sellable as its none supporter if these problems can't be fixed.

**Comment by ZacLuxton** [comment]
You are already getting a better speed then what it is IRL, the reason why these cars are listed much more higher then supporter cars is because we dont want everyone driving in a super / hyper car.

**Comment by ZacLuxton** [comment]
https://github.com/fkk-cz/noire_vehicles/commit/ec421bf861a6e18e4c81e10f1cd40dce2a49d570

installed modkit, should fix most issues
