### ISSUE TITLE
Ford WDF350

### ISSUE THREAD

**Issue by natestwrt** [fkk-cz/noire_vehicles#446]
stickers pop on when not selected

**Comment by ZacLuxton** [comment]
Should be fixed by restart

https://github.com/fkk-cz/noire_vehicles/commit/263d622b02d6fedd92a4acd2ab1d555f812b1054

**Comment by ZacLuxton** [comment]
Seems like it's still an issue unless you put a sticker on there

**Comment by DankGrandma** [comment]
do you get visual bugs inside this truck? I'm getting screen flickering when I'm inside

**Comment by ZacLuxton** [comment]
Nope, so what happens is the cherry sticker will just permanently stay on there (unless you add a sticker on there)
