### ISSUE TITLE
2018 Dodge Durango srt

### ISSUE THREAD

**Issue by DoubleUpGhost** [fkk-cz/noire_vehicles#447]
the handling on the car is messed up, you can not turn the car without flipping it. you can be in a parking lot and the car will flip over when u turn its really bad and i just spent 65k on it can you fix this so i can drive my new car. thanks

**Comment by ZacLuxton** [comment]
https://github.com/fkk-cz/noire_vehicles/commit/8908dcbc67ace29aee69b92db3568a1788464c3e
