### ISSUE TITLE
2021 Ducati V4S

### ISSUE THREAD

**Issue by stormersunited** [fkk-cz/noire_vehicles#449]
armor needs a fix its totaled from like 1 or 2 light taps and would it be possible to get recolors for it? its only red

**Comment by ZacLuxton** [comment]
Damn, I see why it totals so quick

https://github.com/fkk-cz/noire_vehicles/blob/260a41a6467ca4d85ff84188f5f4827be9ca7bbe/DATA/v4sf_data/handling.meta#L41-L43

In comparison to the R6:

https://github.com/fkk-cz/noire_vehicles/blob/c495cc226652d9dc3e4ac476890ed06e3495ee4d/DATA/R6_data/handling.meta#L41-L43

I'll make it so they are equal now

**Comment by ZacLuxton** [comment]
https://github.com/fkk-cz/noire_vehicles/commit/e0e3a662acb7c3f5905e57d8585d2aa45317519d
