### ISSUE TITLE
Audi RS6 Needs a Buff

### ISSUE THREAD

**Issue by zaidiot** [fkk-cz/noire_vehicles#45]
This Audi Has 400 Space in The Trunk. It should be 500 or 600 because its a Sedan. This Audi Does 190Mph in Real life but in Game it does 150 with turbo. The Only Upgrade On It Is A Turbo. If you Hit something lightly it will start to smoke. dosent have armor. I think thats it. Please Fix This Soon

**Comment by DankGrandma** [comment]
as far as the carcols.meta, im seeing engine, suspension, brakes, gearbox and armor upgrades. theres prob something tabbed over too far or some little thing but i cant tell where.

**Comment by zaidiot** [comment]
The RS6 only needs better durability during crashes

**Comment by fkk-cz** [comment]
https://github.com/fkk-cz/noire_vehicles/commit/7fff78934425d7e2888bdc662451d68715ec21c9#diff-810a0e6a8339e75e6d9ace7e1da72f20048b547431de99a91e0b8bbfbb9bcfa2

increased the top speed, changed vehicleClass to VC_SEDAN to increase trunk space/fuel efficiency

**Comment by fkk-cz** [comment]
> 
> 
> The RS6 only needs better durability during crashes

the durability values seem fine
