### ISSUE TITLE
chevrolet k30 

### ISSUE THREAD

**Issue by JdmGuru** [fkk-cz/noire_vehicles#450]
the k30 trunk capacity is only 750. Should be a 1000. Also drinks a extremely amount of fuel. And has no power at all

**Comment by ZacLuxton** [comment]
Its a 1980's vehicle, ofc it's going to use a lot of fuel and not have the best power, I've just tested it out, power and fuel is fine for a vehicle that old. The Trunk space is specified upon the vehicle type which, for this is a van. Which is accurate as it's similar to the bison, which is also a "van"

**Comment by JdmGuru** [comment]
so the 80s model truck is considered a van? its a dually truck

**Comment by ZacLuxton** [comment]
there is no "truck" vehicle type.

its sedan, coupe, sport classic, sport, commercial, emergency, off-road, super, I think that's all
