### ISSUE TITLE
1986 c10 donk

### ISSUE THREAD

**Issue by JdmGuru** [fkk-cz/noire_vehicles#451]
needs more speed. would like a increase from 90mph to atleast 140. it does have a lsx swapped engine. so shouldnt be slow even with big rims on it

**Comment by ZacLuxton** [comment]
![image](https://user-images.githubusercontent.com/79383480/124967976-fa6bb180-e01c-11eb-96b3-eb00faaa0c54.png)


Do you mean this vehicle?

**Comment by JdmGuru** [comment]
yes that vehicle

**Comment by ZacLuxton** [comment]
https://github.com/fkk-cz/noire_vehicles/commit/62ac061b9008c4e3af0c38d85dd79b0906c683f1 - Fixed
