### ISSUE TITLE
Ferrari California T

### ISSUE THREAD

**Issue by EveEnchooli** [fkk-cz/noire_vehicles#452]
I really hate to be this person but the car hard caps at about 160mph on a flat and maybe 175 down hill even when fully upgraded. The overall top speed should be about 196mph, since the T is their twin-turbo model, with a v8 engine and around 550hp. <3
https://fastestlaps.com/models/ferrari-california-t

**Comment by ZacLuxton** [comment]
Since the car is 200K, and the top speed is already good enough, there's no need to buff the speed, for the price point you're getting a nice looking and good speed vehicle
