### ISSUE TITLE
Suyuki Hayabusa GSX1300 has no upgrades except turbo

### ISSUE THREAD

**Issue by rivxl** [fkk-cz/noire_vehicles#453]
Suyuki Hayabusa GSX1300 has no upgrades except turbo

![Screenshot_1](https://user-images.githubusercontent.com/86927440/125145234-826dbc00-e0ee-11eb-9716-5a572a48129d.png)
![Screenshot_2](https://user-images.githubusercontent.com/86927440/125145235-83065280-e0ee-11eb-9613-8b54ffe0bbd0.png)

**Comment by ZacLuxton** [comment]
Merging with #416
