### ISSUE TITLE
Ferrari F430 traction

### ISSUE THREAD

**Issue by Demithekid** [fkk-cz/noire_vehicles#454]
The car has very bad traction it slides of the road easily and it is hard to handle almost like a drift car and for a sports car I think it should have better traction.

**Comment by fkk-cz** [comment]
https://github.com/fkk-cz/noire_vehicles/commit/40d2cd9ca8518cdb9932a9455999a16595c93b8f#diff-62dc01146eb50706c08f4db29163edd1b071a041aa4543184a3cacee9c1043ff

should be better now

**Comment by herkkkk** [comment]
It hasn't really been changed still spins out constantly.
