### ISSUE TITLE
Koenigsegg Gemera

### ISSUE THREAD

**Issue by ItzHunterrrrr** [fkk-cz/noire_vehicles#455]
Handling has dropped since yesterday and first gear is much slower. use to steer like it was on rails at any speed. now it can barely weave traffic efficiently.

**Comment by ItzHunterrrrr** [comment]
actually. after further testing. the top speed and acceleration have both been nerfed aswell. car used to do 207 on flat ground. now it tops out at 183. so needs handling, acceleration and top speed fixed

**Comment by fkk-cz** [comment]
https://github.com/fkk-cz/noire_vehicles/commit/40d2cd9ca8518cdb9932a9455999a16595c93b8f#diff-944f4c3c59ae91c6462551a371470f99ca27c8686513729262236cdb6548fa68

top speed and acceleration is fine with full upgrades. steering is fixed

**Comment by ItzHunterrrrr** [comment]
The car is barely different from a 70k Alfa.. the car is dogshit now and its 500k.. thats 30hours worth of grinding to buy that.. just buff the cop cars speed and teach them how to drive and people wont keep getting away
