### ISSUE TITLE
Suyuki Hayabusa GSX1300 still has no upgrades except turbo

### ISSUE THREAD

**Issue by rivxl** [fkk-cz/noire_vehicles#456]
![125145234-826dbc00-e0ee-11eb-9716-5a572a48129d](https://user-images.githubusercontent.com/86927440/125169519-93630f80-e178-11eb-8d9f-add6a3be9952.png)
![125145235-83065280-e0ee-11eb-9613-8b54ffe0bbd0](https://user-images.githubusercontent.com/86927440/125169520-93fba600-e178-11eb-8fb2-8f446ffc3c66.png)
![Screenshot_2](https://user-images.githubusercontent.com/86927440/125169522-94943c80-e178-11eb-9557-340bb2f6656e.png)
![Screenshot_3](https://user-images.githubusercontent.com/86927440/125169523-95c56980-e178-11eb-9789-0a3dafd7581f.png)

**Comment by ZacLuxton** [comment]
#416 already a issue open
