### ISSUE TITLE
Jeep Grand Cherokee TracKHawk Storage

### ISSUE THREAD

**Issue by kwayy323** [fkk-cz/noire_vehicles#457]
Hey guys i just recently got gold supporter and I was kind of disappointed when i bought the Track Hawk and realized it doesn't have max 1.000 storage. That vehicle is definitely big enough and for sure should be max storage.
- Thanks! kwayy-

**Comment by ZacLuxton** [comment]
Trunk space is based off the vehicle type, the Trackhawk is an SUV which is why it has 750 truck space. We are unable to change this. The only vehicles that have 1k truck space are 'off-road' vehicles
