### ISSUE TITLE
2020 Shelby GT00 Handeling/Brakes

### ISSUE THREAD

**Issue by kwayy323** [fkk-cz/noire_vehicles#458]
Hey I just recently bought supporter and was disappointed on how poor the brakes and handling were on the car. Shelby is to Mustang as the Demon is to the Challenger in the performance package way that is practically fords baby and i think it should have much better brakes and handling then it does now.
-thanks! -kwayy

**Comment by JdmGuru** [comment]
And speed also needs to be increased also. thank you

**Comment by ZacLuxton** [comment]
Do you mean the Shelby GT500?

**Comment by JdmGuru** [comment]
yes its 2 of them. one is the 2013 and the other is 2020
