### ISSUE TITLE
1971 datsun 510 

### ISSUE THREAD

**Issue by JdmGuru** [fkk-cz/noire_vehicles#459]
thank you for importing this btw. i have one small issue. the speed. Can i get a increase to atleast 160. It is a smaller car but also have a rb26 swap in it from a skyline. Thanks in advance

**Comment by ZacLuxton** [comment]
https://github.com/fkk-cz/noire_vehicles/commit/65d8e4de2437668e2de7069fadff42f6b7dbde04 - should do 125 / 130 which is good for the price
