### ISSUE TITLE
Nissan GT-R50

### ISSUE THREAD

**Issue by gxdsent** [fkk-cz/noire_vehicles#463]
For its respected 710 hp irl, being only able to hit 148 max in game is a big bummer considering cars with lower hp can hit nearly 200 hp...its built with 110 more hp than the nismo gtr and that tops out around 205. Also the horn doesn't work as well

Hoping a buff can be in place asap for a 250k cost car :)

**Comment by apricates** [comment]
Hes most likely gonna make it go like 180mph cuz 250k is pretty cheap.

**Comment by gxdsent** [comment]
> Hes most likely gonna make it go like 180mph cuz 250k is pretty cheap.

hopefully at least that minimum. it doesn’t make sense for a $38k car i have is hitting up to 140 at max speed and can keep up with this car, when this car is miles above in every way if we’re speaking in literal terms

**Comment by ZacLuxton** [comment]
https://github.com/fkk-cz/noire_vehicles/commit/97157639846405290e431d090273de338abc9005
