### ISSUE TITLE
Porsche gt3rs

### ISSUE THREAD

**Issue by Aroebic** [fkk-cz/noire_vehicles#464]
Car sounds like a muscle car is 379k and handles like a garbage truck brakes like a honda civic with no brakes and the acceleration needs work top speed could get knocked down a bit for those changes, and even then its still not high for the car, if i had the power id take away most of the wheel spin better the brakes and put a little bit of acceleration on there

**Comment by Aroebic** [comment]
its more the sound and wheel spin then anything

**Comment by ZacLuxton** [comment]
https://github.com/fkk-cz/noire_vehicles/commit/d3a30f79960899ec62983a9012eb4414d0dbc4ee Sound fixed

**Comment by ZacLuxton** [comment]
the wheel spin is fine, for a race vehicle, its not too bad for it to change
