### ISSUE TITLE
Terzo Millennio

### ISSUE THREAD

**Issue by apricates** [fkk-cz/noire_vehicles#465]
I swear yall nerf cars just to laugh at the community. How you gonna nerf handling on a 525k car while a 280k performante can hit 230 downhill and has good handling. I dont understand yall. I guess fun doesn't exist anymore.

**Comment by apricates** [comment]
try turning in that car. Feels like a damn trash truck. My tahoe has better handling and that car costs like 27k.

**Comment by ZacLuxton** [comment]
https://github.com/fkk-cz/noire_vehicles/commit/f75c27dbdb87b9ecc94df288f7236784d7f5fde7 - The vehicle goes 190 maxed out.... Increase handling a tiny bit
