### ISSUE TITLE
Audi RS6 Avant 

### ISSUE THREAD

**Issue by GDNicky** [fkk-cz/noire_vehicles#466]
headlight do not project light so it is extremely difficult to drive at night I've tried putting the different lights on it and it still doesn't work the light themselves work and light up a little on the vehicle but there is no light projected in front of you on the road provided a video of what is happening [https://youtu.be/FXlWgswufh4](url)

**Comment by ZacLuxton** [comment]
https://github.com/fkk-cz/noire_vehicles/commit/c3bd6d5dfe3e48eea2bb23136dfd1f6f8b0767af#diff-c6b95c6ed4d3ad2ffc7dbe6ee386093c41c4b68d414e738f633ef3b032f0859b
