### ISSUE TITLE
Lamborghini SC18

### ISSUE THREAD

**Issue by MostJabrone** [fkk-cz/noire_vehicles#470]
gear ratios are messed up. Has 8 gears and I hit top speed, 180-190 (which seems too low), in 5th gear. The first three gears seem slow as well. Listed as 207mph top speed with 2.5 drag and goes slower than the huracan which is listed as ~198mph top speed and 3 something drag..

**Comment by MostJabrone** [comment]
also it has an aventador's V12 engine and the aventador IRL top sped is 217mph

**Comment by MostJabrone** [comment]
so just an update. drove it today and the gears seem more messed up than they were and it tops out at 130 now...

**Comment by MostJabrone** [comment]
now the top speed is 130...

**Comment by ZacLuxton** [comment]
https://github.com/fkk-cz/noire_vehicles/commit/134619861804857c0f2d3e5af62c155364778e31
