### ISSUE TITLE
RangeRover SVR

### ISSUE THREAD

**Issue by teejizzle** [fkk-cz/noire_vehicles#471]
can it get a slight buff it goes 170ish right now can we get it to go like 185 ish 190. Online stock it says it goes 170 this is with a engine ipgrades it goes 170

**Comment by teejizzle** [comment]
actually im only going 120 - 125 now cant even go close to 170

**Comment by teejizzle** [comment]
ped cars go faster than that

**Comment by teejizzle** [comment]
200k car gets dusted by kia fortek

**Comment by ZacLuxton** [comment]
https://github.com/fkk-cz/noire_vehicles/commit/b54239db8008b99bda1aa12515b47e181895769b - should go around 150 - 155, which is in par with how it is irl

**Comment by ZacLuxton** [comment]
https://github.com/fkk-cz/noire_vehicles/commit/2c7d038c6aca26092d46e5a56f5b46966bffff63 - also fixed the vehicle class to "SUV"
