### ISSUE TITLE
Jeep Cherokee SRT

### ISSUE THREAD

**Issue by Smula6400** [fkk-cz/noire_vehicles#473]
It's doesn't go as fast as it should and does in irl it goes 160 stock but in the game It hits 145 even with upgrades. And the suspension pops out if you go off-roading and hit a jump it sticks outside the wheel wells

**Comment by ZacLuxton** [comment]
The acceleration is good for a vehicle, 0 - 60 in 4.5 seconds which is accurate to in-game

**Comment by ZacLuxton** [comment]
>  And the suspension pops out if you go off-roading and hit a jump it sticks outside the wheel wells

Why would you go off-roading in a SUV, plus its a minor issue, same with the speed. For the price, the accel + Top speed is decent enough, not going to tweak it just because its out a minor bit
