### ISSUE TITLE
Tesla Model S

### ISSUE THREAD

**Issue by CasperBoiRL** [fkk-cz/noire_vehicles#474]
In real life, the Tesla Model S is faster than the x. More importantly, the proclaimed top speed in the dealer is 165, and it is nowhere close to that. It acclerates rapidly, then hits a wall at 126. Also, the drag on the model s is 9.1, while the drag on the model x is 10. This makes since, but what doesnt make since is how the Model X top speed is lower, and the drag is higher, yet it is faster than the Model S.

**Comment by ZacLuxton** [comment]
> the Tesla Model S is faster than the x

This is not true, both the Model S and The X 2016 p90d both have the same top speed (155mph)

![image](https://user-images.githubusercontent.com/79383480/126686502-d95b095b-f05d-462f-8f88-f52e96ef0090.png)


![image](https://user-images.githubusercontent.com/79383480/126686518-e1b1836c-6dae-4274-b829-c23bb310f39e.png)

**Comment by ZacLuxton** [comment]
https://github.com/fkk-cz/noire_vehicles/commit/c6028f96cecf7ee5b473b980c6bd1d6a3376dd23 - Buffed the Tesla Slightly
