### ISSUE TITLE
Maserati Levante

### ISSUE THREAD

**Issue by TheGodfatha** [fkk-cz/noire_vehicles#475]
Ya keep doing this bullshit stop lying about top speed so people pay for what they don’t want. First of all top speed for Maserati Levante is 190 it caps at about 155 or less by two.there’s also no visual upgrades at all which is partially acceptable because maybe it doesn’t have any .

**Comment by ZacLuxton** [comment]
Its top speed _without_ drag, literally says it.

![image](https://user-images.githubusercontent.com/79383480/125675904-38190260-9edf-4092-a386-ff9ab55ce97f.png)

That's the top speed of the vehicle

**Comment by TheGodfatha** [comment]
Eh so be it still there are cases where the top speed is cap.
