### ISSUE TITLE
2009 Ferrari F430 Super

### ISSUE THREAD

**Issue by herkkkk** [fkk-cz/noire_vehicles#476]
I just bought the 2009 Ferrari F430 Super yesterday and I'm extremely disappointed. For almost 800k it should be so much better. The Koenigsegg Agera Rs is better in every single way, speed, acceleration, handling, and only 500k. I would like a refund on the vehicle or the handling and top speed to change.

**Comment by ZacLuxton** [comment]
We recently just changed the handling file for the F430, for a non-supporter vehicle, you're getting a good top speed, and a good vehicle overall, we are not issuing refunds for these things. Just sell it to another player.
