### ISSUE TITLE
BMW E30 M3 Upgrades

### ISSUE THREAD

**Issue by xaliblu** [fkk-cz/noire_vehicles#479]
The BMW E30 takes one hit and its dead or smoking, should have armor upgrades.

**Comment by xaliblu** [comment]
My car just started smoking because I hit a cactus going 30 MPH, very needed.

**Comment by ZacLuxton** [comment]
https://github.com/fkk-cz/noire_vehicles/commit/f7a67a07cddfc1d2794444abd1e8e5b67ab72909
