### ISSUE TITLE
Nissan Fairlady Z

### ISSUE THREAD

**Issue by xnickz** [fkk-cz/noire_vehicles#481]
is it possible to get a refund for this car because when i buying the car my game started to act all crazy and it made me buy 2 of the nissan fairlady z the car was a blast to drive but the game made me buy 2 of them and all im asking for is for 1 of them to be refunded if its possible

**Comment by ZacLuxton** [comment]
Whats your discord name?

**Comment by xnickz** [comment]
nickz#5830

**Comment by ZacLuxton** [comment]
Added you to a ticket on discord
