### ISSUE TITLE
Porsche gt3 

### ISSUE THREAD

**Issue by af22rfz** [fkk-cz/noire_vehicles#483]
The sound of the car is a v8 noise while irl the car is a 4.0 flat 6 that revs up to 9k rpm and sounds amazing https://www.youtube.com/watch?v=62n-H6mo-eM i would appreciate if u could smth about it 
Have a good day !

**Comment by ZacLuxton** [comment]
https://github.com/fkk-cz/noire_vehicles/commit/64db2a60af4983beaeae6a4787325783672575af

Fixed, pending restart
