### ISSUE TITLE
2017 gmc sierra supporter truck

### ISSUE THREAD

**Issue by JdmGuru** [fkk-cz/noire_vehicles#491]
just bought this truck. has no modification options whats so ever, it sounds like a euro car. Doesnt sound like a truck at all. Handling is fine. But speed isnt great. This is the second truck ive bought within the last hour and half and had nothing but bad luck. Could you please put some attention into this thank you

**Comment by ZacLuxton** [comment]
![image](https://user-images.githubusercontent.com/79383480/126051000-e16b9a63-7210-43a0-957e-ee186f8322ff.png)

![image](https://user-images.githubusercontent.com/79383480/126051001-65b9a03f-73bd-4f6b-bf9e-5b06698211dc.png)

![image](https://user-images.githubusercontent.com/79383480/126051003-975d6a49-5c95-4d28-ab81-d78873c82b94.png)

![image](https://user-images.githubusercontent.com/79383480/126051004-ca18af60-57ad-4062-871a-09af9e41b429.png)

![image](https://user-images.githubusercontent.com/79383480/126051005-39394791-562b-49bd-b592-cc808b1aeabe.png)

![image](https://user-images.githubusercontent.com/79383480/126051006-4a01e2a4-26b8-4e32-bdd5-733f676f994d.png)


Not sure what you mean by no upgrades, seems that they are

**Comment by ZacLuxton** [comment]
https://github.com/fkk-cz/noire_vehicles/blob/8ad444ad149d4d526b3d2175766943ff289716b0/DATA/gmcs_data/vehicles.meta#L18

This is why the audio sounds fucked on it, will change it to the Sadler

**Comment by ZacLuxton** [comment]
https://github.com/fkk-cz/noire_vehicles/commit/1a209593499de552b9dc6b6955cd7e4364e03bf1

**Comment by JdmGuru** [comment]
bump.. Still sounds like a euro car lol and i said modifications not upgrades. I cant add light bars etc which im fine with that but the speed could use a lil tweeking thank you again
