### ISSUE TITLE
Huracan EVO Spyder reset after crash

### ISSUE THREAD

**Issue by ItzHunterrrrr** [fkk-cz/noire_vehicles#492]
My huracan was reset to stock essentially after the crash that happened about 20 minutes ago. no wheels, no tint, no horn, its 1150 an item to change..

**Comment by ItzHunterrrrr** [comment]
You also cant even add them anymore, they dont change

**Comment by ZacLuxton** [comment]
@fkk-cz Can you take a look at this

**Comment by ZacLuxton** [comment]
Added you to a ticket
