### ISSUE TITLE
2021 Range Rover Velar is faster IRL and has way to little trunk space for being a SUV

### ISSUE THREAD

**Issue by PlayboiBeni** [fkk-cz/noire_vehicles#494]
Range rover Velar is one of the faster Range Rovers and it only has 400 trunk space as an SUV should be at least 750

**Comment by ZacLuxton** [comment]
![image](https://user-images.githubusercontent.com/79383480/126062733-59afa486-fbf2-4386-aa3a-9ce5790d2d1d.png)

**Comment by ZacLuxton** [comment]
https://github.com/fkk-cz/noire_vehicles/commit/3392aa61a4677326a1925f6b2c6cef0f9a7bffac
