### ISSUE TITLE
2019 Buggati Divo 

### ISSUE THREAD

**Issue by Cortez312** [fkk-cz/noire_vehicles#497]
Car doesn't reach over 200 mph where it can go over 230 irl. The car has really bad handling and breaks which makes it almost impossible to stop or turn. 
https://festivalautomobile.com/en/portfolio-item/bugatti-divo-2/#:~:text=Its%20maximum%20speed%20is%20limited,seconds%20faster%20than%20the%20Chiron.

**Comment by ZacLuxton** [comment]
https://github.com/fkk-cz/noire_vehicles/commit/b98ffad038777c1b9a5763403f9683cdfdb91359 - car goes past 200, increased accel a tiny bit
