### ISSUE TITLE
Ferrari enzo sound buff and needs very slight speed buff

### ISSUE THREAD

**Issue by recruit2212** [fkk-cz/noire_vehicles#498]
The car is good but could do with a bit more meat to the noise of it and top speed could do with a slight buff as it's not great for a sub 700k car struggling to get 195mph.

**Comment by ZacLuxton** [comment]
https://github.com/fkk-cz/noire_vehicles/commit/49c2990ec725acdf7ba2d51f3661d5ec6aea0ae6 - Audio Changed
