### ISSUE TITLE
Jeep Grand Cherokee Trackhawk acceleration

### ISSUE THREAD

**Issue by MadDogMav** [fkk-cz/noire_vehicles#499]
The car has a decent top speed but it takes foreverrr to get there and I mean its a hellcat. If it is even possible to do it I would appreciate if it could have a little bit better acceleration.

**Comment by ZacLuxton** [comment]
https://github.com/fkk-cz/noire_vehicles/commit/7ab263a635299384464aece97d602fc22f793157
