### ISSUE TITLE
Dodge Magnum (null)

### ISSUE THREAD

**Issue by DankGrandma** [fkk-cz/noire_vehicles#50]
the dodge magnum shows up as (null) in the garage menus

**Comment by DankGrandma** [comment]
I've looked at cars that show proper names in the garage and ones that don't and cant find any difference so I'm not sure if its the vehicles or if its the garage.

**Comment by ogmudboneshmurda** [comment]
> 
> 
> I've looked at cars that show proper names in the garage and ones that don't and cant find any difference so I'm not sure if its the vehicles or if its the garage.

the display names should be the gameName, as seen here: https://github.com/ogmudboneshmurda/noire_vehicles/blob/196320e8c0b00b50de7b0aaf4830dea3e886b927/DATA/zachdragmagnum/vehicles.meta#L10
this needs to match the modelName, for some reason certain vehicles don't have the correct name
