### ISSUE TITLE
2010 Dodge RAM 2500 - $35,420

### ISSUE THREAD

**Issue by BluNero** [fkk-cz/noire_vehicles#500]
There is a couple issues with the vehicle.
#1 The driver side window is inverted. I'll attach a picture to go along with this.
#2 The interior of the vehicle isn't quite attached the way it should be. I'll attach another photo to go with this.
#3 The primary colors for the vehicle are a little funky, mostly the colors under the black category. They don't quite reflect what they are supposed to be. As in the color black looks more like an Ash color. Other than that i have no issues. 

Thank you for taking time to read this! 

(#1)
![image](https://user-images.githubusercontent.com/87614243/126075844-ae5a8124-66b4-458a-ad41-38e609ae11e4.png)

(#2) It is like this throughout the whole vehicle.
![image](https://user-images.githubusercontent.com/87614243/126075932-f4b1b299-81ca-4617-8918-cf1523892900.png)

**Comment by ZacLuxton** [comment]
This is a issue with the ydd files / texture issue, there isn't really much we can do

**Comment by BluNero** [comment]
Is there a way to edit the ydd files to fix it? I'm not familiar with the ydd files myself but if I could find someone that is would a reupload of the files/textures be a possibility?

**Comment by ZacLuxton** [comment]
Sadly not, the only way to change it is having a new vehicle files, which could mess up with the current vehicle, and can cause issues  (i.e vehicle not spawning)
