### ISSUE TITLE
65 Shelby Cobra 427: Performance

### ISSUE THREAD

**Issue by Mynameischug** [fkk-cz/noire_vehicles#501]
This car drives as if you are in low gravity or on ice. Braking does not exist, only slowing down. Anything over 30mph and the car is sliding everywhere. The top speed may need a buff as well but I'm not brave enough to test that with the handling and brakes as they are.

**Comment by ZacLuxton** [comment]
https://github.com/fkk-cz/noire_vehicles/commit/a5ecbe09b349f10158f465ab6fc5f9002afb7dc5
