### ISSUE TITLE
MCLAREN 720S N LARGO - Speed/Acceleration 

### ISSUE THREAD

**Issue by dogpound3475** [fkk-cz/noire_vehicles#509]
The car cost 380k
I can't even get the car to get up to 200 WITH upgrades
I'm not asking insane numbers just a slight bump 
feels iffy a "hypercar" that doesn't hit 200

**Comment by ZacLuxton** [comment]
Cars dont have to hit 200, i've just tested it, it has good accell and can hit 190, and 200 downhill
