### ISSUE TITLE
Lamborghini SC18 - Performance Issue

### ISSUE THREAD

**Issue by Gohennn** [fkk-cz/noire_vehicles#513]
The car is about 400k and its top speed is 135 with all maxed out upgrades and I only got up to that speed because I hit a bounce for a second so I would like a full refund or for the speed to be buffed and acceleration buffed basically just needs a whole performance overhaul.

**Comment by ZacLuxton** [comment]
https://github.com/fkk-cz/noire_vehicles/commit/134619861804857c0f2d3e5af62c155364778e31 - Please have a look at the current issues prior to making one, have already fixed this today
