### ISSUE TITLE
2013 Audi TTRS: Upgrades/Top speed

### ISSUE THREAD

**Issue by Mynameischug** [fkk-cz/noire_vehicles#516]
Love the car, thanks for adding it in. I checked a few times and only upgrade available was Turbo, and the top speed was right around 110-120 downhill, normally the vehicle would get to 170ish, or comparable to the Supras 160.

Thanks for all the work you're doing on these cars!

**Comment by Mynameischug** [comment]
Forgot to write that the tints do not work, and you can not change the wheels/tires

**Comment by ZacLuxton** [comment]
just tested it, goes 160.. not quite sure what you mean? will leave it open for no upgrades

**Comment by Mynameischug** [comment]
Ty ill test again, I couldn't get the top speed over 120 down the length of a highway, might have just been a one off issue

**Comment by Mynameischug** [comment]
Tested again, drove from the city to postal 3030 and it would not go above 140 downhill fully repaired

**Comment by ZacLuxton** [comment]
That was my bad (I was testing the vehicles out on Localhost and it had upgrades), there's duplicate modkit id's which is why the upgrades are glitched, when it get fixed, the vehicle will go 160+
