### ISSUE TITLE
2020 Tesla Roadster Top Speed

### ISSUE THREAD

**Issue by Lucky-Luciano** [fkk-cz/noire_vehicles#518]
The Tesla Roadster has a IRL top speed of 250 so could it be made so it goes 180-190 in game? I paid $200k for it and it gets up to only 145.

**Comment by ZacLuxton** [comment]
gta physics for an electric car will make it super bad, especially for the weight of the vehicle, will look at it to go 160 maxed

**Comment by ZacLuxton** [comment]
https://github.com/fkk-cz/noire_vehicles/commit/ca0e2b6e5e30b584ac6562077be79277fe3de1be
