### ISSUE TITLE
Ferrari 458 Prior [Paint issues]

### ISSUE THREAD

**Issue by MrGoony** [fkk-cz/noire_vehicles#521]
The Ferrari 458 has a set paint color, I would love it if I could change the red to any other different colors. In my opinion it really ruins the look. If you could change this I'd be very grateful. Thank you!

**Comment by ZacLuxton** [comment]
Just tested this out, vehicle is perfectly fine, can change it to any colour?

https://streamable.com/x2mn2v

**Comment by MrGoony** [comment]
Sorry i forgot to specify, i meant the red stripe cant be changed to
another color and was hoping i could change it to yellow. My apologies for
the confusion.
