### ISSUE TITLE
Ferrari 458 Paint Issue Specifics

### ISSUE THREAD

**Issue by MrGoony** [fkk-cz/noire_vehicles#522]
The red stripe cannot be changed to any other color, thank you for getting to the ticket quickly but I realized I screwed up on my end of not being specific. I would like to change the stripe to a different color and feel like with it being stuck as red leaves the car with extremely limited color options. Also, I'm having an issue where I'm only able to change the pearlescent color and nothing else.

**Comment by ZacLuxton** [comment]
That's the sticker, so it can't be changed change it in LS Customs. Unsure what you mean by;

>  I'm having an issue where I'm only able to change the pearlescent color and nothing else.

Since it's working perfectly fine with me

https://streamable.com/asbugr

**Comment by MrGoony** [comment]
THANK YOU! Im so dumb, there are no options showing for stickers so my
buddy just told me to try scrolling and it worked, thank you very much, i
apologize for the bother!
