### ISSUE TITLE
Change the brightness of the speedometer and rpm gauge on the rolls Royce wraith

### ISSUE THREAD

**Issue by Poggers3361** [fkk-cz/noire_vehicles#525]
I used the RR wraith and as soon I changed the camera too first person I was blinded by the brightness and for 330k I would expect to be able to see and drive in first person without getting blinded

**Comment by ZacLuxton** [comment]
fxmanifest.lua — Today at 02:27
Following on from your suggestion @Poggers, I would suggest turning down your graphics settings, if you feel it is too bright. We won't fix these types of issues as it is a minor issue and does not affect too many people
