### ISSUE TITLE
Mclaren 720s Spyder

### ISSUE THREAD

**Issue by TheGodfatha** [fkk-cz/noire_vehicles#529]
Its a convertible so im not sure if the top doesnt come out because you guys cant do it or i just dont know the button. Also the speed is kinda off hits a wall at 180 on the highway

**Comment by ZacLuxton** [comment]
Have you tried the page up menu?

**Comment by ZacLuxton** [comment]
Just tested this out, it seems like there is no way to put the top on and this is from the model, so there is not much we can do
