### ISSUE TITLE
2020 Mercedez Benz AMG GT

### ISSUE THREAD

**Issue by jqde** [fkk-cz/noire_vehicles#530]
i love how the car drives and handles im just wondering if it could have slight acceleration boost and it to be slightly louder ive heard these cars irl and they are a lot louder than this, thank you!

**Comment by ZacLuxton** [comment]
https://github.com/fkk-cz/noire_vehicles/blob/4f2dc2cf3e54d6034ea7374e9311fdc88df75333/DATA/amggt/vehicles.meta#L18

It's a replica of the GTA Vanilla vehicle, no need to make another sound

**Comment by ZacLuxton** [comment]
jqde commented yesterday
has no suspension upgrades (and needs it) and also needs an acceleration buff
