### ISSUE TITLE
1997 Lambo Diablo SV 

### ISSUE THREAD

**Issue by KingWZRD123** [fkk-cz/noire_vehicles#531]
yall fixed the handling but you also dropped the top speed its top speed is 207 NOT 175 dont feed me bullshit about gta physics because it used to go 240 #respectfully

https://www.encycarpedia.com/us/lamborghini/97-diablo-sv-coupe#:~:text=Lamborghini%20Diablo%20SV%20%2D%20Specifications%20(1997%2D1998)&text=With%20513%20hp%2C%20the%20naturally,maximum%20speed%20of%20207%20mph.

**Comment by ZacLuxton** [comment]
It was meant to be nerfed, 240 is ridiculous...

**Comment by KingWZRD123** [comment]
So why nerf it down that low? This is a realistic server dont nerf past the irl top speed come on now……

**Comment by ZacLuxton** [comment]
We're not going to buff to irl speeds... I'll test it out and see what I can do

**Comment by KingWZRD123** [comment]
Just say it you wont put it to the irl speed because the cops wont catch it thats the only reason and every single player in the server knows admins prioritize the police

**Comment by ZacLuxton** [comment]
If you know this is a realistic server, why would you run from police in a lambo anyway? Furthermore, the car is what 200 / 300 k (within that range), you can make anywhere between 20 - 30k if not more by doing illegal activity an hour. Come on now, don't be entitled. You argument with "admins prioritize the police" is dumb asf, if thats the case, then they would have **all** their vehicles go 200 / 300 mph and trust me i've seen it in some places. I literally said I would look into it for you, so don't come back with ridiculous and false claims or it'll just be closed

**Comment by ZacLuxton** [comment]
![image](https://user-images.githubusercontent.com/79383480/126896671-454af536-b7d9-4560-bbe8-fc6a3a4f0a5c.png)

**Comment by ZacLuxton** [comment]
![image](https://user-images.githubusercontent.com/79383480/126896722-42dff57a-25cd-430d-9f00-4c01d76f780e.png)
![image](https://user-images.githubusercontent.com/79383480/126896735-34c18a27-47c3-459f-828d-03fd89bb327a.png)

And you're complaining? even irl prices for the vehicles is more expensive then in here, and you can make nearly 30k an hour, sooooo what, you're grinding for what 5 hours maybe? The vehicle wont be buffed, it can go 200, has good accel and can "run from cops"
