### ISSUE TITLE
Nissan 350 FairladyZ 

### ISSUE THREAD

**Issue by GordoGambino** [fkk-cz/noire_vehicles#533]
The car tops at about 130 downhill, everything else is fine but irl the car goes about 160-170 especially when its upgraded fully w turbo and shit. Can you make it so it goes faster? doesnt have to go 160-170 i just want some decent speed, thanks

**Comment by ZacLuxton** [comment]
You're paying 35k for a vehicle, that will probably take 2 hours to grind for (if that), 130 for a vehicle imo for that price point is more then fair
