### ISSUE TITLE
2020 Infiniti Q60 Project Black S

### ISSUE THREAD

**Issue by Vinny326** [fkk-cz/noire_vehicles#535]
This car ingame struggles to stay above 145 on the highway when irl it does have the power and speed to go much faster, not asking for it to go 200mph or anything just a buff so that the car is where it should be in terms of acceleration and top speed.
Thanks

**Comment by ZacLuxton** [comment]
![image](https://user-images.githubusercontent.com/79383480/128552654-a0def6d2-d489-4fff-9fbc-53b2055d6499.png)


Which is in line with irl speed
