### ISSUE TITLE
The model S top speed

### ISSUE THREAD

**Issue by CasperBoiRL** [fkk-cz/noire_vehicles#537]
I was corrected last time on the top speed of the model s. Whoever did that and buffed the Model S, good job, it now has the acceleration it deserves, beating out the model x. But, the top speed of both of the cars is 155, and the model s goes 126-130 while the model x is well over 155. Not asking for a nerf on the model x, only a buff of the model s to get the proper top speed (155)

**Comment by ZacLuxton** [comment]
? This was already solved and merged by this restart? https://github.com/fkk-cz/noire_vehicles/commit/c6028f96cecf7ee5b473b980c6bd1d6a3376dd23
