### ISSUE TITLE
Mitsubishi Lancer EVO IX Top Speed

### ISSUE THREAD

**Issue by luciidxen** [fkk-cz/noire_vehicles#538]
The top speed is only 120, I feel like it should most def be faster than this

**Comment by fkk-cz** [comment]
https://github.com/fkk-cz/noire_vehicles/commit/9616f994b65ca27b019069eaee46bc49ae5194ff#diff-61ff419af870440c5eed44afcd3f9b0c99c66816ff67c2828481cfcdd8e36016

this was apparently handling like a drag vehicle -- knocked down the ridiculous fInitialDriveForce and made it handle more like a 'normal' car instead
