### ISSUE TITLE
1986 Chevrolet K30 

### ISSUE THREAD

**Issue by 1kEyes** [fkk-cz/noire_vehicles#540]
The problem I im having with the 1986 Chevrolet K30 is that it has 750 trunk space and i believe it should have 1000 trunk space. because that back of the truck/trunk is really long and there is also a jeep that has 1000 trunk space that basically doesn't even looks like you can store anything in there if you would like to talk about it my discord is   1,000 Eyes#7219

**Comment by 1kEyes** [comment]
btw just looking at the car you would also understand

**Comment by ZacLuxton** [comment]
https://github.com/fkk-cz/noire_vehicles/commit/a4dfc8e9bffa22c6cac177ac8ccab4398a6dc2e5
