### ISSUE TITLE
1990 Ferrari F40

### ISSUE THREAD

**Issue by Sphinx002** [fkk-cz/noire_vehicles#541]
Ik the car is a 90s super car and what not but the handling is so ass. Its worse than before its most recent fix. The car doesnt need to go over 200mph, a solid 175-180 top speed but it can actually take a turn and brake would def be the move

**Comment by fkk-cz** [comment]
https://github.com/fkk-cz/noire_vehicles/commit/9616f994b65ca27b019069eaee46bc49ae5194ff

the top speed/accel is fine, the issue appears to be the traction. increased the traction curve and min/max values.
