### ISSUE TITLE
jag xkrs terrible top speed 

### ISSUE THREAD

**Issue by recruit2212** [fkk-cz/noire_vehicles#542]
The jag suffers to get close to 120mph and irl those are able to hit the 180mph mark would like to have it fixed as this car is 350K!!!! 
![image_2021-07-31_023346](https://user-images.githubusercontent.com/87608707/127724690-7a7257d3-a2f7-4bc2-8bfb-5e6ab57c3979.png)

**Comment by ZacLuxton** [comment]
https://github.com/fkk-cz/noire_vehicles/commit/338a36d8c994493d9131eae3e4dd96fea084d549 - fixed
