### ISSUE TITLE
2013 Ford GT500 (SHELBY Super Snake) NFS movie car

### ISSUE THREAD

**Issue by JdmGuru** [fkk-cz/noire_vehicles#544]
car spins alot which is no0t a problem but acceleration is bad and top speed it bad. On the movie NFS the car does 280 mph i dont expect to get that but can i get some where around 190-202 Much appreciated. Here is a link also
https://nfs.fandom.com/wiki/Ford_Shelby_GT500_Super_Snake_(S-197_II)

**Comment by ZacLuxton** [comment]
https://github.com/fkk-cz/noire_vehicles/commit/cc37db287bd2a8d62c51d98d08a82917d59d9603 - Done
