### ISSUE TITLE
2020 BMW S1000 RR Durability

### ISSUE THREAD

**Issue by Memematician** [fkk-cz/noire_vehicles#548]
Durability should be low but not this low. Hitting a curb at the wrong angle or running into a fence or cone at low speeds wrecks it completely.

**Comment by fkk-cz** [comment]
https://github.com/fkk-cz/noire_vehicles/blob/f23de747320d24e6fe8c43f167f0a8b6d2d0fdde/DATA/ZB1_data/handling.meta#L119-L122

has normal damage values, test drive confirmed it
