### ISSUE TITLE
Jaguar I-Pace (Can't Enter Car)

### ISSUE THREAD

**Issue by sassygelato** [fkk-cz/noire_vehicles#549]
I can drive it once or twice, then I get back in and the engine glitches and won't start. I can only turn the tires. I have to have someone drive the car to the garage and I get in and put it away. Then I take it out and the cycle restarts

**Comment by ZacLuxton** [comment]
What vehicle is this?

**Comment by sassygelato** [comment]
It’s the Jaguar I-pace

**Comment by ZacLuxton** [comment]
Please state that in the issue title next time.

**Comment by ZacLuxton** [comment]
The vehicle works fine for me, my suggestion would be try turning the engine on and off, or attempt to relog maybe? Without any sort of proof of what you're experiencing, I am unable to assist any further

**Comment by sassygelato** [comment]
https://medal.tv/clips/60665863/d1337WK1GvXe
When I repaired my car, I go to start the car and all it does is flicker and turn off. My car got impounded because there's nothing I could do

**Comment by ZacLuxton** [comment]
This seems like an issue with electric SUV's

**Comment by ZacLuxton** [comment]
The Tesla Model X is doing the exact same thing

**Comment by ZacLuxton** [comment]
go to a gas station, repair kit spam f to get out of the car let it tele you back in, fill it with gas... repair kit again
and then it just works.. Try this and tell me how you get on @sassygelato
