### ISSUE TITLE
09 Bugatti Veyron - Luxury Auto

### ISSUE THREAD

**Issue by FkknAlpha** [fkk-cz/noire_vehicles#55]
Just purchased one of these bad boys and it definitely needs a bit of tweaking. 

The acceleration on it just isn't there at all. IRL it should have a 0-60 of 2.5 seconds and it accelerates like a taxi. I've only gotten the top speed up to 165mph and it should easily hit 220mph. IRL it has a top speed of 250 mph+ . If we were able to upgrade the car I'm sure it wouldn't feel as bad, but being that it can only get turbo I think it needs a buff.

Lastly is the audio of the engine and exhaust. The engine is an 8.0L quad turbo and it doesn't sound anywhere near that.

https://www.gta5-mods.com/vehicles/bugatti-veyron-2009-add-on-replace-auto-spoiler-animated

sound clip : https://www.youtube.com/watch?v=28fXmKyWjzo

Thanks!

**Comment by MadBasel** [comment]
If the Bugatti’s acceleration is like a taxi then the car needs a buff, also the top speed needs buffing as well, 170mph in a Bugatti isn’t realistic at all. The engine sound doesn’t sound like what it does in IRL so that needs sorting out.

**Comment by DankGrandma** [comment]
audioNameHash monster3 audioNameHash sounds good (wont let me show the >/<)

if we set the fInitialDriveMaxFlatVel value to 250 
then set the fInitialDragCoeff value to 1.05
it should top out at 195ish

**Comment by fkk-cz** [comment]
> 
> 
> audioNameHash monster3 audioNameHash sounds good (wont let me show the >/<)
> 
> if we set the fInitialDriveMaxFlatVel value to 250
> then set the fInitialDragCoeff value to 1.05
> it should top out at 195ish

https://github.com/fkk-cz/noire_vehicles/commit/7fff78934425d7e2888bdc662451d68715ec21c9#diff-f891537dac54e63c649ed548effb65529f75d5c5112c5afe0b94641419ce78d3
