### ISSUE TITLE
1969 Dodge Charger Off-Road

### ISSUE THREAD

**Issue by Stagonium** [fkk-cz/noire_vehicles#550]
I love the way this car looks and drives, but I feel like it needs to have actual armor upgrades, as well as the base durability increased a bit. The idea behind the vehicle is to go up mountains and through the rougher terrain and it has the durability of a wet paper bag, it just falls apart in your hands. I hit like one car going 20 and it started smoking.

**Comment by ZacLuxton** [comment]
https://github.com/fkk-cz/noire_vehicles/commit/6c41b097097e107d166f66e0bf9d4ae36d284238 - Fixed
