### ISSUE TITLE
92 porsche GT (supporter vehicle) 

### ISSUE THREAD

**Issue by TheK0opa** [fkk-cz/noire_vehicles#552]
I find that for 275k this vehicle goes way too slow i mean in irl they drove up to 165mph so whats a boost of 30mph. On top of that the acceleration is very slow if we can get that boosted as well i mean it’s a porsche and we all know how fast they can pull. More customization would be awesome too if possible.

**Comment by ZacLuxton** [comment]
So, what you want a 275K car go 200mph?
![image](https://user-images.githubusercontent.com/79383480/127896552-cf307930-5cdc-4641-a173-b76aaba09999.png)

**Comment by ZacLuxton** [comment]
will look at the acceleration, not the top speed.

**Comment by TheK0opa** [comment]
Not 200 but id say close to 171 would be nice i mean some cars under 100 go at least 160.

**Comment by ZacLuxton** [comment]
how fast does it go rn?

**Comment by TheK0opa** [comment]
133 and it slips all over the place when taking off

**Comment by fkk-cz** [comment]
> 
> 
> 133 and it slips all over the place when taking off

fixed in https://github.com/fkk-cz/noire_vehicles/commit/790bd4bfbfde0ce8698e249676051461678a1686
