### ISSUE TITLE
Hennessey Venom GT

### ISSUE THREAD

**Issue by SavageStonerDude** [fkk-cz/noire_vehicles#553]
The carbon fiber on the car looks really broken on the roof and both bumpers as well as some of the body parts in the custom shop don't actually change anything.. i tried to change body parts to just remove the carbon fiber all together but the roof and hood section on body parts only seem to to change one thing and it makes the car look worse..

in all it has very few body parts that actually seem to change anything & anyway to make the carbon fiber look realistic (hurt my eyes less)

**Comment by ZacLuxton** [comment]
this is a model issue and can not be changed
