### ISSUE TITLE
Tesla Cybertruck

### ISSUE THREAD

**Issue by Symple-0** [fkk-cz/noire_vehicles#558]
The tesla cyber truck has the design of a 4 door car and shoes the extra seats and doors but the car is only able to have 2 people in it. I think this should be changed so it can hold 4 people in the car

**Comment by DankGrandma** [comment]
dude you have a ticket open for this #554. this is the third wth?

**Comment by ZacLuxton** [comment]
I have tried to fix this, however it does not change
