### ISSUE TITLE
69 Boss 429 Mustang: Buff

### ISSUE THREAD

**Issue by Mynameischug** [fkk-cz/noire_vehicles#562]
I just wanna be on my John Wick shit, just hoping for a general speed/accel boost, handling seems great, doesn't have the same "low grav" issue as some of the other classics, and I know the boss wasn't the strongest mustang of it's time, but just something to make it more viable compared to other cars if possible, thanks!

**Comment by ZacLuxton** [comment]
Already spoke to you, the top speed is fine (it's in line with the irl speed). acceleration could be tweaked, will take a look

**Comment by Mynameischug** [comment]
Perfect thanks Zac, and the sound? :) Something meaner? :)

**Comment by ZacLuxton** [comment]
I'll take a look at sound too, see what sounds meaner
