### ISSUE TITLE
2012 mercedes-benz C63 AMG

### ISSUE THREAD

**Issue by franco4200** [fkk-cz/noire_vehicles#568]
please make the car quicker i get shit on by a supra thats half as expensive and alot of other cars that are much cheaper, please make the car worth the money.

from FRANCO

**Comment by ZacLuxton** [comment]
![image](https://user-images.githubusercontent.com/79383480/129103001-cad5966d-ae6b-4a1e-ae37-4811c638f2c5.png)


This is in-line with irl top speed, and will not be worked on
