### ISSUE TITLE
2019 Aston Martin Vantage Window Tint

### ISSUE THREAD

**Issue by LactatingWalrus** [fkk-cz/noire_vehicles#573]
Not sure if this is just an issue with the car model itself but you can't tint the windows on this car. Even the pure black option barely tints the windows.

**Comment by ZacLuxton** [comment]
Can you do upgrades on the car? i.e engine etc

**Comment by LactatingWalrus** [comment]
Yup. Upgrades work fine. Only window tint is the issue as far as I can tell.

**Comment by ZacLuxton** [comment]
Hmm, it could be a model issue, let me find out and get back to you

**Comment by ZacLuxton** [comment]
Yes, it's a model issue, if you look carefully you can see the tint starting to change, but its not as dark as others, unfortunately there is nothing we can do in this situation
