### ISSUE TITLE
2018 Honda r fk8

### ISSUE THREAD

**Issue by Ausdog22** [fkk-cz/noire_vehicles#575]
Trunk space is only 250, considering it’s a hatchback and a lot of the sedans and all have at 400-500 I think this should at least have 500 and possibly even 600-750 again it’s a hatchback and doesn’t Make sense it’s Space is so low compared to lots of the sedans.
Also, feel it is really boat like and it’s turns are way to wide it’s supposed to be more of a sportier car and doesn’t handle like it should, and possibly even a little speed upgrade too it only does 135-140 tops fully upgraded I think 150-155 would make a little more sense.

**Comment by ZacLuxton** [comment]
https://github.com/fkk-cz/noire_vehicles/commit/f47f80858de597d94c1e3701e42477cdd05091f7 - Fixed trunk space, we're not going to up the speed by 10mph when you can do that by curb boosting

**Comment by Ausdog22** [comment]
the trunk space is still 250 for me
