### ISSUE TITLE
hyundai genisis RB a little slow.

### ISSUE THREAD

**Issue by MadDogMav** [fkk-cz/noire_vehicles#577]
Maybe a little boost in acceleration. I handles fine and I haven't gotten to the top speed yet but I understand the 5.5 drag cuz its a beefy car but the acceleration could use some tweaking.

**Comment by fkk-cz** [comment]
https://github.com/fkk-cz/noire_vehicles/commit/9616f994b65ca27b019069eaee46bc49ae5194ff#diff-af880b3df41d90cc861667abf4787d724e5b043e49b82de9639b08cd31d5578a

the biggest issue with this vehicle appears to be no traction at low speeds. fixed.
