### ISSUE TITLE
Audi R8v10 LB buff

### ISSUE THREAD

**Issue by DankGrandma** [fkk-cz/noire_vehicles#583]
the acceleration is pretty good but its topping out around 165ish when i believe it tops out around 208ish. steering is a bit sluggish too.

**Comment by JdiggidyJdog** [comment]
The sound doesn't match the car I believe it would sound a little nice with a sound, Maybe like the non-supporter audi r8. I do agree with him on the steering/speed. Better accel as well. (Stock R8 V10 with full carbon pack. 5.2 FSI V10; 525bhp and 530Nm. 0-62mph: 3.9secs. Top speed: 196mph.)

**Comment by DankGrandma** [comment]
> The sound doesn't match the car I believe it would sound a little nicer with a sound, Maybe like the non-supporter audi r8. I do agree with him on the steering/speed. Better accel as well. (Stock R8 V10 with full carbon pack. 5.2 FSI V10; 525bhp and 530Nm. 0-62mph: 3.9secs. Top speed: 196mph.)

**Comment by DankGrandma** [comment]
205 mph
The R8 V10 performance generates 602 horsepower and 413 lb-ft of torque and catapults from 0-60 mph in 3.2 seconds for the Coupe (3.3 seconds for the Spyder), with a top track speed of 205 mph (204 mph for the Spyder).Oct 12, 2020
