### ISSUE TITLE
2021 BMW M4 Competition

### ISSUE THREAD

**Issue by bigneek** [fkk-cz/noire_vehicles#584]
The BMW M4 Competition only goes around 135mph in game, but if you order it IRL with the M Driver Package it will go 180mph. Also really needs an exhaust update and handling tweak.

**Comment by fkk-cz** [comment]
https://github.com/fkk-cz/noire_vehicles/commit/f23de747320d24e6fe8c43f167f0a8b6d2d0fdde#diff-db2e700b34f1c81e99d46a6538e129e1c6e2bcc32c9cecff95802f27a0008970

improved top speed and accel
