### ISSUE TITLE
1995 Ferrari F50

### ISSUE THREAD

**Issue by xFuziii** [fkk-cz/noire_vehicles#589]
hello,
I bought the Ferrari F50 it has nice handling good braking but the speed and ascelleration is pretty slow.
So can this car get a performance upgrade?

Ty and have a nice day

**Comment by fkk-cz** [comment]
https://github.com/fkk-cz/noire_vehicles/commit/f23de747320d24e6fe8c43f167f0a8b6d2d0fdde#diff-d58d011ed7537a67f7f92378a672cf9ef71d40a8a56a92f91ad9ef2f95e84fbe

improved handling
