### ISSUE TITLE
2016 Cadillac CTS V is nowhere close to its top speed and accel CURB WEIGHT IS 11000 

### ISSUE THREAD

**Issue by nickytheprophet** [fkk-cz/noire_vehicles#591]
its one of the fastest cars in its year and class, its a 8 speed IRL and only a 7 speed on here, top speed is like 160 if you get lucky when its supposed to be at least 200, acceleration needs a slight buff too. also the curb weight is 11000 is that some typa joke or something? its 4000 and some change in real life

**Comment by ZacLuxton** [comment]
curb weight doesn't change much

**Comment by ZacLuxton** [comment]
will take a look at acceleration

**Comment by nickytheprophet** [comment]
It's lowkey broken against bearcat and 50cal due to its weight if that could be subbed for speed and acceleration it would be perfect

**Comment by fkk-cz** [comment]
> its a 8 speed IRL and only a 7 speed on here
GTA does not like vehicles with more than 8 gears. Transmission upgrades increase gear count by one, which would lead to this vehicle effectively being a 9-speed.

Fixed the mass issue and raised the top speed as noted above.

https://github.com/fkk-cz/noire_vehicles/commit/790bd4bfbfde0ce8698e249676051461678a1686
