### ISSUE TITLE
Lexus Lfa

### ISSUE THREAD

**Issue by tantatertot** [fkk-cz/noire_vehicles#592]
Exhaust note is way to unrealistic for the car. It also has a lacking top speed at around 160 compared to real life at over 200mph for 375,000.

https://www.gta5-mods.com/vehicles/lfa-v10-sound-mod         < here's a link to a nice sounding lfa v10 I think would fit well

**Comment by fkk-cz** [comment]
https://github.com/fkk-cz/noire_vehicles/commit/f23de747320d24e6fe8c43f167f0a8b6d2d0fdde#diff-8f293bb5a5fb1329291440ac4ced67508fa530a61554a6634dcdbb9890cc95ce

added the sound, improved the handling
