### ISSUE TITLE
Huracan Evo Spyder..

### ISSUE THREAD

**Issue by ItzHunterrrrr** [fkk-cz/noire_vehicles#594]
its been 2 days shy of a month since the car mysteriously lost its upgrades... Still looking to have it refunded or atleast have the top speed and acceleration buffed up to what it was before it lost the upgrades... Acceleration was comparable to the Performante with a top speed of 205 flat

**Comment by ZacLuxton** [comment]
The handling file is the exact same as the evo and the performante, so we would be unable to change it. Theres still an issue open for the no upgrades, however only Assert can do the no upgrades. We don't do refunds on these types of requests. But will look at no upgrades
