### ISSUE TITLE
Lamborghini Urus

### ISSUE THREAD

**Issue by NSIANT** [fkk-cz/noire_vehicles#595]
Hello, 

Was just wondering if we can apply maybe one of the other Lambo sounds to the Urus?
The sound fully upgraded sounds a little bit like a civ car still and was kinda bummed about that.
Also, the speed seems a bit low for how quick the car is IRL.
I appreciate all the time given and taken for these updates that y'all apply so regardless, thank you.

**Comment by ZacLuxton** [comment]
The urus in game is 165 maxed out, urus irl is 190. Not that much of a difference. 

Upgraded Exhaust - https://github.com/fkk-cz/noire_vehicles/commit/5c19dadc7b311636fd6d1ff794a7404f2ca2bd38

**Comment by NSIANT** [comment]
I mean that's fair I appreciate the exhaust, but monetary wise for the car's purchase it's a big difference.
