### ISSUE TITLE
Yamaha R1 

### ISSUE THREAD

**Issue by cracksparrow69** [fkk-cz/noire_vehicles#597]
top speed isnt close to what it is irl, should hit near 200

**Comment by ZacLuxton** [comment]
It's goes 180 - 190 maxed out, which is what it does irl, so speed wont be touched

**Comment by cracksparrow69** [comment]
Hey 

Just tested out the R1 on the highways going around the city, fully upgraded doesn’t even hit 185 downhill. Straights are under 180 or 180 exact.
