### ISSUE TITLE
2015 Ferrari 458 Speciale

### ISSUE THREAD

**Issue by Groovehsocks** [fkk-cz/noire_vehicles#601]
Bought the 2015 Ferrari 458 Speciale, handles almost similar to a tug boat and i feel at it's fully upgraded state it's a tiny bit on the slower side

**Comment by ZacLuxton** [comment]
![image](https://user-images.githubusercontent.com/79383480/130320686-0fc928aa-e9e3-4c46-85ce-6c1c088edd01.png)

Speed is fine. Will take a look at the handling

**Comment by fkk-cz** [comment]
https://github.com/fkk-cz/noire_vehicles/commit/f23de747320d24e6fe8c43f167f0a8b6d2d0fdde#diff-9618aea172a17de11db8112a895f9c790f67a7c753ebfbb29bcee555f9ebc297

should be better now
