### ISSUE TITLE
McLaren Senna needs top speed buff

### ISSUE THREAD

**Issue by YungNino** [fkk-cz/noire_vehicles#602]
For 715k, the McLaren Senna is very slow. Driving it, I’ve gone max 170 mph. In  real life McLaren says the Senna is capable of going from zero to 60 mph in 2.7 seconds and Top speed is 208 mph.

so I think the mclaren senna needs a buff to be realistic and I also think the speed should be buffed because of the expensive 715k price.

**Comment by fkk-cz** [comment]
https://github.com/fkk-cz/noire_vehicles/commit/f23de747320d24e6fe8c43f167f0a8b6d2d0fdde#diff-48bc886fb4c8ad51ec370b7d6b0fa4f8d5ae517e67e9c1da795e0a650cd6fb94

fixed, should be better now
