### ISSUE TITLE
Dodge Demon/Hellcat sound

### ISSUE THREAD

**Issue by ScanPlug** [fkk-cz/noire_vehicles#610]
The Demons engine sound is very inaccurate compared to the one IRL. I have a sound to suggest you guys use. The superchargers on Dodge engines have a distinct whining noise while in the game its a rumble. The performance is otherwise decent I'm still expecting a performance boost on the Dodge Demon because its still slower than the Dodge Charger hellcat.

Please update the Dodge Demon to this sound.
Demon Car sound: https://www.gta5-mods.com/vehicles/demon-hemi-supercharged-v8-sound

**Comment by ZacLuxton** [comment]
> Dodge Charger hellcat.

Challenger hellcat you mean?

**Comment by ScanPlug** [comment]
No the Challenger Demon Is slower than the charger and Challenger Hellcat. But mostly just upgrade the sound to a supercharged one.

**Comment by ZacLuxton** [comment]
Sound is not fivem compatible
