### ISSUE TITLE
Chrysler 300 gas doesn't fill completely.

### ISSUE THREAD

**Issue by SaltedFries** [fkk-cz/noire_vehicles#611]
Gas pump says fully filled yet its left on 96 fuel.

[https://cdn.discordapp.com/attachments/858510874902003742/880979004704829470/2453_FiveM_b2372_GTAProcess.jpg](url)
[https://cdn.discordapp.com/attachments/858510874902003742/880979009566040074/2454_FiveM_b2372_GTAProcess.jpg](url)

**Comment by ZacLuxton** [comment]
https://streamable.com/6rwnyc - Just tested this out, works perfectly fine for me?

**Comment by SaltedFries** [comment]
hm, seems to be fixed? weird, thanks :D
