### ISSUE TITLE
Vehicle Tweak

### ISSUE THREAD

**Issue by MichaelCoppJr** [fkk-cz/noire_vehicles#612]
Vehicle: 
2020 Ford Explorer
(non supporter PDM)

Issue:
I believe the vehicle should be tweaked just about all around. The model in game is a 2020 Ford Explorer RT which would hold a turbocharged V6 with about 400HP and a 0-60 in under 6 seconds. 
I believe the acceleration to be too low, the top speed to be too low, and the braking could use some work.

**Comment by fkk-cz** [comment]
https://github.com/fkk-cz/noire_vehicles/commit/9616f994b65ca27b019069eaee46bc49ae5194ff#diff-ae0b9a826667926576f725f19825796c995457a89753cf0aa46806606d4cee24

improved handling values all around
