### ISSUE TITLE
Tesla Model S Dashboard issues

### ISSUE THREAD

**Issue by SaltedFries** [fkk-cz/noire_vehicles#614]
While the engine is off, the display looks fine.
![image](https://user-images.githubusercontent.com/69441897/131236818-6ace7a13-4716-4283-8dcd-f961c871c428.png)

However, while on, it looks awful.
![image](https://user-images.githubusercontent.com/69441897/131236833-72687228-9896-4d83-bce1-4d8575a0a448.png)

**Comment by ZacLuxton** [comment]
This is a model issue and won't be fixed
