### ISSUE TITLE
Dodge demon slide

### ISSUE THREAD

**Issue by Nick-Vyvyan** [fkk-cz/noire_vehicles#616]
the back end slides out a lot when trying to turn, a very small reduction would be perfect i think. obviously the car has a lot of torque going into the back tires, but it even happens when not pressing the gas. again, a *small* improvement to reduce the slide on turns would be great

**Comment by fkk-cz** [comment]
https://github.com/fkk-cz/noire_vehicles/commit/9616f994b65ca27b019069eaee46bc49ae5194ff#diff-b39a92b5b862fcd1b04b569628ebfd5452357cd604af0bfd43b7f6e466d8f5be

increased fTractionCurveLateral among other things, this should help improve the overall handling
