### ISSUE TITLE
Tesla Model S shows ability to buy armor but doesn't apply.

### ISSUE THREAD

**Issue by SaltedFries** [fkk-cz/noire_vehicles#618]
![image](https://user-images.githubusercontent.com/69441897/131293695-7070df97-77cf-4060-b8c3-a0a3d89ea23c.png)

**Comment by SaltedFries** [comment]
update: only cosmetic stuff updates (e.g. respray neons ect)

**Comment by ZacLuxton** [comment]
Seems like brakes etc are working

**Comment by ZacLuxton** [comment]
Just armour

**Comment by SaltedFries** [comment]
horns do not work also :(

**Comment by ZacLuxton** [comment]
Some horns work - other's dont. Like how most vehicles are. Not much we can do

**Comment by ZacLuxton** [comment]
<identifier/>
					<modifier value="20"/>
					<audioApply value="1.000000"/>
					<weight value="0"/>
					<type>VMT_ARMOUR</type>
				</Item>
				<Item>
					<identifier/>
					<modifier value="40"/>
					<audioApply value="1.000000"/>
					<weight value="10"/>
					<type>VMT_ARMOUR</type>
				</Item>
				<Item>
				
It seems like this is just how the model is. Only 2 types of armour upgrades.
