### ISSUE TITLE
Lamborghini Huracan Evo Spyder

### ISSUE THREAD

**Issue by Rojingrey** [fkk-cz/noire_vehicles#619]
no upgrades except turbo,all the others say default. no wheel customizations, and the neon headlights don't stay when you buy them. been like this for over a month with this car.

**Comment by fkk-cz** [comment]
https://github.com/fkk-cz/noire_vehicles/commit/70fc88e2787c375f0eb65d47abd4f4cb6060eab4#diff-c6a7c17e048687327b6983dff73c11af233ac72716a72426c7c87a48d1e279bc

trying a new modkit ID
