### ISSUE TITLE
Hennessey Velociraptor 

### ISSUE THREAD

**Issue by Archerr95** [fkk-cz/noire_vehicles#621]
Its a 6x6 truck and It’s only a 4 seater currently, definitely room for between 2-4 people in the trunk area, making it an 8 seater would absolutely make the 325k price tag worthwhile. Also it’s down in the insurance menus as ‘NULL’

**Comment by ZacLuxton** [comment]
Seems as though the model is only limited to 4 seats as the layout is the same with the 19raptor which seats 6 people. Leaving open for the bad GTX2 entry

**Comment by Archerr95** [comment]
Does this mean it’s not likely to be changed? Or adapted by yourselves?

**Comment by ZacLuxton** [comment]
It means that it wont be able to be changed. The bad GTX2 entry is something that is on some of the vehicles. For example the 16 challenger

**Comment by Archerr95** [comment]
So you couldn’t even tweak the trunk space to increase it to make use of the masses of wasted space back there?

**Comment by fkk-cz** [comment]
https://github.com/fkk-cz/noire_vehicles/blob/9b3d6796026db41df36835b258874cd6adae3348/DATA/velociraptor/vehicles.meta#L106

this is already the 'biggest' vehicle class possible.
