### ISSUE TITLE
ninja h2

### ISSUE THREAD

**Issue by cracksparrow69** [fkk-cz/noire_vehicles#622]
ninja h2 still doesnt have correct top speed, only one upgrade which is turbo which actually made the bike slower as it used to hit 120 now only does 112-115. this one is the h2r model which has a top speed of over 200 and is roughly 20k more expensive as well. literally the fastest street bike off production line.

**Comment by ZacLuxton** [comment]
For 32k The vehicle is not going 200mph... I hope you know that

**Comment by cracksparrow69** [comment]
Yea I get that. The bmw bike is 35k and goes 190. Unrealistic compared to the h2. Idk why there can’t be a compromise and make it the same speed as the bmw bike.

**Comment by ZacLuxton** [comment]
BMW Bike used to be even more wild... I'll tweak it a little bit later on

**Comment by cracksparrow69** [comment]
yea i remember when it used to hit over 220, and the h2 was always slower than ped cars. i mean the r1 is 27k and hits 175-180, realistically the h2 is way faster than the bmw bike but making it the same speed or roughly the same speed would be a good compromise.

**Comment by ZacLuxton** [comment]
https://github.com/fkk-cz/noire_vehicles/blob/70fc88e2787c375f0eb65d47abd4f4cb6060eab4/DATA/ninjah2_data/vehicles.meta#L7-L9

For some reason - the reason for that is because it has the handling id of the BATI bike from gta5 itself and not a custom one... So that's why its probably the same speed as the ped one

**Comment by fkk-cz** [comment]
https://github.com/fkk-cz/noire_vehicles/commit/cad55a3df68b34a3e2aed00c436b9a94a428125f#diff-8607c955d52df607d6818080a8fd080bb513d2981958d218f3dc9ba7675fd078

created a new handling ID for this bike
