### ISSUE TITLE
Durango SRT 

### ISSUE THREAD

**Issue by Tunawuvsu** [fkk-cz/noire_vehicles#623]
The Durango is slower than it should be, in game it caps out at around 120 mph when in real life its top speed is 180.

**Comment by fkk-cz** [comment]
https://github.com/fkk-cz/noire_vehicles/commit/70fc88e2787c375f0eb65d47abd4f4cb6060eab4#diff-bc6cb61f5408ba6470d58a029940143bcf3c0621a20fa54e11dbaa5d4e05eb44

fixes speed and acceleration issues
