### ISSUE TITLE
Gas Station Tesla Trucks!

### ISSUE THREAD

**Issue by EveEnchooli** [fkk-cz/noire_vehicles#624]
Recently the tesla trucks break down a lot more quickly than they used to, which is fine! I'm okay with bringing repair kits and fixing the truck as needed. The issue is with when the truck breaks down completely it fails the mission, which means you lose the money on the gas run and you have to start all over. When the truck starts to go yellow the window of opportunity to repair before you fail the mission is VERY small.

**Comment by fkk-cz** [comment]
https://github.com/fkk-cz/noire_vehicles/commit/70fc88e2787c375f0eb65d47abd4f4cb6060eab4#diff-cdc2a5c0715823b3474d500549b92567a63fe3c1627ee82fe11e4641ffc795a7

fixes the damage issues, also increased drag which should prevent people from obtaining unrealistic/highly illegal speeds and getting pulled over
