### ISSUE TITLE
2014 BMW M4 F82

### ISSUE THREAD

**Issue by Shad20** [fkk-cz/noire_vehicles#625]
Sounds very bad like a civ car.
2014 BMW M4 F82 Supporter vehicle listed for 65k 

link for sound mod:

https://www.gta5-mods.com/vehicles/bmw-f82-m4-better-sound-mod-beautiful-downrevs

**Comment by fkk-cz** [comment]
This isn't even a sound 'mod' - just a vehicles.meta with a **feltzer3** audio hash
