### ISSUE TITLE
Mercedes Benz E55 AMG

### ISSUE THREAD

**Issue by Shad20** [fkk-cz/noire_vehicles#626]
Car has no engine or transmission upgrades
Mercedes Benz E55 AMG Supporter vehicle listed for 55k

**Comment by fkk-cz** [comment]
https://github.com/fkk-cz/noire_vehicles/commit/70fc88e2787c375f0eb65d47abd4f4cb6060eab4#diff-963fdcae895af09ed8020dc3e5414803ec30f01e653989b30d725a8f7e9747d2

trying new modkit ID

**Comment by ZacLuxton** [comment]
Seems like it's still an issue - unable to click engine or trans upgrades
