### ISSUE TITLE
2019 EVO Lancer

### ISSUE THREAD

**Issue by herkkkk** [fkk-cz/noire_vehicles#631]
The car tops out at around 115, it goes around 140-150 IRL, and its 150k so I'm hoping for a better top speed.

**Comment by herkkkk** [comment]
The car also goes 140 stock IRL, with the upgrades it should go 160 easily.

**Comment by fkk-cz** [comment]
https://github.com/fkk-cz/noire_vehicles/commit/9b3d6796026db41df36835b258874cd6adae3348#diff-1831e75ce07c589c66c535480e1db6aae254248af3de2f1741b39b7994cfa579 fixed.
