### ISSUE TITLE
Brabus 800 mercedes AMG G63

### ISSUE THREAD

**Issue by xFuziii** [fkk-cz/noire_vehicles#632]
Hello,
yesterday i bought the Brabus and im not sure if u can fix the turn radius on it that it goes little sharper and maybe if u can test drive it and give it like a asceleration boost? 
ty and have a nice day

**Comment by fkk-cz** [comment]
https://github.com/fkk-cz/noire_vehicles/commit/9b3d6796026db41df36835b258874cd6adae3348#diff-43fb480c36aa1a17502fb223c43f5efd56765d1da962cf1f07c0656787aa7ed0 fixes the **fSteeringLock** issue, increased the acceleration as well.
