### ISSUE TITLE
1993 McLaren F1

### ISSUE THREAD

**Issue by BluNero** [fkk-cz/noire_vehicles#633]
The McLaren F1 has no upgrades or customization options of any sort. The car cost roughly 817k and doesn't really have the assets to back up the price. Would like to see the car possibly reflect the IRL version which I will post a picture regarding the specifications. ![image](https://user-images.githubusercontent.com/87614243/132205015-ee0664b4-1152-4d49-8402-7eaa123c385f.png)

**Comment by BluNero** [comment]
Also the 1993 McLaren F1 is a 3 seater vehicle. And two of the 3 seats work but the seat to the right of the driver when looking at the front of the car does not allow people to sit in it. I'm not sure if that's fixable or not.

**Comment by fkk-cz** [comment]
first, this vehicle is supposed to have upgrades. https://github.com/fkk-cz/noire_vehicles/commit/9b3d6796026db41df36835b258874cd6adae3348#diff-c859249759ff3e752df9045792ed1f71f068d1a846cfa984502be6d6f4bad4aa fixes that issue.

handling is way off as well.
https://github.com/fkk-cz/noire_vehicles/commit/9b3d6796026db41df36835b258874cd6adae3348#diff-4fed8d42aa61457c16770c7c913577352209876d01e0752b26f17433b5e9fa5d fixed.



> 
> 
> Also the 1993 McLaren F1 is a 3 seater vehicle. And two of the 3 seats work but the seat to the right of the driver when looking at the front of the car does not allow people to sit in it. I'm not sure if that's fixable or not.

This cannot be fixed as GTA has no 3-seat vehicle layouts - at least, not any I'm aware of. @ZacLuxton any idea on this one?

**Comment by ZacLuxton** [comment]
Just tried looking - the "vanilla replacement" of the F1 is the GP1, tried spawning it in to see if it has 3 seats to take the layout from that. But thats only 2 seater. So no there is no 3 seater layout. Would be cool if rockstar implemented that kind of layout but is what it is!

**Comment by BluNero** [comment]
That's fine on the 3 seater option. That's to be expected lol. But if I'm reading this right the issues with no customization has been fixed or do I need to wait until reset?

**Comment by BluNero** [comment]
Understandable, it would have been cool if they implemented 3 seaters but it is what it is. So has the vehicle been adjusted now?

**Comment by BluNero** [comment]
Also don't know if I mentioned that aside from Engine/Transmission/suspension etc. upgrades there was no customization options Window tint/Wheels/Body parts etc. I have not taken the vehicle to the shop since this ticket was created though.

**Comment by ZacLuxton** [comment]
Yes, upgrades and speed has been tweaked

**Comment by BluNero** [comment]
Fantastic, I'll be sure to check it out today after work. Thank you very much for the quick work. I really appreciate everything y'all are doing.

**Comment by BluNero** [comment]
I have just gone through everything with the car and everything is much much better. The only thing is that not the doors open and glitch inside of the car lol.

**Comment by BluNero** [comment]
So I have completely nodded the new and improved F1. Absolutely in love with it. The only thing is when you try to get into the driver side door it acts like the Tesla truck and you besically teleport into the car instead of opening the door

**Comment by ZacLuxton** [comment]
Yeah - That's a model issue - nothing we can do
