### ISSUE TITLE
BMW E60 M5 (Supporter) 

### ISSUE THREAD

**Issue by Tagster47** [fkk-cz/noire_vehicles#634]
Any chance we can have the exhaust/engine sound looked at. It's so loud the the audio breaks for the game. It cuts out any conversations in cars and you can't talk on the phone.

Breaks don't seem to stop the car very quickly either. Trying to bring the car to a stop causes it to slide.

**Comment by gxdsent** [comment]
there’s nothing wrong with the engine sound. it’s actually way more improved than before. either turn down your SFX or sell it lol i’ve heard nothing but positive things about the updated sound, shit i wish i had it on my M4

**Comment by ZacLuxton** [comment]
https://github.com/fkk-cz/noire_vehicles/commit/dde1e4b031608924c9ce97a6928de0c838461860#diff-e58a66ef07f43e50b446c52e7d3d0e830244631d1f167b30b92c2b30d1dbfeaf

**Comment by ZacLuxton** [comment]
Brakes have been fixed - sound will not be tweaked
