### ISSUE TITLE
Tesla Cybertruck Repair Kit Glitch

### ISSUE THREAD

**Issue by ScanPlug** [fkk-cz/noire_vehicles#635]
The Cybertruck will use a repair kit but then wont drive because it thinks it is at 0 fuel even though its an electric car.

**Comment by ZacLuxton** [comment]
Try this fix:
go to a gas station, repair kit spam f to get out of the car let it tele you back in, fill it with gas... repair kit again
and then it just works. 

I have tried this previously and it is effective. You only have to do it once.
