### ISSUE TITLE
2004 Hummer H1

### ISSUE THREAD

**Issue by SavageStonerDude** [fkk-cz/noire_vehicles#638]
jst bought it and it has no upgrade or customized options in the custom shop.. also its seems really fragile for a full size hummer it should be a lot stronger as well feel a little heavier when driving.. please take a look at it.. i cant upgrade anything

**Comment by SavageStonerDude** [comment]
page up menu doesnt work either.. ive seen other hummers with different body parts on bt cant get the option myself anywhere.. (there's a front light bar i want attached bt i cant find it )

**Comment by SavageStonerDude** [comment]
and please if possible can we make it a 6 seater theres more than enough room in real hummers for 6 people plus trunk space.. i want to use it for swat training so seating 6 is perfect and reallistic

**Comment by fkk-cz** [comment]
https://github.com/fkk-cz/noire_vehicles/tree/master/DATA/hummer_data

No upgrades on this vehicle isn't surprising, given there's no carcols.meta

In terms of the seating maybe a different layout? @ZacLuxton

**Comment by SavageStonerDude** [comment]
whatever u guys can adjust id really appreciate! especially if u can add some more armor to it, its by far the most fragile car I've ever owned

**Comment by ZacLuxton** [comment]
https://github.com/fkk-cz/noire_vehicles/commit/d1e7dc8b11947d1b349d3e77860b918eafb38e13
