### ISSUE TITLE
2010 Lexus LFA

### ISSUE THREAD

**Issue by hmu4green** [fkk-cz/noire_vehicles#640]
375k car and the handling is terrible. it flips like a truck on corners even with the lowest suspension. it generally is sad because I spent a lot of money on it and my 155k Audi RS7 drives much better and at the same speed. if someone could look into buffing the Lexus LFA I would appreciate it a lot as i dont really want to drive it at this point.

**Comment by ZacLuxton** [comment]
https://github.com/fkk-cz/noire_vehicles/commit/3fe4b217cd1fde55104b877d69754c09bb65a5dd - fixed
