### ISSUE TITLE
Brabus Rocket 900

### ISSUE THREAD

**Issue by sympozium70** [fkk-cz/noire_vehicles#642]
The rocket is so slow for a 900HP beast that it is. IRL it tops out at 205 but in-game it struggles to reach 150 on the clearest highways. Friendly Cop in town recommended I take it up here. Love the city

**Comment by ZacLuxton** [comment]
https://github.com/fkk-cz/noire_vehicles/commit/ef999a0fdad437f17398506583a5e21d3c5a5e98 - already tweaked this last night
