### ISSUE TITLE
2019 Mitsubishi Lancer EVO top speed

### ISSUE THREAD

**Issue by woebud** [fkk-cz/noire_vehicles#645]
Could you please increase the top speed of the evo? Currently on flat I can barely hit 142-145ish. Stock evo's IRL can go 162mph, upgraded evo's can hit about 170+mph. I feel like 170mph would be perfect while upgraded in city, personally, because it's realistic and it would make it pretty competitive with the Supra in the city which is what i'm hoping for.

**Comment by woebud** [comment]
Mitsubishi Lancer Evolution X

Horsepower | 291 @ 6,500 rpm
Torque | 300 lb-ft @ 4,000 rpm
Top Speed | 162 mph
0-60 mph | 4.5 sec

source:
https://www.topspeed.com/cars/car-news/the-mitsubishi-lancer-evolution-sedan-might-rise-from-the-dead-but-how-ar185867.html

**Comment by woebud** [comment]
it's been nearly two weeks, is this planning on being implemented?

**Comment by ZacLuxton** [comment]
https://github.com/fkk-cz/noire_vehicles/commit/1dd9016ece0f13117ebcc314e8234b01a795a71f
