### ISSUE TITLE
350z Speed and Sound

### ISSUE THREAD

**Issue by OngItsMe** [fkk-cz/noire_vehicles#646]
As far as sound the car doesnt even resemble what its like in real life. I bought my 350z stock and since its never sounded how it sounds in game and also whats up with the speed its getting destroyed by trucks like Nissan titans and Ford Raptors??
Please fix this and make this realistic :)

**Comment by ZacLuxton** [comment]
https://github.com/fkk-cz/noire_vehicles/commit/fdb04f90a103936813fb7dd025dc41e1d0a14f76 - Not fixing the speed, car is 35k, maxed out insta climbs to 120. Sound has been tweakes
