### ISSUE TITLE
Nissan R390 Performance

### ISSUE THREAD

**Issue by gxdsent** [fkk-cz/noire_vehicles#649]
_fInitialDriveMaxFlatVel value="148.000000"_
...this hurts me to the core that its that bad for the car it is lol personally i think an upgrade is due for this car so my import is worth the buy @500k.

For reference:
Top Speed
220 mph (354 km/h)
0-60 mph
3.9 seconds
Engine
3.5L Turbocharged V8
Horsepower
550 bhp (410 kW) @ 6800 rpm
Torque
470 lb⋅ft (637 N⋅m) @ 4400 rpm
Layout
Mid-Engined, Rear-Wheel Drive
Transmission
6-speed Manual
Weight
1440 kg (3175 lbs)

**Comment by ZacLuxton** [comment]
https://github.com/fkk-cz/noire_vehicles/commit/76bbf4c3816b1b289bbea8213aed3b47c884cc38 - Should do 185
