### ISSUE TITLE
Subaru Impreza WRX STi no upgrades

### ISSUE THREAD

**Issue by wetweebs** [fkk-cz/noire_vehicles#650]
this car only has a turbo upgrade and no others. would be nice if the rest were available

**Comment by ZacLuxton** [comment]
https://github.com/fkk-cz/noire_vehicles/commit/c3bd6d5dfe3e48eea2bb23136dfd1f6f8b0767af#diff-6496fc6f9dbe3c0d06ae5bf4d4c9c8dd6afdaf9a52bf49aa99b2a095af66e80e
