### ISSUE TITLE
2015 Ferrari California T 

### ISSUE THREAD

**Issue by MrGoony** [fkk-cz/noire_vehicles#651]
First off, this car is great, love the look and feel of it. The only issues I have noticed with the car are that there is a glitch where you go through the ground when you get into the vehicle and the top speed is 161 mph. This is a badass car, realistically this car goes 190+, I'm not asking for that but for a $228,000 car, a 10-15 mph boost on the top speed would make this car perfect for the purchase. Hope this can happen, thank you!

**Comment by ZacLuxton** [comment]
https://github.com/fkk-cz/noire_vehicles/commit/de47bc99498f189fb2a1a500027fab28ea7f5cdb
