### ISSUE TITLE
Tesla Cyber Truck Durability

### ISSUE THREAD

**Issue by ItzHunterrrrr** [fkk-cz/noire_vehicles#652]
Truck is very fragile. a few rocks, a light bump and you're red on the side of the road. could probably be doubled

**Comment by ZacLuxton** [comment]
_sigh_

**Comment by ZacLuxton** [comment]
https://github.com/fkk-cz/noire_vehicles/commit/828e2e53d246a637c90ef4d836e91f9854803998 - it was _super_ broken, but i mean it is a cybertruck sooo. Fixed anyways :)
