### ISSUE TITLE
Chevrolet Corvette C8 Mansaug

### ISSUE THREAD

**Issue by Loyalstartv** [fkk-cz/noire_vehicles#653]
the car turning is very bad also the car cant drive on dirt road at all it will stop right in the middle of it the sound of the car sound like a ped car the upgrades is missing a few  the top speed of the car is 160 mph it should be way faster den that

**Comment by Loyalstartv** [comment]
the acceleration and shifting is slow it take a long time for the car to take off

**Comment by ZacLuxton** [comment]
> the car turning is very bad also the car cant drive on dirt road 

This is meant to happen as people were taking super / hypercars off road to evade police which is super unrealistic

**Comment by ZacLuxton** [comment]
https://github.com/fkk-cz/noire_vehicles/commit/ea3b7b789c6ba1479ad860a3470d6724e648ba5b - Same handling ID as the Normal C8
