### ISSUE TITLE
'70 Chevelle SS mods

### ISSUE THREAD

**Issue by MrGoony** [fkk-cz/noire_vehicles#654]
There are customization options listed in the body shop but don't actually appear on the garage. Would love to get access to those if you guys can fix them, thank you!

**Comment by ZacLuxton** [comment]
https://github.com/fkk-cz/noire_vehicles/commit/c3bd6d5dfe3e48eea2bb23136dfd1f6f8b0767af#diff-f12cb433736a806b2158aeeca3a7471a909430cd61bda32f8a48ec33a305842d
