### ISSUE TITLE
2020 Rolls Royce Cullinan Performance and Cosmetic Issues

### ISSUE THREAD

**Issue by YungNino** [fkk-cz/noire_vehicles#657]
I want to submit a vehicle buff for the 2020 Rolls Royce Cullinan, the regular and the black badge. But the regular model is my main concern as that's the car I just bought. 

After test driving it around the city and airport, I was only able to reach a top speed of 142 mph. 
In this city, the torque is set at 325 lb-ft with the vehicle having 5 speed transmission.

According to https://www.topspeed.com/cars/rolls-royce/2020-rolls-royce-cullinan-driven-ar190653.html and a couple other online sources, the car is supposed to have a torque of 627 lb-ft with 8 speed transmission, going 0-60 in 4.6 seconds. Many sites list the top speed at 155mph. 

This vehicle also doesn't let me make any cosmetic upgrades at Los Santos Customs (besides respray) such as window tints, neon under glow, interior color, and horn, rims. It does not let me make any performance upgrades (except turbo) such as engine, transmission, armor, etc. Pressing the horn has about a 2 second delay from pressing it to hearing the actual sound.

This vehicle is also rather quiet considering it's a v12 engine in real life. A buff to the sound, making it louder would be the cherry on top to make this car the luxury vehicle it's supposed to be. 

One last thing I noticed, this vehicle can be hotwired with the regular multi tool lock pick. It costs over $300k so I feel like it should require the more expensive tool to hotwire it.

Thank you in advance.

**Comment by ZacLuxton** [comment]
> After test driving it around the city and airport, I was only able to reach a top speed of 142 mph.
In this city, the torque is set at 325 lb-ft with the vehicle having 5 speed transmission.

According to https://www.topspeed.com/cars/rolls-royce/2020-rolls-royce-cullinan-driven-ar190653.html and a couple other online sources, the car is supposed to have a torque of 627 lb-ft with 8 speed transmission, going 0-60 in 4.6 seconds. Many sites list the top speed at 155mph.

We're not going to buff it a little bit, makes 0 sense

> One last thing I noticed, this vehicle can be hotwired with the regular multi tool lock pick. It costs over $300k so I feel like it should require the more expensive tool to hotwire it.

No - All cars no matter the cost can be hotwired, even in irl you can use a standalone one. Make a suggestion in discord if you feel that should be changed.

> This vehicle is also rather quiet considering it's a v12 engine in real life. A buff to the sound, making it louder would be the cherry on top to make this car the luxury vehicle it's supposed to be.

Will find a better audio hash for it

**Comment by YungNino** [comment]
Why does it make zero sense to buff the speed to what it is in real life?

**Comment by ZacLuxton** [comment]
https://github.com/fkk-cz/noire_vehicles/commit/35606047c8bc8b619c6a6aad7c128ca292a69448 - audio tweaked
