### ISSUE TITLE
BMW M8 Armor and Speed

### ISSUE THREAD

**Issue by GunnaWunnaa** [fkk-cz/noire_vehicles#658]
I have had the BMW M8 for a while now and it has just happened to keep getting nerfed. In the past the car used to have hydraulics and pretty decent armor but now both of those have been removed. I understand that the hydraulics might have been a mistake and I understand why it was removed but the armor on the car is a whole different story. I used to be able to bump into a few thing on accident and the car would be fine or even start smoking but that was okay. But now I would bump into a road sign and the car would start smoking or just break entirely. The speed of the car is also a problem since cars that are significantly cheaper go faster than this car which I don't understand. I have been told in the past that the speed of the car takes its inspiration from real life cars so I searched up the average speed of a BMW M8 and it says it can go 190. The speed of the car right now goes about 155 to 160 and I feel as if the price and the speed of the car don't match respectively. The car has just been a difficulty recently for me and even if I try to sell it everyone knows of the problems it has so it it basically impossible to sell. So if it is possible to up the armor and the speed just even a little on the car it would be very appreciated. Thank you for taking the time to read this.

**Comment by ZacLuxton** [comment]
Armour has never been touched on this vehicle?

![image](https://user-images.githubusercontent.com/79383480/134705501-6d21c455-267f-4332-99d2-75c8c5da15e3.png)


Will tweak it a little bit

**Comment by ZacLuxton** [comment]
https://github.com/fkk-cz/noire_vehicles/commit/4ea7e4a02b9022f5096a9c64e6561981e8f9f980
