### ISSUE TITLE
Handling and Braking on the 2018 Dodge Durango

### ISSUE THREAD

**Issue by OzzyWunna** [fkk-cz/noire_vehicles#659]
I've recently bought the Gold Supporter Membership to purchase the 2018 Dodge Durango SRT and I have noticed how the handling of the vehicle is horrible. My car will consistently tip over after every turn and result in me having to ask someone to tip it over. I'm having issues with the braking as well and I feel that this is part of the problem of it tipping it over. The car slows down very slow which leads to so many accidents. I'm always on a physical run to the store to purchase a repair kit. Comparing to the realistic Dodge Durango it does not come close with handling and the breaking as it is a muscle SUV vehicle. I have come to realize that a lot of the supporter vehicles come with a minimal amount of customization and upgrades and a lot of problems respectively. If it is possible to fix the handling & braking problem it would be very appreciated. Thank you for taking the time to read this.

**Comment by ZacLuxton** [comment]
https://github.com/fkk-cz/noire_vehicles/commit/921d6176c95bba8540d6b5596bab7808fdd471e7
