### ISSUE TITLE
2014 BMW M4

### ISSUE THREAD

**Issue by AlexBishop1112** [fkk-cz/noire_vehicles#661]
Please just change to noise of the car sounds like a V8, if you could put the engine sound of the r34 on this car too. Sorry for complaining about this just every time i get in it hurts to hear a v8 sound come out a 3.0 I6

**Comment by ZacLuxton** [comment]
https://github.com/fkk-cz/noire_vehicles/commit/d8091257bad0e3f100c05926a427bb5a53a6d2ce
