### ISSUE TITLE
2020 Rolls Royce Cullinan Follow Up

### ISSUE THREAD

**Issue by YungNino** [fkk-cz/noire_vehicles#663]
First off, thanks for addressing the audio for this car.

The Rolls Royce Cullinan goes about 140 in game and in real life it goes 155. In the last issue for this vehicle you said "why would we buff it a little bit, makes zero sense" and I think it should be buffed so that it can be realistic to how it is in real life. Also, in game the torque is only 325 lb-ft. In real life it's 627 lb-ft. 

So my reasoning is that I want this vehicle to be how it is in real life. That top speed and torque buff to how it is in real life would actually make a big difference in performance.

Are you able to make it so that cosmetics can be upgraded? (window tints, under glow, interior)

Thanks

**Comment by ZacLuxton** [comment]
https://github.com/fkk-cz/noire_vehicles/commit/6507f47c2ab6ef6d85862f4ea9954ff3d1b0ef05
