### ISSUE TITLE
McLaren Senna

### ISSUE THREAD

**Issue by Archerr95** [fkk-cz/noire_vehicles#665]
a 715k car built for handling has the turning circle of a boat, and feels just as heavy... speed and acceleration are fine, it just wont go round corners at any kind of speed. also, the spoiler doesnt flip up under braking like it does IRL (not massively fussed about this though)

**Comment by ZacLuxton** [comment]
https://github.com/fkk-cz/noire_vehicles/commit/9904f2b55c85228c9a5a11cb27976fe1549674c2
