### ISSUE TITLE
2015 BMW M3 F80

### ISSUE THREAD

**Issue by PaaraaM** [fkk-cz/noire_vehicles#667]
the car was just added and has no upgrade options at all for anything in the shop

**Comment by ZacLuxton** [comment]
https://github.com/fkk-cz/noire_vehicles/commit/c3bd6d5dfe3e48eea2bb23136dfd1f6f8b0767af#diff-0e613201cedef1b49db1d874265dc6fadb7d1c8b4e1926f98df8eff73816df98
