### ISSUE TITLE
Mustang Mach- E

### ISSUE THREAD

**Issue by Tagster47** [fkk-cz/noire_vehicles#669]
Any chance something can be done with the handling, I know the top speed ain't gonna be great but dang that handling on this is like driving a bus. I have owned plenty of cars in the city and this handling is the worst. Understand if it's top speed is 130mph like IRL but the handling is so frustrating. Can't go from inside lane to 2nd lane on a right turn, have to cross traffic at 45mph. 

You are crushing it and thanks for all you do.

**Comment by ZacLuxton** [comment]
https://github.com/fkk-cz/noire_vehicles/commit/15f18a77eeeca9758aab3f4253bbe549ebf9c26f
