### ISSUE TITLE
Nissan GTR-50 

### ISSUE THREAD

**Issue by Tycarnell** [fkk-cz/noire_vehicles#671]
Can i please get a speed boost to the supporter Nissan GTR-50 it only has a top speed of around 160is and per research Its top speed is 196 mph.  The 0-60 is good but it just bottoms out at 150 then drags to 160 i barley see anything above that.  This car should not be losing races to the daytona. please fix

**Comment by ZacLuxton** [comment]
Daytona has been nerfed recently, Push should be coming today

**Comment by ZacLuxton** [comment]
https://github.com/fkk-cz/noire_vehicles/commit/803fb65070573a1d9ac88742b47da20cfe27e633
