### ISSUE TITLE
honda civic sir eg6

### ISSUE THREAD

**Issue by cracksparrow69** [fkk-cz/noire_vehicles#672]
no upgrades, cant put window tint, only thing that can be done is respray, horn and headlights. nothing else

**Comment by cracksparrow69** [comment]
with a turbo on it, with 15psi should hit 150 mph, top speed currently is sub 150

**Comment by cracksparrow69** [comment]
"Before you learn how to turbo B16B/B16A, you need to restore your engine and make sure it is reliable. To start with, a standard B16A or B16B will do; their stock internals can withstand about 300whp.
The main performance parts that you will need are a TD05-16G turbocharger (Evolution 8) along with a turbo manifold and an intercooler, oil feed line and oil return line are to be installed. You will also need a wastegate, a blow-off valve, a piping kit, a Walbro 255 fuel pump, an AEM fuel rail, an aftermarket fuel regulator, 550 cc fuel injectors, Type R cams, adjustable cam gears, a 2.5 inch exhaust system, a wideband air/fuel oxygen sensor, and a Hondata ECU.
These upgrades will be enough to get 300 HP, and cover 1/4 mile in less than 12 seconds.
The power may be more, but it is better to make a reliable engine and buy low compression pistons (compression ratio ~8.5). Besides forged pistons, you will need aftermarket rods, a block guard, ACL bearings, and ARP head studs. Comprehensive approach to cylinder head tuning will also be needed. All these upgrades require a lot of money that you can use to buy something like a Nissan GTR.
You can make your life easier, and buy a B16A Jackson Racing supercharger. Along with a 2.5″ exhaust, you will get 210+ horsepower." 

this is from http://mywikimotors.com/honda-b16a-b16b/ which shows a bunch of specs on this car and engine

**Comment by ZacLuxton** [comment]
Got a photo of the vehicle?

**Comment by cracksparrow69** [comment]
Need a picture of the car in game or irl

**Comment by cracksparrow69** [comment]
![Uploading 26027B02-CD3B-49D6-B20B-018FB1306A21.png…]()

**Comment by cracksparrow69** [comment]
Not sure if the pictures sent, I sent them from my phone of the in game car

**Comment by cracksparrow69** [comment]
![image](https://user-images.githubusercontent.com/89215584/134832531-bcba385a-9d2b-4cd9-ab98-67b28aa44a0a.png)

**Comment by cracksparrow69** [comment]
![image](https://user-images.githubusercontent.com/89215584/134832552-6a2eacee-1bc9-43ea-ad28-b7b1093003d1.png)

**Comment by ZacLuxton** [comment]
Thanks - Sorry I didn't know which car it was. I'll take a look later

**Comment by cracksparrow69** [comment]
No worries, you guys just added it on Saturday so it’s pretty new

**Comment by cracksparrow69** [comment]
not sure if this will help at all, in the city its a 3 speed but irl its 5 speed

**Comment by cracksparrow69** [comment]
i see that this was tweaked, i tried reading what was changed but dont know how to decipher all this?

**Comment by ZacLuxton** [comment]
https://github.com/fkk-cz/noire_vehicles/commit/8b72d15f777d27e2cb37fb432b730968cd48f883 - Tweaked
