### ISSUE TITLE
2020 Corvette c8 StingRay

### ISSUE THREAD

**Issue by Zsnipe13** [fkk-cz/noire_vehicles#673]
Neon's don't work, along with that the windows get so dark you can't first person and cant see out. Also it gets dirty super fast for no reason and glitches out textures.
![Screenshot (10)](https://user-images.githubusercontent.com/91433641/134821588-bd5c8655-7a3b-4cd2-9e3e-5b7d3da99499.png)

**Comment by ZacLuxton** [comment]
Textures seem like a model issue and is something we can not fix

**Comment by Zsnipe13** [comment]
it being constantly dirty didn't happen yesterday it just started today and the neons, i can see them if i get on a curb but onces the car is even it stops

**Comment by ZacLuxton** [comment]
I'll look into it later for you
