### ISSUE TITLE
2020 Rolls Royce Cullinan Cosmetics

### ISSUE THREAD

**Issue by YungNino** [fkk-cz/noire_vehicles#675]
We're not able to upgrade the cosmetics on the 2020 Rolls Royce Cullinans, would it be possible to make it so we could add neon under glow and tinted windows? 

Thank you in advance

**Comment by ZacLuxton** [comment]
https://github.com/fkk-cz/noire_vehicles/commit/c3bd6d5dfe3e48eea2bb23136dfd1f6f8b0767af#diff-ae9b7b08708101859cab47c102d1a6498245c437c2a592584a806a26cd9d125c - did both the normal one and the other one
