### ISSUE TITLE
lamborghini huracan performante

### ISSUE THREAD

**Issue by EveEnchooli** [fkk-cz/noire_vehicles#676]
THIS CAR IS MADE OUT OF PAPER MACHE!
Even with armor fully upgraded, you hit a pebble and the car fully breaks down.
I understand that people used to evade like crazy in this car, but I will end up literally spending more money on repair kits to fix this car than I did for the car itself.

**Comment by ZacLuxton** [comment]
https://github.com/fkk-cz/noire_vehicles/blob/4654481ded665931294b0d5ef595eb6a3e7d853c/DATA/hurper_data/handling.meta#L41-L44

Not sure what you mean? The Damage mult's are standard as other cars?

**Comment by ZacLuxton** [comment]
https://github.com/fkk-cz/noire_vehicles/commit/7f8d6e867099e03ed76880e1d5e6523e9cdb6315
