### ISSUE TITLE
2011 Mazda RX 8 R3

### ISSUE THREAD

**Issue by Tagster47** [fkk-cz/noire_vehicles#677]
Car needs some love all around. While this car was not that popular IRL it has some even more unloveable features in the city. 

The difference between stock and fully kitted is hardly noticeable. I am getting passed by Colorados on the road and turning in the city is non existent. It's smash into building on one side of the road to then correcting finally and smashing into another. 

I'll hold it until it gets looked at but might be the shortest owned car I have ever had.

**Comment by ZacLuxton** [comment]
Have you got a photo?

**Comment by Tagster47** [comment]
I can get one when I can get back into the server tonight. Its the
non-supporter one.

**Comment by Tagster47** [comment]
It is the RX8-R3 Non supporter.

**Comment by ZacLuxton** [comment]
Got it - Its 2011 not 2017

**Comment by ZacLuxton** [comment]
https://github.com/fkk-cz/noire_vehicles/commit/cc93b071123af4c0819bb0d539788c43eec6b78a
