### ISSUE TITLE
Suzuki Hayabusa Gsx1300

### ISSUE THREAD

**Issue by butternut97** [fkk-cz/noire_vehicles#678]
broken mod kit no upgrades cant change the paint color either

**Comment by ZacLuxton** [comment]
https://github.com/fkk-cz/noire_vehicles/commit/c3bd6d5dfe3e48eea2bb23136dfd1f6f8b0767af#diff-2e056f889ef1a2e01504190c6a62a200bfd88f0875399845b10b1c0d208ce4a2
