### ISSUE TITLE
Lexus LFA

### ISSUE THREAD

**Issue by Envy12345** [fkk-cz/noire_vehicles#679]
not realistic speed at all. the sound is very good though
https://fastestlaps.com/models/lexus-lfa
it has a 202 top speed and a 3.6 second 0-60 not saying this needs to be right on just that its not close one bit

**Comment by ZacLuxton** [comment]
waiting for PR to merge, but already tweaked it

**Comment by ZacLuxton** [comment]
https://github.com/fkk-cz/noire_vehicles/commit/3fe4b217cd1fde55104b877d69754c09bb65a5dd
