### ISSUE TITLE
Lexus LFA breaking and handling.

### ISSUE THREAD

**Issue by SirKinu** [fkk-cz/noire_vehicles#681]
The handling is the one issue that I see with the Lexus LFA.  The steering ratio seems very slow and the handling is like ice.  This article claims cornering grip of 1.06 lateral G stock.  A faster steering ratio also seems to be a good addition to make this car more lively, especially for $375,000.

https://www.edmunds.com/car-reviews/track-tests/track-tested-2012-lexus-lfa-vs-2011-porsche-911-gt2-rs.html

**Comment by ZacLuxton** [comment]
Should be fixed by next restart
