### ISSUE TITLE
Lexus LFA question.

### ISSUE THREAD

**Issue by SirKinu** [fkk-cz/noire_vehicles#683]
We received a LFA tweak that brought a more realistic acceleration and top speed a few days ago.  Then the handling and braking was tweaked.  Why does the car now have a slower top speed by 40mph?  I know there are fast cars in the city that handle well too, so why did the LFA get slower when the handling was tweaked?

**Comment by ZacLuxton** [comment]
https://github.com/fkk-cz/noire_vehicles/commit/11832714eec8448276eff5008cbcbb22fb0b243c - should go 190
