### ISSUE TITLE
Porsche Taycan

### ISSUE THREAD

**Issue by wetweebs** [fkk-cz/noire_vehicles#684]
top speed of 134mph is extremely underwhelming. the actual top speed (apparently) is ~162mph, which would actually be perfect since that is just barely faster than the Tesla's. this would make the car perform more in line with expectations without giving it crazy overboard performance. a far less important side note: it turns like a boat... 

thank you for your work, and sorry if I've been annoying with all my tweaks

**Comment by ZacLuxton** [comment]
https://github.com/fkk-cz/noire_vehicles/commit/238f4eb688548b3dc020d2e004e806ab3e394364
