### ISSUE TITLE
2017 mclaren 720s

### ISSUE THREAD

**Issue by TheK0opa** [fkk-cz/noire_vehicles#687]
The car went to 200 in the test drive then I add on upgrades and the car only hits 150. Is this a common issue? And can the car be adjusted to actually go 205 mph. I mean the specs show the car in irl can go 211 top speed. Can the sound also be adjusted to something more aggressive it is an 8 cylinder.

**Comment by ZacLuxton** [comment]
the car is 200K - people will just buy that shit to evade police, and then it'll get nerfed again. I'll take a look

**Comment by TheK0opa** [comment]
Its 309k but its good i think the acceleration needs adjusting my bad i just drove it again it was fine on top speed its just accelerating that sucks i mean the brakes really suck at the high speeds too. Maybe adjust the braking just a tad bit obviously don't want it being bought by everybody. Just need it to get the accelerate faster and brakes adjust.

**Comment by TheK0opa** [comment]
Sound is fine i went back with sound up.

**Comment by ZacLuxton** [comment]
the way this thing glides round corners doing 150...

**Comment by ZacLuxton** [comment]
10seconds to go to 100 too.... Ofc the breaks are gonna suck at high speed. thats the point

**Comment by ZacLuxton** [comment]
https://github.com/fkk-cz/noire_vehicles/commit/f49ba684fe216917831ef056f79cacc1c80688d6

**Comment by TheK0opa** [comment]
But a 10 second car is a subie or something cheaper not a 300k mclaren

**Comment by ZacLuxton** [comment]
Updated the accel a little bit, tweaked turning too
