### ISSUE TITLE
Toyota Chaser Jzx100

### ISSUE THREAD

**Issue by iiiiTma** [fkk-cz/noire_vehicles#688]
you cant turn traction contol off or on on Toyota Chaser Jzx100   becouse its a sedan, could you make it soo you could drift with it by making the traction controll work on it becouse its a jdm car.

**Comment by ZacLuxton** [comment]
https://github.com/fkk-cz/noire_vehicles/commit/d9f2ee2581fb5605886393ac9853b05134da0f40 - now under "sport" so should be able to turn on / off DSC
