### ISSUE TITLE
Electric Tron Bike

### ISSUE THREAD

**Issue by alrob19** [fkk-cz/noire_vehicles#690]
Is it possible to make the Tron bike electric with a slightly faster acceleration? Electric would just feel right and it's not super functional right now compared to other bikes unless there are other positives I'm missing. Maybe it’s just like a cool dorky vanity item which I would understand!!

**Comment by ZacLuxton** [comment]
it's got the rockstar / vanilla tuning and not a custom one, so no it doesn't. More like a cool light vehicle lol
