### ISSUE TITLE
Ferrari 812 Superfast

### ISSUE THREAD

**Issue by Trihawk** [fkk-cz/noire_vehicles#708]
Love the car, my only issue is that the handling is not in par with any other 300k+ car. It can barely make turns. I don't even care about the top speed not being equivalent to the real one, would just like to be able to drive it and it not feel like a boat.

**Comment by ZacLuxton** [comment]
https://github.com/fkk-cz/noire_vehicles/commit/50d97d3a580d20f7fca6403601a24fa03fedae29 - Done
