### ISSUE TITLE
New Jaguar XJ220

### ISSUE THREAD

**Issue by gxdsent** [fkk-cz/noire_vehicles#713]
Just purchased and there are no upgrades and kit is coming up as NULL

**Comment by ZacLuxton** [comment]
> Just purchased and there are no upgrades and kit is coming up as NULL

?? - Do you mean upgrades are just saying NULL, or the vehiclename?

**Comment by ZacLuxton** [comment]
https://github.com/fkk-cz/noire_vehicles/commit/c3bd6d5dfe3e48eea2bb23136dfd1f6f8b0767af#diff-8373088400c04cb9040e2f5b3f3e76d7ff138469e08c7a27903b7b296f58377c
