### ISSUE TITLE
Bugatti veyron - Luxury motorsport

### ISSUE THREAD

**Issue by MadBasel** [fkk-cz/noire_vehicles#72]
The Bugatti is so slow it’s unrealistic tbh. The thing goes 170mph when IRL It should push 250mph. Also the engine sound doesn’t sound like an actual Bugatti.

**Comment by DankGrandma** [comment]
audioNameHash monster3 audioNameHash sounds good (wont let me show the >/<)

if we set the fInitialDriveMaxFlatVel value to 250
then set the fInitialDragCoeff value to 1.05
it should top out at 195ish

**Comment by fkk-cz** [comment]
> 
> 
> audioNameHash monster3 audioNameHash sounds good (wont let me show the >/<)
> 
> if we set the fInitialDriveMaxFlatVel value to 250
> then set the fInitialDragCoeff value to 1.05
> it should top out at 195ish

https://github.com/fkk-cz/noire_vehicles/commit/7fff78934425d7e2888bdc662451d68715ec21c9#diff-f891537dac54e63c649ed548effb65529f75d5c5112c5afe0b94641419ce78d3
