### ISSUE TITLE
Lamborghini Huracan Evo Spyder

### ISSUE THREAD

**Issue by Rojingrey** [fkk-cz/noire_vehicles#720]
couple issues with the car,1st when you're at a stop and press on the gas it spins out for a good second or 2 even tho its an awd car but struggles to get traction.2nd the car barely turns without sliding like if there was hydroplane everywhere this is cool for drifting but gets frustrating when driving the vehicle normally.3rd not asking for the speed to bump up but the acceleration could be better got gapped by a audi rs4 i think it was even though the acceleration is better on the lambo in a 0-60 run and even in a 0-100 run but he still gained distance in the sandy airstrip.4th the car breaks down after running over a pole at 20 mph in the front end of the car even tho the engine is in the back but it still manages to break down,it doesn't have upgrades for armor so that might help but the car is as ￼brittle￼ as a 0.77mm piece of led for mechanical pencils.last thing is the car is extremely loud it sounds good but just extremely dank,i turned my audio settings to a sliver and still is loud as hell.

**Comment by ZacLuxton** [comment]
https://github.com/fkk-cz/noire_vehicles/commit/626e43e5d473a424b6deaa361b5c9ca21b56e5f2
