### ISSUE TITLE
Nissan GTR Wide body kit sunk in wheels

### ISSUE THREAD

**Issue by SilentRoses** [fkk-cz/noire_vehicles#731]
Good evvening, afternoon or morning. We recently aquired a nissan GTR and added the wide body kit. However we looked at the wheels and they were sunk in. This atrocity has caused me to rip my eyes out. I am now blind. Please fix this!

User: Phoebe Power
Discord: フィービー ♡#9628

![image](https://user-images.githubusercontent.com/82479748/138943388-b2a9b7eb-d50b-4d76-9220-4542853101bc.png)

**Comment by ZacLuxton** [comment]
this is a model issue - if it's annoying you. Then you can get the GTR widebody with custom wheels in supporter sections
