### ISSUE TITLE
Re-balancing Ferrari 488 Pista

### ISSUE THREAD

**Issue by KyleScot** [fkk-cz/noire_vehicles#734]
The car is not balanced in terms of ride height. The front is very low, and the rear is very high. It looks like the car is sitting on an angle. If this can be re-adjusted the car would look a lot better visually.

**Comment by ZacLuxton** [comment]
https://github.com/fkk-cz/noire_vehicles/commit/ee3830aafcbf612977d8c586ade98aa408ffe9a8 - Tweaked
