### ISSUE TITLE
Ford Mustang GT only Default Now?

### ISSUE THREAD

**Issue by Patton1776** [fkk-cz/noire_vehicles#737]
Yesterday when I logged out of LA Noire FiveM, all was normal.  But tonight when I logged in and pulled my GT out of the Garage, all of its wheels and parts were default options.  I figured it was just a save issue, so I drove it to customs to re-apply customizations, but only default options are available?

**Comment by Patton1776** [comment]
![image](https://user-images.githubusercontent.com/93364345/139525446-ae959aaa-7689-4a0d-8f32-13a9d48573e8.png)

**Comment by ZacLuxton** [comment]
@fkk-cz can you look at this please?

**Comment by ZacLuxton** [comment]
a new car that was added, had a duplicate modkit id. I will tweak this for you now so you should be able to upgrade it

**Comment by ZacLuxton** [comment]
Done

**Comment by Patton1776** [comment]
> 
> 
> a new car that was added, had a duplicate modkit id. I will tweak this for you now so you should be able to upgrade it

Just took it out, took it to the garage.. still only stock options remain.  No change.
