### ISSUE TITLE
Range Rover Vogue Startech

### ISSUE THREAD

**Issue by butternut97** [fkk-cz/noire_vehicles#739]
Car has a broken mod kit no cosmetic or performance upgrades

**Comment by ZacLuxton** [comment]
https://github.com/fkk-cz/noire_vehicles/commit/c3bd6d5dfe3e48eea2bb23136dfd1f6f8b0767af#diff-509f6578e0fb37fb11ed69b01491cce36465be8e13962132019c8da2848ce8f3
