### ISSUE TITLE
Pfister Comet S2.

### ISSUE THREAD

**Issue by SirKinu** [fkk-cz/noire_vehicles#740]
I have searched everywhere for a Safari 911 mod to import into the city, but have found nothing.  The only option is to get the Vanilla Pfister Comet S2.  I think that this car in particular, needs to have a better top speed.  Something more around 160-170 seems reasonable considering the price.  Is it possible for you to modify the stats of Vanilla cars?

**Comment by ZacLuxton** [comment]
We're not buffing vanilla cars
