### ISSUE TITLE
1987 Buick GNX

### ISSUE THREAD

**Issue by Fredbob1122** [fkk-cz/noire_vehicles#741]
for a 100,000 dollar car it is extremely slow and i am very disappointed in it there is no customization that can be done to it other than the turbo. I bought it cause its a dream car and i figured you would be able to upgrade it and make it faster but you cant.....

**Comment by ZacLuxton** [comment]
https://github.com/fkk-cz/noire_vehicles/commit/715aa72bf32a5fa83b203386c3d63e0fba0cfadd - did some minor tweaks on performance and audio hash. Leaving open for no upgrades

**Comment by Fredbob1122** [comment]
ok its good to hear that it is being worked on though

**Comment by ZacLuxton** [comment]
This doesn't have any sort of carcols.meta file meaning I am unable to tweak it for you / add customization to it since this is the only model out there. The car has been tweaked handling wise for you
