### ISSUE TITLE
Mustang GT still default

### ISSUE THREAD

**Issue by Patton1776** [fkk-cz/noire_vehicles#743]
You wrote: "a new car that was added, had a duplicate modkit id. I will tweak this for you now so you should be able to upgrade it"

Unfortunately, issue still persists.  Only default options are available, car is not customizable. 

_Originally posted by @ZacLuxton in https://github.com/fkk-cz/noire_vehicles/issues/737#issuecomment-956554309_

**Comment by ZacLuxton** [comment]
Wait for a few days. It doesnt happen automatically.
