### ISSUE TITLE
Ferarri F430 S 2009 

### ISSUE THREAD

**Issue by DizzyPoy** [fkk-cz/noire_vehicles#746]
Hello there just want to request the Ferrari F430 Engine sound to be changed to Irl Because right now it’s worth 776k But doesn’t have a great sound just have a sound like a normal Car Whereas it has its own sound called Ferrari F430 F1 sound I request you guys to add the sound to the car it will be much much appreciated 
thank you
Dizzy Poy

**Comment by ZacLuxton** [comment]
find a sound

**Comment by DizzyPoy** [comment]
https://www.gta5-mods.com/vehicles/ferrari-f430-scuderia-add-on-fivem-template-lods

**Comment by DizzyPoy** [comment]
https://www.youtube.com/watch?v=eERf03tNcnM this is how Sound Is!

**Comment by ZacLuxton** [comment]
We need the custom sound, not the vehicle...

**Comment by DizzyPoy** [comment]
https://drive.google.com/drive/folders/1Mlgf-Kh8am8bRRNWBIyzteusYCaK6147?usp=sharing

**Comment by DizzyPoy** [comment]
?1

**Comment by ZacLuxton** [comment]
![image](https://user-images.githubusercontent.com/79383480/140385750-a75dc513-619d-4464-83f3-5bb0e0ebdf69.png)

This is for a lambo?

**Comment by ZacLuxton** [comment]
https://streamable.com/zndb59 - how about this

**Comment by DizzyPoy** [comment]
> https://streamable.com/zndb59 - how about this

This is way better put it would be much appreciated I did lot of research for the sound of the score and found this ad mentioned in the page that it’s for Ferrari and it turned out to be Lambo I guess but you’re one is the best I guess so put it thank you for your research 
Thank you 
Dizzy Poy

**Comment by ZacLuxton** [comment]
https://github.com/fkk-cz/noire_vehicles/commit/d4e16c635e3200e604afd8da44bc79aeb8a4d8f0 - tweaked

**Comment by DizzyPoy** [comment]
Thank you For the Great Support And response And Appreciate the way of communication via GitHub Have A good Day 
Zac
Thank you 
Dizzy Poy
