### ISSUE TITLE
Aston Martin Valhalla

### ISSUE THREAD

**Issue by EveEnchooli** [fkk-cz/noire_vehicles#747]
Hihi!
A friend bought this car recently (but github said no account for them) and it doesn't have any upgrades, no armor, no brakes, no engine, no transmission... you get the gist!
Hoping you can look into this please and thank you 😊

**Comment by ZacLuxton** [comment]
https://github.com/fkk-cz/noire_vehicles/commit/85da20c3957eb9f9fa0b9e98539e4b2dca58a77f - tried a different modkit id
