### ISSUE TITLE
Jesko

### ISSUE THREAD

**Issue by Archerr95** [fkk-cz/noire_vehicles#748]
Handling feels heavy (not suprised), but it maxes out at 195 downhill with traction off. the car does 300 IRL (i know thats not feasible, but it should still compete with the FXXK

**Comment by Archerr95** [comment]
The acceleration from 0-100 is great! But then it’s very very sluggish from 100+, and the top speed is woeful

**Comment by ZacLuxton** [comment]
How much is it?

**Comment by ZacLuxton** [comment]
https://github.com/fkk-cz/noire_vehicles/commit/a766875d0d445d44da590768e6be9741eb3bcbc3
