### ISSUE TITLE
RX-7 Veilside 

### ISSUE THREAD

**Issue by FatherRevolution** [fkk-cz/noire_vehicles#750]
The car has literally no turning or brakes

**Comment by FatherRevolution** [comment]
Also the top speed down hill is only 140 with full upgrades this car should be able to go a lot faster

**Comment by ZacLuxton** [comment]
I'll revert the old slide change that was made a few months back before we got dsc today

**Comment by ZacLuxton** [comment]
that _should_ improve the vehicle

**Comment by FatherRevolution** [comment]
> that _should_ improve the vehicle

It will improve the brakes, turning, and speed?
I just don't think the rx-7 should only go 20 mph faster than the VW Golf but thank you!

**Comment by ZacLuxton** [comment]
It should. I'll revert it, wait a few days for it to go live in the server, and then I'll see if it needs a further tweak. Don't want to mess around with it too much incase it is fine.

**Comment by ZacLuxton** [comment]
https://github.com/fkk-cz/noire_vehicles/commit/a7be822aa902a8ff218ecef5101f4af329307b53
