### ISSUE TITLE
Motorcycle Fixes 

### ISSUE THREAD

**Issue by MAYAN-MARK** [fkk-cz/noire_vehicles#752]
Fix the collision issues with a few of the Harleys.

Add storage to the bikes that have saddle bags.

Buff the speed on virtually all the Harleys as most top out ar 90-100

Atm there is no reason to buy anything but the LCC KRUST as it out performs every other Harley Davidson style bike by a very long shot.

Motorcycle are light and powerful vehicles and shouldn't be out ran by eco cars.

**Comment by ZacLuxton** [comment]
> Add storage to the bikes that have saddle bags.

Not possible, since all motorcycles have the motorcycle vehicle class, if you change that then it could mess the vehicle up completely

**Comment by ZacLuxton** [comment]
> Buff the speed on virtually all the Harleys as most top out ar 90-100

Names? Would be helpful

**Comment by ZacLuxton** [comment]
Harleys are also not meant for speed. So not sure what you mean by that.

**Comment by ZacLuxton** [comment]
> Fix the collision issues with a few of the Harleys.

Explain

**Comment by MAYAN-MARK** [comment]
> > Fix the collision issues with a few of the Harleys.
> 
> Explain



> > Fix the collision issues with a few of the Harleys.
> 
> Explain

The Harley StreetGlide(the bagger with the big fairing) 
Has virtually no brakes and is constantly scraping the ground so when you go over bumps it knocks you off.

The Harley Terminator 2 has an issue when it falls over cannot be picked back up.

**Comment by MAYAN-MARK** [comment]
> > Buff the speed on virtually all the Harleys as most top out ar 90-100
> 
> Names? Would be helpful

The Harley Terminator 2, Harley XL883N and the road king all are very slow in comparison to the other Harley/American bikes. Harleys have excellent power to weight ratios giving them great acceleration and good speed. I think its reasonable to have these bikes top at 120mph as it puts them in a similar bracket as the choppers but the choppers are still better. The acceleration needs to be buffed a bit as well as these bikes are sluggish.

**Comment by MAYAN-MARK** [comment]
> > Add storage to the bikes that have saddle bags.
> 
> Not possible, since all motorcycles have the motorcycle vehicle class, if you change that then it could mess the vehicle up completely

Then cant you just give storage to all bikes? Like 200 is reasonab that way you can store food and a repair kit. Or even use the bikes to transport small amounts of illegal items. There are 2 motorcycle clubs in the city but we cant even use our bikes for illegal activities due to zero storage and the other mentioned performance issues.

**Comment by ZacLuxton** [comment]
> Then cant you just give storage to all bikes? Like 200 is reasonable that way you can store food and a repair kit. Or even use the bikes to transport small amounts of illegal items. There are 2 motorcycle clubs in the city but we cant even use our bikes for illegal activities due to zero storage and the other mentioned performance issues.

No, we are not doing that

**Comment by ZacLuxton** [comment]
We're not tweaking vehicles by small amounts of speed. They aren't made for speed.. Harley's are for cruisers and NOT for speed.
