### ISSUE TITLE
Bugatti Veyron Missing upgrades (supporter) 

### ISSUE THREAD

**Issue by SilentRoses** [fkk-cz/noire_vehicles#753]
The buggati veyron is missing a few upgrades via performance as well as 0 cosmetic. I have a feeling cosmetic is down to the entity itself not having upgrades available however performance wise the upgrades do appear to have a few missing. Also as a note pls take a look at vehicle steering. It's like driving blindfolded with 2 left feet and no arms. 

EDIT: Also missing a few textures. If you crash the entire front bumper is removed. There is nothing under said bumper except air.

**Comment by ZacLuxton** [comment]
https://github.com/fkk-cz/noire_vehicles/commit/e4998c8101e63a72a669055f8f39c16dd1fd0d13
