### ISSUE TITLE
Motorcycle Fix 2.0

### ISSUE THREAD

**Issue by MAYAN-MARK** [fkk-cz/noire_vehicles#754]
Fix the Harley street glide and Harley terminator 2 collision issues. 

Street glide has an issue that is is consistently dragging the ground causing handling issues. The bike also basically has no brakes. 

The terminator 2 has collision issues that when it falls over it cannot be picked up. 
This bike also has no preference upgrades and cannot be painted.

Let try no to close this without adressing all the issues thankyou.

**Comment by ZacLuxton** [comment]
> The terminator 2 has collision issues that when it falls over it cannot be picked up.
This bike also has no preference upgrades and cannot be painted.

Model issues / can't be fixed

> Street glide has an issue that is is consistently dragging the ground causing handling issues. The bike also basically has no brakes.

https://github.com/fkk-cz/noire_vehicles/commit/abd06e3a49284cb0477178322440b4f51c217b2e
