### ISSUE TITLE
2012 lamborghini aventador j speedster

### ISSUE THREAD

**Issue by QuintenM911** [fkk-cz/noire_vehicles#756]
the 2012 lamborghini aventador j speedster isn't showing any of the upgrades and without armor it is a wet paper bag. and all the cosmetic upgrades are gone aswell

**Comment by ZacLuxton** [comment]
https://github.com/fkk-cz/noire_vehicles/commit/40742920d8dbf02533869febc3abf8539c42f4d7#diff-9b492e070f257576b800bc844877f3befcf177f6338a21250830657333981bb9
