### ISSUE TITLE
Kawazaki ZX10R 2016

### ISSUE THREAD

**Issue by iiiiTma** [fkk-cz/noire_vehicles#759]
Its dosnt have any upgrades on it, it only has turbo and thats it

**Comment by ZacLuxton** [comment]
https://github.com/fkk-cz/noire_vehicles/commit/40742920d8dbf02533869febc3abf8539c42f4d7#diff-6353fb66e401891f3a6a267becc8422e0607c7bdab48b08ec5f7166ca0457e1e
