### ISSUE TITLE
2012 Lamborghini Aventador J Speedster

### ISSUE THREAD

**Issue by Cobby1-89** [fkk-cz/noire_vehicles#768]
The 2012 Lamborghini Aventador J Speedster acceleration is super slow and only tops out around 165 MPH. It needs to at least match the 2021 Aventador (I would hope)
the 2021 Aventador tops out around 210.
the 2012 Lamborghini Aventador J Speedster Veh Upgrades are only for the paint, and turbo, and headlights only, no other upgrades at the paint-n-spray.
I believe the 2012 is a typo and is supposed to be "2021" 
Can the speed and upgrades be fixed or looked into, It is a Million Dollar Car lol

**Comment by ZacLuxton** [comment]
> the 2012 Lamborghini Aventador J Speedster Veh Upgrades are only for the paint, and turbo, and headlights only, no other upgrades at the paint-n-spray.

Already tweaked the upgrades recently, if it's still not working then ttheres nothing we can do

> the 2021 Aventador tops out around 210.

I'll just replace the handling id with the aventadors we have in-game

**Comment by ZacLuxton** [comment]
https://github.com/fkk-cz/noire_vehicles/commit/026844db040e380e47e3894eb7d4d511896bf8b1 - tweaked

**Comment by Cobby1-89** [comment]
thank you!!

**Comment by ZacLuxton** [comment]
Some cars are fucked in the ass with the carcols.meta file - i could re-tweak it with a different modkit id and see if that fixes it, but i dont have high hopes it will

**Comment by Cobby1-89** [comment]
no problem as long as its faster then 165 max im good
