### ISSUE TITLE
1967 Shelby GT500 Eleanor

### ISSUE THREAD

**Issue by Arcabian** [fkk-cz/noire_vehicles#769]
I Saved for this car and was disappointed to find no customization apart from color and turbo (Turbo disappears on storage).  There are updated versions of this car and the current one doesn't even have windows. Could we possibly get an updated version or fixed version of this car.

**Comment by ZacLuxton** [comment]
There is no carcols / upgradable options on this vehicle sadly, there is also no other vehicle on gta5mods for this vehicle to replace it with
