### ISSUE TITLE
Mazda Rx7 fc3s

### ISSUE THREAD

**Issue by iiiiTma** [fkk-cz/noire_vehicles#771]
I would like to request a sound change for the car i already have the files, me and some other owners want too change the sounds since its not a good sound,

Heres the mod: https://www.gta5-mods.com/vehicles/mazda-rx-7-twin-rotor-engine-sound

**Comment by ZacLuxton** [comment]
@fkk-cz this is for you

**Comment by Cruzamp** [comment]
There is no more customizations for the rx-7 i had it hella custom like 10 hours ago and then all the customizations are now all gone and it took my money with it.

**Comment by No-Yes1** [comment]
@Cruzamp Can you make a new issue on this - since this is a no upgrades issues. Not a sound upgrade

**Comment by No-Yes1** [comment]
![image](https://user-images.githubusercontent.com/79383480/150588381-d582e89b-caac-4e31-8320-0eb49a1b2051.png)

This is a "OIV" / SP mod. Find one that states "Five-M/Add-On"
