### ISSUE TITLE
2019 Porsche 911 GT2 RS handling tweak

### ISSUE THREAD

**Issue by Zoraketh** [fkk-cz/noire_vehicles#772]
Improved handling tweaks. The vehicle likes to whip around, fishtailing rather easily. Not as crazy as the 2020 911 turbo s. A bit louder on the sound would be nice.

**Comment by ZacLuxton** [comment]
https://github.com/fkk-cz/noire_vehicles/commit/0c9e4d35606eaff5f0a41bf49fbe84aa24726dba - tweaked. this is the last time the gt2rs will be tweaked
