### ISSUE TITLE
2021 Chevy Tahoe Z71

### ISSUE THREAD

**Issue by Ridly7** [fkk-cz/noire_vehicles#774]
Can you give the 2021 Tahoe the same handling as the 2020 Chevy Silverado 3500 since it is a 4x4 and make it go at least 140 mph since that's the "realistic" speed

[https://fourwheeltrends.com/does-chevy-tahoe-have-4-wheel-drive-answered/](url)

**Comment by Ridly7** [comment]
[https://www.vehiclehistory.com/questions/whats-the-chevy-tahoe-top-speed-116163](url)

Here's a link for the top speed

**Comment by ZacLuxton** [comment]
https://github.com/fkk-cz/noire_vehicles/commit/2004d69cf8033e0a1302944bebd94b6377d503fb - tweaked
