### ISSUE TITLE
2018 Zenvo ts1 gt

### ISSUE THREAD

**Issue by TheK0opa** [fkk-cz/noire_vehicles#776]
So i just bought this car and it only goes 135 mph top speed. In irl it goes 235 top speed also the acceleration is horrible it should be way better considering how fast this car really is. For 600 k i expect it to go way faster than a 300k car that goes at least 200 mph with all upgrades. Hopefully it can be done cause the car is really nice. Thanks for all you do zac

**Comment by TheK0opa** [comment]
Can we also change the sound to the c18 lambo

**Comment by ZacLuxton** [comment]
https://github.com/fkk-cz/noire_vehicles/commit/20ba955ff7037d9ee672670cdfb377acedac863d - tweaked, should go around 190 give or take. Changed audiohash to the same as the sc18

**Comment by TheK0opa** [comment]
My other car at 300 k does 210 is there a way to get the ts1 to that

**Comment by ZacLuxton** [comment]
Which one?

**Comment by TheK0opa** [comment]
The mclarens they all go 200 +

**Comment by TheK0opa** [comment]
Even the challenger does 220 downhill

**Comment by TheK0opa** [comment]
They all go for 300k ish

**Comment by TheK0opa** [comment]
https://zenvoautomotive.com/ts1-gt/ Heres a link of the vehicles specs
