### ISSUE TITLE
Car Customization Issue (Livery) - 2010 BMW M5 F10

### ISSUE THREAD

**Issue by mikerobawls** [fkk-cz/noire_vehicles#777]
In the showroom, during test drives, and at the time of purchase this car had no stickers or livery on it. After taking it to the customs shop, it now has a livery and when I select the blank Default option it says it confirms my choice but the livery remains and still says "installed" on the menu. I have seen another person with this same car and theirs doesn't have the livery on it so there must be some kind of issue with mine.

**Comment by mikerobawls** [comment]
Worst case scenario would it be possible to just delete the current version of my vehicle and replace it with a new one of the same year/make/model?

**Comment by mikerobawls** [comment]
Heard someone else having a similar issue, they are unable to choose the "default" option for their car horn now after buying a new one so maybe the issue has something to do with not being able to go back to default after purchasing an upgrade.

**Comment by ZacLuxton** [comment]
This seems like a model issue / broken assets and will need to removed from the game

**Comment by mikerobawls** [comment]
how is it a model issue/broken asset when there are other people on this
server with the exact same car and don't have this issue? But other people
are having issues with reselecting the default option for any car
modification.
