### ISSUE TITLE
Ferrari f8 Tributo

### ISSUE THREAD

**Issue by IsaacGucci** [fkk-cz/noire_vehicles#778]
I bought the F8 Tributo from PDM and went to go customize it and it has a weird bug/bad graphic when it gets dirty I have put pics of the car and how it looks dirty VS clean so you can see the difference. I hope you can fix this because it makes it look really bad and unrealistic look. Also it gets dirty after driving for like 30 seconds on a clean road with out ever even touching dirt. 

Dirty
![F8 Side](https://user-images.githubusercontent.com/94812305/142787643-c0ca7d46-7b71-4846-945b-2bb41611f3ac.PNG)
![F8 Frount](https://user-images.githubusercontent.com/94812305/142787646-12452154-3cd4-436a-b22f-efa9a0b6e031.PNG)
![F8 Back](https://user-images.githubusercontent.com/94812305/142787647-eae4209f-5fc5-428e-acea-fd44b1c15d26.PNG)
![F8side2](https://user-images.githubusercontent.com/94812305/142787648-c9a74af6-61c5-4478-a924-8bafb034e4b8.PNG)

Clean
![F8 Clean 2](https://user-images.githubusercontent.com/94812305/142787712-a4c5a9e3-0d8f-41a1-b48b-119eafcd8346.PNG)
![F8 Clean](https://user-images.githubusercontent.com/94812305/142787713-e0e45fcf-4665-4268-8804-c466ce9cc27f.PNG)

**Comment by ZacLuxton** [comment]
This seems like a model / texture issue and won't be fixed
