### ISSUE TITLE
Dinghy 4S

### ISSUE THREAD

**Issue by QuintenM911** [fkk-cz/noire_vehicles#779]
is there a way to make this boat seat 4 people i bought the 4 seater with the intention of have more people safely on the boat. If it cant be done can you tell me which boat can hold 4 people so i know what to buy so that I can have 4 people on the boat safely I want to do Cayo Perico tours

**Comment by ZacLuxton** [comment]
Sadly, this is rockstar's layout, and since we don't change / tweak layouts of vanilla vehicles (exc. the mptuner cars). We are unable to fix this
