### ISSUE TITLE
the shelby cobra is really bad the handling is horrible and the breaks don't work 

### ISSUE THREAD

**Issue by makka69420** [fkk-cz/noire_vehicles#78]

**Comment by DankGrandma** [comment]
fbreakforce value could go to 1.0
need more info on the handling

**Comment by fkk-cz** [comment]
https://github.com/fkk-cz/noire_vehicles/commit/e42b903c29150e95dde3a03f526c53d8409a1961#diff-546ee0a65b7225165c4b60019955dd540daad7cd65a679611ec70100125ba93a
