### ISSUE TITLE
Unable to reselect the "default" option for any car modification

### ISSUE THREAD

**Issue by mikerobawls** [fkk-cz/noire_vehicles#780]
When customizing any vehicle, once you select anything other than the "default" option for any modification category you will then no longer be able to go back and reselect the default option, it will give you a successful message that it was changed but once you exit out the change will revert back to the previous purchased option. I have personally spoke with someone else having this issue as well so it isn't just me.

**Comment by ZacLuxton** [comment]
Is this for a specific car? or for all cars

**Comment by ZacLuxton** [comment]
@mikerobawls ?
