### ISSUE TITLE
Nissan 370z Supporter

### ISSUE THREAD

**Issue by LibexiL** [fkk-cz/noire_vehicles#782]
So I just bought the 370z that i brought in and im seriously disapointed. Top speed is only about 120 when I know the non supporter goes around 130-140+. The handling on my car and the traction  is absolutely terrible too. Im just hoping to maybe get my 370z to go atleast 150-170mph being that the IRL stock top speed is 155mph. With better handling also.

**Comment by LibexiL** [comment]
https://www.gta5-mods.com/vehicles/nissan-370z-nismo-add-on-engine-sound-fix

Also wanted to see about changing the sound to this.

**Comment by ZacLuxton** [comment]
> https://www.gta5-mods.com/vehicles/nissan-370z-nismo-add-on-engine-sound-fix
> 
> Also wanted to see about changing the sound to this.

@fkk-cz for u

**Comment by ZacLuxton** [comment]
https://github.com/fkk-cz/noire_vehicles/commit/ee8a017b9e876a2909624537480f09900a580082 - Swapped handling id to the normal ``370z``

**Comment by ZacLuxton** [comment]
Leaving open for sound fix

**Comment by No-Yes1** [comment]
Furthermore to this, I've checked the custom sound for this, turns out it just replaces the audio hash to another vanilla one;

     <audioNameHash>furoregt</audioNameHash>

Do you still want that?
