### ISSUE TITLE
Aston Martin Valhalla

### ISSUE THREAD

**Issue by ItsTalent** [fkk-cz/noire_vehicles#784]
I purchased this car from PDM excited to upgrade it and have a fast fun car to ride in the city with my boys. Come to find out. It has 0 upgrades. No Engine. No Transmission. No nothing. Kinda disappointing. I am here. Asking you, with $780k outta my bank to add these to the car. I wanna be able to enjoy my beautiful Asty with all her curves going high speeds and upgrades. Thanks

**Comment by ZacLuxton** [comment]
Tried this before, modkit is broken. cant be fixed
