### ISSUE TITLE
1998 Porsche GT1

### ISSUE THREAD

**Issue by gxdsent** [fkk-cz/noire_vehicles#785]
I don't expect to get a crazy buff or anything but fully upgraded the car on flat (no curb/hill boosts) stays in the 160s. Highest recorded Top speed for the car on track is right above 200. So anything slight would be sick. Gotta make sure this million is worth 👍

**Comment by ZacLuxton** [comment]
https://github.com/fkk-cz/noire_vehicles/commit/1e2be95135e625235ce50e5557700ff7738079ae - Done
