### ISSUE TITLE
2019 Ferrari488 Pista, Sports+

### ISSUE THREAD

**Issue by Zoraketh** [fkk-cz/noire_vehicles#787]
Too loud. Even while driving at lower speeds, it hurts my ears. Handling and braking are fine, with and without traction. The top speed is to low for what it should be able to do. Struggling to hit 180, when it should be hitting around 211mph top speed.

**Comment by ZacLuxton** [comment]
> Too loud. Even while driving at lower speeds

f8 game - sfx volume. Turn it down to 3

>  Struggling to hit 180, when it should be hitting around 211mph top speed.

We're not fixing the speed
