### ISSUE TITLE
Ram 1500 TRX

### ISSUE THREAD

**Issue by Nolan262** [fkk-cz/noire_vehicles#788]
The truck is way to slow it needs to be quicker it tops out at 113 MPH Which isnt realistic. The Acceleration is really slow it should be shooting to 60 mph in 3.7 seconds and through the quarter-mile in 11.3 seconds at 110 mph. It also should sound like like a hellcat because it has same engine which is a 6.2 L V8 ,702 HP, supercharged. I personally think it should go 15 to 20 MPH less than the hellcat in the city which is like 190 MPH . The G wagon goes 180 flat and it has less HP and it pretty much the same weight as the TRX.

**Comment by ZacLuxton** [comment]
![image](https://user-images.githubusercontent.com/79383480/143939688-0dfcbc57-78f9-4ffe-b85e-1aefd9dbd7ff.png)


My drilla, google ain't wrong, 118, not being fixed
