### ISSUE TITLE
the bike mechanics

### ISSUE THREAD

**Issue by zestyspade** [fkk-cz/noire_vehicles#79]
i am a pro BMX rider on the server and i have been trying to hit these insane bridge and building jumps on my bmx. the height is maxes out on is like only 40 20 to 30 feet befor you fall of your bike. increasing the land height for landing would take my skill as a BMX rida to the moon

**Comment by fkk-cz** [comment]
this is not related to any specific handling.meta, we have 'realistic' bike handling mechanics in place to prevent unrealistic/GTA-style driving
