### ISSUE TITLE
Chevelle SS 454 - Customizations dont appear on vehicle

### ISSUE THREAD

**Issue by Patton1776** [fkk-cz/noire_vehicles#790]
Hey there, the 454 SS does show a number of "body part" options when the vehicle is in the shop, but when selected, they do not appear on the vehicle.. in fact, when a modification is selected, visually the part becomes invisible on the car.  Additionally, and far less important, the vehicle is listed as NULL.

EXAMPLE:

Body Parts > Hood SELECTED --- the hood is now invisible

**Comment by ZacLuxton** [comment]
These seems like a model issue then, and can't be fixed. @fkk-cz - can you assist with the `` the vehicle is listed as NULL.``
