### ISSUE TITLE
2010 Aston Martin One 77

### ISSUE THREAD

**Issue by Stagonium** [fkk-cz/noire_vehicles#792]
![image](https://user-images.githubusercontent.com/30944488/144175963-f27f0910-061e-40b6-b154-0c2bd50088e7.png)

Seen in the picture above, the top speed of the One 77 is approximately 220, with a 0-60 of 3.5 seconds. My testing at the test strip never yielded speeds above 145, and given the hefty price tag of the vehicle, I would like to see some love given to it before purchasing. Also, if it helps the weight of the vehicle is actually ~3600lbs, whereas the version in game is ~4,000 lbs.

**Comment by ZacLuxton** [comment]
> also, if it helps the weight of the vehicle is actually ~3600lbs, whereas the version in game is ~4,000 lbs.

That doesn't really change anything

**Comment by ZacLuxton** [comment]
https://github.com/fkk-cz/noire_vehicles/commit/0702d16b84d74f33ea2f1d26cf528081fc48ce66 - 200mph , tweaked acceleration too (not just because I also want this vehicle) :)
