### ISSUE TITLE
Supporter Mitsubishi Evo IX

### ISSUE THREAD

**Issue by GrizzlyO** [fkk-cz/noire_vehicles#796]
the car is a bought tuned car and you cant tell me its not that thing should be chipped and tuned to the shit house however it tops out at 130, its quite unrealistic if you ask me and everyone who has seen my car

**Comment by ZacLuxton** [comment]
![image](https://user-images.githubusercontent.com/79383480/144711980-9257af38-f21f-4dc9-a4a7-2a998fc14078.png)

Wont fix
