### ISSUE TITLE
No upgrades for the Mazda RX-7 FC3s

### ISSUE THREAD

**Issue by Cruzamp** [fkk-cz/noire_vehicles#797]
I had mine hella custom. Then I hopped back on the next day and all the upgrades are gone off my car and when I try to go and add them back on there are no upgrades for the car. You can’t even change the rims.

**Comment by ZacLuxton** [comment]
https://github.com/fkk-cz/noire_vehicles/commit/10f3fe8b97a07307c3d81524a18ce57a49390f08 - changed modkit id. please wait a few days for the PR to merge
