### ISSUE TITLE
Audi RS6 PDM version

### ISSUE THREAD

**Issue by A1000Bananas** [fkk-cz/noire_vehicles#80]
Just asking if its available to get some enging mods , but mostly armour upgrade as the car is super slow (overtaken by kia fortek) also breaks down on the slightest of crashes (mainly npc ) , also be able to remove the stickers.
thank you for your time

**Comment by DankGrandma** [comment]
as far as the carcols.meta, im seeing engine, suspension, brakes, gearbox and armor upgrades. theres prob something tabbed over too far or some little thing but i cant tell where.

**Comment by ZacLuxton** [comment]
in respect of this; "also be able to remove the stickers.", go to LS Customers, click on stickers and use mouse arrow up and down, It may need a new modkit, will see now
