### ISSUE TITLE
Nissan Titan new Trailer 

### ISSUE THREAD

**Issue by IsaacGucci** [fkk-cz/noire_vehicles#800]
Can you add support for the Nissan Titan to be able tow the new trailer ?

**Comment by ZacLuxton** [comment]
Does it have a trailer hook? @IsaacGucci

**Comment by johnvito760** [comment]
it only has the tow bar but no ball

**Comment by IsaacGucci** [comment]
but it can tow ped tillers

**Comment by ZacLuxton** [comment]
Merging with #801
