### ISSUE TITLE
trucks for towing 

### ISSUE THREAD

**Issue by johnvito760** [fkk-cz/noire_vehicles#801]
supporter vehicles with a ball 
1986 chevy k30
1986 k5 blazer 
1997 toyota land cruiser
2004 hummer h1
2006 gmc sierra 1500
2010 dodge ram 3500

ford f350 worktruck
2019 dodge donk
2019 dodge ram  
2017 toyota land cruiser

supporter vehicles with tow package no ball
2010 chevy silverado 1500
2016 chevy suburban
2017 hennessey velociraptor
2017 nissian titan
2018 gmc sierra denali 
2019 ford ranger raptor 
2021 gmc sierra 1500
hummer h2

non supporter tow package 
2014 chevy tahoe 
2020 ford explorer 
ford raptor 
gmc denali

non supporter with ball   
2020 toyota 4runner

**Comment by No-Yes1** [comment]
https://github.com/fkk-cz/noire_vehicles/commit/542e8127e346a02ecff4302d826c32c49ae3db8c
