### ISSUE TITLE
2020 Toyota 4runner - Window Tint Issue

### ISSUE THREAD

**Issue by mikerobawls** [fkk-cz/noire_vehicles#802]
Recently purchased a 4runner, took it to the customs shop and under the "window tint" category when cycling through the different options it doesn't display any potential change, and when I try purchasing any of the options it will take my money but doesn't make the change, and it doesn't show that a change has been made in the list just stays as the "default" setting.

**Comment by ZacLuxton** [comment]
This is a common thing with some vehicles and is due to the carcols.meta,  there is nothing we can do about this due to it being a model issue itself.
