### ISSUE TITLE
Car has no upgrades

### ISSUE THREAD

**Issue by mk3ext** [fkk-cz/noire_vehicles#803]
The 2017 Dodge Charger from PDM in the Dodge section has no upgrades in Los Santos Customs apart from Turbo?

Not sure if this is intended, but would be great to have as the car breaks if you hit a lamp-post whereas others don't

**Comment by D4LSpidey** [comment]
just drive better and your car wont break. ez fix

**Comment by ZacLuxton** [comment]
There is no carcols.meta file for this, which is the reason why you are unable to upgrade it. The handling.meta file seems to be in check with other vehicles;

https://github.com/fkk-cz/noire_vehicles/blob/6dd82e6e99035365dddf7174f2974b4dfd13c053/DATA/2017charger/handling.meta#L43-L46

Not Tweaking
