### ISSUE TITLE
Porsche 911 r

### ISSUE THREAD

**Issue by SirKinu** [fkk-cz/noire_vehicles#804]
I imported the 911 r for one reason, the amount of customization.  The mod website shows an incredible amount of options, but I dont see any in ls customs.  Is this intentional, or do they not exist?

https://www.gta5-mods.com/vehicles/porsche-911-r-2016

**Comment by ZacLuxton** [comment]
?? Did you try page up? Is there normal upgrades i.e engine, brakes, etc?

**Comment by ZacLuxton** [comment]
I've taken a look at this further, the pictures doesnt say "amount of options" - the carcols.meta files etc are all there, so I'm guessing they do not exist.
