### ISSUE TITLE
911 r cont.

### ISSUE THREAD

**Issue by SirKinu** [fkk-cz/noire_vehicles#805]
I saw your comments on the past issue I pulled up, and I know I tried another 911 r mod that didnt work for import.  Is it possible for the modifications to be brought over from this model so they can be used for the 911 r in the city?

https://www.gta5-mods.com/vehicles/17-porsche-911-r-gt3-extreme-tuning-uq

**Comment by ZacLuxton** [comment]
no - as it could cause issues with the current model / crashes since it's not optimised for the vehicle we have in game. That's the issue with the vehicles with have tunable cosmetic upgrades / add-on vehicles in general. It could also cause for higher polycounts and wouldn't wish to risk it.
