### ISSUE TITLE
1993 Skyline GTR (Sound)

### ISSUE THREAD

**Issue by gxdsent** [fkk-cz/noire_vehicles#809]
I was wondering if we can swap out the 93 R32 Skyline sound to this one that better matches the car if it's possible. It sounds so damn good. 

https://www.gta5-mods.com/vehicles/nissan-skyline-r32-r33-r34-rb26dett-i6-engine-sound-mod-for-gta-v

**Comment by No-Yes1** [comment]
https://github.com/fkk-cz/noire_vehicles/commit/5e155dd826a416d8aed5be8eea8fd1906410887e - done
