### ISSUE TITLE
Trailers!

### ISSUE THREAD

**Issue by LibexiL** [fkk-cz/noire_vehicles#810]
Now its not a bug or nothing, just have a complaint of the trailers flipping way to easy and not being heavy enough. Id love to see them stick to the ground a little better, or even have an option to un-flip them simply because once they flip you either have to depend on a DOT, Police, or an Admin to come delete it for you. Its a big issue I know majority of people with trailers have experienced the troubles of having a trailer flip. Its just genuinely annoying and a mood killer if you're mining and I'd love to hopefully something done to these wonderful contraptions.

**Comment by No-Yes1** [comment]
sadly there isn't anything to do. Maybe make an issue on the noire_public repo.
