### ISSUE TITLE
Mitsubishi Evo Lancer IX

### ISSUE THREAD

**Issue by MrKennyG** [fkk-cz/noire_vehicles#813]
Hey,

I bought this car about a week ago and without being a jackass, it is probably the worst driving car in the city I've seen. It turns a trashmaster on ice skates lol. I love the look of it and the fact its a four door and I like it because it isn't ridiculously fast and unrealistic but the handling / braking on it is abysmal. I know the snow effects vehicles tractions but this goes a bit beyond that. I've tested it to other vehicles and have other people drive it in the city and they all say the same thing. 

Was hoping to get you to test drive it in the city and see for yourself to possibly get some buffs to its current stats. 

Thanks,
KennyG

**Comment by No-Yes1** [comment]
Probably the values are too low for the snow to handle. Will test tomorrow once snow clears.

**Comment by No-Yes1** [comment]
Just tested this out with non-snow conditions, seems to be fine so won't tweak it. The values are probably too low for the snow to handle since it's not exactly a ""winter"" car if you will. Won't tweak
