### ISSUE TITLE
2018 Dodge Durango SVT

### ISSUE THREAD

**Issue by CapitalOG** [fkk-cz/noire_vehicles#816]
The Durango is very easily flipped even turning corners at around 35mph. I don't know if this is solution that can be solved or not, but i just thought I'd bring it to attention. Other than being very easily flipped compared to the 2020 tahoe or the 2014 tahoe.

**Comment by No-Yes1** [comment]
https://github.com/fkk-cz/noire_vehicles/commit/a2ea83f1c804478d8edd44216b6dff15dd2dc991 - Done
