### ISSUE TITLE
Toyota MR2

### ISSUE THREAD

**Issue by Pookk** [fkk-cz/noire_vehicles#825]
Headlights don't pop up, leading to them just pointing to the ground and there is no Page Up/Page Down menu that shows for me. 

Also entering the car is a scuffed, but I think the Toyota Chaser has a similar issue? Both vehicles are RHD and that might be the cause?

**Comment by No-Yes1** [comment]
It's nothing to do with how the vehicle is (i.e RHD, AWD or FWD). It's to do with a model issue. I've attempted both of those vehicles, and taken a look at the website where the model issue, and found this;

> **All of the lights are working properly besides the popup headlights**, thats something I left for now because I will be implementing actual pop up headlights animation very shortly. I do not recommend driving in first person mode just yet until I can fix the issue with the window material.
