### ISSUE TITLE
Tesla roadster in dirt has no traction at all.

### ISSUE THREAD

**Issue by noyeahsure** [fkk-cz/noire_vehicles#827]
I just bought the tesla roadster which i love, but when touching any sort of dirt, the handling is just thrown out the window, and any movements you make just cause you to spin over and over again.

**Comment by No-Yes1** [comment]
https://github.com/fkk-cz/noire_vehicles/commit/dced3b4e17dafdea19a430003ac36ec0dcd0ff11 - Should fix it
