### ISSUE TITLE
Mustang Mach E

### ISSUE THREAD

**Issue by Silxy** [fkk-cz/noire_vehicles#829]
Has no trunk. Tried reconnecting to check if it was bugged, walked around and on top.. trunk doesn't exsist. If there's a daddy out there to resolve my problems big up da mandems 🙏 UwU

**Comment by No-Yes1** [comment]
Closing out both of these issues - The model itself does not have a trunk, so you can not access it. This is an issue with the vehicle model creater themselves, and not us.
