### ISSUE TITLE
2020 mercedes benz EQC400 suv

### ISSUE THREAD

**Issue by Silxy** [fkk-cz/noire_vehicles#830]
so i finally saved up for a new car. couldn't do mining before as the mustang mach e had no trunk. finally get a new car spent 80k and this car also has no trunk. so i have 2 cars now without trunks... i am not having a good experience being supporter for my first time. please fix! appreciate it.

**Comment by No-Yes1** [comment]
Closing out both of these issues - The model itself does not have a trunk, so you can not access it. This is an issue with the vehicle model creater themselves, and not us.
