### ISSUE TITLE
KTM Super Duke (Sound Upgrade)

### ISSUE THREAD

**Issue by gxdsent** [fkk-cz/noire_vehicles#832]
Came across a new sound mod that matches the bike. Was wondering if this could be implemented at some point :)

https://www.gta5-mods.com/vehicles/ktm-1290-super-duke-r-engine-sound-oiv-addon-fivem

**Comment by No-Yes1** [comment]
Fixed in https://github.com/fkk-cz/noire_vehicles/commit/9b33dadba9c9a015ace7e176c14c52afc802fbaa.
