### ISSUE TITLE
Small Trailer compatibility

### ISSUE THREAD

**Issue by Chitowndevil21** [fkk-cz/noire_vehicles#835]
Is there anyway to get an actual list of trucks that can pull the small trailer?  The list that is pinned on Discord is inaccurate. I have tried the Nissan Titan & the 2000 Ford F350 Super Duty & neither are able to connect to the small trailer. So far I have only gotten the Raptor, the H1 & the Colorado to work.

**Comment by No-Yes1** [comment]
List has been updated in discord; https://discord.com/channels/777682935687413790/822282806959931422/933045124437516339
