### ISSUE TITLE
Vehicle Durability & Fuel Consumption

### ISSUE THREAD

**Issue by MrKennyG** [fkk-cz/noire_vehicles#836]
Broken record Kenny G here. 

I know we have had a few buffs to the vehicles durability and of course i appreciate that but... we have some ways to go.

The police cars are just so much stronger than player vehicles. I know the argument is "police vehicles are made to be stronger" but in the city it's kind of ridiculous. We have on average 4-5 cop cars chasing a single vehicle after a robbery or in a 10-80 and the player vehicles break down so much faster than police vehicles. 

Strengthening player vehicles would allow things like pitting and the overall chase to be much better for both ends. It also doesn't help that there are the street lights / traffic lights / and fire hydrants that are immortal that are put on every corner of the city instantly breaking anything that touches them. We also have 30 trashmasters driving around the city at all times plowing into anything that moves. We had a robbery last night and the driver got hit by 3 trashmasters trying to evade the police.

I would also poll to have some Gas changes. I know every class of vehicle besides SUPER cars were given better gas efficiency but i still think the vehicles eat gas way too fast.  There have been a lot of Car races in the city recently and after almost every race people are at the pumps filling the vehicle again and replenishing their repair kits. 

Hope this sheds a bit of light of the normal day to day. Overall im asking, and im sure many others are, to buff the vehicles substantially and maybe have them eat less gas to make things more entertaining and less repetitive.

Thanks,
-KennyG

**Comment by No-Yes1** [comment]
> Hope this sheds a bit of light of the normal day to day. Overall im asking, and im sure many others are, to buff the vehicles substantially and maybe have them eat less gas to make things more entertaining and less repetitive.

The issue is, is your have some people driving so recklessly and unrealistically (esp. in high value/super cars), which is the reason why the vehicle health/durability was decreased, most civilian vehicles have the exact same durability (exp. super/high values vehicles). 

> The police cars are just so much stronger than player vehicles. I know the argument is "police vehicles are made to be stronger" but in the city it's kind of ridiculous. We have on average 4-5 cop cars chasing a single vehicle after a robbery or in a 10-80 and the player vehicles break down so much faster than police vehicles.

Not sure what you're attempting to imply with this statement? Are you saying you want LEO vehicles to have a slight nerf in armour/durability? 

> . We also have 30 trashmasters driving around the city at all times plowing into anything that moves. We had a robbery last night and the driver got hit by 3 trashmasters trying to evade the police

Might have to bring in the r* meta files for the trashmasters and nerf the durability on these, because I agree, people in larger vehicles (Trucks, trashmasters etc) do not know how to drive and just smash into anything because the armour is higher then your average civilian vehicle....

> I would also poll to have some Gas changes. I know every class of vehicle besides SUPER cars were given better gas efficiency but i still think the vehicles eat gas way too fast. There have been a lot of Car races in the city recently and after almost every race people are at the pumps filling the vehicle again and replenishing their repair kits.

Let me get back to you on the % rate of these. Imo super cars shouldn't have the best fuel efficiently. I mean you wouldn't drive a supercar 24/7 and irl the fuel efficiently is dogshit lol. 

More then happy to take a look at the durability further, but supercars/high value cars shouldn't have the best durability, especially when a select few people want to just use them for chase after chase/ do unrealistic things with them because they are fast...

**Comment by MrKennyG** [comment]
The issue is, is your have some people driving so recklessly and unrealistically (esp. in high value/super cars), which is the reason why the vehicle health/durability was decreased, most civilian vehicles have the exact same durability (exp. super/high values vehicles).

This I understand im actually ok with the supercars having lower durability / gas. It is insanely easy to get a supercar in the city and i know from trying to track down some of these vehicles on duty that they are ridiculous and if given a good driver damn near impossible to stop. So that makes sense. Supercars are just kinda a class in their own of broken.


"The police cars are just so much stronger than player vehicles. I know the argument is "police vehicles are made to be stronger" but in the city it's kind of ridiculous. We have on average 4-5 cop cars chasing a single vehicle after a robbery or in a 10-80 and the player vehicles break down so much faster than police vehicles."

Not sure what you're attempting to imply with this statement? Are you saying you want LEO vehicles to have a slight nerf in armour/durability?

Negative. I think the police cars are were every non supercar armor / durability should be. LEO cars can take quite a few hits / rolls and still move without the engine smoking but if you hit enough things it starts to break down. I would like to see player vehicles around the same durability as police cruisers, or close to it.



I would also poll to have some Gas changes. I know every class of vehicle besides SUPER cars were given better gas efficiency but i still think the vehicles eat gas way too fast. There have been a lot of Car races in the city recently and after almost every race people are at the pumps filling the vehicle again and replenishing their repair kits.

Let me get back to you on the % rate of these. Imo super cars shouldn't have the best fuel efficiently. I mean you wouldn't drive a supercar 24/7 and irl the fuel efficiently is dogshit lol.

This is true. The only reason i mentioned this was because even the non supercars gas goes quite fast still. I agree with everything you said about supercars in the city because i understand how insane they can be and it makes sense.



More then happy to take a look at the durability further, but supercars/high value cars shouldn't have the best durability, especially when a select few people want to just use them for chase after chase/ do unrealistic things with them because they are fast...

Agreed.


Thanks,
-KennyG

**Comment by fkk-cz** [comment]
> It also doesn't help that there are the street lights / traffic lights / and fire hydrants that are immortal that are put on every corner of the city instantly breaking anything that touches them.

Traffic objects and props are frozen for sync issues. In the past people constantly raised the issue of traffic lights falling in front of their vehicles while driving, resulting in them crashing or losing control at no fault of their own. With that said, I don't believe the costs outweigh the benefits of having this system in place.

> We also have 30 trashmasters driving around the city at all times plowing into anything that moves. We had a robbery last night and the driver got hit by 3 trashmasters trying to evade the police.

This could be solved if we bring back the license suspension system, and prevent people with suspended licenses from doing trash or trucker. The durability for commercial and service vehicles is relatively higher to prevent people from abandoning their job vehicles all around the city, and it's also relatively frustrating when your vehicle breaks down while trying to work legals.

> Negative. I think the police cars are were every non supercar armor / durability should be. LEO cars can take quite a few hits / rolls and still move without the engine smoking but if you hit enough things it starts to break down. **I would like to see player vehicles around the same durability as police cruisers, or close to it.**

The reason police vehicles have increased durability is the police need to be able to drive around and patrol, regardless of any minor traffic accidents -- which happens a **lot** down in the city. We can't have situations where the police are constantly spending their time going back to the PD to repair their vehicle. If player vehicles have the same durability as the police vehicles, that will lead to very frustrating situations where civilians continue driving despite their vehicle being damaged/disabled beyond repair.

On one hand, if you want **all** civilian vehicles (with the exception of supercars) to be more durable, this will result in a lot of frustration and generally unrealistic/GTA online style driving from civilians. Even if we bring back the license suspension system, which is definitely needed, that won't help with people who drive at 100+ MPH in downtown areas.

> I would also poll to have some Gas changes. I know every class of vehicle besides SUPER cars were given better gas efficiency but i still think the vehicles eat gas way too fast. There have been a lot of Car races in the city recently and after almost every race people are at the pumps filling the vehicle again and replenishing their repair kits.

I agree with you on the gas consumption, a good example is the `AUTARCH` vanilla supercar, which consumes a lot of fuel even when sitting idle. This has been tweaked in https://github.com/fkk-cz/noire/commit/cf9f239ed17cd628aab2cff4383656956c5a230f, here are the new class multipliers:

> Classes = {
	[0] = 0.6, -- Compacts
	[1] = 0.8, -- Sedans
	[2] = 1.0, -- SUVs
	[3] = 0.6, -- Coupes
	[4] = 0.9, -- Muscle
	[5] = 0.9, -- Sports Classics
	[6] = 0.9, -- Sports
	[7] = 0.9, -- Super
	[8] = 1.0, -- Motorcycles
	[9] = 0.9, -- Off-road
	[10] = 1.0, -- Industrial
	[11] = 1.0, -- Utility
	[12] = 1.0, -- Vans
	[13] = 0.0, -- Cycles
	[14] = 1.0, -- Boats
	[15] = 1.0, -- Helicopters
	[16] = 1.0, -- Planes
	[17] = 0.5, -- Service
	[18] = 0.5, -- Emergency
	[19] = 1.0, -- Military
	[20] = 0.8, -- Commercial
	[21] = 1.0 -- Trains
}

where 1.0 is default (no change). Vehicles also consume more fuel at higher engine speeds, supercars naturally tend to drive at higher RPMs which is one reason why they burn more fuel.

**Comment by MrKennyG** [comment]
Can say after a couple days of testing the fuel seems a lot better and the vehicles are a lot more fun to drive and last a lot longer after hitting a few signs and possible pole. Love the changes and think it will make the city happy leading to more fun police chases and overall fun.
