### ISSUE TITLE
McLaren 765LT

### ISSUE THREAD

**Issue by byu26** [fkk-cz/noire_vehicles#839]
Is there any possible way to get engine and transmission upgrades on the 765LT? Tanksssss
![8363349-middle](https://user-images.githubusercontent.com/35611871/149872891-8d0d8e40-ceb6-4739-884a-49c69bdf2bf2.png)

**Comment by No-Yes1** [comment]
https://github.com/fkk-cz/noire_vehicles/issues/793 - See attached closed issue. I've already attempted to change the modkit value but sadly the engine/trans upgrades do not work. I'll need to dig a little deeper into the issue but overall, I think this is a model issue and something we can not fix. ):
