### ISSUE TITLE
2015 bmw i8

### ISSUE THREAD

**Issue by butternut97** [fkk-cz/noire_vehicles#84]
its very slow compared to the other bmw in around the same price and it only has a turbo upgrade

**Comment by butternut97** [comment]
there are also no rim options but idk if those can be added

**Comment by DankGrandma** [comment]
could prob cut the fInitialDragCoeff value in half to like 4.5 or 5

carcols.meta appears to have all the upgrades but idk. something may be off

**Comment by fkk-cz** [comment]
https://github.com/fkk-cz/noire_vehicles/commit/7fd4684c427453906f25ff97141f7c0520e9de3f#diff-54de87bb0e06c4628da7e612d0069e50717a3fc5e65f6c7838b281ce3d223e04
