### ISSUE TITLE
SAHP Charger

### ISSUE THREAD

**Issue by Leetsauce** [fkk-cz/noire_vehicles#841]
Was wondering if you could take a look at the sahp chargers and see if you can fix the issue of the rear end being so heavy.  Any little bump you hit will send the nose of your vehicle right up in the air and the back and just drops instantly.  Not sure if there is anything you can do about it but it would be a nice fix to not flip over when you hit a little bump. Maybe also check the handling. seems like it was messed with and a lot more touchy and slides around a lot more.

**Comment by No-Yes1** [comment]
Fixed in https://github.com/fkk-cz/noire_vehicles/commit/653cdd9cc139ba92d9f82127a39a1895204663f7
