### ISSUE TITLE
New 1996 R33 Skyline

### ISSUE THREAD

**Issue by gxdsent** [fkk-cz/noire_vehicles#842]
Just a heads up on this one, the headlights seem to be facing the opposite direction. Not sure if this could be fixed through modkits or anything like that. (See Attached Picture) 

--> https://i.imgur.com/OXEGfIm.png

**Comment by No-Yes1** [comment]
I've attempted to look at this one a bit further, tried to fix it, but sadly there has been no hope. I'm guessing the vehicle creator was high and faced it the wrong way... :(
