### ISSUE TITLE
2 issues with the 2015 Dodge ram 2500

### ISSUE THREAD

**Issue by Marco1738** [fkk-cz/noire_vehicles#844]
Okay so i ordered the new 2015 dodge ram 2500 into the server and there are two problems with it. 1) for some reason it seems to run out of gas way quicker then it should like it starts slowing down at around 25-30 gas instead of the usual 10 gas which makes it a lot harder to get around so if you could fix that it would be great. 2) the trunk space is only 750 which is a bummer because i ordered it to be my new mining truck and it can’t do as well with only 750 trunk space so if you could make 1000 that would be awesome

**Comment by Marco1738** [comment]
also it is listed as NULL and i would like if it was the vehicles actual name

**Comment by No-Yes1** [comment]
Fixed in https://github.com/fkk-cz/noire_vehicles/commit/e40c592ef718dd40a298b3d1ff1a893e635034d2. Changed the Vehicle Class to Off_Road. Should be 1k trunk space and allow more gas efficiently. Please wait a few days for this change to merge.
