### ISSUE TITLE
2015 Dodge 2500

### ISSUE THREAD

**Issue by StettyBoostin** [fkk-cz/noire_vehicles#846]
The truck only has 750 storage shouldn’t it be a 1000 even the Colorado and 4 runner have a 1000 storage

**Comment by Marco1738** [comment]
i already opened an issue for this reason and they fixed it, they just said to wait a few days for it to go through

**Comment by No-Yes1** [comment]
Already Fixed in https://github.com/fkk-cz/noire_vehicles/commit/e40c592ef718dd40a298b3d1ff1a893e635034d2.
