### ISSUE TITLE
Honda 2021 problem

### ISSUE THREAD

**Issue by Jeiku94** [fkk-cz/noire_vehicles#848]
both back seat doors are not working. No one can use the back seat doors for some reason even though last week it was working. any reason why this is? or is there a fix to the issue?

**Comment by No-Yes1** [comment]
Apologies, I am in the making of trying to see if this can be fixed. The issue is, is that it's a RHD vehicle, meaning it's possibly more difficult to attempt to fix and require testing prior to committing the change. I'm unsure how it stopped working

**Comment by No-Yes1** [comment]
I've tried to take a further look into this, unsure why it stopped working. This is also a recalled vehicle, so there's no need to fix it. My apologies
