### ISSUE TITLE
Pagani Huayra Roadster

### ISSUE THREAD

**Issue by BlizzWizz** [fkk-cz/noire_vehicles#85]
It dosn't come over 4 gear so the last gears just are there ut it dont change to them so its much slower then it could be.

**Comment by DankGrandma** [comment]
making the fClutchChangeRateScaleUpShift value
and the     fClutchChangeRateScaleDownShift value the same value might fix this

**Comment by fkk-cz** [comment]
> 
> 
> making the fClutchChangeRateScaleUpShift value
> and the fClutchChangeRateScaleDownShift value the same value might fix this

https://github.com/fkk-cz/noire_vehicles/commit/7fd4684c427453906f25ff97141f7c0520e9de3f#diff-37e73e440a73564eefb8842d8068699511771847c78845b3c4660aab6511113f
