### ISSUE TITLE
2010 Dodge 3500 Flatbed

### ISSUE THREAD

**Issue by gxdsent** [fkk-cz/noire_vehicles#851]
The truck tends to flip pretty easily, almost like how the durango used to when you’re turning with no brakes. Just a quick minor tweak to that to stop it from flipping would be 👌🏽.

**Comment by No-Yes1** [comment]
Fixed in https://github.com/fkk-cz/noire_vehicles/commit/05c935e318329f74722eae689e26058fd4376d7b. Please wait a few days for it to merge & go live.
