### ISSUE TITLE
Lamborghini Huracan Spyder (Not Evo)

### ISSUE THREAD

**Issue by apricates** [fkk-cz/noire_vehicles#856]
I was just wondering if you guys could change the audio file as its pretty quiet to this one **https://www.gta5-mods.com/vehicles/lamborghini-huracan-audi-r8-5-2-v10-engine-sound-oiv-add-on-fivem-sound** as long its acceptable.  Maybe also bump up the top speed as its a bit slow for its price.

**Comment by No-Yes1** [comment]
This already has a custom audio hash, the same one used on the 'hevo';

https://github.com/fkk-cz/noire_vehicles/blob/5207fde6139749ee314d4883c9ad47f90ad54d12/DATA/lp610_data/vehicles.meta#L18

https://github.com/fkk-cz/noire_vehicles/blob/5207fde6139749ee314d4883c9ad47f90ad54d12/DATA/hevo_data/vehicles.meta#L18

Unsure as to why it's more quiet on this then the other models?

**Comment by apricates** [comment]
just went to pdm and checked both and they have different engine sounds.

**Comment by No-Yes1** [comment]
They are the exact same audio hash, so unsure why they sound different? I'll have to do some investigating on this

**Comment by No-Yes1** [comment]
I have tested this further and saw there was 2 files called ``lp610``. I have changed the one that has a vanilla license plate to the custom audio sound used in the normal hevo. https://github.com/fkk-cz/noire_vehicles/commit/68bd74b967a10559f451a2ee9818a506b7e54921. Please wait a few days for this to merge live.
