### ISSUE TITLE
2010 Bmw M5 F10

### ISSUE THREAD

**Issue by EncrustMust** [fkk-cz/noire_vehicles#858]
Livery gets stuck on and can’t take off 
There’s a “NULL” option which is the livery, and a  default option which is has no livery, and as soon as you select it even if you didn’t buy it as soon as you go back to do something else ( other modifications) or exit the modify menu it gets put right back on *Car didn’t come with livery so it wasn’t mandatory it just randomly applied*

**Comment by No-Yes1** [comment]
https://github.com/fkk-cz/noire_vehicles/commit/413b9155ea81ea02f651c6b3d211e60b6bf64d25 - I should have fixed this hopefully, I removed the livery and the vehicle flag that states it has a livery. Please wait for a few days for this to merge onto live.
