### ISSUE TITLE
Bently EXP 10 Speed 6 Interior Color

### ISSUE THREAD

**Issue by Chitowndevil21** [fkk-cz/noire_vehicles#859]
Hey just wondering if there was a way to add changing the interior color on this car. Also there are no performance upgrade for this car outside of a turbo, can those be added as well??

**Comment by No-Yes1** [comment]
> Hey just wondering if there was a way to add changing the interior color on this car.

There isn't, as it's a model issue.

> ls there are no performance upgrade for this car outside of a turbo, can those be added as well??

I'll take a look at this over the weekend

**Comment by No-Yes1** [comment]
Fixed in https://github.com/fkk-cz/noire_vehicles/commit/74c5a90bba3f170aaf614f9fb24111cf72b70d5f. Please wait for a few days for this to be merged.
