### ISSUE TITLE
Jaguar XKRS-GT needs a acceleration buff 

### ISSUE THREAD

**Issue by recruit2212** [fkk-cz/noire_vehicles#861]
The car in general is lacking badly in acceleration and even the top end speed. The real life one can do at least 180mph no tuning which is fair as the car is a sub 600hp v8. 
Even with dsc off its sluggish in its higher end speed.

**Comment by No-Yes1** [comment]
fixed in https://github.com/fkk-cz/noire_vehicles/commit/1a8aff3422ad4c3e1c30fcc66686b9b6c8506e4f. Please wait for a few days until it has been merge onto the server.
