### ISSUE TITLE
Buff vehicle Armour, and If possible, get new fast nice cars that is affordable 

### ISSUE THREAD

**Issue by Jakebeastt** [fkk-cz/noire_vehicles#864]
Hitting one pole can make your car smoke sometimes. and it's such a hassle to go get a repair kit. just having car that I can crash a few times would be a lot better. Also, if it's hard to get NEW cars into the city/game don't worry about it. thank you

**Comment by No-Yes1** [comment]
I'm not sure what you're trying to state here? Just drive better? We fixed the issue with armours recently and it seems to be fine? Also, the point of having an economy server is to earn money to get "fast nice cars". Not going to just give them out to be ""affordable"".
