### ISSUE TITLE
x5 BMW

### ISSUE THREAD

**Issue by gxdsent** [fkk-cz/noire_vehicles#865]
The braking on the car is god awful lol It feels like you’re on ice when you try to stop, it doesn’t even need a lot of help because it’s not a super expensive car or anything, but it could use a little nudge in the right direction, maybe just one or two from the 6 it’s at now. I can bear with the squirmy handling but the brakes are rough. 🙂

**Comment by No-Yes1** [comment]
Fixed in https://github.com/fkk-cz/noire_vehicles/pull/868/commits/cf91867db3560c55804ea0a6e16609b5a01dd507. Please wait for a few days for this to merge live.
