### ISSUE TITLE
Audio Tweak for 2016 Challenger SRT

### ISSUE THREAD

**Issue by octanered392** [fkk-cz/noire_vehicles#869]
Suggested new audio modifications for 2016 Dodge Challenger SRT. 

https://www.gta5-mods.com/vehicles/dodge-challenger-hemi-6-4l-v8-sound-mod-sp-add-on-fivem

**Comment by No-Yes1** [comment]
I'm pretty sure we already have this, it's on the demon / trackhawk currently.

**Comment by No-Yes1** [comment]
nevermind

**Comment by No-Yes1** [comment]
Done in https://github.com/fkk-cz/noire_vehicles/commit/4ee79676b3e06349644cf53790044aa6ca6e3fe3. Please wait for a few days for this to merge live.
