### ISSUE TITLE
McLaren 765LT not having upgraded

### ISSUE THREAD

**Issue by ChitoHbk** [fkk-cz/noire_vehicles#870]
So I recently bought this car and after driving it I realized it doesn't have upgrades and think it should as it was out acceration by a Mercedes hatch back

**Comment by No-Yes1** [comment]
Does it have any upgrades? or just not engine/transmission?

**Comment by No-Yes1** [comment]
https://github.com/fkk-cz/noire_vehicles/commit/2a4a577c01fa93c78ca7b718844b92c87010942c - Buffed the acceleration slightly

**Comment by No-Yes1** [comment]
Upon further review, it would seem like it might be a broken carcols.meta file? The rest of the upgrades (exp. Engine & Transmission)

**Comment by No-Yes1** [comment]
https://github.com/fkk-cz/noire_vehicles/blob/master/DATA/765lt_data/carcols.meta

**Comment by No-Yes1** [comment]
https://github.com/fkk-cz/noire_vehicles/blob/18cca86e1540d6132e8749716f1ee0db10370070/DATA/765lt_data/carcols.meta#L200-L232
