### ISSUE TITLE
mclaren senna

### ISSUE THREAD

**Issue by highfkyo** [fkk-cz/noire_vehicles#871]
after the buff of the mclaren senna the handling on it is trash it wont turn like it use to if thats how the car is going to stay id like to know

**Comment by No-Yes1** [comment]
Not sure what you mean, just tested it out and the handling is not "trash" - if fact it's too OP still, no way could a supercar still be able to perform turns like that at the speed I was going.https://streamable.com/hfw8ds. If you're unhappy, sell it back to PDM.
