### ISSUE TITLE
1997 Dodge Viper GTS Speed & Acceleration

### ISSUE THREAD

**Issue by Chitowndevil21** [fkk-cz/noire_vehicles#874]
Great looking car but I think the speed & acceleration are very underwhelming especially being it is a GTS variant. Is there any way this car can be buffed??

**Comment by No-Yes1** [comment]
Fixed in https://github.com/fkk-cz/noire_vehicles/commit/916d6c27567297eed2e77f8ba665e45db62e1c6c. Please wait for a few days for this to merge live.
