### ISSUE TITLE
2014 BMW M4 F82 not spawning in

### ISSUE THREAD

**Issue by Yush6969** [fkk-cz/noire_vehicles#876]
Hello there, As of recently i have purchased myself a nice BMW to drive around within the city. When i bought it, it had no issues and was all fine. But as of yesterday and today whenever i try to spawn it from the garage it doesn't work. the car just disappears and even if i get it back from insurance it continues to keep on disappearing. Here is a clip below of the current issue. Also went to PDM and the vehicle fails to spawn for me.

Much thanks,
Yush

https://medal.tv/games/gta-v/clips/aor99ev1ui98f/d1337Ie4cO9A?invite=cr-MSwwUzgsMTU0OTA0MzYs

**Comment by No-Yes1** [comment]
Sounds like a you problem mate

**Comment by No-Yes1** [comment]
Vehicle was on the recalled list / removed.
