### ISSUE TITLE
Minor car fixes

### ISSUE THREAD

**Issue by NikeXpert** [fkk-cz/noire_vehicles#877]
Is there anyway we could get the 2010 Ram 3500 dually (non-supporter) storage  bumped up to 1000, instead of 750.

Bmw e46 m3 drift new LS motor sound plz..

**Comment by No-Yes1** [comment]
> Bmw e46 m3 drift new LS motor sound plz..

Find a sound then

**Comment by No-Yes1** [comment]
> Is there anyway we could get the 2010 Ram 3500 dually (non-supporter) storage bumped up to 1000, instead of 750.

Do you mean this car? 
![image](https://user-images.githubusercontent.com/79383480/153249394-4f9789fd-4c82-422d-b6e9-5cae168be1e2.png)

**Comment by NikeXpert** [comment]
Yes that truck

**Comment by NikeXpert** [comment]
> > Bmw e46 m3 drift new LS motor sound plz..
> 
> 
> 
> Find a sound then

https://www.gta5-mods.com/vehicles/camaro-ss-ls3-v8-sound-mod-sp-add-on-fivem

**Comment by No-Yes1** [comment]
> Yes that truck

It already have 1K trunk space, the vehicle class is OFF_ROAD?

**Comment by NikeXpert** [comment]
> > > > Bmw e46 m3 drift new LS motor sound plz..
> 
> > > 
> 
> > > 
> 
> > > Find a sound then
> 
> > 
> 
> > https://www.gta5-mods.com/vehicles/camaro-ss-ls3-v8-sound-mod-sp-add-on-fivem
> 
> 
> 
> That's for a camaro, can you find one that's for the BMW?

The bmw is LS3 swapped

**Comment by NikeXpert** [comment]
Can you also update the sound of the 2017 Ram TRX to the same as the trackHawk. Since they have the same motor. And it's class changed to off-road for 1k storage

**Comment by No-Yes1** [comment]
> And it's class changed to off-road for 1k storage

The TRX is already 1K trunk space too. Check before requesting. All ``Off-road`` vehicles are 1k trunk space:

https://github.com/fkk-cz/noire_vehicles/blob/8a14203ff8aee5ed4f8a8587d7ea9b5671200f2d/DATA/trx_data/vehicles.meta#L98

**Comment by No-Yes1** [comment]
> > > > > Bmw e46 m3 drift new LS motor sound plz..
> > 
> > 
> > > >
> > 
> > 
> > > >
> > 
> > 
> > > > Find a sound then
> > 
> > 
> > > 
> > 
> > 
> > > https://www.gta5-mods.com/vehicles/camaro-ss-ls3-v8-sound-mod-sp-add-on-fivem
> > 
> > 
> > That's for a camaro, can you find one that's for the BMW?
> 
> The bmw is LS3 swapped

https://github.com/fkk-cz/noire_vehicles/commit/9bb6656c5836b92344571a16dbdc09a9b5918ebd - done

**Comment by No-Yes1** [comment]
> Can you also update the sound of the 2017 Ram TRX to the same as the trackHawk. Since they have the same motor. And it's class changed to off-road for 1k storage

https://github.com/fkk-cz/noire_vehicles/commit/213aef7909686fe990fea7ff40daa669b2ac65d1 - done.
