### ISSUE TITLE
2020 Ferrari SF90 Stradale

### ISSUE THREAD

**Issue by Zoraketh** [fkk-cz/noire_vehicles#878]
The car has been fine driving wise and all that. Flew in today (2/9/2022) and its plagued with a lot of missing textures and buggy textures. I don't know if something got changed or tweaked, but it was fine the other day (yesterday or the day before). The diffuser used to be carbon fiber as well as the side skirt and splitter. Now its just a flat chrome texture as well as the rear trunk above the engine has some see through textures.
![image](https://user-images.githubusercontent.com/92574732/153310927-f52fb939-7848-4007-96ca-5061c28bb0f1.png)
sorry for the low res screen grab had to snag it from a vid
![image](https://user-images.githubusercontent.com/92574732/153311001-b27f1d78-fc8f-410a-827c-0198dfea042a.png)
![image](https://user-images.githubusercontent.com/92574732/153311218-2ca1d538-a5a3-405b-9d7f-5ae57f99c64b.png)

**Comment by Zoraketh** [comment]
![image](https://user-images.githubusercontent.com/92574732/153311951-778fb08d-77f7-4fc9-b0d5-5f4f60c0665d.png)
![image](https://user-images.githubusercontent.com/92574732/153312019-02138bb5-a208-4dfb-877a-8734e7953b97.png)

**Comment by No-Yes1** [comment]
Upon further investigation, this is due to us downsizing certain assets for the server when we started recalling vehicles, sadly there isn't a fix for this. I would suggest selling it back to PDM? Again, my apologies
