### ISSUE TITLE
2019 corvette zr1

### ISSUE THREAD

**Issue by butternut97** [fkk-cz/noire_vehicles#879]
![image](https://user-images.githubusercontent.com/81532451/153325595-2610176f-4407-47f6-9148-fa6dbee5b5c1.png)
![image](https://user-images.githubusercontent.com/81532451/153325617-a542f384-d68c-43fe-8bb2-001662074f13.png)
the car has some really bad texture issues after yesterdays reset car was fine last night

**Comment by No-Yes1** [comment]
Seems like they are a few cars that now have this textural issue (see #878)

**Comment by No-Yes1** [comment]
Upon further investigation, this is due to us downsizing certain assets for the server when we started recalling vehicles, sadly there isn't a fix for this. I would suggest selling it back to PDM? Again, my apologies
