### ISSUE TITLE
NEO EP9 Upgrade & hitbox issue

### ISSUE THREAD

**Issue by SilentRoses** [fkk-cz/noire_vehicles#881]
HelloLua!

Please could the NeoEP9 be looked at for the following issues,

The Turbo upgrade slows the car down,
The suspension appears to be too low meaning the car scrapes & hits objects not in range quite easily
Transmission, this upgrade also appears to slow the vehicle down
Not 100% sure if engine upgrades do anything for performance?
Armour appears to be fine but not 100% sure. The car is pretty strong default anyway so no worries here regardless
Brakes upgrade does not really make any difference, this is fine as the car brakes pretty fine
The hitbox appears to be a lil off, i was driving normally through the city not close to anyone or hitting anyone however my vehicle still clipped a few people

Could turning be looked at though please as it turns like a boat in a storm lol almost like you lose traction when turning

I've also noticed the vehicle cause some pretty serious headaches in the city, poly count as ive heard is low but i have noticed some body panels glitching into one another like the wing & doors, they are usually violently launched off the vehicle when this glitch occurs. its quite funny to watch.

Not sure if you can do this since it may be an asset thing but can the ability to add a licence plate be added? I have been pulled over a few times for not having a licence plate lol.

And finally a suggestion, with the 3rd eye menu or the pg up menu having the ability to raise dynamic wings for looks. Some cars like the EP9 have a nice looking wing and its a shame we cant share that with others without driving it.

Thank you!

**Comment by No-Yes1** [comment]
Hello, I've fixed the lower limit suspension rate, which should solve the clipping issue, _hopefully_: https://github.com/fkk-cz/noire_vehicles/commit/3bb9918080030d7c908b367f5a305ea9479035e3. In regards to upgradability, it doesn't make sense for an electric vehicle to have turbo/transmission upgrades so I'm guessing that's why they "slow the vehicle down". Again, not sure how that's possible since that have a % of increase. 

> Not sure if you can do this since it may be an asset thing but can the ability to add a licence plate be added? I have been pulled over a few times for not having a licence plate lol.

This is a model/creator issue and can't be fixed.

> And finally a suggestion, with the 3rd eye menu or the pg up menu having the ability to raise dynamic wings for looks. Some cars like the EP9 have a nice looking wing and its a shame we cant share that with others without driving it.

Is there already a wing on this vehicle?

**Comment by SilentRoses** [comment]
Hiya yes the vehicle has a Dynamic wing which can be raised by hitting 60MPH and lowered when hitting the brakes or going below 60MPH. For car meets and shows etc any car with a dynamic wing IE ford GT or NIO EP9 for example maybe have the ability to raise the wing in the left alt menu. Same as when you go to open doors or boot etc.  

Also "Again, not sure how that's possible since that have a % of increase." fetault the car actually goes faster than when you add upgrades. which is ironic lol. Test them in Fort Zancudo one fully upgraded and one not. One test with DSC and one without. You should see what us owners see.

**Comment by No-Yes1** [comment]
> Also "Again, not sure how that's possible since that have a % of increase." fetault the car actually goes faster than when you add upgrades. which is ironic lol. Test them in Fort Zancudo one fully upgraded and one not. One test with DSC and one without. You should see what us owners see.

I'm pretty sure you can revert upgrades? I know some you can / some you can't.

**Comment by SilentRoses** [comment]
At the moment i've been unable to revert any upgrades at all, they take the money to remove the upgrade however when you go back ti the option it defaults to the previous state

**Comment by h0dger** [comment]
also honestly the acceleration for its price is a little lacking,  i know all EV took a hit on acceleration recently but for 335k this car seems to get to 190ish pretty slow for a "super car". my old model s seemed to accelerate faster than this. just a thought

**Comment by No-Yes1** [comment]
> also honestly the acceleration for its price is a little lacking, i know all EV took a hit on acceleration recently but for 335k this car seems to get to 190ish pretty slow for a "super car". my old model s seemed to accelerate faster than this. just a thought

Fixed in https://github.com/fkk-cz/noire_vehicles/commit/33da6aeb484549662dfd86bcea3340360b212365. Please wait for a few days for it to merge live.
