### ISSUE TITLE
Mclaren 720 spider

### ISSUE THREAD

**Issue by Zoraketh** [fkk-cz/noire_vehicles#883]
Interior texture has gone chrome.
I believe there are a number of cars that this has happened to as well as the EMS Suv, I do not know that name.
![image](https://user-images.githubusercontent.com/92574732/153723930-a9154c20-c7d3-414f-95e1-bbba623cdb6a.png)

**Comment by No-Yes1** [comment]
Upon further investigation, this is due to us downsizing certain assets for the server when we started recalling vehicles, sadly there isn't a fix for this. I would suggest selling it back to PDM? Again, my apologies
