### ISSUE TITLE
Tesla Roadster (Doesn't Work) 

### ISSUE THREAD

**Issue by MrGoony** [fkk-cz/noire_vehicles#885]
Car doesn't work after using a repair kit. Just bought the car, if it can't be fixed could I get a full refund for the car please. I was completely fine with having the car without it having a trunk, but the car being bricked because I used a repair kit is kind of a bummer.

**Comment by MrGoony** [comment]
Works after putting gas into it, but that kinda defeats the purpose of an electric car. Sometimes it will go back to working without fueling it if you get into another car and then back into it.

**Comment by No-Yes1** [comment]
This is an issue on all electric vehicles. Transferred to the public repo

**Comment by No-Yes1** [comment]
https://github.com/fkk-cz/noire-public/issues/449 - use this existing issue
