### ISSUE TITLE
2020 Rolls-Royce Cullinan (Extremely limited upgrades)

### ISSUE THREAD

**Issue by ChirpyMedusa** [fkk-cz/noire_vehicles#886]
The 2020 Rolls-Royce Cullinan has no performance upgrades (aside from the turbo), no wheel changes, no window tint, and other cosmetic upgrades that are completely unavilable. Not to mention, when actually purchasing the window tint you get the message "this mod has been purchased," with no changes to the vehicle.

**Comment by ChirpyMedusa** [comment]
Now that I have had it for some time, I have also noticed it gets extremely dirty within minutes of washing it (even when driving on city streets for a short period of time).

**Comment by Ell34** [comment]
Also an issue with the Black Badge version. I can also agree that it does get dirty quickly too.

**Comment by No-Yes1** [comment]
> The 2020 Rolls-Royce Cullinan has no performance upgrades (aside from the turbo), no wheel changes, no window tint, and other cosmetic upgrades that are completely unavilable. Not to mention, when actually purchasing the window tint you get the message "this mod has been purchased," with no changes to the vehicle.

Unsure what the issue really is for this. they both have carcols files and they aren't duplicated.


As for both the dirt issue, I have fixed it for both (https://github.com/fkk-cz/noire_vehicles/commit/8ee9c71bbd5c53781517a1ef63f6e3930fae2b6b / https://github.com/fkk-cz/noire_vehicles/commit/78bed9bbef522b71911d85e3cc42922fe5b727da.

I have also tweaked the tint values to be light smoke when you spawn it in (https://github.com/fkk-cz/noire_vehicles/commit/a246bb690c3304d8dcc9368e66565943d07bb8ae.)
