### ISSUE TITLE
Vehicle Texture Issues

### ISSUE THREAD

**Issue by fkk-cz** [fkk-cz/noire_vehicles#888]
The recent focus on solving the client performance issues has resulted in a few vehicles with broken textures.

Please post any vehicles with texture problems here, ideally with the **exact** make/model name as displayed in the bottom right corner.

**Comment by Cortez312** [comment]
The crown vic

**Comment by Ell34** [comment]
2022 GasGas EC350F , 2021 Porsche 911 Tubro S , 2021 BMW X7 , 2021 Bentley Mulliner Bacalar , 2020 Porsche 911 Speedster , 2019 Ford Ranger Raptor , 2019 Chevrolet Corvette ZR1 , 2017 Italdesign Zerouno , 2016 Jaguar I-Pace , 2013 Audi TT RS , 2009 Cadillac CTS-V (interior looks abit scuffed) , 2008 Chrysler 300c SRT8 , 2005 Ford Mustang GT , 1997 Lexus SC300 , 1995 Ferarri F50 , 1979 Chevrolet Camaro Z28 , 1972 Plymouth Barracuda , 1971 Datsun 510 SR20 , 1970 Chevrolet Monte Carlo , 1969 Chevrolet Camaro SS , Tesla Cybertruck , Porsche 911 GT3 997 , Nissan Silvia , Mercedes-Benz AMG Project One , Mclaren 720s Spider , Lamborghini Cenetenario LP 774-4 , Go-kart , Chevrolet Corvette C8 MANSAUG , Aston Martin DB11 Cyrus , Kia Optima

**Comment by somedudenamedrush** [comment]
Bugatti bolide

**Comment by Stagonium** [comment]
The rims on the LSPD Camaro have messed up textures, as seen [here](https://i.imgur.com/Grt56tT.png)

**Comment by LactatingWalrus** [comment]
The tail lights on the 2019 Aston Martin Vantage have messed up textures now. [Here](https://imgur.com/Mf08s1V)'s a screenshot.

**Comment by fkk-cz** [comment]
> The crown vic



> 2022 GasGas EC350F , 2021 Porsche 911 Tubro S , 2021 BMW X7 , 2021 Bentley Mulliner Bacalar , 2020 Porsche 911 Speedster , 2019 Ford Ranger Raptor , 2019 Chevrolet Corvette ZR1 , 2017 Italdesign Zerouno , 2016 Jaguar I-Pace , 2013 Audi TT RS , 2009 Cadillac CTS-V (interior looks abit scuffed) , 2008 Chrysler 300c SRT8 , 2005 Ford Mustang GT , 1997 Lexus SC300 , 1995 Ferarri F50 , 1979 Chevrolet Camaro Z28 , 1972 Plymouth Barracuda , 1971 Datsun 510 SR20 , 1970 Chevrolet Monte Carlo , 1969 Chevrolet Camaro SS , Tesla Cybertruck , Porsche 911 GT3 997 , Nissan Silvia , Mercedes-Benz AMG Project One , Mclaren 720s Spider , Lamborghini Cenetenario LP 774-4 , Go-kart , Chevrolet Corvette C8 MANSAUG , Aston Martin DB11 Cyrus , Kia Optima



> Bugatti bolide



> The rims on the LSPD Camaro have messed up textures, as seen [here](https://i.imgur.com/Grt56tT.png)



> The tail lights on the 2019 Aston Martin Vantage have messed up textures now. [Here](https://imgur.com/Mf08s1V)'s a screenshot.

Fixed all of these vehicle textures.

**Comment by No-Yes1** [comment]
Audi RS5 Libertywalk

**Comment by No-Yes1** [comment]
![image](https://user-images.githubusercontent.com/79383480/154753849-93caff66-09d6-4ec6-8387-4857c62518da.png)


2019 Chevrolet Corvette ZR1 still looks scuffed

**Comment by fkk-cz** [comment]
Both fixed.

**Comment by NikeXpert** [comment]
Porsche GT3 RS (non-supporter)![image](https://user-images.githubusercontent.com/96304112/155061723-f9055b02-e124-4eac-933a-10b2e0f6e022.jpeg)

**Comment by MrUnlife** [comment]
The texture/paintjob on the 1998 Crown Vic is bugged and stuck at an ugly purple color

**Comment by ItsGabble** [comment]
2020 Ferrari Monza SP2 Tweaks: Emblems missing, headlights change color, tail/brake light is sometimes transparent and changes colors when driving, wheel textures are scuffed when driving and wheels shutter when parked

**Comment by Chitowndevil21** [comment]
1970 Dodge Charger has texture issues.  Seems to be mainly related to red textures.  See attached photos
![1970 Charger RT 1](https://user-images.githubusercontent.com/93257343/161390050-c8cebfaa-6222-40fd-87ec-49c0563ca5f7.jpg)
![1970 Charger RT 2](https://user-images.githubusercontent.com/93257343/161390052-51b86f77-bd0b-48a2-8832-a21fdf607c5a.jpg)
![1970 Charger RT 3](https://user-images.githubusercontent.com/93257343/161390054-8ccdf927-907a-4eae-8e46-b46b0159deeb.jpg)
![1970 Charger RT 4](https://user-images.githubusercontent.com/93257343/161390057-099ce1a0-d85c-4afe-b3e0-6d67c4cb0bf0.jpg)
![1970 Charger RT 5](https://user-images.githubusercontent.com/93257343/161390062-246483fe-2138-4e75-ad7a-06a9b0a7edce.jpg)
.

**Comment by fkk-cz** [comment]
Closing this as the majority of the downsized vehicles that previously had issues seem to be fixed. Any vehicles that still have texture problems can be a standalone issue.
