### ISSUE TITLE
Porsche tweaks 

### ISSUE THREAD

**Issue by NikeXpert** [fkk-cz/noire_vehicles#892]
The Porsche GT3 RS ( non-Supporter
![Screenshot_2022-02-15_153114](https://user-images.githubusercontent.com/96304112/154509088-9df38508-40ce-4de3-be39-4861b7c4e7b7.jpg)
) 
texture issues

Sound change to this plz : https://www.gta5-mods.com/vehicles/porsche-911-gt3-rs-engine-sound-oiv-add-on-fivem

And the New Porsche Turbo S could use some handling updates it has terrible body roll.

**Comment by No-Yes1** [comment]
> And the New Porsche Turbo S could use some handling updates it has terrible body roll.

Do you mean this car? 

![image](https://user-images.githubusercontent.com/79383480/154533872-bc77fe3b-96f9-4b83-beb6-05b89182e182.png)

**Comment by NikeXpert** [comment]
![turbos](https://user-images.githubusercontent.com/96304112/154534389-54784725-2ff5-4ff4-94dd-881320595c3d.jpg)
 this one 2021
