### ISSUE TITLE
2021 BMW M4 COMP. REAR SPOILER ISSUE

### ISSUE THREAD

**Issue by KyleScot** [fkk-cz/noire_vehicles#895]
Hey! I just bought the car today (Feb 18) and when I went to test drive it, it had a rear spoiler on it, let alone, I’ve seen other people around the city have it on as well. When I went to purchase the car there was no rear spoiler on it, so i went to the mod shop in hopes of being able to install one on it. Scrolling through the customization categories there was no option that enabled me to apply the spoiler. Overall it is a really great car and I would very much appreciate the ability to have an option that enables me to apply that rear spoiler.

**Comment by No-Yes1** [comment]
Page up -> it's one of the options
