### ISSUE TITLE
2004 Mustang Cobra

### ISSUE THREAD

**Issue by Zoraketh** [fkk-cz/noire_vehicles#896]
The cosmetics body parts are for the wrong car or body kit is messed. I believe it is showing customization for s550. It breaks the car if you swap to one of them and sends you into the ground.
![image](https://user-images.githubusercontent.com/92574732/155234225-5d5c04c8-d8a4-47ea-ab14-6721cd533e7b.png)
![image](https://user-images.githubusercontent.com/92574732/155234333-6696e61f-4896-46ef-9361-93086ee2881d.png)
![image](https://user-images.githubusercontent.com/92574732/155234385-bce12316-bbb9-4aac-b986-ee5011c5b78d.png)
![image](https://user-images.githubusercontent.com/92574732/155234417-c1223ea9-b560-436b-b610-5d92c9671341.png)
![image](https://user-images.githubusercontent.com/92574732/155234526-51d599a9-7a6d-4981-9141-b8aa9c41f9d2.png)
Starts looking like this after a few seconds of changing the cosmetics

**Comment by Zoraketh** [comment]
![image](https://user-images.githubusercontent.com/92574732/155234333-6696e61f-4896-46ef-9361-93086ee2881d.png)
![image](https://user-images.githubusercontent.com/92574732/155234385-bce12316-bbb9-4aac-b986-ee5011c5b78d.png)
![image](https://user-images.githubusercontent.com/92574732/155234417-c1223ea9-b560-436b-b610-5d92c9671341.png)

**Comment by No-Yes1** [comment]
Has this always been an issue, do you know? Or is this recently?

**Comment by Zoraketh** [comment]
I am unaware, just bought it the day I posted this.

**Comment by No-Yes1** [comment]
Interesting, Might be worth maybe just removing all the cosmetics upgrades then. I'll take a deeper look

**Comment by fkk-cz** [comment]
This seems like a model issue. Added the vehicle to the recall list.
