### ISSUE TITLE
Lambo Sesto Elemento

### ISSUE THREAD

**Issue by Archerr95** [fkk-cz/noire_vehicles#897]
this gorgeous creation currently tops out at 130 mph without traction control, and it takes an age to get there. this car is "supposed" to do a 0-60 in 2.5 seconds and 0-100 in 8 seconds, all the way up to 214. the car looks and sounds STUNNING, i just really want a reason to buy it please <3

**Comment by No-Yes1** [comment]
Fixed in https://github.com/fkk-cz/noire_vehicles/commit/a0105acd2b4988bbbea58a9aebe066c6581aed16. Please wait for a few days for this to merge.
