### ISSUE TITLE
Jaguar XJ220 could do with a nice v12 sound 

### ISSUE THREAD

**Issue by recruit2212** [fkk-cz/noire_vehicles#898]
https://www.gta5-mods.com/vehicles/aston-martin-5-9-v12-engine-sound-oiv-add-on-fivem-sound i know this is for Aston martins but its the closest thing i can find for British engine sounds.

**Comment by No-Yes1** [comment]
Fixed in https://github.com/fkk-cz/noire_vehicles/commit/798eac58da7d1697ff4d6e61fe32954f904144f5. Please wait for a few days for this to merge live.
