### ISSUE TITLE
Mercedes S63 AMG - Sound issue

### ISSUE THREAD

**Issue by No-Yes1** [fkk-cz/noire_vehicles#899]
No sound on this vehicle.

**Comment by No-Yes1** [comment]
Also, no upgrades.

**Comment by Reefeid** [comment]
Upgrades are available now . Audio/Sound is still not fixed . Pulling up with a silent car is deadly on the streets 🤪🤪

**Comment by Reefeid** [comment]
hello , just wanted to check if the audio has been fixed .

**Comment by No-Yes1** [comment]
https://github.com/fkk-cz/noire_vehicles/commit/06428bcc1c3ff4c6945d34f49ffc643c3f3b38d6
