### ISSUE TITLE
Jaguar XJ220 / Aston Martin is silent after audio change.

### ISSUE THREAD

**Issue by recruit2212** [fkk-cz/noire_vehicles#900]
The car is dead silent now but I'm guessing it was due to the sound change which must of bugged out or something?

**Comment by Reefeid** [comment]
add the ASTON MARTIN to this as well. i guess both have the same files.

**Comment by Reefeid** [comment]
still no sound on aston , it will be fixed after tommorows restart ?

**Comment by No-Yes1** [comment]
This should be fixed by server restart.

**Comment by No-Yes1** [comment]
Just to confirm this has now been fixed.
