### ISSUE TITLE
2013 Aston Martin Vanquish No Sound

### ISSUE THREAD

**Issue by viigyD** [fkk-cz/noire_vehicles#906]
Commit 798eac5 on Feb 28th for a custom audio hash for "Jaguar+Aston Martin" caused the 2013 Aston Martin Vanquish to not have any sound at all (no engine noise, no tire squealing, no horn, etc). I'm not sure if other vehicles involved in this tweak also suffer the same issue, but the 2013 Aston Martin has been confirmed by multiple owners to not have a functioning audio hash. [Here's a clip for reference](https://www.twitch.tv/videos/1418132249)

**Comment by No-Yes1** [comment]
Merging with an already existing issue #900
