### ISSUE TITLE
2020 Jeep Gladiator Small Trailer Support

### ISSUE THREAD

**Issue by Chitowndevil21** [fkk-cz/noire_vehicles#908]
Thanks for adding this, love it so far. Just wondering if there is anyway to give it small trailer support, I think it would look sick pulling a trailer.

**Comment by No-Yes1** [comment]
Fixed in https://github.com/fkk-cz/noire_vehicles/commit/e0703e8c7e284a75cfa0a9c06a3959a87442793c. Please wait for a few days for this to merge live.
