### ISSUE TITLE
Buff bmw m8 supporter car 

### ISSUE THREAD

**Issue by Ahy-jason-todd** [fkk-cz/noire_vehicles#91]
Bmw m8 supporter car acceleration is a bit worse than the bmw 8 in pdm handling too if possible please fix and buff acceleration to at least the same level as the regular pdm bmw m8 or better thank you if anything make the car a little bit more expensive

**Comment by fkk-cz** [comment]
changed, uses the same handling as the PDM m8

https://github.com/fkk-cz/noire_vehicles/commit/7fff78934425d7e2888bdc662451d68715ec21c9#diff-9637c2777ff83e60066118bee032a8fe6674835a2ad18c1e4a513a4d3959defd
