### ISSUE TITLE
The Corvette sounds like ass 😂 

### ISSUE THREAD

**Issue by tythetanman** [fkk-cz/noire_vehicles#911]
https://www.gta5-mods.com/vehicles/chevrolet-corvette-camaro-lt4-engine-sound

Helping that out.

**Comment by No-Yes1** [comment]
Which Corvette?

**Comment by tythetanman** [comment]
C8 stingray

**Comment by tythetanman** [comment]
2020

**Comment by No-Yes1** [comment]
That audio hash is for a Camaro, p. sure we already have a Camaro audio hash, might as well add the c8 onto that.

**Comment by No-Yes1** [comment]
Fixed in https://github.com/fkk-cz/noire_vehicles/commit/053a2ab2434b79f18cbf43f158c2692c9da317bb. Please wait for a few days for this to merge live.
