### ISSUE TITLE
Lotus Evija

### ISSUE THREAD

**Issue by Cobby1-89** [fkk-cz/noire_vehicles#914]
was wondering since there is only on in here, could i increase the speed a lil over 210 mph, due to 1) it being a 2.3 mill car, and 2) dodge challengers are just whizzing right by me and they are a huge difference in price. I also was wondering if the brakes could be tightened up so im not driving a slip-n-slide. I spoke to bobby and zack, and they just said to put this info in here. thanks guys.

**Comment by No-Yes1** [comment]
Fixed in https://github.com/fkk-cz/noire_vehicles/commit/9193ed5613c059f74a3b6da65ed87977aad2f1fa. Please wait for a few days for this to merge live.
