### ISSUE TITLE
2000 Ford F-350 Super Duty

### ISSUE THREAD

**Issue by 19Link87** [fkk-cz/noire_vehicles#916]
The truck appears to have both a gooseneck and a ball hitch, yet the ball hitch doesn't work. Is there any way to make both work, or have it optioned in Los Santos Customs to be one or the other?

**Comment by No-Yes1** [comment]
Commited a change to allow the F-350 to tow the small trailer. https://github.com/fkk-cz/noire_vehicles/commit/4b687de188903e90e19bdfe04afaff19b1af2e08. Please wait for a few days for this to merge live.
