### ISSUE TITLE
Bug on Dingy 4s Boat 

### ISSUE THREAD

**Issue by TheBigEgo** [fkk-cz/noire_vehicles#918]
The Dinghy 4s boat has 4 seats but only 2 people are able to sit even when using 3rd eye nothing worked. When you hold F to let engine run with music  playing there is no sound outside of the seat. It spudders like it's out of fuel and does not want to drive. We went and bought Jerry cans to fill and it spent 2k on that alone and we repaired it 3 times and still spudders. If it can be fixed I would love to continue using it to fish. If the issue is not resolved is there a way I can get the full refund of said Dingy 4s as it was 155k.

**Comment by No-Yes1** [comment]
Apologies in the delay of response on this -- i can't remember if the r* Dingy is a 4 seater?

**Comment by No-Yes1** [comment]
i.e only gtao/gtasp

**Comment by somedudenamedrush** [comment]
suntrap is the only one that seats 4 atm

**Comment by No-Yes1** [comment]
Attempted a possible fix to it, by swapping the layout to ``LAYOUT_BOAT_SUNTRAP``  https://github.com/fkk-cz/noire_vehicles/commit/aee07c265c442ded8dd353cd3aadde0c5199ccac. Will leave this open until it gets merged to see if it effects anything.

**Comment by No-Yes1** [comment]
Disregard, there was errors regarding this, due to r* limitations, we can not change the layouts to boats etc etc sadly.
