### ISSUE TITLE
McLaren Senna Proper sound and a possible speed increase. 

### ISSUE THREAD

**Issue by tythetanman** [fkk-cz/noire_vehicles#919]
McLaren Senna Proper sound and a possible speed increase.  Please 

https://www.gta5-mods.com/vehicles/mclaren-senna-m840tr-engine-sound-mod-wip

**Comment by tythetanman** [comment]
230 top speed if possible.

**Comment by No-Yes1** [comment]
Changed in https://github.com/fkk-cz/noire_vehicles/commit/da4a5951ae009b48ddc60db663c311900230af4b. Please wait for a few days for this to merge live.

>230 top speed if possible.

We're not buffing the top speed to something less then 1m to that.
