### ISSUE TITLE
Aston Martin Vantage 2019 sound 

### ISSUE THREAD

**Issue by tythetanman** [fkk-cz/noire_vehicles#920]
https://www.gta5-mods.com/vehicles/aston-martin-5-9-v12-engine-sound-oiv-add-on-fivem-sound

**Comment by No-Yes1** [comment]
Changed in https://github.com/fkk-cz/noire_vehicles/commit/06e708a122c45c2828da423238bd0469a4602edf. Please wait for a few days for this to merge live.
