### ISSUE TITLE
2015 Dodge RAM 2500 Lost All Upgrades

### ISSUE THREAD

**Issue by Chitowndevil21** [fkk-cz/noire_vehicles#925]
For some reason this vehicle has lost all its upgrades.  It had them at the time I purchased it from PDM and now all the upgrades i installed are gone & cannot be repurchased from modshop.

**Comment by No-Yes1** [comment]
Fixed in https://github.com/fkk-cz/noire_vehicles/commit/728b6ad96ab504914801953da7bfbb42d13788c1. Please wait for a few days for this to merge live.
