### ISSUE TITLE
McLaren Senna sound 

### ISSUE THREAD

**Issue by tythetanman** [fkk-cz/noire_vehicles#926]
The McLaren senna got a  sound upgrade but I think something happened while it was being added it now does not have its old sound or the new one it’s no sound at all.

**Comment by TdotG** [comment]
Ya I can also confirm there’s no sound at all. No tire sound, no engine sound. No sound at all.

**Comment by tythetanman** [comment]
Check in it a couple hours ago. Full works now for
The Senna sound.

**Comment by TdotG** [comment]
Ya it’s insane I saw
