### ISSUE TITLE
1999 Dodge Viper shows Null in garage

### ISSUE THREAD

**Issue by Chitowndevil21** [fkk-cz/noire_vehicles#927]
I seen that some of the other Null vehicles where fixed, was wondering if this one could be fixed as well.

**Comment by No-Yes1** [comment]
Fixed in https://github.com/fkk-cz/noire_vehicles/commit/c323eca0a6cb2caa4a4f6858558af8e32a4bf99f. Please wait for a few days for this to merge live.
