### ISSUE TITLE
Ram trucks sound update

### ISSUE THREAD

**Issue by NikeXpert** [fkk-cz/noire_vehicles#928]
2010 Ram 3500 Dually (non-supporter)

https://www.gta5-mods.com/vehicles/cummins-b-series-engine-sound-oiv-addon-fivem

2015 Ram 2500 (supporter) 

https://www.gta5-mods.com/vehicles/dodge-ram-cummins-5-9-isb-i6-engine-sound-oiv-add-on-fivem-sound

**Comment by No-Yes1** [comment]
> 2010 Ram 3500 Dually (non-supporter)

https://github.com/fkk-cz/noire_vehicles/commit/c343f6707137d19440ecb6d42cf6b77925ec8b29.

> 2015 Ram 2500 (supporter)

https://github.com/fkk-cz/noire_vehicles/commit/619388133085f46a5742a04b1d8ed1204c971ca6

Please wait for a few days for this to merge live.
