### ISSUE TITLE
Ferrari F8 Tributo sounds

### ISSUE THREAD

**Issue by phxsec** [fkk-cz/noire_vehicles#93]
the F8T just has the generic gta 5 vanilla cheetah sounds, not sure if this is an sound script or handling https://www.gta5-mods.com/vehicles/handling-and-sounds-2017-ferrari-j50
or there is this one if it doesnt work 
https://www.gta5-mods.com/vehicles/ferrari-laferrari-aperta-2017-handling-and-sounds

**Comment by DankGrandma** [comment]
most of these custom sounds don't seem to work on FiveM. audioNameHash TYRUS might sound better and MONSTER3 is a good one too

**Comment by fkk-cz** [comment]
not FiveM compatible, I need the .awcs
