### ISSUE TITLE
2001 Corvette C5 Buff

### ISSUE THREAD

**Issue by Chitowndevil21** [fkk-cz/noire_vehicles#931]
This car is supposed to be a Z06....it is in need of a buff & the handling is horrible. Better acceleration & top speed, tighter handling please if it can be done.

**Comment by No-Yes1** [comment]
Fixed in https://github.com/fkk-cz/noire_vehicles/commit/ed4bfcda3ce30e00405c9ff27aac4e8651a80f03. Please wait for a few days for this to merge live.
