### ISSUE TITLE
2019 Ferrari 488 Pista

### ISSUE THREAD

**Issue by westkanye** [fkk-cz/noire_vehicles#932]
The 2019 Ferrari 488 Pista need a speed increase, DSC OFF it tops 175 mph, DSC ON it tops 140 mph. This car IRL does 0-60 in 2.7 seconds and has 720hp, and Top Speed is 219mph. Please increase and thank you.
https://www.youtube.com/watch?v=5bpB_QbM0bk&t=70s

**Comment by No-Yes1** [comment]
Fixed in https://github.com/fkk-cz/noire_vehicles/commit/766cde9366707473d93c5b8a8c7068199cfe9005. Please wait for a few days for this to merge live.
