### ISSUE TITLE
1966 Ford F-100, Off Road (Invincible / Beefy As Fuck)

### ISSUE THREAD

**Issue by okxeon** [fkk-cz/noire_vehicles#936]
This vehicle is either invincible or has some serious damage multiplier problems. The guy who was driving it flipped it numerous times after ramping it off cliffs and the tires would not get shot out. When the chase ended we tested tire shots point blank and it was bullet proof. Take a look at it and if its fine then the guy who was driving it was just cheating.

**Comment by No-Yes1** [comment]
![image](https://user-images.githubusercontent.com/79383480/159754588-3c4f007d-4459-4406-9783-120864b57de3.png)

Just tested this, Vehicle damages as well as the average vehicle?
