### ISSUE TITLE
Karin Sultan Classic Fuel Drain/clogged injectors

### ISSUE THREAD

**Issue by ClutchRR** [fkk-cz/noire_vehicles#937]
Burns too much fuel, from mining entrance to sandy garage = uses 6-7 fuel vs 3-4 on other car tests.
Please increase the efficiency of the fuel injectors.

Make it not slow down as much soon as we take our foot off the gas. (feels like wind resistance, or as if its in gear) Best i can describe this, as if you drive a manual, and are in gear, let off the gas, and lightly break.  Let the car roll more.

**Comment by No-Yes1** [comment]
The efficiently comes down to the vehicle type. We're not editing/changing the vehicle class's of vanilla/tuner vehicles.
