### ISSUE TITLE
2017 Dodge RAM 1500 TRX Lost Upgrades

### ISSUE THREAD

**Issue by Chitowndevil21** [fkk-cz/noire_vehicles#939]
This vehicle has lost all of its upgrades. Had them when I purchased now all the upgrades I installed are gone and do not appear in mod shop.

**Comment by No-Yes1** [comment]
Fixed in https://github.com/fkk-cz/noire_vehicles/commit/d9131e39df7cc31643dd65c67a80ec7bd0c4ef06. Please wait for a few days for this to merge live.
