### ISSUE TITLE
Ferrari 430 Scuderia sound / rework ?

### ISSUE THREAD

**Issue by crackplug** [fkk-cz/noire_vehicles#94]
I talked with the guy who got it added to the server before I bought it, and he heavily advised me not to, had nothing good to say about it. Bought it anyways :D. Its got the default cheetah sound and most shit thats 700k+ has way more to offer. Could you guys take the sound from https://www.gta5-mods.com/vehicles/ferrari-f430-scuderia-spider-16m-2009 and put it on? If not could you swap the model as a whole?

**Comment by crackplug** [comment]
Also if you could turn the accel up abit? Im getting smoked by teslas and this thing is an actual racecar

**Comment by DankGrandma** [comment]
audioNameHash TYRUS should sound better than the CARBONIZZARE

fInitialDragCoeff value from 3.5 to 2.5 or 2 should help
