### ISSUE TITLE
Mercedes E63 AMG Issues

### ISSUE THREAD

**Issue by Jolliboy** [fkk-cz/noire_vehicles#940]
Hello, I was the one who asked to have the Mercedes E63 AMG added into the game. I have noted some issues with this particular vehicle that I would like to be addressed. 

Firstly, there is no sound at all, whether that be tire screeching, engine sound, car doors, radio, etc. The gta5-mods.com website states that this vehicle should have a custom sound (https://www.gta5-mods.com/vehicles/mercedes-benz-e63-s-amg-add-on-lod-s-tuning-sound#description_tab) 

Secondly, fully upgraded, this vehicle only reaches  ~146mph (with dsc on) and ~168mph (with dsc off). In real life, this car in its stock form is able to reach 186mph+ With it being fully upgraded, I would assume this vehicle can easily pass the 200mph+ mark. The closest comparison I personally experienced would be the 2010 E60 BMW M5, fully upgraded that vehicle could hit 200mph+

**Comment by No-Yes1** [comment]
We're not doing vehicle handling tweaks to that high amount, unless the vehicle is actually low, 168 is decent for the price. Fixed the audio hash: https://github.com/fkk-cz/noire_vehicles/commit/93768f1f1830ad648ddfd6860125791c4316727d. Please wait for a few days for this to merge live.
