### ISSUE TITLE
2021 RAM TRX made out of paper

### ISSUE THREAD

**Issue by TdotG** [fkk-cz/noire_vehicles#941]
So i just got the 2021 Ram TRX and right away i noticed the car would break down extremely easily, even from hitting simple stop signs/road signs the car just instantly goes down to yellow health and breaks down. Please raise the health for the truck since its extremely weak

**Comment by No-Yes1** [comment]
Fixed in https://github.com/fkk-cz/noire_vehicles/commit/72de239b869ab624105ee2384d1cc79dac76794f. Please wait for a few days for this to merge live.
