### ISSUE TITLE
porsche taycan (handling)

### ISSUE THREAD

**Issue by IsaacGucci** [fkk-cz/noire_vehicles#943]
The Porsche taycan (ev) handles like a boat witch is unrealistic because it is a sorts car it has a lot of technology to help it handle better then most cars here are some examples- Rear axle steering, Adaptive air suspension, Porsche Dynamic Chassis Control, Porsche Active Aerodynamics, And Porsche Torque Vectoring Plus all to help it handle like a Porsche So I think the handling sounds reflect in the city and be a lot better then it is now 

All the info I got was pulled from Porsche website here is the like 

https://newsroom.porsche.com/dam/jcr:93483663-c12b-43ca-98f5-b1b8b845e321/PAG_Taycan_Technology_PM_EN.pdf.PDF

**Comment by No-Yes1** [comment]
Fixed in https://github.com/fkk-cz/noire_vehicles/commit/0c9543b7215ad7e678065fbf6b85d868572f519d. Please wait for a few days for this to merge live.
