### ISSUE TITLE
2019 Ferrari 488 Pista Speed

### ISSUE THREAD

**Issue by Jolliboy** [fkk-cz/noire_vehicles#946]
Hello, the 2019 Ferrari 488 Pista tops out at ~160mph. Realistically, the car reaches 211mph in its stock form. 

The closest comparison to this vehicle (which also happens to already be in the game) is the McLaren 720S. Both cars have almost identical performance specs (exactly the same horsepower and torque, 0-60, 0-100, 1/4 mile time). In the game the McLaren 720S is much faster than the Ferrari 488 Pista. 

I am asking for the performance (acceleration & top speed) of the 2019 Ferrari 488 Pista to be exactly the same as the Mclaren 720S is in-game. I believe this request is reasonable. 

Here are some links (scroll down to the bottom of the page to where it shows the performance specs) to compare both cars. 
McLaren 720S: https://www.caranddriver.com/reviews/a15093417/2018-mclaren-720s-first-drive-review/
Ferrari 488 Pista: https://www.caranddriver.com/reviews/a21238149/2019-ferrari-488-pista-first-drive-review/

**Comment by No-Yes1** [comment]
I already tweaked the pista speed a little bit (21/03) https://github.com/fkk-cz/noire_vehicles/commit/766cde9366707473d93c5b8a8c7068199cfe9005. We're not going to keep continuing to tweak vehicles unless they are broken. The vehicle is meant to go 190 mph? I've just tested this vehicle and watched it go actually a decent acceleration. the vehicle is fine and does not need to be tweaked.
