### ISSUE TITLE
2021 911 Turbo S

### ISSUE THREAD

**Issue by TdotG** [fkk-cz/noire_vehicles#947]
So I just test drove the 2021 Turbo S and it was super underwhelming. The 911 Turbo S IRL hits 0-60 in less than 2.5 seconds and tops out at 205. The car stock in-game hits 170 barely in a test drive. Im suggesting it gets a speed and acceleration buff. The handling is def on point but the speed and acceleration is poor. I would suggest the top speed gets buffed to like 190-200 stock and then 210-220 at least when fully upgraded. There are tuned versions IRL that get to 60mph in less than 2 seconds and hit over 200 easily.

**Comment by No-Yes1** [comment]
it's a 300K vehicle, 170 is a good speed for the vehicle. We're not making small tweaks like this. I've increased the acceleration slightly for the vehicle (https://github.com/fkk-cz/noire_vehicles/commit/1479fbf8faae6b2cc3a60aa6f9e1c2a0d35ff2c4). Please wait for a few days for this to merge live.
