### ISSUE TITLE
Nissan Titan

### ISSUE THREAD

**Issue by LethalTrade** [fkk-cz/noire_vehicles#948]
the video speaks for itself.
https://medal.tv/games/gta-v/clips/gd9Cv6r1odnie/d1337A7U4jT9?invite=cr-MSw2QUYsMzM0MzM3NTMs

**Comment by No-Yes1** [comment]
Just checked the values/flags of this vehicle - it doesn't state it being bulletproof/doesn't break down. I also tested this in-game (see attached clips):

Breaking down: https://streamable.com/tfi1ox
bullets damaging vehicle: https://streamable.com/pjekvz.

Not sure what the entire cause of this is, I have attempted a fix on it by removing a certain vehicle flag. https://github.com/fkk-cz/noire_vehicles/commit/6a50da585559691a6d500a17b5e1328fd473f8dd.
