### ISSUE TITLE
2016 Charger Hellcat issue

### ISSUE THREAD

**Issue by EncrustMust** [fkk-cz/noire_vehicles#949]
The rear lights are still insanely bright and textures are still broken even though the ticket was closed

https://steamuserimages-a.akamaihd.net/ugc/1826780348841542505/98F4644396625BE6015D681689955D085F439C2D/?imw=5000&imh=5000&ima=fit&impolicy=Letterbox&imcolor=%23000000&letterbox=false

**Comment by No-Yes1** [comment]
#903 Already an existing isuse.
