### ISSUE TITLE
1958 Plymouth Belvedere (Supporter)

### ISSUE THREAD

**Issue by 19Link87** [fkk-cz/noire_vehicles#950]
The 1958 Belvedere cannot be painted, other than pearlescent. Is that something you guys can change or is that something with the mod author?

**Comment by fkk-cz** [comment]
This vehicle's carvariations.meta should allow for paint changes, probably an issue with the livery/textures.

https://github.com/fkk-cz/noire_vehicles/blob/master/DATA/plymouth58_data/carvariations.meta
