### ISSUE TITLE
1970 Dodge Charger RT Texture Issues

### ISSUE THREAD

**Issue by Chitowndevil21** [fkk-cz/noire_vehicles#952]
This car has issues with red textures.  The taillights, badging, grill & blower all look screwed up. 
![1970 Charger RT 1](https://user-images.githubusercontent.com/93257343/161379057-df7a311f-c5aa-45dc-a412-8ce249f5525e.jpg)
#
![1970 Charger RT 2](https://user-images.githubusercontent.com/93257343/161379066-b231b1e5-cbb0-4e11-bae3-74f9f7346938.jpg)
![1970 Charger RT 3](https://user-images.githubusercontent.com/93257343/161379086-b879c528-b297-41eb-82e1-8cca3a1412cd.jpg)
![1970 Charger RT 4](https://user-images.githubusercontent.com/93257343/161379092-bf53b063-5ac9-4478-9e8c-2806ade7ae8b.jpg)
![1970 Charger RT 5](https://user-images.githubusercontent.com/93257343/161379095-8760ee44-1ad4-4b63-b943-a5d00ad43885.jpg)

**Comment by No-Yes1** [comment]
I would put this in #888 as this is a direct issue relating to all textural issue on vehicles.
