### ISSUE TITLE
2000 Mustang 2 OP

### ISSUE THREAD

**Issue by Yush6969** [fkk-cz/noire_vehicles#953]
Wagwan G, Mandem has seen this shitty arse 2000 mustang go 2 fast killy. This shit goes like 250 even tho its shit and cheap. nerf it bruv, these pussios on the street book it to the highway and call it a day.

**Comment by No-Yes1** [comment]
Wagwan my drilla, is it this vehicle? 
![](https://img.gta5-mods.com/q95/images/2000-ford-mustang-saleen/687390-PGTA5117615174.jpg)

**Comment by No-Yes1** [comment]
Fixed in https://github.com/fkk-cz/noire_vehicles/commit/64c577fb8a57406358f4d2aca781bbfcd82fc219. Please wait for a few days for this to merge live.
