### ISSUE TITLE
acceleration and speed buff for Buggatti Bollide 2020

### ISSUE THREAD

**Issue by sirgold1** [fkk-cz/noire_vehicles#955]
This car is a support a creator and costs half a million dollars. The quality of the car does not reflect on its irl counterpart at all. Simply does not make sense how cars that are 100k or less are able to accelerate faster and reach a higher top speed. Will appreciate a buff. You would think a car that doesn't even have a trunk would have its focus on speed.

thanks for your time and consideration.

**Comment by No-Yes1** [comment]
many people have the bolide, buffing it anymore will lead to people using it as a meta for robberies, esp. for the price... It should really be increase to 1/2m. I'll do a final tweak on the accel. https://github.com/fkk-cz/noire_vehicles/commit/cc9f0f82d6c980371a313515df16acfa68fcf594. Please wait for a few days for this to merge live.
