### ISSUE TITLE
Lamborghini Huracan EVO Armor and Upgrades 

### ISSUE THREAD

**Issue by tythetanman** [fkk-cz/noire_vehicles#961]
The Lamborghini Huracan EVO that’s priced at 1.1 million has very low grade armor for its rate of speed and value. Looking to see if that armor can be increased (without its top speed decreased, OR if that can be raised a little to balance out the potential drop in speed that could be heavy from the armor)

Just looking to see based off of the price tag on the car on what can be enhanced for the upgrades.

**Comment by No-Yes1** [comment]
Fixed in https://github.com/fkk-cz/noire_vehicles/commit/a87700ee836281ff778c5a45f63bbc58599700c6. Please wait for a few days for this to merge live.
