### ISSUE TITLE
Bentley Continental Supersport 

### ISSUE THREAD

**Issue by GunnaWunnaa** [fkk-cz/noire_vehicles#962]
I have just purchased this Bentley and was surprised to see that the top speed is very underwhelming. I would have expected to supersport version which is almost 200k more than the original to go atleast 200 or have a decent acceleration. For an almost 500k car I dont think the speed and acceleration are worth it. I have also never seen anyone have this car and I think I can understand why but I think buffing this car would add alot of diversity to the cars citizens own. I always see people driving the same 5 cheap and overpowered cars. The top speed now is 150 and really struggles to go past that. I would like to request a speed increase to atleast 200 please or to whatever you see fit. And also when testing the car at the dealership the car has a wing that looks really cool but I am unable to add it on at the customization place, would really appreciate this added as well! Thank you for taking the time to read this request and thank you for developing this amazing server. 

![image](https://user-images.githubusercontent.com/82933557/162607504-ae93c249-fc42-415e-93b7-8e9e4295b56b.png)

![image](https://user-images.githubusercontent.com/82933557/162607535-eef4d665-9c0c-446a-9a42-8b339885fcb9.png)

**Comment by GunnaWunnaa** [comment]
And could you also add traction control since it is a sports version

**Comment by No-Yes1** [comment]
Re: the spoiler, you can enable that with page up

**Comment by No-Yes1** [comment]
Buffed top speed slightly: https://github.com/fkk-cz/noire_vehicles/commit/71ecb3ad9053df46c5d7ba3e0798dd555b66abcc. 

> And could you also add traction control since it is a sports version

Done: https://github.com/fkk-cz/noire_vehicles/commit/263ca65e314ce841858b9f4471cb8df3ac859fd3.

Please wait for a few days for this to merge live.
