### ISSUE TITLE
Tesla Roadster 

### ISSUE THREAD

**Issue by murad532** [fkk-cz/noire_vehicles#963]
As a owner of all the tesla models in the game im a strong advocate for electric vehicle's and going green. i recently added the roadster to my electric fleet and was kind of astonished by a few things that left me confused. firstly any upgrades done to the vehicle don't reflect onto the vehicle (Ex. Purchasing armor doesn't make the roadster any more tough, purchasing tints for the windows are not available and etc. ) Secondly, the vehicle has no sense of armor, even though it was "upgraded" in the shop which same can be said for its transmission and engine that don't reflect on the speed of the vehicle. I know the vehicle only costs 200k and there are other vehicles that cost more that might need more attention but I beg "Electric vehicle lives matter". I write this in frustration from being shot at once and the car breaking down on me. to not being able to start the vehicle at times when I need to drive(will start clipping these incidents as proof from now on).  Thank you and I greatly appreciate your time.

**Comment by No-Yes1** [comment]
the reason for no upgrades as it's an electric vehicle i'm guessing, or it's a model issue. The carcols/carvariations files look fine. As for the armour, I have tweaked this in https://github.com/fkk-cz/noire_vehicles/commit/9d784186c0926f6868932a2b99d45d6d49f5dce6. Please wait for a few days for this to merge live.
