### ISSUE TITLE
2022 BMW M5 Competition Speed & Acceleration 

### ISSUE THREAD

**Issue by Chitowndevil21** [fkk-cz/noire_vehicles#965]
This car needs some love!!!  This thing gets stomped by the M4, that should not be. Just looking some speed & acceleration increases so this Competition can be competitive...LOL!!!

**Comment by No-Yes1** [comment]
Please refer to a prior issue: https://github.com/fkk-cz/noire_vehicles/issues/934. People were using this vehicle as a meta, so it will not be tweaked
