### ISSUE TITLE
92 Q4 Tipping Problem

### ISSUE THREAD

**Issue by gxdsent** [fkk-cz/noire_vehicles#966]
The recent 92 Alfa Romeo Q4 put in has a tipping problem if it takes turns at certain speeds without brakes. That’s the only thing happening, everything else seems fine besides little things here and there that’s tolerable.

**Comment by No-Yes1** [comment]
@gxdsent has this been fixed?

**Comment by gxdsent** [comment]
@No-Yes1 will test when i get home from work. about 4 hours from now i’ll come back with the answers

**Comment by No-Yes1** [comment]
Amazing 😄
