### ISSUE TITLE
Mustang Upgrades and Cosmetics Vanished 

### ISSUE THREAD

**Issue by KnightHawk12** [fkk-cz/noire_vehicles#967]
I logged into the server today to find all my upgrades missing and when i went to go put them back on the mechanic shops don't even give you an option. just like it all vanished within a day

**Comment by No-Yes1** [comment]
Which mustang?

**Comment by KnightHawk12** [comment]
The mustang GT non subscribers vehicle

**Comment by No-Yes1** [comment]
Fixed in https://github.com/fkk-cz/noire_vehicles/commit/c9b4e4fa9ca855f152578eebe93640826e3a44c8. Please wait for a few days for this to merge live.
