### ISSUE TITLE
$350,000 Supra

### ISSUE THREAD

**Issue by Stagonium** [fkk-cz/noire_vehicles#969]
The 350k supporter Supra that has the cool lighting on it, doesn't have any working sound. Horns make no noise, engine makes no noise, tires make no noise. Hopefully its a quick/easy fix

**Comment by No-Yes1** [comment]
https://github.com/fkk-cz/noire_vehicles/commit/8105b077ddccda94ecebceb2fae7ea86fa3ff8ed
