### ISSUE TITLE
1996 Nissan Skyline Gt-R

### ISSUE THREAD

**Issue by EncrustMust** [fkk-cz/noire_vehicles#973]
The headlights point backwards instead of forward
When going through the customizations it breaks and bricks the car
https://steamuserimages-a.akamaihd.net/ugc/1832410963635275176/5440297CE415E632D79592561C940C20F08EE053/?imw=5000&imh=5000&ima=fit&impolicy=Letterbox&imcolor=%23000000&letterbox=false

**Comment by gxdsent** [comment]
whoever made the model reversed some parts of the car that cant be fixed by these guys unfortunately. this issue was brought up previously by a few people including myself

**Comment by No-Yes1** [comment]
See above -- I've already attempted to look at this, I might just have to cancel all customizations for this car as the model is fucked. I'll take a look

**Comment by EncrustMust** [comment]
Ohh, i didnt know this was an existing issue, quite surprised the creator released that car with it being as broken as it is

**Comment by EncrustMust** [comment]
It will forever blow my mind ^

**Comment by fkk-cz** [comment]
This is a model issue that cannot be easily fixed. Probably should discontinue/recall this vehicle.
