### ISSUE TITLE
Just some cars that don’t have dsc

### ISSUE THREAD

**Issue by EncrustMust** [fkk-cz/noire_vehicles#977]
Just some cars that I think should have traction control (DSC) based on the cars that do

-Audi S5 Liberty Walk
-Nissan Silvia S15 RB
-BMW M3 E92 GTS
-Audi RS5 Libertywalk
-1992 BMW M3 E36
-2003 BMW M5
-2019 BMW M5 F90
-2018 Honda Civic R FK8
-2013 Hyundai Genesis RB
-2009 Cadillac CTS-V
-2010 Cadillac CTS Sport Wagon
-2016 Cadillac CTS-V

**Comment by No-Yes1** [comment]
> -2019 BMW M5 F90

Already did this one recently

**Comment by No-Yes1** [comment]
Done the list here: https://github.com/fkk-cz/noire_vehicles/commit/9a2e9470d87d36eec9ae660735e650a04823c85e. Please wait for a few days for this to merge live.
