### ISSUE TITLE
Rolls Royce Cullinan Black Badge 

### ISSUE THREAD

**Issue by akxbigboi** [fkk-cz/noire_vehicles#978]
Car has no upgrades besides turbo. Can't tint windows and can't add underglow to it. And when i bought it and tried to put it in the garage it says its wanted by the police? Can't unlock my car it won't let me get in keeps saying lock after i unlock it. Also can't put xeon lights on and horn.

**Comment by No-Yes1** [comment]
I've attempted to fix this a while back, this has a broken modkit, and even when changing the ID, it still does not work. https://github.com/fkk-cz/noire_vehicles/issues/675 / https://github.com/fkk-cz/noire_vehicles/issues/886. I'll try again w/ a different carcols/carvariations.meta files to see if that fixes it. I'll take a look & get back.

**Comment by akxbigboi** [comment]
thankyou also the back doors also dont close all the way when people hop out the back two doors

**Comment by No-Yes1** [comment]
> thankyou also the back doors also dont close all the way when people hop out the back two doors

That's a model issue/broken door more then likely

**Comment by No-Yes1** [comment]
Fixed both the ``cullinan`` and ``cullinan2``. https://github.com/fkk-cz/noire_vehicles/commit/e8e84f8b9797a63991d004d48f298b4a27d2165c / https://github.com/fkk-cz/noire_vehicles/commit/bb00bee567d8208dd0bf9df6992fe8ea826aa905. Leaving this open for when the commit gets merged.

**Comment by No-Yes1** [comment]
Update: The black badge can now can upgraded, for some reason the normal cullinan can't. I will take a look further but since the black badge can now be upgraded, I will close this issue.
