### ISSUE TITLE
BMW E60 M5 $95K

### ISSUE THREAD

**Issue by EncrustMust** [fkk-cz/noire_vehicles#980]
The audio of it is just insanely loud to where you can’t hear yourself think lmao

**Comment by No-Yes1** [comment]
this is an issue to most custom audio sound packs, do you have another sound in mind?

**Comment by EncrustMust** [comment]
I can’t really find an audio for the v10 M5 that isn’t insanely loud, so any of the other m5 audios in the city would work

**Comment by No-Yes1** [comment]
p. sure the rest of the m5's have the same audio hash -- can you provide an example of one that doesn't sound too loud?

**Comment by EncrustMust** [comment]
The 2018 BMW M5 non supporter isn’t too loud

**Comment by No-Yes1** [comment]
That uses this audio hash from a vanilla vehicle: https://github.com/fkk-cz/noire_vehicles/blob/71667405de1c7fe49eadc0acfaccc0564bef1483/DATA/m5_data/vehicles.meta#L18. I'll change it to that.
