### ISSUE TITLE
Viper Sound Mod

### ISSUE THREAD

**Issue by somedudenamedrush** [fkk-cz/noire_vehicles#981]
can the vipers get changed to this sound https://www.gta5-mods.com/vehicles/dodge-viper-v10-engine-sound-oiv-add-on-fivem

**Comment by No-Yes1** [comment]
What Viper(s)?

**Comment by somedudenamedrush** [comment]
All of them

**Comment by No-Yes1** [comment]
there is already a audio hash for the vipers: https://github.com/fkk-cz/noire_vehicles/blob/90c889d61f7e2ff8eb6d5db8c08bb3490bc2f57a/DATA/viper/vehicles.meta#L18.
