### ISSUE TITLE
Aston Martin Vanquish Zagato

### ISSUE THREAD

**Issue by TdotG** [fkk-cz/noire_vehicles#983]
Is there anyway you can make the gear ratio longer. It up shifts fine from 1-4 but fro, 4-7 it shifts way to much and maxes out the speed very quickly. It shifts so fast that it doesnt even feel like theres extra gears after 4. Also the rear taillights are glitching out.

**Comment by No-Yes1** [comment]
Fixed the gear ratio issue: https://github.com/fkk-cz/noire_vehicles/commit/eb561d76951263817a3fc71d98ff63abf184dc30. Leaving this open for the taillights issue.

**Comment by TdotG** [comment]
> Fixed the gear ratio issue: [eb561d7](https://github.com/fkk-cz/noire_vehicles/commit/eb561d76951263817a3fc71d98ff63abf184dc30). Leaving this open for the taillights issue.

The gear ratio was changed but it unfortunately skips from 6th to 8th gear.

**Comment by TdotG** [comment]
> > Fixed the gear ratio issue: [eb561d7](https://github.com/fkk-cz/noire_vehicles/commit/eb561d76951263817a3fc71d98ff63abf184dc30). Leaving this open for the taillights issue.
> 
> The gear ratio was changed but it unfortunately skips from 6th to 8th gear.

also i think its because of the upgrades. When i test drive it at PDM it goes to 7 smoothly upgraded it skips 7th gear and goes to 8th

**Comment by TdotG** [comment]
Is there anyway you can buff the top speed. The car is 500k and top speed wise it’s not up to par compared to its counterparts.
