### ISSUE TITLE
Jaguar I-Pace SUV Class

### ISSUE THREAD

**Issue by Chitowndevil21** [fkk-cz/noire_vehicles#984]
This car is clearly an SUV, shouldn't be in the Sports class. Can this vehicle be changed to SUV class please??

**Comment by No-Yes1** [comment]
Fixed in https://github.com/fkk-cz/noire_vehicles/commit/1c445088805787e625c3a3d62d5ad6125c327b6e. Please wait for a few days for this to merge live.
