### ISSUE TITLE
2022 Porsche Panamera turbo s 

### ISSUE THREAD

**Issue by Cruzamp** [fkk-cz/noire_vehicles#986]
It is way to slow to what it is, it should be able to hit 190-200mph. Irl it has 620 Hourse power. And it says the top speed irl is 196mph.  In the game it barely hits 130 mph. Also it should have traction control as well. This is suppose to be a fast suv irl. It should be faster than the trucks. But it’s not. It’s way to slow.

**Comment by fkk-cz** [comment]
Adjusted in https://github.com/fkk-cz/noire_vehicles/commit/11420d2189142f552d5a1007ff4176221e784234.
