### ISSUE TITLE
GTR R35 Overall Engine and car sound

### ISSUE THREAD

**Issue by Cozy5** [fkk-cz/noire_vehicles#988]
I bought the R35 about 4 months ago and it was a nice sounding car, it sounded like how the Viper sounds, like that kind of sound, not exact but close to it. I was wondering if anyone could switch it back? I don't think it fits well if an R35 has a stock GTA sound, thank you.

**Comment by No-Yes1** [comment]
The R35's audio hash was changed back in September, I'll switch it to the viper audio hash.

**Comment by No-Yes1** [comment]
https://github.com/fkk-cz/noire_vehicles/commit/3449ffd8b5797af87daf5a8b7a56a2ca4b741035. Please wait for a few days for this to merge live.
