### ISSUE TITLE
Bentley Continental Super Sport 

### ISSUE THREAD

**Issue by GunnaWunnaa** [fkk-cz/noire_vehicles#989]
I made a ticket about a week and a half ago about this car and I apologize if it just hasn't been added yet but nothing has been changed. I was wondering that maybe you buffed the other Bentley by mistake? If I am wrong please let me know. Thank you

**Comment by No-Yes1** [comment]
Apoligies, I did the wrong vehicle, https://github.com/fkk-cz/noire_vehicles/commit/ab54bb21131de4ef65ba99f1bcee5cf537d6b4e7. is the right one.
