### ISSUE TITLE
1993 Nissan skyline GT-R 

### ISSUE THREAD

**Issue by Cruzamp** [fkk-cz/noire_vehicles#990]
it is to slow, i know its a older year but the motor has the same horse power as the one year above it but in the city the r33 gt-r is way fast. i feel like the r32 should be the same speed as the r33 GT-R

**Comment by No-Yes1** [comment]
Fixed in https://github.com/fkk-cz/noire_vehicles/commit/eb805e15ed77febf576496c2bc88a51e484d891d. Please wait for a few days for this to merge live.
