### ISSUE TITLE
2020 Charger SRT Hellcat(New one)

### ISSUE THREAD

**Issue by TdotG** [fkk-cz/noire_vehicles#992]
One of my buddies just recently got the car added in to the city, unfortunately the car seems to be under the wrong vehicle class as it doesn’t have a traction control option. Tops out at 140-150. Can you please change the car class and give it a traction control option and buff the top speed.

**Comment by fkk-cz** [comment]
Adjusted in https://github.com/fkk-cz/noire_vehicles/commit/11420d2189142f552d5a1007ff4176221e784234. Vehicle now has DSC and should perform much better.
