### ISSUE TITLE
GM Bus from Vapid Dealer incorrect hitbox

### ISSUE THREAD

**Issue by 19Link87** [fkk-cz/noire_vehicles#995]
The hitbox on the GM bus is too tall, it extends about a foot higher than the roof of the bus, making it impossible to fit into my personal garage, an LS Customs, or anything just *slightly* too short, that the bus should realistically be able to make it into.

**Comment by No-Yes1** [comment]
This is an issue with all buses, due to r* logic, and can't actually be fixed.
