### ISSUE TITLE
Bugged Car Windows

### ISSUE THREAD

**Issue by PreacherDeimos** [fkk-cz/noire_vehicles#997]
Hey Bobby, it's been this way for a while, but I just never got around to reporting it as I didn't know if it was something I put in a ticket or not, but then I remembered GitHub was probably the best place.

My problem is the windows on one of my cars has a fucked up texture on the front windshield, back passenger windows, and the rear windshield, is this something you'd be able to fix boss man? Attached are pictures of where the texture mapping to the windows are fucked.

Front Window: https://cdn.discordapp.com/attachments/889302842672824351/967840259759030292/unknown.png
Rear Passenger: https://cdn.discordapp.com/attachments/889302842672824351/967840336393142292/unknown.png
Back Window: https://cdn.discordapp.com/attachments/889302842672824351/967840380672434296/unknown.png

Thank you for your time and effort.

-Preacher

**Comment by Artificial-IQ** [comment]
This vehicle's textures are currently not going to be worked on. Have a nice day.
