### ISSUE TITLE
2020 Audi A6 top speed & acceleration buff

### ISSUE THREAD

**Issue by Chitowndevil21** [fkk-cz/noire_vehicles#999]
OK I know I just added this car but it definitely needs some love. This thing struggles to hit 100mph & the acceleration could use an uplift. Just wondering if these could be tweaked??  Also could DSC be added as well??

**Comment by fkk-cz** [comment]
Adjusted in https://github.com/fkk-cz/noire_vehicles/commit/11420d2189142f552d5a1007ff4176221e784234. No DSC will be available for this vehicle, as it's considered a luxury (non-sports) car.
